grpc/grpc-java

rls/src/main/java/io/grpc/rls/RlsProtoConverters.java
rls/src/test/java/io/grpc/rls/RlsProtoConvertersTest.java

Reverts grpc/grpc-java#10397 as it makes Java inconsistent with the other languages.

Revert "Change the default for staleAge to be maxAge - 1 minute"

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

fix https://github.com/grpc/grpc-java/issues/10314
The deadlock can be reproduced with the UT in this change, and diff:
```
@@ -863,6 +870,12 @@ abstract class RetriableStream<ReqT> implements ClientStream {
headers.discardAll(GRPC_PREVIOUS_RPC_ATTEMPTS);
headers.put(GRPC_PREVIOUS_RPC_ATTEMPTS, String.valueOf(substream.previousAttemptCount));
}
+      try  {
+        Thread.sleep(500);
+      } catch (InterruptedException ex) {
+        log.log(Level.INFO, "nothing");
+      }
```
The issue was that two streams from two transports held their transport lock while waiting for the other, thus deadlock. In this particular case, what happens is that in one subListener.close() it creates a new substream on other transports that requires that transport thread. Meanwhile another …

core: fix retriablestream deadlock

---

buildscripts/kokoro/xds.sh

Backport of #9354 to v1.48.x.
---
Same as #9347, but for GCE framework too (xds and xds_v3 jobs).
PR #9269 probably pushed the build
b/238334438

xds: Allow Gradle to use more memory when building interop - GCE (v1.48.x backport)

---

core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

* Eliminate NPE by skipping further processing when stream is defined, but doesn't have a property for streamKey (header processing identified an error)
Backport of #10384

Handle header with errors and endStream = true (1.57.x backport)

---

core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

* Eliminate NPE by skipping further processing when stream is defined, but doesn't have a property for streamKey (header processing identified an error)
Fixes #10364
* Add unit test for missing content type

Handle header with errors and endStream = true (#10384)

---

binder/src/main/java/io/grpc/binder/SecurityPolicies.java
binder/src/test/java/io/grpc/binder/SecurityPoliciesTest.java

This is a port of internal cl/547560711

binder/test: Stop running Robolectric tests on APIs < 19.

---

xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

Because of subtractions from the denominator, we were getting values of 0.0011xxxx rather than a clean 0.001 and so the tests would fail.  Changing the target to be < 0.002 is effectively the same without worrying about rounding errors.

Reduce test flakiness

---

xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java

As per #10433, the assert statement seems to cause a timeout in the pick() function of WRR's static stride scheduler. Additionally, the assertion does not have to be true if there are multiple threads involved. Unless a better solution is suggested, removing it seems like the best option.
Fix on master: #10437

(backport v1.57) removed assert statement for static stride scheduler with multiple threads

---

api/src/context/java/io/grpc/Context.java

#2462 contains the discussion about the `attach(Context)` method.
The `doAttach(Context)` method has been made abstract and the `attach(Context)` method has been deleted. 
There are no open-source or g3 dependencies for this method. 
There is only [one affected repo](https://sourcegraph.com/github.com/quarkusio/quarkus/-/blob/extensions/grpc/runtime/src/main/java/io/grpc/override/ContextStorageOverride.java) from [this query](https://sourcegraph.com/search?q=context:global+class+ContextStorageOverride+lang:java&patternType=standard&sm=0&groupBy=repo), which shouldn't block us from making this change.

Context.Storage deprecated method attach() removed, doAttach() made abstract

---

xds/src/main/java/io/grpc/xds/BootstrapperImpl.java

The bootstrapping code currently does not log zone and subZone from locality correctly, and only logs region. This commit fixes the logging message format.

Fix locality logging

---

api/build.gradle
build.gradle
gae-interop-testing/gae-jdk8/build.gradle
servlet/build.gradle
servlet/jakarta/build.gradle

In d654707 we swapped compiling the uploaded artifacts to Java 11. This caused ABI issues with ByteBuffer, like clear() returning ByteBuffer instead of Buffer.
There are source-level approaches to avoid the accidental ABI dependency on Java 11, but we have no tool able to detect such breakages. We use Animalsniffer for similar cases, but it fails to detect these[1]. Since we have no tool, source-level approaches can't gain the necessary confidence that all incompatibility fixes have been resolved.
Java has had javac-level ways to address this, but they used to require setting bootclasspath. Since Java 9, though, they made it easier and we can use --release, which does exactly what we need.
Fixes #10432
1. https://github.com/mojohaus/animal-sniffer/issues/77
Backport of #10441

Avoid accidental Java 9+ dependency with --release (1.57.x backport)

---

stub/src/main/java/io/grpc/stub/MetadataUtils.java

fixes #1789 
(have made sure there is no internal usage of these methods)

stub: remove 2 deprecated methods from MetadataUtils

---

all/build.gradle

While JacocoReportBase.getExecutionData() is properly annotated with `@InputFiles` and is a FileCollection, which can propagate dependencies, the JacocoPlugin's configuration of the task [goes through a File][barefile], which doesn't propagate task dependency information. This is overcome in the plugin by mustRunAfter. This may have been on purpose to allow jacocoTestReport to report on the subset of tests already run, but is atypical these days.
Because of that, we need to copy the mustRunAfter from the other JacocoTestReports. The dependsOn weren't doing anything because there were no dependsOn; that configuration is quite old so it's hard to say when they stopped functioning.
This fixes warnings like:
```
- Gradle detected a problem with the following location: …
```

all: Copy mustRunAfter from each project's JacocoTestReport

---

README.md
android-interop-testing/build.gradle
api/build.gradle
benchmarks/build.gradle
build.gradle
compiler/build.gradle
examples/android/clientcache/build.gradle
examples/android/helloworld/build.gradle
examples/android/routeguide/build.gradle
examples/android/strictmode/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-debug/build.gradle
examples/example-gauth/build.gradle
examples/example-gcp-observability/build.gradle
examples/example-hostname/build.gradle
examples/example-jwt-auth/build.gradle
examples/example-orca/build.gradle
examples/example-reflection/build.gradle
examples/example-servlet/build.gradle
examples/example-tls/build.gradle
examples/example-xds/build.gradle
gradle/wrapper/gradle-wrapper.properties
interop-testing/build.gradle
netty/shaded/build.gradle
servlet/build.gradle
servlet/jakarta/build.gradle
settings.gradle

Most changes are migrating from conventions to the equivalent extensions. JMH, AppEngine, and Jib plugins trigger future compatibility warnings with `--warning-mode all`.
The movement of configurations was to allow sourceSets to create the configurations and then we just configure them. When configurations were before sourceSets, we'd implicitly create the configuration.
The examples were _not_ updated to the newer Gradle, although the non-Android examples work with the newer Gradle. The Android examples use an older Android Gradle Plugin which will need to be upgraded first. https://github.com/grpc/grpc-java/issues/10445

Upgrade to Gradle 8.2.1 and upgrade plugins

---

README.md

The README describes the released version of gRPC. But the most recent release doesn't use protobuf 3.23.4. Telling people to use protoc 3.23.4 is asking for breakages because they will be running with protobuf-java 3.22.3, which is a downgrade.
The bump to 3.23.4 was incorrectly done in #10359.

README.md: Revert reference to protobuf 3.23.4

---

xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

With the prior implementation of the `EdfScheduler` in WRR, because we replaced the scheduler every time we updated weights, if one subchannel had a large weight while another had a small weight, the second one might've never gotten used.
The fix for this was to randomize the initial scheduler state for each creation of the scheduler. 
However, now that an atomic sequence is used to make picks in the static stride scheduler, we can just pass through this sequence throughout different instances of the scheduler whenever a weight update occurs. 
In #10272, this change was discussed: 
> We can do it in a later PR (by you or someone else), but we will want to replace this Random with AtomicInteger sequence. The only reason to have the random now is because we couldn't carry state between …

xds: replace random with atomic sequence in WRR

---

util/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
util/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

OutlierDetectionLoadBalancer did not delegate calls to an existing ClientStreamTracer from the tracer it installed. This change has the OD tracer delegate all calls to the underlying one.
b/287995936

util: Outlier detection tracer delegation

---

api/src/main/java/io/grpc/ServerRegistry.java
api/src/testFixtures/java/io/grpc/ServerRegistryAccessor.java
okhttp/build.gradle
okhttp/src/main/java/io/grpc/okhttp/OkHttpServerBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpServerProvider.java
okhttp/src/main/resources/META-INF/services/io.grpc.ServerProvider
okhttp/src/test/java/io/grpc/okhttp/OkHttpServerProviderTest.java

This allows okhttp to service the Grpc.newServerBuilderForPort() API. Note that, unlike Netty, it will throw if you try to use ServerBuilder.forPort().
This fixes android-interop-testing which was broken by c9864a119.

okhttp: Add OkHttpServerProvider

---

java_grpc_library.bzl

While not easy to use because java_grpc_library() uses a fixed
toolchain, it is possible for downstream users to apply a patch to the
repo to add their own annotation processors. This feature was added
inside Google so exporting it reduces the diff between internal and
external and causes no harm.
cl/280287611

java_grpc_library.bzl: Allow toolchain to use annotation processors

---

build.gradle

Even though we don't really use japicmp, the configuration was resolving artifacts even when the task was not executed. After some clean up, the configuration looks more ordinary.

build.gradle: Modernize japicmp confiuration

---

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

OutlierDetectionLoadBalancer did not delegate calls to an existing ClientStreamTracer from the tracer it installed. This change has the OD tracer delegate all calls to the underlying one.
b/287995936
Backport of #10459

util: Outlier detection tracer delegation (1.57.x backport)

---

xds/third_party/envoy/import.sh
xds/third_party/googleapis/import.sh
xds/third_party/protoc-gen-validate/import.sh
xds/third_party/xds/import.sh

The scripts used `git rev-parse --show-toplevel` so it appeared they could be used from any directory. But references to "GIT_BASE_DIR" weren't absolute, so it did matter the starting directory. And it mattered in a big way for xds/import.sh as if you ran it from the grpc-java directory it would delete the xds directory in grpc-java, not third_party.
The trap that deleted the GIT_BASE_DIR was very broken. In addition to potentially deleting the wrong directory, it was unnecessary because that directory was in tmpdir. But you can only have one trap per signal, so this unnecessary trap disabled the trap that deleted tmpdir.
The script needed a full clone because it needed to check out a specific commit. To work with --depth 1 you have to use some convoluted syntax. But just downloading a …

xds: Fix import scripts deleting the wrong files, use of trap, and full git clone

---

api/src/main/java/io/grpc/MethodDescriptor.java

Closes #2592: MethodDescriptor.getRequestMarshaller, MethodDescriptor.getResponseMarshaller

API stabilization: getRequestMarshaller, getResponseMarshaller

---

api/src/main/java/io/grpc/ServerCall.java

api: stabilize ServerCall.getAuthority() by removing experimental annotation

---

servlet/build.gradle
servlet/jakarta/build.gradle

Instead of adding explicit dependsOn to compileJava and sourcesJar, adding the sync task to the sourceSet automatically propagates the dependency to all consumers of the code.

servlet: Support configuration avoidance in build

---

buildscripts/kokoro/android.sh
examples/android/clientcache/app/build.gradle
examples/android/clientcache/app/src/main/java/io/grpc/clientcacheexample/ClientCacheExampleActivity.java
examples/android/clientcache/build.gradle
examples/android/helloworld/app/build.gradle
examples/android/helloworld/app/src/main/java/io/grpc/helloworldexample/HelloworldActivity.java
examples/android/helloworld/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/routeguide/app/src/main/java/io/grpc/routeguideexample/RouteGuideActivity.java
examples/android/routeguide/build.gradle
examples/android/strictmode/app/build.gradle
examples/android/strictmode/app/src/main/java/io/grpc/strictmodehelloworldexample/StrictModeHelloworldActivity.java
examples/android/strictmode/build.gradle

Upgrades the Android examples to use Android Gradle Plugin 7.4.0.
Fixes #10445

examples: Android examples to use AGP 7.4.0

---

api/src/main/java/io/grpc/ManagedChannelBuilder.java

Adds a note on how to avoid a JDK bug by converting an ipv6 scope ID to its numeric form.

api: ManagedChannelBuilder note about ipv6 scope id JDK bug.

---

examples/build.gradle
examples/example-alts/build.gradle
examples/example-debug/build.gradle
examples/example-gauth/build.gradle
examples/example-gcp-observability/build.gradle
examples/example-hostname/build.gradle
examples/example-jwt-auth/build.gradle
examples/example-orca/build.gradle
examples/example-reflection/build.gradle
examples/example-servlet/build.gradle
examples/example-tls/build.gradle
examples/example-xds/build.gradle
examples/gradle/wrapper/gradle-wrapper.properties
gradle/wrapper/gradle-wrapper.properties

Examples are updated to use the new version as well, which wasn't done last time in f3f4ed4ef. That noticed some things that were missed before.

Upgrade to Gradle 8.3

---

stub/src/main/java/io/grpc/stub/ClientCalls.java

Remove ThreadlessExecutor from BlockingServerStream

---

gae-interop-testing/gae-jdk8/build.gradle
interop-testing/build.gradle
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

Interop-testing is both binaries and a library. It hadn't been updated to use java-library and to expose API-surface dependencies to dependents.
This fixes the error:
```
> Task :grpc-gae-interop-testing-jdk8:javadoc FAILED
javadoc: error - An internal exception has occurred.
(com.sun.tools.javac.code.Symbol$CompletionFailure: class file for io.grpc.internal.testing.StreamRecorder not found)
Please file a bug against the javadoc tool via the Java bug reporting page
(http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com)
for duplicates. Include error messages and the following diagnostic in your report. Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for io.grpc.internal.testing.StreamRecorder not found
1 error
```

interop-testing: Correctly expose API types to dependents

---

core/src/main/java/io/grpc/internal/ServerCallImpl.java
core/src/test/java/io/grpc/internal/ServerCallImplTest.java

When server side sendMessage throws a RuntimeException, call `handleInternalError()` (previously internalClose) rather than close.  This will log a warning.
rename internalClose to handleInternalError and change argument from a Status to a Throwable.
Allows more debugging of #10500 
Backport of #10513

Handle exception in servers sendMessage better (v1.58 backport of #10513)

---

core/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java
core/src/test/java/io/grpc/internal/PickFirstLoadBalancerProviderTest.java

PR #10475 earlier only de-experimentalized xDS config parsing, but was not enough to fully enable the feature.

core: de-expermentalize pick first config parsing

---

api/src/main/java/io/grpc/ManagedChannelBuilder.java

Blocking can be confused with the blocking stub, which is unrelated. I'm purposefully not saying "it is used only for X," as that isn't what we need from the API. But it is still helpful to users to describe the sorts of things that use it.
Fixes #10508

api: Make offload executor's purpose more clear

---

core/src/main/java/io/grpc/internal/ForwardingReadableBuffer.java
core/src/main/java/io/grpc/internal/MessageDeframer.java
core/src/main/java/io/grpc/internal/ReadableBuffer.java
netty/src/main/java/io/grpc/netty/NettyReadableBuffer.java

When a memory leak occurs, it is really helpful to have access records to understand where the buffer was being held when it leaked. retain() when we create the NettyReadableBuffer already creates an access record the ByteBuf, so here we track when the ByteBuf is passed to another thread.
See #8330

netty: Touch ByteBuf when message framing has been decoded

---

netty/src/main/java/io/grpc/netty/Utils.java
netty/src/test/java/io/grpc/netty/UtilsTest.java

netty: Respect io.netty.allocator.type="unpooled" when getting Netty Allocator

---

api/src/main/java/io/grpc/ServerRegistry.java

Since 3b61799 OkHttp can support Grpc.newServerBuilderForPort().

api: Add grpc-okhttp to suggestions if no server is available

---

binder/src/androidTest/AndroidManifest.xml
binder/src/androidTest/java/io/grpc/binder/BinderChannelSmokeTest.java
binder/src/main/java/io/grpc/binder/AndroidComponentAddress.java
binder/src/main/java/io/grpc/binder/internal/BinderTransport.java
binder/src/test/java/io/grpc/binder/AndroidComponentAddressTest.java

AndroidComponentAddress now accepts an Intent with merely a package restriction, not a full ComponentName. This lets clients avoid hard coding Service class names that they don't control.
Experimental API AndroidComponentAddress#getComponent() becomes nullable, which is technically a breaking change. But we expect the impact will be small since existing callers mostly work with addresses they created themselves, which will have a non-null ComponentName.
Fixes #9062

Enable indirect addressing using <intent-filter>s.

---

netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java
netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java

netty: Eliminate buffer release when there is an error as caller still owns the buffer.

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

Recently the logic in xDS Name resolver was changed to support encoded authorities: https://github.com/grpc/grpc-java/pull/10207.
This seems to cause an issue for xdstp replacements which would percent encode the authority for the replacement causing double encoding.
For example:
URI = xds:///path/to/service
Authority = path%2Fto%2Fservice
xdstp resource = xdstp://<target-authority>/envoy.config.listener.v3.Listener/path%252Fto%252Fservice
Here the authority is encoded due to slashes and during replacement we percent encode it again causing %2F to change to %252F.
To avoid this issue, use the encoded authority only for the getServiceAuthority() API and for all other use cases retain the unencoded authority. 
@ejona86

Add fix for xdstp replacement for encoded authorities

---

stub/src/main/java/io/grpc/stub/ClientCalls.java

This reverts commit 5f480de2ee7bf56e3cb15635c0bd0d71f6f7006a. We're seeing it thrown in (b/301552213):
```
java.util.concurrent.RejectedExecutionException
at io.grpc.stub.ClientCalls$ThreadlessExecutor.execute(ClientCalls.java:761)
at io.grpc.internal.RetriableStream$Sublistener.closed(RetriableStream.java:954)
at io.grpc.internal.ForwardingClientStreamListener.closed(ForwardingClientStreamListener.java:34)
at io.grpc.internal.InternalSubchannel$CallTracingTransport$1$1.closed(InternalSubchannel.java:691)
at io.grpc.internal.DelayedStream$DelayedStreamListener$4.run(DelayedStream.java:510)
at io.grpc.internal.DelayedStream$DelayedStreamListener.delayOrExecute(DelayedStream.java:462)
at io.grpc.internal.DelayedStream$DelayedStreamListener.closed(DelayedStream.java:507)
at …
```

Revert "stub: enable throwing rejected execution exception on ThreadlessExecutor shutdown (#10555)"

---

api/src/main/java/io/grpc/LoadBalancer.java
util/src/main/java/io/grpc/util/GracefulSwitchLoadBalancer.java
util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/main/java/io/grpc/xds/WeightedTargetLoadBalancer.java
xds/src/main/java/io/grpc/xds/WrrLocalityLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterManagerLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WeightedTargetLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WrrLocalityLoadBalancerTest.java

FixedResultPicker can be used in more situations. Note that WrrLocalityLoadBalancerTest's test was changed non-trivially. The noChildLb test was particularly nasty as it assumed LoadBalancer.ErrorPicker had same toString() as
GracefulSwitchLoadBalancer's ErrorPicker.

api: Replace ErrorPicker with FixedResultPicker

---

WORKSPACE
examples/WORKSPACE

I'm not choosing any version in particular (just the latest). The main point is to get off a "random" commit that had a fix for Netty.

Bump rules_jvm_external to 5.3

---

okhttp/build.gradle

This prevents grpc-util from being exposed on the classpath when
compiling code using grpc-okhttp. grpc-core is still needed because of
AbstractManagedChannelImplBuilder.

okhttp: Make grpc-util an implementation dependency

---

interop-testing/src/main/java/io/grpc/testing/integration/StressTestClient.java
interop-testing/src/test/java/io/grpc/testing/integration/StressTestClientTest.java

Introduces a flag to enable the logging of collected metrics. In some cases it can be more practical to analyze the metrics from a log file after the fact, instead of connecting to the metrics server to collect the metrics as the client is running.

interop-testing: Logging of stress test metrics

---

api/src/main/java/io/grpc/ForwardingChannelBuilder.java
api/src/main/java/io/grpc/ForwardingChannelBuilder2.java
api/src/main/java/io/grpc/ForwardingServerBuilder.java

- `ForwardingServerBuilder`
- `ForwardingChannelBuilder` - will be deprecated immediately after stabilization, ref #10587
- `ForwardingChannelBuilder2` - should be used instead of `ForwardingChannelBuilder`
Closes #3363
Closes #7393 
Closes #10585

core: Stabilize forwarding builders

---

repositories.bzl

bazel: protobuf_javalite typo in IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS

---

binder/src/main/java/io/grpc/binder/internal/MultiMessageServerStream.java
binder/src/main/java/io/grpc/binder/internal/SingleMessageServerStream.java
core/src/main/java/io/grpc/internal/AbstractServerStream.java
core/src/main/java/io/grpc/internal/ServerCallImpl.java
core/src/main/java/io/grpc/internal/ServerStream.java
core/src/test/java/io/grpc/internal/AbstractServerStreamTest.java
core/src/test/java/io/grpc/internal/ServerCallImplTest.java
core/src/test/java/io/grpc/internal/ServerImplTest.java
core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java
inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java
netty/src/main/java/io/grpc/netty/NettyServerStream.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
netty/src/test/java/io/grpc/netty/NettyServerStreamTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpServerStream.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpServerTransportTest.java
servlet/src/main/java/io/grpc/servlet/ServletServerStream.java

Avoid flushing headers when the server returns a single response

---

gradle/libs.versions.toml

Starting from version 4.5.0 Mockito uses the Java stream APIs, which are not available on Android API levels < 24. This has been causing the Android integration tests for API levels 21, 22 and 23 to fail.
This is to address #10457.

gradle: Downgrade mockito to 4.4.0

---

interop-testing/src/main/java/io/grpc/testing/integration/StressTestClient.java
interop-testing/src/test/java/io/grpc/testing/integration/StressTestClientTest.java

Adds support for specifying either google default or compute engine "custom" credentials on the command line. This works like it does in TestServiceClient.
Another feature from TestServiceClient is also included - the channel builder is created differently when the server port is 0. This avoids some ipv6 address parsing shenanigans.

interop-testing: Custom credentials in stress test

---

gradle/libs.versions.toml

Backport of #10602
Starting from version 4.5.0 Mockito uses the Java stream APIs, which are not available on Android API levels < 24. This has been causing the Android integration tests for API levels 21, 22 and 23 to fail.
This is to address #10457.

gradle: Downgrade mockito to 4.4.0 (1.59.x backport)

---

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/main/java/io/grpc/testing/integration/StressTestClient.java

This adds the ability to disable the installation of stream tracers in each test call in AbstractInteropTest. The tracers are stored in a list and used to make assertions by normal tests, but a long running stress test will accumulate too many entries in this list and the heap gets quickly filled up.

interop-testing: allow disabling of stream tracers

---

repositories.bzl

Related to #6544 and #6976
Backport of #10592

bazel: protobuf_javalite typo in IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS (1.59.x backport)

---

xds/src/main/java/io/grpc/xds/orca/OrcaOobUtil.java
xds/src/test/java/io/grpc/xds/orca/OrcaOobUtilTest.java

We started using Orca, but not every service in our service mesh serves an Orca endpoint.
This means that our client side logs filled up with severe logging messages about the Orca service being `UNIMPLEMENTED` per subchannel.
This is because the error is the only one that is logged to a static Java logger instance, while the rest of the subchannel messages are logged to the `SubchannelLogger`.
In order to not fill up the logs of our services, we'd like to also log the `UNIMPLEMENTED` error to the `SubchannelLogger`.

Log ORCA UNIMPLEMENTED error to subchannel logger

---

protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java

Add a comment clarifying that the ProtoLiteUtils class will remain experimental.

protobuf-lite: ProtoLiteUtils experimental comment

---

protobuf/src/main/java/io/grpc/protobuf/ProtoUtils.java

This method has been around since 2018 and is now considered stable.
Closes #4477

protobuf: Stabilize ProtoUtils.metadataMarshaller()

---

binder/src/androidTest/java/io/grpc/binder/BinderSecurityTest.java
binder/src/main/java/io/grpc/binder/AsyncSecurityPolicy.java
binder/src/main/java/io/grpc/binder/ServerSecurityPolicy.java
binder/src/test/java/io/grpc/binder/ServerSecurityPolicyTest.java

This is the async variant of SecurityPolicy, allowing callers to implement security checks based on slow calls that aren't meant to block the gRPC thread.
BinderTransportSecurity.checkAuthorization **STILL** blocks while attempting to resolve the ListenableFuture<Status> it gets from the policy object. That will still be adressed in a follow-up.
Relate issue: #10566

Introduce the AsyncSecurityPolicy class.

---

xds/src/main/java/io/grpc/xds/orca/OrcaOobUtil.java
xds/src/test/java/io/grpc/xds/orca/OrcaOobUtilTest.java

We started using Orca, but not every service in our service mesh serves an Orca endpoint.
This means that our client side logs filled up with severe logging messages about the Orca service being `UNIMPLEMENTED` per subchannel.
This is because the error is the only one that is logged to a static Java logger instance, while the rest of the subchannel messages are logged to the `SubchannelLogger`.
In order to not fill up the logs of our services, we'd like to also log the `UNIMPLEMENTED` error to the `SubchannelLogger`.
Backport of #10625. CC @yannickepstein

Log ORCA UNIMPLEMENTED error to subchannel logger (1.59.x backport)

---

interop-testing/src/main/java/io/grpc/testing/integration/StressTestClient.java

The client stream tracers need to be disabled before setUp() is called.

interop-testing: Fix disabling of stream tracers

---

interop-testing/src/main/java/io/grpc/testing/integration/StressTestClient.java

We don't want local specific formatting of the number, so let's just concatenate.

interop-testing: Fix total calls log statement

---

alts/build.gradle

google/protobuf#4046 was fixed a long time ago. Recently noticed when working on ForwardingChannelBuilder(2).

alts: Re-enable deprecation warnings

---

alts/src/main/java/io/grpc/alts/AltsChannelBuilder.java
alts/src/main/java/io/grpc/alts/ComputeEngineChannelBuilder.java
alts/src/main/java/io/grpc/alts/GoogleDefaultChannelBuilder.java
android/src/main/java/io/grpc/android/AndroidChannelBuilder.java
api/src/main/java/io/grpc/ForwardingChannelBuilder.java
api/src/test/java/io/grpc/ForwardingChannelBuilderTest.java
api/src/test/java/io/grpc/ManagedChannelRegistryTest.java
binder/src/main/java/io/grpc/binder/BinderChannelBuilder.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
interop-testing/src/test/java/io/grpc/ChannelAndServerBuilderTest.java
rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java

Deprecate `ForwardingChannelBuilder` in favor of `ForwardingChannelBuilder2`

core: Deprecate ForwardingChannelBuilder

---

alts/src/main/java/io/grpc/alts/internal/AltsHandshakerStub.java
alts/src/test/java/io/grpc/alts/internal/AltsHandshakerStubTest.java

This PR addresses a bug which is a part of https://github.com/grpc/grpc-java/issues/9058. It propagates the original exception caught at https://github.com/grpc/grpc-java/blob/a294b27d5222dc779805b576baf28ed33c46ebc0/alts/src/main/java/io/grpc/alts/internal/AltsHandshakerStub.java#L118

alts: Add propagation of original exception for AltsHandshakerStub

---

core/src/main/java/io/grpc/internal/ServerImpl.java
interop-testing/src/test/java/io/grpc/testing/integration/MoreInProcessTest.java

This is currently the only place where we return Status.UNKNOWN with no description, which makes is harder to debug and differentiate from statuses originated from non-grpc sources.
This PR enriches ServerImpl's #internalClose `Status.UNKNOWN` with description `Application error processing RPC`.

core: add description to Status.UNKNOWN in ServerImpl's #internalClose

---

android-interop-testing/build.gradle
android/build.gradle
binder/build.gradle
binder/src/main/java/io/grpc/binder/BindServiceFlags.java
binder/src/test/java/io/grpc/binder/BindServiceFlagsTest.java
examples/android/clientcache/app/build.gradle
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/strictmode/app/build.gradle

Per https://developer.android.com/about/versions/14#beta-3, Android U has reached the platform stability milestone which means that all external APIs are finalized.
We can thus bump the compileSdkVersion to 34 (U) and begin using APIs added there. We leave targetSdkVersion unchanged for now to avoid the broader evaluation of whether deeper changes may be necessary as part of the upgrade; this simply allows compile-time access to newer APIs without changing runtime behavior.
See b/274061424

Bump compileSdkVersion and finalize setAllowActivityStarts API.

---

benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncServer.java
stub/src/main/java/io/grpc/stub/StreamObservers.java

This class is of questionable utility and generally not used.
Fixes #4694

stub: Deprecate StreamObservers

---

android/build.gradle
android/proguard-rules.txt
benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncServer.java
core/src/main/java/io/grpc/internal/PickFirstLeafLoadBalancer.java
core/src/main/java/io/grpc/internal/PickFirstLoadBalancer.java
stub/src/main/java/io/grpc/stub/StreamObservers.java
util/src/main/java/io/grpc/util/GracefulSwitchLoadBalancer.java
util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
util/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
util/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
util/src/testFixtures/java/io/grpc/util/AbstractTestHelper.java
xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java
xds/src/main/java/io/grpc/xds/LeastRequestLoadBalancer.java
xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/test/java/io/grpc/xds/LeastRequestLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

Implementation of A61 for Ring Hash
Major changes to behavior:
-   Lazy create PickFirstLoadBalancers rather than lazily connect subchannels
-   When picking, look for first entry in ring not in TF rather than focus on first 2 entries in the ring after hash

Make Ring Hash LB a petiole policy

---

testing/src/main/java/io/grpc/internal/testing/FakeNameResolverProvider.java

This fixes BinderChannelSmokeTest, broken by 15fc70be.
CC @sanjaypujare . We noticed when doing the import. We didn't notice in OSS because this CI only runs on master, not per-PR. So we would have noticed eventually but hadn't yet.

testing: Add FakeNameResolverProvider.getProducedSocketAddressTypes

---

rls/build.gradle
services/build.gradle
servlet/build.gradle
servlet/jakarta/build.gradle
util/build.gradle

This prevents grpc-core from being exposed on the classpath when compiling code using grpc-util.

util: Make grpc-core an implementation dependency

---

netty/src/main/java/io/grpc/netty/AbstractHttp2Headers.java

Fixes https://github.com/grpc/grpc-java/issues/10665
Using `grpc-netty` with Netty 4.1.101.Final results in the following error:
```
io.grpc.StatusRuntimeException: UNKNOWN
at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:275)
at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:256)
at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:169)
// Remaining stacktrace omitted
Caused by: java.lang.UnsupportedOperationException
at io.grpc.netty.AbstractHttp2Headers.isEmpty(AbstractHttp2Headers.java:40)
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:419)
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2Connect …
```

Implement Http2Headers.isEmpty

---

api/src/main/java/io/grpc/NameResolver.java

On the surface this looks like a breaking API change but I'm actually just formalizing existing intolerance of multi-start exhibited by widely-used implementations: DnsNameResolver, UdsNameResolver, XdsNameResolver as well as several Google-internal ones

Clarify that NameResolver can only be started once.

---

interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java

Backport of #10084 to v1.54.x.
---

interop-testing: Start mgmt server before xds server (v1.54.x backport)

---

interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java

Backport of #10084 to v1.53.x.
---

interop-testing: Start mgmt server before xds server (v1.53.x backport)

---

interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java

Backport of #10084 to v1.52.x.
---

interop-testing: Start mgmt server before xds server (v1.52.x backport)

---

interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java

Backport of #10084 to v1.51.x.
---

interop-testing: Start mgmt server before xds server (v1.51.x backport)

---

interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java

Backport of #10084 to v1.50.x.
---

interop-testing: Start mgmt server before xds server (v1.50.x backport)

---

util/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
util/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

An OutlierDetectionLoadBalancer child load balancer might decided to shut down any subchannel it is tracking. We need to make sure that those subchannels are removed from the outlier detection tracker map to avoid a memory leak.
Fixes: #10672

util: Remove shutdown subchannels from OD tracking

---

netty/src/main/java/io/grpc/netty/NettyServer.java
netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/netty/NettyServerTransport.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
netty/src/test/java/io/grpc/netty/NettyServerTest.java

The behavior purposefully mirrors that of Netty's
AbstractHttp2ConnectionHandlerBuilder.decoderEnforceMaxRstFramesPerWindow(). That API is not available to our code as we extend the Http2ConnectionHandler, but we want our API to be able to delegate to Netty's in the future if that ever becomes possible.
CC @temawi

netty: Add option to limit RST_STREAM rate

---

netty/src/main/java/io/grpc/netty/NettyServer.java
netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/netty/NettyServerTransport.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
netty/src/test/java/io/grpc/netty/NettyServerTest.java

The behavior purposefully mirrors that of Netty's
AbstractHttp2ConnectionHandlerBuilder.decoderEnforceMaxRstFramesPerWindow(). That API is not available to our code as we extend the Http2ConnectionHandler, but we want our API to be able to delegate to Netty's in the future if that ever becomes possible.
CC @YifeiZhuang 
Backport of #10675

netty: Add option to limit RST_STREAM rate (1.60.x backport)

---

netty/src/main/java/io/grpc/netty/NettyServer.java
netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/netty/NettyServerTransport.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
netty/src/test/java/io/grpc/netty/NettyServerTest.java

The behavior purposefully mirrors that of Netty's
AbstractHttp2ConnectionHandlerBuilder.decoderEnforceMaxRstFramesPerWindow(). That API is not available to our code as we extend the Http2ConnectionHandler, but we want our API to be able to delegate to Netty's in the future if that ever becomes possible.
CC @YifeiZhuang  
Backport of #10675

netty: Add option to limit RST_STREAM rate (1.59.x backport)

---

netty/src/main/java/io/grpc/netty/AbstractHttp2Headers.java

Fixes https://github.com/grpc/grpc-java/issues/10665
Using `grpc-netty` with Netty 4.1.101.Final results in the following error:
```
io.grpc.StatusRuntimeException: UNKNOWN
at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:275)
at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:256)
at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:169)
// Remaining stacktrace omitted
Caused by: java.lang.UnsupportedOperationException
at io.grpc.netty.AbstractHttp2Headers.isEmpty(AbstractHttp2Headers.java:40)
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:419)
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2Connect …
```

Implement Http2Headers.isEmpty (1.59.x backport)

---

util/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
util/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

Backport of #10683
An OutlierDetectionLoadBalancer child load balancer might decided to shut down any subchannel it is tracking. We need to make sure that those subchannels are removed from the outlier detection tracker map to avoid a memory leak.
Fixes: #10672

util: Remove shutdown subchannels from OD tracking (1.60.x backport)

---

core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java

This may help some to move closer to Providers. It especially helps cases where `NameResolverFactory`s aren't returning `InetSocketAddress`, as it allows them to override `getProducedSocketAddressTypes()`, which will now fail starting in 15fc70be.

core: Detect NameResolverProviders passed as Factories

---

api/src/main/java/io/grpc/LoadBalancer.java
api/src/testFixtures/java/io/grpc/LoadBalancerMatchers.java
util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
xds/build.gradle
xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
xds/src/main/java/io/grpc/xds/WeightedTargetLoadBalancer.java
xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WeightedTargetLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WrrLocalityLoadBalancerTest.java

FixedResultPicker is our preferred approach.

api: Deprecate LoadBalancer.EMPTY_PICKER

---

buildscripts/kokoro/android-interop.sh

Note that this uses Pixel2 and Pixel3. Also swap 26-27 from Nexus6P to Pixel2. We tend to prefer the latest (virtual) device for each API level.
The current models and their supported API levels are available via:
```
gcloud firebase test android models list --filter=form=virtual
```
Pixel2.arm supports 31-32, but is beta, so I didn't swap to it. It also supports the preview 33.

android-interop: Add testing for API levels 28-30

---

all/build.gradle

This should have been added when inprocess was moved out of core. This includes inprocess in the Javadoc and code coverage reporting.

all: Add grpc-inprocess

---

buildscripts/kokoro/android-interop.sh

They are a lot faster. Instead of 1-3 minutes of test execution, I now see 2-22 seconds. There still may be 3 minutes of overhead for the gcloud command to complete, but the reduction is noticable in the total execution time. And it seems the tests are actually being run, as there is some flakiness. The flakiness appears to be at a lower rate.
The script was slightly reorganized to make it easier to copy commands to run locally.

kokoro: Use Firebase's arm virtual Android devices

---

buildscripts/kokoro/android-interop.sh

This avoids an OOM. We could probably configure things to run them together, but that generally takes trial-and-error.

kokoro: Build android-interop-testing and binder separately

---

core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java

This may help some to move closer to Providers. It especially helps cases where `NameResolverFactory`s aren't returning `InetSocketAddress`, as it allows them to override `getProducedSocketAddressTypes()`, which will now fail starting in 15fc70be.
Backport of #10693

core: Detect NameResolverProviders passed as Factories (1.60.x backport)

---

util/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
util/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java

We already do this for WRR. Notably, we are no longer trying to avoid the modulus each pick. It was of questionable value, and removing it is necessary to continue sharing the same integer when the list size changes.
The change means we can implement a stronger isEquivalentTo() by comparing the AtomicInteger references. It is strong enough that the operation aligns with normal equals(). Using equals() instead of isEquivalentTo() also made more obvious an equals() optimization that uses the hashCode() before the more expensive HashSet creation; equals() should now be very fast except when they are (very likely) equal.

util: Pass an AtomicInteger to RR's ReadyPicker

---

build.gradle
buildSrc/build.gradle
buildSrc/src/main/java/io/grpc/gradle/CheckForUpdatesTask.java
buildSrc/src/main/java/io/grpc/gradle/CheckPackageLeakageTask.java
buildSrc/src/main/java/io/grpc/gradle/RequireUpperBoundDepsMatchTask.java
xds/build.gradle

Gradle is forcing a move away from using 'project' during task excution and because of some interactions there, this is easiest by making them real classes. That makes them start looking quite strange in the build file, so they are now moved to buildSrc/. We could have continued using Groovy, but it is weird in some ways that are more apparent when making classes and not just scripting. Instead, they were converted to Java.
They are compatible with delayed configuration resolution as well.

Make custom tasks compatible with configuration cache

---

RELEASING.md

This removes the benefit of including the PR number in the title without also requiring using github APIs to query the PR number. It still provides the same details about the change, and indirectly links to the PR if the user wants to see the review.

RELEASING.md: Include commit hash in shortlog

---

binder/src/androidTest/java/io/grpc/binder/internal/BinderTransportTest.java
binder/src/main/java/io/grpc/binder/BinderServerBuilder.java
binder/src/main/java/io/grpc/binder/internal/BinderServer.java
binder/src/main/java/io/grpc/binder/internal/BinderTransportSecurity.java
binder/src/main/java/io/grpc/binder/internal/PendingAuthListener.java
binder/src/test/java/io/grpc/binder/ServerSecurityPolicyTest.java

- Introduce PendingAuthListener to handle a ListenableFuture<Status>, progressing the gRPC through each stage in sequence once the future completes and is OK.
- Move unit tests away from `checkAuthorizationForService` and into `checkAuthorizationForServiceAsync` since that should be the only method called in production now.
- Some tests in `ServerSecurityPolicyTest` had their expectations updated; they previously called synchornous APIs that transformed failed `ListenableFuture<Status>` into one or another status. Now, we call the sync API, so those transformations do not happen anymore, thus the test needs to deal with failed futures directly.
- I couldn't figure out if this PR needs extra tests. AFAICT `BinderSecurityTest` should already cover the new codepaths, but please let me know …

Handle slow security policies without blocking gRPC threads.

---

util/build.gradle

We do the same in grpc-api and grpc-core

util: Disable publishing of fixtures

---

.github/workflows/testing.yml

Protobuf 25.0 drops support for Bazel 5. Bazel 7 is coming out very soon, at which point we'd drop Bazel 5 anyway.

Drop support for Bazel 5

---

RELEASING.md

Removing the $ prompt makes it easier to copy+paste. At no point are we running as root, so there's no # vs $ distinction, not that many people would even notice the difference.
There is a risk here that not all commands end up getting run. When pasting multiple commands at once, gradle or another tool might read in stdin and discard them. But it's probably not worth continuing the copy-each-command-separately-and-avoiding-the-$.

RELEASING.md: Remove $ before commands

---

README.md

Travis is no longer used, the badge should be replaced by GitHub Actions.
See also: https://github.com/grpc/grpc-java-api-checker/pull/28

README.md: Update the build badge

---

netty/src/main/java/io/grpc/netty/NettyServerBuilder.java

The KeepAliveManager clamps the keepalive and keepalive time values such that the result is larger than the minimum values specified here. Therefore, a second check here is unnecessary.

NettyServerBuilder: remove dead code

---

core/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java
core/src/test/java/io/grpc/internal/PickFirstLoadBalancerProviderTest.java

PickFirst was not receiving its configuration without this fix which broke test `directpath_traffic_director_soft_affinity_randomness` for v1.58.0.  
Fixes b/307705360
Backport of #10531

core: de-expermentalize pick first config parsing (1.58.x backport)

---

api/src/main/java/io/grpc/ForwardingChannelBuilder.java
api/src/main/java/io/grpc/ForwardingChannelBuilder2.java
api/src/main/java/io/grpc/ManagedChannelBuilder.java
core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java
core/src/test/java/io/grpc/internal/ManagedChannelImplBuilderTest.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java

Remove unused experimental method. This is a no-op, since it was never implemented on the server side.
Fixes #3399

util:Remove Unused experimental API ManagedChannelBuilder.enableFullStreamDecompression

---

core/src/main/java/io/grpc/internal/ManagedChannelOrphanWrapper.java

Originally you had to confirm that awaitTermination() returned true, but that was annoying and useless, especially after calling shutdownNow(). The behavior was changed in ce2ae1fb because the awaitTermination() detection logic could prevent the channel from getting garbage collected.
Fixes #10732
CC @Jasper-M

core: Improve language for leaked channel error

---

api/build.gradle
api/src/test/java/io/grpc/LoadBalancerRegistryTest.java
api/src/test/java/io/grpc/NameResolverRegistryTest.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerProviderTest.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbNameResolverTest.java

It was just unnecessary, and is isn't great having lower-level tests depend on higher-level packages.

api: Remove test dependency on grpclb

---

core/build.gradle
core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java

It was just unnecessary, and is isn't great having lower-level tests depend on higher-level packages.

core: Remove test dependency on grpclb

---

examples/example-hostname/build.gradle
istio-interop-testing/build.gradle

gcr.io/distroless/java:8 is no longer being updated. Java 8 isn't a distroless option any more. Java 11 and 17 are options, but only Java 17 with Debian 12. The main alternative is to stick with Java 8 and use something like docker.io/library/eclipse-temurin:8-jre . But there doesn't seem to be much need to use an old JDK for these containers.
jib needed updating to support the oci manifest format used in the updated image.

Upgrade distroless base images

---

alts/build.gradle
android-interop-testing/build.gradle
android/build.gradle
api/build.gradle
auth/build.gradle
benchmarks/build.gradle
binder/build.gradle
core/build.gradle
cronet/build.gradle
examples/build.gradle
examples/example-hostname/build.gradle
examples/example-jwt-auth/build.gradle
examples/example-oauth/build.gradle
inprocess/build.gradle
interop-testing/build.gradle
netty/build.gradle
okhttp/build.gradle
protobuf/build.gradle
rls/build.gradle
services/build.gradle
stub/build.gradle
testing/build.gradle
xds/build.gradle

These look pretty fair now, mostly only exposing grpc-api and annotations as api dependencies.
-----
As noticed at https://github.com/grpc/grpc-java/pull/10755#issuecomment-1858032345
CC @temawi

Change many api deps to implementation deps

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

buildscripts: Use the Kokoro shared install lib from the new repo

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

Backport of #10757 to v1.59.x.
---

buildscripts: Use the Kokoro shared install lib from the new repo (v1.59.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

Backport of #10757 to v1.58.x.
---

buildscripts: Use the Kokoro shared install lib from the new repo (v1.58.x backport)

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/main/java/io/grpc/xds/ControlPlaneClient.java
xds/src/main/java/io/grpc/xds/SharedXdsClientPoolProvider.java
xds/src/main/java/io/grpc/xds/XdsClient.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java
xds/src/test/java/io/grpc/xds/XdsClientImplV3Test.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java
xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java

fix https://github.com/grpc/grpc/issues/34099
@ejona86  early feedback about the overall shape would be great, tests needs to be cleaned up.

xDS: implement ADS stream flow control mechanism

---

core/src/main/java/io/grpc/internal/MessageFramer.java

This fixes two bugs in outbound message size checking:
* When thet check failed, the thrown `StatusRuntimeException` with a status code of `RESOURCE_EXHAUSTED` was being caught and rewrapped in another `StatusRuntimeException` but this time with a status code of `UNKNOWN`, and the error message was lost.
* This applies the max outbound message size check to messages prior to, and after compression, since compression of a message that is smaller than the maximum send size can result in a larger message that exceeds the maximum send size. See #10738.

Fix outbound message size checking

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

Backport of #10757 to v1.60.x.
---

buildscripts: Use the Kokoro shared install lib from the new repo (v1.60.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

Backport of #10757 to v1.57.x.
---

buildscripts: Use the Kokoro shared install lib from the new repo (v1.57.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

Backport of #10757 to v1.56.x.
---

buildscripts: Use the Kokoro shared install lib from the new repo (v1.56.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

Backport of #10757 to v1.55.x.
---

buildscripts: Use the Kokoro shared install lib from the new repo (v1.55.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

Backport of #10757 to v1.54.x.
---

buildscripts: Use the Kokoro shared install lib from the new repo (v1.54.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

Backport of #10757 to v1.53.x.
---

buildscripts: Use the Kokoro shared install lib from the new repo (v1.53.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

Backport of #10757 to v1.52.x.
---

buildscripts: Use the Kokoro shared install lib from the new repo (v1.52.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

Backport of #10757 to v1.51.x.
---

buildscripts: Use the Kokoro shared install lib from the new repo (v1.51.x backport)

---

xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java

The issue is that when I block in mock `Answer`, g3 test count that as a method invocation.
It looks local environments and OSS CI didn't report the problem. 
Because we still test that the 2nd message was not delivered due to flow control, it is still fine.
After the fix TAP seems happy, [fusion](https://fusion2.corp.google.com/invocations/b23552fc-3d28-43a3-b4b6-a8ca9d213983/targets/%2F%2Fthird_party%2Fjava_src%2Fgrpc%2Fxds:src%2Ftest%2Fjava%2Fio%2Fgrpc%2Fxds%2FXdsClientImplV3Test)
cc. @danielzhaotongliu

xds: fix test failure in xds flow control

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/main/java/io/grpc/xds/ControlPlaneClient.java
xds/src/main/java/io/grpc/xds/XdsClient.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java
xds/src/test/java/io/grpc/xds/XdsClientImplV3Test.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java
xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java

It seems there is a regression(b/317237071), rollback first.

xds: Revert xds flow control change.

---

README.md

1. The bump to `3.23.4` was incorrectly done to the master README in https://github.com/grpc/grpc-java/pull/10359.
2. This was reverted in https://github.com/grpc/grpc-java/pull/10430.
3. Then protobuf was upgraded again in 1.58.0, from `3.23.4` to `3.24.0` (f8baa9ca1)
4. 1.58.0 release updated it to `3.24.0` for maven, but kept at `3.22.3` for gradle (75af7abf4).
Notes:
* This PR is to be backported to v1.60.x, v1.59.x, v1.58.x. No tag-level release needed.
* After v1.61.0 is out, master README.md protobuf references will be bumped to 3.25.1.

README.md: Correct gradle protobuf reference from 3.22.3 to 3.24.0

---

README.md

Backport of #10772 to v1.60.x.
---
1. The bump to `3.23.4` was incorrectly done to the master README in https://github.com/grpc/grpc-java/pull/10359.
2. This was reverted in https://github.com/grpc/grpc-java/pull/10430.
3. Then protobuf was upgraded again in 1.58.0, from `3.23.4` to `3.24.0` (f8baa9ca1)
4. 1.58.0 release updated it to `3.24.0` for maven, but kept at `3.22.3` for gradle (75af7abf4).

README.md: Correct gradle protobuf reference from 3.22.3 to 3.24.0 (v1.60.x backport)

---

README.md

Backport of #10772 to v1.59.x.
---
1. The bump to `3.23.4` was incorrectly done to the master README in https://github.com/grpc/grpc-java/pull/10359.
2. This was reverted in https://github.com/grpc/grpc-java/pull/10430.
3. Then protobuf was upgraded again in 1.58.0, from `3.23.4` to `3.24.0` (f8baa9ca1)
4. 1.58.0 release updated it to `3.24.0` for maven, but kept at `3.22.3` for gradle (75af7abf4).

README.md: Correct gradle protobuf reference from 3.22.3 to 3.24.0 (v1.59.x backport)

---

README.md

Backport of #10772 to v1.58.x.
---
1. The bump to `3.23.4` was incorrectly done to the master README in https://github.com/grpc/grpc-java/pull/10359.
2. This was reverted in https://github.com/grpc/grpc-java/pull/10430.
3. Then protobuf was upgraded again in 1.58.0, from `3.23.4` to `3.24.0` (f8baa9ca1)
4. 1.58.0 release updated it to `3.24.0` for maven, but kept at `3.22.3` for gradle (75af7abf4).

README.md: Correct gradle protobuf reference from 3.22.3 to 3.24.0 (v1.58.x backport)

---

api/src/main/java/io/grpc/ClientTransportFilter.java
api/src/main/java/io/grpc/ClientTransportHook.java
api/src/main/java/io/grpc/ForwardingChannelBuilder.java
api/src/main/java/io/grpc/ForwardingChannelBuilder2.java
api/src/main/java/io/grpc/ManagedChannelBuilder.java
binder/src/main/java/io/grpc/binder/internal/BinderTransport.java
core/src/main/java/io/grpc/internal/InternalSubchannel.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/ManagedClientTransport.java
core/src/main/java/io/grpc/internal/OobChannel.java
core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java
cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java
cronet/src/test/java/io/grpc/cronet/CronetClientTransportTest.java
inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java
netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
netty/src/test/java/io/grpc/netty/NettyTransportTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java

**Problem**
We're trying to add some stats on the number of connections opened, closed, and active on the client side for grpc-java. On the server side, ServerTransportFilter acts as a reasonable hook for this, but there doesn't seem to be anything comparable on the client side that I can find (if there is, please direct me to it!).
Closes #10647
**Solution**
Add a ClientTransportFilter. Similarly to ServerTransportFilter this will provide an observability hook and allows direct modification of the transport's attributes. 
To wire this in, this PR also adds a `filterTransport` method to `ManagedClientTransport.Listener` which handles modifying the transport's attributes. This is called just before `transportReady`

Add ClientTransportFilter

---

xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java

result:
https://fusion2.corp.google.com/invocations/362bff0d-922f-440b-b5ea-bc0a58da1004/targets/%2F%2Fthird_party%2Fjava_src%2Fgrpc%2Fxds:src%2Ftest%2Fjava%2Fio%2Fgrpc%2Fxds%2FXdsClientImplV3Test/tests
cc. @danielzhaotongliu

xds: fix flaky xds test due to verification race

---

api/src/test/java/io/grpc/ContextTest.java
core/src/main/java/io/grpc/internal/ManagedClientTransport.java
core/src/test/java/io/grpc/internal/ManagedClientTransportTest.java
xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java

Avoids breaking backward compatibility which was done by #10646.

api:Provide a default implementation for new method added to ManagedTranport.Listener to support ClientTransportFilters

---

netty/src/main/java/io/grpc/netty/NettyClientHandler.java

`attribute` is not thread safe, fix forward cl/596040220
Original [tsan](https://fusion2.corp.google.com/ci/tap/zatar.tsan/activity/596040220/invocations/b5346bf3-4f67-4037-9340-fa8abe1a15d8/targets/%2F%2Fjavatests%2Fcom%2Fgoogle%2Fsecurity%2Fzatar%2Ffederation:MtlsCredentialsFactoryTest/history;cell=596040220/b5346bf3-4f67-4037-9340-fa8abe1a15d8/tests)
After fix [tsan](https://fusion2.corp.google.com/invocations/9ba9d310-2942-4f9a-92a3-58ae87a9b364/targets/%2F%2Fjavatests%2Fcom%2Fgoogle%2Fsecurity%2Fzatar%2Ffederation:MtlsCredentialsFactoryTest/tests)
The issue is introduced by #10646
cl/596040220

netty: fix tsan data race in attributes

---

android-interop-testing/src/main/res/layout/activity_tester.xml

Add missing inputType and lint ignore rule.

android-interop-testing: Fix tester activity layout

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java

This stops an exception from being thrown when a known Conscrypt synchronization issue happens.
Note that lack of coverage on the PR is because this issue only happens infrequently in highly concurrent systems and a unit test would not be able to catch it.
Fixes: #10800

okhttp: Ignore known conscrypt socket close issue

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java

Backport of #10811
This stops an exception from being thrown when a known Conscrypt synchronization issue happens.
Note that lack of coverage on the PR is because this issue only happens infrequently in highly concurrent systems and a unit test would not be able to catch it.
Fixes: #10800

okhttp: Ignore known conscrypt socket close issue (1.61.x backport)

---

xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java

fix flaky xds test due to verification race (#10798) (v1.61.x backport)

---

java_grpc_library.bzl

Tested with --incompatible_auto_exec_groups=true with Bazel 7
See also #10514. CC @kotlaja

java_grpc_library.bzl: Support Auto Exec Groups

---

xds/src/main/java/io/grpc/xds/internal/security/trust/CertificateUtils.java
xds/src/test/java/io/grpc/xds/internal/security/CommonTlsContextTestsUtil.java
xds/src/test/java/io/grpc/xds/internal/security/certprovider/CommonCertProviderTestUtils.java
xds/src/test/java/io/grpc/xds/internal/security/certprovider/FileWatcherCertificateProviderTest.java

io.grpc.util.CertificateUtils does much of the same thing as xds's CertificateUtils, but also supports EC keys. The xds code pre-dates the grpc-util class, so it isn't surprising it wasn't using it.
There's a good number of usages of the xds CertificateUtils, so I just got rid of the duplicate implementation, but didn't yet bother changing callers to io.grpc.util.

xds: Add EC key support

---

netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java

6efa9ee3 added `volatile` to `attributes` after TSAN detected a data race that was added in 91d15ce4. The race was because attributes may be read from another thread after `transportReady()`, and the post-filtering assignment occurred after `transportReady()`. The code now filters the attributes separately so they are updated before calling `transportReady()`.
Original TSAN failure:
```
Read of size 4 at 0x0000cd44769c by thread T23:
#0 io.grpc.netty.NettyClientHandler.getAttributes()Lio/grpc/Attributes; NettyClientHandler.java:327
#1 io.grpc.netty.NettyClientTransport.getAttributes()Lio/grpc/Attributes; NettyClientTransport.java:363
#2 io.grpc.netty.NettyClientTransport.newStream(Lio/grpc/MethodDescriptor;Lio/grpc/Metadata;Lio/grpc/CallOptions;[Lio/grpc/ClientStreamTracer;)Lio/grpc/intern …
```

netty: Avoid volatile attributes on client-side

---

api/src/main/java/io/grpc/ClientTransportFilter.java

Change **since** from 1.61 to 1.62 since it wasn't released in 1.61

change the since javadoc in ClientTransportFilter.java

---

xds/src/main/java/io/grpc/xds/GrpcXdsTransportFactory.java
xds/src/main/java/io/grpc/xds/XdsTransportFactory.java
xds/src/test/java/io/grpc/xds/GrpcXdsTransportFactoryTest.java

Mirror C++ implementation.
https://source.corp.google.com/piper///depot/google3/third_party/grpc/src/core/ext/xds/xds_transport.h
This interface will be used to replace `XdsChannelTransport`.
Next step: ControlPlaneClient and LrsClient will implement the XdsTransport defined here.

xds: add xdsTransportFactory interface

---

buildscripts/kokoro/android-interop.sh

Splits the :grpc-android-interop-testing:assembleDebug and :grpc-android-interop-testing:assembleDebugAndroidTest build targets with hopes of avoiding OOMs.

buildscripts: Break up android-interop gradle builds

---

core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java
servlet/src/jettyTest/java/io/grpc/servlet/JettyTransportTest.java
servlet/src/tomcatTest/java/io/grpc/servlet/TomcatTransportTest.java
servlet/src/undertowTest/java/io/grpc/servlet/UndertowTransportTest.java

Netty, okhttp and inproc pass with --runs_per_test 100: sponge2/46002864-6d5f-4fa6-9fe0-38f20c4e516b

transports can send a msg larger than their flow control window

---

binder/src/test/java/io/grpc/binder/internal/PendingAuthListenerTest.java

This class was supposedly already tested via `ServerSecurityPolicyTest.java`, thought that class is actually triggering the short-circuit codepaths (thus, test coverage is reported at 0%).
After this PR, I shall send another one to adapt those tests to force the non-short-circuit async path.
Part of #10566.

Add unit test coverage for PendingAuthListener.

---

binder/src/androidTest/java/io/grpc/binder/BinderSecurityTest.java
binder/src/main/java/io/grpc/binder/AsyncSecurityPolicy.java

I initially omitted the visibility modifier because this class began as an interface. Since it moved to an abstract class, we must make it public so it can be overriden by subclasses in the integrator's packages.
Part of #10566.

Make AsyncSecurityPolicy.checkAuthorizationAsync public.

---

xds/src/main/java/io/grpc/xds/SharedXdsClientPoolProvider.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java

Minor refactor to the tlsContextManager to not expose itself on the xdsClientImpl constructor.
This is to allow stubby team can use xds easily.

xds: move tlsContextManager

---

core/src/main/java/io/grpc/internal/RetriableStream.java

Fixes #10336
Thanks to @turchenkoalex for identifying the underlying problem and fix.

Fix retries that timeout hanging forever.

---

xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

The issues was introduced from 1.60 
Before #10584 the WRR picker is only created for READY states, therefore the pick result is always A subchannel. 
After #10584 the WRR picker is created for TF case, thus we may get a pick result that is empty. 
fix b/287153892

xds: fix NPE in wrr in TF state

---

xds/src/main/java/io/grpc/xds/XdsClient.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java

Currently, the XdsClient.ResourceWatcher is private and can't be used to start watching xDS resources. Mark it as public and an experimental API so that it can be used.
This PR along with https://github.com/grpc/grpc-java/pull/10834 allows users to create and watch custom xDS resources. 
@YifeiZhuang

Allow users to start watching xDS resources 

---

xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

backport of https://github.com/grpc/grpc-java/pull/10868

xds: fix NPE in wrr in TF state [1.61.x backport]

---

core/src/main/java/io/grpc/internal/AbstractClientStream.java
interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java

Fix retry tests that became flaky.  Fixes #10873

Fix flaky retry tests

---

core/src/main/java/io/grpc/internal/AbstractClientStream.java
core/src/main/java/io/grpc/internal/RetriableStream.java
interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java

Fix retries that timeout hanging forever. [ Backport to 1.61.x]

---

xds/third_party/googleapis/import.sh
xds/third_party/googleapis/src/main/proto/google/api/expr/v1alpha1/checked.proto
xds/third_party/googleapis/src/main/proto/google/api/expr/v1alpha1/syntax.proto

Sync googleapis protos to googleapis/googleapis@114a745b2841a044e98cdbb19358ed29fcf4a5f1 for consistency with Envoy and cncf/xds.
The same version is used in [envoy](https://github.com/envoyproxy/envoy/blob/62e7c593748b2ceb3b80a3398e0a937a92edf95d/api/bazel/repository_locations.bzl#L69) and [cncf/xds](https://github.com/cncf/xds/blob/0fa0005c9caaaae56e586ec2c6c26ef93704d29f/bazel/repository_locations.bzl#L23) since Jan 2023.
Function-wise, this is a noop.

xds: Googleapis proto sync to 2023-01-10

---

core/src/main/java/io/grpc/internal/AbstractClientStream.java
core/src/main/java/io/grpc/internal/RetriableStream.java
interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java

Fix retries that timeout hanging forever. [ Backport to 1.59.x]

---

core/src/main/java/io/grpc/internal/RetriableStream.java

Reverts grpc/grpc-java#10855
Failure of //javatests/com/google/geo/automotive/testing/drive/sim/controller/fixtures:DriveSimControllerRuleTest is blocking copybara imports to g3.

Revert "Fix retries that timeout hanging forever."

---

binder/src/main/java/io/grpc/binder/internal/BinderTransport.java
interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java

As discussed in issue #10816, this shouldn't be part of normal logging.
Fixes #10816

Change log level from WARNING to FINER for expected exception

---

buildscripts/kokoro/macos.cfg
buildscripts/kokoro/macos.sh

It makes it hard to run ephemeral jobs, and we don't actually need it here because we aren't changing the setting with manual runs.

kokoro: Avoid using Kokoro's env_vars setting

---

xds/src/main/java/io/grpc/xds/InternalSharedXdsClientPoolProvider.java

This is needed for internal users to both set the bootstrap and interact with the XdsClient via the shared object pool
@YifeiZhuang

Expose the getOrCreate method via the InternalSharedXdsClientPoolProvider

---

xds/src/main/java/io/grpc/xds/XdsClient.java

This will allow users who define and control custom xDS resources to reuse common methods.
@YifeiZhuang

Mark couple of helper functions in XdsClient as public. 

---

auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java
gradle/libs.versions.toml
repositories.bzl

Retryable was added in google-auth-library 1.5.3 to make clear the situations that deserve a retry of the RPC. Upgrading to that caused problems because of transitive dependency issues syncing into Google so it was reverted in 369f87be. google-auth-library 1.11.0 changed the approach to avoid the transitive dependency updates. cl/601545581 upgraded to 1.22.0 inside Google. Bump to that version and swap away from the imprecise IOException heuristic. go/auth-correct-retry
Fixes #6808
CC @TimurSadykov

auth: Add support for Retryable interface

---

interop-testing/src/main/java/io/grpc/testing/integration/Http2Client.java
interop-testing/src/main/java/io/grpc/testing/integration/XdsFederationTestClient.java

We prefer to test using the stable APIs, as they are what our users should be using. Http2Client continues using NettyChannelBuilder because it is intended to test grpc-netty.

interop-testing: Avoid Netty-specific APIs to creating channels

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java

The log level of this method is set to INFO, which is too spammy. Bring it down to the FINE level.
Fixes #10865

util: MultiChildLoadBalance.shutdown() log to FINE

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
util/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java
xds/src/main/java/io/grpc/xds/LeastRequestLoadBalancer.java
xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java

A number of simple cleanups of the MultiChildLoadBalancer class (with associated updates in the petiole policies).
- Add javadoc including the word `override` for all of the methods that are candidates for overriding
- Add `final` to all of the methods that are exposed for use by subclasses, but not expected to be extended
- Getters that were being overridden just to let tests in another package access them have been made `public final`.
- Refactored the code so that the 2 methods acting as flags could be removed leaving cleaner opportunities for construction
- Reordered methods so that those likely to be overridden were at the top of the class
- Removed some unneeded methods

util:MultiChildLoadBalancer cleanup

---

servlet/src/main/java/io/grpc/servlet/GrpcServlet.java
servlet/src/main/java/io/grpc/servlet/ServletServerBuilder.java

I am trying to use gRPC in the existing Spring Boot application, servlets are registered programmatically there.
The code is supposed to look like the following:
```java
@Bean
public ServletRegistrationBean<GrpcServlet> myServiceServlet(MyServiceImpl serviceImpl) {
GrpcServlet servlet = new ServletServerBuilder()
.addService(serviceImpl)
.intercept(TransmitStatusRuntimeExceptionInterceptor.instance())
.buildServlet();
return new ServletRegistrationBean<>(servlet, "/" + MyServiceGrpc.SERVICE_NAME + "/*");
}
```

servlet: introduce ServletServerBuilder.buildServlet()

---

xds/src/main/java/io/grpc/xds/LeastRequestLoadBalancer.java
xds/src/test/java/io/grpc/xds/LeastRequestLoadBalancerTest.java

In 0d39bf50 the ReadyPicker was changed holding List<Subchannel> to List<ChildLbState>, but ChildLbState mutates over time and is not synchronized. We want the picker to have a snapshot of the data, so copy the data from ChildLbState instead of using it directly.
Unfortunately the tests depended on the ChildLbState a bit, so we need to save the EAG only to use it in tests. That's okay for now, but in the future we'll probably want to remove that unnecessary memory usage.

xds: Copy data in least request to avoid picker data race

---

core/build.gradle
netty/build.gradle

Add the 'fake' dependency to grpc-netty instead of grpc-core. grpc-okhttp already depends on grpc-util and probably would be fine without round_robin on Android.
There's not actually a circular dependency, but some tools can't handle the compile vs runtime distinction. Such tools are broken, but fixes have been slow and this approach works with no real downfalls.
Works around #10576 #10701
Backport of #10919

Remove semi-circular dependency between core and util (1.62.x backport)

---

buildscripts/kokoro/windows.bat

I'm trying to upgrade to a newer Windows Kokoro image, but the new one has an old vswhere installed that breaks Gradle. Our old image doesn't have vswhere at all. If vswhere isn't found, this rename prints some errors, but the bat script continues executing. So this change is compatible with both the older and newer image.

buildscripts: Avoid vswhere crashing Gradle

---

compiler/src/java_plugin/cpp/java_generator.cpp
compiler/src/java_plugin/cpp/java_generator.h
compiler/src/java_plugin/cpp/java_plugin.cpp

supercedes #10786, improves #9179 situation

implement ability to skip generation of javax annotation

---

gae-interop-testing/gae-jdk8/src/main/java/io/grpc/testing/integration/NettyClientInteropServlet.java
gae-interop-testing/gae-jdk8/src/main/webapp/WEB-INF/appengine-web.xml

The Java 8 runtime is end of support. Leaving this a gae-jdk8 for now. The gae-jdk8 was because AppEngine changed dramatically from Java 7 to Java 8. Nowadays the versions are more in line with OpenJDK and not very different from each other.
Fixes #10925

Change GAE interop tests to use java11 runtime

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java

The log level of this method is set to INFO, which is too spammy. Bring it down to the FINE level.

util: MultiChildLoadBalance.shutdown() log to FINE (backport #10898 to 1.62)

---

api/src/main/java/io/grpc/MethodDescriptor.java

(minor) Fix a typo in ReflectableMarshaller docstring

---

xds/src/main/java/io/grpc/xds/ControlPlaneClient.java

As discovered by TSAN, the adsStream field is not synchronized.
```
WARNING: ThreadSanitizer: data race (pid=1625)
Read of size 4 at 0x00009b66fc88 by thread T23 (mutexes: write M0):
#0 io.grpc.xds.ControlPlaneClient.isReady()Z ControlPlaneClient.java:203
#1 io.grpc.xds.ControlPlaneClient.readyHandler()V ControlPlaneClient.java:211
#2 io.grpc.xds.ControlPlaneClient$AdsStream.onReady()V ControlPlaneClient.java:328
#3 io.grpc.xds.GrpcXdsTransportFactory$EventHandlerToCallListenerAdapter.onReady()V GrpcXdsTransportFactory.java:145
#4 io.grpc.PartialForwardingClientCallListener.onReady()V PartialForwardingClientCallListener.java:44
#5 io.grpc.ForwardingClientCallListener.onReady()V ForwardingClientCallListener.java:23
#6 io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.o …
```

xds: Fix flow control data race in ControlPlanClient

---

xds/src/main/java/io/grpc/xds/ControlPlaneClient.java
xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java

The DNS lookups are taking considerable time on the Windows CI (~11s),
which causes the test to time out:
```
Wanted but not invoked:
ldsResourceWatcher.onError(<any>);
-> at io.grpc.xds.XdsClientImplTestBase.sendToNonexistentHost(XdsClientImplTestBase.java:3733)
Actually, there were zero interactions with this mock.
at io.grpc.xds.XdsClientImplTestBase.sendToNonexistentHost(XdsClientImplTestBase.java:3733)
```
The ARM build, which uses an emulator, has had this test succeed, so the
failure seems unrelated to CPU usage. We want to avoid external I/O
anyway during tests, so removing the DNS lookup is good.
The TSAN comment referenced XdsClientImplTestBase.sendToNonexistentHost,
but the test no longer calls fakeClock.forwardTime so the comment was
out-of-date. Change the comment to make …

xds: Avoid nonexistent DNS resolution in XdsClientImplV3Test

---

buildscripts/kokoro/windows.bat
buildscripts/kokoro/windows32.bat
buildscripts/kokoro/windows64.bat

This version of Java is old, but not as old as the Java 8 version.

buildscripts: Use Java 11 on Windows CI

---

xds/src/main/java/io/grpc/xds/InternalSharedXdsClientPoolProvider.java

When we implement A71, we're no longer going to have a single xds client, but instead one per channel target. Add that parameter now, even though it is unused, to avoid managing the (internal) API breakage when we implement fallback.

xds: Pre-add fallback to xds client pool accessor

---

CONTRIBUTING.md
benchmarks/build.gradle
gradle/libs.versions.toml
interop-testing/build.gradle
istio-interop-testing/build.gradle
netty/build.gradle

It wasn't actually being used. Since Java 8u252 in early 2020 we've been using ALPN from the JDK. The Jetty ALPN Agent has been a noop.
We do keep the Jetty ALPN support in the code and tests, but we don't have the infrastructure to actually run it.
-----
This is a re-do of #4857, but instead of swapping to Conscript we just use the JDK.

Remove build usages of Jetty ALPN

---

compiler/build.gradle

We had 'test.dependsOn', but it is only run if the golden tasks are configured, which they generally won't be because nothing depends on them. This prevented the test from actually running. This bug was introduced in 0ff9f37b because previously the golden tasks were eagerly constructed.
Remove the "extraPackage" argument because it is a constant and it confused me for a bit wondering when it was necessary.

compiler: actually add dependency on golden tests

---

gae-interop-testing/gae-jdk8/src/main/java/io/grpc/testing/integration/NettyClientInteropServlet.java
gae-interop-testing/gae-jdk8/src/main/webapp/WEB-INF/appengine-web.xml

The Java 8 runtime is end of support. Leaving this a gae-jdk8 for now. The gae-jdk8 was because AppEngine changed dramatically from Java 7 to Java 8. Nowadays the versions are more in line with OpenJDK and not very different from each other.
Fixes #10925
Backport of #10933
-------
We can do releases without this, and our users aren't impacted. But backporting it so the CI is a bit cleaner if we end up making patch releases.

Change GAE interop tests to use java11 runtime (1.62.x backport)

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

backport of https://github.com/grpc/grpc-java/pull/10960

xds: fix xdsNameResolver virtual host lookup using authority [1.62.x backport]

---

xds/src/test/java/io/grpc/xds/XdsClientFederationTest.java

`isolatedResourceDeletions()` has failed with a timeout waiting on onChanged when running under TSAN. TSAN can slow things down, so let's increase the timeout to ensure it isn't just timeout flake.

xds: Increase timeouts in XdsClientFederationTest

---

core/src/test/java/io/grpc/internal/ClientCallImplTest.java

We can just compare the Deadline instances instead of asserting that very little time has passed during the test. Real time probably still matters in the test, but only insofar that the deadline is not expired by the time ClientCallImpl sees it.
This fixes a test failure seen in the emulated aarch64 CI. Note that the message says "ns" when it should say "ms", but this change deletes the code with that typo.
```
java.lang.AssertionError: timeout: 548 ns
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at io.grpc.internal.ClientCallImplTest.assertTimeoutBetween(ClientCallImplTest.java:1102)
at io.grpc.internal.ClientCallImplTest.contextDeadlineShouldBePropagatedToStream(ClientCallImplTest.java:828)
```

core: Don't use real time when comparing deadline in ClientCallImplTest

---

gradle/libs.versions.toml
servlet/build.gradle
servlet/jakarta/build.gradle

This allows the checkForUpdates task to notice the dependencies and suggest updates.
I plan to upgrade some of the servers after this change in hopes it reduces test flakiness.

servlet: Move deps to version catalog

---

binder/src/main/java/io/grpc/binder/BinderChannelBuilder.java
binder/src/main/java/io/grpc/binder/BinderChannelCredentials.java

binder: Add missing Android API annotations

---

binder/src/main/java/io/grpc/binder/SecurityPolicies.java
binder/src/test/java/io/grpc/binder/SecurityPoliciesTest.java

In addition to removing a test that only applies to KitKat, switch other uses of '19' to Config.OLDEST_SDK when possible to test older SDK versions.
ref cl/609823012

roboelectric: Remove references to kitkat

---

.github/workflows/testing.yml
core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java
netty/src/main/java/io/grpc/netty/JettyTlsUtil.java
netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpChannelBuilderTest.java
okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/Platform.java
xds/src/test/java/io/grpc/xds/SharedCallCounterMapTest.java

SelfSignedCertificate is not available on Java 17 because OpenJdkSelfSignedCertGenerator is not available. This only impacted tests.
AccessController is being removed, and these locations are doing simple reflection which is unlikely to require it even when a security policy is in effect. There's other places we do reflection without the AccessController, so either no security policies care or the users can update their policies to allow it.

Fix tests and warnings on Java 17

---

android-interop-testing/src/androidTest/java/io/grpc/android/integrationtest/InteropInstrumentationTest.java

This is to improve investigation of a transient timeout error when running against the `grpc-test.sandbox.googleapis.com` host.

android-interop-testing: Improve errror logging

---

examples/src/main/java/io/grpc/examples/errorhandling/ErrorHandlingClient.java

Or rather, server response is ambiguous and this usage is not generally what we mean when we say it. The example shows how to get an error for any failed RPC, not just those coming from a failing server.
The existing comment caused confusion at
https://stackoverflow.com/a/78104828

examples: Error information is not in the server response

---

xds/src/main/java/io/grpc/xds/client/XdsResourceType.java

This method is only needed sometimes, and with time will be needed less and less. Don't require new types to implement it, instead relying on control planes to use the new approach.
CC @anicr7. See also #10975.

xds: Provide default XdsResourceType.extractResourceName impl

---

xds/src/main/java/io/grpc/xds/LoadBalancerConfigFactory.java
xds/src/main/java/io/grpc/xds/XdsClusterResource.java
xds/src/main/java/io/grpc/xds/client/XdsResourceType.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java
xds/src/test/java/io/grpc/xds/LoadBalancerConfigFactoryTest.java

They have been on by default for a good while, and seem stable. This also removes some grpc-isms from XdsResourceType.

xds: Remove WRR and PF experimental flags

---

xds/src/main/java/io/grpc/xds/XdsClusterResource.java
xds/src/main/java/io/grpc/xds/XdsRouteConfigureResource.java
xds/src/main/java/io/grpc/xds/client/XdsResourceType.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java

That's better for code organization and also removes some grpc-isms from XdsResourceType.

xds: Move LR and RLS experimental flags to where they are used

---

xds/src/main/java/io/grpc/xds/SharedXdsClientPoolProvider.java
xds/src/main/java/io/grpc/xds/client/XdsClientImpl.java

This removes a grpc-ism environment variable. Note that the logger is still registered under XdsClientImpl. That could maybe change, but it is a bit unclear what it should become and it seemed better for this to have no behavior changes.

xds: Move node id logging out of xds.client

---

binder/build.gradle
binder/src/main/java/io/grpc/binder/internal/MetadataHelper.java
binder/src/main/java/io/grpc/binder/internal/ParcelableInputStream.java
binder/src/test/java/io/grpc/binder/SecurityPoliciesTest.java
binder/src/test/java/io/grpc/binder/ServerSecurityPolicyTest.java
binder/src/test/java/io/grpc/binder/internal/ParcelableInputStreamTest.java
gradle/libs.versions.toml

binder: remove existing warnings and allow failOnWarnings

---

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java

The local race passes `rlsPicker` to the channel before CachingRlsLbClient is finished constructing. `RlsPicker` can use multiple of the fields not yet initialized. This seems not to be happening in practice, because it appears like it would break things very loudly (e.g., NPE).
The remote race seems incredibly hard to hit, because it requires an RPC to complete before the pending data tracking the RPC is added to a map. But with if a system is at 100% CPU utilization, maybe it can be hit. If it is hit, all RPCs needing the impacted cache entry will forever be buffered.
CC @temawi

rls: Fix a local and remote race

---

alts/build.gradle
auth/build.gradle
census/build.gradle
gcp-observability/build.gradle
testing/build.gradle

Override google-auth `io.grpc:grpc-context` dependency with our own `project(":grpc-context")`.
This fixes the issue with classes depending on `grpc-alts` implementation receiving very (!) old `io.grpc:grpc-context:1.27.2` as a transitive dependency of `com.google.auth`.   
Projects `grpc-census` `grpc-gcp-observability` are affected in the similar way, except `io.grpc:grpc-context:1.59.1` is pulled as  a transitive dependency of `io.opencensus`. 
```
❯ ./gradlew -q :grpc-xds:dependencyInsight --configuration=compileClasspath --dependency=io.grpc:grpc-context
*** Skipping the build of codegen and compilation of proto files because skipCodegen=true
* Skipping the build of Android projects because skipAndroid=true
io.grpc:grpc-context:1.27.2
Variant compile:
| Attribute Name …
```

alts,census,gcp-observability: Explicitly set grpc-context as an implementation dependency

---

core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/main/java/io/grpc/internal/PickFirstLeafLoadBalancer.java
core/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java
core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java
core/src/test/java/io/grpc/internal/PickFirstLoadBalancerProviderTest.java
interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
util/src/test/java/io/grpc/util/MultiChildLoadBalancerTest.java
util/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java
util/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
util/src/testFixtures/java/io/grpc/util/AbstractTestHelper.java
xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/test/java/io/grpc/xds/LeastRequestLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java

Fix PFLeafLB to use EAG attributes instead of dropping them.
Fix tests to handle expectated behavior changes of new PFLB
Trim flag value before passing it to Boolean.parse so that extra spaces at the end don't interpreet a "true " as false.

Switch flag to use new PickFirstLeafLoadBalancer by default

---

xds/src/main/java/io/grpc/xds/CsdsService.java

To make it stable, this PR hides protobuf from being exposed via the API.
Note: this breaks ABI of `CsdsService.streamClientStatus` and `CsdsService.fetchClientStatus`, but these methods should not normally be called by the user.
Closes #8016.

xds: Stabilize CsdsService

---

gradle/libs.versions.toml

Related issue blocking the update (#10396) was created during dependency update #10359, but I forgot to add the note to libs.versions.toml.

(minor) Add missing update notes for cronet to libs.versions.toml

---

core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/test/java/io/grpc/internal/ClientCallImplTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

We provided extra details when the RPC is killed because of CallOptions' Deadline, but didn't do the same for Context.
To avoid duplicating code, things were restructured, including the threading. There are more code flows now, but I think the multi-threading came out more obvious and less error-prone. I didn't change the status when the deadline is already expired, because the text is shared with DelayedClientCall and AbstractInteropTest doesn't distinguish between the two cases.
As seen at b/300991330

core: Provide DEADLINE_EXCEEDED insights for context deadline

---

core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/test/java/io/grpc/internal/ClientCallImplTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

Reverts grpc/grpc-java#11017
This causes a NPE if cancel is called before starting the call.

Revert "core: Provide DEADLINE_EXCEEDED insights for context deadline"

---

api/src/main/java/io/grpc/CallOptions.java
api/src/main/java/io/grpc/PartialForwardingServerCall.java
api/src/main/java/io/grpc/ServerCall.java
binder/src/main/java/io/grpc/binder/internal/MultiMessageServerStream.java
binder/src/main/java/io/grpc/binder/internal/SingleMessageServerStream.java
core/src/main/java/io/grpc/internal/AbstractClientStream.java
core/src/main/java/io/grpc/internal/AbstractServerStream.java
core/src/main/java/io/grpc/internal/AbstractStream.java
core/src/main/java/io/grpc/internal/Http2ClientStreamTransportState.java
core/src/main/java/io/grpc/internal/ServerCallImpl.java
core/src/main/java/io/grpc/internal/ServerStream.java
core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
core/src/test/java/io/grpc/internal/AbstractServerStreamTest.java
core/src/test/java/io/grpc/internal/Http2ClientStreamTransportStateTest.java
core/src/test/java/io/grpc/internal/ServerCallImplTest.java
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java
inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java
netty/src/main/java/io/grpc/netty/NettyClientStream.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientStreamTest.java
stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java
stub/src/main/java/io/grpc/stub/ServerCalls.java
stub/src/test/java/io/grpc/stub/ServerCallsTest.java
util/src/main/java/io/grpc/util/TransmitStatusRuntimeExceptionInterceptor.java

- on clients this is exposed by setting a CallOption
- on servers this is configured by calling a method on ServerCall or ServerStreamListener

Allow configuration of the queued byte threshold at which a Stream is considered not ready

---

core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/test/java/io/grpc/internal/ClientCallImplTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

We provided extra details when the RPC is killed because of CallOptions' Deadline, but didn't do the same for Context.
To avoid duplicating code, things were restructured, including the threading. There are more code flows now, but I think the multi-threading came out more obvious and less error-prone. I didn't change the status when the deadline is already expired, because the text is shared with DelayedClientCall and AbstractInteropTest doesn't distinguish between the two cases.
As seen at b/300991330
-----
This is a roll-forward of #11017 which was rolled back in #11024. I kept the first commit identical to the earlier one for easier review. The second commit has the fix. I'll squash them together when merging.
CC @temawi

core: Provide DEADLINE_EXCEEDED insights for context deadline (take 2)

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

Future.cancel can return true when the executable has started, but the future value hasn't yet been set which was causing us to do an extra decrement.  That is what was causing `DriveSimControllerRuleTest` to fail with the first attempt to fix the retry deadlock.

Fix retry race condition that can lead to double decrementing inFlightSubStreams and so miss calling closed

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

Future.cancel can return true when the executable has started, but the future value hasn't yet been set which was causing us to do an extra decrement.  That is what was causing `DriveSimControllerRuleTest` to fail with the first attempt to fix the retry deadlock.
Backport of #11026

Fix retry race condition that can lead to double decrementing inFlightSubStreams and so miss calling closed (1.61.x backport)

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

Future.cancel can return true when the executable has started, but the future value hasn't yet been set which was causing us to do an extra decrement.  That is what was causing `DriveSimControllerRuleTest` to fail with the first attempt to fix the retry deadlock.
Backport of #11026

Fix retry race condition (1.62.x backport)

---

util/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
util/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

Including a Status description makes it easier to debug subchannel closure issues if it's clear that a subchannel became unavailable because of an outlier detection ejection.
Fixes #10673

util: Status desc for outlier detection ejection

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

Future.cancel can return true when the executable has started, but the future value hasn't yet been set which was causing us to do an extra decrement.  That is what was causing `DriveSimControllerRuleTest` to fail with the first attempt to fix the retry deadlock.
Backport of #11026

Fix retry race condition (1.63.x backport)

---

servlet/src/main/java/io/grpc/servlet/AsyncServletOutputStreamWriter.java

servlet: Check log fine level before hex string conversion. Fixes #11031. (1.62.x backport)

---

servlet/src/main/java/io/grpc/servlet/AsyncServletOutputStreamWriter.java

Backport of #11032
CC @hypnoce

servlet: Check log fine level before hex string conversion. Fixes #11031. (1.63.x backport)

---

stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java

This change fixes existing users broke by https://github.com/grpc/grpc-java/pull/10977

Make setOnReadyThreshold() a noop method instead of abstract.

---

authz/src/main/java/io/grpc/authz/AuthorizationPolicyTranslator.java
benchmarks/src/main/java/io/grpc/benchmarks/Transport.java
benchmarks/src/main/java/io/grpc/benchmarks/qps/ClientConfiguration.java
benchmarks/src/main/java/io/grpc/benchmarks/qps/ServerConfiguration.java
build.gradle
interop-testing/src/main/java/io/grpc/testing/integration/Http2TestCases.java
interop-testing/src/main/java/io/grpc/testing/integration/StressTestClient.java
interop-testing/src/main/java/io/grpc/testing/integration/TestCases.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
xds/src/main/java/io/grpc/xds/XdsClusterResource.java
xds/src/main/java/io/grpc/xds/internal/Matchers.java
xds/src/main/java/io/grpc/xds/internal/security/trust/XdsX509TrustManager.java

None of these conversions should use the arbitrary system locale. Error Prone will help prevent these getting introduced in the future.
Fixes #10372

Specify a locale for upper/lower case conversions

---

authz/src/main/java/io/grpc/authz/AuthorizationPolicyTranslator.java
benchmarks/src/main/java/io/grpc/benchmarks/Transport.java
benchmarks/src/main/java/io/grpc/benchmarks/qps/ClientConfiguration.java
benchmarks/src/main/java/io/grpc/benchmarks/qps/ServerConfiguration.java
build.gradle
interop-testing/src/main/java/io/grpc/testing/integration/Http2TestCases.java
interop-testing/src/main/java/io/grpc/testing/integration/StressTestClient.java
interop-testing/src/main/java/io/grpc/testing/integration/TestCases.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
xds/src/main/java/io/grpc/xds/XdsClusterResource.java
xds/src/main/java/io/grpc/xds/internal/Matchers.java
xds/src/main/java/io/grpc/xds/internal/security/trust/XdsX509TrustManager.java

None of these conversions should use the arbitrary system locale. Error Prone will help prevent these getting introduced in the future.
Fixes #10372
Backport of #11049

Specify a locale for upper/lower case conversions (1.63.x backport)

---

xds/src/main/java/io/grpc/xds/internal/security/trust/XdsX509TrustManager.java
xds/src/test/java/io/grpc/xds/internal/security/trust/XdsX509TrustManagerTest.java

Setting a null endpoint identification algorithm gets ignored in Sun's
SSLEngine implementation.
Fixes #10810.

xds: Use empty string when disabling server hostname verification

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

Fixes #11053: make sure to remove finished stream in okhttp client transport even if a pending stream was started.

Fix OkHTTP client transport leak

---

README.md

You have to dig deep into SECURITY.md to hear about what's in netty-shaded. Add a small blub for it in the README.
Inspired by discussion on #10931

README.md: Mention the netty-shaded "transport"

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

Fixes #11053: make sure to remove finished stream in okhttp client transport even if a pending stream was started.
Backport of #11054
CC @hypnoce

Fix OkHTTP client transport leak (1.62.x backport)

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

Fixes #11053: make sure to remove finished stream in okhttp client transport even if a pending stream was started.
Backport of #11054
CC @hypnoce

Fix OkHTTP client transport leak (1.63.x backport)

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpServerBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpServerTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpServerTransportTest.java

* Add option in OkHttpServerBuilder
* Add value as MAX_CONCURRENT_STREAM setting in settings frame sent by the server to the client per connection
* Enforce limit by sending a RST frame with REFUSED_STREAM error
This PR is really a try since I may be not enough familiar with all gRPC internals. Let me know if I'm too far from a correct solution.

OkHttpServer: support maxConcurrentCallsPerConnection (Fixes #11062).

---

examples/BUILD.bazel

According to the docs, I can use bazel to build examples, but retry-example is not supported in bazel config. So If you'll try to build this example with bazel, you'll get an error:
```
examples git:(master) ✗ bazel build :retrying-hello-world-server :retrying-hello-world-client
ERROR: Skipping ':retrying-hello-world-client': no such target '//:retrying-hello-world-client': target 'retrying-hello-world-client' not declared in package '' defined by /Users/rostik404/projects/grpc-java/examples/BUILD.bazel
ERROR: no such target '//:retrying-hello-world-client': target 'retrying-hello-world-client' not declared in package '' defined by /Users/rostik404/projects/grpc-java/examples/BUILD.bazel
INFO: Elapsed time: 0.331s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

examples: support retry policy example for bazel build

---

stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java

This change fixes existing users broke by https://github.com/grpc/grpc-java/pull/10977
Backport of #11044

Make setOnReadyThreshold() a noop method instead of abstract. (1.63.x backport)

---

xds/src/main/java/io/grpc/xds/internal/security/trust/XdsX509TrustManager.java
xds/src/test/java/io/grpc/xds/internal/security/trust/XdsX509TrustManagerTest.java

Setting a null endpoint identification algorithm gets ignored in Sun's
SSLEngine implementation.
Fixes #10810.
Backport of #11052

xds: Use empty string when disabling server hostname verification (1.63.x backport)

---

build.gradle
compiler/src/test/golden/TestDeprecatedService.java.txt
compiler/src/test/golden/TestService.java.txt
compiler/src/testLite/golden/TestDeprecatedService.java.txt
compiler/src/testLite/golden/TestService.java.txt
core/src/main/java/io/grpc/internal/GrpcUtil.java
examples/android/clientcache/app/build.gradle
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/strictmode/app/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-debug/build.gradle
examples/example-debug/pom.xml
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-gcp-observability/build.gradle
examples/example-hostname/build.gradle
examples/example-hostname/pom.xml
examples/example-jwt-auth/build.gradle
examples/example-jwt-auth/pom.xml
examples/example-oauth/build.gradle
examples/example-oauth/pom.xml
examples/example-orca/build.gradle
examples/example-reflection/build.gradle
examples/example-servlet/build.gradle
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/example-xds/build.gradle
examples/pom.xml

This reverts commit 338a687fcf0a2c17e469d130492064cd7b4ac955.
Looks a mistake. The  "Start 1.64.0 development cycle" should only be on the [master branch](https://github.com/grpc/grpc-java/commit/b3ffb5078df361d7460786e134db7b5c00939246)

Revert "Start 1.64.0 development cycle"

---

.github/workflows/testing.yml
MODULE.bazel
repositories.bzl

The text between the GRPC_DEPS_{START,END} must be identical in formatting. Probably not a problem in general and not necessarily bad. But it is simplistic.
Eric waking up this morning:
> We need more sed.

bazel: Verify Maven deps in bzlmod and WORKSPACE match

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh
buildscripts/xds-k8s/cloudbuild.yaml

buildscripts: Migrate PSM Interop to Artifact Registry

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh
buildscripts/xds-k8s/cloudbuild.yaml

Backport of #11079 to v1.63.x.
---

buildscripts: Migrate PSM Interop to Artifact Registry (v1.63.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh
buildscripts/xds-k8s/cloudbuild.yaml

Backport of #11079 to v1.62.x.
---

buildscripts: Migrate PSM Interop to Artifact Registry (v1.62.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh
buildscripts/xds-k8s/cloudbuild.yaml

Backport of #11079 to v1.61.x.
---

buildscripts: Migrate PSM Interop to Artifact Registry (v1.61.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh
buildscripts/xds-k8s/cloudbuild.yaml

Backport of #11079 to v1.60.x.
---

buildscripts: Migrate PSM Interop to Artifact Registry (v1.60.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh
buildscripts/xds-k8s/cloudbuild.yaml

Backport of #11079 to v1.59.x.
---

buildscripts: Migrate PSM Interop to Artifact Registry (v1.59.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh
buildscripts/xds-k8s/cloudbuild.yaml

Backport of #11079 to v1.58.x.
---

buildscripts: Migrate PSM Interop to Artifact Registry (v1.58.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh
buildscripts/xds-k8s/cloudbuild.yaml

Backport of #11079 to v1.57.x.
---

buildscripts: Migrate PSM Interop to Artifact Registry (v1.57.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh
buildscripts/xds-k8s/cloudbuild.yaml

Backport of #11079 to v1.56.x.
---

buildscripts: Migrate PSM Interop to Artifact Registry (v1.56.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh
buildscripts/xds-k8s/cloudbuild.yaml

Backport of #11079 to v1.54.x.
---

buildscripts: Migrate PSM Interop to Artifact Registry (v1.54.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh
buildscripts/xds-k8s/cloudbuild.yaml

Backport of #11079 to v1.55.x.
---

buildscripts: Migrate PSM Interop to Artifact Registry (v1.55.x backport)

---

api/src/main/java/io/grpc/DoubleCounterMetricInstrument.java
api/src/main/java/io/grpc/DoubleHistogramMetricInstrument.java
api/src/main/java/io/grpc/LongCounterMetricInstrument.java
api/src/main/java/io/grpc/LongGaugeMetricInstrument.java
api/src/main/java/io/grpc/LongHistogramMetricInstrument.java
api/src/main/java/io/grpc/MetricInstrument.java
api/src/main/java/io/grpc/MetricInstrumentRegistry.java
api/src/main/java/io/grpc/PartialMetricInstrument.java

This PR adds Metric Instrument Registry which provides APIs to register gRPC specific metric instruments. Metric instruments has the necessary information needed to create a metric (e.g. OpenTelemetry based metric).
This is one of the initial PRs (of many) for gRPC metrics architecture / framework described in [gRFC A79](https://github.com/grpc/proposal/blob/master/A79-non-per-call-metrics-architecture.md).
Unit tests will be added in a follow up PR.

Add Metric Instrument Registry

---

core/src/main/java/io/grpc/internal/AbstractServerStream.java
core/src/main/java/io/grpc/internal/AbstractStream.java
netty/src/main/java/io/grpc/netty/NettyClientStream.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/netty/NettyServerStream.java
netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
netty/src/test/java/io/grpc/netty/NettyServerStreamTest.java

Handles Netty write frame failures caused by issues in the Netty itself.
Normally we don't need to do anything on frame write failures because the cause of a failed future would be an IO error that resulted in the stream closure.  Prior to this PR we treated these issues as a noop, except the initial headers write on the client side.
However, a case like netty/netty#13805 (a bug in generating next stream id) resulted in an unclosed stream on our side.
This PR adds write frame future failure handlers that ensures the stream is cancelled, and the cause is propagated via Status.
Fixes #10849

netty: Handle write queue promise failures

---

MODULE.bazel
WORKSPACE
java_grpc_library.bzl

Loads are being added in preparation for moving the symbols out of Bazel and into `rules_java`.
ref cl/623147910

Add `load()` statements for the Bazel builtin top-level java symbols

---

alts/src/main/java/io/grpc/alts/AltsChannelBuilder.java
alts/src/main/java/io/grpc/alts/ComputeEngineChannelBuilder.java
alts/src/main/java/io/grpc/alts/GoogleDefaultChannelBuilder.java
alts/src/test/java/io/grpc/alts/internal/AltsHandshakerStubTest.java
core/src/testFixtures/java/io/grpc/internal/TestUtils.java
examples/src/main/java/io/grpc/examples/routeguide/RouteGuideServer.java

minor: remove the unnecessary final,static

---

compiler/build.gradle
compiler/src/java_plugin/cpp/java_generator.cpp
compiler/src/java_plugin/cpp/java_generator.h
compiler/src/java_plugin/cpp/java_plugin.cpp
compiler/src/testLite/golden/TestDeprecatedService.java.txt
compiler/src/testLite/golden/TestService.java.txt

compiler: add option `@generated=omit`

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
util/src/test/java/io/grpc/util/MultiChildLoadBalancerTest.java
xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java
xds/src/main/java/io/grpc/xds/LazyLoadBalancer.java
xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java

I can leave the three commits as separate when merging. The changes to MultiChildLb itself are pretty easy. Most of the review will be in the two earlier commits which remove the dependency on these features.
I think this exposes some other potential cleanups, but I didn't want to bring in too much.

Remove deactivation and GracefulSwitchLb from MultiChildLb

---

cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java
cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java
cronet/src/main/java/io/grpc/cronet/InternalCronetChannelBuilder.java
cronet/src/test/java/io/grpc/cronet/CronetChannelBuilderTest.java
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java
cronet/src/test/java/io/grpc/cronet/CronetClientTransportTest.java
gradle/libs.versions.toml

In this Pull Request
1. Cronet is updated to `119.6045.31` from `108.5359.79`, In which Experimental API's are deprecated and moved to Stable Interfaces.
2. grpc-cronet Moved Experimental API's to Stable Interfaces
3. Removed use of reflection as Experimental API's are no longer in use (which are introdced in #6111)
Minor Changes
1. Updated JavaDoc : Android Permission from [`MODIFY_NETWORK_ACCOUNTING` (deprecated)](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/AndroidManifest.xml#6416) to `UPDATE_DEVICE_STATS`
2. Update to JAVA-8 API's to improve code readability
3. Moved from `Charset.forName("UTF-8")` to `StandardCharsets.UTF_8` Standard
Fixes #10396 (@sergiitk)

cronet : Update library + Move to StableAPIs in Cronet

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java

`sendGrpcFrame` owns the buffer in `SendGrpcFrameCommand`. If the frame is not handed off to netty, it needs to be released in the method.
https://github.com/grpc/grpc-java/issues/11115

netty: Release SendGrpcFrameCommand when stream is missing

---

netty/src/main/java/io/grpc/netty/CancelServerStreamCommand.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/netty/NettyServerStream.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
netty/src/test/java/io/grpc/netty/NettyServerStreamTest.java

Relevant to https://github.com/grpc/grpc-java/issues/3996
Today, if the deframer encounters an error it will trigger a stream reset. This does not provide the peer with much information about _why_ the stream was reset. In particular, if a client sends an oversized message, the server will
reject the request, but the client will see that as a `CANCELLED` status code rather than a `RESOURCE_EXHAUSTED`.
grpc-go servers do provide this information to clients, and I think that's helpful.
This PR is an attempt to provide best-effort status codes to peers on deframer errors. @ejona86 explained ([here](https://github.com/grpc/grpc-java/issues/3996#issuecomment-2033080658)) that it will not always be possible for the stream to gracefully close with properly encoded trailers. In these cases the …

Allow deframer errors to close stream with a status code

---

protobuf/src/main/java/io/grpc/protobuf/StatusProto.java
protobuf/src/test/java/io/grpc/protobuf/StatusProtoTest.java

Add `StatusProto.toStatusException` overload to accept `Throwable`

---

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
rls/src/main/java/io/grpc/rls/LbPolicyConfiguration.java

Instead of having docs in RefCountedChildPolicyWrapperFactory saying that every method was guarded by a lock, I added `@GuardedBy("lock")` within CachingRlsLbClient, so now it is clearly not thread-safe and the lock protects access. The AtomicLong was replaced with a long since 1) there was no multi-threading and 2) the logic was not atomic-safe which was misleading.

rls: Document RefCountedChildPolicyWrapperFactory as non-threadsafe

---

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
rls/src/main/java/io/grpc/rls/LinkedHashLruCache.java

`getMinEvictionTime()` was fixed to make sure only deltas were used for comparisons (`a < b` is broken; `a - b < 0` is okay). It had also returned `0` by default, which was meaningless as there is no epoch for `System.nanoTime()`. LinkedHashLruCache now passes the current time into a few more functions since the implementations need it and it was sometimes already available. This made it easier to make some classes static.

rls: Fix time handling in CachingRlsLbClient

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java

`sendGrpcFrame` owns the buffer in `SendGrpcFrameCommand`. If the frame is not handed off to netty, it needs to be released in the method.
https://github.com/grpc/grpc-java/issues/11115
Backport of #11116

netty: Release SendGrpcFrameCommand when stream is missing (1.63.x backport)

---

api/src/main/java/io/grpc/DoubleCounterMetricInstrument.java
api/src/main/java/io/grpc/DoubleHistogramMetricInstrument.java
api/src/main/java/io/grpc/LongCounterMetricInstrument.java
api/src/main/java/io/grpc/LongGaugeMetricInstrument.java
api/src/main/java/io/grpc/LongHistogramMetricInstrument.java
api/src/main/java/io/grpc/MetricInstrument.java
api/src/main/java/io/grpc/MetricInstrumentRegistry.java
api/src/main/java/io/grpc/MetricRecorder.java
api/src/main/java/io/grpc/MetricSink.java
api/src/main/java/io/grpc/PartialMetricInstrument.java
api/src/test/java/io/grpc/MetricInstrumentRegistryTest.java
api/src/testFixtures/java/io/grpc/MetricInstrumentRegistryAccessor.java
core/src/main/java/io/grpc/internal/MetricRecorderImpl.java
core/src/test/java/io/grpc/internal/MetricRecorderImplTest.java

This PR adds an internal implementation for `MetricRecorder` interface. And adds unit tests for `MetricInstrumentRegistry`.

Add MetricRecorder implementation

---

api/src/main/java/io/grpc/ClientStreamTracer.java
api/src/main/java/io/grpc/LoadBalancer.java
api/src/testFixtures/java/io/grpc/PickSubchannelArgsMatcher.java
core/src/main/java/io/grpc/internal/DelayedClientTransport.java
core/src/main/java/io/grpc/internal/ForwardingClientStreamTracer.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/PickDetailsConsumerImpl.java
core/src/main/java/io/grpc/internal/PickSubchannelArgsImpl.java
core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/ManagedChannelServiceConfigTest.java
interop-testing/src/test/java/io/grpc/testing/integration/RpcBehaviorLoadBalancerProviderTest.java
rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
util/src/main/java/io/grpc/util/ForwardingClientStreamTracer.java
xds/src/test/java/io/grpc/xds/ClusterManagerLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

As part of gRFC A78:
> To support the locality label in the per-call metrics, we will provide
> a mechanism for LB picker to add optional labels to the call attempt
> tracer.
-----
@temawi, I'm suspecting you may be the best to review this, because you already have some context. Most lines changed are in tests. We can discuss.
(I have [another commit](https://github.com/ejona86/grpc-java/tree/xds-locality-weight-target) prepared that will follow this one (because the tests collide), to plumb locality to WRR)

Plumb optional labels from LB to ClientStreamTracer

---

api/src/main/java/io/grpc/LoadBalancer.java

Since 06df25b65d, WRR has been calling this method, and it will get an exception. We don't want WRR to be broken until we have MetricRecorder fully plumbed.
CC @DNVindhya

api: Return a noop MetricRecorder from Helper by default

---

api/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplGetNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
util/src/main/java/io/grpc/util/ForwardingLoadBalancerHelper.java

gRFC A78 has WRR and pick-first include a `grpc.target` label, defined in A66:
> `grpc.target` : Canonicalized target URI used when creating gRPC
> Channel, e.g. "dns:///pubsub.googleapis.com:443",
> "xds:///helloworld-gke:8000". Canonicalized target URI is the form
> with the scheme included if the user didn't mention the scheme
> (`scheme://[authority]/path`). For channels such as inprocess channels
> where a target URI is not available, implementations can synthesize a
> target URI.
CC @DNVindhya

Plumb target to load balancer

---

api/src/main/java/io/grpc/LoadBalancer.java
rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java

Adds the following metrics to the RlsLoadBalancer:
- grpc.lb.rls.default_target_picks
- grpc.lb.rls.target_picks
- grpc.lb.rls.failed_picks
Still missing the labels, that will be added in a later PR.

rls: add counter metrics

---

xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

The channel target is now available via the `Helper`, let's record it as a label with the various metrics we track in `WeightedRoundRobinLoadBalancer`.

xds: include the target label to WRR metrics

---

api/src/main/java/io/grpc/Configurator.java
api/src/main/java/io/grpc/ConfiguratorRegistry.java
api/src/main/java/io/grpc/DoubleHistogramMetricInstrument.java
api/src/main/java/io/grpc/LongCounterMetricInstrument.java
api/src/main/java/io/grpc/LongGaugeMetricInstrument.java
api/src/main/java/io/grpc/LongHistogramMetricInstrument.java
api/src/main/java/io/grpc/MetricInstrumentRegistry.java
api/src/main/java/io/grpc/MetricSink.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/MetricRecorderImpl.java
core/src/main/java/io/grpc/internal/ServerImplBuilder.java
core/src/test/java/io/grpc/internal/ManagedChannelImplBuilderTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/MetricRecorderImplTest.java
opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryMetricSink.java
opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryMetricsModule.java
opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryMetricsResource.java
opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryModule.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryMetricSinkTest.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryMetricsModuleTest.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryModuleTest.java

This PR adds following components that are required for gRPC Non per call metrics architecture.
- MetricSink implementation for gRPC OpenTelemetry
- Configurator for plumbing per call metrics ClientInterceptor and ServerStreamTracer.Factory via unified OpenTelemetryModule.

Adds MetricSink implementation for gRPC OpenTelemetry

---

xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/main/java/io/grpc/xds/InternalXdsAttributes.java
xds/src/main/java/io/grpc/xds/WeightedTargetLoadBalancer.java
xds/src/main/java/io/grpc/xds/WrrLocalityLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WeightedTargetLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WrrLocalityLoadBalancerTest.java

As part of gRFC A78:
> To support the locality label in the WRR metrics, we will extend the
> `weighted_target` LB policy (see A28) to define a resolver attribute
> that indicates the name of its child. This attribute will be passed
> down to each of its children with the appropriate value, so that any
> LB policy that sits underneath the `weighted_target` policy will be
> able to use it.
xds_cluster_impl is involved because it uses the child names in the AddressFilter, which must match the names used by weighted_target. Instead of using Locality.toString() in multiple policies and assuming the policies agree, we now have xds_cluster_impl decide the locality's name and pass it down explicitly. This allows us to change the name format to match gRFC A78:
> If locality information is …

xds: Plumb locality in xds_cluster_impl and weighted_target

---

api/src/main/java/io/grpc/CallbackMetricInstrument.java
api/src/main/java/io/grpc/MetricRecorder.java
api/src/main/java/io/grpc/MetricSink.java
core/src/main/java/io/grpc/internal/MetricRecorderImpl.java
core/src/test/java/io/grpc/internal/MetricRecorderImplTest.java
opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryMetricSink.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryMetricSinkTest.java

This is needed by gRFC A78 for xds metrics, and for RLS metrics. Since gauges need to acquire a lock (or other synchronization) in the callback, the callback allows batching multiple gauges together to avoid acquiring-and-requiring such locks.
Unlike other metrics, gauges are reported on-demand to the MetricSink. This means not all sinks will receive the same data, as the sinks will ask for the gauges at different times.

Add gauge metric API and Otel implementation

---

opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryMetricsModule.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryMetricsModuleTest.java

From gRFC A78:
> If no locality information is available, the label will be set to the
> empty string.

opentelemetry: Missing locality should be empty string

---

core/src/main/java/io/grpc/internal/PickFirstLeafLoadBalancer.java
core/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java
core/src/test/java/io/grpc/internal/PickFirstLeafLoadBalancerTest.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
xds/src/main/java/io/grpc/xds/XdsEndpointResource.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

Some g3 users are seeing problems.
Put the flag logic in a common place for PickFirstLeafLoadBalancer & WRR's test.

Change HappyEyeballs and new pick first LB flags default value to false

---

api/build.gradle
api/src/main/java/io/grpc/ForwardingChannelBuilder2.java
api/src/main/java/io/grpc/InternalManagedChannelBuilder.java
api/src/main/java/io/grpc/LoadBalancer.java
api/src/main/java/io/grpc/ManagedChannelBuilder.java
api/src/main/java/io/grpc/MetricSink.java
core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java
opentelemetry/src/main/java/io/grpc/opentelemetry/GrpcOpenTelemetry.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

Some APIs were marked experimental but had internal APIs in their surface. These were all changed to internal. And then the internal APIs were mostly hidden from generated documentation.
All these APIs will eventually become public and maybe even stable. But they need some iteration before we're ready for others to start using them.
CC @DNVindhya

api: Hide internal metric APIs

---

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java

Adds these gauges:
- grpc.lb.rls.cache_entries
- grpc.lb.rls.cache_size

rls: Add gauge metric recording

---

api/src/main/java/io/grpc/Configurator.java
api/src/main/java/io/grpc/ConfiguratorRegistry.java
api/src/main/java/io/grpc/DoubleHistogramMetricInstrument.java
api/src/main/java/io/grpc/LongCounterMetricInstrument.java
api/src/main/java/io/grpc/LongGaugeMetricInstrument.java
api/src/main/java/io/grpc/LongHistogramMetricInstrument.java
api/src/main/java/io/grpc/MetricInstrumentRegistry.java
api/src/main/java/io/grpc/MetricSink.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/MetricRecorderImpl.java
core/src/main/java/io/grpc/internal/ServerImplBuilder.java
core/src/test/java/io/grpc/internal/ManagedChannelImplBuilderTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/MetricRecorderImplTest.java
opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryMetricSink.java
opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryMetricsModule.java
opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryMetricsResource.java
opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryModule.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryMetricSinkTest.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryMetricsModuleTest.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryModuleTest.java

This PR adds following components that are required for gRPC Non per call metrics architecture.
- MetricSink implementation for gRPC OpenTelemetry
- Configurator for plumbing per call metrics ClientInterceptor and ServerStreamTracer.Factory via unified OpenTelemetryModule.
Backport of #11140

Adds MetricSink implementation for gRPC OpenTelemetry (1.64.x backport)

---

xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/main/java/io/grpc/xds/InternalXdsAttributes.java
xds/src/main/java/io/grpc/xds/WeightedTargetLoadBalancer.java
xds/src/main/java/io/grpc/xds/WrrLocalityLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WeightedTargetLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WrrLocalityLoadBalancerTest.java

As part of gRFC A78:
> To support the locality label in the WRR metrics, we will extend the
> `weighted_target` LB policy (see A28) to define a resolver attribute
> that indicates the name of its child. This attribute will be passed
> down to each of its children with the appropriate value, so that any
> LB policy that sits underneath the `weighted_target` policy will be
> able to use it.
xds_cluster_impl is involved because it uses the child names in the AddressFilter, which must match the names used by weighted_target. Instead of using Locality.toString() in multiple policies and assuming the policies agree, we now have xds_cluster_impl decide the locality's name and pass it down explicitly. This allows us to change the name format to match gRFC A78:
> If locality information is …

xds: Plumb locality in xds_cluster_impl and weighted_target (1.64.x backport)

---

core/src/main/java/io/grpc/internal/PickFirstLeafLoadBalancer.java
core/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java
core/src/test/java/io/grpc/internal/PickFirstLeafLoadBalancerTest.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
xds/src/main/java/io/grpc/xds/XdsEndpointResource.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

Change HappyEyeballs and new pick first LB flags default value to false (1.63.x backport)

---

opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryMetricsModule.java

CC @DNVindhya 
Backport of #11155

opentelemetry: Fix checking wrong metric for null (1.64.x backport)

---

api/src/main/java/io/grpc/ForwardingChannelBuilder2.java
api/src/main/java/io/grpc/InternalManagedChannelBuilder.java
api/src/main/java/io/grpc/ManagedChannelBuilder.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java
core/src/test/java/io/grpc/internal/ManagedChannelImplBuilderTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplGetNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/ServiceConfigErrorHandlingTest.java
opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryMetricsModule.java
opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryModule.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryMetricsModuleTest.java

You'll probably want to look at the two commits separately. I am sending them in one PR because the second commit shows "what the heck Eric is doing." Each commit has a useful commit message.
I can't say I'm wild about this solution at the current state, but there are some options for getting us out of this strangeness. We need to have a team discussion, and the only thing we guarantee here that might be hard to undo is "when you configure a channel with opentelemetry, that dictates the interceptor order." Which seems appropriate for all solutions.
Backport of #11153

Plumb target to OpenTelemetry per-call metrics (1.64.x backport)

---

api/src/main/java/io/grpc/CallbackMetricInstrument.java
api/src/main/java/io/grpc/MetricRecorder.java
api/src/main/java/io/grpc/MetricSink.java
core/src/main/java/io/grpc/internal/MetricRecorderImpl.java
core/src/test/java/io/grpc/internal/MetricRecorderImplTest.java
opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryMetricSink.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryMetricSinkTest.java

This is needed by gRFC A78 for xds metrics, and for RLS metrics. Since gauges need to acquire a lock (or other synchronization) in the callback, the callback allows batching multiple gauges together to avoid acquiring-and-requiring such locks.
Unlike other metrics, gauges are reported on-demand to the MetricSink. This means not all sinks will receive the same data, as the sinks will ask for the gauges at different times.
Backport of #11154

Add gauge metric API and Otel implementation (1.64.x backport)

---

opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryMetricsModule.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryMetricsModuleTest.java

From gRFC A78:
> If no locality information is available, the label will be set to the
> empty string.
Backport of #11172

opentelemetry: Missing locality should be empty string (1.64.x backport)

---

opentelemetry/src/main/java/io/grpc/opentelemetry/GrpcOpenTelemetry.java
opentelemetry/src/test/java/io/grpc/opentelemetry/GrpcOpenTelemetryTest.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryMetricsModuleTest.java

OpenTelemetryModule is renamed to GrpcOpenTelemetry. The Builder is now `final`, although that should only impact mocks as it had a private constructor.
Fixes #10591
Backport of #11173

opentelemetry: Rename and stabilize API OpenTelemetryModule (1.64.x backport)

---

api/build.gradle
api/src/main/java/io/grpc/ForwardingChannelBuilder2.java
api/src/main/java/io/grpc/InternalManagedChannelBuilder.java
api/src/main/java/io/grpc/LoadBalancer.java
api/src/main/java/io/grpc/ManagedChannelBuilder.java
api/src/main/java/io/grpc/MetricSink.java
core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java
opentelemetry/src/main/java/io/grpc/opentelemetry/GrpcOpenTelemetry.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

Some APIs were marked experimental but had internal APIs in their surface. These were all changed to internal. And then the internal APIs were mostly hidden from generated documentation.
All these APIs will eventually become public and maybe even stable. But they need some iteration before we're ready for others to start using them.
Backport of #11174

api: Hide internal metric APIs (1.64.x backport)

---

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java

Adds these gauges:
- grpc.lb.rls.cache_entries
- grpc.lb.rls.cache_size
Backport of #11175

rls: Add gauge metric recording (1.64.x backport)

---

opentelemetry/build.gradle
opentelemetry/src/main/java/io/grpc/opentelemetry/GrpcOpenTelemetry.java

This PR enables publishing for grpc-opentelemetry module.

opentelemetry: Publish grpc opentelemetry

---

opentelemetry/build.gradle
opentelemetry/src/main/java/io/grpc/opentelemetry/GrpcOpenTelemetry.java

This PR enables publishing for grpc-opentelemetry module.
Backport of #11187.

opentelemetry: Publish grpc opentelemetry (v1.64.x backport)

---

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java

This PR 
- Updates WRR and RLS metrics to be experimental and therefore disabled by default.
From gRFC A78:
> Metric Stability
>
> All metrics added in this proposal will start as experimental and therefore off by default.
- Adds "Experimental." in the beginning of metric description. 
- Updates metric units  to include `{}`, as strings inside `{}` are suffixed to metric name in some [metric conversions](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.33.0/specification/compatibility/prometheus_and_openmetrics.md#metric-metadata).

xds, rls: Experimental metrics are disabled by default

---

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java

This PR 
- Updates WRR and RLS metrics to be experimental and therefore disabled by default.
From gRFC A78:
> Metric Stability
>
> All metrics added in this proposal will start as experimental and therefore off by default.
- Adds "Experimental." in the beginning of metric description. 
- Updates metric units  to include `{}`, as strings inside `{}` are suffixed to metric name in some [metric conversions](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.33.0/specification/compatibility/prometheus_and_openmetrics.md#metric-metadata).
Backport of #11196

xds, rls: Experimental metrics are disabled by default (v1.64.x backport)

---

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
rls/src/main/java/io/grpc/rls/ChildLoadBalancerHelper.java
rls/src/main/java/io/grpc/rls/LbPolicyConfiguration.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java

Previously, picker was likely null if entering backoff soon after start-up. This prevented the picker from being updated and directing queued RPCs to the fallback. It would work for new RPCs if RLS returned extremely rapidly; both ManagedChannelImpl and DelayedClientTransport do a pick before enqueuing so the ManagedChannelImpl pick could request from RLS and DelayedClientTransport could use the response. So the test uses a delay to purposefully avoid that unlikely-in-real-life case.
Creating a resolving OOB channel for InProcess doesn't actually change the destination from the parent, because InProcess uses directaddress. Thus the fakeRlsServiceImpl is now being added to the fake backend server, because the same server is used for RLS within the test.
b/333185213

rls: Guarantee backoff will update RLS picker

---

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
rls/src/main/java/io/grpc/rls/ChildLoadBalancerHelper.java
rls/src/main/java/io/grpc/rls/LbPolicyConfiguration.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java

Previously, picker was likely null if entering backoff soon after start-up. This prevented the picker from being updated and directing queued RPCs to the fallback. It would work for new RPCs if RLS returned extremely rapidly; both ManagedChannelImpl and DelayedClientTransport do a pick before enqueuing so the ManagedChannelImpl pick could request from RLS and DelayedClientTransport could use the response. So the test uses a delay to purposefully avoid that unlikely-in-real-life case.
Creating a resolving OOB channel for InProcess doesn't actually change the destination from the parent, because InProcess uses directaddress. Thus the fakeRlsServiceImpl is now being added to the fake backend server, because the same server is used for RLS within the test.
b/333185213
Backport of #11202

rls: Guarantee backoff will update RLS picker (1.64.x backport)

---

all/build.gradle
opentelemetry/build.gradle

This adds opentelemetry to the shared javadoc (but also other things like having its tests contribute to code coverage).
CC @DNVindhya

all: Add opentelemetry

---

opentelemetry/src/main/java/io/grpc/opentelemetry/GrpcOpenTelemetry.java

opentelemetry: Mark registerGlobal() as experimental (1.64.x backport)

---

all/build.gradle
opentelemetry/build.gradle

This adds opentelemetry to the shared javadoc (but also other things like having its tests contribute to code coverage).
Backport of #11208

all: Add opentelemetry (1.64.x backport)

---

core/src/main/java/io/grpc/internal/DelayedClientTransport.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java

DelayedClientTransport already had to handle all the cases, so ManagedChannelImpl picking was acting only as an optimization. Optimizing DelayedClientTransport to avoid the lock when not queuing makes ManagedChannelImpl picking entirely redundant, and allows us to remove the duplicate race-handling logic.
This avoids double-picking when queuing, where ManagedChannelImpl does a pick, decides to queue, and then DelayedClientTransport re-performs the pick because it doesn't know which pick version was used. This was noticed with RLS, which mutates state within the picker.

core: Fully delegate picks to DelayedClientTransport

---

MODULE.bazel
repositories.bzl

Query in end-user repository fails with:
```
bazel query --notool_deps --noimplicit_deps "deps(//...)" --output graph
ERROR: Evaluation of query failed: preloading transitive closure failed: no such package '@@[unknown repo 'com_google_protobuf_javalite' requested from @https://github.com/grpc-java~]//': The repository '@@[unknown repo 'com_google_protobuf_javalite' requested from @https://github.com/grpc-java~]' could not be resolved: No repository visible as '@com_google_protobuf_javalite' from repository '@https://github.com/grpc-java~'
```
It's because com_google_protobuf_javalite is missing in use_repo in MODULE.bazel and completely not imported in repositories.bzl when using bzlmod. I noticed that actually com_google_protobuf_javalite is an archive with protobuf repository, which we …

Include com_google_protobuf_javalite to MODULE.bazel to fix bzlmod querying graph in end-user repo

---

core/build.gradle
core/src/test/java/io/grpc/internal/ManagedChannelImplBuilderTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplGetNameResolverTest.java

An inprocess class was just being abused. Note that grpc-testing depends on inprocess, so there is still an indirect dependency on inprocess present.

core: Remove direct test dependency on inprocess

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/testFixtures/java/io/grpc/internal/FakeClock.java
interop-testing/src/test/java/io/grpc/testing/integration/ManagedChannelImplIntegrationTest.java
xds/src/test/java/io/grpc/xds/CsdsServiceTest.java

8844cf7b8 triggered a regression where a new RPC wouldn't cause the channel to exit idle mode, if an RPC was still progressing on an old transport. This was already possible previously, but was racy. 8844cf7b8 made it less racy and more obvious.
The two added `exitIdleMode()` calls in this commit are companions to those in `enterIdleMode()`, which detect whether the channel should immediately exit idle mode.
Noticed in cl/635819804.
CC @temawi

core: Exit idle mode when delayed transport is in use

---

core/src/main/java/io/grpc/internal/DelayedClientTransport.java

It wasn't entirely clear what "it" referred to.

core: Make RPC buffering comment more clear

---

core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java
inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java
servlet/src/jettyTest/java/io/grpc/servlet/JettyTransportTest.java
servlet/src/tomcatTest/java/io/grpc/servlet/TomcatTransportTest.java
servlet/src/undertowTest/java/io/grpc/servlet/UndertowTransportTest.java

Returning the runnable did nothing, as both the start method and the runnable are run within the synchronization context. I believe the Runnable used to be required in the previous implementation of ManagedChannelImpl (the lock-based implementation before we created SynchronizationContext).
This fixes a NPE seen in ServerImpl because the server expects proper ordering of transport lifecycle events.
```
Uncaught exception in the SynchronizationContext. Panic!
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.Future.cancel(boolean)" because "this.handshakeTimeoutFuture" is null
at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.transportReady(ServerImpl.java:440)
at io.grpc.inprocess.InProcessTransport$4.run(InProcessTransport.java:215)
at …
```

inprocess: Fix listener race if transport is shutdown while starting

---

examples/example-reflection/README.md

The "list" instruction was missing, so the command didn't work properly. I added it to the readme, so other people won't have to debug it as I did

Minor - add missing instruction

---

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
rls/src/main/java/io/grpc/rls/LinkedHashLruCache.java
rls/src/test/java/io/grpc/rls/LinkedHashLruCacheTest.java

CachingRlsLbClient already calls it with a lock held. The only reason the cache needs to manage the lock itself is for the periodic cleanup. Let the consumer of the cache handle the timer.
----
Just noticed I hadn't sent this out. This was done around the same time as #11124 (unrelated to the fallback RLS PR I just sent out).

rls: Make LinkedHashLruCache non-threadsafe

---

netty/src/test/java/io/grpc/netty/AdvancedTlsTest.java
util/src/main/java/io/grpc/util/AdvancedTlsX509KeyManager.java
util/src/test/java/io/grpc/util/AdvancedTlsX509KeyManagerTest.java

This PR is a part of 'Stabilize Advanced TLS' effort.
Clean up, improve javadoc, de-experimentalize of AdvancedTlsX509KeyManager, add a unit test (e2e already exists).

security: Stabilize AdvancedTlsX509KeyManager.

---

core/src/main/java/io/grpc/internal/ManagedClientTransport.java

This hasn't been needed since f8f569e07, when InternalSubchannel stopped calling start() with a lock held. Note that also means no transport needs to return a Runnable (but some still are).
I had noticed in e4e7f3a06 that it was safe for InProcess to call the listener directly within start(), but I didn't notice this Javadoc that said it wasn't allowed.
CC @jdcormie

core: Remove "can't call transport listener from start()" restriction

---

buildscripts/kokoro/android-interop.sh

There are no longer any devices (virtual or otherwise) that support API level 21, 22, or 23. Google Play services is still supporting API level 21 (although there is a pattern of notifying of dropped levels in July, and dropping them in August).
CC @jdcormie

kokoro: Remove unavailable API levels 21-23

---

gcp-csm-observability/src/main/java/io/grpc/gcp/csm/observability/MetadataExchanger.java
gcp-csm-observability/src/test/java/io/grpc/gcp/csm/observability/CsmObservabilityTest.java

Just a typo, maybe because service_namespace is used in filter metadata from CDS.

gcp-csm-o11y: s/csm.service_namespace/csm.service_namespace_name/

---

core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java
servlet/src/jettyTest/java/io/grpc/servlet/JettyTransportTest.java
servlet/src/tomcatTest/java/io/grpc/servlet/TomcatTransportTest.java
servlet/src/undertowTest/java/io/grpc/servlet/UndertowTransportTest.java

The test was added in e4e7f3a06 when InProcess stopped returning a Runnable from start(). In #11256 we realized (indirectly) that there's no point in using the Runnable any more.
This test failed with Binder (which seems to have been using the Runnable unnecessarily), and InProcess, Netty, and OkHttp don't use the Runnable. Instead of fixing it, we'll just move toward stopping using Runnable.
I'm not removing the Runnable usage from Binder in this commit because this test is currently causing CI failures and I don't want to do a behavior change when fixing it.

core: Delete AbstractTransportTest.clientShutdownBeforeStartRunnable

---

gcp-csm-observability/build.gradle

This prevents mixing shaded and non-shaded class files. We do the same thing in all the other projects that depend on xds.

gcp-csm-o11y: Use xds's shadow configuration

---

binder/src/androidTest/java/io/grpc/binder/internal/BinderClientTransportTest.java
binder/src/androidTest/java/io/grpc/binder/internal/OneWayBinderProxies.java
binder/src/main/java/io/grpc/binder/BinderChannelBuilder.java
binder/src/main/java/io/grpc/binder/internal/BinderClientTransportFactory.java
binder/src/main/java/io/grpc/binder/internal/BinderTransport.java

Timeout is initially infinite so that we can release/import the supporting code and the behavior change independently. 
Fixes https://github.com/grpc/grpc-java/issues/11137

binder: Add a connection timeout

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpServerTransport.java

Using --runs_per_test=1000, this changes the flake rate of TlsTest from 2% to 0%.
While I believe it is possible to write a reliable test for this (including noticing the SSLSocket behavior), it was becoming too invasive so I gave up.
Fixes #11012

okhttp: Workaround SSLSocket not noticing socket is closed

---

util/src/main/java/io/grpc/util/AdvancedTlsX509KeyManager.java

* Previous `java.util.logging.Logger#log()` usage in `AdvancedTlsX509KeyManager.java` was newly introduced in API level 26 not backwards compatible with Android

util: fix logging to be compatible with Android for AdvancedTlsX509KeyManager

---

binder/src/androidTest/java/io/grpc/binder/internal/BinderClientTransportTest.java
binder/src/main/java/io/grpc/binder/internal/BinderTransport.java

https://github.com/grpc/grpc-java/issues/10566

Don't block an offload thread when the client's SecurityPolicy is async

---

binder/src/main/java/io/grpc/binder/internal/BinderTransport.java

Call to awaitTermination() should be access guarded but it is not when called from inside the runnable. This PR fixes that.

Adding missing synchronization in runnable

---

build.gradle

It is simultaneously overly zealous and doesn't notice basic cases. As noticed in #11281.

Disable ErrorProne's MutableConstantField check

---

opentelemetry/src/main/java/io/grpc/opentelemetry/GrpcOpenTelemetry.java
opentelemetry/src/main/java/io/grpc/opentelemetry/internal/OpenTelemetryConstants.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryMetricsModuleTest.java

As part of gRFC [A66](https://github.com/grpc/proposal/blob/master/A66-otel-stats.md#units):
> Buckets for histograms in default views should be as follows -
> Latency : 0, 0.00001, 0.00005, 0.0001, 0.0003, 0.0006, 0.0008, 0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.008, 0.01, 0.013, 0.016, 0.02, 0.025, 0.03, 0.04, 0.05, 0.065, 0.08, 0.1, 0.13, 0.16, 0.2, 0.25, 0.3, 0.4, 0.5, 0.65, 0.8, 1, 2, 5, 10, 20, 50, 100
> Size : 0, 1024, 2048, 4096, 16384, 65536, 262144, 1048576, 4194304, 16777216, 67108864, 268435456, 1073741824, 4294967296
This PR adds histogram bucket boundaries for per-call metrics.
CC @yashykt

opentelemetry: Add explicit histogram buckets for per-call metrics

---

api/src/main/java/io/grpc/ServerBuilder.java

api: Stabilize ServerBuilder.AddServices()

---

build.gradle

It is simultaneously overly zealous and doesn't notice basic cases. As noticed in #11281.
Backport of #11283

Disable ErrorProne's MutableConstantField check (v1.65.x backport)

---

examples/example-gcp-csm-observability/README.md
examples/example-gcp-csm-observability/build.gradle
examples/example-gcp-csm-observability/csm-client.Dockerfile
examples/example-gcp-csm-observability/csm-server.Dockerfile
examples/example-gcp-csm-observability/settings.gradle
examples/example-gcp-csm-observability/src/main/java/io/grpc/examples/csmobservability/CsmObservabilityClient.java
examples/example-gcp-csm-observability/src/main/java/io/grpc/examples/csmobservability/CsmObservabilityServer.java
examples/example-gcp-csm-observability/src/main/proto/helloworld/helloworld.proto

This PR adds a CSM Observability example. This is intended to be built as docker images and deployed as part of CSM observability user guide.
(Backport of #11267)
CC @yashykt

examples: Add GCP CSM Observability example (v1.65.x backport) 

---

opentelemetry/src/main/java/io/grpc/opentelemetry/GrpcOpenTelemetry.java
opentelemetry/src/main/java/io/grpc/opentelemetry/internal/OpenTelemetryConstants.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryMetricsModuleTest.java

As part of gRFC [A66](https://github.com/grpc/proposal/blob/master/A66-otel-stats.md#units):
> Buckets for histograms in default views should be as follows -
> Latency : 0, 0.00001, 0.00005, 0.0001, 0.0003, 0.0006, 0.0008, 0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.008, 0.01, 0.013, 0.016, 0.02, 0.025, 0.03, 0.04, 0.05, 0.065, 0.08, 0.1, 0.13, 0.16, 0.2, 0.25, 0.3, 0.4, 0.5, 0.65, 0.8, 1, 2, 5, 10, 20, 50, 100
> Size : 0, 1024, 2048, 4096, 16384, 65536, 262144, 1048576, 4194304, 16777216, 67108864, 268435456, 1073741824, 4294967296
This PR adds histogram bucket boundaries for per-call metrics.
(Backport of #11281)

opentelemetry: Add explicit histogram buckets for per-call metrics (v1.65.x backport)

---

MODULE.bazel
buildscripts/data-plane-api-no-envoy.patch
repositories.bzl
xds/third_party/envoy/import.sh

Bazel was not updated as part of feab4e54. Also, `(( X++ ))` exits 1 if X is zero. The patch to data-plane-api is being upstreamed in https://github.com/envoyproxy/envoy/pull/34759

Upgrade and fix import issues with envoy_api

---

binder/src/androidTest/java/io/grpc/binder/internal/BinderTransportTest.java
binder/src/main/java/io/grpc/binder/BinderServerBuilder.java
binder/src/main/java/io/grpc/binder/internal/BinderServer.java
binder/src/main/java/io/grpc/binder/internal/BinderTransportSecurity.java

Allocating this executor before BinderServer even exists is convoluted and actually leaks if the built server is never actually start()ed. Instead, we have BinderServer own this executor directly, with a lifetime from start() until termination. Pass the executor to ServerAuthInterceptor via TransportAuthorizationState Attribute instead of at construction time.

binder: Simplify ownership of ServerAuthInterceptor's executor.

---

services/BUILD.bazel

The target was wrongly deleted in 75492c8 / #10832.
See details in https://github.com/grpc/grpc-java/issues/4017#issuecomment-2159516522.

services: restore //services:binarylog bazel target

---

gradle/libs.versions.toml
netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java
netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java

Change the logic for identifying changes to the read index when merging into a netty composite buffer so that it works with both older versions of netty and netty 4.1.111
Fixes #11284

netty:Fix Netty composite buffer merging to be compatible with Netty 4.1.111

---

examples/example-opentelemetry/README.md
examples/example-opentelemetry/build.gradle
examples/example-opentelemetry/settings.gradle
examples/example-opentelemetry/src/main/java/io/grpc/example/opentelemetry/OpenTelemetryClient.java
examples/example-opentelemetry/src/main/java/io/grpc/example/opentelemetry/OpenTelemetryServer.java
examples/example-opentelemetry/src/main/java/io/grpc/example/opentelemetry/logging/LoggingOpenTelemetryClient.java
examples/example-opentelemetry/src/main/java/io/grpc/example/opentelemetry/logging/LoggingOpenTelemetryServer.java
examples/example-opentelemetry/src/main/proto/helloworld/helloworld.proto

This PR adds a gRPC OpenTelemetry example. The example uses [Prometheus exporter](https://javadoc.io/doc/io.opentelemetry/opentelemetry-exporter-prometheus/latest/io/opentelemetry/exporter/prometheus/PrometheusHttpServer.html) to export metrics and can be verified locally.
It also provides an example using [LoggingMetricExporter](https://javadoc.io/doc/io.opentelemetry/opentelemetry-exporter-logging/latest/io/opentelemetry/exporter/logging/LoggingMetricExporter.html) to export and log the metrics using `java.util.logging`.
CC @yashykt

examples: Add gRPC OpenTelemetry example

---

all/build.gradle

This adds GCP CSM Observability to the shared javadoc (but also other things like having its tests contribute to code coverage).

all:Add GCP CSM Observability

---

netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java
netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java

Change the logic for identifying changes to the read index when merging into a netty composite buffer so that it works with both older versions of netty and netty 4.1.111
Fixes #11284 
Backport of #11294

netty:Fix Netty composite buffer merging to be compatible with Netty 4.1.111 (1.63.x backport)

---

netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java
netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java

Change the logic for identifying changes to the read index when merging into a netty composite buffer so that it works with both older versions of netty and netty 4.1.111
Fixes #11284 
Backport of #11294

netty:Fix Netty composite buffer merging to be compatible with Netty 4.1.111 (1.64.x backport)

---

netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java
netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java

Change the logic for identifying changes to the read index when merging into a netty composite buffer so that it works with both older versions of netty and netty 4.1.111
Fixes https://github.com/grpc/grpc-java/issues/11284
Backport of https://github.com/grpc/grpc-java/pull/11294

netty:Fix Netty composite buffer merging to be compatible with Netty 4.1.111 (v1.65.x backport)

---

api/src/main/java/io/grpc/MetricRecorder.java
core/src/main/java/io/grpc/internal/MetricRecorderImpl.java

This PR adds validation to check label values size against size of registered metric labels in `MetricRecorder` interface.

core: Add label values size validation in MetricRecorder

---

examples/example-opentelemetry/README.md
examples/example-opentelemetry/build.gradle
examples/example-opentelemetry/settings.gradle
examples/example-opentelemetry/src/main/java/io/grpc/example/opentelemetry/OpenTelemetryClient.java
examples/example-opentelemetry/src/main/java/io/grpc/example/opentelemetry/OpenTelemetryServer.java
examples/example-opentelemetry/src/main/java/io/grpc/example/opentelemetry/logging/LoggingOpenTelemetryClient.java
examples/example-opentelemetry/src/main/java/io/grpc/example/opentelemetry/logging/LoggingOpenTelemetryServer.java
examples/example-opentelemetry/src/main/proto/helloworld/helloworld.proto

This PR adds a gRPC OpenTelemetry example. The example uses [Prometheus exporter](https://javadoc.io/doc/io.opentelemetry/opentelemetry-exporter-prometheus/latest/io/opentelemetry/exporter/prometheus/PrometheusHttpServer.html) to export metrics and can be verified locally.
It also provides an example using [LoggingMetricExporter](https://javadoc.io/doc/io.opentelemetry/opentelemetry-exporter-logging/latest/io/opentelemetry/exporter/logging/LoggingMetricExporter.html) to export and log the metrics using `java.util.logging`.
Backport of #11299.

examples: Add gRPC OpenTelemetry example (v1.65.x backport)

---

all/build.gradle

This adds GCP CSM Observability to the shared javadoc (but also other things like having its tests contribute to code coverage).
Backport of #11305

all:Add GCP CSM Observability (v1.65.x backport)

---

examples/example-gcp-csm-observability/build.gradle
examples/example-gcp-csm-observability/src/main/java/io/grpc/examples/csmobservability/CsmObservabilityClient.java
examples/example-gcp-csm-observability/src/main/java/io/grpc/examples/csmobservability/CsmObservabilityServer.java

examples: Remove unused imports from CSM Observability example (v1.65.x backport)

---

util/src/main/java/io/grpc/util/AdvancedTlsX509KeyManager.java

See https://github.com/grpc/grpc-java/pull/11312 for the rationale. This was removed in https://github.com/grpc/grpc-java/pull/11139.

security: Add ExperimentalApi annotation to AdvancedTlsX509KeyManager class.

---

util/src/main/java/io/grpc/util/AdvancedTlsX509KeyManager.java

See https://github.com/grpc/grpc-java/pull/11312 for the rationale. This was removed in https://github.com/grpc/grpc-java/pull/11139.
Backport of #11315
CC @matthewstevenson88

security: Add ExperimentalApi annotation to AdvancedTlsX509KeyManager class. (1.65.x backport)

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpServerTransport.java

MacOS is consistently failing the CI build, so can't do version updates for release.  This should unblock.
Using --runs_per_test=1000, this changes the flake rate of TlsTest from 2% to 0%.
While I believe it is possible to write a reliable test for this (including noticing the SSLSocket behavior), it was becoming too invasive so I gave up.
Fixes #11012
Backport of #11266

okhttp: Workaround SSLSocket not noticing socket is closed (1.63.x backport)

---

services/BUILD.bazel

The target was wrongly deleted in 75492c8 / #10832.
See details in https://github.com/grpc/grpc-java/issues/4017#issuecomment-2159516522.
Backport of #11292

services: restore //services:binarylog bazel target (1.65.x backport)

---

build.gradle
compiler/src/test/golden/TestDeprecatedService.java.txt
compiler/src/test/golden/TestService.java.txt
compiler/src/testLite/golden/TestDeprecatedService.java.txt
compiler/src/testLite/golden/TestService.java.txt
core/src/main/java/io/grpc/internal/GrpcUtil.java
examples/android/clientcache/app/build.gradle
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/strictmode/app/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-debug/build.gradle
examples/example-debug/pom.xml
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-gcp-observability/build.gradle
examples/example-hostname/build.gradle
examples/example-hostname/pom.xml
examples/example-jwt-auth/build.gradle
examples/example-jwt-auth/pom.xml
examples/example-oauth/build.gradle
examples/example-oauth/pom.xml
examples/example-orca/build.gradle
examples/example-reflection/build.gradle
examples/example-servlet/build.gradle
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/example-xds/build.gradle
examples/pom.xml

This should never have been done and makes the normal patch release process broken.

Revert "Start 1.63.3 development cycle"

---

api/src/main/java/io/grpc/CallOptions.java
api/src/test/java/io/grpc/CallOptionsTest.java
stub/src/main/java/io/grpc/stub/AbstractStub.java
stub/src/test/java/io/grpc/stub/BaseAbstractStubTest.java

https://github.com/grpc/grpc-java/issues/11289
1. Support setting onReadyThreshold through AbstractStub
2. Add copy of the onReadyThreshold property when copying CallOptions(fix bug)

grpc-java supports onReadyThreshold property setting

---

xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java

Verified the configure through interop test, not exactly the same though:
```
$ JAVA_OPTS=-Djava.util.logging.config.file=logging.properties  ./run-test-client.sh --use_tls=false --service_config_json='{"loadBalancingConfig":[{"weighted_round_robin":{"enableOobLoadReport":true, "blackoutPeriod":"10s","oobReportingPeriod":"10s","weightExpirationPeriod":"100s","errorUtilizationPenalty":"0.12","weightUpdatePeriod":"3s"}}]}'
Running test empty_unary
Jun 27, 2024 3:21:57 PM io.grpc.xds.WeightedRoundRobinLoadBalancer <init>
FINE: weighted_round_robin LB created
Test completed.
```
@anicr7 verified through TD:
```
localityLbPolicies:
- customPolicy:
name: weighted_round_robin
data: '{ "enableOobLoadReport": true }'
```
cc. @anicr7

doc: add document on WRR configure example through service config

---

core/src/main/java/io/grpc/internal/PickFirstLeafLoadBalancer.java
core/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java
core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java
core/src/test/java/io/grpc/internal/PickFirstLeafLoadBalancerTest.java

change from intra EAG to inter EAG

core:Change address deduping to be across EAGs

---

core/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java

All known bugs have been fixed and merged.  Re-enabling usage of PickFirstLeafLoadBalancer by default.
Note that Happy Eyeballs is not enabled by default.

Enable new PickFirst LB

---

core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java

This utility is not relevant on supported JDK versions anymore.

core: remove GrpcUtil.getHost

---

util/src/main/java/io/grpc/util/GracefulSwitchLoadBalancer.java
util/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
util/src/main/java/io/grpc/util/OutlierDetectionLoadBalancerProvider.java
util/src/test/java/io/grpc/util/GracefulSwitchLoadBalancerTest.java
util/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerProviderTest.java
util/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java
util/src/testFixtures/java/io/grpc/util/GracefulSwitchLoadBalancerAccessor.java
xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
xds/src/main/java/io/grpc/xds/PriorityLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/WeightedTargetLoadBalancer.java
xds/src/main/java/io/grpc/xds/WeightedTargetLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/WrrLocalityLoadBalancer.java
xds/src/main/java/io/grpc/xds/WrrLocalityLoadBalancerProvider.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/PriorityLoadBalancerProviderTest.java
xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WeightedTargetLoadBalancerProviderTest.java
xds/src/test/java/io/grpc/xds/WeightedTargetLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WrrLocalityLoadBalancerProviderTest.java
xds/src/test/java/io/grpc/xds/WrrLocalityLoadBalancerTest.java

This doesn't actually remove switchTo() as the API is currently public, although we may want to mark it deprecated. You may want to look at each commit separately, especially the first. The rest of the commits should look pretty similar to each other (IIRC). The tests added to GracefulSwitchLoadBalancerTest are copies of the existing tests with switchTo() replaced. You'll notice I made some changes to the existing tests before I copied them.
No rush on reviewing this. It has been sitting around on my machine since March.

Replace GracefulSwitch.switchTo with normal config passing

---

buildscripts/grpc-java-artifacts/Dockerfile
compiler/build.gradle
compiler/check-artifact.sh

CentOS 7 became end-of-life on July 1st and is no longer working. We now dynamically link against libstdc++, as RHEL 8 doesn't support static linking: https://access.redhat.com/articles/rhel8-abi-compatibility
We now use objdump in check-artifact for all linux architectures. This avoids using a mix of objdump and ldd. ldd shows transitive dependencies, which is less convenient.

compiler: Upgrade from CentOS 7 to AlmaLinux 8

---

buildscripts/kokoro/android-interop.sh
buildscripts/kokoro/android.sh

It doesn't have Android SDK nor the VERSION file. See also d654707838

kokoro: Adjust android CIs to work with Ubuntu 22.04 image

---

binder/src/main/java/io/grpc/binder/internal/BinderClientTransportFactory.java

Enables logic for #11137 
TGP passes: http://test/OCL:648465904:BASE:648380197:1719887241500:d3863716

binder: Establish a default connect timeout.

---

netty/src/test/java/io/grpc/netty/AdvancedTlsTest.java
util/BUILD.bazel
util/build.gradle
util/src/main/java/io/grpc/util/AdvancedTlsX509KeyManager.java
util/src/test/java/io/grpc/util/AdvancedTlsX509KeyManagerTest.java

Two new 'updateIdentityCredentials' methods with swapped (chain, key) arguments are added. Original 'updateIdentityCredentialsFromFiles' are deprecated.

security: Add updateIdentityCredentials methods to AdvancedTlsX509KeyManager.

---

netty/src/main/java/io/grpc/netty/GrpcHttp2ConnectionHandler.java
netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java
netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java

The fix to support Netty 4.1.111 caused a problem in a Google internal test which led to #11366 which would have completely broken Netty 4.1.111 installations.  This eliminates the problems that caused a desire to revert.  
A long term fix should be developed to keep the performance advantages provided by NettyAdaptiveCumulator with no down sides.

Restore old behavior of NettyAdaptiveCumulator, but avoid using that class if Netty is on version 4.1.111 or later

---

buildscripts/grpc-java-artifacts/Dockerfile
compiler/build.gradle
compiler/check-artifact.sh

CentOS 7 became end-of-life on July 1st and is no longer working. We now dynamically link against libstdc++, as RHEL 8 doesn't support static linking: https://access.redhat.com/articles/rhel8-abi-compatibility
We now use objdump in check-artifact for all linux architectures. This avoids using a mix of objdump and ldd. ldd shows transitive dependencies, which is less convenient.
Backport of #11354

compiler: Upgrade from CentOS 7 to AlmaLinux 8 (1.64.x backport)

---

buildscripts/grpc-java-artifacts/Dockerfile
compiler/build.gradle
compiler/check-artifact.sh

CentOS 7 became end-of-life on July 1st and is no longer working. We now dynamically link against libstdc++, as RHEL 8 doesn't support static linking: https://access.redhat.com/articles/rhel8-abi-compatibility
We now use objdump in check-artifact for all linux architectures. This avoids using a mix of objdump and ldd. ldd shows transitive dependencies, which is less convenient.
Backport of #11354

compiler: Upgrade from CentOS 7 to AlmaLinux 8 (1.63.x backport)

---

buildscripts/grpc-java-artifacts/Dockerfile
compiler/build.gradle
compiler/check-artifact.sh

CentOS 7 became end-of-life on July 1st and is no longer working. We now dynamically link against libstdc++, as RHEL 8 doesn't support static linking: https://access.redhat.com/articles/rhel8-abi-compatibility
We now use objdump in check-artifact for all linux architectures. This avoids using a mix of objdump and ldd. ldd shows transitive dependencies, which is less convenient.
Backport of #11354

compiler: Upgrade from CentOS 7 to AlmaLinux 8 (1.65.x backport)

---

netty/src/main/java/io/grpc/netty/GrpcHttp2ConnectionHandler.java
netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java
netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java

The fix to support Netty 4.1.111 caused a problem in a Google internal test which led to #11366 which would have completely broken Netty 4.1.111 installations.  This eliminates the problems that caused a desire to revert.  
A long term fix should be developed to keep the performance advantages provided by NettyAdaptiveCumulator with no down sides.
Backport of #11367

Restore old behavior of NettyAdaptiveCumulator, but avoid using that class if Netty is on version 4.1.111 or later (1.63.x backport)

---

netty/src/main/java/io/grpc/netty/GrpcHttp2ConnectionHandler.java
netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java
netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java

The fix to support Netty 4.1.111 caused a problem in a Google internal test.  This eliminates the problems that caused a desire to revert.  
Backport of #11367

Restore old behavior of NettyAdaptiveCumulator, but avoid using that class if Netty is on version 4.1.111 or later (1.65.x backport)

---

netty/src/main/java/io/grpc/netty/GrpcHttp2ConnectionHandler.java
netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java
netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java

The fix to support Netty 4.1.111 caused a problem in a Google internal test which led to #11366 which would have completely broken Netty 4.1.111 installations.  This eliminates the problems that caused a desire to revert.  
A long term fix should be developed to keep the performance advantages provided by NettyAdaptiveCumulator with no down sides.
Backport of #11367

Restore old behavior of NettyAdaptiveCumulator, but avoid using that class if Netty is on version 4.1.111 or later (1.64.x backport)

---

util/src/main/java/io/grpc/util/AdvancedTlsX509KeyManager.java

Three 'updateIdentityCredentials*' deprecated methods are annotated with the 
ExperimentalApi("https://github.com/grpc/grpc-java/issues/8024").

security: Annotate deprecated methods of AdvancedTlsX509KeyManager with ExperimentalAPI.

---

util/src/main/java/io/grpc/util/AdvancedTlsX509TrustManager.java

There's a missing if-statement to check SSLEngine vs socket before calling currentDelegateManager.checkClientTrusted

Fix AdvancedTlsX509TrustManager to handle client side validation of socket

---

MODULE.bazel
authz/src/test/java/io/grpc/authz/AuthorizationPolicyTranslatorTest.java
authz/src/test/java/io/grpc/authz/AuthorizationServerInterceptorTest.java
build.gradle
buildSrc/src/main/java/io/grpc/gradle/CheckForUpdatesTask.java
examples/build.gradle
examples/example-alts/build.gradle
examples/example-debug/build.gradle
examples/example-debug/pom.xml
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-gcp-csm-observability/build.gradle
examples/example-gcp-observability/build.gradle
examples/example-hostname/build.gradle
examples/example-hostname/pom.xml
examples/example-jwt-auth/build.gradle
examples/example-jwt-auth/pom.xml
examples/example-oauth/build.gradle
examples/example-oauth/pom.xml
examples/example-opentelemetry/build.gradle
examples/example-orca/build.gradle
examples/example-reflection/build.gradle
examples/example-servlet/build.gradle
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/example-xds/build.gradle
examples/pom.xml
gradle/libs.versions.toml
repositories.bzl

The GSON upgrade slightly changed an error string, so the test was updated to be less of a change detector.
Some OpenTelemetry dependencies are alpha versions, so needed an adjustment in build.gradle to accept the versions. Similarly, Undertow includes Final in its version numbers which needs to be accepted.

Upgrade dependencies

---

netty/src/test/java/io/grpc/netty/AdvancedTlsTest.java
util/src/main/java/io/grpc/util/AdvancedTlsX509KeyManager.java
util/src/main/java/io/grpc/util/AdvancedTlsX509TrustManager.java
util/src/test/java/io/grpc/util/AdvancedTlsX509KeyManagerTest.java
util/src/test/java/io/grpc/util/AdvancedTlsX509TrustManagerTest.java

- Swap key/cert arguments of internal private classes in KeyManager
- Deprecate *FromFile methods in TrustManager in favor of overloaded updateTrustCredentials
- Unit test for https://github.com/grpc/grpc-java/pull/11352

util: Align AdvancedTlsX509{Key and Trust}Manager

---

examples/WORKSPACE

It hasn't been needed since 0064991. In that commit the main WORKSPACE was cleaned up, but not the examples.

examples: For Bazel, remove compat repo for maven_install

---

.github/workflows/testing.yml
MODULE.bazel
RELEASING.md
examples/MODULE.bazel
examples/WORKSPACE.bzlmod

This also updates the version number of the grpc-java module as part of the release process.

examples: Add bzlmod support

---

MODULE.bazel
repositories.bzl

Since Bazel 6 [1], Bazel has used com_google_protobuf for javalite. We only used the other repo because Bazel expected it, which was because Protobuf split out javalite to a separate branch for a while. Since everything is now reunified, we can use a singular protobuf repo.
1. https://github.com/bazelbuild/bazel/commit/abdb1d6bfeba6f059e2d8e5383121fbead332c6a

bazel: Use com_google_protobuf instead of com_google_protobuf_javalite

---

protobuf-lite/BUILD.bazel

We don't include protobuf in IO_GRPC_GRPC_JAVA_ARTIFACTS, so there might not actually be an alias available for it to @com_google_protobuf. While we could add it, it is easier to use the @com_google_protobuf references directly.
This was preventing `bazel query 'deps(//...)' from succeeding, because it couldn't find javalite.

bazel: Don't use artifact() for protobuf deps

---

xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

From gRFC A58:
> When less than two subchannels have load info, all subchannels will
> get the same weight and the policy will behave the same as round_robin
CC @temawi, @DNVindhya

xds: WRR rr_fallback should trigger with one endpoint weight

---

api/src/main/java/io/grpc/LoadBalancer.java
util/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
util/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

They share very little code, and we really don't want RoundRobinLb to be public and non-final. Originally, WRR was expected to share much more code with RR, and even delegated to RR at times. The delegation was removed in 111ff60e. After dca89b25, most of the sharing has been moved out into general-purpose tools that can be used by any LB policy.
FixedResultPicker now has equals to makes it as a EmptyPicker replacement. RoundRobinLb still uses EmptyPicker because fixing its tests is a larger change. OutlierDetectionLbTest was changed because FixedResultPicker is used by PickFirstLeafLb, and now RoundRobinLb can squelch some of its updates for ready pickers.

xds: Stop extending RR in WRR

---

api/src/main/java/io/grpc/NameResolver.java
core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/RetryingNameResolver.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/RetryingNameResolverTest.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbNameResolverTest.java

This reverts commit 9ba2f9dec5c71a5d0afbba0f196331a47844bc07.
It causes a channel panic due to unimplemented onResult2().
```
java.lang.UnsupportedOperationException: Not implemented.
at io.grpc.NameResolver$Listener2.onResult2(NameResolver.java:257)
at io.grpc.internal.DnsNameResolver$Resolve.lambda$run$0(DnsNameResolver.java:334)
at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:94)
at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:126)
at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:333)
```
b/356669977

Revert "Introduce onResult2 in NameResolver Listener2 that returns Status (#11313)"

---

api/src/main/java/io/grpc/NameResolver.java
core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/RetryingNameResolver.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/RetryingNameResolverTest.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbNameResolverTest.java

This reverts commit 9ba2f9dec5c71a5d0afbba0f196331a47844bc07.
It causes a channel panic due to unimplemented onResult2().
```
java.lang.UnsupportedOperationException: Not implemented.
at io.grpc.NameResolver$Listener2.onResult2(NameResolver.java:257)
at io.grpc.internal.DnsNameResolver$Resolve.lambda$run$0(DnsNameResolver.java:334)
at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:94)
at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:126)
at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:333)
```
b/356669977
CC @kannanjgithub 
Backport of #11421

Revert "Introduce onResult2 in NameResolver Listener2 that returns Status (#11313)" (1.66.x backport)

---

core/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java

Reverts grpc/grpc-java#11348
Traffic increase still present in Android (GMS) as reported in b/356143949

Revert "Enable new PickFirst LB"

---

interop-testing/build.gradle

googleapis and rls can still be used at runtime.

interop-testing: Remove unused implementation deps

---

xds/build.gradle
xds/src/generated/thirdparty/grpc/io/envoyproxy/envoy/service/rate_limit_quota/v3/RateLimitQuotaServiceGrpc.java
xds/third_party/cel-spec/LICENSE
xds/third_party/cel-spec/import.sh
xds/third_party/cel-spec/src/main/proto/cel/expr/checked.proto
xds/third_party/cel-spec/src/main/proto/cel/expr/syntax.proto
xds/third_party/envoy/import.sh
xds/third_party/envoy/src/main/proto/envoy/extensions/filters/http/rate_limit_quota/v3/rate_limit_quota.proto
xds/third_party/envoy/src/main/proto/envoy/service/rate_limit_quota/v3/rlqs.proto
xds/third_party/envoy/src/main/proto/envoy/type/matcher/v3/http_inputs.proto
xds/third_party/envoy/src/main/proto/envoy/type/v3/http_status.proto
xds/third_party/envoy/src/main/proto/envoy/type/v3/ratelimit_strategy.proto
xds/third_party/envoy/src/main/proto/envoy/type/v3/ratelimit_unit.proto
xds/third_party/envoy/src/main/proto/envoy/type/v3/token_bucket.proto
xds/third_party/xds/import.sh
xds/third_party/xds/src/main/proto/xds/type/matcher/v3/cel.proto
xds/third_party/xds/src/main/proto/xds/type/matcher/v3/http_inputs.proto
xds/third_party/xds/src/main/proto/xds/type/v3/cel.proto

Imports the protos of Rate Limiting Quota Service (RLQS) and Rate Limit Quota HTTP Filter.
Note: the list below only shows the new top-level protos, and excludes their direct and transitional dependencies (those from import statements).
- Service — envoy/service/rate_limit_quota/v3/rlqs.proto (Service): 7b8a304
- HTTP Filter — envoy/extensions/filters/http/rate_limit_quota/v3/rate_limit_quota.proto: 49c77c4
- Initial third-party repo setup: 99a64bd
- Parsed CEL Expression: cel/expr/syntax.proto: 99a64bd
- Parsed and type-checked CEL Expression: cel/expr/checked.proto: 99a64bd
- `HttpAttributesCelMatchInput` — xds/type/matcher/v3/http_inputs.proto: 54924e0
- `HttpRequestHeaderMatchInput` — envoy/type/matcher/v3/http_inputs.proto: 49c77c4
- `CelMatcher` — xds/type/matcher/v3/cel.proto: …

xds: Import RLQS protos

---

core/src/test/java/io/grpc/internal/PickFirstLeafLoadBalancerTest.java

PickFirstLeafLB uses channel reference equality to see if it has re-created subchannels. The tests reusing channels breaks the expected invariant.
----
I've got a cleanup to PF to use SubchannelData more, but the change triggers bugs in the tests. So this fixes the test first, and will pass both before and after the PF cleanup.

core: Don't reuse channels in PickFirstLeafLB test

---

xds/src/main/java/io/grpc/xds/client/ControlPlaneClient.java
xds/src/main/java/io/grpc/xds/client/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplV3Test.java

Closes #11232 
As described in the original issue:
If a CDS update revoke all subscribed resources, all EDS subscriptions will be cancelled. 
The first observation of the `istiod` logs is,
```
>>>>> CDS PUSH
2024-06-04T08:30:16.705222Z	info	ads	CDS: PUSH for node:e2e-service-consumer-base-5dd4cb9fbf-v6gjk.default resources:0 size:0B nonce:af2f0bd1-c785-4232-b381-de703b6e3e7d version:2024-06-04T08:30:16Z/7
>>>>> EDS PUSH immediately after CDS
2024-06-04T08:30:16.705384Z	info	ads	EDS: PUSH for node:e2e-service-consumer-base-5dd4cb9fbf-v6gjk.default resources:2 size:395B empty:0 cached:0/2 nonce:cea5b0b2-82d7-4c81-99cc-744ae9a7948e version:2024-06-04T08:30:16Z/7
2024-06-04T08:30:16.705464Z	debug	grpcgen	building lds for e2e-service-consumer-base-5dd4cb9fbf-v6gjk.default with filter: …
```

Allow to send empty subscription and update version afterward (1.66.x backport)

---

core/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java

Reverts grpc/grpc-java#11348
Traffic increase still present in Android (GMS) as reported in b/356143949
Backport of #11425

Revert "Enable new PickFirst LB" (1.66.x backport)

---

CONTRIBUTING.md

It came up in #11073, and I saw it could use a little updating. Notably, I'm linking to a guide to what Git commit messages should look like. I also tried to make the language less heavy-handed and demanding.
-----
I do think there's more that can be done, but I think this is a step in the right direction. It's obvious the IntelliJ style mention is out-of-date, for example.

CONTRIBUTING.md: Update commit guidelines

---

core/src/main/java/io/grpc/internal/AbstractClientStream.java

This makes `shouldBeCountedForInUse` and `useGet` `private` fields of `AbstractClientStream` `final` since they already are effectively.

chore: make once-set fields of `AbstractClientStream` `final`

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
util/src/test/java/io/grpc/util/MultiChildLoadBalancerTest.java
util/src/testFixtures/java/io/grpc/util/AbstractTestHelper.java

Some addresses are equal even though their toString is different (InetSocketAddress ignores the hostname when it has an address). And some addresses are not equal even though their toString might be the same (AnonymousInProcessSocketAddress doesn't override toString()).
InetSocketAddress/InetAddress do not cache the toString() result. Thus, even in the worst case that uses a HashSet, this should use less memory than the earlier approach, as no strings are formatted. It probably also significantly improves performance in the reasonably common case when an Endpoint is created just for looking up a key, because the string creation in the constructor isn't then amorized.
updateChildrenWithResolvedAddresses(), for example, creates n^2 Endpoint objects for lookups.

util: SocketAddress.toString() cannot be used for equality

---

xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancerProvider.java

A package-private class isn't visible and `@Internal` is stronger than experimental. The only way users should use WRR is via the weight_round_robin string, and that's already not suffixed with _experimental.
Closes #9885

xds: Remove useless ExperimentalApi for WRR

---

xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

There was no point to using subchannels as keys to subchannelToReportListenerMap, as the listener is per-child. That meant the keys would be guaranteed to be known ahead-of-time and the unsynchronized getOrCreateOrcaListener() during picking was unnecessary.
The picker still stores ChildLbStates to make sure that updating weights uses the correct children, but the picker itself no longer references ChildLbStates except in the constructor. That means weight calculation is moved into the LB policy, as child.getWeight() is unsynchronized, and the picker no longer needs a reference to helper.

xds: WRRPicker must not access unsynchronized data in ChildLbState

---

netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java

LocalChannel is not guaranteed to be compatible with NioEventLoopGroup, and is failing with Netty 4.2.0.Alpha3-SNAPSHOT.
See #11447
CC @normanmaurer

netty: Use DefaultELG with LocalChannel in test

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
util/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
xds/src/main/java/io/grpc/xds/LeastRequestLoadBalancer.java
xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java

One LB no longer needs to extend ChildLbState and one has to start, so it is a bit of a wash. There are more LBs that need the auto-request logic, but if we have an API where subclasses override it without calling super then we can't change the implementation in the future. Adding behavior on top of a base class allows subclasses to call super, which lets the base class change over time.

Remove implicit requestConnection() on IDLE from MultiChildLB

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
util/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java
xds/src/main/java/io/grpc/xds/LeastRequestLoadBalancer.java
xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java

That's the obvious default, and all current usages use (something equivalent to) that default.

util: MultiChildLb children should always start with a NoResult picker

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java

Since 04474970 RingHashLB has not used
acceptResolvedAddressesInternal(). At the time that was needed because deactivated children were part of MultiChildLB. But in 9de8e443, the logic of RingHashLB and MultiChildLB.acceptResolvedAddressesInternal() converged, so it can now swap back to using the base class for more logic.

xds: Delegate more RingHashLB address updates to MultiChildLB

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java

These were once needed to be overridden (e.g., by RoundRobinLB), but now nothing overrides them and MultiChildLB doesn't even call one of them.

util: Remove minor convenience functions from MultiChildLB

---

core/src/main/java/io/grpc/internal/PickFirstLeafLoadBalancer.java
core/src/test/java/io/grpc/internal/PickFirstLeafLoadBalancerTest.java

This would impact TRANSIENT_FAILURE and refreshNameResolver() logic for dual-stack endpoints.

core: PF Index.size() should be number of addresses

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java

No usages actually needed a map nor a copy.

util: Remove MultiChildLB.getImmutableChildMap()

---

android-interop-testing/build.gradle
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/main/java/io/grpc/testing/integration/CustomBackendMetricsLoadBalancerProvider.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java

This removes the auth dependency and the implicit xds/orca from AbstractInteropTest for things that weren't used in all but one case.

interop-testing: Move interop tests only used by test client to the test client

---

core/src/main/java/io/grpc/internal/PickFirstLeafLoadBalancer.java
core/src/test/java/io/grpc/internal/PickFirstLeafLoadBalancerTest.java

This is the same as if we received a GOAWAY. We wait for the next RPC to begin connecting again. This is InternalSubchannel's behavior.

core: In PF, disjoint update while READY should transition to IDLE

---

xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java
xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancerProvider.java
xds/src/test/java/io/grpc/xds/ClusterManagerLoadBalancerProviderTest.java
xds/src/test/java/io/grpc/xds/ClusterManagerLoadBalancerTest.java

While child LB policies are unlikey to change for each cluster name (RLS returns regular cluster names, so should be unique), and the configuration for CDS policies won't change, RLS configuration can definitely change.
----
In a following commit I'll remove child policy config from the child's state, because it should be updated every address update. At that point `unusedChildConfig` will go away. But that's straight-forward compared to this commit.
The impact of MultiChildLB is really small, as getChildAddresses() could easily ignore the state stored in MultiChildLB. Most of this is the typical "migrate to GracefulSwitchLoadBalancer" changes. But ClusterManagerLoadBalancerTest is probably the biggest non-trivial change that hasn't been seen before.

xds: ClusterManagerLB must update child configuration

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
util/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java
xds/src/main/java/io/grpc/xds/LeastRequestLoadBalancer.java
xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java

The child policy config should be refreshed every address update, so it shouldn't be stored in the ChildLbState. In addition, none of the current usages actually used what was stored in the ChildLbState in a meaningful way (it was always null).
ResolvedAddresses was also removed from createChildLbState(), as nothing in it should be needed for creation; it varies over time and the values passed at creation are immutable.

util: Remove child policy config from MultiChildLB state

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java

No need to look up in the map to see if they are still a child.

util: MultiChildLB children know if they are active

---

opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryTracingModule.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryTracingModuleTest.java

What is missing.
1. Server side `Context` propagation, i.e. in `StreamTracer.filterContext()`, OpenTelemetry Context does not automatically propagate to another thread. This needs a separate PR to override grpcContextStorage.
2. `inboundMessageRead` in deframer will supply `optionalWireSize`  == `optionalUncompressedSize` in compression situation.

add OpenTelemetryTracingModule

---

api/src/main/java/io/grpc/InternalSubchannelAddress.java
api/src/main/java/io/grpc/InternalSubchannelAddressAttributes.java
api/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/InternalSubchannel.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
util/src/main/java/io/grpc/util/ForwardingSubchannel.java
xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/main/java/io/grpc/xds/client/LoadStatsManager2.java
xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java

This fixes Incorrect load reporting when using pick first as locality-routing policy.
Cause: ClusterImplLoadBalancer used to assume all the address are in the same locality and used first address in the list of addresses to determine locality. This is not always true leading to incorrect load reporting.
Fix: Get locality from address connected by the subchannel.
Closes #11434.

xds: Fix load reporting when pick first is used for locality-routing.

---

core/src/main/java/io/grpc/internal/ReadableBuffers.java

Detachable lets a buffer outlive its original lifetime. The new lifetime is application-controlled. If the application fails to read/close the stream, then the leak detector wouldn't make clear what code was responsible for the buffer's lifetime. With this touch, we'll be able to see detach() was called and thus know the application needs debugging.
Realized when looking at b/364531464, although I think the issue is unrelated.

core: touch() buffer when detach()ing

---

core/src/main/java/io/grpc/internal/ReadableBuffers.java

Detachable lets a buffer outlive its original lifetime. The new lifetime is application-controlled. If the application fails to read/close the stream, then the leak detector wouldn't make clear what code was responsible for the buffer's lifetime. With this touch, we'll be able to see detach() was called and thus know the application needs debugging.
Realized when looking at b/364531464, although I think the issue is unrelated.
Backport of #11510

core: touch() buffer when detach()ing (1.66.x backport)

---

core/src/main/java/io/grpc/internal/ReadableBuffers.java

Detachable lets a buffer outlive its original lifetime. The new lifetime is application-controlled. If the application fails to read/close the stream, then the leak detector wouldn't make clear what code was responsible for the buffer's lifetime. With this touch, we'll be able to see detach() was called and thus know the application needs debugging.
Realized when looking at b/364531464, although I think the issue is unrelated.
Backport of #11510

core: touch() buffer when detach()ing (1.67.x backport)

---

xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java

Unit test: `pickFirstLoadReport_onUpdateAddress()` was checking equality of localityStats based on position, but the list returned by `upstreamLocalityStatsList` is an unordered list. 
Updated to verify equality of localityStats independent of its position in the list.
CC @shivaspeaks

xds: Fix flakiness in `ClusterImplLoadBalancerTest.pickFirstLoadReport_onUpdateAddress()`

---

core/src/main/java/io/grpc/internal/PickFirstLeafLoadBalancer.java
core/src/test/java/io/grpc/internal/PickFirstLeafLoadBalancerTest.java

This blocks top level versions from doing any health checking, while those under petiole policies can.
Fixes #11413

use an attribute from resolved addresses IS_PETIOLE_POLICY to control whether or not health checking is supported

---

buildscripts/kokoro/macos.sh
buildscripts/kokoro/unix.sh

unix.sh is shared by multiple OSes and environments. Clear JAVA_HOME, since we never want to use that as PATH is more reliable, better supported, and more typical.

buildscripts: OS X env should be in macos.sh

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java

This PR adds xDS node ID in control plane errors to enable cross-referencing with control plane logs when debugging (b/364405814). 
CC @fengli79

xds: Add xDS node ID in few control plane errors

---

cronet/build.gradle
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

Created a way to detect insufficient threads to start the transport for read and write simultaneously. 
Fixes #11271

Detect transport executors with no remaining threads

---

s2a/src/test/java/io/grpc/s2a/handshaker/IntegrationTest.java

Move awaitTermination to after the server shutdown.
Fixes #11527

Fix slow tests that took 40 seconds to get through tearDown.

---

s2a/src/test/java/io/grpc/s2a/handshaker/IntegrationTest.java

Move unused and unimportant fields to local variables. pickUnusedPort() is inherently racy, so avoid using it when unnecessary. The channel's default executor is fine to use, but if you don't like it directExecutor() would be an option too. But blocking stub doesn't even use the executor for unary RPCs. Thread.join() does not propagate exceptions from the Thread; it just waits for the thread to exit.
@rmehta19

s2a: Cleanups to IntegrationTest

---

contextstorage/build.gradle
contextstorage/src/main/java/io/grpc/override/ContextStorageOverride.java
contextstorage/src/main/java/io/grpc/override/OpenTelemetryContextStorage.java
contextstorage/src/test/java/io/grpc/override/OpenTelemetryContextStorageTest.java
settings.gradle

b/357892637
follow up with https://github.com/grpc/grpc-java/pull/11500
opencensus shim will find opentelmetry context when using opencensus {@link io.opencensus.trace.unsafe.ContextManagerImpl}, but does not solve the problem of bridging io.grpc.context and io.opentelemetry.context
otel implementation does not have otel over grpc contxt: 
https://github.com/open-telemetry/opentelemetry-java/blob/18d192d1fadc6f6dd4dfbff01c0c139eaf93c604/context/src/grpcInOtelTest/java/io/grpc/override/ContextStorageOverride.java
other implementation: 
https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/grpc-1.6/library#library-instrumentation-for-grpc-160

Implement ContextStorageOverride for opentelemetry context bridge

---

netty/src/main/java/io/grpc/netty/InternalProtocolNegotiators.java
s2a/src/main/java/io/grpc/s2a/channel/S2AHandshakerServiceChannel.java
s2a/src/main/java/io/grpc/s2a/handshaker/S2AProtocolNegotiatorFactory.java
s2a/src/test/java/io/grpc/s2a/channel/S2AHandshakerServiceChannelTest.java

Addresses https://github.com/grpc/grpc-java/pull/11113#discussion_r1761935897 and https://github.com/grpc/grpc-java/pull/11113#discussion_r1761954130

s2a,netty: S2AHandshakerServiceChannel doesn't use custom event loop.

---

examples/build.gradle
examples/example-alts/build.gradle
examples/example-debug/build.gradle
examples/example-debug/pom.xml
examples/example-dualstack/build.gradle
examples/example-dualstack/pom.xml
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-gcp-csm-observability/build.gradle
examples/example-gcp-observability/build.gradle
examples/example-hostname/build.gradle
examples/example-hostname/pom.xml
examples/example-jwt-auth/build.gradle
examples/example-jwt-auth/pom.xml
examples/example-oauth/build.gradle
examples/example-oauth/pom.xml
examples/example-opentelemetry/build.gradle
examples/example-orca/build.gradle
examples/example-reflection/build.gradle
examples/example-servlet/build.gradle
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/example-xds/build.gradle
examples/pom.xml
gradle/libs.versions.toml

Update protobuf-java to address CVE-2024-7254

---

s2a/build.gradle

Needs to add @ExperimentalApi to public classes until goes through a grpc design review
See comments on: #11113 most importantly:
- Need to eliminate all blocking
- Need to close channels when no longer needed (ProtocolNegotiator.close() was called)
- Need to document where all certs came from 
CC @rmehta19

s2a: Disabling publishing until it is ready for users

---

xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java

This PR adds null check for xdsClient in onSubChannelState. 
This avoids NPE for xdsClient when LB is shutdown and onSubChannelState is called later as part of listener callback. As shutdown is racy and eventually consistent, this check would avoid calculating locality after LB is shutdown.
b/369220083

xds: Check for validity of xdsClient in ClusterImplLbHelper

---

xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java

This PR adds null check for xdsClient in onSubChannelState. 
This avoids NPE for xdsClient when LB is shutdown and onSubChannelState is called later as part of listener callback. As shutdown is racy and eventually consistent, this check would avoid calculating locality after LB is shutdown.
b/369220083
Backport of #11553
CC @apolcyn

xds: Check for validity of xdsClient in ClusterImplLbHelper (v1.67.x backport)

---

xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java

The main goal was to make sure subchannels went CONNECTING only after a connection was requested (since the test doesn't transition to CONNECTING from TF). That helps guarantee that the test is using the expected subchannel.
The missing ClusterImplLB.requestConnection() doesn't actually matter much, as cluster manager doesn't propagate connection requests.
CC @DNVindhya. This doesn't change the test we were looking at yesterday, but I'll have a follow-up that will.

xds: Improve ClusterImpl's FakeSubchannel to verify state changes

---

android/src/main/java/io/grpc/android/UdsChannelBuilder.java

This avoids a DNS lookup, which can be slow and fail.
Fixes #11442

android: For UDS, use fake IP instead of localhost

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java

Instead of doing a dance of supplementing config so the later createChildAddressesMap() won't delete children, just look at the existing children and don't delete any that shouldn't be deleted.

xds: Have ClusterManagerLB use child map for preserving children

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
xds/src/test/java/io/grpc/xds/LeastRequestLoadBalancerTest.java

Tests were converted to use getChildLbStateEag() if the argument was an EAG, so the instanceof was no longer necessary.

util: Simplify MultiChildLB.getChildLbState()

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

Supercedes https://github.com/grpc/grpc-java/pull/11368 raised earlier for the same issue.
Fixes #11040

Make address resolution error use the default service config

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java

A map of children is still needed, but is created temporarily on update. The order of children is currently preseved, but we could use regular HashMaps if that is not useful.

util: Store only a list of children in MultiChildLB

---

okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/Platform.java

When running on the JDK, it is quite normal for Conscrypt not to be present. We'll end up using the JDK 9 ALPN API and everything will be fine. On Android, it would be extremely rare for someone to completely remove the default Android security providers, so the warning was almost never going to trigger on that platform anyway.
Fixes #11576. Alternative to #11567

okhttp: Don't warn about missing Conscrypt

---

api/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/InternalSubchannel.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/PickFirstLeafLoadBalancer.java
core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
core/src/test/java/io/grpc/internal/PickFirstLeafLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java

Hide behind environment variable GRPC_SERIALIZE_RETRIES
This is for testing with GMS core to see if they use the new PF with only 1 subchannel at a time trying to reconnect whether that eliminates their 6% data increase.

Change PickFirstLeafLoadBalancer to only have 1 subchannel at a time

---

contextstorage/build.gradle
settings.gradle

follow up on https://github.com/grpc/grpc-java/pull/11500

rename grpc-context-override-opentelemetry and publish artifact

---

xds/src/main/java/io/grpc/xds/client/ControlPlaneClient.java
xds/src/main/java/io/grpc/xds/client/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java

According to [gRFC A57](https://github.com/grpc/proposal/blob/master/A57-xds-client-failure-mode-behavior.md#handling-ads-stream-termination):
> If the ADS stream is closed without ever having received a response from the server, then the XdsClient should consider that a connectivity error. It should log the error and report the error to all watchers of resources that were subscribed to on that stream.
For `status == OK`, updated the new status to `Status.UNAVAILABLE` with description "ADS stream closed with OK before receiving a response".
> Note that we do not consider it an error if the ADS stream was closed after having received a response on the stream. This is because there are legitimate reasons why the server may need to close the stream during normal operations, such as needing …

xds: Update error handling for ADS stream close and failure scenarios

---

core/src/test/java/io/grpc/internal/RetriableStreamTest.java

The rootcause is reentrant lock has more than one hold count. In this case, lock1 is held when stream4 is created within sublistener.closed callback. It can just be released, no tryLock(), which increment the lock hold count in the current thread, and prevent thread1 from acquiring lock1.
Tested with blaze test `--runs_per_test=100`:
http://sponge2/caeee424-089f-456e-99de-eb82a35558ba
cc. @ejona86

core: fix test flakiness in retriableStream hedging deadlock test

---

s2a/build.gradle

There are a few comments which we will get to in followup CL's:
https://github.com/grpc/grpc-java/pull/11540
https://github.com/grpc/grpc-java/pull/11534
https://github.com/grpc/grpc-java/pull/11539
https://github.com/grpc/grpc-java/pull/11113#discussion_r1762063248
I think all major comments / refactoring after https://github.com/grpc/grpc-java/pull/11113 have been addressed. Are we ok to enable publishing of s2a?

s2a: Enable publishing.

---

interop-testing/src/main/java/io/grpc/testing/integration/TestServiceServer.java
interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java

when i build `grpc-java` project.  i find a unit test error. 
reason：
`Util.getV4Address(port);`  obtained address conflicts with the local address

fix XdsTestServer/TestServiceServer listenAddresses conflict

---

stub/src/main/java/io/grpc/stub/ServerCalls.java
stub/src/test/java/io/grpc/stub/ServerCallsTest.java

added fix for ignore unary response if status is not OK along with Junit
Fixes https://github.com/grpc/grpc-java/issues/5969

grpc-stub: added fix for ignore unary response if status is not OK 

---

gcp-csm-observability/src/main/java/io/grpc/gcp/csm/observability/MetadataExchanger.java
gcp-csm-observability/src/test/java/io/grpc/gcp/csm/observability/CsmObservabilityTest.java
gcp-csm-observability/src/test/java/io/grpc/gcp/csm/observability/MetadataExchangerTest.java

This PR updates how the mesh_id local label is assigned.
Instead of deriving it from the bootstrap or parsing it from the bootstrap's node_id, the mesh_id will now be set using the `CSM_MESH_ID` environment variable.
CC  @yashykt

gcp-csm-o11y: Get mesh_id from environment variable

---

api/src/main/java/io/grpc/CallCredentials.java

The current Javadoc for the method `CallCredentials.applyRequestMetadata` seems unclear or possibly contains an error. It currently states:
> the implementation may give the `applier` to an asynchronous task which will eventually call the `applier`.
I believe this should be clarified to:
> the implementation may give the `appExecutor` an asynchronous task which will eventually call the `applier`.
This change better explains the usage of `appExecutor` in this method.

api: fix javadoc of CallCredentials.applyRequestMetadata

---

netty/build.gradle
netty/src/main/java/io/grpc/netty/NettyClientTransport.java

In NettyClientTransport, the TCP_USER_TIMEOUT attribute can be set only if the channel is of the AbstractEpollStreamChannel.
Fixes #11517

TCP_USER_TIMEOUT property setting issue fixed

---

binder/src/main/java/io/grpc/binder/internal/BinderTransport.java

Callers are frequently confused by this message and waste time looking for problems in the client when the root cause is a server crash. See b/371447460 for more context.

Update binderDied() error description to spell out the possibilities for those unfamiliar with Android internals.

---

stub/src/main/java/io/grpc/stub/ServerCalls.java
stub/src/test/java/io/grpc/stub/ServerCallsTest.java

This reverts commit 99f86835ed8a1c960d532e58b5fd51ec1bb99825.
The change doesn't handle `null` messages, which don't happen with protobuf, but can happen with other marshallers, especially in tests. See cl/689445172
This will reopen #5969
CC @NaveenPrasannaV
Backport of #11636

Revert "stub: Ignore unary response on server if status is not OK" (1.68.x backport)

---

binder/src/test/java/io/grpc/binder/internal/BinderServerTransportTest.java
binder/src/test/java/io/grpc/binder/internal/ServiceBindingTest.java

PAUSED Looper mode has been the default for many years, maybe around robolectric 4.5 (9ae9f0b6a6). Explicitly specifying PAUSED Looper mode is not necessary.
cl/690684542
CC @hoisie
------
I did look up the robolectric 4.5 version, and we're on 4.13 so everything seems in-place.

binder: Remove unnecessary uses of LooperMode(PAUSED)

---

alts/build.gradle
authz/build.gradle
build.gradle
examples/example-hostname/build.gradle
examples/gradle/wrapper/gradle-wrapper.properties
gradle/wrapper/gradle-wrapper.properties
netty/shaded/build.gradle
s2a/build.gradle
settings.gradle
xds/build.gradle

com.github.johnrengelman.shadow is now com.gradleup.shadow (note the redirect)
https://github.com/johnrengelman/shadow/releases/tag/8.3.0

Upgrade Gradle to 8.10.2 and upgrade plugins

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java

Fixes NPE from "Detect transport executors with no remaining threads #11503".

If the frame handler thread is null do not schedule it on the executor

---

repositories.bzl
xds/third_party/envoy/import.sh
xds/third_party/envoy/src/main/proto/envoy/config/cluster/v3/cluster.proto
xds/third_party/envoy/src/main/proto/envoy/config/core/v3/protocol.proto
xds/third_party/envoy/src/main/proto/envoy/config/core/v3/socket_cmsg_headers.proto
xds/third_party/envoy/src/main/proto/envoy/config/core/v3/socket_option.proto
xds/third_party/envoy/src/main/proto/envoy/config/endpoint/v3/load_report.proto
xds/third_party/envoy/src/main/proto/envoy/config/listener/v3/quic_config.proto
xds/third_party/envoy/src/main/proto/envoy/config/route/v3/route_components.proto
xds/third_party/envoy/src/main/proto/envoy/config/trace/v3/datadog.proto
xds/third_party/envoy/src/main/proto/envoy/config/trace/v3/dynamic_ot.proto
xds/third_party/envoy/src/main/proto/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
xds/third_party/envoy/src/main/proto/envoy/extensions/load_balancing_policies/client_side_weighted_round_robin/v3/client_side_weighted_round_robin.proto
xds/third_party/envoy/src/main/proto/envoy/extensions/transport_sockets/tls/v3/common.proto
xds/third_party/envoy/src/main/proto/envoy/extensions/transport_sockets/tls/v3/tls.proto

envoyproxy/envoy: Sync protos to the latest imported version https://github.com/envoyproxy/envoy/commit/742a3b02e3b2a9dfb877a7e378607c6ed0c2aa53 (commit 2024-10-23, cl/692906546).
Should be a noop, just a routine xDS proto update to make upcoming GCP_Auth_Filter related imports simpler.

xds: Envoy proto sync to 2024-10-23

---

xds/BUILD.bazel

feab4e54 removed xds v2 for the Gradle build. Testing with a deploy.jar, I see the same 4 MB size reduction (31 -> 27 MB) here.
While an orca dependency is deleted in this commit, it is only a direct dependency. It remains in the :orca target, so doesn't contribute a size reduction.
CC @sergiitk

xds: Remove Bazel dependency on xds v2

---

servlet/src/main/java/io/grpc/servlet/ServletServerStream.java

This brings grpc-servlet in line with the grpc-netty implementation found in NettyServerStream.TransportState.

Deframe failures should be logged on the server as warnings

---

xds/src/main/java/io/grpc/xds/GcpAuthenticationFilter.java

Fixes failing checks (["ImpossibleNullError"](http://go/bugpattern/ImpossibleNullComparison)) during google3 import of GcpAuthenticationFilter from Github.

Replace null check with has value check because proto fields can never be null

---

s2a/src/test/java/io/grpc/s2a/internal/handshaker/FakeS2AServerTest.java

While here:
- add an `awaitTermination` to after calling shutdown on server
- don't use port picker

s2a: fix flake in FakeS2AServerTest

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
util/src/test/java/io/grpc/util/MultiChildLoadBalancerTest.java
util/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
util/src/testFixtures/java/io/grpc/util/AbstractTestHelper.java
xds/src/main/java/io/grpc/xds/LeastRequestLoadBalancer.java
xds/src/test/java/io/grpc/xds/LeastRequestLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

This is a step toward removing ResolvedAddresses from ChildLbState, which isn't actually used by MultiChildLb. Most usages of the EAG usages can be served more directly without peering into MultiChildLb's internals or even accessing ChildLbStates, which make the tests less sensitive to implementation changes. Some changes do leverage the new behavior of MultiChildLb where it preserves the order of the entries.
This does fix an important bug in shutdown tests. The tests looped over the ChildLbStates after shutdown, but shutdown deleted all the children so it looped over an entry collection. Fixing that exposed that deliverSubchannelState() didn't function after shutdown, as the listener was removed from the map when the subchannel was shut down. Moving the listener onto the TestSubchannel …

util: Remove EAG conveniences from MultiChildLb

---

services/src/main/java/io/grpc/protobuf/services/ChannelzProtoUtil.java
services/src/test/java/io/grpc/protobuf/services/ChannelzProtoUtilTest.java

This will allow android apps to expose internal grpc-java state for debugging.

Make channelz work with proto lite

---

api/src/main/java/io/grpc/NameResolver.java

Backport of #11666 to v1.68.x.
---
When forwarding from Listener onAddresses to Listener2 continue to use onResult and not onResult2 because the latter requires to be called from within synchronization context and it breaks existing code that didn't need to do so when using the old Listener interface
Fixed #11662.

api: When forwarding from Listener onAddresses to Listener2 continue to use onResult (v1.68.x backport)

---

core/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java
core/src/testFixtures/java/io/grpc/internal/PickFirstLoadBalancerProviderAccessor.java
util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
util/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java

It isn't actually used by MultiChildLb, and using the health API gives us more confidence that health is properly plumbed.

util: Remove resolvedAddresses from MultiChildLb.ChildLbState

---

services/build.gradle

Generated code for v1alpha was ignored, but not v1. Ignoring v1 reduces lines being checked from 16,145 to 6,303, significantly improving the overall code coverage and removing noise. This was noticed because there was a very clear drop at 0aa976c4 visible in the coveralls.io coverage graph, the point when v1 was introduced.

services: Don't track code coverage of reflection.v1 gencode

---

core/src/test/java/io/grpc/internal/InstantTimeProviderTest.java

Updated the tolerance time to 1 sec as per the latest discussion to fix the flaky test.
Fixes https://github.com/grpc/grpc-java/issues/11680

core-test: updated the tolerance time to 1 second

---

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/main/java/io/grpc/testing/integration/TestCases.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
interop-testing/src/main/java/io/grpc/testing/integration/XdsFederationTestClient.java

The goal of this PR is to increase the test coverage of the C2P E2E load test by improving the rpc_soak and channel_soak tests to support concurrency.
**rpc_soak:**
The client performs many large_unary RPCs in sequence over the same channel. The test can run in either a concurrent or non-concurrent mode, depending on the number of threads specified (soak_num_threads):
- Non-Concurrent Mode: When soak_num_threads = 1, all RPCs are performed sequentially on a single thread.
- Concurrent Mode: When soak_num_threads > 1, the client uses multiple threads to distribute the workload. Each thread performs a portion of the total soak_iterations, executing its own set of RPCs concurrently.
**channel_soak:**
Similar to rpc_soak, but this time each RPC is performed on a new channel. The channel is …

interop-testing: Add concurrency condition to the soak test using existing blocking api 

---

binder/src/main/java/io/grpc/binder/AndroidComponentAddress.java
binder/src/main/java/io/grpc/binder/BinderChannelBuilder.java
binder/src/main/java/io/grpc/binder/internal/BinderClientTransportFactory.java
binder/src/main/java/io/grpc/binder/internal/BinderTransport.java
binder/src/test/java/io/grpc/binder/AndroidComponentAddressTest.java

The target UserHandle is best modeled as part of the SocketAddress since it's part of the server's location.
This change allows a NameResolver to select different target users over time within a single Channel.

Let AndroidComponentAddress specify a target UserHandle

---

gae-interop-testing/gae-jdk8/src/main/webapp/WEB-INF/appengine-web.xml

Java 11 is out-of-support on GAE. Unfortunately the docs use the term "deprecated" as "deleted," not "discouraged." So they talk about it being deprecated _after_ it is no longer supported.
https://cloud.google.com/appengine/docs/standard/lifecycle/support-schedule#java https://cloud.google.com/appengine/docs/flexible/lifecycle/support-schedule#java

gae-interop-testing: Upgrade to Java 17

---

interop-testing/src/test/java/io/grpc/testing/integration/ProxyTest.java

Enabled smallLatency() test which was ignored earlier and its working as Expected as I don't see any latency issue here.
Fixes https://github.com/grpc/grpc-java/issues/2951

testing: enabled smallLatency test

---

examples/example-gcp-csm-observability/build.gradle
examples/example-gcp-csm-observability/src/main/java/io/grpc/examples/csmobservability/CsmObservabilityClient.java
examples/example-gcp-csm-observability/src/main/java/io/grpc/examples/csmobservability/CsmObservabilityServer.java

Change - 
The CSM Observability examples will now use an xDS enabled server and xds credentials with a fallback on insecure credentials. This allows users to try configuring authn/mtls and authz/rbac using the same example images.
(Existing example uses a non-xds enabled server and insecure credentials.)

[CSM] Use xds-enabled server and xds credentials in examples

---

gae-interop-testing/gae-jdk8/src/main/webapp/WEB-INF/appengine-web.xml

Java 11 is out-of-support on GAE. Unfortunately the docs use the term "deprecated" as "deleted," not "discouraged." So they talk about it being deprecated _after_ it is no longer supported.
https://cloud.google.com/appengine/docs/standard/lifecycle/support-schedule#java https://cloud.google.com/appengine/docs/flexible/lifecycle/support-schedule#java
Backport of #11699

gae-interop-testing: Upgrade to Java 17 (v1.68.x backport)

---

api/src/testFixtures/java/io/grpc/testing/DeadlineSubject.java

This was noticed because of a CallOptionsTest flake that had a surprising error:
```
expected                    : 59.983387319
but was                     : 59.983387319
outside tolerance in seconds: 0.01
```

api: DeadlineSubject should include actual on failure

---

xds/src/main/java/io/grpc/xds/XdsServerWrapper.java

According to gRFC [A71 xDS Fallback]( https://github.com/grpc/proposal/blob/master/A71-xds-fallback.md#update-csds-to-aggregate-configs-from-multiple-xdsclient-instances):
> Update CSDS to aggregate configs from multiple XdsClient instances.
>
> The CSDS RPC service will be changed to get data from all XdsClient instances. A new string field named client_scope will be added to the CSDS [ClientConfig](https://github.com/envoyproxy/envoy/blob/e61e461736a28e26b6fcf0ca25d34c47ed29b0fc/api/envoy/service/status/v3/csds.proto#L130) message to indicate the channel target the data is associated with. For gRPC clients, this field will contain the key channels use to lookup their XdsClient instance, such as dataplane target for client channels or special value **"#server" for xDS-enabled gRPC …

xds: Add `grpc.target` value for xDS enabled server metrics

---

examples/example-gcp-csm-observability/build.gradle
examples/example-gcp-csm-observability/src/main/java/io/grpc/examples/csmobservability/CsmObservabilityClient.java
examples/example-gcp-csm-observability/src/main/java/io/grpc/examples/csmobservability/CsmObservabilityServer.java

[CSM] Use xds-enabled server and xds credentials in examples (v1.68.x backport)

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java

Fixes NPE from "Detect transport executors with no remaining threads #11503".
Backport of #11651

If the frame handler thread is null do not schedule it on the executor (1.68.x backport)

---

.github/workflows/testing.yml

The two Bazel versions are completely separate; no need to run them serially.
----
We started testing against two versions because of bzlmod. Even when we drop 6.0.0 we're going to need to keep two runs, one with and one without bzlmod. I was noticing it was taking a while to run compared to our other GitHub Actions, and I think this makes it more clear what is going on anyway.

.github/workflows: Split Bazel into two jobs

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpProtocolNegotiator.java

Backport of #11725 to v1.69.x.
---
With these changes scoped ipv6 link is supported.
This was previously attempted in #9326 but due to internal failures it was reverted. We now fixed the internal issues, so this should go seamlessly.
Fixes #9325

okhttp: Fix for ipv6 link local with scope (v1.69.x backport)

---

s2a/src/main/java/io/grpc/s2a/internal/handshaker/tokenmanager/SingleTokenFetcher.java
s2a/src/test/java/io/grpc/s2a/internal/handshaker/GetAuthenticationMechanismsTest.java
s2a/src/test/java/io/grpc/s2a/internal/handshaker/tokenmanager/SingleTokenAccessTokenManagerTest.java

This is the easy-to-fix state, but GetAuthenticationMechanisms can save these temporary states used in tests, so more fixes will be necessary.
CC @rmehta19

s2a: Restore static token state mutated in tests

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java

ObjectPool is our standard solution for dealing with the sometimes-shutdown resources. This was implemented by a contributor not familiar with regular tools.
There are wider changes that can be made here, but I chose to just do a smaller change because this class is used by GrpclbNameResolver.

core: Simplify DnsNameResolver by using ObjectPool

---

examples/example-hostname/src/main/java/io/grpc/examples/hostname/HostnameServer.java

I've slept since I wrote the original code, so now I see a less repetitive implementation.
------
Is this better? I figured we'd want to make it any nicer before we copy it to any other examples.
I changed the first comment to make it clearer that awaitTermination() doesn't sleep the full 30 seconds if it doesn't need to.

examples: Simplify graceful shutdown in Hostname example

---

xds/src/main/java/io/grpc/xds/client/ControlPlaneClient.java
xds/src/test/java/io/grpc/xds/XdsClientFallbackTest.java

Eliminate unneeded fakeClock.forwardTime() that was causing the conflict.
```
Read of size 8 at 0x00008eea4e28 by thread T24:
#0 io.grpc.internal.FakeClock$ScheduledExecutorImpl.schedule(Lio/grpc/internal/FakeClock$ScheduledTask;JLjava/util/concurrent/TimeUnit;)V FakeClock.java:140 
#1 io.grpc.internal.FakeClock$ScheduledExecutorImpl.schedule(Ljava/lang/Runnable;JLjava/util/concurrent/TimeUnit;)Ljava/util/concurrent/ScheduledFuture; FakeClock.java:150 
#2 io.grpc.SynchronizationContext.schedule(Ljava/lang/Runnable;JLjava/util/concurrent/TimeUnit;Ljava/util/concurrent/ScheduledExecutorService;)Lio/grpc/SynchronizationContext$ScheduledHandle; SynchronizationContext.java:153 
#3 io.grpc.xds.client.XdsClientImpl$ResourceSubscriber.restartTimer()V XdsClientImpl.java:779 
#4 …
```

Fix tsan error

---

xds/src/main/java/io/grpc/xds/client/BootstrapperImpl.java
xds/src/test/java/io/grpc/xds/GrpcBootstrapperImplTest.java

It was clearly defined in gRFC A30. The relevant text was copied as a comment in the code.
As discovered due to grpc/grpc-go#7932

xds: Unexpected types in server_features should be ignored

---

okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/OkHostnameVerifier.java

Implement fix to address a security issue related to maliciously crafted hostnames during certificate validation in OkHttp
grpc-java is susceptible to [CVE-2021-0341](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-0341)
This mirrors the okhttp patch for this exploit available in https://github.com/square/okhttp/pull/6353

fix security issue with okhttp

---

xds/src/main/java/io/grpc/xds/StructOrError.java
xds/src/main/java/io/grpc/xds/XdsClusterResource.java
xds/src/main/java/io/grpc/xds/XdsRouteConfigureResource.java
xds/src/main/java/io/grpc/xds/client/XdsResourceType.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java

StructOrError is a more generic API, but we have StatusOr now so we don't want new usages of StructOrError. Moving StructOrError out of io.grpc.xds.client will make it easier to delete StructOrError once we've migrated to StatusOr in the future.
TRANSPORT_SOCKET_NAME_TLS should also move, but it wasn't immediately clear to me where it should go.

xds: Move specialized APIs out of XdsResourceType

---

xds/src/main/java/io/grpc/xds/client/BootstrapperImpl.java
xds/src/test/java/io/grpc/xds/GrpcBootstrapperImplTest.java

It was clearly defined in gRFC A30. The relevant text was copied as a comment in the code.
As discovered due to grpc/grpc-go#7932
Backport of #11751

xds: Unexpected types in server_features should be ignored (1.68.x backport)

---

.github/workflows/testing.yml

Bazel 8 is now out. We support the two most recent releases.
FWIW, I have compiled with Bazel 8 and didn't experience any problems.

.github/workflows: Stop testing Bazel 6

---

xds/src/main/java/io/grpc/xds/XdsClusterResource.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java

Added change for circuit breaking by converting signed 32-bit Int to Unsigned 64-bit Long For MaxRequest negative value ( -1)
Fixes https://github.com/grpc/grpc-java/issues/11695

xds: fixed unsupported unsigned 32 bits issue for circuit breaker

---

xds/src/main/java/io/grpc/xds/client/BootstrapperImpl.java
xds/src/test/java/io/grpc/xds/GrpcBootstrapperImplTest.java

It was clearly defined in gRFC A30. The relevant text was copied as a comment in the code.
As discovered due to grpc/grpc-go#7932
Backport of #11751

xds: Unexpected types in server_features should be ignored (1.69.x backport)

---

xds/src/main/java/io/grpc/xds/client/ControlPlaneClient.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java

The backoffPolicy was calculating time since last attempt, but if the stream had been successfully connected and received responses it should delay from the current time (i.e. reset the stopwatch).  Changed test so that stopwatch wasn't always 0, which masked the problem.

xds: Fix XDS control plane client retry timer backoff duration when connection closes after results are received

---

xds/src/main/java/io/grpc/xds/XdsClientMetricReporterImpl.java
xds/src/test/java/io/grpc/xds/XdsClientMetricReporterImplTest.java

XdsClient metrics were added in #11661. It is missing `grpc.xds.authority` label for `grpc.xds_client.resources` gauge. 
While label value is absent, label got added while registering the gauge. This leads to `java.lang.IllegalArgumentException: Incorrect number of required labels provided.` on invoking callback.  Stack trace is added below:
```
00:25:09.808 [PeriodicMetricReader-1] WARN  i.o.s.m.i.state.CallbackRegistration - An exception occurred invoking callback for CallbackRegistration{instrumentDescriptors=[InstrumentDescriptor{name=grpc.xds_client.resources, description=EXPERIMENTAL.  Number of xDS resources., unit={resource}, type=OBSERVABLE_GAUGE, valueType=LONG, advice=Advice{explicitBucketBoundaries=null, attributes=null}}, InstrumentDescriptor{name=grpc.xds_client.connected, …
```

xds: Remove xds authority label from metric registration

---

api/build.gradle
api/src/main/java/io/grpc/InternalStatus.java
api/src/main/java/io/grpc/InternalStatusRuntimeException.java
api/src/main/java/io/grpc/StatusException.java
api/src/main/java/io/grpc/StatusRuntimeException.java
api/src/test/java/io/grpc/StatusExceptionTest.java
api/src/test/java/io/grpc/StatusRuntimeExceptionTest.java
core/src/main/java/io/grpc/internal/ServerCallImpl.java
core/src/main/java/io/grpc/internal/ServerImpl.java

TBD, instead of https://github.com/grpc/grpc-java/pull/11066
Just demonstrating the idea, without comments in code for now.

StatusRuntimeException without stacktrace - Android compatibility

---

api/BUILD.bazel
api/build.gradle
api/src/main/java/io/grpc/IgnoreJRERequirement.java
api/src/test/java/io/grpc/CallOptionsTest.java
api/src/test/java/io/grpc/SynchronizationContextTest.java
api/src/test/java/io/grpc/TimeUtilsTest.java
buildscripts/checkstyle.xml
netty/build.gradle
stub/build.gradle

This avoids the dependency on animalsniffer-annotations. grpc-api, and particularly grpc-context, are used many low-level places and it is beneficial for them to be very low dependency. This brings grpc-context back to zero-dependency.

api: Use package-private IgnoreJRERequirement

---

examples/src/main/java/io/grpc/examples/header/HeaderClientInterceptor.java

Updated the deleted reference attachHeaders to newAttachHeadersInterceptor in HeaderClientInterceptor for header example
Fixes https://github.com/grpc/grpc-java/issues/11693

examples: Updated the deleted reference attachHeaders to newAttachHeadersInterceptor in HeaderClientInterceptor for header example

---

examples/build.gradle
examples/example-alts/build.gradle
examples/example-alts/settings.gradle
examples/example-debug/build.gradle
examples/example-dualstack/build.gradle
examples/example-dualstack/settings.gradle
examples/example-gauth/build.gradle
examples/example-gauth/settings.gradle
examples/example-gcp-csm-observability/build.gradle
examples/example-gcp-observability/build.gradle
examples/example-hostname/build.gradle
examples/example-jwt-auth/build.gradle
examples/example-jwt-auth/settings.gradle
examples/example-oauth/build.gradle
examples/example-oauth/settings.gradle
examples/example-opentelemetry/build.gradle
examples/example-orca/build.gradle
examples/example-reflection/build.gradle
examples/example-servlet/build.gradle
examples/example-servlet/settings.gradle
examples/example-tls/build.gradle
examples/example-tls/settings.gradle
examples/example-xds/build.gradle
examples/settings.gradle

As stated [on its main page][index], it isn't officially supported, so we shouldn't include it in our examples.
[index]: https://maven-central.storage-download.googleapis.com/index.html

examples: Remove references to maven-central.storage-download.googleapis.com

---

gae-interop-testing/gae-jdk8/build.gradle

These repositories are already included from the main build.gradle, so they don't do anything. Much less do they need to be defined twice in the same file.

gae-interop-testing: Remove duplicate repositories

---

android-interop-testing/build.gradle
android/build.gradle
binder/build.gradle
build.gradle
cronet/build.gradle
gradle/libs.versions.toml

The module metadata in Guava causes the -jre version to be selected even when you choose the -android version. Gradle did not give any clues that this was happening, and while
`println(configurations.compileClasspath.resolve())` shows the different jar in use, most other diagonstics don't. dependencyInsight can show you this is happening, but only if you know which dependency has a problem and read Guava's module metadata first to understand the significance of the results.
You could argue this is a Guava-specific problem. I was able to get parts of our build working with attributes and resolutionStrategy configurations mentioned at
https://github.com/google/guava/releases/tag/v32.1.0 , so that only Guava would be changed. But it was fickle giving poor error messages or silently swapping …

Disable Gradle Module Metadata resolution

---

netty/src/main/java/io/grpc/netty/CancelServerStreamCommand.java

In e036b1b198bfa2eb5fbdd27fc02a5df95ecd939b, CancelServerStreamCommand got another field. But, its hashCode and equals methods were not updated.

Fix equality and hashcode of CancelServerStreamCommand.

---

xds/src/main/java/io/grpc/xds/client/XdsClient.java
xds/src/test/java/io/grpc/xds/CsdsServiceTest.java

There's no reason to use the interface outside of
XdsClientImpl/ControlPlaneClient. Since XdsClientImpl implements the interface directly, its methods are still public. That can be a future cleanup.

xds: Make XdsClient.ResourceStore package-private

---

xds/src/main/java/io/grpc/xds/client/ControlPlaneClient.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java

This fixes a regression introduced in 19c9b998.
b/374697875

xds: Preserve nonce when unsubscribing type

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/main/java/io/grpc/xds/FilterChainMatchingProtocolNegotiators.java
xds/src/main/java/io/grpc/xds/GcpAuthenticationFilter.java
xds/src/main/java/io/grpc/xds/InternalXdsAttributes.java
xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/main/java/io/grpc/xds/WrrLocalityLoadBalancer.java
xds/src/main/java/io/grpc/xds/XdsAttributes.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/main/java/io/grpc/xds/XdsServerBuilder.java
xds/src/main/java/io/grpc/xds/internal/security/SecurityProtocolNegotiators.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WrrLocalityLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
xds/src/test/java/io/grpc/xds/XdsSecurityClientServerTest.java
xds/src/test/java/io/grpc/xds/internal/security/SecurityProtocolNegotiatorsTest.java

Internal* classes should generally be accessors that are used outside of the package/project. Only one attribute was used outside of xds, so leave only that one attribute in InternalXdsAttributes. One attribute was used by the internal.security package, so move the definition to the same package to reduce the circular dependencies.
CC @danielzhaotongliu

xds: Avoid depending on io.grpc.xds.Internal* classes

---

xds/src/main/java/io/grpc/xds/client/ControlPlaneClient.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java

If the control plane sends a resource type the client doesn't understand at-the-moment, the control plane will still expect the client to include the nonce if the client subscribes to the type in the future.
This most easily happens when unsubscribing the last resource of a type. Which meant 1cf1927d1 was insufficient.
CC @markdroth, @danielzhaotongliu

xds: Remember nonces for unknown types

---

xds/src/main/java/io/grpc/xds/ClusterMetadataRegistry.java
xds/src/main/java/io/grpc/xds/GcpAuthenticationFilter.java
xds/src/main/java/io/grpc/xds/MetadataRegistry.java
xds/src/main/java/io/grpc/xds/XdsClusterResource.java
xds/src/main/java/io/grpc/xds/internal/ProtobufJsonConverter.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java
xds/src/test/java/io/grpc/xds/internal/ProtobufJsonConverterTest.java

Add Support for Audience Metadata Parsing in xDS Cluster Resource

xds: Parsing xDS Cluster Metadata

---

netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java

Since approximately the LBv2 API (the current API) was introduced, gRPC won't use a transport until it is ready. Long ago, transports could be used before they were ready and these old tests were not waiting for the negotiator to complete before starting. We need them to wait for the handshake to complete to avoid a test-only data race in getAttributes() noticed by TSAN.
Throwing away data frames in the Noop handshaker is necessary to act like a normal handshaker; they don't allow data frames to pass until the handshake is complete. Without the handling, it goes through invalid code paths in NettyClientHandler where a terminated transport becomes ready, and a similar data race.
```
Write of size 4 at 0x00008db31e2c by thread T37:
#0 …
```

netty: Fix getAttributes() data races in NettyClientTransportTest

---

xds/src/main/java/io/grpc/xds/client/ControlPlaneClient.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java

This fixes a regression introduced in 19c9b998.
b/374697875
Backport of #11796

xds: Preserve nonce when unsubscribing type (1.69.x backport)

---

xds/src/main/java/io/grpc/xds/client/ControlPlaneClient.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java

This fixes a regression introduced in 19c9b998.
b/374697875
Backport of #11796

xds: Preserve nonce when unsubscribing type (1.68.x backport)

---

xds/src/main/java/io/grpc/xds/client/ControlPlaneClient.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java

If the control plane sends a resource type the client doesn't understand at-the-moment, the control plane will still expect the client to include the nonce if the client subscribes to the type in the future.
This most easily happens when unsubscribing the last resource of a type. Which meant 1cf1927d1 was insufficient.
Backport of #11799

xds: Remember nonces for unknown types (1.69.x backport)

---

xds/src/main/java/io/grpc/xds/client/ControlPlaneClient.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java

If the control plane sends a resource type the client doesn't understand at-the-moment, the control plane will still expect the client to include the nonce if the client subscribes to the type in the future.
This most easily happens when unsubscribing the last resource of a type. Which meant 1cf1927d1 was insufficient.
Backport of #11799

xds: Remember nonces for unknown types (1.68.x backport)

---

xds/src/test/java/io/grpc/xds/XdsClientFallbackTest.java
xds/src/test/java/io/grpc/xds/client/CommonBootstrapperTestUtils.java

These changes reduce connect_then_mainServerDown_fallbackServerUp test time from 20 seconds to 5 s by faking time for the the does-no-exist timer.
XdsClientImpl only uses the TimeProvider for CSDS cache details, so any implementation should be fine. FakeXdsClient provides an implementation, so might as well use it as it is one less clock to think about.

xds: Increase speed of fallback test

---

xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java

This is in service to [gRFC A89](https://github.com/grpc/proposal/pull/471). Since the gRFC isn't finalized this purposefully doesn't really do anything yet. The grpc-opentelemetry change to use this optional label will be done after the gRFC is merged. grpc-opentelemetry currently has a hard-coded list (one entry) of labels that it looks for, and this label will need to be added.
b/356167676 (specifically b/356167676#comment26)
CC @igorbernstein2

xds: Pass grpc.xds.cluster label to tracer

---

xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java

This is in service to [gRFC A89](https://github.com/grpc/proposal/pull/471). Since the gRFC isn't finalized this purposefully doesn't really do anything yet. The grpc-opentelemetry change to use this optional label will be done after the gRFC is merged. grpc-opentelemetry currently has a hard-coded list (one entry) of labels that it looks for, and this label will need to be added.
b/356167676 (specifically b/356167676#comment26)
CC @igorbernstein2
Backport of #11818

xds: Pass grpc.xds.cluster label to tracer (1.70.x backport)

---

core/src/main/java/io/grpc/internal/PickFirstLeafLoadBalancer.java
core/src/test/java/io/grpc/internal/PickFirstLeafLoadBalancerTest.java

The gRFC A61 states that addresses should be alternated in the Happy Eyeballs case rather than purely going in the specified order.

core: Alternate ipV4 and ipV6 addresses for Happy Eyeballs in PickFirstLeafLoadBalancer 

---

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

This PR resolves an issue with peer address extraction in the soak test. 
In current `TestServiceClient` implementation, the same `clientCallCapture` atomic is shared across threads, leading to incorrect peer extraction. This fix ensures that each thread uses a local variable for capturing the client call.

interop-testing: fix peer extraction issue in soak test iterations

---

xds/src/main/java/io/grpc/xds/XdsClientMetricReporterImpl.java
xds/src/test/java/io/grpc/xds/XdsClientMetricReporterImplTest.java

XdsClient metrics were added in #11661. It is missing `grpc.xds.authority` label for `grpc.xds_client.resources` gauge. 
While label value is absent, label got added while registering the gauge. This leads to `java.lang.IllegalArgumentException: Incorrect number of required labels provided.` on invoking callback.  Stack trace is added below:
```
00:25:09.808 [PeriodicMetricReader-1] WARN  i.o.s.m.i.state.CallbackRegistration - An exception occurred invoking callback for CallbackRegistration{instrumentDescriptors=[InstrumentDescriptor{name=grpc.xds_client.resources, description=EXPERIMENTAL.  Number of xDS resources., unit={resource}, type=OBSERVABLE_GAUGE, valueType=LONG, advice=Advice{explicitBucketBoundaries=null, attributes=null}}, InstrumentDescriptor{name=grpc.xds_client.connected, …
```

xds: Remove xds authority label from metric registration (v1.69.x backport)

---

xds/src/main/java/io/grpc/xds/XdsClusterResource.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java

Added change for circuit breaking by converting signed 32-bit Int to Unsigned 64-bit Long For MaxRequest negative value ( -1)
Fixes https://github.com/grpc/grpc-java/issues/11695
Backport of #11735

xds: fixed unsupported unsigned 32 bits issue for circuit breaker (1.68.x backport)

---

xds/src/main/java/io/grpc/xds/XdsClusterResource.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java

Added change for circuit breaking by converting signed 32-bit Int to Unsigned 64-bit Long For MaxRequest negative value ( -1)
Fixes https://github.com/grpc/grpc-java/issues/11695
Backport of #11735

xds: fixed unsupported unsigned 32 bits issue for circuit breaker (1.69.x backport)

---

okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/OkHostnameVerifier.java

Implement fix to address a security issue related to maliciously crafted hostnames during certificate validation in OkHttp
grpc-java is susceptible to [CVE-2021-0341](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-0341)
This mirrors the okhttp patch for this exploit available in https://github.com/square/okhttp/pull/6353
Backport of #11749

fix security issue with okhttp (1.68.x backport)

---

compiler/src/java_plugin/cpp/java_generator.cpp

Protobuf is interested in using absl::string_view instead of const std::string&. Just copy to std::string as the C++17 build isn't yet operational and that level of performance doesn't matter.
cl/711732759 b/353571051
CC @danielzhaotongliu

compiler: Prepare for C++ protobuf using string_view

---

xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java

The name is being changed to allow the value to be used in more metrics where xds-specifics are awkward.

xds: Rename grpc.xds.cluster to grpc.lb.backend_service

---

xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java

The name is being changed to allow the value to be used in more metrics where xds-specifics are awkward.
Backport of #11841

xds: Rename grpc.xds.cluster to grpc.lb.backend_service (v1.70.x backport)

---

xds/src/test/java/io/grpc/xds/XdsClientFallbackTest.java

d65d3942e increased the test speed of
connect_then_mainServerDown_fallbackServerUp by using FakeClock. However, it introduced a data race because FakeClock is not thread-safe. This change injects a single thread for gRPC callbacks such that syncContext is run on a thread under the test's control.
A simpler approach would be to expose syncContext from XdsClientImpl for testing. However, this test is in a different package and I wanted to avoid adding a public method.
```
Read of size 8 at 0x00008dec9d50 by thread T25:
#0 io.grpc.internal.FakeClock$ScheduledExecutorImpl.schedule(Lio/grpc/internal/FakeClock$ScheduledTask;JLjava/util/concurrent/TimeUnit;)V FakeClock.java:140
#1 io.grpc.internal.FakeClock$ScheduledExecutorImpl.schedule(Ljava/lang/Runnable;JLjava/util/concurrent/TimeUnit;)Ljava/ …
```

xds: Fix fallback test FakeClock TSAN failure

---

core/src/main/java/io/grpc/internal/PickFirstLeafLoadBalancer.java
core/src/test/java/io/grpc/internal/PickFirstLeafLoadBalancerTest.java

Also,
Move cleanup of removed subchannels into a method so it can be called from 2 places in acceptResolvedAddresses. 
Since the seek could mean we never looked at the first address, if we go off the end of the index and haven't looked at the all of the addresses then instead of scheduleBackoff() we reset the index and request a connection.

core:Have acceptResolvedAddresses() do a seek when in CONNECTING state and cleanup removed subchannels when a seek was successful

---

xds/src/main/java/io/grpc/xds/FaultFilter.java

This is the only usage of PickSubchannelArgs when creating a filter's ClientInterceptor, and a follow-up commit will remove the argument and actually reuse the interceptors. Other filter's interceptors can already be reused.
There doesn't seem to be any significant loss of legibility by making FaultFilter a more ordinary interceptor, but the change does cause the ForwardingClientCall to be present when faultDelay is configured, independent of whether the fault delay ends up being triggered.
Reusing interceptors will move more state management out of the RPC path which will be more relevant with RLQS.
CC @sergiitk 
-----
The diff is sorta hard to follow, so it may be easier to see the shape of the code before and compare to it after. I don't believe there to be any behavior changes other …

xds: Allow FaultFilter's interceptor to be reused across RPCs

---

netty/src/main/java/io/grpc/netty/NettyWritableBufferAllocator.java
netty/src/test/java/io/grpc/netty/NettyWritableBufferAllocatorTest.java

Fixes https://github.com/grpc/grpc-java/issues/11719
MessageFramer.flush() is being called between every message, so messages are never combined and the larger allocation just wastes memory. The change removes the restriction on the min buffer size and hence, prevents the said wastage.

netty: Removed 4096 min buffer size

---

core/src/main/java/io/grpc/internal/DelayedClientTransport.java
core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java

Setting the authority is only useful when creating a real stream, as there will be a following pick otherwise. In addition, DelayedStream will buffer each call to setAuthority() in a list and we don't want that memory usage. Note that no LBs are using this feature yet, so users would not have been exposed to the memory use.
We also needed to setAuthority() when the LB selected a subchannel on the first pick attempt.
------
I noticed this while reviewing #11851

core: Propagate authority override from LB exactly once

---

xds/src/main/java/io/grpc/xds/FaultFilter.java
xds/src/main/java/io/grpc/xds/Filter.java
xds/src/main/java/io/grpc/xds/GcpAuthenticationFilter.java
xds/src/main/java/io/grpc/xds/RouterFilter.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/GcpAuthenticationFilterTest.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java

This moves the interceptor creation from the ConfigSelector to the resource update handling.
The code structure changes will make adding support for filter lifecycles (for RLQS) a bit easier. The filter lifecycles will allow filters to share state across interceptors, and constructing all the interceptors on a single thread will mean filters wouldn't need to be thread-safe (but their interceptors would be thread-safe).
CC @larry-safran (It's a bit unclear who best to review; Sergii dug into this some which triggered me to make the PR. If you're interested, take a look.)

xds: Reuse filter interceptors across RPCs

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java

The field was made final in 4b52639aa but was soon reverted in 3ebb3e192 because of what I assume was a bad merge conflict resolution. The field has contained an immutable object since its introduction in d25f5acf1, so it is pretty likely to remain a constant in the future.

xds: Make XdsNR.RoutingConfig.empty a constant

---

alts/src/main/java/io/grpc/alts/AltsContextUtil.java
alts/src/test/java/io/grpc/alts/AltsContextUtilTest.java

This adds a createFrom(Attributes) to mirror the check(Attributes) added in ba8ab79. It also adds conveniences for ClientCall for both createFrom() and check(). This allows getting peer information from ClientCall and CallCredentials.RequestInfo, as was already available from ServerCall.
The tests were reworked to test the Attribute-based methods and then only basic tests for client/server.
Fixes #11042

alts: Add ClientCall support to AltsContextUtil

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java
interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java
netty/src/main/java/io/grpc/netty/NettyWritableBufferAllocator.java
netty/src/test/java/io/grpc/netty/NettyWritableBufferAllocatorTest.java
xds/src/main/java/io/grpc/xds/FaultFilter.java

Fixes: https://github.com/grpc/grpc-java/issues/11700
Updates the backoff range from [0, 1] to [0.8, 1.2] as per the A6 redefinition

core: updates the backoff range as per the A6 redefinition

---

protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java
protobuf/src/main/java/io/grpc/protobuf/ProtoUtils.java

protobuf: Stabilize marshallerWithRecursionLimit

---

xds/build.gradle
xds/src/main/java/io/grpc/xds/XdsConfig.java
xds/src/main/java/io/grpc/xds/XdsDependencyManager.java
xds/src/main/java/io/grpc/xds/XdsRouteConfigureResource.java
xds/src/main/java/io/grpc/xds/client/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/ControlPlaneRule.java
xds/src/test/java/io/grpc/xds/XdsClientFallbackTest.java
xds/src/test/java/io/grpc/xds/XdsDependencyManagerTest.java
xds/src/test/java/io/grpc/xds/XdsTestControlPlaneService.java
xds/src/test/java/io/grpc/xds/XdsTestUtils.java
xds/src/test/java/io/grpc/xds/client/CommonBootstrapperTestUtils.java

This is just defining the XdsDependencyManager and associated classes; no movement of any functionality.

Add new classes for eliminating xds config tears

---

xds/src/main/java/io/grpc/xds/XdsConfig.java
xds/src/main/java/io/grpc/xds/XdsDependencyManager.java
xds/src/main/java/io/grpc/xds/XdsRouteConfigureResource.java
xds/src/test/java/io/grpc/xds/XdsDependencyManagerTest.java
xds/src/test/java/io/grpc/xds/XdsTestUtils.java

children is a single object which is either a list of leaf names (AggregateConfig) or an EdsUpdate (EndpointConfig).  All intermediate aggregate nodes have been squashed.
Rebasing onto master pulled some of the commits from master into this PR.

xds: Change XdsClusterConfig to have children field instead of endpoint

---

xds/src/main/java/io/grpc/xds/XdsDependencyManager.java
xds/src/test/java/io/grpc/xds/XdsDependencyManagerTest.java

There is a possibility that when clusters are removed from a configuration, they can have their XdsClient subscriptions notified about being absent (since CDS is state of the world) which generates a callback to doesNotExist.  If this happens before the CdsWatcher object is cancelled, then a new XdsConfig is sent which has those clusters marked as being in error (Status rather than value).  The tests need to just ignore those updates.

xds:Cleanup to reduce test flakiness

---

buildscripts/kokoro/android-interop.sh

To try to aid failure when building android-interop-testing
```
The Daemon will expire after the build after running out of JVM heap space.
The project memory settings are likely not configured or are configured to an insufficient value.
The daemon will restart for the next build, which may increase subsequent build times.
These settings can be adjusted by setting 'org.gradle.jvmargs' in 'gradle.properties'.
The currently configured max heap space is '512 MiB' and the configured max metaspace is '384 MiB'.
...
Exception in thread "Daemon client event forwarder" java.lang.OutOfMemoryError: Java heap space
...
> Task :grpc-android-interop-testing:mergeDexDebug FAILED
ERROR:D8: java.lang.OutOfMemoryError: Java heap space
com.android.builder.dexing.DexArchiveMergerException: Error while …
```

kokoro: Increase gradle mem in android-interop

---

servlet/jakarta/build.gradle

The version number is simply a unique string per version.
CC @kannanjgithub 
----
FWIW, it is very rare to need to do something like this.

servlet: Provide Gradle a filter version number

---

s2a/src/main/java/io/grpc/s2a/S2AChannelCredentials.java
s2a/src/main/java/io/grpc/s2a/internal/handshaker/S2AStub.java
s2a/src/test/java/io/grpc/s2a/IntegrationTest.java

S2AStub is an internal API and shouldn't be used outside of s2a. It is still available for tests.
@rmehta19, could you review?

s2a: Don't allow S2AStub to be set

---

examples/src/main/java/io/grpc/examples/helloworld/HelloWorldServer.java

Examples: Updated HelloWorldServer to use Executor

---

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java

A failing Status from acceptResolvedAddresses means something is wrong with the config, but parts of the config may still have been applied. Thus there are now two possible flows: errors that should prevent updateOverallBalancingState() and errors that should have no effect other than the return code. To manage that, MultChildLb must always be responsible for calling updateOverallBalancingState(). acceptResolvedAddressesInternal() was inlined to make that error processing easier. No existing usages actually needed to have logic between updating the children and regenerating the picker.
RingHashLb already was verifying that the address list was not empty, so the short-circuiting when acceptResolvedAddressesInternal() returned an error was impossible to trigger. WrrLb's updateWeightTask() …

util: Use acceptResolvedAddresses() for MultiChildLb children

---

xds/src/main/java/io/grpc/xds/FaultFilter.java
xds/src/main/java/io/grpc/xds/Filter.java
xds/src/main/java/io/grpc/xds/FilterRegistry.java
xds/src/main/java/io/grpc/xds/GcpAuthenticationFilter.java
xds/src/main/java/io/grpc/xds/InternalRbacFilter.java
xds/src/main/java/io/grpc/xds/RbacFilter.java
xds/src/main/java/io/grpc/xds/RouterFilter.java
xds/src/main/java/io/grpc/xds/XdsListenerResource.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/main/java/io/grpc/xds/XdsRouteConfigureResource.java
xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
xds/src/test/java/io/grpc/xds/FaultFilterTest.java
xds/src/test/java/io/grpc/xds/GcpAuthenticationFilterTest.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java
xds/src/test/java/io/grpc/xds/RbacFilterTest.java
xds/src/test/java/io/grpc/xds/RouterFilterTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java

This is the first step towards supporting filter state retention in Java. The mechanism will be similar to the one described in [A83](https://github.com/grpc/proposal/blob/master/A83-xds-gcp-authn-filter.md#filter-call-credentials-cache) for C-core, and will serve the same purpose. However, the implementation details are very different due to the different nature of xDS HTTP filter support in C-core and Java.
In Java, xDS HTTP filters are backed by classes implementing `io.grpc.xds.Filter`, from here just called "Filters". 
To support Filter state retention (next PR), Java's xDS implementation must be able to create unique Filter instances per:
- Per HCM `envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager`
- Per filter name as specified in …

xds: Change how xDS filters are created by introducing Filter.Provider

---

xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java

PriorityLb should propagate config problems up to the name resolver so it can refresh.
CC @SreeramdasLavanya

xds: Use acceptResolvedAddresses() for PriorityLb children

---

interop-testing/src/main/java/io/grpc/testing/integration/RpcBehaviorLoadBalancerProvider.java
interop-testing/src/test/java/io/grpc/testing/integration/RpcBehaviorLoadBalancerProviderTest.java
services/src/main/java/io/grpc/protobuf/services/HealthCheckingLoadBalancerFactory.java
services/src/test/java/io/grpc/protobuf/services/HealthCheckingLoadBalancerFactoryTest.java
util/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
util/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java
xds/src/main/java/io/grpc/xds/WrrLocalityLoadBalancer.java
xds/src/main/java/io/grpc/xds/orca/OrcaOobUtil.java
xds/src/test/java/io/grpc/xds/ClusterManagerLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/MetadataLoadBalancerProvider.java
xds/src/test/java/io/grpc/xds/WrrLocalityLoadBalancerTest.java

We want to move away from handleResolvedAddresses(). These are "easy" in that they need no logic. LBs extending ForwardingLoadBalancer had the method duplicated from handleResolvedAddresses() and swapped away from `super` because ForwardingLoadBalancer only forwards handleResolvedAddresses() reliably today. Duplicating small methods was less bug-prone than dealing with ForwardingLoadBalancer.
CC @SreeramdasLavanya

Use acceptResolvedAddresses() in easy cases

---

xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java
xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java

`XdsServerWrapper#generatePerRouteInterceptors` was always intended to be executed within a sync context. This PR ensures that by calling `syncContext.throwIfNotInThisSynchronizationContext()`.
This change is needed for upcoming xDS filter state retention because the new tests in XdsServerWrapperTest flake with this NPE:
> `Cannot invoke "io.grpc.xds.client.XdsClient$ResourceWatcher.onChanged(io.grpc.xds.client.XdsClient$ResourceUpdate)" because "this.ldsWatcher" is null`

xds: ensure server interceptors are created in a sync context

---

xds/src/main/java/io/grpc/xds/EnvoyServerProtoData.java
xds/src/main/java/io/grpc/xds/XdsListenerResource.java
xds/src/test/java/io/grpc/xds/FilterChainMatchingProtocolNegotiatorsTest.java

xds: avoid unnecessary dns lookup

---

xds/src/main/java/io/grpc/xds/EnvoyServerProtoData.java
xds/src/main/java/io/grpc/xds/Filter.java
xds/src/main/java/io/grpc/xds/FilterChainMatchingProtocolNegotiators.java
xds/src/main/java/io/grpc/xds/XdsListenerResource.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java
xds/src/test/java/io/grpc/xds/StatefulFilter.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java
xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java

This PR adds support filter state retention in Java. The mechanism will be similar to the one described in [A83](https://github.com/grpc/proposal/blob/master/A83-xds-gcp-authn-filter.md#filter-call-credentials-cache) for C-core, and will serve the same purpose. However, the implementation details are very different due to the different nature of xDS HTTP filter support in C-core and Java.
New filter instances are created per combination of:
1. `XdsNameResolver` instance,
2. Filter name+typeUrl as configured in HttpConnectionManager (HCM) http_filters.
Existing client-side filter instances are shutdown:
- A single a filter instance is shutdown when an LDS update contains HCM that is missing filter configuration for name+typeUrl  combination of this instance.
- All filter instances when …

xds: Support filter state retention

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java

ffcc360ba adjusted updateBalancingState() to require being run within the sync context. However, it still queued the work into the sync context, which was unnecessary. This re-entering the sync context unnecessarily delays the new state from being used.
----
I found this with a new xds test I've prepared, after fixing some problems in xds name resolver. See https://github.com/grpc/grpc-java/compare/master...ejona86:grpc-java:xds-cluster-race (which I'll send out once this is merged). After fixing XdsNameResolver, the test went from failing 2% to ~0.2% of the time. That led me to discover this delayed processing. With both changes, there were no flakes in 1000 runs.
CC @kannanjgithub, @danielzhaotongliu

core: Apply ManagedChannelImpl's updateBalancingState() immediately

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/FakeControlPlaneXdsIntegrationTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

Listener2.onResult() doesn't require running in the sync context, so when called from the sync context it is guaranteed not to do its processing immediately (instead, it schedules work into the sync context).
The code was doing an update dance: 1) update service config to add new cluster, 2) update config selector to use new cluster, 3) update service config to remove old clusters. But the onResult() wasn't being processed immediately, so the actual execution order was 2, 1, 3 which has a small window where RPCs will fail. But onResult2() does run immediately. And since ca4819ac6, updateBalancingState() updates the picker immediately.
cleanUpRoutes() was also racy because it updated the routingConfig before swapping to the new config selector, so RPCs could fail saying there was no route …

xds: Fix cluster selection races when updating config selector

---

xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java

It is confusing/harder to read the logs when the
activations/deactivations because of the config happen before the log entry describing the new config.

xds: Log cluster_manager config update before applying config

---

netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java

Fixes #11659 
FYI: https://github.com/netty/netty/issues/14918

netty: Swap to UniformStreamByteDistributor

---

servlet/src/main/java/io/grpc/servlet/ServletServerStream.java

It eventually happens from Tomcat when it's behind nginx.
Currently caller gets just `io.grpc.StatusRuntimeException: CANCELLED` which is not very clear.
I guess when this code was originally developed, the assumption was that nobody will received it, but it actually happens, so worth making this status more clear.
if you are curious, the exception which causes that is
```
java.io.IOException: null
at org.apache.coyote.http2.Stream$StandardStreamInputBuffer.receiveReset(Stream.java:1516)
at org.apache.coyote.http2.Stream.receiveReset(Stream.java:227)
at org.apache.coyote.http2.Http2UpgradeHandler.close(Http2UpgradeHandler.java:1302)
at org.apache.coyote.http2.Http2UpgradeHandler.upgradeDispatch(Http2UpgradeHandler.java:434)
at org.apache.coyote.http2.Http2AsyncUpgradeHandler.upgradeDispatc …
```

servlet: set description for CANCELLED status

---

api/src/testFixtures/java/io/grpc/StatusMatcher.java
api/src/testFixtures/java/io/grpc/StatusOrMatcher.java
xds/src/main/java/io/grpc/xds/XdsAttributes.java
xds/src/main/java/io/grpc/xds/XdsConfig.java
xds/src/main/java/io/grpc/xds/XdsDependencyManager.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/main/java/io/grpc/xds/XdsNameResolverProvider.java
xds/src/test/java/io/grpc/xds/XdsDependencyManagerTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
xds/src/test/java/io/grpc/xds/XdsTestUtils.java

I'm going to leave this in draft form until after I squash and rebase on master (once the review has gotten to that point).
~"Gracefully handle tcp listeners. Fix error processing in XdsNR" is partly speculative right now, as we have a discussion of how error handling should be done. The tcp listeners is needed, but it got mixed together with onError() behavior. I can split it up needed.~ The gRFC changed to match the behavior here. https://github.com/grpc/proposal/commit/fea37889f085c4f55e61e29678356e9a57dc4bf0

xds: Use XdsDependencyManager for XdsNameResolver

---

binder/src/main/java/io/grpc/binder/internal/PingTracker.java
binder/src/test/java/io/grpc/binder/internal/PingTrackerTest.java
core/src/main/java/io/grpc/internal/ClientTransport.java
core/src/main/java/io/grpc/internal/FailingClientTransport.java
core/src/main/java/io/grpc/internal/Http2Ping.java
core/src/main/java/io/grpc/internal/KeepAliveManager.java
core/src/test/java/io/grpc/internal/KeepAliveManagerTest.java
core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java
inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java
netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

Fixes: https://github.com/grpc/grpc-java/issues/10524

Stops exception allocation on channel shutdown

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

This allows Filters to access the xds configuration for their own processing. From gRFC A83:
> This data is available via the XdsConfig attribute introduced in A74.
> If the xDS ConfigSelector is not already passing that attribute to the
> filters, it will need to be changed to do so.
CC @shivaspeaks, this should be the last part to fully unblock gcp authn filter

xds: Include XdsConfig as a CallOption

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java

It is much harder to debug refcounting problems when we ignore impossible situations. So make such impossible cases complain loudly so the bug is obvious.

xds: Assert XdsNR's cluster ref counting is consistent

---

xds/src/main/java/io/grpc/xds/FaultFilter.java
xds/src/main/java/io/grpc/xds/Filter.java
xds/src/main/java/io/grpc/xds/GcpAuthenticationFilter.java
xds/src/main/java/io/grpc/xds/InternalRbacFilter.java
xds/src/main/java/io/grpc/xds/RbacFilter.java
xds/src/main/java/io/grpc/xds/RouterFilter.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java
xds/src/test/java/io/grpc/xds/RbacFilterTest.java
xds/src/test/java/io/grpc/xds/StatefulFilter.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java

This is to support gRFC A83 xDS GCP Authentication Filter:
> Otherwise, the filter will look in the CDS resource's metadata for a
> key corresponding to the filter's instance name.
CC @sergiitk, @kannanjgithub, @larry-safran

xds: Expose filter names to filter instances

---

api/build.gradle
api/src/test/java/io/grpc/MetadataTest.java
api/src/test/java/io/grpc/MethodDescriptorTest.java
api/src/test/java/io/grpc/ServerInterceptorsTest.java
api/src/test/java/io/grpc/ServerServiceDefinitionTest.java
api/src/test/java/io/grpc/ServiceDescriptorTest.java
core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
core/src/test/java/io/grpc/internal/AbstractServerStreamTest.java
core/src/test/java/io/grpc/internal/ConnectivityStateManagerTest.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/GrpcUtilTest.java
core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
core/src/test/java/io/grpc/internal/JsonParserTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplBuilderTest.java
core/src/test/java/io/grpc/internal/ManagedChannelServiceConfigTest.java
core/src/test/java/io/grpc/internal/MessageDeframerTest.java
core/src/test/java/io/grpc/internal/MessageFramerTest.java
core/src/test/java/io/grpc/internal/ServerCallImplTest.java
core/src/test/java/io/grpc/internal/ServerImplTest.java
core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java

replace ExpectedException in grpc-api and grpc-core

---

opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryTracingModule.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryTracingModuleTest.java

with gRFC update: https://github.com/grpc/proposal/pull/474

otel tracing: fix span names

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java

panic() calls a good amount of code, so it could get another exception. The SynchronizationContext is running on an arbitrary thread and we don't want to propagate this secondary exception up its stack (to be handled by its UncaughtExceptionHandler); it we wanted that we'd propagate the original exception.
This second exception will only be seen in the logs; the first exception was logged and will be used to fail RPCs.
Also related to http://yaqs/8493785598685872128 and b692b9d26

core: Log any exception during panic because of exception

---

services/src/main/java/io/grpc/protobuf/services/HealthServiceImpl.java
services/src/test/java/io/grpc/protobuf/services/HealthStatusManagerTest.java

fix #11853 
Use ServerCallStreamObserver.setOnCancelHandler() to disable this exception

services: fix HealthService notifyWatchers

---

xds/src/test/java/io/grpc/xds/XdsSecurityClientServerTest.java

Fixes: https://github.com/grpc/grpc-java/issues/11692

Cleans up FileWatcherCertificateProvider in XdsSecurityClientSecurityTest

---

core/src/main/java/io/grpc/internal/InstantTimeProvider.java
core/src/main/java/io/grpc/internal/TimeProviderResolverFactory.java
core/src/test/java/io/grpc/internal/InstantTimeProviderTest.java

Seems like there is not need to use reflection in InstantTimeProvider.
if Instant class is present, then we can use normally.

no reflection in InstantTimeProvider, fixes #11975

---

util/src/main/java/io/grpc/util/GracefulSwitchLoadBalancer.java
util/src/test/java/io/grpc/util/GracefulSwitchLoadBalancerTest.java

Previously it would wait for the new LB to enter READY. However, that prevents there being an upper-bound on how long the old policy will continue to be used. The point of graceful switch is to avoid RPCs seeing increased latency when we swap config. We don't want it to prevent the system from becoming eventually consistent.

util: Graceful switch to new LB when leaving CONNECTING

---

core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java

ATTR_LOAD_BALANCING_CONFIG was deleted in bf7a42dbd.
-----
FWIW, I don't know why checkstyle isn't complaining about the public class not having javadoc. It really shouldn't be public, but it is being used in XdsNameResolverTest to validate a service config.

core: Delete stale SuppressWarnings("deprecated") for ATTR_LOAD_BALANCING_CONFIG

---

core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java
core/src/test/java/io/grpc/internal/ProxyDetectorImplTest.java

"EXP" stood for experimental and all documentation that referenced it made it was clear it was experimental. It's been some years since we started logging a message when it was used to say it will be deleted. There's no time like the present to delete it.

core: Delete the long-deprecated GRPC_PROXY_EXP

---

stub/src/test/java/io/grpc/stub/StreamObserversTest.java

Some JUnit environments require the RunWith annotation. Notably Blaze/Bazel needs it.

stub: Add RunWith(JUnit4) to support varied environments

---

core/src/main/java/io/grpc/internal/DelayedClientTransport.java

core: Avoid Set.removeAll() when passing a possibly-large List (1.70.x backport)

---

core/src/main/java/io/grpc/internal/DelayedClientTransport.java

core: Avoid Set.removeAll() when passing a possibly-large List (1.71.x backport)

---

core/src/main/java/io/grpc/internal/DelayedClientTransport.java

core: Avoid Set.removeAll() when passing a possibly-large List (1.72.x backport)

---

xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java

Backport of #11997 to v1.72.x.
---
Fixes #11995

xds: ClusterResolverLoadBalancer handle update for both resolved addresses and errors via ResolutionResult (v1.72.x backport)

---

xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java

Backport of #11997 to v1.71.x.
--- 
Fixes #11995.

xds: ClusterResolverLoadBalancer handle update for both resolved addresses and errors via ResolutionResult (v1.71.x backport)

---

xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java

Backport of #11997 to v1.70.x. 
--- 
Fixes #11995.

xds: ClusterResolverLoadBalancer handle update for both resolved addresses and errors via ResolutionResult (v1.70.x backport)

---

stub/src/main/java/io/grpc/stub/ServerCalls.java
stub/src/test/java/io/grpc/stub/ServerCallsTest.java

https://github.com/grpc/grpc-java/issues/11973
this maybe have a little performance implications.

stub: fix onError metadata race condition

---

core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java

A post-merge review of 8516cfef9 suggested this change and the comment had been lost in my inbox.

core: Loop over interceptors when computing effective interceptors

---

stub/src/main/java/io/grpc/stub/ServerCalls.java
stub/src/test/java/io/grpc/stub/ServerCallsTest.java

https://github.com/grpc/grpc-java/issues/11973
this maybe have a little performance implications.
Backport of #11979
CC @JoeCqupt

stub: fix onError metadata race condition (1.72.x backport)

---

api/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
xds/src/main/java/io/grpc/xds/LazyLoadBalancer.java

It has been deprecated since cec9ee368, six years ago. It was replaced with LoadBalancer.requestConnection().

api: Remove deprecated SubchannelPicker.requestConnection()

---

xds/build.gradle
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/main/java/io/grpc/xds/RbacFilter.java
xds/src/main/java/io/grpc/xds/XdsClusterResource.java
xds/src/main/java/io/grpc/xds/XdsRouteConfigureResource.java
xds/src/main/java/io/grpc/xds/internal/MatcherParser.java
xds/src/main/java/io/grpc/xds/internal/security/CommonTlsContextUtil.java
xds/src/main/java/io/grpc/xds/internal/security/certprovider/CertProviderSslContextProvider.java
xds/src/main/java/io/grpc/xds/internal/security/trust/XdsX509TrustManager.java
xds/src/test/java/io/grpc/xds/FilterChainMatchingProtocolNegotiatorsTest.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplV3Test.java
xds/src/test/java/io/grpc/xds/internal/security/ClientSslContextProviderFactoryTest.java
xds/src/test/java/io/grpc/xds/internal/security/CommonTlsContextTestsUtil.java
xds/src/test/java/io/grpc/xds/internal/security/certprovider/CertificateProviderStoreTest.java

The security code referenced fields removed from gRFC A29 before it was finalized.

xds: Enable deprecation warnings

---

xds/src/main/java/io/grpc/xds/XdsClientMetricReporterImpl.java
xds/src/main/java/io/grpc/xds/client/XdsClient.java
xds/src/main/java/io/grpc/xds/client/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/XdsClientMetricReporterImplTest.java

This aims to complete the [XDS client metrics](https://github.com/grpc/proposal/blob/master/A78-grpc-metrics-wrr-pf-xds.md#xdsclient) by adding the remaining grpc.xds.authority metric.

feat: add the missing xds.authority label

---

buildscripts/kokoro/psm-dualstack.cfg

Backport of #11950 to v1.70.x.
---
120 minutes has not been sufficient, causing frequent VM timeout errors in the test runs.

Update psm-dualstack.cfg (v1.70.x backport)

---

buildscripts/kokoro/psm-dualstack.cfg

Backport of #11950 to v1.68.x.
---
120 minutes has not been sufficient, causing frequent VM timeout errors in the test runs.

Update psm-dualstack.cfg (v1.68.x backport)

---

api/src/main/java/io/grpc/StatusOr.java

Add some documentation to StatusOr.equals regarding how underlying statuses are compared, to avoid any confusion, as suggested in issue #11949.

Add some documentation to StatusOr.equals 

---

xds/src/main/java/io/grpc/xds/XdsDependencyManager.java
xds/src/test/java/io/grpc/xds/XdsDependencyManagerTest.java

This prevents a NPE and subsequent channel panic when trying to build a config (because there are no watchers, so waitingOnResource==false) without any listener and route.
```
java.lang.NullPointerException: Cannot invoke "io.grpc.xds.XdsDependencyManager$RdsUpdateSupplier.getRdsUpdate()" because "routeSource" is null
at io.grpc.xds.XdsDependencyManager.buildUpdate(XdsDependencyManager.java:295)
at io.grpc.xds.XdsDependencyManager.maybePublishConfig(XdsDependencyManager.java:266)
at io.grpc.xds.XdsDependencyManager$EdsWatcher.onChanged(XdsDependencyManager.java:899)
at io.grpc.xds.XdsDependencyManager$EdsWatcher.onChanged(XdsDependencyManager.java:888)
at io.grpc.xds.client.XdsClientImpl$ResourceSubscriber.notifyWatcher(XdsClientImpl.java:929)
at …
```

xds: XdsDepManager should ignore updates after shutdown

---

xds/src/main/java/io/grpc/xds/XdsDependencyManager.java
xds/src/test/java/io/grpc/xds/XdsDependencyManagerTest.java

This prevents a NPE and subsequent channel panic when trying to build a config (because there are no watchers, so waitingOnResource==false) without any listener and route.
```
java.lang.NullPointerException: Cannot invoke "io.grpc.xds.XdsDependencyManager$RdsUpdateSupplier.getRdsUpdate()" because "routeSource" is null
at io.grpc.xds.XdsDependencyManager.buildUpdate(XdsDependencyManager.java:295)
at io.grpc.xds.XdsDependencyManager.maybePublishConfig(XdsDependencyManager.java:266)
at io.grpc.xds.XdsDependencyManager$EdsWatcher.onChanged(XdsDependencyManager.java:899)
at io.grpc.xds.XdsDependencyManager$EdsWatcher.onChanged(XdsDependencyManager.java:888)
at io.grpc.xds.client.XdsClientImpl$ResourceSubscriber.notifyWatcher(XdsClientImpl.java:929)
at …
```

xds: XdsDepManager should ignore updates after shutdown (1.72.x backport)

---

gae-interop-testing/gae-jdk8/src/main/webapp/WEB-INF/appengine-web.xml

Backport of #11699 to v1.67.x.
---
Java 11 is out-of-support on GAE. Unfortunately the docs use the term "deprecated" as "deleted," not "discouraged." So they talk about it being deprecated _after_ it is no longer supported.
https://cloud.google.com/appengine/docs/standard/lifecycle/support-schedule#java https://cloud.google.com/appengine/docs/flexible/lifecycle/support-schedule#java

gae-interop-testing: Upgrade to Java 17 (v1.67.x backport)

---

buildscripts/kokoro/psm-dualstack.cfg

Backport of #11950 to v1.67.x.
---
120 minutes has not been sufficient, causing frequent VM timeout errors in the test runs.

Update psm-dualstack.cfg (v1.67.x backport)

---

.github/workflows/gradle-wrapper-validation.yml
.github/workflows/lock.yml
.github/workflows/testing.yml
gae-interop-testing/gae-jdk8/src/main/webapp/WEB-INF/appengine-web.xml

Backport of #11476 and #11669 to v1.66.x.
---
GitHub began the Node16 deprecation process a year ago [^1][^2]. This PR updates all workflows to use the latest Node20 actions. I have tested the workflows in my fork repository.
The last update was made almost two years ago in PR https://github.com/grpc/grpc-java/pull/9648.
Java 11 is out-of-support on GAE, hence bumping to Java 17. 
[^1]: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
[^2]: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

.github/workflows: Bump action major versions (v1.66.x backport)

---

README.md
build.gradle
compiler/build.gradle
examples/android/clientcache/build.gradle
examples/android/helloworld/build.gradle
examples/android/routeguide/build.gradle
examples/android/strictmode/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-debug/build.gradle
examples/example-dualstack/build.gradle
examples/example-gauth/build.gradle
examples/example-gcp-csm-observability/build.gradle
examples/example-gcp-observability/build.gradle
examples/example-hostname/build.gradle
examples/example-jwt-auth/build.gradle
examples/example-oauth/build.gradle
examples/example-opentelemetry/build.gradle
examples/example-orca/build.gradle
examples/example-reflection/build.gradle
examples/example-servlet/build.gradle
examples/example-tls/build.gradle
examples/example-xds/build.gradle
protobuf-lite/build.gradle
settings.gradle

The plugin now outputs to "generated/sources". The IDE configuration explicitly adding the folders to the source sets hasn't been needed for some years.

Bump com.google.protobuf gradle plugin to 0.9.5

---

xds/src/main/java/io/grpc/xds/WeightedTargetLoadBalancer.java
xds/src/test/java/io/grpc/xds/WeightedTargetLoadBalancerTest.java

Convert the tests to use acceptResolvedAddresses() as well.
----
CC @SreeramdasLavanya, @shivaspeaks 
I think after this #11623 can be completed.

xds: Use acceptResolvedAddresses() for WeightedTarget children

---

buildscripts/kokoro/psm-dualstack.cfg

Backport of #11950 to v1.66.x.
---
120 minutes has not been sufficient, causing frequent VM timeout errors in the test runs.

Update psm-dualstack.cfg (v1.66.x backport)

---

xds/src/main/java/io/grpc/xds/XdsClusterResource.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java

Backport of #12054 to v1.73.x.
---
It has seen good testing by users and behaved as expected.
Fixes #11996
-----
CC @atollena, @yannickepstein

xds: Enable least request by default (v1.73.x backport)

---

xds/src/main/java/io/grpc/xds/FilterRegistry.java
xds/src/main/java/io/grpc/xds/GcpAuthenticationFilter.java
xds/src/test/java/io/grpc/xds/GcpAuthenticationFilterTest.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java

Missing and final piece of [gRFC A83-xds-gcp-authn-filter.md](https://github.com/grpc/proposal/blob/master/A83-xds-gcp-authn-filter.md#temporary-environment-variable-protection)

xds: temporary flag protection of GcpAuthenticationFilter

---

buildscripts/kokoro/psm-light.cfg

Rename PSM interop fallback test suite to light (1.73.x)

---

buildscripts/kokoro/psm-light.cfg

Backport https://github.com/grpc/grpc-java/pull/12091 to v1.71.x

Rename PSM interop fallback test suite to light (1.70.x)

---

buildscripts/kokoro/psm-light.cfg

Backport https://github.com/grpc/grpc-java/pull/12091 to v1.71.x

Rename PSM interop fallback test suite to light (1.71.x)

---

buildscripts/kokoro/psm-light.cfg

Backport https://github.com/grpc/grpc-java/pull/12091 to v1.72.x

Rename PSM interop fallback test suite to light (1.72.x)

---

buildscripts/kokoro/psm-light.cfg

This is part of a cross-repository change to generalize the fallback test suite to support other tests, and to change the name for clarity. See also https://github.com/grpc/psm-interop/pull/179.

Rename PSM interop fallback test suite to light

---

xds/src/main/java/io/grpc/xds/GcpAuthenticationFilter.java
xds/src/test/java/io/grpc/xds/GcpAuthenticationFilterTest.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java
xds/src/test/java/io/grpc/xds/XdsTestUtils.java

Backport of #11972 to v1.72.x.
---
null

xds: propagate audience from cluster resource in gcp auth filter (v1.72.x backport)

---

xds/src/main/java/io/grpc/xds/FilterRegistry.java
xds/src/main/java/io/grpc/xds/GcpAuthenticationFilter.java
xds/src/test/java/io/grpc/xds/GcpAuthenticationFilterTest.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java

Backport of #12075 to v1.73.x.
---
Missing and final piece of [gRFC A83-xds-gcp-authn-filter.md](https://github.com/grpc/proposal/blob/master/A83-xds-gcp-authn-filter.md#temporary-environment-variable-protection)

xds: temporary flag protection of GcpAuthenticationFilter (v1.73.x backport)

---

xds/src/main/java/io/grpc/xds/FilterRegistry.java
xds/src/main/java/io/grpc/xds/GcpAuthenticationFilter.java
xds/src/test/java/io/grpc/xds/GcpAuthenticationFilterTest.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java

Backport of #12075 to v1.72.x.
---
Missing and final piece of [gRFC A83-xds-gcp-authn-filter.md](https://github.com/grpc/proposal/blob/master/A83-xds-gcp-authn-filter.md#temporary-environment-variable-protection)

xds: temporary flag protection of GcpAuthenticationFilter (v1.72.x backport)

---

xds/src/main/java/io/grpc/xds/FaultFilter.java
xds/src/main/java/io/grpc/xds/Filter.java
xds/src/main/java/io/grpc/xds/FilterRegistry.java
xds/src/main/java/io/grpc/xds/GcpAuthenticationFilter.java
xds/src/main/java/io/grpc/xds/InternalRbacFilter.java
xds/src/main/java/io/grpc/xds/RbacFilter.java
xds/src/main/java/io/grpc/xds/RouterFilter.java
xds/src/main/java/io/grpc/xds/XdsListenerResource.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/main/java/io/grpc/xds/XdsRouteConfigureResource.java
xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
xds/src/test/java/io/grpc/xds/FaultFilterTest.java
xds/src/test/java/io/grpc/xds/GcpAuthenticationFilterTest.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java
xds/src/test/java/io/grpc/xds/RbacFilterTest.java
xds/src/test/java/io/grpc/xds/RouterFilterTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java

Backport of #11883 to v1.71.x.
---
This is the first step towards supporting filter state retention in Java. The mechanism will be similar to the one described in [A83](https://github.com/grpc/proposal/blob/master/A83-xds-gcp-authn-filter.md#filter-call-credentials-cache) for C-core, and will serve the same purpose. However, the implementation details are very different due to the different nature of xDS HTTP filter support in C-core and Java.
In Java, xDS HTTP filters are backed by classes implementing `io.grpc.xds.Filter`, from here just called "Filters". 
To support Filter state retention (next PR), Java's xDS implementation must be able to create unique Filter instances per:
- Per HCM `envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager`
- Per filter name …

xds: Change how xDS filters are created by introducing Filter.Provider (v1.71.x backport)

---

xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java
xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java

Backport of #11930 to v1.71.x.
---
`XdsServerWrapper#generatePerRouteInterceptors` was always intended to be executed within a sync context. This PR ensures that by calling `syncContext.throwIfNotInThisSynchronizationContext()`.
This change is needed for upcoming xDS filter state retention (PR #11936) because the new tests in XdsServerWrapperTest flake with this NPE:
> `Cannot invoke "io.grpc.xds.client.XdsClient$ResourceWatcher.onChanged(io.grpc.xds.client.XdsClient$ResourceUpdate)" because "this.ldsWatcher" is null`

xds: ensure server interceptors are created in a sync context (v1.71.x backport)

---

netty/src/test/java/io/grpc/netty/NettyChannelBuilderTest.java
netty/src/test/java/io/grpc/netty/NettyServerBuilderTest.java
netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpChannelBuilderTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpProtocolNegotiatorTest.java
okhttp/src/test/java/io/grpc/okhttp/UtilsTest.java
protobuf-lite/src/test/java/io/grpc/protobuf/lite/ProtoLiteUtilsTest.java
testing/src/test/java/io/grpc/testing/GrpcCleanupRuleTest.java
util/src/test/java/io/grpc/util/GracefulSwitchLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/GrpcBootstrapperImplTest.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java
xds/src/test/java/io/grpc/xds/PriorityLoadBalancerProviderTest.java
xds/src/test/java/io/grpc/xds/SharedXdsClientPoolProviderTest.java
xds/src/test/java/io/grpc/xds/WeightedRandomPickerTest.java

Replace ExpectedException

---

xds/src/main/java/io/grpc/xds/XdsDependencyManager.java

This provides better type and missing-map handling. Note that getWatchers() now implicitly creates the map if it doesn't exist, instead of just returning an empty map. That makes it a bit easier to use and more importantly avoids accidents where a bug tries to modify the immutable map.

xds: Use getWatchers more often in XdsDepManager

---

xds/src/main/java/io/grpc/xds/XdsDependencyManager.java

The optimization makes the code more complicated. Yes, we know that maybePublishConfig() will do no work because of an outstanding watch, but we don't do this for other new watchers created and doing so would just make the code more bug-prone. This removes a difference in how different watcher types are handled.

xds: Remove EDS maybePublishConfig() avoidance in XdsDepManager

---

xds/src/main/java/io/grpc/xds/XdsConfig.java
xds/src/main/java/io/grpc/xds/XdsDependencyManager.java
xds/src/test/java/io/grpc/xds/XdsDependencyManagerTest.java

The children of aggregate clusters have a priority order, so we can't ever throw them in an ordinary set for later iteration.
This now detects recusion limits only after subscribing, but that matches our existing behavior in CdsLoadBalancer2. We don't get much value detecting the limit before subscribing and doing so makes watcher types more different.
Loops are still a bit broken as they won't be unwatched when orphaned, as they will form a reference loop. In CdsLoadBalancer2, duplicate clusters had duplicate watchers so there was single-ownership and reference cycles couldn't form. Fixing that is a bigger change.
Intermediate aggregate clusters are now included in XdsConfig, just for simplicity. It doesn't hurt anything whether they are present or missing. but it required updates to …

xds: Fix XdsDepManager aggregate cluster child ordering and loop detection

---

binder/src/main/java/io/grpc/binder/internal/BinderTransport.java
binder/src/main/java/io/grpc/binder/internal/LeakSafeOneWayBinder.java

- Use @BinderThread to document thread access rules for methods and fields.
- Make TransactionHandler impl non-public since only Android should call it.
- Replace an unnecessary AtomicLong with a plain old long.
- Restructure sendAcknowledgeBytes() so the ack tracking fields are checked and updated in the same place (caller) 
Fixes #12047

binder: Rationalize @ThreadSafe-ty of BinderTransport.

---

xds/src/main/java/io/grpc/xds/XdsDependencyManager.java
xds/src/test/java/io/grpc/xds/XdsDependencyManagerTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

Reference counting doesn't release cycles, so swap to a tracing garbage collector. This greatly simplifies the code as well, as diffing is no longer necessary. (If vanilla reference counting was used, diffing wouldn't have been necessary either as you just increment all the new objects and decrement the old ones. But that doesn't work when use a set instead of an integer.)

xds: Use tracing GC in XdsDepManager

---

xds/src/main/java/io/grpc/xds/XdsDependencyManager.java

1fd29bc80 replaced cancelWatcher() with watcher.close(). But setting cancelled was missing. Because the config update checks for shutdown, the cancelled flag no longer avoids exceptions. But it seems best to continue avoiding any processing after close to avoid surprises.

xds: cancelled=true on watch close in XdsDepManager

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/RetryingNameResolver.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/RetryingNameResolverTest.java

It was introduced in fcb5c54e4 because at the time we didn't change the API to communicate the status. When onResult2() was introduced in 90d0fabb1 this hack stopped being necessary.

core: Remove RetryingNR.RESOLUTION_RESULT_LISTENER_KEY

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java

This is missing behavior defined in gRFC A74:
> As per gRFC A31, the ConfigSelector gives each RPC a ref to the
> cluster that was selected for it to ensure that the cluster is not
> removed from the xds_cluster_manager LB policy config before the RPC
> is done with its LB picks. These cluster refs will also hold a
> subscription for the cluster from the XdsDependencyManager, so that
> the XdsDependencyManager will not stop watching the cluster resource
> until the cluster is removed from the xds_cluster_manager LB policy
> config.
Without the logic, RPCs can race and see the error:
> INTERNAL: CdsLb for cluster0: Unable to find non-dynamic root cluster
Fixes #12152. This fixes the regression introduced in 297ab05e

xds: XdsNR should be subscribing to clusters with XdsDepManager

---

api/src/main/java/io/grpc/NameResolver.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/RetryingNameResolver.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
xds/src/main/java/io/grpc/xds/XdsDependencyManager.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
xds/src/test/java/io/grpc/xds/XdsDependencyManagerTest.java

ClusterResolverLb gets the NameResolverRegistry from LoadBalancer.Helper, so a new API was added in NameResover.Args to propagate the same object to the name resolver tree.
RetryingNameResolver was exposed to xds. This is expected to be temporary, as the retrying is being removed from ManagedChannelImpl and moved into the resolvers. At that point, DnsNameResolverProvider would wrap DnsNameResolver with a similar API to RetryingNameResolver and xds would no longer be responsible.

xds: Add logical dns cluster support to XdsDepManager

---

binder/src/androidTest/java/io/grpc/binder/internal/BinderClientTransportTest.java
binder/src/main/java/io/grpc/binder/internal/BinderTransport.java
binder/src/testFixtures/java/io/grpc/binder/internal/SettableAsyncSecurityPolicy.java

Addresses a pre-existing problem noted in CR/769886275

binder: Cancel checkAuthorization() request if still pending upon termination

---

buildscripts/grpc-java-artifacts/Dockerfile

download maven using archive/permalink url (1.67.x backport)

---

buildscripts/grpc-java-artifacts/Dockerfile

download maven using archive/permalink url (1.69.x backport)

---

buildscripts/grpc-java-artifacts/Dockerfile

download maven using archive/permalink url (1.70.x backport)

---

buildscripts/grpc-java-artifacts/Dockerfile

download maven using archive/permalink url (1.72.x backport)

---

buildscripts/grpc-java-artifacts/Dockerfile

download maven using archive/permalink url (1.73.x backport)

---

buildscripts/kokoro/psm-spiffe.cfg

kokoro: add spiffe tests config (1.73.x backport)

---

binder/src/main/java/io/grpc/binder/AndroidComponentAddress.java

Addresses CR/769886275 comment on an unrelated/preexisting issue.

AndroidComponentAddress constructor can be private.

---

binder/src/main/java/io/grpc/binder/internal/Outbound.java
core/src/main/java/io/grpc/internal/AbstractClientStream.java
core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
core/src/test/java/io/grpc/internal/GrpcUtilTest.java
core/src/test/java/io/grpc/internal/ServerImplTest.java
inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java

PROTOCOL-HTTP2.md specifies "TimeoutValue → {positive integer as ASCII string of at most 8 digits}". Zero is not positive, so it should be avoided. So make sure timeouts are at least 1 nanosecond instead of 0 nanoseconds.
grpc-go recently began disallowing zero timeouts in https://github.com/grpc/grpc-go/pull/8290 which caused a regression as grpc-java can generate such timeouts. Apparently no gRPC implementation had previously been checking for zero timeouts.
Instead of changing the max(0) to max(1) everywhere, just move the max handling into TimeoutMarshaller, since every caller of TIMEOUT_KEY was doing the same max() handling.
Before fd8fd517d (in 2016!), grpc-java actually behaved correctly, as it
failed RPCs with timeouts "<= 0". The commit changed the handling to the
max(0) handling …

core: grpc-timeout should always be positive

---

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
rls/src/main/java/io/grpc/rls/LbPolicyConfiguration.java
rls/src/main/java/io/grpc/rls/RlsLoadBalancer.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

297ab05ef converted CDS to XdsDependencyManager. This caused three regressions:
* CdsLB2 as a RLS child would always fail with "Unable to find non-dynamic root cluster" because is_dynamic=true was missing in its service config
* XdsNameResolver only propagated resolution updates when the clusters changed, so a CdsUpdate change would be ignored. This caused a hang for RLS even with is_dynamic=true. For non-RLS the lack config update broke the circuit breaking psm interop test. This would have been more severe if ClusterResolverLb had been converted to XdsDependenceManager, as it would have ignored EDS updates
* RLS did not propagate resolution updates, so CdsLB2 even with is_dynamic=true the CdsUpdate for the new cluster would never arrive, causing a hang
b/428120265
b/427912384
Backport …

Fix RLS regressions from XdsDepMan conversion (1.74.x backport)

---

MAINTAINERS.md

This PR moves the following inactive maintainers to Emeritus:
- Larry Safran (@larry-safran)
- Mark B. (@markb74)
This PR must remain open until July 10th, 2025 to allow time for response.

Remove inactive maintainers

---

netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java

In #12185, RPCs were randomly hanging. In #12207 this was tracked down to the headers promise completing successfully, but the netty stream was null. This was because the headers write hadn't completed but stream.close() had been called by goingAway().

netty: Associate netty stream eagerly to avoid client hang

---

netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java

In #12185, RPCs were randomly hanging. In #12207 this was tracked down to the headers promise completing successfully, but the netty stream was null. This was because the headers write hadn't completed but stream.close() had been called by goingAway().
Backport of #12222

netty: Associate netty stream eagerly to avoid client hang (1.74.x backport)

---

api/src/main/java/io/grpc/Metadata.java

Fix instances where HashSet / HashMap were initialized with initial capacity of the number of keys to be inserted, which would always lead to a rehash / resize operation.

api: Size Sets and Maps correctly in handling of Metadata values to be exchanged during a call

---

core/src/main/java/io/grpc/internal/DelayedClientCall.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

The main reason I made a change here was to fix the tense from the deadline "will be exceeded in" to "was exceeded after". But we really don't want to be doing the string formatting unless the deadline is actually exceeded. There were a few more changes to make some variables effectively final.

core: Don't pre-compute DEADLINE_EXCEEDED message for delayed calls

---

xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java

The PriorityLB predates A56. tryNextPriority() now matches ChoosePriority() from the gRFC.
The biggest change is waiting on CONNECTING children instead of failing after the failOverTimer fires. The failOverTimer should be used to start lower priorities more eagerly, but shouldn't cause the overall connectivity state to become TRANSIENT_FAILURE on its own. The prior behavior of creating the "Connection timeout for priority" failing picker was particularly strange, because it didn't update child's connectivity state. This previous behavior was creating errors because of the failOverTimer with no way to diagnose what was going wrong.
b/428517222

xds: Align PriorityLB child selection with A56

---

interop-testing/src/main/java/io/grpc/testing/integration/SoakClient.java

Avoid hypothetical races b/t writes to stderr and other logging

interop-testing: make soak test use logger rather than writing to stderr directly

---

MODULE.bazel
examples/MODULE.bazel
examples/build.gradle
examples/example-alts/build.gradle
examples/example-debug/build.gradle
examples/example-debug/pom.xml
examples/example-dualstack/build.gradle
examples/example-dualstack/pom.xml
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-gcp-csm-observability/build.gradle
examples/example-gcp-observability/build.gradle
examples/example-hostname/build.gradle
examples/example-hostname/pom.xml
examples/example-jwt-auth/build.gradle
examples/example-jwt-auth/pom.xml
examples/example-oauth/build.gradle
examples/example-oauth/pom.xml
examples/example-opentelemetry/build.gradle
examples/example-orca/build.gradle
examples/example-reflection/build.gradle
examples/example-servlet/build.gradle
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/example-xds/build.gradle
examples/pom.xml
gradle/libs.versions.toml
repositories.bzl

Notably, protobuf to 3.25.8, opentelemetry to 1.52.0. Protobuf in Bazel has 25.5 in the BCR and it seems better to align the WORKSPACE with that version. But we can't actually use 25.5 in BCR because it is incompatible with Bazel 7.
-------
This is a backport of #12252 (not created with the script; I just saved the old commits before I fixed all the conflicts on master)

Bump versions of dependencies (#12252) (v1.75.x)

---

xds/src/main/java/io/grpc/xds/client/ControlPlaneClient.java

Seems like a good time to stop hating ourselves, as that seems to be the only reason to use the same string.

xds: Use a different log name for XdsClientImpl and ControlPlaneClient

---

xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java

Backport of #12289 to v1.75.x.
---
Since c4256add4 we no longer fabricate a TRANSIENT_FAILURE update from children. However, previously that would have set
seenReadyOrIdleSinceTransientFailure = false and prevented future timer creation. If a LB policy gives extraneous updates with state CONNECTING, then it was possible to re-create failOverTimer which would then wait the 10 seconds for the child to finish CONNECTING. We only want to give the child one opportunity after transitioning out of READY/IDLE.
https://github.com/grpc/proposal/pull/509

xds: Avoid PriorityLb re-enabling timer on duplicate CONNECTING (v1.75.x backport)

---

netty/src/main/java/io/grpc/netty/GrpcSslContexts.java

This PR is related to https://github.com/grpc/grpc-java/issues/12227. 
With the proposed change, the GrpcSslContext was able to create SslContext with BCJSSE provider. I didn't find problems with this setup in our app and in example-tls, therefore raising a PR. My findings are described in aforementioned issue as comment https://github.com/grpc/grpc-java/issues/12227#issuecomment-3127857981. 
@ejona86 letting you know since your comments in the issue

netty: Support BCJSSE provider in GrpcSslContexts

---

cronet/build.gradle
xds/src/main/java/io/grpc/xds/client/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java

xds: xdsClient caches transient error for new watchers

---

binder/src/androidTest/java/io/grpc/binder/internal/BinderClientTransportTest.java
binder/src/androidTest/java/io/grpc/binder/internal/BinderTransportTest.java
binder/src/main/java/io/grpc/binder/internal/ActiveTransportTracker.java
binder/src/main/java/io/grpc/binder/internal/BinderClientTransport.java
binder/src/main/java/io/grpc/binder/internal/BinderClientTransportFactory.java
binder/src/main/java/io/grpc/binder/internal/BinderServer.java
binder/src/main/java/io/grpc/binder/internal/BinderServerTransport.java
binder/src/main/java/io/grpc/binder/internal/BinderTransport.java
binder/src/main/java/io/grpc/binder/internal/Inbound.java
binder/src/test/java/io/grpc/binder/internal/BinderServerTransportTest.java
binder/src/testFixtures/java/io/grpc/binder/internal/BinderClientTransportBuilder.java

BinderTransport.java is getting too long and deeply nested.
This is a pure refactor with no code changes. Wish this was obvious but github's diff viewer is so terrible!

binder: Move BinderTransport's inner classes to the top level

---

binder/src/main/java/io/grpc/binder/internal/BinderClientTransport.java
binder/src/test/java/io/grpc/binder/internal/RobolectricBinderTransportTest.java
core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java

`attributes = setSecurityAttrs(attributes, remoteUid);` should not run for :
- a malformed SETUP_TRANSPORT transaction
- a rogue SETUP_TRANSPORT transaction that arrives post-TransportState.SETUP

binder: REMOTE_UID must hold exactly the uid passed to the SecurityPolicy and never change

---

README.md

With the default @generated=omit option used by grpc-compiler, it is no longer necessary to have the compile-only dependency on org.apache.tomcat:annotations-api.

Remove org.apache.tomcat:annotations-api from README

---

android-interop-testing/src/main/AndroidManifest.xml
android-interop-testing/src/main/java/io/grpc/android/integrationtest/TesterActivity.java
android-interop-testing/src/main/res/layout/activity_tester.xml
android-interop-testing/src/main/res/values/strings.xml
binder/src/main/AndroidManifest.xml
lint.xml

Fixes : https://github.com/grpc/grpc-java/issues/6868 
android-interop-testing : worked on clearing lint warnings in android-interop and binder module

android-interop-testing : working on clearing lint warnings

---

servlet/src/jettyTest/java/io/grpc/servlet/JettyTransportTest.java
servlet/src/main/java/io/grpc/servlet/ServletAdapter.java
servlet/src/main/java/io/grpc/servlet/ServletServerBuilder.java
servlet/src/tomcatTest/java/io/grpc/servlet/TomcatTransportTest.java
servlet/src/undertowTest/java/io/grpc/servlet/UndertowTransportTest.java

servlet: configurable methodNameResolver

---

servlet/src/main/java/io/grpc/servlet/ServletAdapter.java
servlet/src/test/java/io/grpc/servlet/ServletServerBuilderTest.java

Currently there is a race between 2 tasks scheduled to handle request timeout
* servlet AsyncContext timeout
* gRPC Context
which can cause instability

servlet: add extra 5s to AsyncContext timeout

---

binder/src/main/java/io/grpc/binder/internal/BinderTransport.java

There's no reason why we shouldn't just have proper synchronization here, even if only used in tests. We shouldn't get into the habit of suppressing them.
CC @kannanjgithub, @jdcormie

binder: Fix synchronization instead of suppressing GuardedBy

---

api/src/main/java/io/grpc/LoadBalancer.java

Use a singleton empty Object array to initialize the customOptions default in LoadBalancer.Builder.

Avoid allocating empty array in LoadBalancer

---

android/src/main/java/io/grpc/android/AndroidChannelBuilder.java
android/src/test/java/io/grpc/android/AndroidChannelBuilderTest.java

Fixes : https://github.com/grpc/grpc-java/issues/12313
In case if VPN toggled on<->off `wasConnected` returns true and `delegate.enterIdle()` is skipped.
PS: Not using `android.net.ConnectivityManager.NetworkCallback#onCapabilitiesChanged` for API 24+ can also be an issue if capabilities change and user needs to receive updates.

android: fix network change handling on API levels < 24

---

SECURITY.md

In the olden days Alpine didn't work at all. Then it worked. And then sometime in 2021 it started failing (#8751) because of missing __strndup. The most recent deep investigation showed it is missing __strdup these days https://github.com/grpc/grpc-java/issues/11660#issuecomment-2469284111 .
I'm not expecting too many people to find this themselves, but we can link to it when they experience problems.

SECURITY.md: Mention gcompat for Alpine

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java

This had been accidentally left in 0c179e3f9.
Requesting a refresh is pretty close to RetryingNameResolver's behavior of exponential backoff. While not identical, it is the closest we can get easily.

xds: Remove verify TODO for onResult2 error status

---

examples/MODULE.bazel

This is an alternative to #12135 
CC @vorburger

examples: Explain Bazel BCR releases and git_override option

---

api/src/main/java/io/grpc/ClientStreamTracer.java
core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/OobChannel.java
core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/main/java/io/grpc/internal/SubchannelChannel.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java
opentelemetry/src/main/java/io/grpc/opentelemetry/GrpcOpenTelemetry.java
opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryMetricsModule.java
opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryMetricsResource.java
opentelemetry/src/main/java/io/grpc/opentelemetry/internal/OpenTelemetryConstants.java
opentelemetry/src/test/java/io/grpc/opentelemetry/OpenTelemetryMetricsModuleTest.java

implements [A96](https://github.com/grpc/proposal/pull/488/files)

Implement otel retry metrics

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java

Needed for `GcpAuthenticationFilter` to retrieve the cluster key set into the `CallOptions`.

xds: Make cluster selection interceptor run before other filters

---

xds/src/test/java/io/grpc/xds/internal/security/trust/XdsTrustManagerFactoryTest.java

xds: Use `unused` variable to ignore the return value

---

android/src/main/java/io/grpc/android/UdsChannelBuilder.java

11922 :: UdsChannelBuilder does not work with WiFi Proxy on Android.
