stub/src/main/java/io/grpc/stub/Calls.java
stub/src/test/java/io/grpc/stub/CallsTest.java

Addresses #152 
@ejona86 Please take a look.

Implement cancellation for the Future interface.

---

core/src/main/java/io/grpc/transport/AbstractClientStream.java
core/src/main/java/io/grpc/transport/AbstractServerStream.java
core/src/main/java/io/grpc/transport/AbstractStream.java
core/src/main/java/io/grpc/transport/Buffer.java
core/src/main/java/io/grpc/transport/ClientStream.java
core/src/main/java/io/grpc/transport/ClientTransport.java
core/src/main/java/io/grpc/transport/ClientTransportFactory.java
core/src/main/java/io/grpc/transport/CompositeBuffer.java
core/src/main/java/io/grpc/transport/ForwardingBuffer.java
core/src/main/java/io/grpc/transport/Http2ClientStream.java
core/src/main/java/io/grpc/transport/MessageDeframer.java
core/src/main/java/io/grpc/transport/MessageFramer.java
core/src/main/java/io/grpc/transport/ServerStream.java
core/src/main/java/io/grpc/transport/ServerStreamListener.java
core/src/main/java/io/grpc/transport/ServerTransportListener.java
core/src/main/java/io/grpc/transport/TransportFrameUtil.java

Polish javadoc for transport/

---

core/src/main/java/io/grpc/transport/HttpUtil.java
netty/src/main/java/io/grpc/transport/netty/NettyClientHandler.java

The attempt here is to identify all causes of GO_AWAY and to ensure
there is a reasonable description to help understand the cause.
Fixes #163

Tightening up error message for GO_AWAY.

---

okhttp/src/test/java/io/grpc/transport/okhttp/OkHttpClientTransportTest.java

Test receiving invalid stream IDs in okhttp

---

examples/build.gradle

@nmittler 
Same fix as done before for other modules

Fix IntelliJ project generation by including generated protobuf srcs

---

integration-testing/src/test/java/io/grpc/testing/integration/Http2NettyLocalChannelTest.java
netty/src/main/java/io/grpc/transport/netty/NettyChannelBuilder.java
netty/src/main/java/io/grpc/transport/netty/NettyClientTransport.java
netty/src/main/java/io/grpc/transport/netty/NettyServer.java
netty/src/main/java/io/grpc/transport/netty/NettyServerBuilder.java

Demonstrate and test usage with LocalChannel but will be used for working with Native EPoll channel

Add support to Netty builders for specifying other channel types

---

build.gradle

Add name and developers to pom

---

core/src/test/java/io/grpc/transport/HttpUtilTest.java

Add package statement to HttpUtilTest

---

okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/transport/okhttp/OkHttpClientTransportTest.java

This was found and verified by Android Gms-core setting App, when the server is down during a RPC, the App crashes by the IllegalStateException.
modified:   okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java

Don't read with frameReader after it is closed, otherwise an Illegalstateexception would be thrown and will not be caught.

---

auth/src/test/java/io/grpc/auth/ClientAuthInterceptorTests.java
examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java
examples/src/main/java/io/grpc/examples/helloworld/HelloWorldServer.java

Add missing copyright headers

---

.travis.yml
buildscripts/make_dependencies.sh
compiler/build.gradle

It will likely fail tests, due to #223.

Working Travis build, with caching of deps

---

.travis.yml
build.gradle
checkstyle.xml
examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java
examples/src/main/java/io/grpc/examples/routeguide/RouteGuideClient.java
examples/src/main/java/io/grpc/examples/routeguide/RouteGuideServer.java

Make checkstyle failures fatal, and fix last issues

---

integration-testing/build.gradle
integration-testing/src/main/java/io/grpc/testing/integration/AbstractTransportTest.java
integration-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java

Take two. The second commit is the only change, and tweaks tests so they pass on Travis.
@nmittler, if you could review it, it shouldn't take long.

Use tls for netty tests

---

integration-testing/src/main/java/io/grpc/testing/integration/AbstractTransportTest.java

The previous flow control test would work without issue even if flow
control was being ignored.
Resolves #245

Test whether inbound flow control functions

---

netty/src/main/java/io/grpc/transport/netty/NettyServer.java

Wait for handler registration

---

core/src/main/java/io/grpc/SerializingExecutor.java

isThreadScheduled is @GuardedBy("internalLock").

Hold lock while reading isThreadScheduled

---

okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientStream.java
okhttp/src/test/java/io/grpc/transport/okhttp/OkHttpClientTransportTest.java

Resets the stream when the receiving window size goes negative.

okhttp: Reset stream when receiving window is negative  Resolves #215

---

build.gradle
compiler/build.gradle
compiler/src/test/run_nano_test.sh

Resolves #276
@ejona86 please take a look

Rename the codegen binary from java_plugin to protoc-gen-grpc-java

---

netty/src/main/java/io/grpc/transport/netty/NettyServer.java
netty/src/main/java/io/grpc/transport/netty/NettyServerBuilder.java
netty/src/main/java/io/grpc/transport/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/transport/netty/NettyServerTransport.java
netty/src/test/java/io/grpc/transport/netty/NettyServerHandlerTest.java

netty: Add option to set MAX_CONCURRENT_STREAMS

---

integration-testing/src/main/java/io/grpc/testing/integration/AbstractTransportTest.java

See #289 for more detail.
I can't reproduce the failure locally, my guess is that our TIMEOUT is too short for Travis, when the Travis machines get high CPU usage or short of memory (and causes full GC), we should tolerate longer waiting time.
I'm not sure whether this change can fix the flakeness, but I'd like to give it a try.
@ejona86

De-flake transport test.

---

build.gradle
compiler/build.gradle

Remove call sites of Os.isFamily(). Use osdetector instead

---

core/src/main/java/io/grpc/transport/Http2ClientStream.java
okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientStream.java
okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/transport/okhttp/OkHttpClientTransportTest.java

okhttp: Clean up stream when error happens.

---

core/src/main/java/io/grpc/transport/AbstractClientStream.java
core/src/main/java/io/grpc/transport/AbstractServerStream.java
core/src/main/java/io/grpc/transport/AbstractStream.java
core/src/main/java/io/grpc/transport/MessageFramer.java
core/src/test/java/io/grpc/transport/MessageFramerTest.java
netty/src/main/java/io/grpc/transport/netty/NettyClientStream.java
netty/src/main/java/io/grpc/transport/netty/NettyWritableBufferAllocator.java
netty/src/test/java/io/grpc/transport/netty/NettyServerHandlerTest.java
netty/src/test/java/io/grpc/transport/netty/NettyServerStreamTest.java
okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientStream.java
okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpWritableBufferAllocator.java

Fixes
https://github.com/grpc/grpc-java/issues/336

Fix memeory leak in MessageFramer

---

core/src/main/java/io/grpc/transport/MessageFramer.java
core/src/test/java/io/grpc/transport/MessageFramerTest.java

@nmittler 
Fixes https://github.com/grpc/grpc-java/issues/350

Fix issue where MessageFramer.close can be called in a reentrant fashion

---

okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java

Fix the race between failing and starting pending streams.

---

README.md

Add build status icon and rephrase title

---

CONTRIBUTING.md

Improve Contributing

---

build.gradle
compiler/build.gradle

Use protoc artifact from Maven Central.

---

benchmarks/src/generated/main/grpc/testing/Qpstest.java
examples/src/generated/main/io/grpc/examples/helloworld/HelloRequest.java
examples/src/generated/main/io/grpc/examples/helloworld/HelloResponse.java
examples/src/generated/main/io/grpc/examples/routeguide/Feature.java
examples/src/generated/main/io/grpc/examples/routeguide/Point.java
examples/src/generated/main/io/grpc/examples/routeguide/Rectangle.java
examples/src/generated/main/io/grpc/examples/routeguide/RouteNote.java
examples/src/generated/main/io/grpc/examples/routeguide/RouteSummary.java
integration-testing/src/generated/main/com/google/protobuf/EmptyProtos.java
integration-testing/src/generated/main/io/grpc/testing/integration/Messages.java

The previous output was not generated with proto3-alpha-2. This has been
regenerated using protoc on Maven Central, so it should be the same
output everywhere.
@zhangkun83

Update generated proto output

---

core/src/main/java/io/grpc/ChannelImpl.java

Ideally OKHttp wouldn't do blocking I/O during start(), but it does and
fixing it is non-trivial. OkHttp can either throw an exception when it
encounters an error during start or it can shut itself down. Both
require changes in ChannelImpl, so we just choose to keep OkHttp's
current behavior and deal with it in ChannelImpl.
@madongfly

Handle OkHttp throwing exception during start()

---

DEPLOYING.md
compiler/Dockerfile

Dockerfile for deployment

---

checkstyle.xml

@ejona86 
Makes checkstyle less noisy for tests

Add more JUnit annotations to list of methods checkstyle will ignore

---

okhttp/src/main/java/io/grpc/transport/okhttp/AsyncFrameWriter.java
okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/transport/okhttp/OkHttpClientTransportTest.java

okhttp: update connection window when receives DATA for existed streams.

---

integration-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
integration-testing/src/main/java/io/grpc/testing/integration/Util.java
integration-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java

okhttp: Enable TLS for Http2OkHttpTest.

---

benchmarks/src/jmh/java/io/grpc/benchmarks/netty/AbstractBenchmark.java
benchmarks/src/jmh/java/io/grpc/benchmarks/netty/FlowControlledMessagesPerSecondBenchmark.java
benchmarks/src/jmh/java/io/grpc/benchmarks/netty/SingleThreadBlockingQpsBenchmark.java
benchmarks/src/jmh/java/io/grpc/benchmarks/netty/StreamingPingPongsPerSecondBenchmark.java
benchmarks/src/jmh/java/io/grpc/benchmarks/netty/StreamingResponseBandwidthBenchmark.java
benchmarks/src/jmh/java/io/grpc/benchmarks/netty/UnaryCallQpsBenchmark.java
benchmarks/src/jmh/java/io/grpc/benchmarks/netty/UnaryCallResponseBandwidthBenchmark.java

@ejona86 
Add additional benchmarks including:
- streaming ping-pong messages per second
- unary response bandwidth in megabits per second
- streaming response bandwidth in megabits per second

Add new benchmarks

---

DEPLOYING.md
compiler/Dockerfile

Fix minor issues with release scripts/documentation

---

core/src/main/java/io/grpc/transport/AbstractStream.java
okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientStream.java
okhttp/src/main/java/io/grpc/transport/okhttp/OutboundFlowController.java
okhttp/src/test/java/io/grpc/transport/okhttp/OkHttpClientTransportTest.java

okhttp: outbound flow control.

---

build.gradle
netty/src/main/java/io/grpc/transport/netty/ProtocolNegotiators.java
okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java

For having http2 protocol string "h2".
Manually tested by ./run-test-client.sh --server_port=443 --server_host=grpc-test.sandbox.google.com --use_okhttp=true

Upgrade okhttp to 2.3

---

build.gradle

Release commit for 0.7.0

---

okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java
okhttp/src/main/java/com/squareup/okhttp/internal/SelectedProtocolQuerier.java

Fixes #467
Manually tested by using NPN on Android 4.3 (api level 18) talk to GFE.

Add SelectedProtocolQuerier to get protocol selected by NPN on Android.

---

netty/src/main/java/io/grpc/transport/netty/ProtocolNegotiators.java

To make CheckStyle happy.
@nmittler

Remove unused imports.

---

interop-testing/src/main/java/io/grpc/testing/integration/AbstractTransportTest.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java

Fixes #456
Manually tested with ./run-test-client.sh --server_port=443 --server_host=grpc-test.sandbox.google.com --server_host_override=grpc-test.sandbox.google.com --service_account_key_file=/usr/local/google/home/simonma/gce_cred.json --oauth_scope=https://www.googleapis.com/auth/xapi.zoo --test_case=service_account_creds
@ejona86

Add service_account_creds test.

---

build.gradle
okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java

Upgrade OkHttp to 2.4.

---

DEPLOYING.md

Document how to copy credentials for docker

---

stub/src/main/java/io/grpc/stub/ClientCalls.java

Previously, it always threw a RuntimeExecutionException with a
StatusRuntimeException within (since the only callers of setException()
provide a StatusRuntimeException).

Blocking calls should error with StatusRuntimeException

---

auth/src/main/java/io/grpc/auth/ClientAuthInterceptor.java

Make the code clearer, fixes #531.

---

interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
testing/src/main/java/io/grpc/testing/TestUtils.java

Rename getSslSocketFactoryForCertainCert to be newSslSocketFactoryForCa.

---

README.md

Add the bintray repository for Maven protoc-plugin in the example

---

run-test-client.sh
run-test-server.sh

Just helps new users wanting to try things out from thinking they need
to deal with compiling our protoc plugin. As seen in #581

Suggest -PskipCodegen in run-test-{client,server}

---

core/src/main/java/io/grpc/ServerServiceDefinition.java
core/src/test/java/io/grpc/MutableHandlerRegistryImplTest.java
core/src/test/java/io/grpc/ServerInterceptorsTest.java

Also trying to get my feet wet with this change, nothing too fancy.

Try to simplify server method definition

---

benchmarks/src/generated/main/grpc/io/grpc/testing/TestServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/testing/WorkerGrpc.java
compiler/src/java_plugin/cpp/java_generator.cpp
compiler/src/test/golden/TestService.java.txt
compiler/src/test/golden/TestServiceNano.java.txt
examples/src/generated/main/grpc/io/grpc/examples/helloworld/GreeterGrpc.java
examples/src/generated/main/grpc/io/grpc/examples/routeguide/RouteGuideGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
stub/src/main/java/io/grpc/stub/AbstractServiceDescriptor.java

Change AbstractServiceDescriptor.methods() to return Collection

---

okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientStream.java
okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/transport/okhttp/OkHttpClientTransportTest.java

Remove OkHttpClientTransport.DEFAULT_INITIAL_WINDOW_SIZE, use Utils.DEFAULT_WINDOW_SIZE instead.

---

okhttp/src/main/java/io/grpc/transport/okhttp/AsyncFrameWriter.java
okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/transport/okhttp/OkHttpClientTransportTest.java

The basic ideas are:
1. Do connecting in the same serializing executor that AsyncFrameWriter used, so that the stream operations like syncStream(), data() will be executed only after the connection is connected.
Fixes #578
@ejona86, please take a look, thanks.

okhttp: make transport.start() async.

---

core/src/main/java/io/grpc/AbstractChannelBuilder.java
core/src/main/java/io/grpc/ChannelImpl.java
core/src/test/java/io/grpc/ChannelImplTest.java

Add ClientInterceptors "inside" ChannelImpl

---

benchmarks/src/main/java/io/grpc/benchmarks/qps/Utils.java

Benchmark: Enable/Disable TLS for okhttp accordingly

---

core/src/main/java/io/grpc/transport/AbstractClientStream.java

These were some useful fixes found in #630 that seemed shouldn't be lost.

Error handling fix and minor improvements

---

core/src/main/java/io/grpc/Context.java

Add missing generics to Context internals

---

core/src/main/java/io/grpc/ServerImpl.java

Stop using intrinsic lock in ServerImpl

---

okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java

Correctly handle unknown http2 error code.

---

okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientStream.java
okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/transport/okhttp/OkHttpClientTransportTest.java

This is required by our internal sync.

Adjust @GuardedBy to pass internal GuardedBy Checking.

---

okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java

See [grpc spec](https://github.com/grpc/grpc-common/blob/master/PROTOCOL-HTTP2.md#errors)
@ejona86, please take a look, thanks!

OkHttp: sync error map with gRpc spec.

---

core/src/main/java/io/grpc/ClientCall.java
core/src/main/java/io/grpc/ClientCallImpl.java
core/src/main/java/io/grpc/ForwardingClientCallListener.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractTransportTest.java
stub/src/main/java/io/grpc/stub/ClientCalls.java
stub/src/test/java/io/grpc/stub/ClientCallsTest.java

Rename onPayload to onMessage

---

core/src/main/java/io/grpc/ClientCall.java
core/src/main/java/io/grpc/ClientCallImpl.java
core/src/main/java/io/grpc/ClientInterceptors.java
core/src/main/java/io/grpc/ForwardingClientCall.java
core/src/test/java/io/grpc/ClientInterceptorsTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractTransportTest.java
stub/src/main/java/io/grpc/stub/ClientCalls.java
stub/src/test/java/io/grpc/stub/ClientCallsTest.java

Rename sendPayload to sendMessage

---

core/src/main/java/io/grpc/ChannelImpl.java
core/src/main/java/io/grpc/ServerImpl.java

Make ServerImpl Use the common Scheduled Executor Service

---

core/src/main/java/io/grpc/ClientCall.java

Based on offline conversation, break all previous clients.

Remove all support for Payload

---

README.md
android-interop-testing/build.gradle
build.gradle

Upgrade protobuf-gradle-plugin to 0.6.1

---

netty/src/main/java/io/grpc/transport/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/transport/netty/NettyClientTransport.java

@nmittler, you should take a look at this when you get back.
@zhangkun83, since nmittler is on vacation do you feel comfortable reviewing this?
@carl-mastrangelo, FYI.

Notify transportReady() in Netty

---

core/src/main/java/io/grpc/transport/Http2ClientStream.java

@ejona86 Please take a look, thanks!

Make the change on status effective.

---

interop-testing/src/main/java/io/grpc/testing/integration/AbstractTransportTest.java

See #702 for details.
Fixes #702. 
@ejona86, Please take a look, thanks!

Fix serviceAccountCreds test and computeEngineCreds test.

---

core/src/main/java/io/grpc/transport/Http2ClientStream.java
netty/src/main/java/io/grpc/transport/netty/NettyClientHandler.java

Cherry-picked the two commits with a little conflict resolving.

Backport ef106e0 and 248f575 to 0.7.x

---

netty/src/main/java/io/grpc/transport/netty/GrpcSslContexts.java
okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java

Switch ALPN/NPN to advertise only h2

---

benchmarks/src/generated/main/grpc/io/grpc/testing/TestServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/testing/WorkerGrpc.java
benchmarks/src/jmh/java/io/grpc/benchmarks/netty/AbstractBenchmark.java
compiler/src/java_plugin/cpp/java_generator.cpp
compiler/src/test/golden/TestService.java.txt
compiler/src/test/golden/TestServiceNano.java.txt
compiler/src/test/proto/test.proto
core/src/main/java/io/grpc/MethodDescriptor.java
examples/src/generated/main/grpc/io/grpc/examples/helloworld/GreeterGrpc.java
examples/src/generated/main/grpc/io/grpc/examples/routeguide/RouteGuideGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
okhttp/src/test/java/io/grpc/transport/okhttp/OkHttpClientTransportTest.java
stub/src/main/java/io/grpc/stub/ClientCalls.java
stub/src/main/java/io/grpc/stub/ServerCalls.java

Rename Duplex to Bidi

---

core/src/main/java/io/grpc/KnownLength.java

Add available() to KnownLength

---

protobuf-nano/src/main/java/io/grpc/protobuf/nano/NanoProtoInputStream.java

Make NanoProtoInputStream package private

---

core/src/main/java/io/grpc/Status.java
core/src/main/java/io/grpc/StatusException.java
core/src/main/java/io/grpc/StatusRuntimeException.java

Fix javadoc, and remove deprecated OperationException classes

---

core/src/main/java/io/grpc/ClientInterceptors.java

Remove deprecated ClientInterceptors classes

---

benchmarks/src/jmh/java/io/grpc/benchmarks/TransportBenchmark.java
benchmarks/src/jmh/java/io/grpc/benchmarks/netty/AbstractBenchmark.java
benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncServer.java
core/src/main/java/io/grpc/ChannelImpl.java
core/src/main/java/io/grpc/ServerImpl.java
examples/src/main/java/io/grpc/examples/header/CustomHeaderClient.java
examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java
examples/src/main/java/io/grpc/examples/routeguide/RouteGuideClient.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceServer.java
netty/src/main/java/io/grpc/transport/netty/NettyServerBuilder.java

Change awaitTerminated to awaitTermination

---

core/src/main/java/io/grpc/Metadata.java
core/src/main/java/io/grpc/ServerServiceDefinition.java

Tighten up some access limit

---

core/src/main/java/io/grpc/AbstractServerBuilder.java

Add a javadoc for AbstractServerBuilder.buildEssentials

---

core/src/main/java/io/grpc/AbstractChannelBuilder.java

Add a javadoc for AbstractChannelBuilder.buildEssentials

---

core/src/main/java/io/grpc/AbstractChannelBuilder.java
core/src/main/java/io/grpc/ChannelImpl.java
core/src/main/java/io/grpc/Context.java
core/src/main/java/io/grpc/inprocess/package-info.java
core/src/main/java/io/grpc/internal/ExperimentalApi.java
core/src/main/java/io/grpc/internal/Internal.java
core/src/main/java/io/grpc/internal/package-info.java
core/src/main/java/io/grpc/package-info.java

Create annotation ExperimentalApi and Internal.

---

core/src/main/java/io/grpc/Channel.java

Remove Deprecated newCall method on Channel

---

build.gradle

Resolves #805
@nmittler @ejona86

Upgrade protobuf-gradle-plugin to 0.7.0

---

RELEASING.md

Update Docker version requirement

---

android-interop-testing/app/build.gradle

Update android-interop-test's dependency.

---

android-interop-testing/app/build.gradle

Update dependency for android interop test

---

core/src/main/java/io/grpc/CallOptions.java
core/src/main/java/io/grpc/ChannelImpl.java
core/src/main/java/io/grpc/ClientCallImpl.java
core/src/main/java/io/grpc/MessageEncoding.java
core/src/main/java/io/grpc/inprocess/InProcessTransport.java
core/src/main/java/io/grpc/internal/AbstractClientStream.java
core/src/main/java/io/grpc/internal/AbstractStream.java
core/src/main/java/io/grpc/internal/HttpUtil.java
core/src/main/java/io/grpc/internal/MessageDeframer.java
core/src/main/java/io/grpc/internal/MessageFramer.java
core/src/main/java/io/grpc/internal/Stream.java
core/src/test/java/io/grpc/internal/MessageDeframerTest.java
core/src/test/java/io/grpc/internal/MessageFramerTest.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/netty/NettyServerStream.java

In regards to #492
There will be more parts to compression, this is just the first.

Add compression [Part 1]

---

interop-testing/build.gradle
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
interop-testing/src/generated/main/java/io/grpc/testing/integration/Messages.java
interop-testing/src/generated/main/java/io/grpc/testing/integration/Test.java
interop-testing/src/main/java/io/grpc/testing/integration/ReconnectTestClient.java
interop-testing/src/main/proto/io/grpc/testing/integration/messages.proto
interop-testing/src/main/proto/io/grpc/testing/integration/test.proto

Implement Connection Backoff Interop test.

---

core/src/main/java/io/grpc/ClientCall.java
core/src/main/java/io/grpc/ClientCallImpl.java

Improve documentation for ClientCall.

---

core/src/main/java/io/grpc/MutableHandlerRegistry.java

Fix Comment in MutableHandlerRegistry

---

core/src/main/java/io/grpc/ServerImpl.java

Addresses @ejona86's comment on #823

Make ServerImpl constructor pakcage-private

---

core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/test/java/io/grpc/internal/GrpcUtilTest.java

Makes application-provided string comes first in User-Agent.

---

core/src/main/java/io/grpc/ChannelImpl.java
core/src/main/java/io/grpc/Context.java
core/src/main/java/io/grpc/ExperimentalApi.java

Add comment field to ExperimentalApi

---

core/src/main/java/io/grpc/CallOptions.java
core/src/main/java/io/grpc/ChannelImpl.java

Add experimental api to compression

---

benchmarks/build.gradle
benchmarks/src/jmh/java/io/grpc/benchmarks/netty/AbstractBenchmark.java
stub/src/main/java/io/grpc/stub/StreamObserver.java

Fixing the benchmarks

---

core/src/main/java/io/grpc/ServerImpl.java

Removing unused method in ServerImpl

---

core/src/main/java/io/grpc/ClientCall.java

Make ClientCall listener methods noops

---

core/src/main/java/io/grpc/ServerCall.java

Make ServerCall.Listener methods Nops

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

OkHttp: Fix race condition between sendCancel and sendFrame

---

core/src/main/java/io/grpc/internal/AbstractServerStream.java
core/src/test/java/io/grpc/internal/AbstractServerStreamTest.java

Add unit tests for AbstractServerStream

---

benchmarks/src/generated/main/grpc/io/grpc/testing/TestServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/testing/WorkerGrpc.java
compiler/src/java_plugin/cpp/java_generator.cpp
compiler/src/test/golden/TestService.java.txt
compiler/src/test/golden/TestServiceNano.java.txt
examples/src/generated/main/grpc/io/grpc/examples/helloworld/GreeterGrpc.java
examples/src/generated/main/grpc/io/grpc/examples/routeguide/RouteGuideGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java

Annotate method descritpor files in the generated code with ExperimentalApi

---

compiler/src/java_plugin/cpp/java_generator.cpp
compiler/src/java_plugin/cpp/java_generator.h
compiler/src/java_plugin/cpp/java_plugin.cpp

Check javanano_use_deprecated_package in the message's FileDescriptor, not the current file's.

---

core/src/main/java/io/grpc/MethodDescriptor.java
core/src/test/java/io/grpc/ServerInterceptorsTest.java

Fields in MethodDescriptor can't be null

---

android-interop-testing/app/build.gradle
android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/InteropTester.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractTransportTest.java
testing/build.gradle
testing/src/main/java/io/grpc/testing/StreamRecorder.java

Fixes #899 
@ejona86 Please take a look, thanks!

Move StreamRecorder to testing package.

---

core/src/main/java/io/grpc/ServerCall.java

Prevent status from impacting how ServerCall.Listener is invoked

---

core/src/main/java/io/grpc/HandlerRegistry.java
core/src/main/java/io/grpc/MutableHandlerRegistryImpl.java
core/src/main/java/io/grpc/ServerImpl.java
core/src/test/java/io/grpc/MutableHandlerRegistryImplTest.java

Remove HandlerRegistry.Method

---

core/src/main/java/io/grpc/Metadata.java

This is the documentation part of #725

Document valid characters for AsciiMarshaller

---

core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/main/java/io/grpc/internal/SharedResourceHolder.java

Daemonize shared threads, and make sure each thread has a name

---

android/src/main/java/io/grpc/android/AndroidChannelBuilder.java
core/src/main/java/io/grpc/ManagedChannelBuilder.java
core/src/main/java/io/grpc/ServerBuilder.java
core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java

Use Executor in stable builder APIs instead of ExecutorService

---

core/src/main/java/io/grpc/HandlerRegistry.java
core/src/main/java/io/grpc/MutableHandlerRegistryImpl.java

Add an authority header to HandlerRegistry.lookupMethod

---

core/src/main/java/io/grpc/Metadata.java

Remove Metadata.Headers and Metadata.Trailers

---

netty/src/main/java/io/grpc/netty/NettyServer.java

Resolves #926. Transports can still be alive when the Server shuts down,
but they are using the worker event loops. Only release the worker event
loops when all transport's channels are closed.
@nmittler

Only release event loops when unused

---

android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/InteropTester.java
android-interop-testing/app/src/main/proto/io/grpc/android/integrationtest/test.proto

The test scenarios all remain the same. The changes are just in proto to nanoproto conversion and removing mocktio

Port test cases in AbstractTransportTest to android interop test

---

core/src/main/java/io/grpc/internal/Stream.java

Fix flow-control documentation on Stream

---

examples/src/main/java/io/grpc/examples/header/CustomHeaderServer.java
examples/src/main/java/io/grpc/examples/helloworld/HelloWorldServer.java
examples/src/main/java/io/grpc/examples/routeguide/RouteGuideServer.java

Update server to await termination in the main thread

---

examples/src/main/java/io/grpc/examples/experimental/CompressingHelloWorldClient.java
stub/src/main/java/io/grpc/stub/AbstractStub.java

Use stub call options for compression

---

core/src/main/java/io/grpc/ServerProvider.java
core/src/test/java/io/grpc/ServerProviderTest.java
core/src/test/resources/io/grpc/ServerProviderTest-multipleProvider.txt
core/src/test/resources/io/grpc/ServerProviderTest-unavailableProvider.txt
netty/src/main/java/io/grpc/netty/NettyServerProvider.java
netty/src/main/resources/META-INF/services/io.grpc.ServerProvider
netty/src/test/java/io/grpc/netty/NettyServerProviderTest.java

Add a server Provider

---

testing/src/main/java/io/grpc/testing/StreamRecorder.java
testing/src/main/java/io/grpc/testing/TestUtils.java

We've not done any real work to make sure they have reasonable APIs.
@louiscryan, FYI

Mark classes in testing as ExperimentalApi

---

examples/src/main/java/io/grpc/examples/experimental/CompressingHelloWorldClient.java
examples/src/main/java/io/grpc/examples/header/CustomHeaderClient.java
examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java
examples/src/main/java/io/grpc/examples/routeguide/RouteGuideClient.java

Update Client Examples to use ManagedChannelBuilder

---

core/src/main/java/io/grpc/MethodDescriptor.java
core/src/main/java/io/grpc/ServerCallHandler.java
stub/src/main/java/io/grpc/stub/ServerCalls.java

Fixes #975 
@zhangkun83, so I've marked the ones I could, but it seemed like there should be more. Did I miss any obvious ones?

Mark some APIs codegen uses experimental to allow for optimizations

---

interop-testing/src/main/java/io/grpc/testing/integration/TestServiceServer.java

Make Interop Server block until shutdown

---

core/src/main/java/io/grpc/internal/ServerImpl.java

Don't let server start if already shutting down

---

interop-testing/src/main/java/io/grpc/testing/integration/TestServiceImpl.java
stub/src/main/java/io/grpc/stub/ServerCalls.java

Fix the double-closure of server call for interop tests.

---

CHANGES.md

In order to keep track of fixes, breakages, new features and the like, I am adding a CHANGES file.  Ideally this will be updated on each pull request, assuming the change has user impact.

Add a Changes document to keep track of release notes

---

SECURITY.md
build.gradle

It causes it to try to download protoc with _fedora in its classifier.

classifierWithLikes breaks protobuf-gradle-plugin

---

interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java

Actually this is a wild guess for the flakiness described in #991, since I couldn't reproduce it on my local machine, I have low confidence for fixing that flakiness, but give it a try and reduce the memory usage is no harm.

Reduce memory usage in test.

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java

Correct the order of arguments.

---

README.md
android-interop-testing/app/build.gradle
examples/android/app/build.gradle

Update README per the discussion in #1104

Give dependency example for android clients.

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

Sorry for the unrelated test changes in this PR, I am adding the first test that doesn't depend on mocking which added additional changes.
I mentioned this in #1109 and #1108

Allow non-host based authorities in OkHttp transport

---

interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java

Expose timeout_on_sleeping_server test to interop test client.

---

core/src/main/java/io/grpc/internal/TransportSet.java

The scheduling on another thread led to a race where sometimes the
future wasn't completed by the time isDone() was checked in
ClientCallImpl causing the usage of DelayedStream, which really messed
up what the test was trying to do.

Fix flake in ManagedChannelImplTest.transportFailsOnStart

---

core/src/main/java/io/grpc/internal/ClientCallImpl.java

Otherwise, when DelayedStream is created it ends up calling
clientTransportProvider a second time. However, we already have a
transportFuture available, we should just use it instead.
Fixes #1132

Pass the initial transportFuture to DelayedStream.

---

netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java

Followup promised by commit f39b67c0e83c78c37f6dffc206e7531b6b834a5f

Add followup ProtocolNegotiators.tls tests

---

okhttp/build.gradle

Update okhttp javadoc

---

core/src/main/java/io/grpc/Context.java
core/src/test/java/io/grpc/ContextTest.java

A few minor bugs were discovered and fixed.

Increase code coverage of Context

---

core/src/main/java/io/grpc/CallOptions.java
core/src/main/java/io/grpc/RequestKey.java
core/src/test/java/io/grpc/CallOptionsTest.java

Increase coverage for CallOptions

---

core/src/main/java/io/grpc/internal/MessageDeframer.java
core/src/test/java/io/grpc/internal/MessageDeframerTest.java

Running "./gradlew build :grpc-all:jacocoTestReport"  seems to indicate that the methods in this class were not well covered.  I am adding these really simple unit tests to cover it.

Add unit tests for SizeEnforcingInputStream

---

okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

We should check the window update is sent after the message is consumed.
Hopefully this will fix #1168

[OkHtpp] Correct windowUpdateWithInboundFlowControl test.

---

core/src/main/java/io/grpc/Internal.java
core/src/main/java/io/grpc/internal/package-info.java

Clarify the audience of internal API.

---

core/src/main/java/io/grpc/internal/GrpcUtil.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/main/java/io/grpc/netty/NettyServer.java
netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
netty/src/main/java/io/grpc/netty/NettyServerTransport.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java

Fixes #1144
@louiscryan @nmittler Please take a look, thanks!

Make the header list size limit configurable on both client and serve side.

---

core/src/main/java/io/grpc/CallOptions.java
core/src/main/java/io/grpc/Status.java
core/src/main/java/io/grpc/internal/AbstractClientStream.java
core/src/main/java/io/grpc/internal/AbstractStream.java

Migrating from Objects.ToStringHelper to MoreObjects.ToStringHelper.

---

core/src/main/java/io/grpc/Metadata.java
core/src/test/java/io/grpc/MetadataTest.java
netty/src/main/java/io/grpc/netty/Utils.java
protobuf/src/main/java/io/grpc/protobuf/ProtoUtils.java

Add Header name character restrictions

---

core/src/main/java/io/grpc/Metadata.java
core/src/test/java/io/grpc/MetadataTest.java

Update -bin header restrictions, and re introduce string interning.

---

core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/test/java/io/grpc/internal/ClientCallImplTest.java

Minor refactor of ClientCallImpl's start method to be more testable, and also add tests.
Minor behavior changes:
- If there are no available message encodings, the header will no longer be set
- Multiple accept encodings (a.k.a. decompressors) now show up as a single comma separated string, rather than as multiple headers.
/cc @ejona86

Minor cleanup of ClientCallImpl header normalization

---

core/src/main/java/io/grpc/Metadata.java
core/src/test/java/io/grpc/MetadataTest.java

Fix placeholder in the error message of Preconditions.

---

core/src/main/java/io/grpc/internal/ServerCallImpl.java
core/src/main/java/io/grpc/internal/ServerImpl.java
core/src/test/java/io/grpc/internal/ServerCallImplTest.java

Trying to keep ServerImpl simple.

Split out server call impl, add explicit tests and remove an impossble case

---

netty/src/main/java/io/grpc/netty/Utils.java

I recommend a merge commit over a cherry pick :smile:

Fix build failure due to unused import.

---

android-interop-testing/app/proguard-rules.pro
android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/InteropTester.java

@carl-mastrangelo Please take a look, thanks!

Update Android interop test App to use ManagedChannelBuilder

---

core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/main/java/io/grpc/internal/DelayedStream.java
core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
core/src/test/java/io/grpc/internal/ClientCallImplTest.java
core/src/test/java/io/grpc/internal/DelayedStreamTest.java

Move delayed stream out of ClientCallImpl, and add tests for createStream

---

core/src/test/java/io/grpc/internal/SerializeReentrantCallsDirectExecutorTest.java

@carl-mastrangelo, please take a look, thanks!

Add missing @RunWith, it is required internally

---

core/src/main/java/io/grpc/ClientCall.java
core/src/main/java/io/grpc/internal/ServerCallImpl.java
core/src/test/java/io/grpc/internal/ServerCallImplTest.java
stub/src/main/java/io/grpc/stub/ServerCalls.java

I left the request(2) in place because I didn't see a good place to put it.

Move ServerCall unary check and add tests

---

core/src/main/java/io/grpc/internal/TransportSet.java
core/src/test/java/io/grpc/internal/TransportSetTest.java

`TransportSet` won't connect/reconnect until a transport is requested
through `obtainActiveTransport()`.
Lazy connection is safer, and more desirable in mobile environments.
It's also what C core is doing.
To warm up connections, `LoadBalancer` can call
`TransportManager.getTransport()`, even periodically if it wants to
maintain live connections.
#1191

Revert to lazy-connection.

---

core/src/test/java/io/grpc/ForwardingServerCallListenerTest.java

These tests aren't super useful, but its easy coverage.

Bump test coverage

---

interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpProtocolNegotiator.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpTlsUpgrader.java
okhttp/third_party/okhttp/java/io/grpc/okhttp/internal/DistinguishedNameParser.java
okhttp/third_party/okhttp/java/io/grpc/okhttp/internal/OkHostnameVerifier.java

@carl-mastrangelo please take a look, thanks!

[OkHttp]Add hostname verification.

---

grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

While GrpclbLoadBalancer always starts by sending a GRPCLB request to addresses that NameResolver has provided, the addresses may be application servers that don't implement GRPCLB protocol. In that case, we should start sending application traffic to it.
#1137

GRPCLB fallback mode.

---

core/src/main/java/io/grpc/inprocess/InProcessTransport.java
core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractTransportTest.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java

- Include transport information in RPC's final status
- Implement toString() of transports

More information for debugging.

---

core/src/main/java/io/grpc/internal/GrpcUtil.java

Fix memory leak with cancellation timeouts

---

netty/src/main/java/io/grpc/netty/NettyChannelProvider.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelProvider.java

This makes it possible to delegate to channel providers.

Raise method visibility in Channel Providers

---

examples/src/main/java/io/grpc/examples/header/CustomHeaderClient.java
examples/src/main/java/io/grpc/examples/header/CustomHeaderServer.java
examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java
examples/src/main/java/io/grpc/examples/helloworld/HelloWorldServer.java
examples/src/main/java/io/grpc/examples/routeguide/RouteGuideClient.java
examples/src/main/java/io/grpc/examples/routeguide/RouteGuideServer.java

Try to make it clear how failures propagate and provide hints on how to
get more error information.

More precise exception handling in examples

---

build.gradle

The v0.12.x (yes, 0.12, to sync with c) branch has been made.

Start 0.13.0 development cycle

---

interop-testing/src/test/java/io/grpc/testing/integration/TlsTest.java

The client didn't have the trust manager set, so the RPC would fail due
to server-certificate verification, not lack of client auth.
With this change, noClientAuthFailure now fails with tcnative but still
passes with Jetty ALPN.
@matthild, FYI

Fix broken noClientAuthFailure test

---

core/src/main/java/io/grpc/Context.java
core/src/test/java/io/grpc/ContextTest.java

Before the service would be leaked, because when the scheduled future
was cancelled the scheduler wouldn't be released. Also, Future isn't
powerful enough to signal when we should release when cancelling.
Given the nature of Context, it also seems beneficial to not have it own
threads. Since any caller of withDeadline*() is required to cancel the
Context, it shouldn't be too burdensome for them to manage the lifecycle
of the scheduler.

Require a ScheduledExecutorService to be provided to Context

---

core/src/main/java/io/grpc/internal/ServerCallImpl.java
core/src/test/java/io/grpc/internal/ServerCallImplTest.java

Context was being closed when the server was closing the RPC, but not if
the client cancelled.

Cancel server context when call is cancelled

---

protobuf/src/main/java/io/grpc/protobuf/ProtoInputStream.java
protobuf/src/test/java/io/grpc/protobuf/ProtoUtilsTest.java

Fix NPE in ProtoInputStream.drainTo

---

examples/src/generated/main/java/io/grpc/examples/helloworld/HelloReply.java
examples/src/generated/main/java/io/grpc/examples/helloworld/HelloRequest.java
examples/src/generated/main/java/io/grpc/examples/helloworld/HelloWorldProto.java
examples/src/generated/main/java/io/grpc/examples/routeguide/RouteGuideProto.java
examples/src/main/proto/helloworld.proto
examples/src/main/proto/route_guide.proto

Partially synchronized route_guide, and revert one of the earlier changes to helloworld's outer_classname.
More details in each commit message.

A few more example proto tweaks

---

core/src/main/java/io/grpc/inprocess/InProcessTransport.java

Fixes #875 
This is the first commit split out of #1397. Since #1397 is so large and has been introducing flakes, it seems unlikely to committed for 0.13. However, this fix is much smaller to review and would be good to have in for 0.13.

Fix InProcessTransport to call onReady

---

netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java

Its possible to reference the NTF, but not call it!

d'oh, really raise the visibility

---

README.md

Maven protoc plugin has a new name and is on Maven Central

---

interop-testing/src/test/java/io/grpc/testing/integration/CascadingTest.java

Added some integration tests for cascading cancellation

Add cascading cancellation tests

---

interop-testing/src/test/java/io/grpc/testing/integration/CascadingTest.java

Fix flakiness in Cascading cancellation tests

---

SECURITY.md
build.gradle

This reverts commit 17515364105a28b5698062534322749a04c22fd1.
It causes an java.lang.AbstractMethodError

Revert "Update to latest tcnative release"

---

core/src/main/java/io/grpc/internal/TransportSet.java

Most of the time it is just feeling like logspam.
Fixes #1439

Decrease log verbosity for transport status changes

---

RELEASING.md
android-interop-testing/app/build.gradle
build.gradle

Each commit is intended to be reviewed independently.

Release commits for v0.13.1 + backported comments to make sed work

---

core/src/main/java/io/grpc/internal/DelayedClientTransport.java
core/src/main/java/io/grpc/internal/DelayedStream.java
core/src/main/java/io/grpc/internal/SingleTransportChannel.java
core/src/test/java/io/grpc/internal/DelayedStreamTest.java

@carl-mastrangelo, FYI, this fixes a bug in my authority change

Fix bugs and improvements found by static analyser

---

core/src/main/java/io/grpc/internal/AbstractClientStream.java
core/src/main/java/io/grpc/internal/ClientStream.java
core/src/main/java/io/grpc/internal/DelayedClientTransport.java
core/src/main/java/io/grpc/internal/DelayedStream.java
core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
core/src/test/java/io/grpc/internal/ClientCallImplTest.java
core/src/test/java/io/grpc/internal/DelayedStreamTest.java
netty/src/main/java/io/grpc/netty/CancelClientStreamCommand.java

DelayedClientTransport.PendingStream will override cancel(), which has a
clearer semantic.

Merge DelayedStream's setError() into cancel()

---

core/src/main/java/io/grpc/internal/ClientCallImpl.java

Sometimes, (somehow?) the exceptions that occur in ClientCallImpl don't get printed out properly.  This change adds the thrown exception to the cancelled status that gets bubbled back up to the Client Call listener.

Add more log into for cancellation

---

interop-testing/src/test/java/io/grpc/testing/integration/TlsTest.java

Add more debug output in TlsTest

---

core/src/main/java/io/grpc/inprocess/InProcessTransport.java
core/src/main/java/io/grpc/internal/DelayedClientTransport.java
core/src/main/java/io/grpc/internal/ManagedClientTransport.java
netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java
netty/src/main/java/io/grpc/netty/GracefulCloseCommand.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyClientStream.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/main/java/io/grpc/netty/Utils.java
netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java

The backport itself was trivial, but it is a lot bigger than I would have hoped. Sending this out for discussion. I think I'm leaning toward not backporting this work just because of its size.

Backport netty transportshutdown

---

grpclb/src/generated/main/java/io/grpc/grpclb/LoadBalancerProto.java
grpclb/src/generated/main/java/io/grpc/grpclb/Server.java
grpclb/src/generated/main/java/io/grpc/grpclb/ServerOrBuilder.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
grpclb/src/main/proto/load_balancer.proto
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

Use bytes instead of a string for IP address.

---

SECURITY.md

Remove last vestiges of ChannelImpl/ServerImpl from security doc

---

all/build.gradle

Include sources for all files in 'fat' binary jar

---

stub/src/test/java/io/grpc/stub/AbstractStubTest.java

It got an error when built internally.

Add RunWith annotation to AbstractStubTest.

---

interop-testing/src/test/java/io/grpc/stub/StubConfigTest.java

Fix flaky deadline test

---

core/src/main/java/io/grpc/DnsNameResolver.java
core/src/main/java/io/grpc/DnsNameResolverFactory.java
core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/test/java/io/grpc/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/FakeClock.java

Retry DNS resolution when there is an error.

---

core/src/test/java/io/grpc/CallOptionsTest.java
core/src/test/java/io/grpc/DeadlineTest.java

Remove Flakes caused by assertEquals

---

core/src/main/java/io/grpc/Metadata.java

For #1460
Random other minor cleanups </boyscout>  Feel free to push back on any changes.

Remove some array copies in metadata

---

build.gradle

Fix POM connection from svn to git

---

netty/src/main/java/io/grpc/netty/NettyClientHandler.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

Add rst error detail in OkHttp

---

benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
compiler/src/java_plugin/cpp/java_generator.cpp
compiler/src/test/golden/TestService.java.txt
compiler/src/testLite/golden/TestService.java.txt
compiler/src/testNano/golden/TestService.java.txt
examples/src/generated/main/grpc/io/grpc/examples/helloworld/GreeterGrpc.java
examples/src/generated/main/grpc/io/grpc/examples/routeguide/RouteGuideGrpc.java
grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
stub/src/main/java/io/grpc/stub/ServerCalls.java
stub/src/test/java/io/grpc/stub/ServerCallsTest.java

Addresses #1469 and continues development started and discussed in https://github.com/grpc/grpc-java/pull/1634
cc @ejona86 @carl-mastrangelo
cc @jhump @ericzundel

Provide base methods for Abstract stub

---

build.gradle

Update Netty dependency to 4.1.0.CR7

---

core/src/main/java/io/grpc/Server.java
core/src/main/java/io/grpc/inprocess/InProcessServer.java
core/src/main/java/io/grpc/internal/ServerImpl.java
core/src/test/java/io/grpc/inprocess/InProcessServerTest.java
core/src/test/java/io/grpc/internal/ServerImplTest.java
netty/src/main/java/io/grpc/netty/NettyServer.java
netty/src/test/java/io/grpc/netty/NettyServerTest.java

Add getting the port out of a Server

---

protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java
protobuf-lite/src/test/java/io/grpc/protobuf/lite/ProtoLiteUtilsTest.java
protobuf/src/main/java/io/grpc/protobuf/ProtoUtils.java

Addresses #1678
+cc: @louiscryan

Allow use of a global ExtensionRegistry

---

benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadWorker.java

After these changes the Java qps worker seems to work fine.

Adjust Java qps worker to work well with run_performance_tests.py

---

benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadWorker.java

Do changes from https://github.com/grpc/grpc-java/pull/1686 properly.
@louiscryan  FYI.

Fix QpsWorker shutdown properly

---

core/src/main/java/io/grpc/internal/MessageFramer.java

Fixes:
* Catch case where buffer allocator returns a 0 length buffer.  In the case there are two writes to the OutputStream, one of size 0, and then of size 1, the while loop could potentially spin forever. 
* Grow the internal buffer much faster.  If a small write is followed by a much bigger write, allocate as much as the bigger write, rather than growing exponentially.  This change should still degrade to exponential growth after enough writes.
* Add some finals, everyone likes finals.
cc: @nmittler

Fix some corner cases with MessageFramer

---

auth/src/test/java/io/grpc/auth/ClientAuthInterceptorTests.java
benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadClient.java
core/src/main/java/io/grpc/ClientCall.java
core/src/main/java/io/grpc/ClientInterceptors.java
core/src/main/java/io/grpc/ForwardingClientCall.java
core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/test/java/io/grpc/ClientInterceptorsTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
stub/src/main/java/io/grpc/stub/ClientCalls.java
stub/src/test/java/io/grpc/stub/ClientCallsTest.java

Allow passing cancellation details to ClientCall.cancel()

---

interop-testing/src/test/java/io/grpc/testing/integration/StressTestClientTest.java

Fix race in StressTestClientTest.gaugesShouldBeExported(). Fixes #1695

---

core/src/test/java/io/grpc/internal/ClientCallImplTest.java
testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java

I can't reproduce the bug reported in #1682 ... can you confirm? Am I missing something?

Add tests for call.cancel() from within messageRead

---

core/src/main/java/io/grpc/internal/GrpcUtil.java

Try to use ScheduledThreadpoolExecutor

---

core/src/main/java/io/grpc/inprocess/InProcessTransport.java
testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java

Strip cause from InProcessTransport between client and server. 

---

core/src/main/java/io/grpc/Status.java

remove the dependency on Guava's Throwables.getCausalChain #1663

---

RELEASING.md

@carl-mastrangelo, do you think this works better?

Disable parallel with argument for greater ease

---

SECURITY.md
benchmarks/build.gradle
build.gradle
interop-testing/build.gradle
netty/build.gradle

use Jetty ALPN agent instead of Jetty ALPN #1497

use Jetty ALPN agent instead of Jetty ALPN

---

netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java

netty: call transportShutdown immediately on ID exhaustion

---

core/src/test/java/io/grpc/ContextsTest.java

core: Add unit test for Contexts.interceptCall

---

core/src/main/java/io/grpc/Status.java

Addresses #1722. Both options are in my opinion helpful (and I would make use of them now, if they'd be available, in my app's code) but I don't have strong opinions.

Make Code.status() public, add Status#fromCode()

---

okhttp/src/main/java/io/grpc/okhttp/Headers.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java

Followup to https://github.com/grpc/grpc-java/pull/1858

okhttp: generate user agent once for whole transport

---

core/src/main/java/io/grpc/CallOptions.java
core/src/main/java/io/grpc/Deadline.java
stub/src/main/java/io/grpc/stub/AbstractStub.java

core: Promote Deadline API to stable

---

benchmarks/src/main/java/io/grpc/benchmarks/qps/ClientConfiguration.java

Broken by a7049bca3b820c503f1f704288033222980c5485

benchmarks: honor transport in AsyncClient

---

core/src/main/java/io/grpc/ManagedChannel.java
core/src/main/java/io/grpc/inprocess/InProcessTransport.java
core/src/main/java/io/grpc/internal/DelayedClientTransport.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/ManagedClientTransport.java
core/src/main/java/io/grpc/internal/ServerImpl.java
core/src/main/java/io/grpc/internal/TransportSet.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTransportManagerTest.java
core/src/test/java/io/grpc/internal/ServerImplTest.java
netty/src/main/java/io/grpc/netty/ForcefulCloseCommand.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/netty/NettyServerTransport.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java

Implement shutdownNow

---

core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java

#1896 
This is the actual test for #1883

core: A missed-out test for #1896

---

SECURITY.md
build.gradle

This is dependent on #1903 (and includes those changes).

netty: Use uber boringssl jar

---

core/src/main/java/io/grpc/CallOptions.java
core/src/main/java/io/grpc/internal/DelayedClientTransport.java
core/src/main/java/io/grpc/internal/TransportSet.java
core/src/test/java/io/grpc/CallOptionsTest.java
core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTransportManagerTest.java
core/src/test/java/io/grpc/internal/TransportSetTest.java

implements `Swap to 'fail fast' and 'ignore connectivity' behavior` #1759

core: fail fast implementation

---

examples/src/main/java/io/grpc/examples/helloworld/HelloJsonClient.java
examples/src/main/java/io/grpc/examples/helloworld/HelloJsonServer.java

examples: make JSON code more obviously advanced

---

core/src/main/java/io/grpc/internal/DelayedClientTransport.java
core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java
core/src/test/java/io/grpc/internal/TransportSetTest.java

Don't wrap the Status when a fail-fast RPC is already queued when the
transport fails, since that Status is directly responsible for the
failing of the RPC. For future fail-fast RPCs, use the saved status as a
cause to make debugging easier.
This came out of #1330, where the unnecessary nesting of the status
codes just added noise.
@buchgr, FYI

core: Improve fail fast status messages

---

benchmarks/src/jmh/java/io/grpc/netty/HeadersBenchmark.java

Initial numbers so we have some reference:
```
Benchmark                              (headerCount)    Mode     Cnt     Score    Error  Units
HeadersBenchmark.convertClientHeaders              1  sample  108722   111.912 ±  1.751  ns/op
HeadersBenchmark.convertClientHeaders              5  sample  165053   268.991 ±  1.776  ns/op
HeadersBenchmark.convertClientHeaders             10  sample  188272   441.860 ±  2.531  ns/op
HeadersBenchmark.convertClientHeaders             20  sample  190869   841.065 ± 31.847  ns/op
HeadersBenchmark.convertServerHeaders              1  sample  126578   110.958 ±  1.604  ns/op
HeadersBenchmark.convertServerHeaders              5  sample  179316   241.991 ±  2.006  ns/op
HeadersBenchmark.convertServerHeaders             10  sample  103436   406.329 ±  3.114 …
```

benchmarks: add a header encoding benchmark

---

core/src/main/java/io/grpc/ServerCallHandler.java

Make ServerCallHandler non-experimental.

---

stub/src/test/java/io/grpc/stub/ClientCallsTest.java

If the timoutout expires, the test will almost certainly fail now due to
responses not matching expected responses, but it isn't as obvious why
the test fails. Swapping to ArrayList prints the entire list when they
don't match, which also makes it easier to diagnose.
This is, in part, to help diagnose #1932

stub: Improve ClientCall test to fail more obviously

---

android-interop-testing/app/build.gradle
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
build.gradle
compiler/src/test/golden/TestService.java.txt
compiler/src/testLite/golden/TestService.java.txt
compiler/src/testNano/golden/TestService.java.txt
examples/android/app/build.gradle
examples/src/generated/main/grpc/io/grpc/examples/helloworld/GreeterGrpc.java
examples/src/generated/main/grpc/io/grpc/examples/routeguide/RouteGuideGrpc.java
grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java

The two commits will remain separate.

Commits for 0.14.1 release

---

core/src/main/java/io/grpc/BindableService.java
core/src/main/java/io/grpc/ServerBuilder.java
core/src/main/java/io/grpc/ServerInterceptors.java

core: make BindableService no longer experimental.

---

core/src/main/java/io/grpc/ServerInterceptor.java

core:  make ServerInterceptor non experimental

---

core/src/main/java/io/grpc/ClientCall.java

doc: add flow-control example to ClientCall javadoc.

---

core/src/main/java/io/grpc/Context.java
core/src/main/java/io/grpc/Contexts.java

core: mark Context as not experimental

---

examples/src/main/java/io/grpc/examples/advanced/HelloJsonClient.java
examples/src/main/java/io/grpc/examples/advanced/HelloJsonServer.java

examples: move json server and client to advanced package

---

core/src/main/java/io/grpc/package-info.java

core: add package level javadoc.

---

core/src/main/java/io/grpc/Contexts.java

core: update issue for Contexts experimental status

---

core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/test/java/io/grpc/internal/ClientCallImplTest.java

core: fix race with exception in onMessage

---

stub/src/main/java/io/grpc/stub/StreamObserver.java

core: clarify StreamObserver documentation

---

examples/android/app/build.gradle
examples/android/app/proguard-rules.pro
examples/android/app/src/main/java/io/grpc/helloworldexample/HelloworldActivity.java

examples: Android example is now using lite

---

auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTests.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

JWT needs less configuration and zero round-trips to initialize.
Fixes #785

auth: Promote OAuth2 service accounts to JWT

---

examples/src/main/java/io/grpc/examples/errorhandling/ErrorHandlingClient.java

examples: Avoid deprecated generated class

---

android-interop-testing/app/build.gradle
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
build.gradle
compiler/src/test/golden/TestService.java.txt
compiler/src/testLite/golden/TestService.java.txt
compiler/src/testNano/golden/TestService.java.txt
examples/android/app/build.gradle
examples/src/generated/main/grpc/io/grpc/examples/helloworld/GreeterGrpc.java
examples/src/generated/main/grpc/io/grpc/examples/routeguide/RouteGuideGrpc.java
grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java

Start 1.0.0 development cycle

---

android-interop-testing/app/build.gradle
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
build.gradle
compiler/src/test/golden/TestService.java.txt
compiler/src/testLite/golden/TestService.java.txt
compiler/src/testNano/golden/TestService.java.txt
examples/android/app/build.gradle
examples/src/generated/main/grpc/io/grpc/examples/helloworld/GreeterGrpc.java
examples/src/generated/main/grpc/io/grpc/examples/routeguide/RouteGuideGrpc.java
grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java

This will be made on the v0.15.x branch and will retain both commits. Please review each commit individually.

Release 0.15.0

---

netty/src/main/java/io/grpc/netty/WriteQueue.java
netty/src/test/java/io/grpc/netty/WriteQueueTest.java

The issue was found and reported by @blakearnold. Thank you!

Fix wrong use of checkNotNull in WriteQueue.

---

testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java

- See #1330 for details.
- Also, Netty 4.1.2.Final comes with additional information where
a (usually statically cached) ClosedChannelException was triggered [1]
[1] https://github.com/netty/netty@e845670#diff-8c9a7d1d9b0fdb6c5aef2794d05a9f88

netty: add logging to find cause of ClosedChannelException

---

core/src/main/java/io/grpc/internal/ServerCallImpl.java

Metadata has been passed to the application. The application may be
modifying Metadata concurrently, so we must not access Metadata after
that point.
Fixes #1947

core: Save accept encoding since Metadata is not thread-safe

---

.travis.yml
build.gradle
buildscripts/jenkins-pre.bat
core/src/test/java/io/grpc/internal/KeepAliveManagerTest.java

I intend to keep the two commits separate. One fixes the current warnings and the next tries to keep them gone.
CC @zsurocking

travis,jenkins: Fail build if javac emits warnings

---

android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/TesterOkHttpChannelBuilder.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceServer.java

interop: Bump maxMessageSize for Android testing

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/ServerImpl.java

This splits out the most important parts of #2032, in hopes of allowing forward progress without blocking the discussion.

core: Fix ErrorProne errors

---

core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/main/java/io/grpc/internal/SharedResourceHolder.java
interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelProvider.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/third_party/okhttp/java/io/grpc/okhttp/internal/Platform.java
testing/src/main/java/io/grpc/testing/TestUtils.java

@ejona86 
@zsurocking 
AppEngine may support Conscrypt at some point which would allow ALPN to function. This PR roughly covers what is needed to make GRPC clients work on AppEngine

Make the OkHTTP transport AppEngine friendly. 

---

netty/src/main/java/io/grpc/netty/WriteQueue.java
netty/src/test/java/io/grpc/netty/WriteQueueTest.java

WriteQueue uses LinkedBlockingQueue, which has stronger synchronization
semantics than we need.  It also requires that we batch reads from it
in order to get reasonable performance.  After profiling the delay
between writing to LBQ and reading from it, there was a ~10us delay.
This change switches to using ConcurrentLinkedQueue as the underlying
queue, and removes the batching (reads).  Using CLQ with batching is
slightly slower.
Benchmarks show favorable numbers for both latency and throughput.
Each of the following results were run several times:
```
Before:
Benchmark                         (direct)  (transport)    Mode     Cnt       Score     Error  Units
TransportBenchmark.unaryCall1024      true        NETTY  sample  321575  124185.027 ± 406.112  ns/op …
```

netty: reduce contention in WriteQueue

---

benchmarks/src/main/java/io/grpc/benchmarks/Utils.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
interop-testing/src/test/java/io/grpc/testing/integration/TlsTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
testing/src/main/java/io/grpc/testing/TestUtils.java

Cleanup redundant API un TestUtils
Fix TlsTest to be ignored on JKD7 correctly
@ejona86 PTAL

Fix selection of security Provider to conscruct SSLContext

---

stub/src/main/java/io/grpc/stub/ClientCalls.java
stub/src/test/java/io/grpc/stub/ClientCallsTest.java

Ensure that trailers are not lost when making blocking calls.

---

okhttp/third_party/okhttp/java/io/grpc/okhttp/internal/Platform.java

On Android choose from the installed providers preferring newer more capable providers over older 
ones.
On AppEngine force the use of conscrypt even if it is not installed
@ejona86

Revise security provider selection for android

---

netty/src/test/java/io/grpc/netty/AbstractHttp2HeadersTest.java

This increases line coverage by 1.3%.

netty: Add test for AbstractHttp2Headers

---

benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
compiler/src/java_plugin/cpp/java_generator.cpp
grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java

forgot to make Stub final class...

compiler: make Stub final class

---

core/src/main/java/io/grpc/internal/SharedResourceHolder.java

This change avoid executors backed by request-scoped threads from becoming
zombies
See
https://cloud.google.com/appengine/docs/java/javadoc/com/google/appengine/api/ThreadManager.html#currentRequestThreadFactory--
for context on request-scoped threads.
If an executor is created with a thread from the AppEngine request-scoped thread factory then when the request ends the Executor is still retained even if the only thread it had to do work is now dead
@ejona86

Force the immediate release of reference counted resources on AppEngine

---

README.md

Since we have released 0.15.0, we should update the README.md.

update grpc version to 0.15.0 and protoc to 3.0.0-beta-3

---

core/src/main/java/io/grpc/internal/ClientCallImpl.java

core: Log a warning in ClientCall.cancel if no detail is provided.

---

interop-testing/src/test/java/io/grpc/testing/integration/CascadingTest.java

The value of nodeCount depended on deadlines expiring after the chain
was constructed. This is effectively the same as using Thread.sleep()
and would commonly fail if the machine was under load.
Instead of checking nodeCount after the deadline expires, we now wait
for the chain to be constructed and then cancel the RPC. This also
ensures that the cancel propagates instead of each hop just enforcing
the deadline. As a bonus, this also reduces test execution time by one
second. A new test was added for deadline propagation.
Fixes #1852

interop: Fix flake in cascading test due to sleeps

---

README.md

This is basically a continuation of 4b17a2e31
I will back-port this to v1.0.x
CC @david-cao

Slightly encourage more use of lite, instead of nano

---

examples/android/routeguide/app/build.gradle

Also add back the deleted .gitignore to helloworld example.

Change routeguide example to use proto 3.0.0

---

benchmarks/src/main/java/io/grpc/benchmarks/Utils.java
benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncServer.java

The performance of this is very sensitive to the parallelism of the pool.  This PR is more exploratory than anything else.  It's main purpose is to see how well the unconstrained QPS benchmark runs.

benchmarks: use a fork-join pool to reduce executor contention

---

benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadServer.java

The LoadClient was okay since it reuses Utils, but LoadServer missed out.  Add FJP in there too.

benchmarks: add fork join pool executor to load server too

---

core/src/main/java/io/grpc/internal/TransportSet.java

core: fix a deadlock in TransportSet.

---

examples/android/helloworld/app/src/main/java/io/grpc/helloworldexample/HelloworldActivity.java
examples/android/helloworld/app/src/main/res/layout/activity_helloworld.xml

Show the full stacktrace when error happens and make the result text view scrollable.

Update android example.

---

README.md
android-interop-testing/build.gradle
build.gradle
core/src/main/java/io/grpc/internal/TransportSet.java
examples/android/README.md
examples/android/helloworld/app/build.gradle
examples/android/helloworld/app/src/main/java/io/grpc/helloworldexample/HelloworldActivity.java
examples/android/helloworld/app/src/main/res/layout/activity_helloworld.xml
examples/android/helloworld/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/routeguide/build.gradle
examples/build.gradle

Most commits required no changes. But do take look at the deadlock commit, as I had to modify it to compile without 7d464fc.

Cherry-picks from master to v1.0.x

---

README.md
android-interop-testing/app/build.gradle
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
build.gradle
compiler/src/test/golden/TestService.java.txt
compiler/src/testLite/golden/TestService.java.txt
compiler/src/testNano/golden/TestService.java.txt
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/build.gradle
examples/pom.xml
grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java

The three commits will remain separate.

Release v1.0.0

---

interop-testing/src/test/java/io/grpc/testing/integration/ProxyTest.java
interop-testing/src/test/java/io/grpc/testing/integration/TrafficControlProxy.java

interop-testing: Remove hard-coded ports in ProxyTest

---

core/src/main/java/io/grpc/MethodDescriptor.java
core/src/test/java/io/grpc/MethodDescriptorTest.java

Usually it should be called by code generators

Add a new option for caching support

---

benchmarks/build.gradle

This includes a "pauses" profiler.

benchmarks: upgrade to jmh 1.14

---

core/src/main/java/io/grpc/PickFirstBalancerFactory.java

core: Make PickFirst.pick's fast path lock-free

---

thrift/src/main/java/io/grpc/thrift/MessageFactory.java
thrift/src/main/java/io/grpc/thrift/ThriftUtils.java

New APIs need a stablization period.

Mark Thrift experimental

---

README.md
android-interop-testing/app/build.gradle
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
build.gradle
compiler/src/test/golden/TestService.java.txt
compiler/src/testLite/golden/TestService.java.txt
compiler/src/testNano/golden/TestService.java.txt
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/build.gradle
examples/pom.xml
grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java

Review each commit individually.

Release 1.0.1

---

protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java

Alternate implementation of https://github.com/grpc/grpc-java/pull/2288

protobuf: cache temp buffers

---

netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java
netty/src/main/java/io/grpc/netty/GrpcHttp2ConnectionHandler.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
netty/src/main/java/io/grpc/netty/Utils.java
netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java

Create generic interface for listening on protocol negotiation completion to pass arbitrary attributes.
Addresses #1556.

Refactor passing down ssl session

---

README.md

This is a cherry-pick of the commit just before v1.0.1 onto master, without any manual modifications.

Update README to reference 1.0.1

---

netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersDecoder.java
netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersDecoderTest.java

Binary header values are printed in their base64 encoded form.
The GrpcHttpOutboundHeaders, as mentioned in the issue, don't seem to be affected by this regression. The toString() method seems fine.

netty: Add toString() to GrpcHttp2InboundHeaders. Fixes #2341.

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java

core: Use grace period to avoid exitIdleMode in fast path

---

run-test-client.sh
run-test-server.sh

interop-testing: -PskipCodegen requires =true

---

.github/ISSUE_TEMPLATE

github: add an issue template

---

examples/README.md
examples/build.gradle
examples/pom.xml
examples/src/main/java/io/grpc/examples/advanced/HelloJsonServer.java
examples/src/main/java/io/grpc/examples/errorhandling/DetailErrorSample.java
examples/src/main/java/io/grpc/examples/errorhandling/ErrorHandlingClient.java
examples/src/main/java/io/grpc/examples/header/HeaderClientInterceptor.java
examples/src/main/java/io/grpc/examples/header/HeaderServerInterceptor.java
examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java
examples/src/main/java/io/grpc/examples/helloworld/HelloWorldServer.java
examples/src/main/java/io/grpc/examples/routeguide/RouteGuideClient.java
examples/src/main/java/io/grpc/examples/routeguide/RouteGuideServer.java
examples/src/test/java/io/grpc/examples/header/HeaderClientInterceptorTest.java
examples/src/test/java/io/grpc/examples/header/HeaderServerInterceptorTest.java
examples/src/test/java/io/grpc/examples/helloworld/HelloWorldClientTest.java
examples/src/test/java/io/grpc/examples/helloworld/HelloWorldServerTest.java
examples/src/test/java/io/grpc/examples/routeguide/RouteGuideClientTest.java
examples/src/test/java/io/grpc/examples/routeguide/RouteGuideServerTest.java

Demonstrate unit testing gRPC clients and servers with `InProcessTransport`.

examples: unit test examples for users

---

benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadServer.java
core/src/main/java/io/grpc/ManagedChannelProvider.java
core/src/main/java/io/grpc/NameResolverProvider.java
core/src/main/java/io/grpc/Status.java
core/src/main/java/io/grpc/internal/CompositeReadableBuffer.java
core/src/main/java/io/grpc/internal/ServerImpl.java
core/src/test/java/io/grpc/ResolvedServerInfoTest.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java

cleanup error-prone and unused code/code-path

all: cleanup - errorprone, unused

---

core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/main/java/io/grpc/internal/ServerCallImpl.java
core/src/test/java/io/grpc/internal/ClientCallImplTest.java

- s/IMPLEMENTATION_VERION/IMPLEMENTATION_VERSION
- s/ACCEPT_ENCODING_SPLITER/ACCEPT_ENCODING_SPLITTER

core: Fix typos in GrpcUtil

---

netty/src/main/java/io/grpc/netty/NettyClientHandler.java

Just a quick dead code removal

Remove deadcode

---

README.md

This takes users into the common gitter chat room.

Add gitter chat icon to the README.md file

---

README.md

docs: Place all badges together

---

context/src/main/java/io/grpc/Context.java

http://errorprone.info/bugpattern/ClassNewInstance

context: Fix ErrorProne ClassNewInstance

---

benchmarks/README.md

Update param name for saving histograms

---

core/src/main/java/io/grpc/internal/ChannelExecutor.java
core/src/test/java/io/grpc/internal/ChannelExecutorTest.java

Dedicated for mutating states of ManagedChannelImpl, InternalSubchannel
and LoadBalancer.

core: thread-less ChannelExecutor.

---

netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java

It exsits in OkHttp transport already, this PR adds netty support.

Add support for keepalive in netty transport

---

core/src/main/java/io/grpc/ManagedChannelBuilder.java

core: make forTarget(String) non-experimental

---

core/src/main/java/io/grpc/internal/DelayedClientTransport2.java

doc: update javadocs in DelayedClientTransport2.

---

build.gradle
core/src/main/java/io/grpc/internal/LogExceptionRunnable.java
core/src/main/java/io/grpc/internal/ServerCallImpl.java
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

Still compatible with 1.6, v21 will not be.
cc: @ejona86

all: update to guava 20

---

core/src/main/java/io/grpc/LoadBalancer2.java

doc: more guidelines for LoadBalancer2 implementations.

---

netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java

Not to expose dependency of `io.netty.handler.ssl.SslContext` when implementing `TransportCreationParamsFilter`
Change the `TransportCreationParamsFilter` API
````
ProtocolNegotiator getProtocolNegotiator(NegotiationType negotiationType, SslContext sslContext);
````
into
````
ProtocolNegotiator getProtocolNegotiator();
````

netty: no add_dep io.netty.handler.ssl.SslContext

---

context/src/main/java/io/grpc/Context.java

This is an alternative to #2543 and it doesn't introduce volatile usage.

core: remove a benign data race.

---

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/main/java/io/grpc/testing/integration/TestCases.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceServer.java
interop-testing/src/main/java/io/grpc/testing/integration/Util.java
interop-testing/src/test/java/io/grpc/testing/integration/TestCasesTest.java
testing/src/main/java/io/grpc/testing/TestUtils.java

This implements the custom_metadata interop test (grpc/grpc#8481)

interop-testing: Add custom_metadata interop test

---

testing/src/main/java/io/grpc/testing/TestUtils.java

Also add forgotten close() for the InputStream.

testing: Remove accidental cast to char in file IO

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl2.java

They have already been added to ManagedChannelImpl2.
Resolves #2299

core: more logs in ManagedChannelImpl.

---

README.md
examples/README.md
examples/android/README.md

docs: add links to examples and tutorials.

---

core/src/main/java/io/grpc/util/RoundRobinLoadBalancerFactory2.java
core/src/test/java/io/grpc/util/RoundRobinLoadBalancer2Test.java

A bunch of code clean up in `RoundRobinLoadBalancer2`
/cc @kkaneda  @zhangkun83

RoundRobinLoadBalancer minor cleanups

---

auth/src/main/java/io/grpc/auth/ClientAuthInterceptor.java
core/src/main/java/io/grpc/CallCredentials.java

docs: fix deprecation reference in ClientAuthInterceptor.

---

build.gradle

thrift: disable export of artifact

---

core/src/main/java/io/grpc/internal/ServerImpl.java
core/src/test/java/io/grpc/internal/ServerImplTest.java

core: cancel RPC when exception in server onReady

---

netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java

core: pass down addr to which client is connected

---

benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
compiler/src/java_plugin/cpp/java_generator.cpp
compiler/src/test/golden/TestService.java.txt
compiler/src/testLite/golden/TestService.java.txt
compiler/src/testNano/golden/TestService.java.txt
core/src/main/java/io/grpc/ServiceDescriptor.java
core/src/test/java/io/grpc/ServiceDescriptorTest.java
grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java
services/src/generated/main/grpc/io/grpc/reflection/v1alpha/ServerReflectionGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/AnotherDynamicServiceGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/DynamicServiceGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/ReflectableServiceGrpc.java
services/src/main/java/io/grpc/protobuf/service/ProtoReflectionService.java
testing-proto/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
testing-proto/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
testing-proto/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
testing-proto/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java

Fixes: #2636
Also fixes a minor bug where methods could have been null inside the method list.

core: make ServiceDescriptor use the Builder pattern

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java

For https://github.com/netty/netty/issues/6296

netty: work around netty bug when RPCs may be reset early

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/netty/ProtocolNegotiator.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java

implements the comments mentioned in #2619

netty: call transportReady in handleProtocolNegotiationCompleted

---

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

Mockito is restricted on AppEngine.

Replace Mockito with StreamObserver for several interop tests

---

all/build.gradle

all: remove thrift from grpc-all export

---

README.md
android-interop-testing/app/build.gradle
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
build.gradle
compiler/src/test/golden/TestService.java.txt
compiler/src/testLite/golden/TestService.java.txt
compiler/src/testNano/golden/TestService.java.txt
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/build.gradle
examples/pom.xml
examples/thrift/build.gradle
grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java
services/src/generated/main/grpc/io/grpc/reflection/v1alpha/ServerReflectionGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/AnotherDynamicServiceGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/DynamicServiceGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/ReflectableServiceGrpc.java
testing-proto/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
testing-proto/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
testing-proto/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
testing-proto/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java

3 commits, per the release docs.

Update to 1.1.2

---

core/src/main/java/io/grpc/ManagedChannelBuilder.java
core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java

core: switch to LBv2 as the default.

---

netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java

Closes #2350
cc @buchgr @ejona86

netty: include SETTINGS_MAX_HEADER_LIST_SIZE in SETTINGS

---

netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java

Backports #2729
cc @ejona86 @bobwenx

netty: Fix NPE in NettyClientTransport (v1.1 backport)

---

core/src/main/java/io/grpc/LoadBalancer.java

Subchannel can be nullable, add annotation for consitency

core: add @nullable annotation

---

CONTRIBUTING.md

Copied instructions by @dapengzhang0 posted in #2728
cc @ejona86

Add instructions about running tests in IJ w/ alpn agent

---

core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

The class and method referenced in it were removed recently

doc: remove irrelevant java doc

---

CONTRIBUTING.md

We probably want to have more there in the future, but it's a good start.
cc @carl-mastrangelo

core: update contributing guidelines w/ pr/commit conventions

---

core/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/PickFirstBalancerFactory.java
core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/main/java/io/grpc/internal/DelayedClientTransport.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/OobChannel.java
core/src/main/java/io/grpc/internal/PickSubchannelArgsImpl.java
core/src/main/java/io/grpc/util/RoundRobinLoadBalancerFactory.java
core/src/test/java/io/grpc/PickFirstLoadBalancerTest.java
core/src/test/java/io/grpc/internal/ClientCallImplTest.java
core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

This will allow adding new arguments passed to pickSubchannel without significant API changes in core LB API in the future.
Addresses #2737
cc @ejona86 @zhangkun83

core: introduce PickSubchannelArgs

---

android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/InteropTester.java

fix JavaStyle and ErrorProne warnings found in internal weekly import

android-interop-testing: fix lint

---

core/src/main/java/io/grpc/CallOptions.java
core/src/main/java/io/grpc/LoadBalancer.java
core/src/test/java/io/grpc/CallOptionsTest.java
core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java

Addresses #2738
cc @ejona86 @zhangkun83

core: use withOptions instead of withAffinity

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java

This reverts commit b753231590cd81505aa3694ba6c70137b1aa8877.
@kpayson64 FYI this is being reverted since it should have been made to the master branch instead of v1.2.x

okhttp: revert okhttp: Add restricted AppEngine SSL setup (#2795)

---

core/src/main/java/io/grpc/internal/KeepAliveManager.java
core/src/test/java/io/grpc/internal/KeepAliveManagerTest.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java

Nothing is using this yet, but it will be used on both client and
server.

core: Support keepalive even when transport is idle

---

documentation/server-reflection-tutorial.md

This updates the tutorial to reflect the new package and factory method for `ProtoReflectionService`.

documentation: update path/method for reflection

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java

okhttp: Add restricted AppEngine SSL setup

---

core/src/main/java/io/grpc/ClientInterceptor.java

doc: suggest against overriding Context in ClientInterceptor

---

build.gradle

Per the recommendation here:
http://mrhaki.blogspot.com/2016/11/gradle-goodness-replacing-operator-for.html

all: fix gradle nag for deprecated leftshift operator

---

benchmarks/src/jmh/java/io/grpc/internal/SerializingExecutorBenchmark.java
core/src/main/java/io/grpc/internal/SerializingExecutor.java
core/src/test/java/io/grpc/internal/SerializingExecutorTest.java

This is an alternative implementation of #2192

core: make SerializingExecutor lockless

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/netty/NettyServerTransport.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java

use KeepAliveManager in NettyServerHandler

netty: Server side keep alive

---

core/src/main/java/io/grpc/internal/FailingClientStream.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java

Something 'very bad' has happened, but without grpc propagating the
cause from the Future it is very difficult to figure out what.
Fixes #2296

netty: Handle channel creation failure

---

core/src/main/java/io/grpc/ManagedChannel.java

doc: document that channel state is not implemented.

---

core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/main/java/io/grpc/internal/KeepAliveManager.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java

Each commit can be reviewed individually. I will merge them separately.

Permissive client keepalive

---

netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java

netty: ignore flaky max connection age tests

---

core/src/main/java/io/grpc/MethodDescriptor.java

core: make MethodDescriptor.Builder non experimental

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java

For convenience of implementing max connection idle.

netty: move connection.addListner inside constructor of NettyServerHandler

---

netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
testing/src/main/java/io/grpc/testing/TestUtils.java
testing/src/test/java/io/grpc/testing/TestUtilsTest.java

netty: fix flaky max connection age tests using sleepAtLeast

---

benchmarks/build.gradle

benchmarks: disable flag printing

---

core/src/main/java/io/grpc/internal/AtomicBackoff.java
core/src/test/java/io/grpc/internal/AtomicBackoffTest.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

Any ENHANCE_YOUR_CALM is good reason to log, but too_many_pings also
triggers increase of the keepalive time for later connections.

netty,okhttp: handle ENHANCE_YOUR_CALM and too_many_pings

---

core/src/main/java/io/grpc/internal/AtomicBackoff.java
core/src/test/java/io/grpc/internal/AtomicBackoffTest.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

Any ENHANCE_YOUR_CALM is good reason to log, but too_many_pings also
triggers increase of the keepalive time for later connections.

netty,okhttp: handle ENHANCE_YOUR_CALM and too_many_pings (backport to v1.3)

---

grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

grpclb: remove non-determinism workaround

---

core/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/PickFirstBalancerFactory.java
core/src/main/java/io/grpc/internal/InternalSubchannel.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/OobChannel.java
core/src/test/java/io/grpc/PickFirstLoadBalancerTest.java
core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

You can look at the commits separately, or together. Still missing tests.
CC @zhangkun83

Avoid reconnect in Load Balancers

---

core/src/main/java/io/grpc/Channel.java
core/src/main/java/io/grpc/ManagedChannel.java
core/src/main/java/io/grpc/ManagedChannelBuilder.java

This and previous PRs are for implementations of Channel and ManagedChannel other than the one we include.

core: clarify more origin docs for Channel

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java

netty: fix server keepalive not initialized bug

---

core/src/test/java/io/grpc/PickFirstLoadBalancerTest.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java

Each commit gives some details. Although normally changes like this are trivial, in this case they aren't, so this should be given normal attention during review.

Fixes for static checker failures

---

context/src/main/java/io/grpc/Context.java
context/src/test/java/io/grpc/ContextTest.java
core/src/main/java/io/grpc/CallOptions.java
core/src/main/java/io/grpc/CompressorRegistry.java
core/src/main/java/io/grpc/ConnectivityStateInfo.java
core/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/ManagedChannelProvider.java
core/src/main/java/io/grpc/Metadata.java
core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java

This adds / clarifies javadocs for some classes.

Minor updates to expand javadocs

---

testing/src/test/java/io/grpc/testing/GrpcServerRuleTest.java

CC @zhangkun83 @carl-mastrangelo

testing: Add missing RunWith to GrpcServerRuleTest

---

SECURITY.md

all: fix bad ref to ServerCall

---

netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java

This is a minor change setting the size of data frames sent when
interleaving RPCs.  The size was ~1024bytes previously, which
resulted in the `writev` syscalls sending many smaller chunks
before hitting the low water mark.  The end effect is larger calls
to `writev`, as seen with strace.
The effect of this is noticeable when sending a lot of data.  When
sending as many 1MB messages as possible it nearly doubles the
rate.
Before:
```
INFO: single throughput GRPC
50.0%ile Latency (in nanos):		280856575
90.0%ile Latency (in nanos):		349618175
95.0%ile Latency (in nanos):		380444671
99.0%ile Latency (in nanos):		455172095
99.9%ile Latency (in nanos):		537198591
100.0%ile Latency (in nanos):		566886399
QPS:                           346
Count:                         103984
```
After:
``` …
```

netty: increase message quantum

---

core/src/main/java/io/grpc/internal/AbstractClientStream.java
core/src/main/java/io/grpc/internal/AbstractServerStream.java
core/src/main/java/io/grpc/internal/AbstractStream.java
core/src/main/java/io/grpc/internal/Http2ClientStreamTransportState.java
core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
netty/src/main/java/io/grpc/netty/NettyClientStream.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

core: remove 2 suffix from streams

---

build.gradle

all: fix gradle file for licence type

---

.github/ISSUE_TEMPLATE
CONTRIBUTING.md

Java counterpart of  https://github.com/grpc/grpc/pull/11303.

Improve contributing.md guidelines.

---

testing/src/test/java/io/grpc/testing/GrpcServerRuleTest.java

testing: move out inner class tests in GrpcServerRuleTest

---

build.gradle
core/src/main/java/io/grpc/internal/CensusStatsModule.java
core/src/test/java/io/grpc/internal/CensusModulesTest.java

core: Bump up instrumentation_api to 0.4.3, use instrumentation-defined STATS_CONTEXT_KEY.

---

README.md

This is a cherry-pick from 1.4.x

all: update readme to point to 1.4.0

---

benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/ReportQpsScenarioServiceGrpc.java

Looks like this was overlooked earlier

benchmarks: add missing ReportQpsScenarioServiceGrpc

---

netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java

Eagerly initializing `sslContext` (https://github.com/grpc/grpc-java/pull/3060) can throw unnecessarily when `InternalNettyChannelBuilder#setDynamicTransportParamsFactory` has been used to set a transport params factory. This PR introduces `DefaultNettyTransportCreationParamsFilterFactory`, and moves the `final sslContext` member variable from `NettyTransportFactory` into `DefaultNettyTransportCreationParamsFilterFactory`. This also moves the existing nested `DynamicNettyTransportParams` class into `DefaultNettyTransportCreationParamsFilterFactory`. 
Unfortunately, the git diff here is not very helpful with seeing the code movement.
I think this is a reasonable way to re-arrange things: we only use `sslContext` if the `transportCreationParamsFilterFactory` parameter to the …

netty: move sslContext into transportCreationParamsFilterFactory

---

build.gradle
protobuf/build.gradle

This is a backport of #2965 for v1.3.x branch

build,protobuf: update google_api_protos dependency

---

buildscripts/kokoro/windows.bat
buildscripts/kokoro/windows.cfg

Using this PR to test changes for now

Make Kokoro logs less noisy

---

core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
core/src/main/java/io/grpc/internal/ServerImpl.java
core/src/test/java/io/grpc/internal/ServerImplTest.java

This is the equivalent of #3029 for server-side. Lesser gains, but still seems worthwhile.

core: Simplify ServerImpl constructor; testable Builder

---

README.md
android-interop-testing/app/build.gradle
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
build.gradle
compiler/src/test/golden/TestService.java.txt
compiler/src/testLite/golden/TestService.java.txt
compiler/src/testNano/golden/TestService.java.txt
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/build.gradle
examples/pom.xml
examples/thrift/build.gradle
grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java
services/src/generated/main/grpc/io/grpc/instrumentation/v1alpha/MonitoringGrpc.java
services/src/generated/main/grpc/io/grpc/reflection/v1alpha/ServerReflectionGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/AnotherDynamicServiceGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/DynamicServiceGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/ReflectableServiceGrpc.java
testing-proto/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
testing-proto/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
testing-proto/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
testing-proto/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java

Review each commit separately.

Release 1.3.1

---

buildscripts/kokoro/windows.bat
buildscripts/kokoro/windows.cfg

Backport: Add Kokoro files to v1.4.x

---

buildscripts/kokoro/windows.bat
buildscripts/kokoro/windows.cfg

Backport: Add Kokoro files to v1.3.x

---

buildscripts/kokoro/windows.bat
buildscripts/kokoro/windows.cfg

Backport: Add Kokoro files to v1.2.x

---

buildscripts/kokoro/windows.bat
buildscripts/kokoro/windows.cfg

Backport: Add Kokoro files to v1.1.x

---

buildscripts/kokoro/windows.bat
buildscripts/kokoro/windows.cfg

Backport: Add Kokoro files to v1.0.x

---

context/src/main/java/io/grpc/Context.java

Turns out avoiding log() alone in the static initialization is not
enough. isLoggable() can also be overridden and call back to Context.
We take a another approach, save the exception and log it outside of
the initialization block.

context: stop using logger at all in static initialization.

---

build.gradle
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

Backport of https://github.com/grpc/grpc-java/pull/3188

all,interop-testing: update google-auth-library-oauth2-http

---

buildscripts/kokoro/windows.bat

all: make Kokoro show actual Gradle results (backport)

---

README.md
RELEASING.md
build.gradle
examples/README.md
examples/android/README.md

Canonicalize URL prefixes to https://grpc.io (backport to 1.3.x)

---

README.md
RELEASING.md
build.gradle
examples/README.md
examples/android/README.md

Canonicalize URL prefixes to https://grpc.io (backport to 1.2.x)

---

README.md
RELEASING.md
build.gradle
examples/README.md
examples/android/README.md

Canonicalize URL prefixes to https://grpc.io (backport to 1.1.x)

---

stub/src/main/java/io/grpc/stub/package-info.java

cf https://github.com/grpc/grpc.github.io/issues/508

doc (minor): Uppercase Java

---

stub/src/main/java/io/grpc/stub/ServerCalls.java

This has a number of small benefits.  First, it makes stack traces
easier to read.  For example:
Old class names:
```
ServerCalls$1$1.class
ServerCalls$1.class
ServerCalls$2$1.class
ServerCalls$2.class
```
New class names:
```
ServerCalls$StreamingServerCallHandler.class
ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.class
ServerCalls$UnaryServerCallHandler.class
ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.class
```
This is much easier to read quickly, espcially if line numbers don't
match between HEAD and the code that prints the stack trace.
Another benefit of this is that it drops a class file from the jar
(`EmptyServerCallListener`).
Lastly, it makes it easier in the future to test, since the specific
class can be referenced from a test. …

stub: Use nameed classes rather than anonymous in ServerCalls

---

stub/src/main/java/io/grpc/stub/package-info.java

git cherry-pick 68d73fa4d66559a93f0cca4ca9c601b4b3fc128f 29befc131d821347fb10a9c86eb3893fed2b18ff

backport v1.5.x: update javadoc link

---

stub/src/main/java/io/grpc/stub/package-info.java

git cherry-pick 68d73fa4d66559a93f0cca4ca9c601b4b3fc128f 29befc131d821347fb10a9c86eb3893fed2b18ff

backport v1.4.x: update javadoc link

---

core/src/main/java/io/grpc/ClientStreamTracer.java
core/src/main/java/io/grpc/internal/CensusStatsModule.java
core/src/main/java/io/grpc/internal/CensusTracingModule.java
core/src/main/java/io/grpc/internal/StatsTraceContext.java
core/src/test/java/io/grpc/CallOptionsTest.java
core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
core/src/test/java/io/grpc/internal/CensusModulesTest.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbClientLoadRecorder.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java

Resolves #3256
/cc @elandau @ejona86

core: pass CallOptions to newClientStreamTracer().

---

core/src/main/java/io/grpc/internal/CensusStatsModule.java
core/src/test/java/io/grpc/internal/CensusModulesTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

core/stats: report message count metrics to Census.

---

core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
interop-testing/src/test/java/io/grpc/testing/integration/ProxyTest.java

Duplicate throws exception, and  Javadoc issues: ManagedChannelImplTransportManagerTest.java has been deleted.

core: Java Refactor

---

context/src/main/java/io/grpc/Context.java

This code is authored by @lukesandberg
Add a bloom filter to fast fail reading keys that do not exist
@lukesandberg 's read benchmark will come in as a part of #3263

add bloom filter to Context

---

netty/src/main/java/io/grpc/netty/GrpcSslContexts.java
netty/src/main/java/io/grpc/netty/JettyTlsUtil.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpProtocolNegotiator.java

Additionally: include info on why android classes are missing

netty,okhttp: include more detail about ALPN missing

---

core/BUILD.bazel
core/src/main/java/io/grpc/internal/GrpcUtil.java
netty/BUILD.bazel
repositories.bzl

CC @duelinmarkers 
CC @neozwu @garrettjonesgoogle

Backport Bazel and GAE 8 bug fixes to v1.6.x

---

core/src/main/java/io/grpc/internal/SerializingExecutor.java

Atomic booleans cost a few extra bytes.  Save the object overhead and use an atomic field updater.

core: save alloc in SerializingExecutor

---

core/src/main/java/io/grpc/internal/ServerImpl.java

This makes it much easier to read stack traces since the name of the
event is in the frame.

core: name more anonymous classes in ServerImpl

---

core/src/main/java/io/grpc/internal/ClientCallImpl.java

Added checkState for this condition.

core: ClientCallImpl start should not be called after cancel

---

benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/ReportQpsScenarioServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
compiler/src/java_plugin/cpp/java_generator.cpp
compiler/src/test/golden/TestService.java.txt
core/src/main/java/io/grpc/MethodDescriptor.java
grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
protobuf/src/main/java/io/grpc/protobuf/ProtoMethodDescriptorSupplier.java
protobuf/src/main/java/io/grpc/protobuf/ProtoServiceDescriptorSupplier.java
services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java
services/src/generated/main/grpc/io/grpc/instrumentation/v1alpha/MonitoringGrpc.java
services/src/generated/main/grpc/io/grpc/reflection/v1alpha/ServerReflectionGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/AnotherDynamicServiceGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/DynamicServiceGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/ReflectableServiceGrpc.java
testing-proto/src/generated/main/grpc/io/grpc/testing/protobuf/SimpleServiceGrpc.java

This is a clone from #3086, but with an additional commit. For some reason I can no longer push to @lukaszx0's branch. It worked the first time...

Introduce MethodDescriptorSupplier

---

core/src/main/java/io/grpc/ForwardingChannelBuilder.java
core/src/main/java/io/grpc/ManagedChannelBuilder.java
core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java

Fixes #3493
CC @garrettjonesgoogle

Promote keepalive to ManagedChannelBuilder; stabilize

---

core/BUILD.bazel
repositories.bzl

core: fix Bazel build

---

auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java

Fixes https://github.com/grpc/grpc-java/issues/3525

auth: remove use of JDK7 ReflectiveOperationException

---

stub/src/main/java/io/grpc/stub/AbstractStub.java
stub/src/main/java/io/grpc/stub/CallStreamObserver.java
stub/src/main/java/io/grpc/stub/ClientCallStreamObserver.java
stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java

It appears no one mocks these.

stub: avoid mocking stub classes

---

cronet/README.md
cronet/src/main/java/io/grpc/cronet/CronetCallOptions.java
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java
cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java
cronet/src/main/java/io/grpc/cronet/CronetWritableBuffer.java
cronet/src/main/java/io/grpc/cronet/CronetWritableBufferAllocator.java

As tracked by https://github.com/grpc/grpc-java/issues/1116.
@ejona86 I reassigned the TODOs from zsurocking to me.

cronet: open-source experimental Cronet transport code

---

core/src/jmh/java/io/grpc/AttributesBenchmark.java
core/src/main/java/io/grpc/Attributes.java

Nice to have when using a base set of attributes multiple times.

core: allow attributes to be built multiple times

---

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java

interop-testing: fix interop_test client.

---

auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java

CC @ericgribkoff, it looked like this should be backported to 1.7.

1.7 backport: auth: remove use of JDK7 ReflectiveOperationException

---

cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java

@carl-mastrangelo I forgot to do this as part of the earlier cleanup

cronet: make CronetChannelBuilder final

---

README.md

```
$ git checkout -b bump-readme master
$ git cherry-pick v$MAJOR.$MINOR.$PATCH^
```

Update README to reference 1.7.0

---

SECURITY.md

Reported here: #3593
I verified the problem by hand.
Related: #3604

SECURITY.md: fix tcnative version for master branch

---

SECURITY.md

Reported here: #3593
I verified the problem by hand.
Related: #3604

SECURITY.md: fix tcnative version for v1.7.x

---

SECURITY.md
netty/src/main/java/io/grpc/netty/GrpcSslContexts.java

netty: Updated ALPN error message and added troubleshooting procedures

---

stub/src/main/java/io/grpc/stub/ServerCalls.java

Additionally:
* Prefer RuntimeException from status
* remove redundant "static" on interfaces
* use checkState to shorten code

stub: update ServerCalls to include status messages

---

testing/src/main/java/io/grpc/testing/TestUtils.java
testing/src/main/java/io/grpc/testing/TlsTesting.java
testing/src/test/java/io/grpc/testing/TestUtilsTest.java
testing/src/test/java/io/grpc/testing/TlsTestingTest.java

testing: add TlsTesting.loadCert

---

repositories.bzl

This fixes the Bazel build after d87ef740

bazel: Update opencensus to 0.8

---

cronet/src/test/java/io/grpc/cronet/CronetChannelBuilderTest.java
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java
cronet/src/test/java/io/grpc/cronet/CronetClientTransportTest.java
cronet/src/test/java/io/grpc/cronet/CronetWritableBufferAllocatorTest.java

Addresses https://github.com/grpc/grpc-java/issues/3587. Manually verified the roboelectric tests build and run with Android Studio.

cronet: add tests

---

netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java

Fixes https://github.com/grpc/grpc-java/issues/3707

netty: TransportTracer test for local window update

---

core/src/main/java/io/grpc/ServerBuilder.java
core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
core/src/main/java/io/grpc/internal/ServerImpl.java
core/src/test/java/io/grpc/internal/ServerImplTest.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java

Backport server handshake timeout

---

core/src/main/java/io/grpc/internal/AbstractClientStream.java
core/src/main/java/io/grpc/internal/AbstractServerStream.java
core/src/main/java/io/grpc/internal/AbstractStream.java
core/src/main/java/io/grpc/internal/GrpcUtil.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyClientStream.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java

Also updated unit tests to verify client side stats in `AbstractTransportTest`

core,netty: wire TransportTracer to netty client

---

core/BUILD.bazel
repositories.bzl

This fixes the Bazel build after ef2ec949

bazel: Add dep on opencensus-contrib-grpc-metrics

---

okhttp/src/main/java/io/grpc/okhttp/OutboundFlowController.java

This change is required for the okhttp transport tracer stats.

okhttp: make outbound window size readable

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java

netty: fix server keepalive unexpected ping ack (backport v1.8.x) 

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java

netty: fix server keepalive unexpected ping ack (backport v1.7.x) 

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java

netty: fix server keepalive unexpected ping ack (backport v1.5.x) 

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java

netty: fix server keepalive unexpected ping ack (backport v1.6.x) 

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java

netty: fix server keepalive unexpected ping ack (backport v1.3.x)

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java

netty: fix server keepalive unexpected ping ack (backport v1.4.x) 

---

core/src/main/java/io/grpc/internal/LogId.java
netty/src/main/java/io/grpc/netty/NettyServer.java

These are already WithLogId:
ManagedChannelImpl, InternalSubchannel, ServerTransport

core,netty: add ID to NettyServer

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java

netty: Netty server poorly handles unknown content type (backport)

---

.github/ISSUE_TEMPLATE

Most people skip these fields, and I am not sure maintainers look at them.  Let's keep it light.

all: update github issue template

---

core/src/main/java/io/grpc/internal/CensusStatsModule.java
core/src/main/java/io/grpc/internal/CensusTracingModule.java
core/src/main/java/io/grpc/internal/SerializingExecutor.java

Backport of https://github.com/grpc/grpc-java/pull/3754

core: workaround for Atomic*FieldUpdater bug on some Android devices

---

repositories.bzl

Correct sha1 for common-protos

---

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

Interop tests use actual Census implementations, while MockableSpan is
compatible with the Census OSS implementation, it doesn't work with
the google internal implementation, thus the tests will fail.
/cc @bogdandrutu

interop-testing: stop using MockableSpan.

---

core/src/main/java/io/grpc/ChannelStats.java
core/src/main/java/io/grpc/InternalChannelStats.java
core/src/main/java/io/grpc/ManagedChannel.java
core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/ChannelTracer.java
core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/OobChannel.java
core/src/test/java/io/grpc/internal/ClientCallImplTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

Refactoring the existing code according to this plan:
https://github.com/grpc/grpc-java/pull/3817#discussion_r155683847

core: ManagedChannel should implement InternalInstrumented

---

.gitignore
protobuf-lite/build.gradle

Partially addresses https://github.com/grpc/grpc-java/issues/3864

Partial fix for fresh Intellij import

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/GrpcAttributes.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbConstants.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

core/grpclb: resolve TXT records in DNS name resolver and include balancer addresses

---

core/src/main/java/io/grpc/ManagedChannel.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/OobChannel.java

git cherry-pick 40453c744fd9113135fbe4af68343a65a0a1c6fb

core: fix unimplemented API in ManageChannel (backport 1.9)

---

core/src/main/java/io/grpc/InternalTransportStats.java
core/src/main/java/io/grpc/TransportStats.java

Limited access will be granted via InternalTransportStats.

core: make TransportStats package-private

---

benchmarks/src/main/java/io/grpc/benchmarks/qps/OpenLoopClient.java
build.gradle
core/src/main/java/io/grpc/Metadata.java
core/src/main/java/io/grpc/internal/ApplicationThreadDeframer.java
core/src/main/java/io/grpc/internal/ChannelExecutor.java
core/src/test/java/io/grpc/MethodDescriptorTest.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceImpl.java
netty/src/test/java/io/grpc/netty/AbstractHttp2HeadersTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java
stub/src/test/java/io/grpc/stub/ClientCallsTest.java

The fixes could have subtle side-effects, but I did take care when making them.

Update ErrorProne to 2.1.3 and fix failures

---

interop-testing/src/main/java/io/grpc/testing/integration/TestServiceImpl.java

Fixes https://github.com/grpc/grpc-java/issues/3843

interop-testing: fix race in TestServiceImpl

---

buildscripts/kokoro/gae-interop.sh

Backport of https://github.com/grpc/grpc-java/pull/3901

buildscripts: fix gae kokoro script error using cmd output rather than $? (1.9 backport)

---

gae-interop-testing/gae-jdk7/build.gradle
gae-interop-testing/gae-jdk8/build.gradle

gae: retry on exceptions too, not just on non 200OK (1.9 backport)

---

buildscripts/kokoro/gae-interop.sh

Backport of https://github.com/grpc/grpc-java/pull/3902

buildscripts: automatically delete old lingering versions (1.9 backport)

---

RELEASING.md

I just closed 1.9.0. I realized we were missing the step from the documentation.

RELEASING.md: Add closing of the milestone

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

Use call executor and scheduled executor service to schedule and run `retry()`.
Backoff amount computation from retry policy and testcases during backoff will be added in future PRs.

core: retry part 3, use call executor and scheduled executor service

---

core/src/test/java/io/grpc/ForwardingClientCallListenerTest.java
core/src/test/java/io/grpc/ForwardingClientCallTest.java
core/src/test/java/io/grpc/ForwardingServerCallTest.java

Adding tests for completeness. This PR is low priority.

core: tests for forwarding {Server,Client}{Call, CallListener}

---

README.md
android-interop-testing/app/build.gradle
build.gradle
compiler/src/test/golden/TestService.java.txt
compiler/src/testLite/golden/TestService.java.txt
compiler/src/testNano/golden/TestService.java.txt
core/src/main/java/io/grpc/internal/GrpcUtil.java
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/build.gradle
examples/pom.xml

The commits will stay separate.

Release v1.9.1

---

context/src/main/java/io/grpc/Context.java
context/src/main/java/io/grpc/InternalContext.java
context/src/main/java/io/grpc/PersistentHashArrayMappedTrie.java
context/src/test/java/io/grpc/PersistentHashArrayMappedTrieTest.java

This will allow us to measure how often contexts of particular sizes are used.

context: add basic context profiling

---

core/src/main/java/io/grpc/internal/ConnectivityStateManager.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ConnectivityStateManagerTest.java

There have been no callers of disable() since commit 1c7421be7.

core: ConnectivityStateManager is always enabled

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

This is the last feature of retry impl PRs (not including transparent retry and hedging).

core: retry part 5 continued, throttle policy

---

WORKSPACE
examples/BUILD.bazel
examples/WORKSPACE

Rename Bazel workspace to io_grpc_grpc_java

---

core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/AbstractSubchannel.java
core/src/main/java/io/grpc/internal/Channelz.java
core/src/main/java/io/grpc/internal/InternalSubchannel.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/OobChannel.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

- channelz is nullable and is null by default
- the *channels are registered at creation and unregistered at
termination

core: register channels, subchannels, oobchannels with channelz

---

core/src/main/java/io/grpc/internal/ServerImpl.java
core/src/test/java/io/grpc/internal/ServerImplTest.java

A previous PR added client transports, this PR adds server
transports.

core: add server transports to channelz

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

It is now discovering legitimate errors in some tests that need to be
resolved first. Follow progress at #3293.

core: Disable panic mode

---

core/src/main/java/io/grpc/internal/BinaryLogProvider.java
core/src/test/java/io/grpc/internal/BinaryLogProviderTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/ServerImplTest.java
core/src/test/resources/io/grpc/internal/BinaryLogProviderTest-multipleProvider.txt
core/src/test/resources/io/grpc/internal/BinaryLogProviderTest-unavailableProvider.txt

Use the common util rather than rolling our own here.

core: load binarylog class using serviceprovider util

---

core/BUILD.bazel
core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/JsonParser.java
core/src/test/java/io/grpc/internal/JsonParserTest.java

This is part 1 of https://github.com/grpc/grpc-java/commit/b01609572ab4f0dba6eae23fe5be05a302ecefc7
Next will be re validating the service config, and part 3 will be enforcing it in MCI.

core: split JSON parsing into its own file

---

alts/src/generated/main/grpc/io/grpc/alts/internal/HandshakerServiceGrpc.java
alts/src/generated/main/java/io/grpc/alts/internal/Handshaker.java
alts/src/main/proto/handshaker.proto

We are synchronizing the proto change across 3 languages.

alts: minor update to ALTS handshaker proto

---

services/src/generated/main/java/io/grpc/channelz/v1/Channel.java
services/src/generated/main/java/io/grpc/channelz/v1/ChannelOrBuilder.java
services/src/generated/main/java/io/grpc/channelz/v1/ChannelzProto.java
services/src/generated/main/java/io/grpc/channelz/v1/Subchannel.java
services/src/generated/main/java/io/grpc/channelz/v1/SubchannelOrBuilder.java
services/src/main/proto/io/grpc/channelz.proto

This is more consistent with the other fields.

services: update channelz.proto to refer to sockets as socket_ref

---

core/src/main/java/io/grpc/internal/Channelz.java
core/src/test/java/io/grpc/internal/ChannelzTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
services/src/main/java/io/grpc/services/ChannelzProtoUtil.java
services/src/main/java/io/grpc/services/ChannelzService.java
services/src/test/java/io/grpc/services/ChannelzProtoUtilTest.java
services/src/test/java/io/grpc/services/ChannelzServiceTest.java
services/src/test/java/io/grpc/services/ChannelzTestHelper.java

This implements the class to expose the stats as
protos. GetServerSockets is still unimplemented and will require a
follow up change.
This PR is large but more than half of the LOC are tests.

core,services: add ChannelzService class

---

core/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/PickFirstBalancerFactory.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/PickFirstLoadBalancerTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

core: fix channel.getState(true) will not reconnect

---

services/src/generated/main/java/io/grpc/channelz/v1/ChannelzProto.java
services/src/generated/main/java/io/grpc/channelz/v1/Security.java
services/src/main/proto/io/grpc/channelz.proto

For context:
https://github.com/grpc/proposal/pull/71

services: update channelz TLS proto to use RFC names

---

core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java

core: re-add back in orphan wrapper

---

examples/src/main/java/io/grpc/examples/routeguide/RouteGuideServer.java

Same as https://github.com/grpc/grpc/pull/14794.

routeguide: reimplement distance calculation

---

build.gradle
core/build.gradle
protobuf/build.gradle
repositories.bzl
services/build.gradle

Bump to Guava 20

---

core/src/main/java/io/grpc/internal/FailingClientStream.java
core/src/main/java/io/grpc/internal/FailingClientTransport.java
core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java
core/src/test/java/io/grpc/internal/FailingClientStreamTest.java
core/src/test/java/io/grpc/internal/FailingClientTransportTest.java
core/src/test/java/io/grpc/internal/GrpcUtilTest.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

Address #3553 for normal retry. Not covering the unimplemented hedging case.

core: no retry on dropped PickResult

---

core/src/main/java/io/grpc/internal/AbstractClientStream.java
netty/src/main/java/io/grpc/netty/CancelClientStreamCommand.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyClientStream.java
netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java

Backport of https://github.com/grpc/grpc-java/pull/4222

core,netty: client sends rst stream when server half-closes (1.11 backport)

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/ServiceConfigInterceptor.java

Fixes #4333 
cc: @dapengzhang0

core: don't warn on absent service config

---

netty/src/main/java/io/grpc/netty/InternalNettySocketSupport.java
netty/src/main/java/io/grpc/netty/NettySocketSupport.java

Previous version is not actually extendable from other packages.

netty: fix visibility issues with InternalNettySocketSupport

---

core/src/main/java/io/grpc/internal/InternalSubchannel.java
core/src/test/java/io/grpc/internal/InternalSubchannelTest.java

This is info not being reported at the moment and is missing from the
display.

core: add sockets to subchannel stat

---

core/src/main/java/io/grpc/ConnectivityState.java
core/src/main/java/io/grpc/ManagedChannel.java

The earlier issue was for the feature itself, not the stabilization.

core: Fix experimental API issue for channel state API

---

core/src/main/java/io/grpc/internal/JsonParser.java
core/src/main/java/io/grpc/internal/ServiceConfigUtil.java

core: also expose parser on JsonParser

---

android-interop-testing/app/build.gradle
android-interop-testing/app/src/main/AndroidManifest.xml
android-interop-testing/build.gradle

Updates the build to use later play services release, plus fixes some new lint errors.

android-interop-testing: update app dependencies

---

README.md

In response to https://github.com/grpc/grpc-java/issues/4407

README.md: clarify that Android is for client-side use

---

services/src/main/java/io/grpc/services/BinaryLogProviderImpl.java
services/src/main/java/io/grpc/services/BinlogHelper.java
services/src/test/java/io/grpc/services/BinlogHelperTest.java

This class really is an internal helper class for the implementation.

services: BinaryLog is an overused term, rename to BinlogHelper

---

.travis.yml
buildscripts/build_artifacts_in_docker.sh
buildscripts/grpc-java-releasing/Dockerfile
buildscripts/kokoro/android.sh
buildscripts/kokoro/linux_artifacts.cfg
buildscripts/kokoro/linux_artifacts.sh
buildscripts/kokoro/release_artifacts.cfg
buildscripts/kokoro/release_artifacts.sh
buildscripts/kokoro/unix.sh
buildscripts/kokoro/upload_artifacts.cfg
buildscripts/kokoro/upload_artifacts.sh
buildscripts/kokoro/windows.bat
buildscripts/kokoro/windows32.bat
buildscripts/kokoro/windows64.bat
buildscripts/make_dependencies.sh
buildscripts/run_in_docker.sh
buildscripts/sonatype-upload.sh

A backport of the scripts for auto release using kokoro infrastructure.

Release scripts backport to v1.12.x

---

core/src/main/java/io/grpc/internal/AbstractClientStream.java
core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java

core: fix client does not detect truncated message

---

protobuf/src/main/java/io/grpc/protobuf/ProtoUtils.java

Add metadataMarshaller to ProtoUtils

---

RELEASING.md

Helps address https://github.com/grpc/grpc-java/issues/4460

RELEASING.md: check availability on JCenter

---

core/src/main/java/io/grpc/Attributes.java
core/src/test/java/io/grpc/AttributesTest.java

core: fix Attributes hashCode

---

services/src/generated/main/java/io/grpc/binarylog/BinaryLogProto.java
services/src/generated/main/java/io/grpc/binarylog/GrpcLogEntry.java
services/src/generated/main/java/io/grpc/binarylog/GrpcLogEntryOrBuilder.java
services/src/generated/main/java/io/grpc/binarylog/Message.java
services/src/generated/main/java/io/grpc/binarylog/MessageOrBuilder.java
services/src/generated/main/java/io/grpc/binarylog/MetadataEntry.java
services/src/generated/main/java/io/grpc/binarylog/MetadataEntryOrBuilder.java
services/src/generated/main/java/io/grpc/binarylog/Peer.java
services/src/generated/main/java/io/grpc/binarylog/PeerOrBuilder.java
services/src/main/proto/io/grpc/binarylog.proto

sync with grpc/grpc-proto for https://github.com/grpc/grpc-proto/commit/ef8948a966ff454034b62c0c332020733d2207d3

services: sync binarylog.proto

---

alts/BUILD.bazel
alts/build.gradle

Add grpclb and dns name resolver that can parse SRV record.

alts: add grpclb library dependency

---

core/src/main/java/io/grpc/ServerBuilder.java

core: fix ServerBuilder.setBinaryLog javadoc

---

core/src/main/java/io/grpc/ForwardingChannelBuilder.java
core/src/main/java/io/grpc/ManagedChannelBuilder.java
core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/ChannelTracer.java
core/src/main/java/io/grpc/internal/Channelz.java
core/src/main/java/io/grpc/internal/InternalSubchannel.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/OobChannel.java
core/src/test/java/io/grpc/internal/ChannelTracerTest.java
core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
services/src/test/java/io/grpc/services/ChannelzProtoUtilTest.java

Includes 
- API plumbing for channel tracing `+ManagedChannelBuilder.maxTraceEvents()`
- trace logging for channel/subchannel creation events and name resolving events.
Trace logging for all other events will be added in subsequent PRs.

core: Implement channel tracing for some events

---

build.gradle
core/src/main/java/io/grpc/internal/CensusTracingModule.java
core/src/test/java/io/grpc/internal/CensusModulesTest.java
repositories.bzl
testing/src/main/java/io/grpc/internal/testing/StatsTestUtils.java

Changed calls to deprecated methods to the newly added methods.

core: update opencensus to 0.12.3.

---

buildscripts/kokoro/android.sh
cronet/README.md
cronet/build.gradle
cronet/cronet_deps.sh

See https://github.com/GoogleChromeLabs/cronet-sample/pull/6 for prior art.

cronet: use Cronet from Google Maven

---

alts/src/generated/main/grpc/io/grpc/alts/internal/HandshakerServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/ReportQpsScenarioServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
compiler/src/java_plugin/cpp/java_generator.cpp
compiler/src/test/golden/TestService.java.txt
compiler/src/testLite/golden/TestService.java.txt
compiler/src/testNano/golden/TestService.java.txt
grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
services/src/generated/main/grpc/io/grpc/channelz/v1/ChannelzGrpc.java
services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java
services/src/generated/main/grpc/io/grpc/reflection/v1alpha/ServerReflectionGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/AnotherDynamicServiceGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/DynamicServiceGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/ReflectableServiceGrpc.java
testing-proto/src/generated/main/grpc/io/grpc/testing/protobuf/SimpleServiceGrpc.java

stub: remove static Method descriptors and stabilize method accessors

---

services/src/generated/main/java/io/grpc/binarylog/BinaryLogProto.java
services/src/generated/main/java/io/grpc/binarylog/GrpcLogEntry.java
services/src/generated/main/java/io/grpc/binarylog/GrpcLogEntryOrBuilder.java
services/src/generated/main/java/io/grpc/binarylog/Metadata.java
services/src/main/proto/io/grpc/binarylog.proto

https://github.com/grpc/grpc-proto/pull/20

services: sync binlog proto

---

cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java
cronet/src/test/java/io/grpc/cronet/CronetClientTransportTest.java

cronet: fill in transport attributes as required by CallCredentials

---

services/src/main/java/io/grpc/services/BinlogHelper.java
services/src/test/java/io/grpc/services/BinlogHelperTest.java

These are first class concepts and should be pulled to top level of
proto.

services: binlog deadline and methodName at start of rpc

---

auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java
cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java
cronet/src/test/java/io/grpc/cronet/CronetClientTransportTest.java

This backports #4532 and #4524

auth,cronet: PRIVACY_AND_INTEGRITY protect GoogleCredentials (1.13 backport)

---

protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoInputStream.java
protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java
protobuf-nano/src/main/java/io/grpc/protobuf/nano/MessageNanoFactory.java
protobuf-nano/src/main/java/io/grpc/protobuf/nano/NanoProtoInputStream.java
protobuf-nano/src/main/java/io/grpc/protobuf/nano/NanoUtils.java
protobuf/src/main/java/io/grpc/protobuf/ProtoFileDescriptorSupplier.java
protobuf/src/main/java/io/grpc/protobuf/ProtoUtils.java

- Split anonymous classes in named and final classes
- Fix some Javadocs and annotate when things were added.

protobuf{,lite,nano}: make more classes final

---

android-interop-testing/app/src/androidTest/AndroidManifest.xml
android-interop-testing/app/src/androidTest/java/io/grpc/android/integrationtest/InteropInstrumentationTest.java
android-interop-testing/app/src/main/AndroidManifest.xml
android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/InteropTask.java
android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/TesterOkHttpChannelBuilder.java

This is needed by our internal instrumentation tests.

android-interop-testing: minor fixes for instrumentation tests

---

alts/src/test/java/io/grpc/alts/internal/AltsHandshakerStubTest.java

Intended to resolve #4291.
Previously AltsHandshakerStubTest.closeEarlyTest is flaky because it is async.
De-flake the test by removing executors.
cc: @jiangtaoli2016, @ejona86.

alts: de-flake AltsHandshakerStubTest

---

core/build.gradle
core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java

core: make Auto config load balancer not depend on service config

---

core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
core/src/main/java/io/grpc/internal/InternalHandlerRegistry.java
core/src/main/java/io/grpc/internal/ServerImpl.java

Also some minor formatting changes.

core: make InternalHandlerRegistry a HandlerRegistry

---

android-interop-testing/app/build.gradle
android-interop-testing/app/src/androidTest/AndroidManifest.xml
android-interop-testing/app/src/androidTest/java/io/grpc/android/integrationtest/InteropInstrumentationTest.java

See https://developer.android.com/topic/libraries/support-library/refactor

android-interop-testing: migrate to androidx test libs

---

alts/src/generated/main/grpc/io/grpc/alts/internal/HandshakerServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/ReportQpsScenarioServiceGrpc.java
benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
compiler/src/java_plugin/cpp/java_generator.cpp
compiler/src/test/golden/TestService.java.txt
compiler/src/testLite/golden/TestService.java.txt
grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
services/src/generated/main/grpc/io/grpc/channelz/v1/ChannelzGrpc.java
services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java
services/src/generated/main/grpc/io/grpc/reflection/v1alpha/ServerReflectionGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/AnotherDynamicServiceGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/DynamicServiceGrpc.java
services/src/generated/test/grpc/io/grpc/reflection/testing/ReflectableServiceGrpc.java
stub/src/main/java/io/grpc/stub/RpcMethod.java
stub/src/main/java/io/grpc/stub/annotations/RpcMethod.java
testing-proto/src/generated/main/grpc/io/grpc/testing/protobuf/SimpleServiceGrpc.java

This annotation will enable Java APT to generate code.

compiler, stub: Add @RpcMethod annotation (#3173)

---

RELEASING.md

This greatly reduces the amount of content. The removed content was
already deteriorating. For example, it references grpc-java-deploy which
is no longer present nor necessary. It also didn't suggest using
build_docker.sh for building protoc-artifacts.
While the docs could have been updated, without actually running them
they are unlikely to be functional. Removing the docs seems better than
spending effort of maintaining them, especially since they add confusion
to the process and are a scary amount of content for new devs.

RELEASING.md: Remove manual artifact documentation

---

services/src/main/java/io/grpc/services/BinlogHelper.java
services/src/test/java/io/grpc/services/BinlogHelperTest.java

These are first class concepts and must exist as top level fields.

services: binlog status code, msg, details

---

.travis.yml
build.gradle

Fix class major version warning when using jdk10
fixes https://github.com/grpc/grpc-java/issues/4654

Fix jdk10 support in travis

---

SECURITY.md
build.gradle

Currently riding the train, but everything looks good so far.

all: update to netty 4.1.27 and tcnative 2.0.12

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

Backport of https://github.com/grpc/grpc-java/pull/4630

core: enterIdleMode() exits idle if still in use (backport to v1.14.x)

---

core/src/main/java/io/grpc/ManagedChannel.java

doc: clarify channel state API unimplemented until v1.6.1

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java

core: add flags for selectively enabling grpclb

---

.travis.yml

Previously it was just erroring:
[[: command not found

travis.yml: Actually trigger coveralls

---

README.md

Update versions from 1.13.1 to 1.13.2.

Documentation - bump versions

---

repositories.bzl

Cherry pick of #4707 and b1c461f8fb0f2e4942355fd99af46086081cb8d5

all: fix bazel build deps for netty (1.14.x backport)

---

CONTRIBUTING.md

CONTRIBUTING.md: Add reference to COMPILING.md

---

auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java

This removes an impossible condition and adds a test for another
condition.

auth: Small improvement to test coverage

---

core/src/main/java/io/grpc/internal/CensusStatsModule.java

https://groups.google.com/d/msg/grpc-io/v4HTQeMBd4g/-W42wjleDQAJ

core: remove unused fullMethodName field from CensusStatsModule.

---

android/src/main/java/io/grpc/android/AndroidChannelBuilder.java
core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java

These are small straight forward fixes.

Fix lints discovered during import

---

core/src/main/java/io/grpc/PickFirstBalancerFactory.java
core/src/test/java/io/grpc/PickFirstLoadBalancerTest.java

This makes the behavior more clear.
----
Should I also remove the body of Picker.requestConnection?

core: Avoid implicit requestConnection in PickFirst

---

README.md

all: point readme to new URL

---

README.md

all: point readme to new jar URL (1.14.x backport)

---

README.md

all: point readme to new jar URL (1.13.x backport)

---

buildscripts/kokoro/gae-interop.sh
gae-interop-testing/gae-jdk7/build.gradle
gae-interop-testing/gae-jdk7/src/main/webapp/WEB-INF/appengine-web.xml
gae-interop-testing/gae-jdk8/build.gradle
gae-interop-testing/gae-jdk8/src/main/webapp/WEB-INF/appengine-web.xml

The independent commits will be rebase merged.

Clean up GAE tests
