- README.md
Releasing.md to follow.  This is mainly to have the splash page on Github point to the current version.
> all: recommend the latest gRPC version on master

- .travis.yml
- benchmarks/src/main/java/io/grpc/benchmarks/ByteBufInputStream.java
- benchmarks/src/main/java/io/grpc/benchmarks/SocketAddressValidator.java
- benchmarks/src/test/java/io/grpc/benchmarks/driver/LoadClientTest.java
- build.gradle
- compiler/build.gradle
- core/src/main/java/io/grpc/Status.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/main/java/io/grpc/internal/ServerCallImpl.java
- core/src/test/java/io/grpc/ConnectivityStateInfoTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceImpl.java
- interop-testing/src/test/java/io/grpc/testing/integration/ProxyTest.java
- netty/src/test/java/io/grpc/netty/NettyChannelBuilderTest.java
- netty/src/test/java/io/grpc/netty/NettyStreamTestBase.java
- netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
- okhttp/src/main/java/io/grpc/okhttp/OutboundFlowController.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
- okhttp/third_party/okhttp/java/io/grpc/okhttp/internal/DistinguishedNameParser.java
- okhttp/third_party/okhttp/java/io/grpc/okhttp/internal/Platform.java
- okhttp/third_party/okhttp/java/io/grpc/okhttp/internal/framed/Huffman.java
- protobuf-lite/build.gradle
- testing/src/main/java/io/grpc/testing/DeadlineSubject.java
- thrift/build.gradle
- thrift/src/main/java/io/grpc/thrift/ThriftInputStream.java
ErrorProne provides static analysis for common issues, including
misused variables GuardedBy locks.
This increases build time by 60% for parallel builds and 30% for
non-parallel, so I've provided a way to disable the check. It is on by
default though and will be run in our CI environments.
So I've tried to do an okay job fixing up existing issues. But I wouldn't
be surprised if someone would prefer they were handled differently.
> all: Enable ErrorProne during compilation

- netty/build.gradle
I'm quite confused how we went this long using Jetty ALPN for the Netty
tests. Anyway, we strongly prefer tcnative, so we should be using it in
the tests.
CC @lukaszx0
> netty: Use tcnative in tests instead of Jetty ALPN

- core/src/main/java/io/grpc/internal/AbstractClientStream2.java
Minor fix to make linking work in IDEs.
> doc: fix @link to cancel in java doc

- core/src/main/java/io/grpc/internal/AbstractStream.java
Small clean up of a doc that is irrelevant
> doc: there's no type param anymore

- build.gradle
- interop-testing/build.gradle
It doesn't do anything, since tcnative has been specified as a normal
dependency for a while.
> interop-testing: Remove useless tcnative configuration

- android-interop-testing/app/build.gradle
- build.gradle
- core/src/main/java/io/grpc/internal/MoreThrowables.java
- core/src/main/java/io/grpc/internal/ServerCallImpl.java
- examples/android/helloworld/app/build.gradle
- examples/android/routeguide/app/build.gradle
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
Guava 20 introduced some overloading optimizations for Preconditions
that require using Guava 20+ at runtime. Unfortunately, Guava 20 removes
some things that is causing incompatibilities with other libraries, like
Cassandra. While the incompatibility did trigger some of those libraries
to improve compatibility for newer Guavas, we'd like to give the
community more time to work through it. See #2688
At this commit, we appear to be compatible with Guava 18+. It's not
clear if we want to actually "support" 18, but it did compile. Guava 17
doesn't have at least MoreObjects, directExecutor, and firstNotNull.
Guava 21 compiles without warnings, so it should be compatible with
Guava 22 when it is released.
One test method will fail with the upcoming Guava 22, but this won't
impact applications. …
> all: Downgrade to Guava 19

- services/src/main/java/io/grpc/protobuf/service/ProtoReflectionService.java
- services/src/test/java/io/grpc/protobuf/service/ProtoReflectionServiceTest.java
This addresses https://github.com/grpc/grpc-java/issues/2689. `ServerReflectionIndex` is now immutable, and its reference is replaced by a new instance when changes are detected.
I also fixed some poor formatting choices present in the earlier code, primarily the tests - I don't think the changes are too invasive, given that much of the code has genuinely been changed here, and the formatting already popped up as an issue on https://github.com/grpc/grpc-java/pull/2657.
> services: don't update reflection index mid-stream

- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
It didn't check if the address was already there in the current
subchannel set before creating a new subchannel for it, causing a leak
of subchannels.
> grpclb: fix a bug in handling server address updates.

- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
For #2762
If it doesn't fix the flaky test, status.toString() will print out the
whole stack trace so that we will know what's in there.
> netty/test: be less agreesive on checking cause

- core/src/main/java/io/grpc/internal/KeepAliveManager.java
- core/src/test/java/io/grpc/internal/KeepAliveManagerTest.java
There was a bug:
IDLE_AND_PING_SENT -> a new stream starts -> ping acked
would lead the keepalivemanager into IDLE state forever.
> core: fix keepalivemanager bug on handling IDLE_AND_PING_SENT

- core/src/main/java/io/grpc/internal/KeepAliveManager.java
- core/src/test/java/io/grpc/internal/KeepAliveManagerTest.java
backport of #2773 
There was a bug:
IDLE_AND_PING_SENT -> a new stream starts -> ping acked
would lead the keepalivemanager into IDLE state forever.
> core: fix keepalivemanager bug on handling IDLE_AND_PING_SENT (backport 1.0.x)

- core/src/main/java/io/grpc/internal/KeepAliveManager.java
- core/src/test/java/io/grpc/internal/KeepAliveManagerTest.java
#2773 
There was a bug:
IDLE_AND_PING_SENT -> a new stream starts -> ping acked
would lead the keepalivemanager into IDLE state forever.
> core: fix keepalivemanager bug on handling IDLE_AND_PING_SENT (backport v1.1.x)

- core/src/main/java/io/grpc/util/RoundRobinLoadBalancerFactory.java
- core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
handleResolvedAddresses constructs subchannels for each address in
an EquivalentAddressGroup, sharing a reference to an immutable
Atrributes. However, as noted, this Attributes instance contains
a mutable AtomicReference, eventually causing subchannel state
changes to be improperly reflected in *all* subchannels of an
EquivalentAddressGroup.
This change gives each subchannel its own Attributes instance, mitigating
this issue.
> Fix shared subchannel state in RoundRobin LB

- examples/src/main/java/io/grpc/examples/errorhandling/DetailErrorSample.java
- examples/src/main/java/io/grpc/examples/errorhandling/ErrorHandlingClient.java
The executor-less version is being removed, as having the executor
explicitly specified is less bug-prone.
> examples: Always pass an executor to Futures.addCallback()

- core/src/test/java/io/grpc/ServiceDescriptorTest.java
- core/src/test/java/io/grpc/internal/AbstractClientStream2Test.java
- core/src/test/java/io/grpc/internal/AbstractServerStreamTest.java
- core/src/test/java/io/grpc/internal/MessageDeframerTest.java
- core/src/test/java/io/grpc/internal/ServerCallImplTest.java
- netty/src/test/java/io/grpc/netty/NettyChannelBuilderTest.java
- netty/src/test/java/io/grpc/netty/NettyServerBuilderTest.java
- netty/src/test/java/io/grpc/netty/NettyStreamTestBase.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpChannelBuilderTest.java
fix JavaStyle and ErrorProne warnings found in internal weekly import:
- Calls to ExpectedException#expect should always be followed by exactly one statement.
- Do not mock 'java.util.concurrent.Future'
> all: fix errorprones

- core/src/main/java/io/grpc/LoadBalancer.java
the build (jdk version jdk1.8.0_91) produces some noise
```
/usr/local/google/home/zdapeng/git/grpc-java/core/src/main/java/io/grpc/LoadBalancer.java:196: warning - Tag @link: can't find pickSubchannel(PickSubchannelArgs) in io.grpc.LoadBalancer.SubchannelPicker
/usr/local/google/home/zdapeng/git/grpc-java/core/src/main/java/io/grpc/LoadBalancer.java:388: warning - Tag @link: can't find pickSubchannel(
PickSubchannelArgs) in io.grpc.LoadBalancer.SubchannelPicker
/usr/local/google/home/zdapeng/git/grpc-java/core/src/main/java/io/grpc/LoadBalancer.java:178: warning - Tag @link: can't find pickSubchannel(PickSubchannelArgs) in io.grpc.LoadBalancer.SubchannelPicker
3 warnings
:grpc-core:javadocJar
```
It seems nothing wrong with the javadoc and it could be a javac's bug, but here's a …
> core: fix '@link: can't find...' build noise

- core/src/main/java/io/grpc/LoadBalancer.java
- grpclb/build.gradle
- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
- grpclb/src/main/java/io/grpc/grpclb/LbAddressGroup.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
The balancer service attaches a token string for each `Server` entry it
sends to the client.  The client has to set the token to the `"lb-token"`
header when assigning that Server entry to an RPC.
For convenience of testing, also implemented `hashCode()` and `equals()` for
`PickResult`.
cc @ejona86 for the changes in `PickResult`.
> grpclb: set LB tokens to headers.

- NOTICE.txt
- netty/build.gradle
- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
- netty/third_party/netty/LICENSE.txt
- netty/third_party/netty/java/io/grpc/netty/FixedHttp2ConnectionDecoder.java
Reviewing each commit separately is easiest. I'll leave the two commits as separate when I merge to master.
The netty/third_party stuff is a clone of what was done in okhttp/third_party.
> Backport SETTINGS ACK sequencing fix

- okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
Per request of the VTK team, we want to bake in the needed SSL workaround for AppEngine standard.
> okhttp: Add restricted AppEngine SSL setup

- build.gradle
Jetty ALPN was broken with jdk1.8.0_121
> all: Bump Jetty ALPN agent version, for new JREs

- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
Increased timeout to 20 seconds to see if flakiness of #2328 persists. Will take further action after sufficient observation
> testing: temporarily increased newStream_duringShutdown test timeout to 20s

- core/src/main/java/io/grpc/ManagedChannel.java
Both `ManagedChannelImpl` and `Channel` have it
cc @zhangkun83
> core: add missing @ThreadSafe annotation

- core/src/main/java/io/grpc/internal/KeepAliveManager.java
- core/src/test/java/io/grpc/internal/KeepAliveManagerTest.java
Preparing to support server side keepalive.
For the convience on server side, not to use Ping `onSuccess()` callback to cancle shutdownFuture any more, instead, regard `onDataReceived()` as ping Ack and cancel shutdownFuture in it.
This is a part of the larger PR #2778
> core: keepaliveManager not to use Ping.onSuccess and ragard onDataReceive as ping Ack

- core/src/main/java/io/grpc/internal/BackoffPolicy.java
- core/src/main/java/io/grpc/internal/ExponentialBackoffPolicy.java
- core/src/main/java/io/grpc/internal/InternalSubchannel.java
- core/src/test/java/io/grpc/ContextsTest.java
- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
- core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
- core/src/test/java/io/grpc/internal/ExponentialBackoffPolicyTest.java
- core/src/test/java/io/grpc/internal/FakeClock.java
- core/src/test/java/io/grpc/internal/FakeClockTest.java
- core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- core/src/test/java/io/grpc/internal/StatsTraceContextTest.java
Rather than use a mix of millis and nanos, let's just use nanos throughout.  We can convert to millis on API boundaries (like with Census).  Many Java APIs already speak Nanos, so we should too.
> core: use nanos more consistently

- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
As 65e4d9f has split the channel instantiation and `connect()`, we can `startWriteQueue()` even earlier.
> netty: move startWriteQueue right after channel is constructed

- services/src/generated/main/java/io/grpc/instrumentation/v1alpha/CanonicalRpcStats.java
- services/src/generated/main/java/io/grpc/instrumentation/v1alpha/CanonicalRpcStatsOrBuilder.java
- services/src/generated/main/java/io/grpc/instrumentation/v1alpha/MonitoringProto.java
- services/src/generated/main/java/io/grpc/instrumentation/v1alpha/StatsRequest.java
- services/src/generated/main/java/io/grpc/instrumentation/v1alpha/StatsRequestOrBuilder.java
- services/src/generated/main/java/io/grpc/instrumentation/v1alpha/StatsResponse.java
- services/src/generated/main/java/io/grpc/instrumentation/v1alpha/StatsResponseOrBuilder.java
- services/src/main/java/io/grpc/services/MonitoringUtil.java
- services/src/main/proto/grpc/instrumentation/v1alpha/monitoring.proto
- services/src/test/java/io/grpc/services/MonitoringUtilTest.java
We filled in some of the missing type definitions in `monitoring.proto`. One of these, `StatsResponse`, is the same as the nested type `CanonicalRpcStats.View`. This PR drops the now-redundant `CanonicalRpcStats.View` and replaces its use with the new `StatsResponse`. 
This is a breaking change to existing use of the monitoring service, but we have it marked as experimental/v1alpha so I believe this is fine. If not, I will leave in `CanonicalRpcStats.View` with a todo to remove it in a later version.
> services: update monitoring.proto

- core/src/main/java/io/grpc/internal/KeepAliveManager.java
- core/src/test/java/io/grpc/internal/KeepAliveManagerTest.java
- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
`keepAlivedManager#onTransportshutdown` should not be called in `transport.shutdown()` because it is possible that there are still open RPC streams, and maybe inactive, so keepalive is still needed.
> Okhttp: keepAlivedManager#onTransportShutdown moved from shutdown to stopIfNecessary and refactored

- core/src/main/java/io/grpc/LoadBalancer.java
The deprecation happens in 1.2.0. Now we can delete it for the next release.
> core: delete deprecated pickSubchannel()

- core/src/main/java/io/grpc/internal/KeepAliveManager.java
- core/src/test/java/io/grpc/internal/KeepAliveManagerTest.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
Modified KeepAliveManager to use a Pinger interface, which can send ping or shutdown transport for both server and client.
> core,netty,okhttp: KeepAliveManager with Pinger

- benchmarks/src/jmh/java/io/grpc/benchmarks/netty/HandlerRegistryBenchmark.java
This appears to have been broken by 3df1446 (which was reverted and
later rolled forward again in 66ab956).
Without this fix, the ServerServiceDefinition.Builder realizes that a
method is registered that isn't in the ServiceDescriptor. Swapping to a
different constructor causes the builder to generate the
ServiceDescriptor for us.
```
java.lang.IllegalStateException: No entry in descriptor matching bound method E6Cq77iKGNKVCGyVOqq8DqEazX9AcBdPNoMj86c3I5zo4Tv77U/vLe7QS7mhUfaooN7eYdBW7gd9oyV.kc9I0zJumfuUbhyb7SR1u
at io.grpc.ServerServiceDefinition$Builder.build(ServerServiceDefinition.java:164)
at io.grpc.benchmarks.netty.HandlerRegistryBenchmark.setup(HandlerRegistryBenchmark.java:107)
```
> benchmarks: Fix broken building of ServerServiceDefinition

- benchmarks/src/jmh/java/io/grpc/internal/StatsTraceContextBenchmark.java
- core/src/main/java/io/grpc/internal/StatsTraceContext.java
This removes a needless warning, and isn't much slower.  Also this
includes a benchmark for StatsTraceContext to measure the overhead
for creation.  It adds about 40ns per RPC.  Optimization will come
after structural changes are made to break the dependency on
Census.
> core,benchmarks: use Atomics for StatsTraceContext

- core/src/main/java/io/grpc/internal/ClientCallImpl.java
We got a `NullPointerException` from `ClientCallImpl#startDeadlineTimer` when a new Call is created after a Netty channel is terminated. Here is a stacktrace:
```
INTERNAL: java.lang.NullPointerException
at io.grpc.internal.ClientCallImpl.startDeadlineTimer(ClientCallImpl.java:320)
at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:253)
```
The following code snippet reproduces the bug:
```
ManagedChannel channel = NettyChannelBuilder.forAddress(host, port)
.usePlaintext(true)
.build();
channel.shutdown();
Thread.sleep(1000);
GreeterGrpc.GreeterBlockingStub stub =
GreeterGrpc.newBlockingStub(channel)
.withDeadlineAfter(10, TimeUnit.SECONDS);
stub.sayHello(HelloRequest.newBuilder().setName("world").build());
```
The issue was that `ClientCallImpl` is created from …
> core: Do not call startDeadlineTimer when is deadlineCancellationExecutor is null

- core/src/main/java/io/grpc/ManagedChannelBuilder.java
The behavior of how the application's User-Agent is used changed in
2247ad2. But the Javadoc was not updated.
> core: Fix User-Agent Javadoc in ManagedChannelBuilder

- core/src/main/java/io/grpc/internal/MessageDeframer.java
Compression frames existed in a very early iteration of the gRPC
protocol. It was killed long ago.
> core: Remove internal comment referencing compression frames

- core/src/main/java/io/grpc/internal/KeepAliveManager.java
executor.schedule() will "eat" any exceptions thrown by the Runnables,
because the Future is expected to be used to see them. However, we never
call get() on the Future, so we need to just the exceptions like we do
elsewhere in this case.
> core: Wrap keepalive runnables with exception logging

- benchmarks/src/jmh/java/io/grpc/netty/OutboundHeadersBenchmark.java
- core/src/main/java/io/grpc/internal/AbstractClientStream2.java
- core/src/main/java/io/grpc/internal/AbstractStream2.java
- core/src/main/java/io/grpc/internal/Framer.java
- core/src/main/java/io/grpc/internal/MessageFramer.java
- core/src/test/java/io/grpc/internal/AbstractClientStream2Test.java
- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/main/java/io/grpc/netty/NettyClientStream.java
- netty/src/main/java/io/grpc/netty/Utils.java
- netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
Based on ejona86@89f0d8c. It adds a writeHeaders API to AbstractClientStream2.Sink. When sending a GET request, writeHeaders call will be delayed until we have the request payload and halfClose is called. The request payload can then be sent in the query string.
> support GET verb in AbstractClientStream2

- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
d116cc9 fixed the NPE, but the initialization of the manager happened
_after_ newHandler() was called, so a null manager was passed to the
handler.
Fixes #2828 
------
I haven't tested this manually yet. I wanted to send it out to get opinions on whether this is the fix we want. It seems considerably less invasive than some other options we were discussing.
> netty: Fix client keepalive initialization (again)

- netty/src/main/java/io/grpc/netty/KeepAliveEnforcer.java
- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
- netty/src/test/java/io/grpc/netty/KeepAliveEnforcerTest.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
Everything is currently permitted, but I've tested with other
configurations and all tests pass. I'll set the restrictive default at
the same time as adding a configuration API.
> netty: Add server keepalive enforcement

- core/src/main/java/io/grpc/internal/GrpcUtil.java
- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/test/java/io/grpc/netty/NettyChannelBuilderTest.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
To be in line with `NettyServerBuilder` APIs
- Deleted `enableKeepAlive(boolean enable)` and
`enableKeepAlive(boolean enable, long keepAliveDelay, TimeUnit delayUnit, long keepAliveTimeout, 
TimeUnit timeoutUnit)`
which never worked in v1.2
- Added `keepAliveTime(long keepAliveTime, TimeUnit timeUnit)` and
`keepAliveTimeout(long keepAliveTimeout, TimeUnit timeUnit)`
> netty: refactor NettyChannelBuilder keepalive API

- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
Each time helper.updatePicker() is called, the Channel will re-process
all pending streams with the new picker.  If the old picker is
equivalent to the old one, it's wasteful.
This is also needed to make our internal integration test easier.
Because the load-balancer may send address list that is identical to the
previous one, just to update the TTL.  Without this change, new picker
replaces the old picker even if they carry the same list, which
effectively resets the round-robin pointer.  This causes a little
imbalance between test backends, resulting in test failure.
> grpclb: skip picker updates that have no effect

- netty/src/main/java/io/grpc/netty/NettyServer.java
- netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
- netty/src/main/java/io/grpc/netty/NettyServerTransport.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
- netty/src/test/java/io/grpc/netty/NettyServerTest.java
Now that there is a config, the new defaults are now being enabled.
Previously there were no default limits. Now keepalives may not be more
frequent than every 5 minutes and only when there are outstanding RPCs.
> netty: Add config for server keepalive enforcement

- core/src/main/java/io/grpc/LoadBalancer.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
This allows LoadBalancers to trace the activities, including the final
status of the stream that is created as a result of the pick.
@ejona86 Although earlier we talked about switching `PickResult` to builder pattern, I found this particular change works fine with the current pattern. Let me know if you prefer doing the switch now.
> core: allow SubchannelPicker to return a StreamTracer factory.

- netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
While we can use permit/deny in this one case, it isn't generalizable to
other cases. In order to avoid always questioning how to deal with
boolean config options, just pass the boolean in all cases.
This mirrors what is being done with the client-side's
keepAliveWithoutCalls.
These methods were very recently added, so there is a low risk of
breakage.
> netty: Pass boolean to builder instead of permit/deny specialized naming

- core/src/main/java/io/grpc/internal/CensusStreamTracerModule.java
- core/src/test/java/io/grpc/internal/CensusStreamTracerModuleTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
Per spec this metric should be calculated on the server and sent back to
the client, for which the mechanism is not currently defined. As it's
not a required metric, we remove the incorrect implementation for now.
Internal ref: b/37208451
> core: remove incorrect reporting of CLIENT_SERVER_ELAPSED_TIME.

- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
They were added in #2863. In TestServiceClient metricsExpected() returns
false because server-side stats is not available, but client-side stats
are there, thus these asserts would fail.
Resolves grpc/grpc/issues/10552
> testing: remove negative asserts about stats.

- okhttp/src/test/java/io/grpc/okhttp/OptionalMethodTest.java
- okhttp/third_party/okhttp/java/io/grpc/okhttp/internal/OptionalMethod.java
When OptionalMethod attempts to invoke a method on a private class that inherits from a superclass that has a public method, it fails.
This happens after changes to the library visibility in conscrypt.
> okhttp: Add OptionalMethod support for private classes

- core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
- core/src/main/java/io/grpc/internal/CensusStreamTracerModule.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/MessageFramer.java
- core/src/main/java/io/grpc/internal/OobChannel.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
- core/src/test/java/io/grpc/inprocess/InProcessTransportTest.java
- core/src/test/java/io/grpc/internal/CensusStreamTracerModuleTest.java
- core/src/test/java/io/grpc/internal/MessageFramerTest.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
I did not fix the unused statsTraceCtx in
AbstractClientStream2.GetFramer. Instead, I opened
https://github.com/grpc/grpc-java/issues/2896
> core: Fix unused variables

- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
- compiler/src/java_plugin/cpp/java_generator.cpp
- compiler/src/test/golden/TestService.java.txt
- compiler/src/testLite/golden/TestService.java.txt
- compiler/src/testNano/golden/TestService.java.txt
- grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
- services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java
- services/src/generated/main/grpc/io/grpc/instrumentation/v1alpha/MonitoringGrpc.java
- services/src/generated/main/grpc/io/grpc/reflection/v1alpha/ServerReflectionGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/AnotherDynamicServiceGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/DynamicServiceGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/ReflectableServiceGrpc.java
- testing-proto/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
- testing-proto/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
- testing-proto/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
- testing-proto/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
Ports compiler code to use builder code
Related to https://github.com/grpc/grpc-java/pull/2625
cc @carl-mastrangelo
> compiler: move over to method descriptor builder

- core/src/main/java/io/grpc/internal/AbstractClientStream.java
- core/src/main/java/io/grpc/internal/MessageDeframer.java
- core/src/main/java/io/grpc/internal/MessageFramer.java
- core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
- core/src/test/java/io/grpc/internal/MessageDeframerTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
Parallel of https://github.com/grpc/grpc/pull/10612
The change in ACS brings it in line with ACS2
> core: use RESOURCE_EXHAUSTED for max message size failures

- core/src/main/java/io/grpc/internal/AbstractClientStream2.java
- core/src/main/java/io/grpc/internal/Framer.java
- core/src/main/java/io/grpc/internal/Http2ClientStreamTransportState.java
- core/src/test/java/io/grpc/internal/AbstractClientStream2Test.java
- core/src/test/java/io/grpc/internal/Http2ClientStreamTransportStateTest.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- okhttp/src/main/java/io/grpc/okhttp/OutboundFlowController.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientStreamTest.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
One thing worth noting is that I overrided onStreamDeallocated to get notification when transportReportStatus is called and stream is considered finished. Then I can remove the stream from transport map and also reset the stream if the framer is not yet closed.
> Move okhttp to AbstractStream2

- core/src/main/java/io/grpc/internal/AbstractClientStream2.java
- core/src/main/java/io/grpc/internal/StatsTraceContext.java
- core/src/test/java/io/grpc/internal/AbstractClientStream2Test.java
Also define the expected call sites of StatsTraceContext.
Resolves #2896
> core: record stats for GET requests

- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
We aren't upgrading yet, because we don't want to begin using the new
Mockito APIs. But all the tests now pass with the newer version. There
are a lot of warnings that can't be fixed until we bump the mockito
version.
> all: Fix basic compatibility with Mockito 2.7.19

- core/src/main/java/io/grpc/ServerCall.java
- core/src/main/java/io/grpc/internal/ServerCallImpl.java
- core/src/main/java/io/grpc/internal/ServerStream.java
- core/src/test/java/io/grpc/internal/ServerCallImplTest.java
Resolves #727 
Also mark `ServerStream.getAuthority()` as nullable because `AbstractServerStream.getAuthority()` already returns null.
> core: add ServerCall.getAuthority()

- core/src/main/java/io/grpc/ClientStreamTracer.java
- core/src/main/java/io/grpc/internal/StatsTraceContext.java
- core/src/test/java/io/grpc/internal/CensusStreamTracerModuleTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
This is a partial backport of #2921 into v1.3.x
The addition of inboundHeaders is not backported as it turns out to be
non-trivial as OkHttp is still on AbstractClientStream on v1.3.x while
has switched to AbstractClientStream2 on master.
> core: rename headersSent to outboundHeaders.

- core/src/main/java/io/grpc/ServerStreamTracer.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
- core/src/main/java/io/grpc/internal/StatsTraceContext.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
This is needed for GRPCLB server-side load reporting, which needs to record
the authority and peer identity.
> core: pass ServerCall to ServerStreamTracer.

- netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
cover the missed coverage of `ping` and `onPingTimeout` in `NettyServerHandler`
> netty: more coverage on server keepalive

- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
- grpclb/src/main/java/io/grpc/grpclb/LbAddressGroup.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
This has the limitation that all LB addresses must have the same
authority. Future work will try to remove that limitation.
> grpclb: Flatten LB addresses to use pick-first

- core/src/main/java/io/grpc/internal/AbstractClientStream2.java
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/TestCases.java
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
- interop-testing/src/test/java/io/grpc/testing/integration/TestCasesTest.java
- netty/src/main/java/io/grpc/netty/NettyClientStream.java
- netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
- testing-proto/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
- testing-proto/src/generated/main/java/io/grpc/testing/integration/Test.java
- testing-proto/src/main/proto/io/grpc/testing/integration/test.proto
This PR has two commits:
1. Remove the `grpc-payload-bin=` prefix from outgoing GET requests. This brings the implementation inline with C++ and our test server behind GFE.
2. Add the cacheable_unary interop test, which verifies that GET requests sent to a server behind a caching proxy are correctly sent and responses cached.
> Add cacheable_unary interop test

- core/src/main/java/io/grpc/internal/GrpcUtil.java
The App Engine development appserver imposes similar ClassLoader restrictions to the production environment. This patch allows for development of grpc using code in the development appserver. First grpc patch - please let me know if I missed any of the contributing guidelines!
> core: Add support for the AppEngine development sandbox

- build.gradle
- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
- core/src/main/java/io/grpc/internal/CensusStatsModule.java
- core/src/main/java/io/grpc/internal/CensusStreamTracerModule.java
- core/src/main/java/io/grpc/internal/CensusTracingModule.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/test/java/io/grpc/internal/CensusModulesTest.java
- core/src/test/java/io/grpc/internal/CensusStreamTracerModuleTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/AutoWindowSizingOnTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyLocalChannelTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/TransportCompressionTest.java
- testing/src/main/java/io/grpc/internal/testing/StatsTestUtils.java
Main implementation is in `CensusTracingModule`.
Also a few fix-ups in the stats implementation `CensusStatsModule`:
- Change header key name from `grpc-census-bin` to `grpc-tags-bin`
- Server does not fail on header parse errors. Uses the default instead.
DO NOT SUBMIT: currently using snapshot version of Census. Must switch to a release version before submitting.
> core: integrate instrumentation-java (Census) tracing

- grpclb/src/main/java/io/grpc/grpclb/GrpclbConstants.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
It is accessed by the server-side load-reporting code which is from a
different package.
> grpclb: expose the token metadata key.

- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
- core/src/main/java/io/grpc/internal/CensusStatsModule.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/test/java/io/grpc/internal/CensusModulesTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/AutoWindowSizingOnTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyLocalChannelTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/TransportCompressionTest.java
Static mutable flags are evil.  Turned them to options on channel
builder.  Also restore the local stats recording by default, because
these flags were added with the concern of wire-compatibility, but not
local feature.
> core: stop using static flags for Census control.

- build.gradle
It previously failed because of the errorprone dependency and the -Xep:
arguments passed to javac
> build: fix -PerrorProne=false

- stub/src/main/java/io/grpc/stub/ClientCalls.java
All that the `call` field was used for was to call `request` and nothing else. The `request` can be done by the `adapter` field, so the `call` field is redundant.
> stub: rm redundant call field in StreamObserverToCallListenerAdapter

- build.gradle
- protobuf/build.gradle
Addresses https://github.com/grpc/grpc-java/issues/2961.
Thanks to @zhangkun83 who identified a similar issue with instrumentation-java, I've sent https://github.com/googleapis/api-common-java/pull/27 to make their dependency on auto-value compileOnly, which will enable remove the remaining `exclude group` from the dependency on `libraries.google_api_protos`. AFAIK the presence of this rule doesn't impact https://github.com/grpc/grpc-java/issues/2961.
> build,protobuf: update google_api_protos dependency

- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
- compiler/src/java_plugin/cpp/java_generator.cpp
- compiler/src/test/golden/TestService.java.txt
- compiler/src/testLite/golden/TestService.java.txt
- compiler/src/testNano/golden/TestService.java.txt
- grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
- services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java
- services/src/generated/main/grpc/io/grpc/instrumentation/v1alpha/MonitoringGrpc.java
- services/src/generated/main/grpc/io/grpc/reflection/v1alpha/ServerReflectionGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/AnotherDynamicServiceGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/DynamicServiceGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/ReflectableServiceGrpc.java
- testing-proto/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
- testing-proto/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
- testing-proto/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
- testing-proto/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
FutureStubs only support unary calls
> compiler: remove streaming calls from javadoc for newFutureStub

- examples/android/helloworld/app/proguard-rules.pro
I have no clue why this isn't needed for routeguide as well, but
routeguide is compiling fine without the dontwarn.
> android-helloworld: Ignore proguard warnings for javax.naming

- examples/android/helloworld/app/src/main/java/io/grpc/helloworldexample/HelloworldActivity.java
ActionBarActivity has been deprecated for 2+ years and has been
extending AppCompatActivity for all that time. This should be a no-op.
> android-helloworld: Remove usage of ActionBarActivity

- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/Http2ClientStreamTransportState.java
- core/src/main/java/io/grpc/internal/InternalSubchannel.java
- core/src/main/java/io/grpc/internal/MoreThrowables.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
- core/src/main/java/io/grpc/internal/WithLogId.java
- netty/src/main/java/io/grpc/netty/StreamIdHolder.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
Did a code analysis on javadoc. There are some broken links in javadoc, although none of them are in public and non-internal API.
> javadoc: fix broken links in javadoc

- core/src/main/java/io/grpc/ManagedChannelBuilder.java
- core/src/main/java/io/grpc/NameResolver.java
- core/src/main/java/io/grpc/Status.java
- core/src/main/java/io/grpc/StatusException.java
- core/src/main/java/io/grpc/StatusRuntimeException.java
some links in javadoc are not in correct format and produced build warnings:
```
/usr/local/google/home/zdapeng/git/grpc-java/core/src/main/java/io/grpc/ManagedChannelBuilder.java:49: warning - Tag @see: can't find forTarget() in io.grpc.ManagedChannelBuilder
5 warnings
/usr/local/google/home/zdapeng/git/grpc-java/core/src/main/java/io/grpc/NameResolver.java:89: warning - Tag @link: can't find NameResolver in io.grpc.NameResolver.Factory
/usr/local/google/home/zdapeng/git/grpc-java/core/src/main/java/io/grpc/Status.java:235: warning - Tag @link: can't find Status in io.grpc.Status.Code
/usr/local/google/home/zdapeng/git/grpc-java/core/src/main/java/io/grpc/StatusException.java:63: warning - Tag @link: can't find Status in io.grpc.StatusException …
```
> doc: fix broken links

- core/src/main/java/io/grpc/ServerBuilder.java
Also, remove an erroneously added ExperimentalApi annotation.  The
method was non experimental as of the 1.0.0 release.
> core: document ServerBuilder return values and method history

- services/src/main/java/io/grpc/services/HealthServiceImpl.java
- services/src/main/java/io/grpc/services/HealthStatusManager.java
- services/src/test/java/io/grpc/services/HealthStatusManagerTest.java
`HealthStatusManager` should not expose server stub methods, because it is wrong to call server stub methods directly.
> services: HealthStatusManager not to expose server stub methods

- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
fixes #2982 
The problem is `grpcHandler.handleProtocolNegotiationCompleted` can happen before `ctx.pipeline().replace(this, null, grpcHandler)` in which `handlerAdded()` is called
Moved `keepAliveManager.onTransportStarted()` inside `handlerAdded()` to fix it.
Tested with manual interoptest and it's working now.
Removed the test case `keepAliveManagerStarted() ` that is not functioning. The test case `keepAliveManager_pingSent()` already covered it.
> netty: fix server keepalive not initialized bug

- core/src/main/java/io/grpc/CallOptions.java
Deprecated since 1.3.0
Resolves #1766
> core: delete deprecated affinity API.

- core/src/test/java/io/grpc/MetadataTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/ProxyTest.java
The expected value should be first.
> Fix incorrect assertEquals argument ordering

- okhttp/third_party/okhttp/java/io/grpc/okhttp/internal/framed/Http2.java
Intended to address https://github.com/grpc/grpc-java/issues/3032.
This was addressed in OkHttp3 by https://github.com/square/okhttp/pull/2299, but I'm fairly certain their fix still contains a bug - they parse the settings id as a Java short, so anything in the experimental range (such as gRPC C++ servers are using) is a negative number, and the linked pull request's use of `break` instead of `continue` results in an index out of bounds exception in `Settings#set`. I'll follow up on that with the OkHttp repo separately. 
@ejona86 I'm not sure of the status of the code in okhttp/third_party - since this is "shaded" from OkHttp2, can we patch it, or do we need to move the modifications somehow out of the third_party/ subdirectory? As-is, I'm also not sure where to put tests for this, but …
> okhttp: ignore unknown HTTP/2 settings

- compiler/src/java_plugin/cpp/java_generator.cpp
The code uses std::back_insert_iterator which is part of the iterator header. The header is not included though.
We (bazel) noticed the build failing on Windows when using the Visual Studio C++ compiler.
> compiler: Fix compilation error

- core/src/main/java/io/grpc/internal/ServerCallImpl.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
- core/src/test/java/io/grpc/internal/FakeClock.java
- core/src/test/java/io/grpc/internal/FakeClockTest.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
When we cancel a stream, we must 1) set both ServerCall.isCancelled() and CancellableContext.isCancelled() to be true, as well 2) notify any listeners that the stream is now cancelled. Today, this happens in JumpToApplicationThreadServerStreamListener therefore both 1 and 2 happen in a serialized executor and may become queued. This diff moves 1 to be executed immediately on the cancelling thread's context (we are still required to run 2 in the executor for correctness reasons). The result is that anyone polling for isCancelled() in either of the two places will immediately see the update rather than waiting.
Fixes #2112
> Server side cancellations should promptly inform server

- core/src/main/java/io/grpc/internal/ServerImpl.java
Calling CancellableContext#close() multiple times does not cause problems, but is unnecessary here. The return value of getListener() is a ServerStreamListenerImpl, which already calls CancellableContext#cancel() inside of the `finally` block of ServerStreamListener#closed().
> core: JumpToApplication...Listener should not close context

- core/src/main/java/io/grpc/internal/GrpcUtil.java
- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
CC @cr22rc
Addresses documentation issue from #2935
> netty: Clarify max header list size configuration

- testing/src/main/java/io/grpc/testing/GrpcServerRule.java
- testing/src/test/java/io/grpc/testing/GrpcServerRuleTest.java
otherwise it cannot take effect
> testing: GrpcServerRule#directExecutor can only be called at instantiation

- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/ForwardingNameResolver.java
- core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
The current implementation has a bug where certain methods are not forwarded to the delegate.
> core: OverrideAuthorityNameResolverFactory should forward refresh()

- interop-testing/build.gradle
In response to https://github.com/grpc/grpc/issues/11258 / https://github.com/grpc/grpc-java/issues/3032, we should run our full suite of interop tests using OkHttp. As best I can tell, OkHttp cannot use ALPN unless it has the ALPN agent, which was [removed](https://github.com/grpc/grpc-java/commit/9466eb5014bd4ed2fd0af2567c605ae79a27e86b#diff-dbbdfba18c8958c51b031ef112a6fa7c) a while ago from the build rule, back when we were still using the boot classpath. This adds it back in, so that the `--use_okhttp=true` option in the test client is able to use TLS.
> interop-testing: add alpnagent to support okhttp in test client

- examples/README.md
- examples/build.gradle
- examples/pom.xml
- examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java
- examples/src/test/java/io/grpc/examples/header/HeaderClientInterceptorTest.java
- examples/src/test/java/io/grpc/examples/header/HeaderServerInterceptorTest.java
- examples/src/test/java/io/grpc/examples/helloworld/HelloWorldClientTest.java
- examples/src/test/java/io/grpc/examples/helloworld/HelloWorldServerTest.java
migrated simple tests using `GrpcServerRule`.
Kept the low level in-process channel setup and tear down code for the RouteGuide example to show how users can use in-process directly to set more custom channel builder options when needed.
resolves #2490
> examples: migrate unittest examples to GrpcServerRule

- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- netty/src/test/java/io/grpc/netty/NettyChannelBuilderTest.java
Creating the SslContext can throw, generally due to broken ALPN. We want
that to propagate to the caller of build(), instead of within the
channel where it could easily cause hangs.
We still delay creation until actual build() time, since TLS is not
guaranteed to work and the application may be configuring plaintext or
similar later before calling build() where SslContext is unnecessary.
The only externally-visible change should be the exception handling.
I'd add a test, but the things throwing are static and trying to inject
them would be pretty messy.
Fixes #2599
> netty: Eagerly create SslContext

- context/src/main/java/io/grpc/Context.java
Normally I would make this final, but CancellableContext extends it, and it's public API now.  We can't really add `@DoNotMock` since it is a dependency, even as compileOnly, since the retention is runtime.  It seems a menacing comment is the best we can do.
> context: declare that context should not be mocked

- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- netty/src/test/java/io/grpc/netty/NettyChannelBuilderTest.java
Creating the SslContext can throw, generally due to broken ALPN. We want
that to propagate to the caller of build(), instead of within the
channel where it could easily cause hangs.
We still delay creation until actual build() time, since TLS is not
guaranteed to work and the application may be configuring plaintext or
similar later before calling build() where SslContext is unnecessary.
The only externally-visible change should be the exception handling.
I'd add a test, but the things throwing are static and trying to inject
them would be pretty messy.
Fixes #2599
> netty: Eagerly create SslContext (backport)

- core/src/main/java/io/grpc/ManagedChannelBuilder.java
- core/src/main/java/io/grpc/NameResolverProvider.java
We don't want people to be desensitized to the Internal annotation.
NameResolverProvider should have probably been ExperimentalApi from the
start, but it was copied from ManagedChannelProvider.
Theoretically, ManagedChannelProvider could be marked ExperimentalApi as
well, but there are no known use cases for doing so since making an
alternative ManagedChannel implementation is quite difficuilt and we
aren't aware of anybody interested in doing so. That isn't the case for
NameResolverProvider; NameResolverProvider is core to 'targets' being
useful.
CC @zhangkun83
> core: Mark NameResolverProvider experimental and clarify docs

- core/src/main/java/io/grpc/MethodDescriptor.java
- core/src/test/java/io/grpc/MethodDescriptorTest.java
- core/src/test/java/io/grpc/ServiceDescriptorTest.java
- core/src/test/java/io/grpc/internal/CensusModulesTest.java
Depends on #2886, related to #2625.
cc @carl-mastrangelo
> core: deprecate MethodDescriptor.create

- core/src/main/java/io/grpc/internal/KeepAliveManager.java
Since netty 4.1.11-final, netty/netty#6627 has been fixed.
> core: scheduler.schedule() can be used normally

- core/src/main/java/io/grpc/internal/ServerCallImpl.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
Currently, inbound headers are processed in the transport thread, but the resulting new stream's decompressor is not set until the `ServerCallImpl` constructor is invoked from a `wrappedExecutor` thread. The `ServerCallImpl` constructor will parse the headers and, if necessary, call `MessageDeframer#setDecompressor` to set the decompressor. This is not thread-safe, as incoming data frames may simultaneously be consumed by the deframer in the transport thread.
This PR moves the call to `setDecompressor` into the transport thread. This is a similar issue to https://github.com/grpc/grpc-java/issues/2865 on the client side. My in-progress move of client deframing to the client thread made the compression test (https://github.com/grpc/grpc-java/issues/2157) extra flaky, but due to this race …
> core: set server stream decompressor in transport thread

- android-interop-testing/app/build.gradle
- android-interop-testing/app/proguard-rules.pro
- android-interop-testing/app/src/androidTest/java/io/grpc/android/integrationtest/InteropTesterTest.java
This adds an instrumented test which runs the Android interops against our deployed test server. This will be used in Firebase test lab to get tests running on Android emulators and/or devices.
> android-interop-testing: instrumented interop tests

- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/FixedObjectPool.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/OverrideAuthorityNameResolverFactory.java
- core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
Add some example tests for easier fields in AbstractManagedChannelImplBuilder.
Many fields are no longer Nullable, in order to move logic from construction to
mutation, which eases testing and simplifies cross-class interactions.
The nameResolverFactory comment starting 'Avoid loading the provider unless
necessary' was outdated and has not been a concern since #2071 which swapped to
a hard-coded list on Android.
Consider this a working RFC. If we like it, there are many more places we can apply
the same pattern and apply more cleanups. Specific details can maybe be done
differently, but before harping on the details, it'd be good to determine if we like the
general approach.
This is low priority :smile:
> core: Simplify ChannelImpl constructor; testable Builder

- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
Add unit tests to enforce behavior that we already expect today.
fixes #3083
> core: ensure ServerStream and ClientStream become noops after closing

- core/src/main/java/io/grpc/internal/ServerCallImpl.java
- core/src/main/java/io/grpc/internal/ServerStream.java
- core/src/test/java/io/grpc/internal/ServerCallImplTest.java
- examples/src/test/java/io/grpc/examples/routeguide/RouteGuideClientTest.java
- stub/src/main/java/io/grpc/stub/ServerCalls.java
- stub/src/test/java/io/grpc/stub/ServerCallsTest.java
The current check in ServerCallImpl is theoretically unsafe (#3059). Move that check into the stub, and expand the unit tests to cover other interesting edge cases on the server side:
- client sends one, but zero requests received at onHalfClose
- client sends one, but > 1 requests received at onHalfClose
- server sends one, but zero responses sent at onComplete
- server sends one, but > 1 responses sent via onNext
fixes #2243 
fixes #3059
> stub: detect invalid states on server side (eg zero responses for unary)

- all/build.gradle
- core/build.gradle
- netty/build.gradle
core's sources already have filters applied, so it isn't necessary to
copy them to all.
This filters InternalNotifyOnServerBuild, which is marked experimental. What's up with that one @ericgribkoff?
I should probably add the Netty Internal* classes to this PR as well.
> all: Filter out Internal* classes from Javadoc

- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/ForwardingNameResolver.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/OverrideAuthorityNameResolverFactory.java
- core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
- core/src/test/java/io/grpc/internal/OverrideAuthorityNameResolverTest.java
The current implementation has a bug where certain methods are not forwarded to the delegate.
This is essentially the same as e4f1f398a0f92cc09054c351ea6c5e6816459c77 which was merged to the v1.4.x branch. This PR uses the new license header.
Fixes #3061
> core: OverrideAuthorityNameResolverFactory should forward refresh() (#3062)

- core/src/main/java/io/grpc/Metadata.java
Interning strings isn't needed much any more since keys are now
compared by byte value.  Also, intern is slow (about 150ns per)
which affects code that creates keys often.  Lastly, older
versions of Java don't garbage collect interned strings, which
lowers the applications stability.
> core: don't intern Metadata keys

- buildscripts/kokoro/windows.bat
- buildscripts/kokoro/windows.cfg
This adds the necessary files to run the current Jenkins Windows tests on Kokoro.
> Add config and build files to run Windows tests on Kokoro

- core/src/main/java/io/grpc/InternalServerInterceptors.java
- core/src/main/java/io/grpc/ServerBuilder.java
- core/src/main/java/io/grpc/ServerInterceptors.java
- core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
This adds server-wide interceptors that applies to all call handlers.
Because ServerCallHandler is acquired per request, and can be dynamicly
provided by the fallback registry, the interceptors have to be installed
on a per-request basis.  This adds a few object allocations per request,
which is acceptable.
> core: ServerBuilder.intercept().

- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
The listener to the connect future depends on the channel pipeline being intact. But the way it is attached allows the connect attempt to fail, and have the entire pipeline being torn down by netty before the `.addListener` actually runs. The result is that the listener will be attached to an already completed future, and the logic will be applied to an empty pipeline.
The fundamental problem is that there are two threads, the grpc thread, and the netty thread. This PR moves the listener attaching code into the netty thread, guaranteeing the listener is attached before any connection is made. It makes more sense for the code to live inside `AbstractBufferingHandler`, since handlers are generally free to swallow exceptions (the alternative is to make `NettyClientHandler` forward exceptions …
> netty: fix race condition for listeners attaching to connect future

- core/BUILD.bazel
It is now using io.grpc.internal.SerializingExecutor.
> core: Fix Bazel building for :util

- netty/src/main/java/io/grpc/netty/HandlerSettings.java
- netty/src/main/java/io/grpc/netty/InternalHandlerSettings.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/main/java/io/grpc/netty/NettyHandlerSettings.java
- netty/src/main/java/io/grpc/netty/NettyServerTransport.java
InternalHandlerSettings is part of "netty:internal" inside google,
which is used to allow controlled exposure of internals.
"netty:internal" depends on "netty", which consists of the rest of the
netty subproject.  Therefore, "netty" should not depend on
"netty:internal".
> netty: InternalHandlerSettings should not be used by non-Internal classes

- netty/src/main/java/io/grpc/netty/NettyHandlerSettings.java
Bug introduced in commit 8c017337eb03b7e77ae97fa15b0f761d98466d2b
> netty: fix NettyHandlerSettings synchronized on wrong object.

- core/src/test/java/io/grpc/util/UtilServerInterceptorsTest.java
Our internal DoNotMock applies to spy() too.
> core: stop spying ServerCall in UtilServerInterceptorsTest.

- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
tldr: the NOOP_MESSAGE fence operation is racey; we are not flushing
the channel and the application thread is not waiting for the
operation to complete.
Details:
On windows, the serverNotListening test sometimes still fails with this
problem:
https://gist.github.com/zpencer/077da915c70e9bd75624932cfa21aa9d
The test fails on this assertion:
```
verify(mockClientTransportListener, timeout(TIMEOUT_MS)).transportTerminated();
```
The call being verified should have been called when the NOOP_MESSAGE
fails. Because the call to `NettyClientTransport.start` returns a null
for the success case, the caller immediately starts the verification
with a 1s timeout. We should return a Runnable that tells the caller
to block until the fence operation is done. We also need to flush the
channel to ensure …
> netty: client transport needs to flush fence operation

- all/build.gradle
grpc-protobuf-lite brings in protobuf-lite as a dependency, which has
different versions of classes in protobuf. This causes duplicate classes
on the class path, which easily breaks things. Since lite the lite
runtime/codegen is incompatible with full protobuf, it makes sense to
only depend on one of the two.
grpc-protobuf actually already has a dependency on grpc-protobuf-lite,
but excludes the protobuf-lite dependency, making the dep safe. But this
is more of an implementation detail.
We only change deps so that JavaDoc, code coverage, and similar will
still include grpc-protobuf-lite.
Fixes #2985 
Doing this now since it seems a user (in #3149) has hit this problem.
Previously it was theoretical.
> all: Don't depend directly on grpc-protobuf-lite

- .gitignore
- examples/BUILD.bazel
- examples/README.md
- examples/WORKSPACE
If you prefer to use Maven:
```
$ mvn verify
$ # Run the server
$ mvn exec:java -Dexec.mainClass=io.grpc.examples.helloworld.HelloWorldServer
$ # In another terminal run the client
$ mvn exec:java -Dexec.mainClass=io.grpc.examples.helloworld.HelloWorldClient
```
If you prefer to use Bazel:
```
(With Bazel v0.4.5 or above.)
$ bazel build :hello-world-server :hello-world-client
$ # Run the server:
$ bazel-bin/hello-world-server
$ # In another terminal run the client
$ bazel-bin/hello-world-client
```
> examples: add bazel build example

- repositories.bzl
Although this repo is not used in bazel build internally, it is exposed in a bzl rule.
> bazel: update netty tcnative to 2.0.5

- examples/pom.xml
Everyone using maven should really use the rule, in order to prevent
accidentally using an older version of a common library, like protobuf.
> examples: Enable maven enforcer requireUpperBoundDeps

- core/src/main/java/io/grpc/inprocess/InProcessTransport.java
- core/src/main/java/io/grpc/internal/AbstractClientStream.java
- core/src/main/java/io/grpc/internal/AbstractServerStream.java
- core/src/main/java/io/grpc/internal/AbstractStream.java
- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/ClientStream.java
- core/src/main/java/io/grpc/internal/DelayedStream.java
- core/src/main/java/io/grpc/internal/NoopClientStream.java
- core/src/main/java/io/grpc/internal/ServerStream.java
- core/src/main/java/io/grpc/internal/Stream.java
- core/src/test/java/io/grpc/internal/DelayedStreamTest.java
Previously ClientCallImpl's stream listener would call
stream.setDecompressor(), but this has always been a bit strange as the
only case where the call listener calls the stream and forms a bit of a
loop. It also turned out to be racy in the presence of
DelayedClientStream since DelayedClientStream does not guarantee that
the listener has processed before returning.
Now we let the stream handle decompressor selection itself. Compressor
selection on client and server and decompressor selection on server
remain unchanged. Nothing prevents them from being changed, other than
it is currently unnecessary to fix the severe compressionTest flake.
Fixes #2865
Fixes #2157
> core: Move client-side decompressor selection to stream

- core/src/main/java/io/grpc/InternalNotifyOnServerBuild.java
It is misnamed if it is @ExperimentalApi. Even being @Internal is
strange, since nothing in io.grpc actually uses it and so it could
actually be in io.grpc.internal.
I'm not trying to fix the API, but just make it slightly more
consistent.
> core: Mark InternalNotifyOnServerBuilder @Internal

- auth/build.gradle
- context/build.gradle
- core/build.gradle
- netty/build.gradle
- okhttp/build.gradle
- protobuf-lite/build.gradle
- protobuf-nano/build.gradle
- protobuf/build.gradle
- services/build.gradle
- stub/build.gradle
This is important for stable builds, as if the signature changes the old source
may no longer validate.
> all: Use fixed version number for java 6 signature

- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
- interop-testing/src/main/java/io/grpc/testing/integration/Util.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
Conscrypt can thus be an alternative to Jetty ALPN for running these
OkHttp integration tests.
> interop-testing: Support conscrypt at runtime with OkHttp

- buildscripts/make_dependencies.bat
Backport #2141 to fix Kokoro build for v1.0.x branch
The other release branches have this change already and have green builds on Kokoro.
> Backport (v1.0.x): Fix Windows build to specify Studio version

- examples/BUILD.bazel
- protobuf-lite/BUILD.bazel
- protobuf/BUILD.bazel
- repositories.bzl
fix misuse of `@com_google_protobuf` mentioned in a comment of #3175
> fix misuse of bazel repo @com_google_protobuf

- core/src/main/java/io/grpc/ManagedChannelProvider.java
- core/src/main/java/io/grpc/NameResolverProvider.java
- core/src/main/java/io/grpc/ServerProvider.java
currentThread().getContextClassLoader() was originally used to match
ServiceLoader's default. ServiceLoader is mostly used with SPIs that
exist in the bootclasspath and so the class's ClassLoader would not
work. But in gRPC we have a library in the application's ClassLoader.
Context ClassLoader has been causing problems in any case more than one
application ClassLoader exists, like in Servlet containers, Android, and
plugins. To my knowledge, in every case the context class loader is
different from the provider's class loader, the context class loader has
caused breakage, not success. In addition, since we use static fields
for storing the provider results, using anything but the provider's
class loader is asking to have results that vary simply depending on
which thread called gRPC …
> core: Stop using context ClassLoader in Providers

- build.gradle
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
This avoids a guava dependency conflict that caused the interop test server to fail with the message:
> Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.platformThreadFactory()Ljava/util/concurrent/ThreadFactory;
at io.grpc.internal.GrpcUtil.getThreadFactory(GrpcUtil.java:482)
at io.grpc.internal.GrpcUtil$2.create(GrpcUtil.java:446)
at io.grpc.internal.GrpcUtil$2.create(GrpcUtil.java:439)
at io.grpc.internal.SharedResourceHolder.getInternal(SharedResourceHolder.java:104)
at io.grpc.internal.SharedResourceHolder.get(SharedResourceHolder.java:74)
at io.grpc.internal.SharedResourcePool.getObject(SharedResourcePool.java:35)
at io.grpc.internal.ServerImpl.start(ServerImpl.java:149)
at io.grpc.internal.ServerImpl.start(ServerImpl.java:70) …
> all,interop-testing: update google-auth-library-oauth2-http

- core/src/main/java/io/grpc/ManagedChannelBuilder.java
- core/src/main/java/io/grpc/ServerBuilder.java
This change is here to allow custom server / channel implementations to throw if TLS or plaintext is not supported.  This is the case when using custom, security specific builders.
As a side effect InProcessServerBuilder throwing UOE is now allowed from the javadoc.
> core: clarify security methods on channel and server

- RELEASING.md
We need to know of external breakages that would prevent testing release branches.
I moved the CI configuration for a new release branch to immediately after the branch is created, as seems appropriate. I also hope it will make it less likely to be forgotten. There's also unrelated link fixes.
I'll submit the changes as individual commits. Reviewing the commits individually is probably easiest due to the move.
> Use periodic builds for release branches

- README.md
- RELEASING.md
- build.gradle
- examples/README.md
- examples/android/README.md
- stub/src/main/java/io/grpc/stub/package-info.java
Use https://grpc.io as the canonical URL prefix in various places: https://github.com/grpc/grpc/pull/11738 for Java repo
> Canonicalize URL prefixes to https://grpc.io

- buildscripts/kokoro/windows.bat
There were a couple of issues:
- `windows.bat` wasn't returning the Gradle exit code; it was returning an exit code related to the commands renaming the `*.xml` files
- `%%ERRORLEVEL%%` changed to `%ERRORLEVEL%`
After PR review, I'll remove the commit causing test failures, squash commits, and make sure the Kokoro build is green with these changes.
> Make Kokoro show actual Gradle results

- README.md
- RELEASING.md
- build.gradle
- examples/README.md
- examples/android/README.md
- stub/src/main/java/io/grpc/stub/package-info.java
> Canonicalize URL prefixes to https://grpc.io (backport to 1.5.x)

- README.md
- RELEASING.md
- build.gradle
- examples/README.md
- examples/android/README.md
- stub/src/main/java/io/grpc/stub/package-info.java
> Canonicalize URL prefixes to https://grpc.io (backport to 1.4.x)

- core/src/main/java/io/grpc/ClientCall.java
- core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
- core/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java
Change the `@DoNotMock` message to refer to `InProcessServerBuilder`, and include some usage examples that users may find useful.
fixes #3124
> core: update javadocs regarding ClientCall mocks

- core/src/main/java/io/grpc/internal/AbstractSubchannel.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/OobChannel.java
- core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java
The old `SubchannelImpl` is actually not implementing anything, and the old `SubchannelImplImpl` has a weird name.
> core: refactor SubchannelImpl

- netty/src/main/java/io/grpc/netty/NettyServerTransport.java
- netty/src/test/java/io/grpc/netty/NettyServerTransportTest.java
Log all exceptions at INFO rather than SEVERE.
Known uninteresting exceptions should be FINE.
fixes #1768
> netty: quieter errors in NettyServerTransport

- interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpTlsUpgrader.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
We use custom x509 extensions to encode multiple dimensions of server identity, and clients verify different dimensions based on individual client requirements. This is all coded up into HostnameVerifier implementations, but we need to ability to pass this to the the OkHttpChannelBuilder. I've implemented the ability to pass this through, defaulting to the existing OkHostnameVerifier implementation when unspecified.
> Add support for specifying a custom hostname verifier when using on OkHttpChannelBuilder

- testing-proto/src/generated/main/java/io/grpc/testing/protobuf/SimpleRequest.java
- testing-proto/src/generated/main/java/io/grpc/testing/protobuf/SimpleRequestOrBuilder.java
- testing-proto/src/generated/main/java/io/grpc/testing/protobuf/SimpleResponse.java
- testing-proto/src/generated/main/java/io/grpc/testing/protobuf/SimpleResponseOrBuilder.java
- testing-proto/src/generated/main/java/io/grpc/testing/protobuf/SimpleServiceProto.java
- testing-proto/src/main/proto/io/grpc/testing/protobuf/simpleservice.proto
In migrating internal tests to use testing protos, I found it was not convenient to test in some scenarios without having a field in the message. All `SimpleResponse` messages are `equals` to each other. Users might not want to assume reference identity/inequality between server and client for equal/unequal messages even for InProcess. Even with reference identity, it would still be inconvenient if their were hundreds of messages.
To have a  non-proto based String to String service instead is another solution, but the usefulness of this proto based service would still be too limited.
> testing-proto: add string message to testing proto

- build.gradle
Without this config change, unit tests will not be runnable in
intellij using gradle 4.0
https://github.com/gradle/gradle/issues/2315
> build.gradle: intellij fix for gradle 4.0

- core/src/main/java/io/grpc/InternalMetadata.java
- core/src/main/java/io/grpc/Metadata.java
- core/src/main/java/io/grpc/Status.java
- core/src/test/java/io/grpc/MetadataTest.java
- core/src/test/java/io/grpc/internal/Http2ClientStreamTransportStateTest.java
Previously anyone could create metadata keys with a leading ":", due to not having a way to prevent it.  This change effectively only allows internal code to make use of this.
> core: hide access to pseudo headers

- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
For `basicStream`, we can not use a timeout with the `inOrder` mock. The test looks like it's only testing for one interaction in that part of the test, rather than multiple interactions in a specific order. This looks fine to me. Please let me know what you think.
`clientCancelFromWithinMessageRead` is another test that needs a timeout argument.
> netty: add timeouts to address test flakiness

- android-interop-testing/app/proguard-rules.pro
- core/src/main/java/io/grpc/ManagedChannelProvider.java
- core/src/main/java/io/grpc/NameResolverProvider.java
- core/src/test/java/io/grpc/ManagedChannelProviderTest.java
- core/src/test/java/io/grpc/NameResolverProviderTest.java
- core/src/test/java/io/grpc/StaticTestingClassLoader.java
- core/src/test/java/io/grpc/internal/DnsNameResolverProviderTest.java
- examples/android/helloworld/app/proguard-rules.pro
- examples/android/routeguide/app/proguard-rules.pro
- netty/src/test/java/io/grpc/netty/NettyChannelProviderTest.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpChannelProviderTest.java
Class.forName(String) is understood by ProGuard, removing the need for
manual ProGuard configuration and allows ProGuard to rename the provider
classes. Previously the provider classes could not be renamed.
Fixes #2633
> core: Use Class.forName(String) in provider for Android

- core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
- core/src/main/java/io/grpc/inprocess/InProcessServer.java
- core/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java
- core/src/main/java/io/grpc/inprocess/InProcessTransport.java
- core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
- core/src/main/java/io/grpc/internal/ServerTransport.java
- core/src/test/java/io/grpc/inprocess/InProcessServerTest.java
- core/src/test/java/io/grpc/inprocess/InProcessTransportTest.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
- netty/src/main/java/io/grpc/netty/NettyServerTransport.java
For Netty, this reduces the number of threads necessary for servers (although
until channel is converted, actual number of threads isn't impacted) and
naturally reduces contention and timeout latency.
For InProcess, this gets us closer to allowing applications to provide all
executors, which is especially useful during tests.
CC @zhangkun83
> core: Server uses transport's ScheduledExecutorService

- core/src/main/java/io/grpc/LoadBalancer.java
- core/src/main/java/io/grpc/ManagedChannel.java
- core/src/main/java/io/grpc/internal/ConnectivityStateManager.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/ConnectivityStateManagerTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
This is only implementing how subchannel state changes are hooked up to channel state APIs. Debates in state semantics and transition rules for loadbalanced channel such as #2873 are not addressed. Any changes in state semantics and transition rules in the future can be easily adapted.
> POC: channel state API plumbing

- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
This reverts commit 57b9105c7f14b52a3ed132302af1af59fc869281.
Issue #2682 is fixed, so we can revert the commit as planned. This
re-applies a previously-reverted modernization.
> Revert interop-testing: overrideAuthority breaks JWT

- build.gradle
Jetty ALPN was broken with jdk1.8.0_121
This is a backport of #2816 to fix the Kokoro build.
> all: Bump Jetty ALPN agent version, for new JREs (1.0 backport)

- build.gradle
Jetty ALPN was broken with jdk1.8.0_121
This is a backport of #2816 to fix the Kokoro build.
> all: Bump Jetty ALPN agent version, for new JREs (1.1 backport)

- build.gradle
Jetty ALPN was broken with jdk1.8.0_121
This is a backport of #2816 to fix the Kokoro build.
> all: Bump Jetty ALPN agent version, for new JREs (1.2 backport)

- context/src/main/java/io/grpc/Context.java
Using static initialization is possible, but quite complex to handle
logging and circular loading. Lazy loading prevents an entire class of
circular dependencies.
Given the various iterations involved here, it'd be good if all the
reviewers reviewed this change.
> context: Lazy load storage

- context/build.gradle
- context/src/test/java/io/grpc/ContextTest.java
This will break if 2f6e2c87ab1aeda591fcb7764a8ad6bb20855a2a & a3a5420922ecf1ddc2c4ab77c273be3df47b74f5 are reverted:
```
io.grpc.ContextTest > initContextWithCustomClassLoaderWithCustomLogger FAILED
java.lang.ExceptionInInitializerError
at io.grpc.ContextTest$LoadMeWithStaticTestingClassLoader.run(ContextTest.java:789)
at io.grpc.ContextTest.initContextWithCustomClassLoaderWithCustomLogger(ContextTest.java:760)
Caused by:
java.lang.RuntimeException: Storage override had failed to initialize
at io.grpc.Context.storage(Context.java:134)
at io.grpc.Context.current(Context.java:163)
at io.grpc.ContextTest$LoadMeWithStaticTestingClassLoader$1.publish(ContextTest.java:773)
at java.util.logging.Logger.log(Logger.java:738)
at java.util.logging.Logger.doLog(Logger.java:765)
at …
```
> Context: add test for the scenario that Context's logger itself is using Context

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
LoadBalancer may log subchannels. This makes the logs more informative.
> core: Override SubchannelImpl.toString()

- SECURITY.md
- build.gradle
This cherry-picks #3087 to the v1.4.x branch, since updating SECURITY.md was missed before the release.
If we were strict about the versions, we would recommend 2.0.1, since that's what we were using at the time of the release, but it doesn't seem to matter much in this case and 2.0.3 is expected to be a faster and support shading.
> v1.4.x: update netty-tcnative version in SECURITY.md; and bump to 4.0.3

- core/src/main/java/io/grpc/inprocess/InProcessTransport.java
- core/src/main/java/io/grpc/internal/ClientTransport.java
- core/src/main/java/io/grpc/internal/DelayedClientTransport.java
- core/src/main/java/io/grpc/internal/FailingClientTransport.java
- core/src/main/java/io/grpc/internal/ForwardingConnectionClientTransport.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
- core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
to keep only one newStream() method in the `ClientTransport` interface
> core,netty,okhttp: remove 2-arg ClientTransport.newStream()

- core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/CallCredentialsApplyingTransportFactory.java
- core/src/main/java/io/grpc/internal/ClientTransportFactory.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
Coupled with the similar change on server-side, this removes the need for a
thread when using Netty. For InProcess and OkHttp, it would allow us to let the
user to provide the scheduler for tests or application-wide thread sharing.
The first commit is from #3184, and need not be reviewed here. This change
depends on it, but not too heavily; the dependency could be removed without
much trouble (although then at the price of merge conflicts and needing to
re-apply review fixes).
> core: Channel uses transport's ScheduledExecutorService

- stub/src/main/java/io/grpc/stub/ClientCallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ClientCalls.java
Allow a client to gracefully cancel a one-to-many streaming service by signaling the server to stop sending messages.
Addresses #3095
> Implemented ClientCallStreamObserver.cancel()

- context/src/main/java/io/grpc/Context.java
Use deadline on client calls lead to create TimeoutException even
if deadline not occurs yet. `fillStacktrack` very expensive operation
that allocate many unnecessary objects in heap. Now exception
creates only when deadline occurs.
Close #3272
> context: Create TimeoutException only when deadline occurs

- benchmarks/src/main/java/io/grpc/benchmarks/qps/AbstractConfigurationBuilder.java
```
:grpc-benchmarks:compileJavaC:\jenkins\workspace\gRPC-Java-PR-Windows\benchmarks\src\main\java\io\grpc\benchmarks\qps\AbstractConfigurationBuilder.java:58: warning:
[MissingOverride] getDefaultValue implements method in Param; expected @Override
public String getDefaultValue() {
^
(see http://errorprone.info/bugpattern/MissingOverride)
Did you mean '@Override public String getDefaultValue() {'?
error: warnings found and -Werror specified
1 error
1 warning
FAILED
FAILURE: Build failed with an exception.
```
> benchmarks: fix [MissingOverride]

- netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java
- netty/src/main/java/io/grpc/netty/GrpcHttp2OutboundHeaders.java
Recent Netty change https://github.com/netty/netty/commit/a91df58ca17d5b30c57c46dde5b1d60bb659b029
caused the `status()` method to be invoked, which AbstractHttp2Headers does not implement.
This change is necesary to upgrade to Netty 4.1.14
> netty: support `status()` on Headers

- auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
- auth/src/main/java/io/grpc/auth/MoreCallCredentials.java
- core/src/main/java/io/grpc/CallCredentials.java
- core/src/main/java/io/grpc/CallOptions.java
- stub/src/main/java/io/grpc/stub/AbstractStub.java
As discussed in #1914, we need CallCredentials and MoreCallCredentials
to be stable, but there's less of a strong need for the contents of
CallCredentials to be stable. We're willing to commit to the name,
without needing to commit to the plumbing.
CC @garrettjonesgoogle
> Stabilize auth flow using CallCredentials

- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
Previously only when all addresses returned by NameResolver are
balancers would GRPCLB be forced.  This change is a follow-up of
https://github.com/grpc/grpc/pull/10258
> grpclb: force GRPCLB policy when NameResolver returns at least one balancer

- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
According to Census team, the tag wire format is now stable.
/cc @dinooliva @songy23
> core: enable Census tags propagation by default.

- core/src/main/java/io/grpc/internal/ConnectivityStateManager.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/ConnectivityStateManagerTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
Fix bug found by internal user
```
W/ChannelExecutor: Runnable threw exception in ChannelExecutor
java.lang.IllegalStateException: ConnectivityStateManager is already disabled
at com.google.common.base.Preconditions.checkState(Preconditions.java:459)
at io.grpc.internal.ConnectivityStateManager.gotoState(ConnectivityStateManager.java:66)
at io.grpc.internal.ManagedChannelImpl$5.run(ManagedChannelImpl.java:476)
at io.grpc.internal.ChannelExecutor.drain(ChannelExecutor.java:72)
at io.grpc.internal.DelayedClientTransport.shutdown(DelayedClientTransport.java:216)
at io.grpc.internal.ManagedChannelImpl.shutdown(ManagedChannelImpl.java:480)
at io.grpc.internal.ManagedChannelImpl.shutdown(ManagedChannelImpl.java:69)
```
> core: fix ConnectivityStateManager is already disabled bug

- core/src/main/java/io/grpc/internal/KeepAliveManager.java
- core/src/test/java/io/grpc/internal/KeepAliveManagerTest.java
If onTransportActive ran while SendPing was already scheduled, we would
schedule another SendPing, which seems fine, but the server might observe
us sending pings too quickly, and make us GOAWAY.
Fixes #3274.
> Don't schedule multiple pings.

- compiler/src/java_plugin/cpp/java_generator.cpp
- compiler/src/java_plugin/cpp/java_generator.h
- compiler/src/java_plugin/cpp/java_plugin.cpp
This fixes sign-compare and maybe-unintialized. An unused-value warning
remains.
I changed LogHelper to always call abort so the compiler would know the
method does not return, which fixed the maxbe-uninitialized warning.
> compiler: Fix some warnings when building with Bazel

- core/src/main/java/io/grpc/StreamTracer.java
- core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
- core/src/test/java/io/grpc/internal/MessageDeframerTest.java
- core/src/test/java/io/grpc/internal/MessageFramerTest.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
- testing/src/main/java/io/grpc/internal/testing/TestClientStreamTracer.java
- testing/src/main/java/io/grpc/internal/testing/TestServerStreamTracer.java
- testing/src/main/java/io/grpc/internal/testing/TestStreamTracer.java
This is a big, but mostly mechanical change.  The newly added Test*StreamTracer classes are designed to be extended which is why they are non final and have protected fields.  There are a few notable things in this:
1.  verifyNoMoreInteractions is gone.   The API for StreamTracers doesn't make this guarantee.  I have recovered this behavior by failing duplicate calls.  This has resulted in a few bugs in the test code being fixed.
2.  StreamTracers cannot be mocked anymore.  Tracers need to be thread safe, which mocks simply are not.  This leads to a HUGE number of reports when trying to find real races in gRPC.
3.  If these classes are useful, we can promote them out of internal.  I just put them here out of convenience.
> testing,core: don't use mocks for stream tracers

- benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadServer.java
- benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncServer.java
Add missing workloads for missing streaming workloads. Client workloads coming on another PR.
Also, refactor away some redundant code.
> benchmark: add missing server side workloads

- build.gradle
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
- netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
- repositories.bzl
EmbeddedChannel now runs all pending tasks when the Channel is closed.
This caused the Http2ConnectionHandler to clear deframer references (on
channelInactive) on errors when it previously didn't. Now that the
errors were handled more fully, it exposed bugs in tests.
FYI @normanmaurer, @Scottmitch
> netty: Update netty to 4.1.14

- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
- interop-testing/src/test/java/io/grpc/testing/integration/TestServiceClientTest.java
Reintroduced in 924b0b2, the test service client will throw an NPE unless `--server_host_override` is explicitly set on the command line. This checks if `serverHostOverride` is set before passing it to the `NettyChannelBuilder`, and adds a (useful?) mini-test to assure that the client doesn't throw an exception on an empty argument list.
> interop-testing: fix NPE on empty args to test service client

- core/src/main/java/io/grpc/ManagedChannelProvider.java
- core/src/main/java/io/grpc/NameResolverProvider.java
null class loader means to use the bootstrap class loader, which would
normally make sense. However, Robolectric tests run on OpenJDK and
provide the Android environment as part of the application, so "Android"
won't be present in the bootstrap class loader.
> core: Providers should consider Robolectric as Android

- interop-testing/src/main/java/io/grpc/testing/integration/Http2Client.java
The Java HTTP/2 test client has been flaky (https://github.com/grpc/grpc/issues/10390, plus assorted others), and the failing tests (`MAX_STREAMS`, `RST_AFTER_DATA`, `RST_DURING_DATA`) all set what now looks like a rather spare deadline of five seconds in the Java client. Looking at the successful runs for these tests in the other languages, the tests can occasionally take a very long time, up to two minutes. See for example [go's MAX_STREAMS test case clocking in at 1:53](https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/15990/testReport/(root)/tests/cloud_to_cloud_go_http2_server_max_streams/). None of the other tests in the Java client set a deadline at all, and they are all reliably passing.
This PR increases the timeout value to 180 seconds.
It also removes the …
> interop-testing: larger timeout for HTTP/2 client

- okhttp/src/main/java/io/grpc/okhttp/Headers.java
There was no way to use it without touching internal APIs, and it should
never have been public to begin with as it serves no purpose to a user.
> okhttp: Make Headers package-private

- netty/src/main/java/io/grpc/netty/NettyClientStream.java
Intended to address https://github.com/grpc/grpc-java/issues/3007.
> netty: check for stream before freeing flow control bytes on client

- context/src/main/java/io/grpc/Context.java
- context/src/main/java/io/grpc/ThreadLocalContextStorage.java
- context/src/test/java/io/grpc/ContextTest.java
This API change allows storage implementations to put some state information into the return value, giving it the ability to act as a cookie. In environments where contexts can be replaced, the current `original context` can be stashed there and be restored when `detach` is called.
> context: change storage API to return a restoreable context

- auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- netty/src/main/java/io/grpc/netty/NettyClientStream.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- testing/src/main/java/io/grpc/internal/NoopClientCall.java
- testing/src/main/java/io/grpc/internal/NoopServerCall.java
- testing/src/main/java/io/grpc/testing/NoopClientCall.java
- testing/src/main/java/io/grpc/testing/NoopServerCall.java
> all: fix typo of overridden

- android-interop-testing/README.md
- android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/InteropTester.java
- android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/TesterInstrumentation.java
Previously `TesterInstrumentation` returned a status of 0 on success. This is the same code returned when the instrumentation tests fail with an exception. This switches to returning `Activity.RESULT_OK` (-1) on success and `Activity.RESULT_CANCELED` (0) on failure, making it possible to distinguish between runtime failures and a passing test case.
Note: these are different than the JUnit instrumentation tests currently running for our Firebase open-source Android integration tests (https://github.com/grpc/grpc-java/pull/3079). This change only impacts command-line runs of the older Instrumentation interop tests, which we do not currently run in open-source.
> interop-testing: use Activity.RESULT_OK instead of 0

- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
As noted after `@Ignore`
> Re-enable once https://github.com/grpc/grpc-java/issues/1175 is fixed
#1175 has been closed for a long time, should re-enable the tests.
> netty: not to ignore tests for window overriding

- android-interop-testing/app/src/main/AndroidManifest.xml
The `com.google.android.gms.version` is no longer required, and some build tools rely on the minimum SDK being present in `AndroidManifest.xml` rather than solely in `build.gradle`.
> android-interop-testing: remove gms version metadata, add minimum sdk

- core/src/main/java/io/grpc/inprocess/InProcessTransport.java
- core/src/main/java/io/grpc/internal/DelayedClientTransport.java
- core/src/main/java/io/grpc/internal/ForwardingConnectionClientTransport.java
- core/src/main/java/io/grpc/internal/InternalSubchannel.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/ManagedClientTransport.java
- core/src/main/java/io/grpc/internal/OobChannel.java
- core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java
- core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
This aligns with shutdownNow(), which is already accepting a status.
The status will be propagated to application when RPCs failed because
of transport shutdown, which will become useful information for debug.
> core: pass status to ManagedClientTransport.shutdown()

- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
Previously, the round-robin list that the client uses (effective
round-robin list, ERRL) was the received round-robin list (RRRL, from
remote balancer) excluding non-READY backends.  Drop and backend
entries are in the same list.
The problem with it is that when not all backends are READY, drop
entries take a larger proportion in ERRL than they do in the RRRL,
resulting a larger drop ratio than intended.
To fix this, we employ a two-list scheme:
- A _drop list_ (DL) that is out of the RRRL, with the same size and
the same number of drop entries as the RRRL.
- A _backend list_ (BL) that contains only the backend entries from
the RRRL, excluding non-READY ones.
For every pick, the client would round-robin on the DL to determine
whether the pick should be dropped.  Only when it's not …
> grpclb: use two-level drop behavior

- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/main/java/io/grpc/netty/NettyClientStream.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/main/java/io/grpc/netty/SendGrpcFrameCommand.java
- netty/src/main/java/io/grpc/netty/WriteQueue.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
- netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
NettyClientTransport needs to call close() on the Channel directly
instead of sending a message, since the message would typically be
delayed until negotiation completes.
The closeFuture() closes too early to be helpful, which is very
unfortunate. Using it squelches the negotiator's error handling. We now
rely on the handlers to report shutdown without any back-up. The
handlers error handling has matured, so maybe this is okay.
------
This work was initially triggered by useless error messages if using a Proxy failed. I _thought_ I had already submitted this. But then it bit me again when trying to get Conscrypt working, so I finished up the old commit.
> netty: Handle shutdown and failures during negotiator

- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
Tracing wire format is now stable.
Note a Census tracing implementation, which is not included in gRPC,
is still required for tracing to work.
/cc @ejona86
> core: enable Census trace context propagation.

- context/src/main/java/io/grpc/Context.java
- context/src/main/java/io/grpc/PersistentHashArrayMappedTrie.java
- context/src/test/java/io/grpc/ContextTest.java
- context/src/test/java/io/grpc/PersistentHashArrayMappedTrieTest.java
This is the hashtrie data structure authored by @ejona86 
The linked list key value store is known cause problems in pathological cases where users keep updating the same key(s) over and over. This copy on write tree will have reads that cost `O(lgN)` where N is the number of keys in the map, rather than `O(M)` where M is the total number of `put` operations in the case of the linked arrays.
Also:
- added some unit tests
- ran a test putting random keys into the map and comparing the result with a java.util.HashMap to verify sanity. The test passes but I won't check it into the repo because it 
takes a long time to run: https://gist.github.com/zpencer/12cb435235d171c1fe09aef18825fad0
Benchmarks:
linked array: https://gist.github.com/zpencer/7455cb146d39cbf5628e0608a94ad70c
hashtrie: …
> context: hashtrie based keyvalue store

- context/src/main/java/io/grpc/Context.java
These are unused fields that slipped past the previous diff.
> context: remove unused fields

- android-interop-testing/app/build.gradle
- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/ReportQpsScenarioServiceGrpc.java
- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
- build.gradle
- compiler/src/test/golden/TestService.java.txt
- compiler/src/testLite/golden/TestService.java.txt
- compiler/src/testNano/golden/TestService.java.txt
- examples/android/helloworld/app/build.gradle
- examples/android/routeguide/app/build.gradle
- examples/build.gradle
- examples/pom.xml
- examples/thrift/build.gradle
- grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
- services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java
- services/src/generated/main/grpc/io/grpc/instrumentation/v1alpha/MonitoringGrpc.java
- services/src/generated/main/grpc/io/grpc/reflection/v1alpha/ServerReflectionGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/AnotherDynamicServiceGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/DynamicServiceGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/ReflectableServiceGrpc.java
- testing-proto/src/generated/main/grpc/io/grpc/testing/protobuf/SimpleServiceGrpc.java
all: bump to 1.7.0-SNAPSHOT
This bump changelist is applied a bit late with respect to the
1.6.0 branch cut. Look at the 1.6.0 to see the source of truth of
where it was cut. Do not assume it is the commit that preceeds
this one.
> all: bump to 1.7.0-SNAPSHOT

- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
GrpclbLoadBalancer can work in non-GRPCLB (delegate) mode according to
name resolution results.  Previously the policy selection, delegation
and GRPCLB logic are in the same file, which is not very readable.  It
will get worse as we going to implement policy fallback logic soon.
This PR refactors the GRPCLB logic out, and makes GrpclbLoadBalancer
focus on the policy selection and delegation logic.
__Notes for reviewers__: github doesn't recognize the copy of major chunks of code from `GrpclbLoadBalancer.java` to `GrpclbState.java`. You may want to fetch my branch
and view the diff with `-C`, e.g.:
```bash
$ git remote add zhangkun83 git@github.com:zhangkun83/grpc-java.git
$ git fetch zhangkun83 grpclb_fallback
$ git difftool --tool=meld -C 8634632019ee7ea35e44c6c8749343ec99ecc858 …
```
> grpclb: refactor main GRPCLB logic out of GrpclbLoadBalancer.

- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/ReportQpsScenarioServiceGrpc.java
- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
- build.gradle
- compiler/src/java_plugin/cpp/java_generator.cpp
- compiler/src/java_plugin/cpp/java_generator.h
- compiler/src/java_plugin/cpp/java_plugin.cpp
- grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
- services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java
- services/src/generated/main/grpc/io/grpc/instrumentation/v1alpha/MonitoringGrpc.java
- services/src/generated/main/grpc/io/grpc/reflection/v1alpha/ServerReflectionGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/AnotherDynamicServiceGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/DynamicServiceGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/ReflectableServiceGrpc.java
- testing-proto/src/generated/main/grpc/io/grpc/testing/protobuf/SimpleServiceGrpc.java
If the option becomes popular, we can just remove the version.
I didn't update the golden files in compiler/. They would be convenient to exclude the version,
but it may be better to include the version in them. Opinions welcome.
CC @zhangkun83
> compiler: Add option to disable version output

- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
Previously, if two streams are added (but not active yet), then the transport is changed into inUse; after that, if one of them gets active and then closed and removed, then the transport will be changed into and staying at notInUse, although the other stream could later be active.
> netty: fix transport spuriously in notInUse state

- core/BUILD.bazel
- netty/BUILD.bazel
- repositories.bzl
In 72b9ee2 (see also #3328, #3338), gson kept its old name while opencensus got what should have
become gson's new name instead of a fixed opencensus name.
I think this resolves that.
> Fix gson / opencensus bazel naming mixup

- netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java
The version of netty we are using supports this option now:
https://github.com/netty/netty/pull/6954
Fixes #2907
> netty: graceful shutdowns should for streams to close

- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
Increased interval from 20,000 micros (i.e. 20 millis) to 20 seconds.
> interop-testing: fix dealineExceeded test by increasing time interval

- core/src/main/java/io/grpc/internal/GrpcUtil.java
While the code had correctly determined full threads were available, the
call to MoreExecutors returned a request thread factory, which has
limitations.
Note that Async stub users may not be able to call GAE APIs in
callbacks. This is because the threads aren't request threads. They can
override the individual call's executor with
com.google.appengine.api.ThreadManager.currentRequestThreadFactory() in
an interceptor via callOptions.withExecutor().
Fixes #3296
-----
@neozwu, can you test this?
As a user, I think I'd expect the Async API callbacks to be done or request threads. But this isn't very feasible to configure automatically because the executor would need to "save" the environment when a new call is created and re-associate callbacks with it. It'd be easy to override blindly, but …
> Avoid request threads on AppEngine Java 8

- core/src/main/java/io/grpc/internal/CompositeReadableBuffer.java
- core/src/test/java/io/grpc/internal/CompositeReadableBufferTest.java
If the initial buffer in a CompositeReadableBuffer has 0 readable bytes, invoking readUnsignedByte() on the composite triggers the following exception:
```
java.lang.IndexOutOfBoundsException
at io.grpc.internal.AbstractReadableBuffer.checkReadable(AbstractReadableBuffer.java:72)
at io.grpc.internal.ReadableBuffers$ByteArrayWrapper.readUnsignedByte(ReadableBuffers.java:158)
at io.grpc.internal.CompositeReadableBuffer$1.readInternal(CompositeReadableBuffer.java:71)
at io.grpc.internal.CompositeReadableBuffer$ReadOperation.read(CompositeReadableBuffer.java:220)
at io.grpc.internal.CompositeReadableBuffer.execute(CompositeReadableBuffer.java:178)
at io.grpc.internal.CompositeReadableBuffer.readUnsignedByte(CompositeReadableBuffer.java:74)
at …
```
> core: advance past empty buffer in CompositeReadableBuffer

- compiler/build.gradle
This includes the file names and context, which is soo much nicer.
> compiler: Produce unified output on diff failure

- context/src/main/java/io/grpc/Context.java
The main goal here is simplification. You can review the two commits separately. They will be merged as separate commits.
> Remove two unnecessary fields from Context

- build.gradle
- netty/src/main/java/io/grpc/netty/GrpcSslContexts.java
We'll need to figure out what we want to do about the deprecated API.
We'll probably just drop the verification check, but need to look into
it a bit.
----
I'll wait for the release announcement before actually merging.
> netty: Update to Netty 4.1.15

- core/src/main/java/io/grpc/internal/AbstractReadableBuffer.java
- core/src/main/java/io/grpc/internal/ForwardingReadableBuffer.java
- core/src/main/java/io/grpc/internal/ReadableBuffer.java
- core/src/test/java/io/grpc/internal/AbstractReadableBufferTest.java
- core/src/test/java/io/grpc/internal/ForwardingReadableBufferTest.java
These were likely added to match the ByteBuf api, but we never use them.
> core: remove unused buffer methods

- build.gradle
- protobuf-nano/src/main/java/io/grpc/protobuf/nano/NanoUtils.java
This reverts commit 671783f912539b41450117a6c81e1009fde5471d
The dependency on `core` caused some problems with
Proguard. There are android builds that should include
`protobuf-*` but expect the rest of gRPC to be bundled with the
runtime environment. In that case, when Proguard inspects the
output, it will find a reference to IoUtil but fail to find the
class itself. It makes the builds easier to just avoid this
dependency.
> protobuf-nano: do not use preexisting IoUtils internal class

- netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
- okhttp/src/main/java/io/grpc/okhttp/Headers.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientStreamTest.java
It turns out that https://github.com/grpc/grpc-java/pull/2945 did not fully implement GET support for the OkHttp transport. This PR modifies the outgoing headers for a GET request to specify `method: GET` and sets `endStream=true`, and also tells the frame writer to immediately flush the headers instead of waiting for additional data on the stream (which will never come).
Edit: This also adds a test for `method: GET` to the corresponding Netty test case. Netty was already doing things correctly, but did not have test coverage for this.
> Finish support for GET methods in OkHttp transport

- netty/src/main/java/io/grpc/netty/InternalNettyServerBuilder.java
- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/main/java/io/grpc/netty/NettyServer.java
- netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
- netty/src/test/java/io/grpc/netty/NettyServerTest.java
This change does two things: it hides the ProtocolNegotiator from
NSB, and exposes an internal init channel on NSB and NCB.  The
reason for the change is that PN is not a powerful enough
abstraction for internal Google use (and for some other outside
users with highly specific uses).
The new API exposes adding a ChannelHandler to the pipeline upon
registration of the channel.
To accomplish this, NettyClientTransport is modified to use
ChannelInitializer.  There is a comment explaining why it cannot
be used, but after looking at the the original discussion, I
believe the reasons for doing so are no longer applicable.
Specifically, at the time that CI was removed, there was no
WriteQueue class.  The WQ class buffers all writes and executes
them on the EventLoop.  Prior to WQ it was not the …
> netty: hide ProtocolNegotiator, and expose initial ChannelHandler

- context/src/main/java/io/grpc/Context.java
- context/src/test/java/io/grpc/ContextTest.java
If a context has an unreasonable number of ancestors, then
chances are this is an application error. Log the stack trace to
notify the user and aid in debugging.
> context: log severe warning if ancestry chain > 1000

- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/main/java/io/grpc/internal/IoUtils.java
- core/src/main/java/io/grpc/internal/MessageFramer.java
- core/src/main/java/io/grpc/internal/ServerCallImpl.java
- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
- protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoInputStream.java
- protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java
Fix more of these usages so we can enable `@Beta` checks
For `Ticker`: replace with a factory for StopWatch. We can make
fake stop watches from unit tests, where `@Beta` doesn't matter.
> core,netty,okhttp,protobuf-lite: avoid @Beta guava classes

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- netty/src/test/java/io/grpc/netty/NettyChannelBuilderTest.java
Cleaning up channels is something users should do.  To promote this
behavior, add a log message to indicate that the channel has not
been properly cleaned.
This change users PhantomReferences to avoid keeping the channel
alive and retaining too much memory.  Only the id and the target
are kept.  Additionally, the lost references are only checked at
JVM shutdown and on new channel creation.  This is done to avoid
Object finalizers.
The test added checks to see that the message is logged.  Since
java does not allow forcing of a GC cycle, this code is best
effort, giving up after about a second.  A custom log filter is
added to hook the log messages and check to see if the correct
one is present.  Handlers are not used because they are
hierarchical, and would be annoying to restore their …
> core: add finalizer checks for ManagedChannels

- android-interop-testing/app/build.gradle
- android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/InteropTester.java
This makes it easier to convert over to Proto lite, which will be
replacing nano in the near future.
The enum style will be going away too after the migration.
> android-interop-testing: use Java Style enums

- build.gradle
- core/build.gradle
- interop-testing/build.gradle
- protobuf/build.gradle
- testing/build.gradle
Maven Enforcer's dependencyConvergence is commonly used in Spring
projects, as it is inherited by all starter projects[1]. While I find
that option to be crazy and harmful (and would instead support
requireUpperBoundDeps), it does bother people.
1. https://github.com/spring-projects/spring-boot/blob/v1.5.6.RELEASE/spring-boot-starters/pom.xml#L94
> all: Keep artifacts dependencyConvergence-clean

- build.gradle
- core/build.gradle
- core/src/main/java/io/grpc/StreamTracer.java
- core/src/main/java/io/grpc/internal/AbstractClientStream.java
- core/src/main/java/io/grpc/internal/CensusStatsModule.java
- core/src/main/java/io/grpc/internal/CensusTracingModule.java
- core/src/main/java/io/grpc/internal/MessageDeframer.java
- core/src/main/java/io/grpc/internal/MessageFramer.java
- core/src/main/java/io/grpc/internal/StatsTraceContext.java
- core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
- core/src/test/java/io/grpc/internal/CensusModulesTest.java
- core/src/test/java/io/grpc/internal/MessageDeframerTest.java
- core/src/test/java/io/grpc/internal/MessageFramerTest.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbClientLoadRecorder.java
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
- testing/src/main/java/io/grpc/internal/testing/TestClientStreamTracer.java
- testing/src/main/java/io/grpc/internal/testing/TestServerStreamTracer.java
- testing/src/main/java/io/grpc/internal/testing/TestStreamTracer.java
Two methods, `outboundMessageSent()` and `inboundMessageRead()` are added to StreamTracer in order to associate individual messages with sizes. Both types of sizes are optional, as allowed by Census tracing.
Both methods accept a sequence number as the type ID as required by Census. The original `outboundMesage()` and `inboundMessage()` are also replaced by overrides that take the sequence number, to better match the new methods. The deprecation of the old overrides are tracked by #3460
> core: record individual messages with sizes to Census/tracing

- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/main/java/io/grpc/internal/ServerCallImpl.java
It was added by mistake in commit 2b1363d58600ac49b73116e00d17302063ef532a
@zpencer, core should not depend on Guava collect because it's not Android-friendly.
> core: remove reference to Guava collect.

- core/src/main/java/io/grpc/ManagedChannelProvider.java
- core/src/main/java/io/grpc/NameResolverProvider.java
- core/src/main/java/io/grpc/ServerProvider.java
- core/src/test/java/io/grpc/NameResolverProviderTest.java
- core/src/test/java/io/grpc/ServerProviderTest.java
Rebased code of https://github.com/grpc/grpc-java/pull/3453 on master.
@ejona86 / @carl-mastrangelo
> core: allow to fallback to ServiceLoader.load withouth classloader to make GRCP more OSGi friendly.

- context/src/test/java/io/grpc/ContextTest.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
You can review the two commits individually.
> Errorprone fixes: Avoid catching AssertionError in tests, use .class literal when able

- java_grpc_library.bzl
_path_ignoring_repository munges bazel filesystem paths into proto import paths, in order to pass to protoc -I. Currently, the function assumes that the include's path begins with the bazel workspace root, which can therefore be sheared off the front of the path.
This assumption is incorrect. For an include living in an external repository (say, `@com_google_protobuf//:timestamp_proto`), the filesystem path is something like
`bazel-out/darwin_x86_64/fastbuild/genfiles/external/com_google_protobuf/google/protobuf/timestamp.proto`. (See also: http://docs.bazel.build/versions/master/skylark/lib/Label.html#workspace_root.)
This commit changes _path_ignoring_repository to handle this case correctly.
> java_grpc_library.bzl: fix path-manipulation bug.

- core/src/main/java/io/grpc/internal/DelayedClientTransport.java
Make `pendingStreams` in `DelayedClientTransport` non-null.  These two versions are equivalent, but I might be going to introduce `Collection<PendingStream2> pendingStreams2` for a short period of time for implementing retry, and I will have to check a lot of complicated conditions like 
```java
if ((pendingStreams == null || pendingStreams.isEmpty()) && (pendingStreams2 == null || pendingStreams2.isEmpty()) ) {
return;
}
if (pendingStream != null) {
toProcess = new ArrayList<PendingStream>(pendingStreams);
}
if (pendingStream2 != null) {
toProcess2 = new ArrayList<PendingStream2>(pendingStreams2);
}
```
```java
```
Making `pendingStreams` non-null will make the above situation a lot easier.
> core: nonnull pendingStreams in DelayedClientTransport

- core/src/main/java/io/grpc/ForwardingChannelBuilder.java
- core/src/main/java/io/grpc/ManagedChannelBuilder.java
- core/src/main/java/io/grpc/inprocess/InProcessTransport.java
- core/src/main/java/io/grpc/internal/AbstractClientStream.java
- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/AbstractStream.java
- core/src/main/java/io/grpc/internal/ApplicationThreadDeframer.java
- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/ClientStream.java
- core/src/main/java/io/grpc/internal/Deframer.java
- core/src/main/java/io/grpc/internal/DelayedStream.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/MessageDeframer.java
- core/src/main/java/io/grpc/internal/NoopClientStream.java
- core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
- core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
- core/src/test/java/io/grpc/internal/ApplicationThreadDeframerTest.java
- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
- core/src/test/java/io/grpc/internal/MessageDeframerTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
This builds on https://github.com/grpc/grpc-java/pull/3395 and adds client-side support for full-stream decompression.
This is successfully interoperating with the C++ server sending gzipped streams. The next step on the Java side is to improve the test coverage for full-stream compression by adding (or mocking) a server that sends gzipped streams. This will enable adding something along the lines of `FullStreamCompressionTest extends AbstractInteropTest`, similar to our existing `TransportCompressionTest`, `AutoWindowSizingOnTest`, etc. I already have such a server working and these tests passing locally with the client-side code included here.
@ejona86 This PR doesn't include a hard-coded 'don't do full-stream compression' flag yet. It's easier to test this and future work with …
> Part 2 - Client-side full-stream decompression

- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
- testing/src/main/java/io/grpc/internal/testing/TestClientStreamTracer.java
The additional mocks that I added in https://github.com/grpc/grpc-java/pull/3145 made at least the `#basicStreams` test flaky: approximately 0.25% of local runs would hit a Mockito `UnfinishedStubbingException`, which I believe was due to the potential for the `doAnswer` blocks to trigger another mocked method. I didn't fully track down the cause, but rather just removed the use of mocks for `ClientStreamListener` and `ServerStreamListener` altogether, and no longer observe failures across many thousands of runs.
This also adds an `#awaitOutboundHeaders` method to `TestClientStreamTracer` (https://github.com/grpc/grpc-java/pull/3305), as without this a small percentage of runs of `#basicStreams` would also fail due to a race between the server receiving the headers and the Netty future on …
> testing: reduce mocks in AbstractTransportTest to eliminate flakes

- examples/BUILD.bazel
- examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlClient.java
- examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlServer.java
- examples/src/main/proto/hello_streaming.proto
Refactor the proto file `helloworld_streaming.proto` because Bazel and Gradle have incompatible base directory for proto imports. Bazel's proto import is relative to WORKSPACE, whereas Gradle proto plugin's is relative to `${sourceSet}/proto/`. In `helloworld_streaming.proto` file, `import helloworld.proto` does not work for Bazel. If `import src/main/proto/helloworld.proto`, that works for Bazel, but Gradle and Maven would fail. Some workarounds are very hacky, so use independent proto without imports instead to avoid this issue.
> examples: fix Bazel build

- core/src/main/java/io/grpc/InternalMethodDescriptor.java
- core/src/main/java/io/grpc/MethodDescriptor.java
- core/src/main/java/io/grpc/internal/CensusTracingModule.java
- core/src/test/java/io/grpc/MethodDescriptorTest.java
- core/src/test/java/io/grpc/internal/CensusModulesTest.java
- testing-proto/src/test/java/io/grpc/testing/protobuf/SimpleServiceTest.java
move census registration into internal, and preserve tracing bit when rebuilding a MethodDescriptor
> core: move census registration into internal

- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
Mocks fail in GAE+jdk7 with this exception, so avoid using mocks.
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.google.apphosting.runtime.security.shared.stub.sun.reflect.ReflectionFactory
at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.<init>(SunReflectionFactoryInstantiator.java:24)
at org.objenesis.strategy.StdInstantiatorStrategy.newInstantiatorOf(StdInstantiatorStrategy.java:65)
at org.objenesis.ObjenesisBase.getInstantiatorOf(ObjenesisBase.java:76)
at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:59)
at org.mockito.internal.creation.jmock.ClassImposterizer.createProxy(ClassImposterizer.java:128)
at org.mockito.internal.creation.jmock.ClassImposterizer.imposterise(ClassImposterizer.java:63)
at …
```
> Make AbstractInteropTest runnable in GAE+jdk7

- core/src/main/java/io/grpc/LoadBalancer.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
Resolves #3355
GrpclbLoadBalancer should use PickResult.withDrop() instead of
PickResult.withError() when dropping RPCs.
> core: add first-class drop support in LoadBalancer.

- core/src/main/java/io/grpc/internal/CensusStatsModule.java
- core/src/main/java/io/grpc/internal/CensusTracingModule.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbClientLoadRecorder.java
These are created per call, so use volatiles to save memory
> core,grpclb: use denser atomics for census

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
This behavior is documented in the javadoc of LoadBalancer.shutdown().
Resolves #3545
> core: do not call LoadBalancer callbacks after it's shut down.

- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
The check fails in Java-Go interop test because of
https://github.com/grpc/grpc-go/issues/1572
This is also needed for the internal gRPC-GFE test.
Resolves #3562
> interop-test: disable message size check in interop-test client.

- core/src/main/java/io/grpc/util/RoundRobinLoadBalancerFactory.java
- core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
In relative order of importance:
* Don't acquire lock when picking subchannel.
* Use O(1) lookup for updating channel state
* Use non synchronized ref instead of AtomicReference
* Dont store size in picker.
* make class final
* remove test that was not valid
> util: improve scalabiltiy of RR load balancer

- stub/BUILD.bazel
This is the error when running `bazel build ...` from the root dir:
```
external/grpc_java/stub/src/main/java/io/grpc/stub/AbstractStub.java:46: error: [strict] Using type com.google.errorprone.annotations.DoNotMock from an indirect dependency (TOOL_INFO: "@com_google_errorprone_error_prone_annotations//jar"). See command below **
@DoNotMock
^
** Please add the following dependencies: 
@com_google_errorprone_error_prone_annotations//jar  to @grpc_java//stub 
** You can use the following buildozer command: 
buildozer 'add deps @com_google_errorprone_error_prone_annotations//jar ' @grpc_java//stub 
```
> stub: add missing bazel dep com_google_errorprone

- core/src/main/java/io/grpc/internal/BackoffPolicy.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/OobChannel.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
This is required by an internal use case.  We have already been doing
so for Subchannels.
> core: refresh name resolution when an OOB connection is closed.

- cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
Since 7df9ae97, ClientTransportFactory#newClientTransport
requires a ProxyParam arg.
> cronet: add ProxyParam arg to CronetTransportFactory

- core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java
Otherwise the scheme (https) is used to determine the port.
> core: Add port to proxy URL for Authenticator

- buildscripts/kokoro/macos.cfg
- buildscripts/kokoro/unix.sh
An initial noop task, so that our internal build system always succeeds for osx.
The end goal is to move macos builds from travis to kokoro.
> kokoro: Initial config files for macos

- core/src/test/java/io/grpc/internal/ProxyDetectorImplTest.java
Using HostAndPort just complicates the code. HostAndPort is also @Beta,
which is generally fine to use in tests, but is needless here.
> core: Use literal host:port instead of computing

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
> core: Fix naming style of string constants

- context/src/main/java/io/grpc/Context.java
- context/src/test/java/io/grpc/ContextTest.java
This achieves two things:
* communicates that `CancellableContext` is a resource that must be freed
* provides the ability to use the try-with-resources idiom to cancel the context when we finish up some blocking work. For users, this may be a better API than `runAndCancel` and `callAndCancel`.
@ejona86 and I considered adding a try-with-resources API that attaches the CancellableContext before the `try`, and *both* cancels as well as detaches at the `close`. But the problem is that the close runs before any catch statements, so users will not be able to use the exception as the cancellation cause unless they use a nested try/catch.
We also considered adding a try-with-resources API to attach/detach a context without cancelling, so that the two `try` statements in the example will look …
> context: Make CancellableContext implement Closeable

- examples/build.gradle
The sourceSets also works with Eclipse, and presumably other IDEs (OOB).
see also https://github.com/google/protobuf-gradle-plugin/issues/109
> Replace IntelliJ IDEA specific sourceDirs with sourceSets

- .travis.yml
With #3608 Kokoro is now able to handle OS X. I'm not removing the
OS X-specific parts of the .travis.yml in case we need to revert back to
using Travis.
Fixes #3466
> travis: Remove OS X build

- buildscripts/kokoro/unix.sh
Remove the `&&`s so that the script will fail due to the build command failing, instead of `pushd` failing
> buildscripts: make the script fail for the right reason with set -e

- netty/src/main/java/io/grpc/netty/NettyServerTransport.java
Move netty connection log info to a separate logger:
io.grpc.netty.NettyServerTransport.connections
Users can redirect or disable this log using the usual way:
-Djava.util.logging.config.file="logging.properties"
Related to #1768, #3575
> netty: separate connection log

- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
We don't need the synchronization StringBuffer provides
> testing: Use StringBuilder instead of StringBuffer

- buildscripts/kokoro/unix.sh
- buildscripts/make_dependencies.sh
Be even more defensive with our shell scripts, to avoid future mistakes:
`set -u` : reading an unset env variable will fail. In conditional statements we must always check the variable is bound `-v FOO && ` before reading its value. When combined with `set -e` causes the script to exit if we use an unbound variable.
`set -o pipefail`: When used with `set -e` causes the script to exit if any part of a pipe expression fails
> buildscripts: set -u, set -o pipefail

- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/ReportQpsScenarioServiceGrpc.java
- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
- benchmarks/src/jmh/java/io/grpc/benchmarks/netty/SingleThreadBlockingQpsBenchmark.java
- benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadServer.java
- compiler/src/java_plugin/cpp/java_generator.cpp
- compiler/src/test/golden/TestService.java.txt
- compiler/src/testLite/golden/TestService.java.txt
- compiler/src/testNano/golden/TestService.java.txt
- grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- interop-testing/src/test/java/io/grpc/stub/StubConfigTest.java
- services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java
- services/src/generated/main/grpc/io/grpc/instrumentation/v1alpha/MonitoringGrpc.java
- services/src/generated/main/grpc/io/grpc/reflection/v1alpha/ServerReflectionGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/AnotherDynamicServiceGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/DynamicServiceGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/ReflectableServiceGrpc.java
- testing-proto/src/generated/main/grpc/io/grpc/testing/protobuf/SimpleServiceGrpc.java
- testing-proto/src/test/java/io/grpc/testing/protobuf/SimpleServiceTest.java
Several commits so you can see the changes
Key things:
* MethodDescriptor is lazy loaded, so protobuf loading only happens on demand.  This also means tracing registration happens  on demand.  
* The names of the getters all being with `method`.  This makes it harder for autocomplete to pick them up.
* A new field is used, which matches the getter name.  Rather than make the new-getters reference the old-fields, make the old-fields reference the new getters.  This makes removal of the old-fields a simple operation.  
* The getters may not be inlineable, but thats an easy fix if it ends up being a problem.  Not worth premature optimization (but is worth future work).
The expected timeline for this is adding this to the 1.8 cut, and deprecating the old-fields.  They will be removed in 1.9.
>  compiler: add methods for accessing method descriptors

- examples/android/helloworld/gradle/wrapper/gradle-wrapper.properties
- examples/android/routeguide/gradle/wrapper/gradle-wrapper.properties
- examples/gradle/wrapper/gradle-wrapper.properties
- gradle/wrapper/gradle-wrapper.properties
While this fixes a Gradle-caused failure on Java 9, it is still failing
due to Generated annotations as seen in #3633.
Fixes #3632
> Upgrade to Gradle 4.3

- android-interop-testing/app/proguard-rules.pro
Fixes https://github.com/grpc/grpc-java/issues/3635. https://github.com/grpc/grpc-java/commit/a3ff9cd784fce8a3a05054f0cd695954283e51f5 changed `grpc-testing`'s dependency on the Truth library to compileOnly, which confuses Proguard here. Adding `-whyareyoukeeping class io.grpc.testing.DeadlineSubject` to the proguard file shows that `DeadlineSubject` is indeed being stripped out by Proguard, so it seems safe to just ignore the earlier warning.
> android-interop-testing: fix proguard for grpc-testing dependency

- android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/InteropTester.java
- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/ReportQpsScenarioServiceGrpc.java
- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
- compiler/src/java_plugin/cpp/java_generator.cpp
- compiler/src/test/golden/TestService.java.txt
- compiler/src/testLite/golden/TestService.java.txt
- compiler/src/testNano/golden/TestService.java.txt
- grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
- services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java
- services/src/generated/main/grpc/io/grpc/instrumentation/v1alpha/MonitoringGrpc.java
- services/src/generated/main/grpc/io/grpc/reflection/v1alpha/ServerReflectionGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/AnotherDynamicServiceGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/DynamicServiceGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/ReflectableServiceGrpc.java
- testing-proto/src/generated/main/grpc/io/grpc/testing/protobuf/SimpleServiceGrpc.java
This includes a few other minor changes:
* imports are now sorted
* The javadoc link is now correct
>  compiler: remove references to static fields

- SECURITY.md
Our static initialization in `OkHttpProtocolNegotiator` has impacted a couple of Android users recently when trying to use the Play Services Dynamic Security provider, so just calling out this requirement explicitly in our docs.
> SECURITY.md: provider must be installed before channel creation

- core/src/main/java/io/grpc/Contexts.java
The message isn't great, but _much_ better than no message.
> core: Add description for Status mapped from error-less Context

- stub/src/main/java/io/grpc/stub/ClientCalls.java
Changes:
* No longer catch throwable, and don't wrap Error
* log an error if call.cancel() throws
* Unwrap ExecutionExcetion  always
* include a description with cancellation when interrupted
> stub: clean up call cancellation

- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpTransportTest.java
- testing/src/main/java/io/grpc/internal/testing/TestUtils.java
Our Travis-CI builds are failing with `Protocol family unavailable` due
to the usage of ::1. Although it's 2017 and we'd expect to have ipv6
_loopback_ anywhere that mattered, apparently that's not the case.
The tests now work equally well on IPv4-only and IPv6-only machines.
> Allow tests to run on IPv6-less machines

- protobuf-lite/build.gradle
This seems to be an intellij-only problem, everything compiles and tests fine from the gradle CLI. Intellij complains that in `ProtoLiteUtilsTest`  com.google.protobuf.{Empty, Enum, Type} can not be found unless this is added.
Not sure if this one is related: https://github.com/grpc/grpc-java/pull/3598
> protobuf-lite: add javalite generated sources to intellij path

- core/src/main/java/io/grpc/ManagedChannel.java
- core/src/main/java/io/grpc/internal/InternalSubchannel.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
This addresses https://github.com/grpc/grpc-java/issues/2169. Currently users of OkHttp may have to wait up to 60 seconds (for DNS resolution to be re-attempted) or longer (if in exponential backoff to reconnect after `TRANSIENT_FAILURE`) for RPCs to succeed after the network connection is re-established. This provides a hook for apps to tell gRPC that the network is available and name resolution and reconnection attempts may occur immediately.
> core: add resetConnectBackoff() method to ManagedChannel

- android-interop-testing/app/build.gradle
- android-interop-testing/app/src/main/AndroidManifest.xml
- examples/android/helloworld/app/build.gradle
Bumps `minSdkVersion` to 14. This is the minimum API level supported by recent Google Play Services, and also required by some internal Android tooling. This also bumps the minSdkVersion for the helloworld example (our routeguide example already has a higher minSdkVersion set, so just left that alone).
> android-interop-testing,examples: bump minimumSdkVersion to 14

- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
This change removes some of the non deterministic size outputs for
proto.  Instead of serializing the message and measuring the size,
measure before serialization.  As long as the remote always returns
using the same encoder, this should be stable.
Fixes: #3547
> interop-testing:  make max size tests more deterministic

- core/src/main/java/io/grpc/internal/AbstractClientStream.java
- core/src/main/java/io/grpc/internal/AbstractServerStream.java
- core/src/main/java/io/grpc/internal/MessageFramer.java
- core/src/main/java/io/grpc/internal/TransportTracer.java
- core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
- core/src/test/java/io/grpc/internal/AbstractServerStreamTest.java
- core/src/test/java/io/grpc/internal/MessageFramerTest.java
- netty/src/main/java/io/grpc/netty/NettyClientStream.java
- netty/src/main/java/io/grpc/netty/NettyServerStream.java
- netty/src/main/java/io/grpc/netty/SendGrpcFrameCommand.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
- netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
- netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
- netty/src/test/java/io/grpc/netty/NettyServerStreamTest.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
This lets us remove synchronization for `lastMessageSentTimeNanos` and `messagesSent` in the TransportTracer.
> core,netty,okhttp: move transport tracer outbound counters to transport thread

- core/src/main/java/io/grpc/internal/ClientTransport.java
- core/src/main/java/io/grpc/internal/DelayedClientTransport.java
- core/src/main/java/io/grpc/internal/FailingClientTransport.java
- core/src/main/java/io/grpc/internal/ForwardingConnectionClientTransport.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
This merely adds the method but does not do anything yet on the implementations.
> core,netty,okhttp: Add getTransportStats method to ClientTransport

- java_grpc_library.bzl
'includes' were already handled, but not 'src's. This allows you to
depend on things like :any_proto from the protobuf repo.
Fixes #3650 
The test for this is in #3674, but it can't be merged until we update
protobuf.
CC @ah-edg
> java_grpc_library: fix remote protos that are 'src's

- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/main/java/io/grpc/internal/ProxyDetector.java
- core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
- core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
This is a workaround of the security restrictions, but effectively turns off proxy support in GAE+JDK7.
I can't seem to get AccessController to work in GAE, the checkPermission API fails:
```
Can not use checkPermission:
Caused by: java.lang.SecurityException: AccessController.checkPermission is unsupported.
```
And doPriviledged also fails:
```
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Thrown from handleResolvedAddresses(): java.lang.NoClassDefFoundError: java.net.ProxySelector is a restricted class. Please see the Google App Engine developer's guide for more details.
```
Let's use the usual technique of checking for the `IS_RESTRICTED_APPENGINE` flag.
Fixes https://github.com/grpc/grpc-java/issues/3676
> core: no ProxyDetector for GAE+JDK7

- build.gradle
- core/build.gradle
- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
- core/src/main/java/io/grpc/internal/CensusStatsModule.java
- core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
- core/src/test/java/io/grpc/internal/AbstractServerImplBuilderTest.java
- core/src/test/java/io/grpc/internal/CensusModulesTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
- interop-testing/src/test/java/io/grpc/testing/integration/AutoWindowSizingOnTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyLocalChannelTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/InProcessTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/TransportCompressionTest.java
- testing/src/main/java/io/grpc/internal/TestingAccessor.java
- testing/src/main/java/io/grpc/internal/testing/StatsTestUtils.java
This commit updates gRPC core to use io.opencensus:opencensus-api and
io.opencensus:opencensus-contrib-grpc-metrics instead of
com.google.instrumentation:instrumentation-api for stats and tagging. The gRPC
Monitoring Service continues to use instrumentation-api.
The main changes affecting gRPC:
- The StatsContextFactory is replaced by three objects, StatsRecorder, Tagger,
and TagContextBinarySerializer.
- The StatsRecorder, Tagger, and TagContextBinarySerializer are never null,
but the objects are no-ops when the OpenCensus implementation is not
available.
This commit includes changes written by @songy23 and @sebright.
_________________________________________________________________
I added two TODOs for parts that I didn't know how to update.  This PR is still using the snapshot of …
> core: use new OpenCensus stats/tagging API.

- gae-interop-testing/gae-jdk7/src/main/java/io/grpc/testing/integration/OkHttpClientInteropServlet.java
- gae-interop-testing/gae-jdk8/src/main/java/io/grpc/testing/integration/NettyClientInteropServlet.java
Tests that require serverInProcess() will not work because the server
is remote.
> gae-interop-testing: disable serverInProcess tests

- gae-interop-testing/gae-jdk7/build.gradle
- gae-interop-testing/gae-jdk7/src/main/java/io/grpc/testing/integration/OkHttpClientInteropServlet.java
- gae-interop-testing/gae-jdk8/src/main/java/io/grpc/testing/integration/NettyClientInteropServlet.java
Do not rely on ManagedChannelBuilder to select the correct concrete
type; directly instantiate the required type.
> gae-interop-testing: concrete channel builders

- gae-interop-testing/gae-jdk7/src/main/java/io/grpc/testing/integration/OkHttpClientInteropServlet.java
- gae-interop-testing/gae-jdk8/src/main/java/io/grpc/testing/integration/NettyClientInteropServlet.java
Turns out the ManagedChannelBuilder was misbehaving because the
devserver launcher ignores the app's jdk7 configuration and uses
whatever jdk is in JAVA_HOME. This is the reason
GrpcUtil.IS_RESTRICTED_APPENGINE was wrong.
Changing JAVA_HOME to point to jdk7 reveals that devservers lack
conscrypt. Adding an explicit check to make sure the jdk7 test is not
running in a dev server.
> gae-interop-testing: use ManagedChannelBuilder, abort if devserver

- core/src/main/java/io/grpc/internal/AbstractClientStream.java
- core/src/main/java/io/grpc/internal/Http2ClientStreamTransportState.java
- core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
- core/src/test/java/io/grpc/internal/Http2ClientStreamTransportStateTest.java
- netty/src/main/java/io/grpc/netty/NettyClientStream.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
This diff does not actually change any behaviors yet, that will come
in the next diff along with unit tests for those new behaviors.
> core,netty,okhttp: add TransportTracer param to ClientStream and Http2ClientStreamTransportState

- core/src/test/java/io/grpc/MethodDescriptorTest.java
- core/src/test/java/io/grpc/internal/CallCredentialsApplyingTest.java
- core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- core/src/test/java/io/grpc/internal/ServerCallImplTest.java
- netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientStreamTest.java
The method name passed to MethodDescriptor does not include the leading
'/'. If it does, on the wire it will actually cause two slashes. This
has been this way for a _long_ time, but in tests that ignore the method
name or use the same MethodDescriptor no client and server the extra /
"works fine." But it's misleading, so let's remove it.
> Fix broken method names in tests that include leading '/'

- core/src/main/java/io/grpc/internal/AbstractClientStream.java
- core/src/main/java/io/grpc/internal/TransportTracer.java
- netty/src/main/java/io/grpc/netty/NettyClientStream.java
- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
- netty/src/main/java/io/grpc/netty/NettyServerStream.java
- netty/src/main/java/io/grpc/netty/SendGrpcFrameCommand.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
- netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
- netty/src/test/java/io/grpc/netty/NettyServerStreamTest.java
Bugfix for 9fac15d4f8fb09106fc4a80d761afbe1594b4d0c which always bumps the value by 1. Also remove msgCount from SendGrpcFrameCommand because it is no longer necessary.
> netty: bump correct value of outbound msg counter

- gae-interop-testing/gae-jdk7/src/main/java/io/grpc/testing/integration/OkHttpClientInteropServlet.java
Without this, the test is flakey for some test methods. The flakiness
is probably caused by AbstractInteropTest and not due to gRPC itself.
> gae-interop-testing: create new instance per test for okhttp

- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/main/java/io/grpc/internal/ProxyDetector.java
- core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
- core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
https://github.com/grpc/grpc-java/pull/3677
> core: backport pull #3677 to v1.8.x

- core/src/main/java/io/grpc/ServerBuilder.java
- core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
The two commits here are easiest to review separately and will be committed separately. The first adds support for a negotiation timeout to core and the second improves transportReady callback placement in Netty so the negotiation timeout applies to more phases.
Before merging I'll reserve an issue for `negotiationTimeout`'s `@ExperimentalApi` and update the annotation.
> core,netty: Add server negotiation timeout before client preface

- netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
Since Netty may have set some parameters already, we should modify the
existing SSLParameters instead of starting from scratch.
This may fix ALPN with JDK9, but full support for ALPN with JDK9 is
still later work and we're not supporting it yet.
Fixes #3532 
CC @vietj
> netty: Avoid clearing SSLParameters

- core/src/main/java/io/grpc/ClientCall.java
- stub/src/main/java/io/grpc/stub/CallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ClientCallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java
- stub/src/main/java/io/grpc/stub/StreamObserver.java
This mainly copies documentation from other places, like StreamObserver
and ClientCall, but does fix some missing important threading notes.
Fixes #3413
CC @bubenheimer
> stub: Improve threading expectation docs

- gae-interop-testing/gae-jdk7/build.gradle
- gae-interop-testing/gae-jdk8/build.gradle
While using + is convenient, it prevents builds from being
deterministic which makes it hard/impossible to reproduce a historic
build or execution results.
> gae-interop-testing: Pin appengine library version

- core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
- core/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java
- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
- core/src/main/java/io/grpc/internal/CensusStatsModule.java
- core/src/test/java/io/grpc/internal/CensusModulesTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- testing/src/main/java/io/grpc/internal/testing/StatsTestUtils.java
RPC upstarts are counted into metrics `RPC_{CLIENT,SERVER}_STARTED_COUNT`. In addition, RPC completions are counted into metrics `RPC_{CLIENT,SERVER}_FINISHED_COUNT`.  From these
metrics, users will be able to derive count of RPCs that are currently active.
/cc @dinooliva, @sebright
> core: record RPC upstarts to Census.

- okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
Disable census for now due to:
https://github.com/census-instrumentation/opencensus-java/issues/777
> okhttp: disable census when in GAE+JDK7

- core/BUILD.bazel
- repositories.bzl
This fixes the Bazel build after ef2ec949
This is a backport of #3697
> bazel: Add dep on opencensus-contrib-grpc-metrics (backport)

- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
> netty: fix server keepalive unexpected ping ack

- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
PR for https://github.com/grpc/grpc-java/issues/3370
> netty: Netty server poorly handles unknown content type

- gae-interop-testing/gae-jdk7/build.gradle
- gae-interop-testing/gae-jdk8/build.gradle
While using + is convenient, it prevents builds from being
deterministic which makes it hard/impossible to reproduce a historic
build or execution results.
Backport of #3716
> gae-interop-testing: Pin appengine library version (backport)

- core/src/main/java/io/grpc/internal/CensusStatsModule.java
- core/src/main/java/io/grpc/internal/CensusTracingModule.java
- core/src/main/java/io/grpc/internal/SerializingExecutor.java
Replaces https://github.com/grpc/grpc-java/pull/3753. Leaves the synchronized fallback in place for SerializingExecutor, but just falls back to (racy) volatile updates in the stats modules.
> core: workaround for Atomic*FieldUpdater bug on some Android devices

- core/src/main/java/io/grpc/ServiceDescriptor.java
This should reference reflection rather than the ServiceDescriptor.Builder experimental tracking issue.
> core: correct issue number for getSchemaDescriptor()

- core/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
handshakeTimeout is unnecessary for InProcess, and the scheduling is causing
Thread creation that is breaking restrictive test environments. Those
environments are mostly broken already because client-side will try to create
Threads as well, but they are currently lucking out that the exception on
client-side doesn't break much.
> core: Disable handshakeTimeout for InProcess

- core/src/main/java/io/grpc/HandlerRegistry.java
- core/src/main/java/io/grpc/ServerBuilder.java
MutableHandlerRegistry from #933 is not stabilized, so this is not enough to
resolve the issue.
> core: Stabilize HandlerRegistry

- core/src/main/java/io/grpc/ManagedChannelBuilder.java
The CallOptions from #1767 are not included, so this is not enough to resolve
the issue.
> core: Stabilize ManagedChannelBuilder.overrideAuthority

- auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
- auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java
Fixes #3267 
Should we backport this to 1.8?
CC @buchgr
> auth: Treat IOExceptions as UNAVAILABLE

- core/src/main/java/io/grpc/ManagedChannel.java
ManagedChannel now supports the getState/notifyWhenStateChanged API (#2292).
> core: update ManagedChannel docs (#3762)

- SECURITY.md
This also fixes an oversight for the 1.0.2+ releases, since they had a
different netty version.
> SECURITY.md: Avoid needing to update tcnative table every release

- netty/src/main/java/io/grpc/netty/Utils.java
There's been another sighting, but it's very hard to narrow down what is
triggering it.
> netty: Include more stace trace information for ClosedChannelExceptions

- core/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
handshakeTimeout is unnecessary for InProcess, and the scheduling is causing
Thread creation that is breaking restrictive test environments. Those
environments are mostly broken already because client-side will try to create
Threads as well, but they are currently lucking out that the exception on
client-side doesn't break much.
This is a backport of #3764
> core: Disable handshakeTimeout for InProcess (backport)

- SECURITY.md
This also fixes an oversight for the 1.0.2+ releases, since they had a
different netty version.
This is a backport of #3767
> SECURITY.md: Avoid needing to update tcnative table every release (backport)

- protobuf/build.gradle
This breaks javanano links, but the value to normal and lite proto seems
more important.
Trivia: I've had this branch lying around for a while... "Tue Aug 18 14:04:30 2015 -0700". All I did is replace "FIXME: breaks javanano documentation" in the commit message. :smile:
> Link JavaDoc to protobuf JavaDoc

- auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
- auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java
Fixes #3267 
This is a backport of #3757
> auth: Treat IOExceptions as UNAVAILABLE (backport)

- core/src/main/java/io/grpc/ManagedChannel.java
ManagedChannel now supports the getState/notifyWhenStateChanged API (#2292).
This is a backport of #3768
> core: update ManagedChannel docs (#3762) (backport)

- repositories.bzl
- testing/BUILD.bazel
Adds necessary dependencies and bazel build rules to create `@grpc_java//testing`.
I tried to follow bazel conventions and style I found in `code/BUILD.bazel`.
> testing: bazel build targets

- compiler/build.gradle
Useful when building bazel and tensorflow for some nvidia devices.
> compiler: Build on aarch64

- context/build.gradle
- context/src/test/java/io/grpc/StaticTestingClassLoader.java
- context/src/test/java/io/grpc/testing/DeadlineSubject.java
- core/build.gradle
- interop-testing/build.gradle
The class is still used internally, so we move it to context's tests for
it to be reused. To avoid a circular dependency with context's tests
depending on core's tests, StaticTestingClassLoader was also moved to
context's tests.
This is driven by a need to modernize DeadlineSubject for newer versions
of Truth, but the newer versions of Truth update Guava. To avoid leaking
the Guava update to all users of grpc-testing, we're removing the
Subject. In our internal tests we can update the Truth dependency with
less issue.
CC @JiangJi 
Some discussion in #3779
> testing: Remove DeadlineSubject

- core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
Previously it was 20s. 20s isn't _bad_, but may be too aggressive.
Having it longer doesn't hurt us too much; we just need some bound.
Since the MAX_BACKOFF on client-side is 120s, this will have client and
server match, except for jitter. Although I will note that the
client-side value covers more work than the server-side, such as
attempting to connect to multiple hosts.
> core: Increase server handshake timeout to 120s

- core/src/main/java/io/grpc/MethodDescriptor.java
- core/src/main/java/io/grpc/internal/BinaryLog.java
- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/ServerCallImpl.java
- core/src/test/java/io/grpc/internal/BinaryLogTest.java
ServerCallImpl and ClientCallImpl will each have a BinaryLog
field. Each time the constructor is called, we will do a lookup
for the log. Performance is not critical for binlog, but if it
becomes a problem MethodDescriptor can have a setter to store
it as an Object (to avoid a depdency on `internal`).
The binary log class is a skeleton class at the moment, but does
contain the max header and message length info. The limits are
determined by parsing the shell variable GRPC_BINARY_LOG_CONFIG.
> core: initial binary log class

- build.gradle
- repositories.bzl
Okio buffers gained some useful methods for interop with java nio.   These methods are needed to pass bytebuffers to the new proto api in 3.5.0
> okhttp: bump to okio 1.13.0

- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
Previously fallback mode can be entered only if the client has not
received any server list and the fallback timeout has expired.
Now the fallback timer is started when the stream to the balancer is broken
AND there is no ready Subchannels. Fallback mode is activated when the
timer expires. When a new server list is received from the balancer, either
the fallback timer is cancelled, or fallback mode is exited.
Also fixed a bug that the fallback timer should've been cancelled when GrpcState
is shut down.
> grpclb: switch to fallback mode if all connections are lost

- buildscripts/kokoro/gae-interop.sh
- gae-interop-testing/gae-jdk7/build.gradle
- gae-interop-testing/gae-jdk8/build.gradle
GAE interop tests:
- add runtime configs to jdk7 and jdk8 projects 
kokoro scripts: 
- make sure a 'dummy-default' version always exists
- when the tests are done, divert all traffic to dummy-default and delete the version deployed for tests
> gae-interop-testing: kokoro script to run interop tests in GAE

- core/src/main/java/io/grpc/InternalTransportStats.java
- core/src/main/java/io/grpc/inprocess/InProcessTransport.java
- core/src/main/java/io/grpc/internal/ClientTransport.java
- core/src/main/java/io/grpc/internal/DelayedClientTransport.java
- core/src/main/java/io/grpc/internal/FailingClientTransport.java
- core/src/main/java/io/grpc/internal/ForwardingConnectionClientTransport.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/main/java/io/grpc/internal/ServerTransport.java
- core/src/main/java/io/grpc/internal/TransportTracer.java
- core/src/test/java/io/grpc/internal/MessageDeframerTest.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/main/java/io/grpc/netty/NettyServerTransport.java
- netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
io.grpc can not refer to io.grpc.internal so this needs to be moved
out. The end state will have the channelz class in io.grpc, which
needs to refer to stats like this.
> core,netty,okhttp: move TransportTracer.Stats to io.grpc

- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/DelayedClientTransport.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/OobChannel.java
- core/src/main/java/io/grpc/internal/RetriableStream.java
- core/src/test/java/io/grpc/internal/RetriableStreamTest.java
With an approach using a variant of `DelayedStream` - `RetriableStream`.
`RetriableStream` is a logical stream per call that can create a sequence of `substreams`, the physical streams for the retry attempts. It could also create a family of substreams in parallel in hedging case.
`RetriableStream` buffers, delays and executes stream operations before `passThrough`, where `passThrough` is meant by `commit` as well as the buffer `drained` by the winning substream.
This PR only implements buffering messages and replaying buffered messages when retry.
Retry policy, hedging, transparent retry, backoff, max buffer size and APIs that users can enable retry are not included in this PR.
> core: retry support part 1, RetriableStream

- core/src/main/java/io/grpc/InternalLogId.java
- core/src/main/java/io/grpc/InternalWithLogId.java
- core/src/main/java/io/grpc/inprocess/InProcessTransport.java
- core/src/main/java/io/grpc/internal/DelayedClientTransport.java
- core/src/main/java/io/grpc/internal/ForwardingConnectionClientTransport.java
- core/src/main/java/io/grpc/internal/InternalSubchannel.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/ManagedClientTransport.java
- core/src/main/java/io/grpc/internal/OobChannel.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
- core/src/main/java/io/grpc/internal/ServerTransport.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/main/java/io/grpc/netty/NettyServer.java
- netty/src/main/java/io/grpc/netty/NettyServerTransport.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
The channelz service must not live in io.grpc.internal, and channelz
needs to be able to get the identifier of the entities it
tracks. Since io.grpc can not refer to io.grpc.internal, the LogId
must be moved out of internal.
> core: move WithLog and LogId to io.grpc

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/RetriableStream.java
- core/src/test/java/io/grpc/internal/RetriableStreamTest.java
2 commits:
- the first one is pure refactoring to add Substream class,
- the second is not to add closed substreams to drainedSubstreams.
> core: retry support part 1 followup, drainedSubstreams should not contain closed ones

- repositories.bzl
The protobuf checksums were simply not updated when changing the
version.
> bazel: Fix protobuf checksums

- gae-interop-testing/gae-jdk7/src/main/java/io/grpc/testing/integration/OkHttpClientInteropServlet.java
- gae-interop-testing/gae-jdk8/src/main/java/io/grpc/testing/integration/NettyClientInteropServlet.java
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
- interop-testing/src/test/java/io/grpc/testing/integration/AutoWindowSizingOnTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyLocalChannelTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/InProcessTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/TransportCompressionTest.java
By doing this we can isolate the Census records for each test, and
eliminate the trial-and-error workaround in AbstractInteropTest.
This is a preferred fix for #3777 and supersedes #3803
> interop-testing: start a new server for each test method.

- BUILD.bazel
I'm planning to wait for when we update to the next protobuf release before merging this.
> java_grpc_library: add test for remote proto in srcs

- build.gradle
- context/src/test/java/io/grpc/testing/DeadlineSubject.java
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
Due to transitive dependencies, this also upgrades Guava to 22. However
Truth is only used in our tests, so our users should be unimpacted.
CC @JiangJi. Sorry for the delay; I've been quite busy.
> Update to Truth 0.36

- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpTransportTest.java
- testing/src/main/java/io/grpc/internal/testing/TestUtils.java
Our Travis-CI builds are failing with "Protocol family unavailable" due
to the usage of ::1. Although it's 2017 and we'd expect to have ipv6
_loopback_ anywhere that mattered, apparently that's not the case.
The tests now work equally well on IPv4-only and IPv6-only machines.
This is the 1.7.x backport of #3654.
> Allow tests to run on IPv6-less machines (backport)

- buildscripts/jenkins-pre.bat
- buildscripts/kokoro/windows.bat
- buildscripts/make_dependencies.bat
We already depend on Powershell, so this should make it easier to use the
script with less set-up.
> buildscripts: Remove dependency on 7za

- netty/shaded/build.gradle
- netty/shaded/src/testShadow/java/io/grpc/netty/shaded/ShadingTest.java
- settings.gradle
The entire transport is shaded because we wouldn't want to collide with
the unshaded form of grpc-netty.
> Shade Netty transport

- compiler/build.gradle
This allows building release binaries on Windows without Bash and GCC.
> compiler: Verify binary with native VS commands

- core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
- core/src/main/java/io/grpc/inprocess/InProcessTransport.java
- core/src/test/java/io/grpc/inprocess/InProcessTransportTest.java
Currently, InProcess(io.grpc.inprocess) does not support the use of a user-agent, but it may be useful for testing of `LoggingInterceptor`(It is just an example, it records the status, responses, user-agent, etc to log files).
> core: support user-agent in InProcess

- core/src/main/java/io/grpc/Attributes.java
- core/src/test/java/io/grpc/AttributesTest.java
> core: fix Attributes value equality

- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/ChannelStats.java
- core/src/main/java/io/grpc/internal/ChannelTraceStats.java
- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/OobChannel.java
- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
The call begin stat is bumped when the application calls `.start` and call end stats are bumped when the  `ClientStreamListener.closed` callback is called. This means the begin stat on the channel will be bumped immediately but the transport level stats may come later because of  `DelayedClientTransport`. The call end stats may be bumped on the transport first, and will finally be bumped on the channel when the callback gets triggered.
> Add ChannelStats and tests

- core/src/main/java/io/grpc/Instrumented.java
- core/src/main/java/io/grpc/InternalInstrumented.java
- core/src/main/java/io/grpc/InternalLogId.java
- core/src/main/java/io/grpc/InternalWithLogId.java
- core/src/main/java/io/grpc/LogId.java
- core/src/main/java/io/grpc/WithLogId.java
- core/src/main/java/io/grpc/inprocess/InProcessTransport.java
- core/src/main/java/io/grpc/internal/ClientTransport.java
- core/src/main/java/io/grpc/internal/DelayedClientTransport.java
- core/src/main/java/io/grpc/internal/FailingClientTransport.java
- core/src/main/java/io/grpc/internal/ForwardingConnectionClientTransport.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/main/java/io/grpc/internal/ServerTransport.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/main/java/io/grpc/netty/NettyServerTransport.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
This allows the channelz class to keep collections of type `Map<Long, InternalInstrumented<T>>`, where `T` is an `@Internal` class that lives in `io.grpc`.
> core: InternalInstrumented<T> for instrumented classes

- cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
- cronet/src/main/java/io/grpc/cronet/CronetClientStream.java
- cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java
- cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java
- cronet/src/test/java/io/grpc/cronet/CronetClientTransportTest.java
AbstractStream now requires TransportTracer to be non-null.
> cronet: pass TransportTracer instead of null.

- services/src/main/java/io/grpc/services/BinaryLog.java
- services/src/test/java/io/grpc/services/BinaryLogTest.java
We actually do want to differentiate between cases like "log peer
info but 0 bytes of headers" and "do not log".
> services: BinaryLog.Factory return nulls

- RELEASING.md
- core/src/main/java/io/grpc/internal/GrpcUtil.java
Using META-INF for loading the version is broken on Android and
frequently broken when gRPC is shaded. Having hard-coded strings be
replaced on version bumps has been working well.
Fixes #2098
> core: Use hard-coded string for version

- core/src/main/java/io/grpc/Grpc.java
- core/src/main/java/io/grpc/internal/DnsNameResolver.java
- core/src/main/java/io/grpc/internal/GrpcAttributes.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbConstants.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
This is part one of handling service config, and also enabled grpclb to work.  I manually tested this with some complex DNS data, but I dont have many unit tests because we dont have a dummy DNS server.   
Handling or the SRV records logs failures and tries to keep going.
> core/grpclb: resolve TXT records in DNS name resolver and include balancer addresses

- repositories.bzl
Updating SHA-1 checksum for com_google_api_grpc_google_common_protos Skylark rule.
The new value is reported as the expected value when performing
$ bazel build //...
on a clean pull of this repo. The new value can also be confirmed via
$ curl http://central.maven.org/maven2/com/google/api/grpc/proto-google-common-protos/1.0.0/proto-google-common-protos-1.0.0.jar | sha1sum
> Update proto Skylark rule to allow gRPC Java to build using Bazel

- testing/src/main/java/io/grpc/testing/StreamRecorder.java
This reverts commit dc71083ce913152763e86ffbc79a78e88b6f04a3.
StreamRecorder is too old and may have users unable to migrate it out easily soon.
> Revert "testing: delete deprecated StreamRecorder"

- testing/src/main/java/io/grpc/testing/StreamRecorder.java
cherry-pick 659cce52b6bfce9f13527de48ac6cb7358809daf
> Revert "testing: delete deprecated StreamRecorder" (back port to 1.9)

- core/src/main/java/io/grpc/internal/DelayedClientTransport.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
As pointed out by @zhangkun83 delayedTransport `shutdown` will make retry attempts that are in backoff unable to create new stream. So wrap delayedTransport with `retriableTransport`, which will keep uncommitted retriable streams alive when `shutdown`.
> core: retry support part 1 followup, channel.shutdown should not fail retry in backoff

- netty/src/main/java/io/grpc/netty/GrpcSslContexts.java
- netty/src/main/java/io/grpc/netty/JettyTlsUtil.java
- netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
Netty `4.1.16` supports Java 9 ALPN, gRPC should take advantage of that to ease deployment (especially on platforms without tcnative and/or openssl).
This PR determines whether Java 9 ALPN and Netty 4.1.16 is available and enables Netty Java 9 ALPN.
> Use java 9 ALPN if available

- core/src/main/java/io/grpc/ManagedChannel.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/OobChannel.java
Two APIs were added to ManageChannel. This would be API breaking if they are still abstract.
> core: fix unimplemented API in ManageChannel

- .travis.yml
- COMPILING.md
- README.md
- android-interop-testing/app/build.gradle
- build.gradle
- buildscripts/kokoro/unix.sh
- buildscripts/make_dependencies.bat
- compiler/Dockerfile
- examples/android/helloworld/app/build.gradle
- examples/android/routeguide/app/build.gradle
- examples/build.gradle
- examples/pom.xml
- repositories.bzl
protoc-3.5.0-linux-x86_64 introduced GLIBC_2.14 dependency and broke
gRPC release process (https://github.com/google/protobuf/issues/4138).
3.5.1-1 is the proper re-build.
> Upgrade to Protobuf 3.5.1 and Protoc 3.5.1-1.

- .travis.yml
- COMPILING.md
- README.md
- android-interop-testing/app/build.gradle
- build.gradle
- buildscripts/kokoro/unix.sh
- buildscripts/make_dependencies.bat
- compiler/Dockerfile
- examples/android/helloworld/app/build.gradle
- examples/android/routeguide/app/build.gradle
- examples/build.gradle
- examples/pom.xml
- repositories.bzl
protoc-3.5.0-linux-x86_64 introduced GLIBC_2.14 dependency and broke
gRPC release process (https://github.com/google/protobuf/issues/4138).
3.5.1-1 is the proper re-build.
> Upgrade to Protobuf 3.5.1 and Protoc 3.5.1-1. (backport #3921)

- RELEASING.md
We're no longer using Jenkins, and the equivalent parts necessary for
Kokoro are in go/grpc/java/releasing.
> RELEASING.md: Remove Jenkins job creation

- repositories.bzl
Currently, grpc-java could not build by bazel because protobuf's sha256 is incorrect.
It might need some CI (travis or kokoro(?)) checking.
```
$ bazel build //protobuf:all
....................
ERROR: /Users/jyane/workspace/repos/github.com/jyane/grpc-java/protobuf/BUILD.bazel:1:1: no such package '@com_google_protobuf_java//': Error downloading [https://github.com/google/protobuf/archive/v3.5.1.zip] to /private/var/tmp/_bazel_jyane/6860dd76b063c3142c2bc69dd88c44cb/external/com_google_protobuf_java/v3.5.1.zip: Checksum was 1f8b9b202e9a4e467ff0b0f25facb1642727cdf5e69092038f15b37c75b99e45 but wanted cef7f1b5a7c5fba672bec2a319246e8feba471f04dcebfe362d55930ee7c1c30 and referenced by '//protobuf:protobuf'
ERROR: /Users/jyane/workspace/repos/github.com/jyane/grpc-java/protobuf/BUILD.bazel:1:1: …
```
> bazel: fix protobuf sha256

- buildscripts/kokoro/windows.bat
Our build isn't happy on Java 9 yet.
> buildscripts: Avoid Java 9 for Windows CI

- core/src/test/java/io/grpc/ClientInterceptorsTest.java
- core/src/test/java/io/grpc/ServerInterceptorsTest.java
- examples/src/test/java/io/grpc/examples/header/HeaderClientInterceptorTest.java
- examples/src/test/java/io/grpc/examples/header/HeaderServerInterceptorTest.java
- examples/src/test/java/io/grpc/examples/helloworld/HelloWorldClientTest.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
- netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
Spies are really magical and easily produce unexpected results. Using them in
tests can easily yield tests that don't do what you think they do. Delegation
is much safer when possible.
Delegation doesn't work when methods `return true`, final methods, and with
restricted visibility, though. So CensusModulesTest and
MaxConnectionIdleManagerTest are left as-is.
> all: Prefer mock+delegatesTo() over Mockito.spy()

- buildscripts/kokoro/bazel.cfg
- buildscripts/kokoro/bazel.sh
The internal change is cl/181324357
So... this was really easy (granted, completely untested). But it does have the standard problem of Kokoro of being hard to see externally. I think that's likely "okay" right now, and eventually that limitation should go away. Given there aren't even any tests being run, I hope that just the "failure" signal would be enough for most people.
I'm not against adding bazel to Travis, but it seemed to become a bit of a can of worms, as could be seen in #3925. I think we could make it reasonably clean, but I'm not sure it's worth the effort given how simple this solution is.
CC @jyane
> buildscripts: Add Kokoro-based Bazel CI

- COMPILING.md
Added instructions for instructing IntelliJ to use gradle for build/test actions instead of the default IntelliJ compiler.
Helps with https://github.com/grpc/grpc-java/issues/3864
> Added note for IntelliJ building

- netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java
- netty/src/main/java/io/grpc/netty/GrpcHttp2ConnectionHandler.java
- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/main/java/io/grpc/netty/NettyServer.java
- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
- netty/src/main/java/io/grpc/netty/NettyServerTransport.java
- netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
This adds a method on GrpcHttp2ConnectionHandler which, when called, indicates that the channel associated with the handler is no longer needed.   
Notes:
* The handler may not be on the channel, but will either a. need to be added or will never be added.
* The channel will only be "unused" on the server side.
* It is expected that after calling `notifyUnused()`, the channel will be deregistered from the loop without being properly shut down.   This allows the channel to be handed off to a Non-netty API.
> netty: make GrpcHttp2ConnectionHandler able to indicate it will no longer be used

- README.md
- android-interop-testing/build.gradle
- build.gradle
- examples/android/clientcache/build.gradle
- examples/android/helloworld/build.gradle
- examples/android/routeguide/build.gradle
- examples/build.gradle
This fixes support for newer Android Gradle Plugins.
CC @zhangkun83. This is a more complete version of #3597.
> Update protobuf-gradle-plugin to 0.8.3

- core/src/main/java/io/grpc/ManagedChannel.java
These limitations are by design, but may be non-obvious.
CC @dcow
> core: Mention limitations of connectivity state API

- core/BUILD.bazel
- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
- core/src/main/java/io/grpc/internal/DnsNameResolver.java
- core/src/main/java/io/grpc/internal/GrpcAttributes.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
- core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java
I *think* the idle state transitions are correct.  I have looked at them and tried tracing a few paths through.  This doesn't go full idle because the name resolver doesn't need to be restarted.  Also, the LB transition happens inside of a NR callback, so it would be odd to have the NR terminate itself upon successful resolution.  (Might this cause recursion?  I think it may).
> Make ManagedChannel honor Service config LB

- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/test/java/io/grpc/internal/GrpcUtilTest.java
The separator was accidentally removed in 1bbe126b4
> core: add missing separator in user-agent

- core/src/main/java/io/grpc/internal/RetriableStream.java
Based on the comment in #3839, 
> I think it may not be useful/necessary to make this a volatile instead of using a lock. It's not used one we've committed, we likely only have 1-2 streams at a time, the critical section seems quite controlled (doesn't need to call into arbitrary code), and using a volatile is looking complicated/possibly-broken. The first 3 points are different from our other atomic usages here.
it's more reasonable and convenient to return a `Runnable` for `commit()` method because we want to execute part of the commit under a lock and run part of it out of the lock.
> core: retry part I followup, refactor commit()

- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/test/java/io/grpc/internal/GrpcUtilTest.java
The separator was accidentally removed in 1bbe126b4
This is a backport of #3974
> core: add missing separator in user-agent (backport 1.9)

- README.md
We can make this more nuanced (I'd have to test it out, but as far as I remember we work just fine on earlier Android levels if you don't care about TLS) but API level 14 is the minimum required by Google Play Services. Are we okay with setting that as the minimum supported version?
> README.md: include supported Android API levels

- grpclb/BUILD.bazel
add a bazel build definition to grpclb.
I think `src/generated` was created for resolving this issue https://github.com/grpc/grpc-java/issues/357 then I did not add generated files. I just use `java_grpc_library`.
But Bazel requires a full path from WORKSPACE in a proto file (https://github.com/cgrushko/proto_library/blob/04369f0d2ade8c8566727e0b6f3a53f1ba8925c0/src/person.proto#L5) for importing other proto files.
In this PR, it does not relate, but services will require a full path (https://github.com/grpc/grpc-java/compare/master...jyane:add-services-bazel#diff-afc0c0ce1aad649c36404301917e883cR21)
"Do not add generated files" or "Use generated files in Bazel" which is better for now?
> bazel,grpclb: add a bazel build definition

- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/CallTracer.java
- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/OobChannel.java
- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
This class will be reused to count ServerCall stats.
> core: rename io.grpc.internal.ChannelTracer to CallTracer

- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
grpc-java version: 1.8.0
I have encountered NullPointerException.
`Http2Exception.streamError` will raise an exception `new StreamException(id, error, String.format(fmt, args), cause);` but `newStreamException` passes a null value then raises a NullPointerException.
`Http2Exception.streamError` in netty is:
https://github.com/netty/netty/blob/33ddb83dc1e754039540906db50d76f06fa6819b/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2Exception.java#L149
I think `Throwable#getMessage` is generally Nullable, so wrapping null value might be needed.
Is it intentionally? if it is I will close this PR.
Here is stacktrace:
```
java.lang.NullPointerException
at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
at java.util.regex.Matcher.reset(Matcher.java:309)
at …
```
> netty: avoid unintentionally NullPointerException

- core/src/main/java/io/grpc/ForwardingChannelBuilder.java
- core/src/main/java/io/grpc/ManagedChannelBuilder.java
- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/RetriableStream.java
- core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
- core/src/test/java/io/grpc/internal/RetriableStreamTest.java
Implement buffer size counting with `ClientStreamTracer` and buffer size limit following the spce https://github.com/grpc/proposal/blob/master/A6-client-retries.md#memory-management-buffering
> core: retry support part 2, buffer size limit

- core/src/main/java/io/grpc/internal/DnsNameResolver.java
Enabling it makes the GAE interop test consistently fail with this stack trace:
```
io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl onError: [io.grpc.internal.ManagedChannelImpl-5] Failed to resolve name. status=Status{code=UNKNOWN, description=null, cause=java.lang.IllegalStateException: Cannot create new threads after request thread stops. (ManagedChannelImpl.java:1056)
at com.google.apphosting.runtime.ApiProxyImpl$CurrentRequestThread.start(ApiProxyImpl.java:1183)
at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:972)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
at io.grpc.internal.DnsNameResolver.resolve(DnsNameResolver.java:265)
at io.grpc.internal.DnsNameResolver.start(DnsNameResolver.java:156)
at …
```
> core: disable jndi in gae jdk7

- netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
>  netty: only add gRPC negotiator once SSL is established

- core/src/main/java/io/grpc/ExperimentalApi.java
- core/src/main/java/io/grpc/Internal.java
`@Internal` and `@ExperimentalApi` annotations are not visible at compile time of application (not grpc-java) because their retention policies are `SOURCE`.
So, change retention policies to `CLASS`.
According to `javap -v`, grpc-java's annotations are removed at compile time.
I think changing to `CLASS` is necessary for resolving this issue (https://github.com/grpc/grpc-java/issues/3929) because the users will use compiled jar files.
If this(https://github.com/grpc/grpc-java/pull/790#discussion_r36914004) is the only reason, I want to change retention policy to `CLASS`.
> core: change retention policies to CLASS

- core/src/main/java/io/grpc/StreamTracer.java
- core/src/main/java/io/grpc/internal/StatsTraceContext.java
- core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
- core/src/test/java/io/grpc/internal/MessageDeframerTest.java
- core/src/test/java/io/grpc/internal/MessageFramerTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
- testing/src/main/java/io/grpc/internal/testing/TestClientStreamTracer.java
- testing/src/main/java/io/grpc/internal/testing/TestServerStreamTracer.java
- testing/src/main/java/io/grpc/internal/testing/TestStreamTracer.java
They were deprecated in 1.7.0.
Resolves #3460
> core: delete outboundMessage() and inboundMessage() on StreamTracer.

- RELEASING.md
Trying again: https://github.com/grpc/grpc-java/pull/3692 wasn't quite right, so this copies the command from https://github.com/grpc/grpc-java/commit/9c46f92b111c6a1b632024b81ef20653cc237379#diff-60cd2f42437b5cb3c2c09391a6f4c54a to the "Branching the Release" section.
> RELEASING.md: include golden files in branch cut

- SECURITY.md
- okhttp/src/main/java/io/grpc/okhttp/OkHttpProtocolNegotiator.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpProtocolNegotiatorTest.java
- okhttp/third_party/okhttp/java/io/grpc/okhttp/internal/Platform.java
This addresses https://github.com/grpc/grpc-java/issues/3966 and incorporates the text changes to `SECURITY.md` from #3301. Tested with `org.conscrypt:conscrypt-android:1.0.0.RC14`, as well as Google Play's security provider.
This changes our detection of the Google Play security provider from using the class name to the provider name, `GmsCore_OpenSSL`. This would seem to be equally as stable, and recent versions of OkHttp do the [check similarly](https://github.com/square/okhttp/blob/1d9c158a96382facc3be672f6b41dc79fb5eb48b/okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java#L196), although I realized in testing this that OkHttp uses `GMSCore_OpenSSL`, which did not work in my tests (checking elsewhere, it should indeed be `GmsCore_OpenSSL`, and the lookup is …
> okhttp: support Conscrypt security provider

- netty/shaded/build.gradle
This fixes the gradle warning:
The SimpleWorkResult type has been deprecated and is scheduled to be
removed in Gradle 5.0. Please use WorkResults.didWork() instead.
> netty/shaded: Bump shadow plugin version to 2.0.2

- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
This is to notice regressions like in #4016
> netty: Add test to verify error for TLS failure

- netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
This backports #3997 and #4030
> netty: only add gRPC negotiator once SSL is established (1.9 backport)

- core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java
Since this address is never resolved gRPC fails to connect with an
UnresolvedAddressException when the env variable is specified. This
should resolve the address before we attempt to proxy to it.
I know this env variable is scheduled to be removed, so if that's happening in the next version I guess this fix probably isn't necessary.
Also not sure whether there's a good reason why we don't make a DNS lookup here (c.f. comment), but I couldn't find anywhere down the pipeline where this would otherwise get resolved.
> core: Resolve address of GRPC_PROXY_EXP hostname

- buildscripts/kokoro/cronet.sh
This avoids needing to build all of grpc as well as avoids having to
manually track which dependencies are necessary.
This cuts 1.5 minutes off the Cronet build time (to 3.5 minutes). But it
also reduces the amount being downloaded which should help with #3284.
> kokoro: Use --include-build in cronet

- core/src/test/resources/io/grpc/NameResolverProviderTest-multipleProvider.txt
- core/src/test/resources/io/grpc/NameResolverProviderTest-unavailableProvider.txt
These should have been removed in the previous PR.
> core: remove unused test resouce files from NameResolverProviderTest

- core/src/main/java/io/grpc/MethodDescriptor.java
- core/src/main/java/io/grpc/ServiceDescriptor.java
- core/src/test/java/io/grpc/MethodDescriptorTest.java
- core/src/test/java/io/grpc/ServiceDescriptorTest.java
Implements #2472
* Added `MethodDescriptor.toString()` method.
* Added `ServiceDescriptor.toString()` method.
* Upgraded deprecated code in unit tests.
> Add toString for MethodDescriptor and ServiceDescriptor

- core/src/main/java/io/grpc/internal/RetriableStream.java
- core/src/test/java/io/grpc/internal/RetriableStreamTest.java
Implement logic for making retry decision using RetryPolicy.
A lot of old TODOs in tests that depend on backoff implementation are fulfilled.
> core: retry part 5 continued, logic on retry policy

- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/ReportQpsScenarioServiceGrpc.java
- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
- compiler/src/java_plugin/cpp/java_generator.cpp
- compiler/src/test/golden/TestService.java.txt
- compiler/src/testLite/golden/TestService.java.txt
- compiler/src/testNano/golden/TestService.java.txt
- grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
- services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java
- services/src/generated/main/grpc/io/grpc/instrumentation/v1alpha/MonitoringGrpc.java
- services/src/generated/main/grpc/io/grpc/reflection/v1alpha/ServerReflectionGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/AnotherDynamicServiceGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/DynamicServiceGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/ReflectableServiceGrpc.java
- testing-proto/src/generated/main/grpc/io/grpc/testing/protobuf/SimpleServiceGrpc.java
https://github.com/grpc/grpc-java-api-checker/pull/1 (cc @jyane) adds a tool for checking for unintended uses of `@ExperimentalApi` or `@Internal` code via an error prone plugin. Since `@ExperimentalApi` is itself `@Internal`, the `@ExperimentalApi` annotation in the generated code causes the annotation checker to report an error, whenever the generated gRPC service code is not in an `io.grpc` (sub)package.
One option is to `@SuppressWarnings("Internal")`, as done here. An alternative might be to configure the annotation checker to exclude generated code, but that seems more cumbersome - right now we're generating code for the user to compile that includes use of a gRPC `@Internal` API, so just suppressing the warnings related to this seems appropriate.
@carl-mastrangelo What do you …
> compiler: avoid invoking experimental method in generated code

- core/src/main/java/io/grpc/internal/RetriableStream.java
This change is being made in preparation for fixing a bug in the enforcement
of @GuardedBy.
Non-static inner classes can refer to locks declared by their enclosing
instances. Static member types (static classes, interfaces) cannot.
> core: Remove incorrect @GuardedBy annotations

- core/src/main/java/io/grpc/ExperimentalApi.java
- core/src/main/java/io/grpc/Internal.java
Backport of https://github.com/grpc/grpc-java/pull/4051. Backporting so that the grpc-java-api-checker tool can work starting with release 1.10.0
> (backport) core: remove @Internal annotation on @Internal and @ExperimentalApi

- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/BenchmarkServiceGrpc.java
- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/ReportQpsScenarioServiceGrpc.java
- benchmarks/src/generated/main/grpc/io/grpc/benchmarks/proto/WorkerServiceGrpc.java
- compiler/src/java_plugin/cpp/java_generator.cpp
- compiler/src/test/golden/TestService.java.txt
- compiler/src/testLite/golden/TestService.java.txt
- compiler/src/testNano/golden/TestService.java.txt
- grpclb/src/generated/main/grpc/io/grpc/grpclb/LoadBalancerGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/TestServiceGrpc.java
- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
- services/src/generated/main/grpc/io/grpc/health/v1/HealthGrpc.java
- services/src/generated/main/grpc/io/grpc/instrumentation/v1alpha/MonitoringGrpc.java
- services/src/generated/main/grpc/io/grpc/reflection/v1alpha/ServerReflectionGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/AnotherDynamicServiceGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/DynamicServiceGrpc.java
- services/src/generated/test/grpc/io/grpc/reflection/testing/ReflectableServiceGrpc.java
- testing-proto/src/generated/main/grpc/io/grpc/testing/protobuf/SimpleServiceGrpc.java
Backport of https://github.com/grpc/grpc-java/pull/4039. Backporting so that the grpc-java-api-checker tool can work starting with release 1.10.0
> (backport) compiler: avoid invoking experimental method in generated code

- core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java
Since this address is never resolved gRPC fails to connect with an
UnresolvedAddressException when the env variable is specified. This
should resolve the address before we attempt to proxy to it.
This is a backport of #4027
> core: Resolve address of GRPC_PROXY_EXP hostname (1.9 backport)

- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
The previous test was really testing two things at once, let's split
it up:
- checking that user interceptors' `MethodDescriptor`s are unchanged
- checking that the binlog interceptor runs first for incoming events
and runs last for outgoing events
> core: split binlog tests into two in ManagedChannelImplTest

- buildscripts/make_dependencies.bat
Kokoro already has cmake installed, so it's not necessary in that
environment. We still keep the old code around because it's helpful for
setting up new Windows environments in general.
> kokoro: Avoid getting cmake if it's installed

- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
Some users have reported "Channel closed but for unknown reason".
Adding this information doesn't tell us where the bug is, but may help
us narrow down why getShutdownStatus() is null.
> netty: Include more details for closure of unknown reason

- build.gradle
- netty/src/main/java/io/grpc/netty/AbstractHttp2Headers.java
- netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java
- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
- netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java
- repositories.bzl
In newer netty, bootstrap can return a non-null Channel (called a FailedChannel), even if the promise was also a failure.
> netty: upgrade to 4.1.21

- build.gradle
This makes the local mvn case more clear.
> buildscripts: avoid remote repo vars in uploadArchives for local

- examples/android/clientcache/app/build.gradle
- examples/android/helloworld/app/build.gradle
`applicationId` from the gradle file replaces the package value declared in `AndroidManifest.xml` when the apk is built (see https://developer.android.com/studio/build/application-id.html#change_the_package_name), which makes for confusing behavior when the values are not aligned - the package name is important for authorization/credentials with google APIs.
> examples: match applicationId to AndroidManifest.xml package

- SECURITY.md
netty-handler has SslHandler which is really the piece that needs to
agree with netty-tcnative. But as I mention, all of netty should be a
consistent version, otherwise it may randomly break due to internal API
changes.
> SECURITY.md: Mention netty-handler instead of codec-http2

- buildscripts/kokoro/unix.sh
This adds back functionality that was accidentally dropped when
porting from travis:
- make sure generating protos will not lead to any uncomitted changes
- actually run the unit tests
> build: run unit tests on osx, ensure proto output included

- core/src/main/java/io/grpc/internal/BinaryLogProvider.java
- core/src/test/java/io/grpc/internal/BinaryLogProviderTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- services/src/main/java/io/grpc/services/BinaryLog.java
- services/src/main/java/io/grpc/services/BinaryLogSink.java
- services/src/main/java/io/grpc/services/BinaryLogSinkProvider.java
- services/src/test/java/io/grpc/services/BinaryLogTest.java
The `BinaryLog` will write `GrpcLogEntry` objects to the sink.
> services: introduce BinaryLogSinkProvider

- core/src/test/java/io/grpc/ServiceProvidersTestAbstractProvider.java
- services/src/main/java/io/grpc/services/BinaryLogSink.java
- This class should not be a part of the public API
- Update ServiceProvidersTest to verify package private services can be
loaded with the utility.
> core,services: lock down visibility of BinaryLogSink

- core/src/main/java/io/grpc/internal/AbstractStream.java
- core/src/main/java/io/grpc/internal/MessageDeframer.java
- core/src/test/java/io/grpc/internal/MessageDeframerTest.java
This removes the debug string added in 5a4794f2c because the issue was resolved
and the debug string is confusing for Netty, producing results like:
io.grpc.netty.NettyClientTransport$3: Frame size 216695976 exceeds maximum: 4194304
This makes it seem like it's a HTTP/2 frame problem and not a gRPC message
problem. Although it is clearer once you see the maximum is 4 MB, this already
bit me in #4086.
In general, we should talk about "messages" instead of "frames" when possible
as that's what is most comprehensible to the consumer of the description. I
also make sure to mention "gRPC" messages/frames because otherwise the message
is ambiguous.
> core: Improve status descriptions in MessageDeframer

- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
To avoid breakage, temporarily disable retry when stats or tracing is enabled.
This still agrees with the description of the javadoc of `ManagedChannelBuilder.enableRetry()`
```java
/**
* Enables the retry mechanism provided by the gRPC library.
*
* <p>This method may not work as expected for the current release because retry is not fully
* implemented yet.
*
* @return this
* @since 1.11.0
*/
@ExperimentalApi("https://github.com/grpc/grpc-java/issues/3982")
public T enableRetry()
```
> core: temporarily disable retry when stats or tracing is enabled

- java_grpc_library.bzl
These don't contribute if grpc-java is imported with name = grpc_java,
and break the build if grpc-java is imported with another name.
> all: drop @grpc_java from java_grpc_library.bzl

- core/src/test/java/io/grpc/internal/BinaryLogProviderTest.java
- services/src/test/java/io/grpc/services/BinaryLogTest.java
- The unsafe operation was reverted in code, so the test should not
use it either
- The variable naming is tripping internal linters
> core,services: fix binarylog unit tests

- core/src/main/java/io/grpc/internal/ServerCallImpl.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
- core/src/test/java/io/grpc/internal/ServerCallImplTest.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/MoreInProcessTest.java
- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
Signed-off-by: Rama <ramaraochavali@gmail.com>
Fixes https://github.com/grpc/grpc-java/issues/3819, https://github.com/grpc/grpc-java/issues/3746
> core: change serverimpl,servercallimpl's internalclose to cancel stream

- core/src/test/java/io/grpc/internal/FakeClock.java
- core/src/test/java/io/grpc/internal/FakeClockTest.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
In `FakeClock` we have `runDueTasks()` (without filter), `numPendingTasks(filter)`, and `getPendingTasks(filter)` which are useful. The `runDueTasks(filter)` method seems not a right way to test. 
This PR is low priority.
> core: remove runDueTasks with filter

- build.gradle
This allows SSL to work on later JVMs
> all: update to latest alpn agent

- alts/src/main/java/io/grpc/alts/AltsServerBuilder.java
I think `AltsServerBuilder` wraps `NettyServerBuilder` and delegate could be private.
Changing delegate (intended / not intended) would break the builder pattern.
> alts: change visibility of `NettyServerBuilder`

- alts/build.gradle
- alts/src/main/java/io/grpc/alts/AltsChannelBuilder.java
- alts/src/main/java/io/grpc/alts/AltsProtocolNegotiator.java
- alts/src/main/java/io/grpc/alts/InternalTsiFrameHandler.java
- alts/src/test/java/io/grpc/alts/AltsProtocolNegotiatorTest.java
- alts/src/test/java/io/grpc/alts/InternalNettyTsiHandshakerTest.java
- alts/src/test/java/io/grpc/alts/transportsecurity/AltsTsiFrameProtectorTest.java
- alts/src/test/java/io/grpc/alts/transportsecurity/AltsTsiTest.java
- alts/src/test/java/io/grpc/alts/transportsecurity/ChannelCrypterNettyTestBase.java
- alts/src/test/java/io/grpc/alts/transportsecurity/FakeChannelCrypter.java
- alts/src/test/java/io/grpc/alts/transportsecurity/FakeTsiHandshaker.java
- alts/src/test/java/io/grpc/alts/transportsecurity/FakeTsiTest.java
- alts/src/test/java/io/grpc/alts/transportsecurity/TsiTest.java
- interop-testing/build.gradle
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceServer.java
In order to prepare ALTS kokoro interop test, we add '--use_alts' option to test_client and test_server.
> Add ALTS to interop tests

- buildscripts/make_dependencies.bat
```
protobuf. ...
+
```
Fixes #4120
> buildscripts: Hard-code use of TLSv1.2 for github download

- buildscripts/make_dependencies.bat
```
protobuf. ...
+
```
Fixes #4120 
> buildscripts: Hard-code use of TLSv1.2 for github download (v1.10.x backport)

- buildscripts/make_dependencies.bat
```
protobuf. ...
+
```
Fixes #4120
> buildscripts: Hard-code use of TLSv1.2 for github download (v1.9.x backport)

- buildscripts/make_dependencies.bat
```
protobuf. ...
+
```
Fixes #4120
> buildscripts: Hard-code use of TLSv1.2 for github download (v1.8.x backport)

- buildscripts/make_dependencies.bat
```
protobuf. ...
+
```
Fixes #4120
> buildscripts: Hard-code use of TLSv1.2 for github download (v1.7.x backport)

- buildscripts/make_dependencies.bat
```
protobuf. ...
+
```
Fixes #4120
> buildscripts: Hard-code use of TLSv1.2 for github download (v1.6.x backport)

- buildscripts/make_dependencies.bat
```
protobuf. ...
+
```
Fixes #4120
> buildscripts: Hard-code use of TLSv1.2 for github download (v1.5.x backport)

- buildscripts/make_dependencies.bat
```
protobuf. ...
+
```
Fixes #4120
> buildscripts: Hard-code use of TLSv1.2 for github download (v1.4.x backport)

- buildscripts/make_dependencies.bat
```
protobuf. ...
+
```
Fixes #4120
> buildscripts: Hard-code use of TLSv1.2 for github download (v1.3.x backport)

- buildscripts/make_dependencies.bat
```
protobuf. ...
+
```
Fixes #4120
> buildscripts: Hard-code use of TLSv1.2 for github download (v1.2.x backport)

- buildscripts/make_dependencies.bat
```
protobuf. ...
+
```
Fixes #4120
> buildscripts: Hard-code use of TLSv1.2 for github download (v1.1.x backport)

- buildscripts/make_dependencies.bat
```
protobuf. ...
+
```
Fixes #4120
> buildscripts: Hard-code use of TLSv1.2 for github download (v1.0.x backport)

- alts/build.gradle
- alts/src/main/java/io/grpc/alts/InternalTsiFrameHandler.java
- alts/src/main/java/io/grpc/alts/transportsecurity/AltsTsiFrameProtector.java
- alts/src/main/java/io/grpc/alts/transportsecurity/TsiFrameProtector.java
- alts/src/test/java/io/grpc/alts/AltsProtocolNegotiatorTest.java
- alts/src/test/java/io/grpc/alts/InternalNettyTsiHandshakerTest.java
- alts/src/test/java/io/grpc/alts/transportsecurity/TsiTest.java
This doesn't seem that much worse than avoiding Java 8 language features. ~~Is this acceptable, or should I split up the interop-test Blaze target?~~ Discussed elsewhere; this seems good.
> alts: Remove Java 8 library usages

- core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
- core/src/main/java/io/grpc/inprocess/InProcessServer.java
- core/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java
- core/src/main/java/io/grpc/internal/FixedObjectPool.java
- core/src/test/java/io/grpc/inprocess/InProcessChannelBuilderTest.java
- core/src/test/java/io/grpc/inprocess/InProcessServerBuilderTest.java
- core/src/test/java/io/grpc/inprocess/InProcessServerTest.java
- core/src/test/java/io/grpc/inprocess/InProcessTransportTest.java
The is one of a sequence of PRs to allow application to provide all threads. 
This PR added `InProcess{Channel, Server}Builder.scheduledExecutorService()` API
> core: allow application to provide all threads - inprocess channel

- alts/src/main/java/io/grpc/alts/HandshakerServiceChannel.java
- benchmarks/src/test/java/io/grpc/benchmarks/driver/LoadWorkerTest.java
- core/src/main/java/io/grpc/ForwardingChannelBuilder.java
- core/src/main/java/io/grpc/ManagedChannelBuilder.java
- core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
- core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
- interop-testing/src/test/java/io/grpc/testing/integration/CompressionTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/StressTestClientTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/TransportCompressionTest.java
- netty/shaded/src/testShadow/java/io/grpc/netty/shaded/ShadingTest.java
- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpChannelBuilderTest.java
> core,netty,okhttp,alts,inprocess: deprecate usePlaintext(boolean)

- okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpChannelBuilderTest.java
A similar PR to `core: allow application to provide all threads - inprocess channel` #4139
> core: allow application to provide all threads - OkHttp channel

- core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java
Addresses https://github.com/grpc/grpc-java/issues/4154 by using `getHostString()` instead of `getHostName()` when its available, to avoid a potential reverse lookup that can execute on the user's calling thread.
For non-Android users, this will avoid the network I/O for anyone using Java 7+. But for Android, `getHostString()` is only available for Android API levels >= 19 and the fallback to `getHostName()` can still trigger a `NetworkOnMainException`.
@ejona86 From a preliminary look, https://github.com/grpc/grpc-java/pull/4137 will address the root cause of #4154, and will apply to all supported Android API levels. If #4137 makes it in the next release, we probably won't need this PR - unless we want to backport a light-weight fix for #4145 to existing releases.
> core: prefer getHostString() to getHostName() in ProxyDetectorImpl

- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
Some internal tests are broken and noticing the warning logs. They need
to be fixed before this is enabled.
CC @zpencer, @carl-mastrangelo
> core: Disable ManagedChannelImpl orphan check

- core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java
Since this address is never resolved gRPC fails to connect with an
UnresolvedAddressException when the env variable is specified. This
should resolve the address before we attempt to proxy to it.
> core: Resolve address of GRPC_PROXY_EXP hostname (1.10 backport)

- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
Timeouts and Status returns can be common, and previously those cases
weren't that clear. For example, if there was a StatusRuntimeException
it would just print the status code and message, but not the causal
chain.
> interop-testing: Improve failure messages for ping_ping

- core/src/main/java/io/grpc/Internal.java
With the advent of LoadBalancer2 (now just LoadBalancer) the need to use
internal APIs was removed; there's now first-class APIs exposed for
LoadBalancer use.
The old LoadBalancer API interacted with io.grpc.internal.ClientTransport
directly.
> core: Internal is not necessary for LoadBalancers

- core/src/main/java/io/grpc/inprocess/InProcessTransport.java
- core/src/main/java/io/grpc/internal/Channelz.java
- core/src/main/java/io/grpc/internal/ClientTransport.java
- core/src/main/java/io/grpc/internal/DelayedClientTransport.java
- core/src/main/java/io/grpc/internal/FailingClientTransport.java
- core/src/main/java/io/grpc/internal/ForwardingConnectionClientTransport.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/main/java/io/grpc/internal/InternalSubchannel.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
- core/src/main/java/io/grpc/internal/ServerTransport.java
- core/src/test/java/io/grpc/inprocess/InProcessTransportTest.java
- core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
- cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/main/java/io/grpc/netty/NettyServerTransport.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
Transport ststistics should really be a child member of SocketStats.
While we're at it, let's add the local and remote SocketAddress to
SocketStats, with a test.
> core,netty,okhttp,testing: nest TransportStats inside SocketStats for channelz

- core/src/main/java/io/grpc/internal/AbstractServerStream.java
- core/src/main/java/io/grpc/internal/AbstractStream.java
- core/src/main/java/io/grpc/internal/Channelz.java
- core/src/main/java/io/grpc/internal/TransportTracer.java
- netty/src/main/java/io/grpc/netty/NettyClientStream.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
For channelz, clients increment the local counter and servers increment the remote.
> core,netty,okhttp,testing: separate local vs remote stream start time

- buildscripts/kokoro/android.sh
Use parameter expansion<sup>1</sup> to check if the pull request id environment variable is set (otherwise we get an unbound variable error due to `set -u`)
<sup>1</sup> https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
> buildscripts: avoid unbound variable error

- build.gradle
- compiler/build.gradle
- protobuf-lite/build.gradle
Previously if protobuf-generated code triggered ErrorProne we'd have to disable
the failing check for all code in that task. With -XepExcludedPaths we can
disable the ErrorProne-checking just for protobuf. Note that we continue using
ErrorProne on our generated code. Also note this only applies to ErrorProne
checks; JDK checks still require task-level disabling.
> Ignore proto-generated code for ErrorProne

- core/src/main/java/io/grpc/internal/Channelz.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/OobChannel.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
It is a channelz requirement that subchannels and channels are
separate, and we can not retrieve a root channel by asking for a
subchannel and vice versa.
> core: keep root channels separate from subchannels in channelz

- cronet/cronet_deps.sh
- cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
- cronet/src/test/java/io/grpc/cronet/CronetChannelBuilderTest.java
Add APIs to CronetChannelBuilder to set the tag and UID used for Android TrafficStats tagging.
> cronet: Add API to apply TrafficStats tag and UID to Cronet GRPC channels

- core/src/main/java/io/grpc/internal/DelayedClientTransport.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
Currently, `delayedTransport` retains a copy of the last used `SubchannelPicker` even when the channel has moved into idle mode. If this `SubchannelPicker` wraps an error or drop `PickResult`, the next new RPC on the channel will (1) trigger an exit of idle mode but then (2) immediately fail with the cached error status. This PR changes `ManagedChannelImpl` to set the `SubchannelPicker` of `delayedTransport` to null when entering idle mode, so that the first new RPC will be buffered rather than failing immediately.
> core: set delayedTransport picker to null in idle mode

- core/src/main/java/io/grpc/internal/AbstractClientStream.java
- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/ClientStreamListener.java
- core/src/main/java/io/grpc/internal/DelayedStream.java
- core/src/main/java/io/grpc/internal/ForwardingClientStreamListener.java
- core/src/main/java/io/grpc/internal/InternalSubchannel.java
- core/src/main/java/io/grpc/internal/RetriableStream.java
- core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
- core/src/test/java/io/grpc/internal/Http2ClientStreamTransportStateTest.java
- core/src/test/java/io/grpc/internal/NoopClientStreamListener.java
- core/src/test/java/io/grpc/internal/RetriableStreamTest.java
- cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java
- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
- netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientStreamTest.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
Changes:
- `ClientStreamListener.onClose(Status status, RpcProgress rpcProgress, Metadata trailers)` added.
- `AbstractClientStream.transportReportStatus(Status status, RpcProgress rpcProgress, boolean stopDelivery, Metadata trailers)` added
- `ClientCallImpl.ClientStreamListenerImpl` will ignore the arg `rpcProgress` (non retry)
- `RetriableStream.SubListener` will handle `rpcProgress` and decide if transparent retry.
- `NettyClientHandler` and `OkHttpClientTransport` will pass `RpcProgress.REFUSED` to client stream listener for later stream ids when received GOAWAY, or for stream received a RST_STREAM frame with REFUSED code.
- All other files are just a result of refactoring.
> core,netty,okhttp: Transparent retry

- buildscripts/kokoro/windows.bat
- buildscripts/make_dependencies.bat
There's no 'set -e' in BAT, so we get to do it manually. Wee!
Note that we need to use 'exit /b' instead of 'exit' in the scripts, as
otherwise it exits more than just the current script.
CC @matt-kwong
> buildscripts: check errorlevel of error-prone commands in .bat files

- buildscripts/grpc-java-releasing/Dockerfile
- buildscripts/grpc-java-releasing/scl-enable-devtoolset.sh
- buildscripts/kokoro/unix.sh
- buildscripts/run_in_docker.sh
- compiler/Dockerfile
CC @zpencer @zhangkun83 
This removes pre-compiled protoc from the docker image, since there's nothing actually tying the version in the docker image to our source. Similarly it no longer checks out grpc-java as part of the docker image because that checkout is guaranteed to be old.
Then the question is how we want to build within the docker image. You could fire it up like before, and then do a git clone and then go on your way. run_in_docker.sh ~~is a POC that~~ drops you into the docker container with your current grpc-java checkout and as your current user so that you can develop there mostly as normal. I'd imagine the release process would eventually become `./buildscripts/run_in_docker.sh env MVN_ARTIFACTS=1 ./buildscripts/kokoro/unix.sh` which would drop results to mvn-release …
> Cleaner release docker

- build.gradle
The project property can be set form the CLI, so that it is simple to
run JMH on a single class.
> buildscript: read jmh include from project property

- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
Hardcoding 127.0.0.1 leads to failure in ipv6
> testing: temporarily disable socketStats_addresses test

- services/src/main/java/io/grpc/services/BinaryLog.java
- services/src/test/java/io/grpc/services/BinaryLogTest.java
Also added test to cover this case, and renamed test variables
to make it more obvious in the future that the default metadata
is non empty.
> services: fix binary logging empty metadata NPE

- cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
We actually require an `ExperimentalCronetEngine` to create any streams, but our API previously allowed any `CronetEngine` and delayed the cast until an RPC was created. https://github.com/grpc/grpc-java/pull/4208 moved the cast earlier, which broke some internal tests (using mocked CronetEngines) that never actually sent an RPC. We should adjust the API here to require an `ExperimentalCronetEngine` upfront, but this PR restores the delayed cast behavior to fix existing tests, until I have time to update the internal user's test code along with the API change.
cc @JensenPaul
> cronet: delay cast to ExperimentalCronetEngine

- alts/build.gradle
- alts/src/test/java/io/grpc/alts/internal/AesGcmHkdfAeadCrypterTest.java
The previously used javax.xml.bind.DatatypeConverter is deprecated in
Java 9.
> alts: Use Guava base16 decoding functions in tests

- core/src/jmh/java/io/grpc/internal/ChannelzBenchmark.java
- core/src/main/java/io/grpc/internal/Channelz.java
- core/src/main/java/io/grpc/internal/InternalSubchannel.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
- core/src/test/java/io/grpc/internal/ChannelzTest.java
- core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
- services/src/main/java/io/grpc/services/ChannelzProtoUtil.java
- services/src/main/java/io/grpc/services/ChannelzService.java
- services/src/test/java/io/grpc/services/ChannelzProtoUtilTest.java
- services/src/test/java/io/grpc/services/ChannelzServiceTest.java
Rather than querying the ServerImpl for its sockets, we register them
into channelz as with all the other entities, for consistency.
Adjust the server/serversocket registration so that:
* server is added before the first transport
* server is removed after the last transport
Error conditions are checked with `assert` statements, so we throw in
tests. But in prod, an error in channelz should not prevent normal
gRPC operation.
I have tested a branch where we avoid using Long as map keys, and
instead use the LogId as the keys:
https://gist.github.com/zpencer/c04efaaa8b6772a8fa392539c45410ab
Long keys benchmark:
https://gist.github.com/zpencer/a31d470bb46c1205d3110e20fca0050e
LogId keys benchmark:
https://gist.github.com/zpencer/5a5c6c2cea9b12bfe480b7ee5c6ab0e4
We expect servers to have many …
> core,services: track server sockets in channelz

- core/src/main/java/io/grpc/internal/InternalSubchannel.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/OobChannel.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
This way we won't risk an exception making us fail to clean up.
For `transportClosed` only remove if we know this isn't a
duplicate call to close.
> core: perform channelz obj removal before things that may throw

- core/src/main/java/io/grpc/internal/DnsNameResolver.java
JndiResolver.resolve may throw Error that could cause rpc to hang. Catch and log Throwable and keep using jdkResolver's result to prevent it.
> core: catch and log Throwable for jndiResolver.resolve(host)

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
> core: re-enable panic mode after all affected internal tests have been fixed.

- benchmarks/build.gradle
- benchmarks/src/main/java/io/grpc/benchmarks/Utils.java
- benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadClient.java
- benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncClient.java
- benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncServer.java
- benchmarks/src/main/java/io/grpc/benchmarks/qps/ClientConfiguration.java
- benchmarks/src/main/java/io/grpc/benchmarks/qps/OpenLoopClient.java
- benchmarks/src/main/java/io/grpc/benchmarks/qps/ServerConfiguration.java
NIO does not mean to use Jetty ALPN; the only reason to use Jetty ALPN
is to test OkHttp. We don't need to disable ciphers to test Java 7
(except for OkHttp, which we don't care about on Java 7 and it wasn't
plumbed already) and we _really_ don't want people to copy the code to
do so. useTransportSecurity()/usePlaintext() are preferred over the
transport-specific NegotiationType.
Fixes #4223
> benchmarks: Modernize TLS configuration

- build.gradle
-XepFilterPaths should be included in the filtering, otherwise
-PerrorProne=false will fail. I broke this in 1fb72ef6
> build.gradle: Filter -Xep instead of just -Xep:

- build.gradle
-XepFilterPaths should be included in the filtering, otherwise
-PerrorProne=false will fail. I broke this in 1fb72ef6
Backport of #4211
> build.gradle: Filter -Xep instead of just -Xep: (v1.11 backport)

- cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
- cronet/src/test/java/io/grpc/cronet/CronetChannelBuilderTest.java
This is the cronet counterpart of #4139 and #4150.
> cronet: allow application to provide all threads

- core/src/main/java/io/grpc/internal/AbstractClientStream.java
- core/src/main/java/io/grpc/internal/MessageFramer.java
- netty/src/main/java/io/grpc/netty/CancelClientStreamCommand.java
- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/main/java/io/grpc/netty/NettyClientStream.java
- netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
This addresses https://github.com/grpc/grpc-java/issues/4202. I tried to keep the changes minimal, to allow for easily backporting this to earlier releases if necessary.
Currently, if a server half-closes a stream with a Netty client, both server and client will hold onto the stream resources until (if ever) the client calls halfClose(). The same problem does not occur with an OkHttp client, as `OkHttpClientTransport.TransportState#onEndOfStream` triggers deletion of the stream reference on the client and sends a RST_STREAM to the server, which lets the Netty server drop the stream resources as well.
This PR changes the Netty client behavior to be similar to that of OkHttp clients: when end of stream is received from the server, the client sends a RST_STREAM if it has not already …
> core,netty: client sends rst stream when server half-closes

- grpclb/src/main/java/io/grpc/grpclb/CachedSubchannelPool.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancerFactory.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/main/java/io/grpc/grpclb/SubchannelPool.java
- grpclb/src/test/java/io/grpc/grpclb/CachedSubchannelPoolTest.java
- grpclb/src/test/java/io/grpc/grpclb/FakeSocketAddress.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
This is to conform with the GRPCLB spec. The spec doesn't (yet) define
the actual timeout. We choose 10 seconds here arbitrarily.  It may be
configurable in the future.
This will fix internal bug b/74410243
@slash-lib
>  grpclb: Cache Subchannels for 10 seconds after it is removed from the backendlist

- buildscripts/kokoro/windows.bat
- buildscripts/kokoro/windows.cfg
- buildscripts/kokoro/windows32.bat
- buildscripts/kokoro/windows64.bat
- buildscripts/make_dependencies.bat
We always build the artifacts, but only store them in placer via
kokoro if MVN_ARTIFACTS is set to a non empty value.
MVN_ARTIFACTS is not set by default right now.
Click on the windows invocation URL and click placer link to find the artifacts:
https://source.cloud.google.com/results/invocations/8cf374ec-52f8-4e21-ae81-3a957d60953d/details
> buildscripts: build windows artifacts in kokoro

- core/src/main/java/io/grpc/internal/BinaryLogProvider.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/test/java/io/grpc/internal/BinaryLogProviderTest.java
- services/src/main/java/io/grpc/services/BinaryLog.java
- services/src/test/java/io/grpc/services/BinaryLogTest.java
To make unit tests easier, added the BinaryLogSinkWriter abstract
class, which allows verifying high level arguments rather than low
level protobufs.
> core,services: implement binarylog Client and ServerInterceptor

- build.gradle
- core/src/main/java/io/grpc/internal/MoreThrowables.java
- interop-testing/build.gradle
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceServer.java
- interop-testing/src/main/java/io/grpc/testing/integration/Util.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
- netty/build.gradle
- netty/src/main/java/io/grpc/netty/GrpcSslContexts.java
- netty/src/test/java/io/grpc/netty/TlsTest.java
- testing/src/main/java/io/grpc/internal/testing/TestUtils.java
The commits will be kept separate when merging.
~~Since Conscrypt has had some breaking changes, this should probably wait until Conscrypt 1.0 is released to avoid breakage. That implies there will be some changes still to this PR before it is merged, but they can't be done at this time and are relatively small in scope.~~
> Add support for Conscrypt with Netty

- netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
Always set the remote address, no reason why this should be a TLS-only
feature. This is needed for channelz, and is especially useful in unit
tests where we are using plaintext.
> netty,okhttp,testing: always set TRANSPORT_ATTR_REMOTE_ADDR

- gae-interop-testing/gae-jdk7/build.gradle
- gae-interop-testing/gae-jdk8/build.gradle
For some reason this is now required to avoid this exception:
java.lang.ClassNotFoundException: com.google.appengine.api.ThreadManager
> buildscripts: add explicit dependency on appengine SDK

- interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
This allows ProGuard to remove OkHttp's ConnectionSpec in most cases,
saving about 40 methods. The savings won't be realized until
DEFAULT_CONNECTION_SPEC is removed.
> okhttp: Convert to internal ConnectionSpec eagerly

- gae-interop-testing/gae-jdk7/build.gradle
- gae-interop-testing/gae-jdk8/build.gradle
This fixes the following in GAE:
java.lang.ClassNotFoundException: com.google.appengine.api.ThreadManager
>  buildscripts: add explicit dependency on appengine SDK (backport to 1.11)

- gae-interop-testing/gae-jdk7/build.gradle
- gae-interop-testing/gae-jdk8/build.gradle
This fixes the following in GAE:
java.lang.ClassNotFoundException: com.google.appengine.api.ThreadManager
> buildscripts: add explicit dependency on appengine SDK (backport to 1.10)

- build.gradle
- core/build.gradle
- protobuf/build.gradle
- repositories.bzl
- services/build.gradle
Fixes #4176
This is a backport of #4262. Although it seems late to do a change like this for the release,
we've actually done this before in #2528. Also, since this is just a dependency change,
there's really no more testing that we should wait on (we're on HEAD internally, for
instance).
> Bump to Guava 20 (1.11 backport)

- gae-interop-testing/gae-jdk7/build.gradle
- gae-interop-testing/gae-jdk8/build.gradle
This fixes the following in GAE:
java.lang.ClassNotFoundException: com.google.appengine.api.ThreadManager
> buildscripts: add explicit dependency on appengine SDK (backport to 1.9)

- services/src/main/java/io/grpc/services/BinaryLog.java
This fixes a serial warning that breaks the build when building
_without_ ErrorProne. I have no clue why _disabling_ ErrorProne makes
the warning pop up, but whatever, the warning is legit.
I also gave it a name, since the anonymous $1 seems weird if we're
providing a serialVersionUID. Not to say we're actually supporting
serializing this object. But if we ever see a serialized form show up in
the future, having a more clear name would make it obvious what it is.
> services: Specify serialVersionUID for the dummy SocketAddress

- alts/build.gradle
- benchmarks/build.gradle
- build.gradle
- grpclb/build.gradle
- interop-testing/build.gradle
- protobuf-lite/build.gradle
- protobuf-nano/build.gradle
- services/build.gradle
- testing-proto/build.gradle
This update automatically adds generated sources and proto IDLs to the
`idea` plugin, so clean up the configs.
> build.gradle: bump protobuf plugin to 0.8.5

- okhttp/third_party/okhttp/java/io/grpc/okhttp/internal/framed/Hpack.java
Backport of the first commit of #4276. (The subsequent commits in that PR are improvements and test additions that are not needed for 1.11) This fixes #4261.
> okhttp: fix HPACK reader bug (1.11 backport)

- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
> netty: http2 server transport graceful shutdown sends 2 GOAWAYs

- .travis.yml
- benchmarks/build.gradle
- build.gradle
- core/src/test/java/io/grpc/AttributesTest.java
- examples/build.gradle
- grpclb/build.gradle
- interop-testing/build.gradle
- services/build.gradle
- testing-proto/build.gradle
~~Tests still fail; at the very least because of missing Jetty ALPN.~~ I
don't know why the dependency on javax.annotations is unnecessary in the
compiler tests and the example when using Maven.
This depends on #3637. This isn't quite enough for #3633, because we've
not yet clear in our README what's necessary. The annotations stuff is still
very confusing to me; I think our users will suffer unless we have a pretty good
understanding of what's going on and clearly document what they need to do.
> Fix compilation in Java 9

- RELEASING.md
If the release branch (i.e., v1.11.x) was not up-to-date with the local
repo, then the push to update the branch will fail. Doing it first
allows you to notice, merge in the updates and fix the tag before
pushing it.
Also document pulling the most up-to-date version of the release branch
before creating the 'release' branch. That would reduce the amount of
time the release branch could be modified.
> RELEASING.md: Push branch before tag

- core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
Backport of https://github.com/grpc/grpc-java/pull/3789
> core,okhttp: handle unresolved proxy addresses (backport to v1.8.x)

- core/src/main/java/io/grpc/internal/Channelz.java
- core/src/test/java/io/grpc/inprocess/InProcessTransportTest.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/main/java/io/grpc/netty/NettyServerTransport.java
- netty/src/main/java/io/grpc/netty/Utils.java
- netty/src/test/java/io/grpc/netty/UtilsTest.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- okhttp/src/main/java/io/grpc/okhttp/Utils.java
- okhttp/src/test/java/io/grpc/okhttp/UtilsTest.java
- services/src/main/java/io/grpc/services/ChannelzProtoUtil.java
- services/src/test/java/io/grpc/services/ChannelzProtoUtilTest.java
- services/src/test/java/io/grpc/services/ChannelzTestHelper.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
For okhttp, expose the standard options from the Socket object.
For netty, expose all the `io.netty.channel.ChannelOption`s of the
`channel.config()`.
> core,netty,okhttp,services: expose socket options to channelz

- core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java
This makes it easier for a gRPC developer to validate the proxy code
using a real proxy.
> core: document how to set up squid proxy for testing

- gae-interop-testing/gae-jdk8/src/main/java/io/grpc/testing/integration/LongLivedChannel.java
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
OkHttpClientInteropServlet and NettyClientInteropServlet both run the
`@After` method from AbstractInteropTest. Let's make sure we await
termination.
For the long lived channel test, do the cleanup in `destroy`.
> GAE: call channel.shutdown()

- okhttp/src/main/java/io/grpc/okhttp/OkHttpTlsUpgrader.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpTlsUpgraderTest.java
Address mismatch between IPv6 address hosts derived from URIs and X509 subjectAltName extensions as discussed in #4278
> okhttp: properly verify IPv6 address hosts

- core/src/test/java/io/grpc/internal/ReadableBuffersTest.java
Address #4198, part 1. Just adding tests for `ReadableBuffers`.
> core: add tests for ReadableBuffers

- buildscripts/kokoro/bazel.sh
- java_grpc_library.bzl
They were removed in 137c74d1 since it was believed they were unnecessary.
However, since they are in a macro and not a rule, they are relative to the
caller, not their definition.
Added building the examples to the kokoro CI. Note that this means the examples
are built twice: once in grpc-java's build and once in their own (because it
has a WORKSPACE). Given that the Bazel build is our fastest build, this
slowdown won't probably be an issue.
CC @cgrushko
> java_grpc_library: re-add grpc-java repo to targets

- SECURITY.md
Many people going to the troubleshooting section would be fixed by
swapping to grpc-netty-shaded, so we should call that out.
@saturnism, would you mind reviewing?
> SECURITY.md: Add reference to grpc-netty-shaded

- protobuf/src/main/java/io/grpc/protobuf/StatusProto.java
It was added in 1e9bd9a8 which was initially released in v1.11.0.
> protobuf: fix @since for fromStatusAndTrailers

- core/src/main/java/io/grpc/inprocess/InProcessServer.java
- core/src/main/java/io/grpc/internal/Channelz.java
- core/src/main/java/io/grpc/internal/InternalServer.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/main/java/io/grpc/netty/NettyServer.java
- netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
- netty/src/main/java/io/grpc/netty/NettyServerTransport.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
- netty/src/test/java/io/grpc/netty/NettyServerTest.java
- services/src/main/java/io/grpc/services/ChannelzProtoUtil.java
- services/src/test/java/io/grpc/services/ChannelzProtoUtilTest.java
- services/src/test/java/io/grpc/services/ChannelzTestHelper.java
This PR exposes listen sockets to the channelz service.
These sockets are not in the set of sockets discoverable via
`GetServerSockets`.
Server listen sockets differ from normal sockets in that only have
a local address and socket options.
Fixed an issue of socket addresses not reporting the port.
> core,netty,services: add server listen sockets to channelz proto service

- core/src/main/java/io/grpc/internal/ReadableBuffers.java
- core/src/test/java/io/grpc/internal/ReadableBuffersTest.java
Before:
`InputBufferStream.close()` does not close their buffer so the buffer will leak.
After:
Resolves #4198.
Override the `close` for closing their buffer.
> core: add a `close` to InputBufferStream

- README.md
due to https://github.com/xolstice/protobuf-maven-plugin/issues/30, out of the box user experience on windows for compiling protobufs was often suboptimal, needing to retry several times before the compilation succeeded. We have not seen the error since upgrading to the latest version.
> upgrade protobuf-maven-plugin

- netty/src/main/java/io/grpc/netty/NettyServer.java
- services/src/test/java/io/grpc/services/ChannelzTestHelper.java
Fix linter complaint because comment does not match arg name.
> netty,services: fix param comment lint

- netty/src/main/java/io/grpc/netty/NettyServer.java
Fix race by avoiding async handler. This was leading to a flakey test:
channelzListenSocket
> netty: fix getListenSockets race

- core/src/main/java/io/grpc/internal/Channelz.java
- netty/src/main/java/io/grpc/netty/NettySocketSupport.java
- netty/src/main/java/io/grpc/netty/Utils.java
- services/src/main/java/io/grpc/services/ChannelzProtoUtil.java
- services/src/test/java/io/grpc/services/ChannelzProtoUtilTest.java
NettySocketSupport is responsible for making the low level calls to
get and populate the TcpInfo structure.
> core,netty: add NettySocketSupport to populate TcpInfo

- examples/pom.xml
This was missed in 2094bb4d8
CC @jorgheymans, oops, we missed this in review.
> examples: upgrade protobuf-maven-plugin to 0.5.1

- compiler/src/java_plugin/cpp/java_generator.cpp
- compiler/src/test/golden/TestService.java.txt
- compiler/src/test/proto/test.proto
- compiler/src/testLite/golden/TestService.java.txt
- compiler/src/testNano/golden/TestService.java.txt
previously `Import` fails because it gets turned into a method named
`import`. This PR makes the method be named `import_`, everything else
stays the same, such as the name in the method descriptor.
Note: `iMport` or `iMPORT` or any variation of capitalizations that is
not `Import` always worked. `Import` gets translated into `import`
because of our attempts to camel case the names.
fixes https://github.com/grpc/grpc-java/issues/2195
> compiler: allow capitalized java keywords as rpc names

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
Without using a final local variable, cancelling a task can make the
runnable become null when it's executed.
Fixes https://github.com/grpc/grpc-java/issues/4077
> core: idle mode timer runnable should never be null

- build.gradle
Old branches fail to build unless we take this change.
> all: update to latest alpn agent (backport to v1.10.x)

- build.gradle
Old branches fail to build unless we take this change.
> all: update to latest alpn agent (backport to v1.9.x)

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
Without using a final local variable, cancelling a task can make the
runnable become null when it's executed.
> core: idle mode timer runnable should never be null (#4315) (backport to v1.10.x)

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
Without using a final local variable, cancelling a task can make the
runnable become null when it's executed.
> core: idle mode timer runnable should never be null (#4315) (backport to v1.9.x)

- core/src/main/java/io/grpc/internal/AbstractServerStream.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
Previously StreamTracer.streamClosed() is called in
ServerStream.close(), but it is not exactly when the stream is
officially closed.  ServerStreamListener.closed() is guaranteed to be
called and it is the official end of the stream.
> core: always call StreamTracer.streamClosed() when stream is officially closed

- core/src/main/java/io/grpc/internal/RetryPolicy.java
This reverts one line in 0a598c0
Always not compare equality for doubles with `==`.
> core: compare doubles with compare instead of ==

- services/src/main/java/io/grpc/services/ChannelzService.java
Right now this is inaccessible to services.
> services: make channelz constructor static

- core/src/main/java/io/grpc/internal/Channelz.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
- services/src/main/java/io/grpc/services/ChannelzProtoUtil.java
- services/src/test/java/io/grpc/services/ChannelzProtoUtilTest.java
- services/src/test/java/io/grpc/services/ChannelzTestHelper.java
This fixes listen sockets. It is ok to have no data but report socket
options.
> services: socket options were erroneously ignored if socket has no stats

- core/src/main/java/io/grpc/inprocess/InProcessTransport.java
- services/src/main/java/io/grpc/services/ChannelzProtoUtil.java
Then channelz GUI will take this into account. This is particularly
useful for InProcessTransport, where I have decided we do not need
special support for in channelz. The server and channel stats are
already sufficient.
Fixes https://github.com/grpc/grpc-java/issues/4344
> services: turn channelz null futures into Status.UNIMPLEMENTED

- core/src/main/java/io/grpc/internal/JsonParser.java
Needed for other internal name resolvers to encode parse json
> core: make JsonParser public

- core/src/main/java/io/grpc/ForwardingChannelBuilder.java
- core/src/main/java/io/grpc/PartialForwardingClientCall.java
- core/src/main/java/io/grpc/PartialForwardingClientCallListener.java
- core/src/main/java/io/grpc/PartialForwardingServerCall.java
- core/src/main/java/io/grpc/PartialForwardingServerCallListener.java
- core/src/main/java/io/grpc/internal/ForwardingClientStream.java
- core/src/main/java/io/grpc/internal/ForwardingClientStreamListener.java
- core/src/main/java/io/grpc/internal/ForwardingConnectionClientTransport.java
- core/src/main/java/io/grpc/internal/ForwardingManagedChannel.java
- core/src/main/java/io/grpc/internal/ForwardingNameResolver.java
- core/src/main/java/io/grpc/internal/ForwardingReadableBuffer.java
- core/src/test/java/io/grpc/ForwardingTestUtil.java
Forward `toString()` method for forwarding classes to improve debug information.
For example, `ForwardingManagedChannel.toString()` will return something like:
```
ForwardingManagedChannel{delegate=ManagedChannelImpl{logId=tag-13247, target=localhost:8080}}
```
> core: forward toString for forwarding classes

- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
In current code of `ManagedChannelImplTest`, new tests will have to add more and more custom args in `createChannel(...)`, and each time when a custom arg is needed all other default args need be repeatedly provided in `createChannel(...)`. In most cases those args are just builder attributes. So this PR makes ManagedChannelImplTest easier to stub by providing a builder field, then new tests will just set necessary builder attributes before calling `createChannel()`.
> core: refactor ManagedChannelImplTest with a configurable builder

- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
Replace the tests with tests that just make sure binary log is
installed. Better tests exist today in BinaryLogProviderTest to make
sure the actual logic is correct.
> core: remove unneeded binlog tests for ManagedChannelImpl ServerImpl

- core/src/main/java/io/grpc/internal/BinaryLogProvider.java
The interceptors are a part of the implementation and not meant for
callers.
> core: clarify binlog API

- services/src/main/java/io/grpc/services/BinaryLog.java
- services/src/main/java/io/grpc/services/BinaryLogProviderImpl.java
The code that uses this will create an instance, namely the actual Impl of the BinaryLogProvider.
> services: avoid static initialization for BinaryLog.java

- buildscripts/kokoro/android.sh
Since 4369e8cd the --include-build just opens us up to trouble with
accidentally building the protoc plugin. Since we're going to do a
./gradlew install anyway, let's just wait until after that point for
building cronet.
This sort of problem was experienced while developing #4369.
> kokoro: Avoid --include-build for Android

- buildscripts/sonatype-upload.sh
Set $CONF before we use it.
Also enable some defensive bash flags to catch errors.
> buildscripts: sonatype uploader ussing CONF before it is set

- buildscripts/kokoro/release_artifacts.cfg
- buildscripts/kokoro/release_artifacts.sh
The script does nothing at the moment other than set up the kokoro
job.
> buildscripts: initial kokoro config for auto releasing artifacts

- services/src/test/java/io/grpc/services/ChannelzProtoUtilTest.java
- services/src/test/java/io/grpc/services/ChannelzTestHelper.java
- final classes should have toString()
- fix arg name mismatch
> services: fix channelz linter warnings

- core/BUILD.bazel
- java_grpc_library.bzl
- repositories.bzl
- stub/BUILD.bazel
Fixes: #3633.
Test Plan:
On most recent Bazel version run:
```
$ bazel --host_javabase=/usr/lib64/jvm/java-9-openjdk \
build --javacopt='--release 9' \
--java_toolchain=@bazel_tools//tools/jdk:toolchain_jdk9 \
examples:helloworld_java_grpc
```
> Bazel: Fix compilation in Java 9

- .travis.yml
- buildscripts/kokoro/android.sh
- buildscripts/kokoro/unix.sh
- buildscripts/make_dependencies.sh
ARCH can be '32' or '64'. If it is not set then default to '64'.
Update intermediate and final artifact output dirs to include ARCH so
that runs do not clobber each other.
The linux release job will invoke unix.sh with `ARCH=32` and again
with `ARCH=64`.
`buildscripts/make_dependencies.sh` will be responsible for building
and making sure /tmp/protobuf/ is symlinked to the right arch.
> buildscripts: make unix.sh and make_dependencies.sh arch aware

- core/src/main/java/io/grpc/ManagedChannelBuilder.java
- core/src/main/java/io/grpc/ServerBuilder.java
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceServer.java
- interop-testing/src/test/java/io/grpc/testing/integration/AutoWindowSizingOnTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyLocalChannelTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/TransportCompressionTest.java
- netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
On server side, `maxMessageSize` is deprecated for
`maxInboundMessageSize` to match the channel builder.
Update usages to use new setter.
fixes https://github.com/grpc/grpc-java/issues/2563
> (low priority) core,netty,interop-testing: stabilize maxInboundMessageSize API

- testing/build.gradle
- testing/src/main/java/io/grpc/testing/GrpcCleanupRule.java
- testing/src/test/java/io/grpc/testing/GrpcCleanupRuleTest.java
Added `GrpcCleanupRule` based on offline discussions with @ejona86 
This will ease a lot of test scenarios that we want to automatically shut down servers and channels, with much more flexibility such as that mentioned by #3624 than `GrpcServerRule`.
**ManagedChannel/Server cleanup details:**
- If the test has already failed, call `shutdownNow()` for each of the resources registered.
- If no error happens up to now, call `shutdown()` for each of the resources registered. If any error occurs, immediately call `shutdownNow()` for each resource.
- If no error happens up to now, call `awaitTermination()` with `timeout = deadline - current time` and assert termination for each resource.  If any error occurs, immediately call `shutdownNow()` for the current resource and all the rest resources. …
>  testing: GrpcCleanupRule

- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- stub/src/main/java/io/grpc/stub/ClientCalls.java
Improves debugging experience with ClientCall instances.
Sent on behalf of @charlesmunger
> core,stub: Add toString() to ClientCallImpl and GrpcFuture

- services/src/main/java/io/grpc/services/BinaryLogProviderImpl.java
This class is not stable API.
This is a backport of #4420
> services: BinaryLogProviderImpl is experimental (v1.12 backport)

- core/BUILD.bazel
- core/src/main/java/io/grpc/inprocess/InProcessTransport.java
- core/src/main/java/io/grpc/internal/AbstractClientStream.java
- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/ClientStream.java
- core/src/main/java/io/grpc/internal/DelayedStream.java
- core/src/main/java/io/grpc/internal/ForwardingClientStream.java
- core/src/main/java/io/grpc/internal/NoopClientStream.java
- core/src/main/java/io/grpc/internal/RetriableStream.java
- core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
- core/src/test/java/io/grpc/internal/ForwardingClientStreamTest.java
Added `ClientStream.setDeadline(Deadline deadline)` method, which will set the timeout header.
Resolving #4412
> core: populate effective deadline to ClientStream

- core/src/main/java/io/grpc/CallOptions.java
The handful of Google internal targets that violated this check have already been cleaned up. It looks like since @carl-mastrangelo first attempted this change, the errorprone tooling has improved such that this is no longer flagging false-positives, like unit tests.
Fixes #3671
> core: Adds @CheckReturnValue to CallOptions

- core/src/main/java/io/grpc/ClientCall.java
- core/src/main/java/io/grpc/ServerCall.java
- core/src/main/java/io/grpc/ServerCallHandler.java
This was already clearly documented in ServerCall.Listener and
ClientCall.
> core: Document Metadata ownership passes to the Call{,Listener}

- android/build.gradle
- android/settings.gradle
This enables building the `grpc-android` .aar artifact. Conscrypt's conscrypt-android [build.gradle](https://github.com/google/conscrypt/blob/0b798b404f9072af38ca6268b2a3d0cf304481cd/android/build.gradle) was a useful reference.
Conscrypt includes conscrypt-android as a subproject of their root build, but this PR leaves the grpc-android artifact as a separate build instead. There are two reasons for this: (1) the plugins to build and deploy Android are different, so Conscrypt duplicated the deploy config anyways and (2) with the latest versions of gradle and the android gradle plugin, mixing java and android builds introduces classpath guava conflicts that break gradle (not the build, breaks the gradle tool itself). Resolving these issues and integrating grpc-android as a subproject of …
> android: add artifact build

- buildscripts/build_artifacts_in_docker.sh
- buildscripts/grpc-java-releasing/Dockerfile
- buildscripts/kokoro/linux_artifacts.sh
- buildscripts/kokoro/unix.sh
- buildscripts/kokoro/upload_artifacts.cfg
- buildscripts/kokoro/upload_artifacts.sh
- buildscripts/kokoro/windows.bat
- buildscripts/kokoro/windows32.bat
- buildscripts/kokoro/windows64.bat
- buildscripts/run_in_docker.sh
This introduces the scripts for the auto release process.
In kokoro, there will be a job `release_artifacts` that the team
can trigger manually with an RPC, it does not run automatically.
The job will kick off 3 other jobs:
- macos: builds protoc-gen-grpc-java-1.13.0-osx-x86_64.exe
- windows: builds protoc-gen-grpc-java-1.13.0-windows-x86_32.exe and
protoc-gen-grpc-java-1.13.0-windows-x86_64.exe
- linux_artifacts: builds protoc-gen-grpc-java-1.13.0-linux-x86_32.exe,
protoc-gen-grpc-java-1.13.0-linux-x86_64.exe, and the jars
If all 3 jobs are successful then a child job `upload_artifacts` is
triggered. This job downloads all the artifacts, signs the files, then
uploads them to oss.sonatype.org in a staging repo.
> buildscripts: automate the release process

- stub/src/main/java/io/grpc/stub/AbstractStub.java
No internal google targets were broken by this change.
Fixes #3985
> stub: Add @CheckReturnValue to AbstractStub

- buildscripts/kokoro/upload_artifacts.sh
The `find` was unnecessary. Update the sanity check to reflect this
assumption.
> buildscripts: assume artifacts are coalesced in upload_artifacts

- core/src/main/java/io/grpc/inprocess/InProcessTransport.java
- core/src/main/java/io/grpc/internal/InternalSubchannel.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/OobChannel.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/main/java/io/grpc/netty/NettyServer.java
- netty/src/main/java/io/grpc/netty/NettyServerTransport.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
Use MoreObjects.toStringHelper and use only the log id's long value,
because the class name is already present in the toStringHelper.
> core,netty,okhttp: make toString more consistent for channelz

- buildscripts/kokoro/upload_artifacts.sh
The `find` was unnecessary. Update the sanity check to reflect this
assumption.
> buildscripts: assume artifacts are coalesced in upload_artifacts (#4439) (backport to v1.12.x)

- buildscripts/kokoro/upload_artifacts.sh
Just a very basic sanity check that the android artifact is not missing.
> buildscripts: add basic sanity check for android aar

- RELEASING.md
The steps are still valid, and should be considered the source of
truth. However, these steps have been automated as a kokoro job. Add a
link to the documentation for the kokoro job.
> RELEASING.md: add links to auto release documentation

- SECURITY.md
Master currently is for grpc >= 0.11 so it doesn't make sense that the SECURITY.md instructs to use the 2.0.6 (which triggers an error) - see https://github.com/grpc/grpc-java/issues/3989
> updated dependency from 2.0.6 to 2.0.7 in security documentation

- alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java
- core/src/jmh/java/io/grpc/AttributesBenchmark.java
- core/src/main/java/io/grpc/Attributes.java
- core/src/main/java/io/grpc/CallCredentials.java
- core/src/main/java/io/grpc/Grpc.java
- core/src/main/java/io/grpc/NameResolver.java
- core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
- core/src/main/java/io/grpc/internal/GrpcAttributes.java
- core/src/main/java/io/grpc/internal/ProxyDetector.java
- core/src/main/java/io/grpc/util/RoundRobinLoadBalancerFactory.java
- core/src/test/java/io/grpc/AttributesTest.java
- core/src/test/java/io/grpc/PickFirstLoadBalancerTest.java
- core/src/test/java/io/grpc/internal/CallCredentialsApplyingTest.java
- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
- core/src/test/java/io/grpc/internal/DelayedStreamTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
- core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbConstants.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/CachedSubchannelPoolTest.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
Deprecate static builder method, Keys.of(), add a notice of plans to
deprecate keys(), emphasize that the name is only a debug label.
Related: https://github.com/grpc/grpc-java/issues/1764
> core: stabilize Attributes API

- buildscripts/kokoro/bazel.sh
- java_grpc_library.bzl
They were removed in 137c74d1 since it was believed they were unnecessary.
However, since they are in a macro and not a rule, they are relative to the
caller, not their definition.
Added building the examples to the kokoro CI. Note that this means the examples
are built twice: once in grpc-java's build and once in their own (because it
has a WORKSPACE). Given that the Bazel build is our fastest build, this
slowdown won't probably be an issue.
CC @carl-mastrangelo 
This is a backport of #4288
> java_grpc_library: re-add grpc-java repo to targets (1.11 backport)

- core/src/jmh/java/io/grpc/CallOptionsBenchmark.java
- core/src/main/java/io/grpc/BinaryLogProvider.java
- core/src/main/java/io/grpc/CallOptions.java
- core/src/main/java/io/grpc/internal/ServiceConfigInterceptor.java
- core/src/test/java/io/grpc/CallOptionsTest.java
- core/src/test/java/io/grpc/ClientInterceptorsTest.java
- core/src/test/java/io/grpc/internal/CensusModulesTest.java
- core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java
Deprecate `of()` in favor of `create()` and
`createWithDefault()`. Emphasize that the name string is only for
debug purposes.
Fixes #1869
> core: stabilize custom CallOptions API

- core/src/main/java/io/grpc/internal/Channelz.java
- services/src/main/java/io/grpc/services/ChannelzProtoUtil.java
- services/src/test/java/io/grpc/services/ChannelzProtoUtilTest.java
- services/src/test/java/io/grpc/services/ChannelzTestHelper.java
Added `ChannelTrace` as an inner class of `Channelz`.
This is in preparation for the implementation of [Channel Tracing](https://github.com/grpc/proposal/blob/master/A3-channel-tracing.md)
> core,services: Add ChannelTracing data object

- context/src/main/java/io/grpc/Context.java
- context/src/test/java/io/grpc/ContextTest.java
- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-java/4430)
> context/core/netty: Add @CheckReturnValue to Context

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
Moved `setState()` inside of `channelExecutor` runnable together with `setSubchannels`, otherwise the state may be inconsistent with subchannels, say channel state is the initial IDLE but subchannels is non-empty with active transports, or channel state is READY but subchannels is empty.
> core: make channel stats' channel state consistent with subchannels

- core/src/main/java/io/grpc/CallOptions.java
This marks the method as still experimental, to be clear to users that
they are using an experimental api.
This is a follow up for:
https://github.com/grpc/grpc-java/pull/4457#pullrequestreview-120393893
> core: put @ExperimentalApi on CallOptions.of()

- core/src/main/java/io/grpc/internal/ChannelTracer.java
- core/src/test/java/io/grpc/internal/ChannelTracerTest.java
This is a class similar to CallTracer, to be used for Channel Tracing.
The constructor arg `maxEvents` is a param supposed to be provided by `ManagedChannelBuilder`.
> core: Add ChannelTracer

- services/src/main/java/io/grpc/services/ChannelzProtoUtil.java
- services/src/test/java/io/grpc/services/ChannelzProtoUtilTest.java
These are subtley differently named but distinct fields.
> services: differentiate between tcpi_retransmits and tcpi_retrans

- netty/src/main/java/io/grpc/netty/GrpcHttp2ConnectionHandler.java
This fixes the warning:
`Tag @link: reference not found: Channelz.Security`
Javadoc `@link` is simplistic in its processing of '.' and thinks if a
dot exists it means it is part of the package name. You're forced to use
the full name of nested classes.
> netty: Fix Javadoc reference to Channelz.Security

- android/build.gradle
- build.gradle
- compiler/build.gradle
- examples/android/clientcache/gradle/wrapper/gradle-wrapper.properties
- examples/android/helloworld/gradle/wrapper/gradle-wrapper.properties
- examples/android/routeguide/gradle/wrapper/gradle-wrapper.properties
- examples/example-kotlin/android/helloworld/gradle/wrapper/gradle-wrapper.properties
- examples/example-kotlin/gradle/wrapper/gradle-wrapper.properties
- examples/gradle/wrapper/gradle-wrapper.properties
- gae-interop-testing/gae-jdk7/build.gradle
- gae-interop-testing/gae-jdk8/build.gradle
- gradle/wrapper/gradle-wrapper.properties
The new jmh plugin fixes a warning for the newer version of Gradle.
The new AppEngine plugin still produces a warning, but updating it
anyway so people know that upgrading the plugin doesn't fix the problem.
The Visual Studio fixes were necessary starting ~4.4.
https://github.com/gradle/gradle-native/issues/34#issuecomment-335222096
describes the change in behavior.
There's nothing immediately being used as part of this update. It's just
to keep us current and to get us over that Visual Studio change hump.
> Bump to Gradle 4.7

- examples/build.gradle
- examples/pom.xml
- examples/src/main/java/io/grpc/examples/advanced/HelloJsonClient.java
- examples/src/main/java/io/grpc/examples/advanced/JsonMarshaller.java
- grpclb/build.gradle
- protobuf/build.gradle
- protobuf/src/main/java/io/grpc/protobuf/ProtoUtils.java
- protobuf/src/test/java/io/grpc/protobuf/ProtoUtilsTest.java
- services/build.gradle
Also, move some of proto-utils usage for things like durations, timestamp, and any
fixes #1786
> protobuf,examples: move json encoding to examples

- core/BUILD.bazel
- core/src/main/java/io/grpc/BinaryLogProvider.java
- core/src/main/java/io/grpc/internal/CensusTracingModule.java
- core/src/test/java/io/grpc/internal/CensusModulesTest.java
- services/src/main/java/io/grpc/services/CensusBinaryLogProvider.java
io.grpc (core) does not strictly require census. Move the usages and
and remove census from BUILD.bazel .
> core: remove io.grpc core dependency on census

- core/src/main/java/io/grpc/internal/CallTracer.java
- core/src/main/java/io/grpc/internal/Channelz.java
- core/src/main/java/io/grpc/internal/TimeProvider.java
- core/src/main/java/io/grpc/internal/TransportTracer.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- core/src/test/java/io/grpc/internal/ServerCallImplTest.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbClientLoadRecorder.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancerFactory.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
- netty/src/test/java/io/grpc/netty/NettyTransportTest.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpTransportTest.java
- services/src/main/java/io/grpc/services/ChannelzProtoUtil.java
- services/src/test/java/io/grpc/services/ChannelzProtoUtilTest.java
- services/src/test/java/io/grpc/services/ChannelzTestHelper.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
This is the same practice as #2833
More PRs switching to nanos may come after.
> all: TimeProvider to use nanos rather than millis more consistently

- services/src/main/java/io/grpc/services/BinlogHelper.java
- services/src/main/java/io/grpc/services/InetAddressUtil.java
- services/src/test/java/io/grpc/services/BinlogHelperTest.java
`peer` is deprecated in favor of `address` and `ip_port`.
> services: use Peer.address proto

- core/src/main/java/io/grpc/InternalClientInterceptors.java
- core/src/main/java/io/grpc/InternalServerInterceptors.java
- core/src/main/java/io/grpc/internal/CensusTracingModule.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/CensusModulesTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
- services/src/main/java/io/grpc/services/BinaryLogProvider.java
- services/src/main/java/io/grpc/services/BinaryLogProviderImpl.java
- services/src/main/java/io/grpc/services/BinlogHelper.java
- services/src/main/java/io/grpc/services/CensusBinaryLogProvider.java
- services/src/test/java/io/grpc/services/BinaryLogProviderTest.java
- services/src/test/java/io/grpc/services/BinlogHelperTest.java
- services/src/test/java/io/grpc/services/CensusBinaryLogProviderTest.java
BinaryLogProvider is purely an implementation of io.grpc.BinaryLog and can exist in services.
Add internal accessors for ServerInterceptors and ClientInterceptors because some helpers are pkg private
Fix tests that were once creating BinaryLogProvider instances, they should now only create io.grpc.BinaryLog instances
> move io.grpc.BinaryLogProvider to io.grpc.services

- core/src/main/java/io/grpc/ForwardingChannelBuilder.java
- core/src/main/java/io/grpc/ManagedChannelBuilder.java
- core/src/main/java/io/grpc/ServerBuilder.java
- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
- services/src/main/java/io/grpc/services/BinaryLogProviderImpl.java
- services/src/main/java/io/grpc/services/BinaryLogSink.java
- services/src/main/java/io/grpc/services/BinaryLogs.java
- services/src/main/java/io/grpc/services/CensusBinaryLogProvider.java
The BinaryLogSink needs to be extendable.
The io.grpc.BinaryLog needs to be settable for a channel or server.
> services,core: make BinaryLogSink visible, add setter

- auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
- auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java
- core/src/main/java/io/grpc/inprocess/InProcessTransport.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
This keeps them more secure. Other types of creds are left as-is, since
we don't quite know if it makes sense to have a similar restriction. (It
likely does make sense, but this is a more precise change for our
needs.)
I will keep the two separate commits when merging. Each commit has a commit message, although the two commits are pretty disjoint, so it's not a big deal to review it all at once.
>  auth: Require PRIVACY_AND_INTEGRITY for GoogleCredentials

- core/src/main/java/io/grpc/InternalClientInterceptors.java
- core/src/main/java/io/grpc/InternalServerInterceptors.java
- services/src/test/java/io/grpc/services/BinaryLogProviderTest.java
- Type parameters must be upper camel case
- constant case field must be final
> core,services: fix lints

- buildscripts/kokoro/android.sh
Use the full path to the Android helloworld app APK, as otherwise it's easy to accidentally collect stats for the wrong example app.
cc @zpencer
> buildscripts: fix Android apk/dex comparison

- auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
- auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java
This reverts commit 8e9d4cbe5cb455315e55846e91706cccecb4b577.
Reason: breaks internal products that use a custom Channel that doesn't set security level properly.
> Revert "auth: Require PRIVACY_AND_INTEGRITY for GoogleCredentials"

- services/src/main/java/io/grpc/services/BinlogHelper.java
- services/src/test/java/io/grpc/services/BinlogHelperTest.java
The truncation flag tells us whether the msg or meta was truncated.
>  services: update the binlog message truncation flag

- services/src/main/java/io/grpc/services/BinlogHelper.java
- services/src/test/java/io/grpc/services/BinlogHelperTest.java
The spec says users can specify a blacklist a method from binlogs by
saying "-package.service/method".
> services: allow binlog to blacklist methods

- benchmarks/src/jmh/java/io/grpc/benchmarks/TransportBenchmark.java
- interop-testing/src/main/java/io/grpc/testing/integration/ReconnectTestClient.java
- okhttp/src/main/java/io/grpc/okhttp/NegotiationType.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpChannelBuilderTest.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpTransportTest.java
The functionality provided by `#negotiationType` is identical to just directly invoking `#usePlaintext`/`#useTransportSecurity`. 
Removing the `#negotiationType` method (which isn't part of `ManagedChannelBuilder`) will make it cleaner to use `OkHttpChannelBuilder` as the delegate builder for a `ForwardingChannelBuilder` (specifically, this helps  AndroidChannelBuilder, which loads OkHttp via reflection and so doesn't have easy access to the `#negotiationType` method's `io.grpc.okhttp.NegotiationType` parameter)
> okhttp: deprecate OkHttpChannelBuilder#negotiationType

- buildscripts/kokoro/android.sh
#4511 only fixed the dex count comparison. This updates the full dex diff and apk size comparison
> buildscripts: correct Android apk size and dex diff output

- android/src/main/java/io/grpc/android/AndroidChannelBuilder.java
- android/src/test/java/io/grpc/android/AndroidChannelBuilderTest.java
This PR adds forwarding method for `OkHttpChannelBuilder` specific methods such as `#transportExecutor`. It only omits a forwarding method for `OkHttpChannelBuilder#connectionSpec(com.squareup.okhttp.ConnectionSpec)`, as this method is little-used and its parameter type is awkward to deal with reflectively.
> android: forward OkHttpChannelBuilder-specific methods to delegate

- services/src/main/java/io/grpc/services/BinlogHelper.java
- services/src/test/java/io/grpc/services/BinlogHelperTest.java
Each entry within the RPC has a seq ID that begins from 1 and counts upwards.
> services: add sequence id within call for entries

- auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
- auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java
This keeps them more secure. Other types of creds are left as-is, since
we don't quite know if it makes sense to have a similar restriction. (It
likely does make sense, but this is a more precise change for our
needs.)
This is a rollforward of 8e9d4cbe5cb455315e55846e91706cccecb4b577
which was rolled back in de9515269635d2e8e84540fcd6744cc1a69ce81b
Reference: #4528
> auth: Require PRIVACY_AND_INTEGRITY for GoogleCredentials

- core/src/main/java/io/grpc/ClientCall.java
- Clarify that some methods of ClientCall may be invoked from any thread. 
- Adds @throws clauses to request(). 
- Adds threading note to cancel() to match request().
> Add clarification to ClientCall javadoc 

- SECURITY.md
- examples/README.md
- examples/src/main/java/io/grpc/examples/helloworldtls/HelloWorldServerTls.java
examples: replace client certificate in trust store in 'Hello world example with TLS with mutual auth' with proper CA certificate to fix SSLV3_ALERT_HANDSHAKE_FAILURE in two host with different IPs setup, switch to required client auth to fail on incorrect configuration
> Issue 4515: SSLHandshakeException when using ClientAuth.REQUIRE with two hosts

- examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java
This client talks to HelloWorld server and not to the route guide one.
> examples: Fix comment in HelloWorldClient

- buildscripts/kokoro/upload_artifacts.sh
We must not include signatures for maven-metadata.xml*, as the file is
a server-maintained index. Avoiding signing the .md5 and .sha1 avoids
signing unnecessary files (which double-excludes some
maven-metadata.xml* files).
We also swap to using ASCII armored output instead of the binary output,
as that's what is appropriate for "asc" files.
Fixes #4574
> Fix signatures in release process

- buildscripts/kokoro/upload_artifacts.sh
We must not include signatures for maven-metadata.xml*, as the file is
a server-maintained index. Avoiding signing the .md5 and .sha1 avoids
signing unnecessary files (which double-excludes some
maven-metadata.xml* files).
We also swap to using ASCII armored output instead of the binary output,
as that's what is appropriate for "asc" files.
Fixes #4574. Backports #4575.
> Fix signatures in release process (1.13.x backport)

- buildscripts/kokoro/upload_artifacts.sh
We must not include signatures for maven-metadata.xml*, as the file is
a server-maintained index. Avoiding signing the .md5 and .sha1 avoids
signing unnecessary files (which double-excludes some
maven-metadata.xml* files).
We also swap to using ASCII armored output instead of the binary output,
as that's what is appropriate for "asc" files.
Fixes #4574. Backports #4575
> Fix signatures in release process  (1.12.x backport)

- stub/src/main/java/io/grpc/stub/StreamObservers.java
Updates #4558
It appears in the linked bug that onError is called from outside.  I don't believe this is safe because thew onReadyCallback is going to call onCompleted.  In the case of an error, it seems like the iterator should be stopped, but there isn't a great way to phrase this.  Ideas welcome.
> stub: clarify StreamObservers interaction

- services/src/main/java/io/grpc/services/BinlogHelper.java
- services/src/test/java/io/grpc/services/BinlogHelperTest.java
Java is unlike the other implementations that our code strips the leading `/`.
When we log the method name, we should be consistent with the
other implementations and put back the `/`.
> services: binlog method name should include leading / char

- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
A new RPC starts with the following steps:
1. Pick a READY transport
2. the READY transport calls `transport.newStream()`
3. the new stream calls `stream.start()`
4. `stream.start()` invokes or enqueus `writeHeaders()` (or for GET request, noop)
A racy transport shutdown could happen between 3 and 4, and by the retry spec, the RPC should be transparent-retry-able in this case. For Netty and OkHttp transport implementation, before step 4, (even if step 1, 2, and 3 excluding 4 are made atomic,) the http2-stream for the RPC is not created, so the current transparent retry logic does not apply and need fix.
Of course, if step 1, 2, and 3 including 4 are made atomic, and not with GET, there will be no such problem.
> netty,okhttp: make rpc followed by racy transport shutdown transparent-retry-able

- core/src/main/java/io/grpc/util/RoundRobinLoadBalancerFactory.java
- core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
- Rework stickiness picker logic to be non-blocking
- Stash `Subchannel` ref in an attribute rather than dedicated map
Possibly controversial:
- Stash constant/immutable `PickResult` in `Subchannel` attribute to avoid identical allocation on every rpc
> util: Improve RoundRobinLoadBalancer scalability with stickiness

- core/src/main/java/io/grpc/LoadBalancer.java
- core/src/main/java/io/grpc/PickFirstBalancerFactory.java
- core/src/main/java/io/grpc/internal/InternalSubchannel.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/OobChannel.java
- core/src/test/java/io/grpc/LoadBalancerTest.java
- core/src/test/java/io/grpc/PickFirstLoadBalancerTest.java
- core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java
- core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
This avoids the needs to flatten to EAGs for cases like PickFirst,
making the Attributes in EAGs able to be used in communication with
core. See #4302 for some discussion on the topic.
-----
This alone will not be enough to rid ourselves of all flattening. We also
need to support List\<EAG> with OobChannels. But I'll do that as a later
PR.
> core: Add support for List<EAG> in Subchannels

- core/src/test/java/io/grpc/PickFirstLoadBalancerTest.java
- core/src/test/java/io/grpc/internal/JndiResourceResolverTest.java
- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
Unused variables in tests were deleted. The unused variable in Netty
was a future that needed completing; that was a bug.
> Fix unused variables

- core/build.gradle
- core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
- core/src/main/java/io/grpc/internal/CallCredentialsApplyingTransportFactory.java
- core/src/main/java/io/grpc/internal/ClientTransportFactory.java
- core/src/main/java/io/grpc/internal/InternalSubchannel.java
- core/src/test/java/io/grpc/internal/CallCredentialsApplyingTest.java
- core/src/test/java/io/grpc/internal/ClientTransportFactoryTest.java
- core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- core/src/test/java/io/grpc/internal/TestUtils.java
- cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
- cronet/src/test/java/io/grpc/cronet/CronetChannelBuilderTest.java
- netty/src/main/java/io/grpc/netty/GrpcHttp2ConnectionHandler.java
- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
- netty/src/test/java/io/grpc/netty/NettyTransportTest.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpChannelBuilderTest.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpTransportTest.java
- testing/src/main/java/io/grpc/internal/testing/AbstractClientTransportFactoryTest.java
There's two commits here, they are likely easiest to review separately. The first commit message provides some details that should help review for that commit (which is larger).
If need be, I can split the EAG plumbing changes out of the first commit and only have it be plumbing for ClientTransportOptions.
These changes are "noisy" because the method signature changed. There's not really much interesting code here, other than the new ClientTransportOptions and a few added tests.
> Plumb EAG attributes to transports and Netty's ProtocolNegotiator

- core/src/main/java/io/grpc/internal/ClientTransportFactory.java
Convert the checkNotNull into our more standard line while I'm cleaning
it up.
> core: Add missing @Nullable annotations to ClientTransportOptions

- netty/src/main/java/io/grpc/netty/GrpcSslContexts.java
- netty/src/test/java/io/grpc/netty/TlsTest.java
Enable testing on Java 9+ in TlsTest, to prevent future regressions.
Fixes #4620
> netty: Fix regression in Java 9 ALPN support

- netty/src/main/java/io/grpc/netty/GrpcSslContexts.java
- netty/src/test/java/io/grpc/netty/TlsTest.java
Enable testing on Java 9+ in TlsTest, to prevent future regressions.
Fixes #4620
Backport of #4625
> netty: Fix regression in Java 9 ALPN support (1.13 backport)

- netty/src/main/java/io/grpc/netty/GrpcSslContexts.java
- netty/src/test/java/io/grpc/netty/TlsTest.java
Enable testing on Java 9+ in TlsTest, to prevent future regressions.
Fixes #4620
Backport of #4625
> netty: Fix regression in Java 9 ALPN support (1.12 backport)

- buildscripts/make_dependencies.sh
This cuts ~20 seconds from the build time and avoids the need to have
autoconf and libtool installed. This is the "normal" way to build
protobuf.
> buildscripts: Use "all" protobuf download to avoid ./autogen.sh

- services/src/main/java/io/grpc/services/ChannelzService.java
- services/src/main/java/io/grpc/services/RequireDoubleSubmitCookieInterceptor.java
- services/src/test/java/io/grpc/services/RequireDoubleSubmitCookieInterceptorTest.java
Add this form of XSRF protection to channelz. Non web browser clients
calling channelz must also include the cookie header and metadata
key.
> services: double submit cookie interceptor for channelz

- .travis.yml
- examples/pom.xml
We do not want to always use jdk8, this allows the `jdk:` section to
select the jdk
> buildscript: fix jdk9, remove jdk10

- alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java
- alts/src/test/java/io/grpc/alts/internal/AltsProtocolNegotiatorTest.java
So that Google call credentials can be sent via ALTS channel.
> alts: add call credential security level attribute

- build.gradle
- core/build.gradle
- core/src/main/java/io/grpc/ClientCall.java
- core/src/main/java/io/grpc/ServerCall.java
- core/src/main/java/io/grpc/StreamTracer.java
- repositories.bzl
- stub/src/main/java/io/grpc/stub/AbstractStub.java
- stub/src/main/java/io/grpc/stub/CallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ClientCallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java
DoNotMock was removed from error_prone_annotations in 2.1.3, because
there was no enforcement mechanism (which is in google/error-prone#572).
Guava and Trust also depend on error_prone_annotations and are beginning
to use newer versions, so our usage of DoNotMock is causing diamond
dependency problems. This allows us to update to 2.2.0.
The annotations were useful internally; we're solving that in cl/205294089.
------
This came out of trying to fix #4655.
> Remove DoNotMock annotation in favor of JavaDoc

- buildscripts/run_in_docker.sh
Printing the commands is pretty ugly output and not particularly
helpful, unless debugging the logic. If needing to debug, just add the
-x locally.
> buildscripts: Remove set -x from run_in_docker.sh

- build.gradle
- context/src/test/java/io/grpc/testing/DeadlineSubject.java
This helps an internal cleanup removing the old failWithRawMessage API.
> context: Avoid deprecated Truth API

- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
If the server sends all response message but does not send the trailers, client throws
StatusRuntimeException: INTERNAL: Received unexpected EOS on DATA frame from server
> interop-testing: Fix clientStreaming interop test does not fail on missing trailers

- core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
> core: make service config errors recoverable

- build.gradle
gae-jdk7 in particular is failing with the 0.42 Truth because it depends
on org.checkerframework:checker-qual 2.5.3 instead of 2.0.0.
------
This is a workaround. We're going to need to figure out a long-term strategy. We have to be able to update to newer versions.
> Downgrade to Truth 0.41 for Java 7 support

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
This fixes a bug with `ManagedChannel#enterIdle` where new calls could hang (remain buffered indefinitely, until the next RPC on the channel) if `#enterIdle` was invoked concurrently with the calls being started. 
The failure cases revolved around `#enterIdle` shutting down the channel's current resolver and LB policy, meaning that asynchronous name resolution or pick selection could (a) never start if the shutdown signal from `#enterIdle` was received before the actual resolution/selection began or (b) have their results ignored since the lb policy that generated them no longer matched the channel's lb policy.
> core: enterIdleMode() exits idle if still in use

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
This is to implement one of changes made in the spec
https://github.com/grpc/proposal/pull/89/files
> core: channel tracing log only when number of backends changed between zeor and nonzero

- core/src/main/java/io/grpc/util/TransmitStatusRuntimeExceptionInterceptor.java
- core/src/test/java/io/grpc/util/UtilServerInterceptorsTest.java
A cancelled context in a ServerCall will have already closed - this
suppresses log messages indicating "context already closed" from
when SREs are thrown as a result of active client requests within the
context.
> Don't close in TSREI in cancelled contexts

- android/build.gradle
- android/proguard-rules.txt
- android/src/main/java/io/grpc/android/AndroidChannelBuilder.java
- android/src/test/java/io/grpc/android/AndroidChannelBuilderTest.java
Redo of https://github.com/grpc/grpc-java/pull/4662. 
Also deletes some unnecessary forwarding methods from AndroidChannelBuilder
> android: include proguard config to keep method names

- build.gradle
- interop-testing/build.gradle
Truth 0.42 brings in some Java 8 bytecode, but they are only in
annotations. So we remove them for gae-java7, otherwise they cause the
build to fail with messages like:
> Unable to stage app: Class file is Java 8 but max supported is Java 7: com/google/auto/value/extension/memoized/Memoized.class in /usr/local/google/home/ejona/clients/grpc-java/gae-interop-testing/gae-jdk7/build/exploded-grpc-gae-interop-testing-jdk7/WEB-INF/lib/auto-value-annotations-1.6.2.jar
> Unable to stage app: Class file is Java 8 but max supported is Java 7: org/checkerframework/dataflow/qual/Pure$Kind.class in /tmpfs/src/github/grpc-java/gae-interop-testing/gae-jdk7/build/exploded-grpc-gae-interop-testing-jdk7/WEB-INF/lib/checker-qual-2.5.3.jar
I manually tested the interop client with Java 7 and it ran without …
> Upgrade to Truth 0.42

- core/src/main/java/io/grpc/internal/DnsNameResolver.java
- core/src/main/java/io/grpc/internal/InternalSubchannel.java
- core/src/main/java/io/grpc/internal/ProxyDetector.java
- core/src/main/java/io/grpc/internal/ProxySocketAddress.java
- core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
This internal class will only ever be used to plumb proxy info.
> core: turn PairSocketAddress into ProxySocketAddress

- grpclb/src/main/java/io/grpc/grpclb/GrpclbConstants.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancerFactory.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
Since AutoConfiguredLoadBalancer is the location for lb delegation, gRPCLB no longer needs to.  This is a follow up item that simplifies the code.
> grpclb: remove unnecesary support for lb delegation

- core/src/main/java/io/grpc/util/TransmitStatusRuntimeExceptionInterceptor.java
- core/src/test/java/io/grpc/util/UtilServerInterceptorsTest.java
Prevent multiple effective close calls either by successful completion
of a cancel or complete notification, or through successive exceptions
handled within a single call.
> core: Don't close in TSREI in cancelled contexts (#4596) (backport to v1.14.x)

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
This is the implementation of the second one of the changes to the channel tracing spec
https://github.com/grpc/proposal/pull/89
> core: let channel tracing log service config changes

- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpTransportTest.java
- testing/src/main/java/io/grpc/internal/testing/TestUtils.java
Our Travis-CI builds are failing with "Protocol family unavailable" due
to the usage of ::1. Although it's 2017 and we'd expect to have ipv6
_loopback_ anywhere that mattered, apparently that's not the case.
The tests now work equally well on IPv4-only and IPv6-only machines.
This is a backport of #3654
> Allow tests to run on IPv6-less machines (1.6 backport)

- gae-interop-testing/gae-jdk7/build.gradle
- gae-interop-testing/gae-jdk7/src/main/java/io/grpc/testing/integration/OkHttpClientInteropServlet.java
- gae-interop-testing/gae-jdk8/build.gradle
- gae-interop-testing/gae-jdk8/src/main/java/io/grpc/testing/integration/NettyClientInteropServlet.java
The server doesn't support Echo Status.
CC @zpencer 
This fixes a regression caused by #4682
> gae-interop-testing: Disable special_status_message

- android-interop-testing/build.gradle
- build.gradle
- buildscripts/checkstyle.xml
We previously passed a custom variable to the checkstyle configuration.
In Gradle 4.0 config_loc was added for the same purpose. The default
configDir is $projectDir/config/checkstyle which is different for each
project; we need to override it to always point to the root project.
> gradle: Use config_loc in checkstyle

- repositories.bzl
This was missed in the earlier #4668 and #4664
> repositories.bzl: Upgrade to Truth 0.42

- netty/src/main/java/io/grpc/netty/NettyClientStream.java
- netty/src/main/java/io/grpc/netty/NettyServerStream.java
- netty/src/main/java/io/grpc/netty/WriteQueue.java
- netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
- netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java
- netty/src/test/java/io/grpc/netty/NettyServerStreamTest.java
- netty/src/test/java/io/grpc/netty/NettyStreamTestBase.java
Passing a promise to WriteQueue was only misused to add a listener on
the promise before issuing the write. Although in this case the listener
ordering will be "random" because listeners are being added from two
different threads, in general we always want to add a listener after the
write returns to let any lower-level listeners be registered first.
Future work can resolve the "random" listener order by passing the
listener to the WriteQueue and adding the listener from the event loop.
> netty: Remove option to pass promise to WriteQueue

- core/src/main/java/io/grpc/ExperimentalApi.java
- core/src/main/java/io/grpc/Metadata.java
- core/src/main/java/io/grpc/SecurityLevel.java
- core/src/main/java/io/grpc/Status.java
- core/src/main/java/io/grpc/StatusException.java
- core/src/main/java/io/grpc/StatusRuntimeException.java
- protobuf/src/main/java/io/grpc/protobuf/StatusProto.java
- services/src/main/java/io/grpc/services/HealthStatusManager.java
- stub/src/main/java/io/grpc/stub/ClientResponseObserver.java
- stub/src/main/java/io/grpc/stub/StreamObservers.java
Additionally, make Status*Exception.getTrailers() non experimental
> all:  add tracking issues for all experimental APIs and make it required

- core/src/main/java/io/grpc/util/RoundRobinLoadBalancerFactory.java
- core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
RoundRobinLoadBalancerFactory creates a new Picker instance every time the set of provided address groups changes or the connection state of subchannels associated with existing address groups changes. In certain scenarios, such as deployment/replacement of the target service cluster, this can lead to high churn of Picker objects. Given that each new Picker's subchannel index is initialized to zero, in these scenarios requests can end up getting disproportionately routed through subchannels (and hence server nodes) which are earlier in the list of address groups.
At Netflix we have measured that some service nodes end up taking 3-4x the load that of other nodes during deployment.
This commit randomizes the start index of the RoundRobinLoadBalancerFactory.Picker which eliminates this …
> core: initialize round robin load balancer picker to random index

- cronet/src/main/java/io/grpc/cronet/CronetCallOptions.java
No-op change. These look like the only remaining usages within grpc itself.
> cronet: Clean up remaining usages of deprecated CallOptions#of()

- README.md
- core/src/main/java/io/grpc/ManagedChannelProvider.java
- core/src/main/java/io/grpc/ServerProvider.java
- documentation/server-reflection-tutorial.md
- examples/build.gradle
- examples/example-kotlin/build.gradle
- examples/pom.xml
grpc-netty is still really useful, but for most users who aren't doing
anything advanced using grpc-netty-shaded is much safer from a
dependency basis.
grpc-netty-shaded has seen more usage and has shown itself to be stable
and reduce the number of conflicts due to Netty versions.
> Encourage using grpc-netty-shaded instead of grpc-netty

- core/src/main/java/io/grpc/inprocess/InProcessSocketAddress.java
- core/src/test/java/io/grpc/inprocess/InProcessSocketAddressTest.java
This is a minor API change, since names can no longer be null.  gRPC never constructed these addresses with null, but other users could.
> inprocess: prevent null names, and define socket address equality

- README.md
- examples/android/clientcache/build.gradle
- examples/android/helloworld/build.gradle
- examples/android/routeguide/build.gradle
- examples/build.gradle
The version bump happened in some places already, but many references
were missed.
This fixes the following warning that shows up with newer versions of
Gradle:
> Using TaskInputs.file() with something that doesn't resolve to a File
> object has been deprecated and is scheduled to be removed in Gradle
> 5.0. Use TaskInputs.files() instead.
> Bump protobuf-gradle-plugin to 0.8.5

- core/src/main/java/io/grpc/Status.java
There seem to be some users converting from StatusRuntimeException
to StatusException using the following paradigm:
sre.getStatus().toException(sre.getTrailers())
Since there isn't a viable alternative, revert the warning.
> core: revert warning about `Status.asException(null)`

- stub/src/main/java/io/grpc/stub/ClientCalls.java
- stub/src/main/java/io/grpc/stub/ServerCalls.java
* Reflowed some method parameters to be on the same line, else one
parameter per line
* Used `@link` where appropriate
* Made some parameters non-final where it had no effect
* Renamed some parameters to be consistent
> stub: update docs about Call lifetime + minor cleanups

- core/src/main/java/io/grpc/internal/DnsNameResolver.java
- core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
It used to throw NPE, since URI.create creates URI with null hostname. Now it
thorws IllegalArgumentException for invalid DNS name, NPE for null name.
Resolves #3701
> Fix errror message when DNS name is invalid.

- README.md
Reorganize the README to flow better for new users, pointing them in
good directions. Also try to reduce the size so they actually read the
thing. It's still to long, but is a step in the right direction.
Fixes #4615
> README.md: Reorganize and trim

- netty/src/main/java/io/grpc/netty/InternalNettyChannelBuilder.java
This is needed internally for building netty transports outside of a channel.
> netty/internal: add InternalNettyChannelBuilder.buildTransportFactory().

- alts/build.gradle
- examples/build.gradle
- examples/pom.xml
- netty/shaded/build.gradle
There's no good way to provide users of ALTS a choice between grpc-netty
and grpc-netty-shaded. Since Netty is not exposed through the ALTS API
surface, we opt for the shaded version as it has fewer deployment
issues. However, this also means that we _can't_ expose any Netty API,
like EventLoopGroup.
--------------
The core problem is that we need to be able to use ALTS with grpc-netty-shaded, as it greatly reduces the diamond dependency issues users experience. With grpc-netty it may not be possible to produce a working executable, depending on what your other dependencies are. ALTS is the first dependency we've had on grpc-netty.
It seems we are painting ourselves into a corner with ALTS, as I feel like I'm threading a needle amongst all the constraints involved. But I don't see any …
> alts: Use grpc-netty-shaded instead of grpc-netty

- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
If the RPC did not finish, then the remainig checks are red herrings.
> interop-testing: timeoutOnSleepingServer should check that RPC finished

- core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java
- core/src/test/java/io/grpc/internal/ProxyDetectorImplTest.java
ProxySelector.getDefault() can return null
Fixes #4677
> core: Handle null ProxySelector

- gae-interop-testing/gae-jdk7/build.gradle
- gae-interop-testing/gae-jdk7/src/main/java/io/grpc/testing/integration/OkHttpClientInteropServlet.java
- gae-interop-testing/gae-jdk8/build.gradle
- gae-interop-testing/gae-jdk8/src/main/java/io/grpc/testing/integration/NettyClientInteropServlet.java
for jdk7 include the passing test names in the order they were run
for both, include the JUL log output
> gae-interop-testing: increase response verbosity

- buildscripts/build_docker.sh
Github used to produce tars with the full SHA in the folder name.
However, now they are providing tars with just as much SHA as was in the
initial request. This coincides with a change in its services:
Before:
Resolving github.com... 192.30.253.113, 192.30.253.112
Connecting to github.com|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github-production-release-asset-2e65be.s3.amazonaws.com/23357588/88f90e58-e598-11e7-9263-ef8b1fb345b8?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20180817%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180817T190158Z&X-Amz-Expires=300&X-Amz-Signature=b684e1ead24a96764fd1f29ac5eb1df693d47c5fe86962088aee2ccfb8e4e72a&X-Amz-SignedHeaders=host&actor_id=0&response-content-disposition= …
> buildscripts: Use full SHA for protobuf download

- gae-interop-testing/gae-jdk7/src/main/java/io/grpc/testing/integration/OkHttpClientInteropServlet.java
The test is flakey and we have exhausted the obvious clues. Since the
impact of this is likely low, let's `@Ignore` it.
See #4626
> gae-interop-testing: disable timeoutOnSleepingServer

- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
Most environments won't trigger an interruption, but AppEngine will if
the request takes too long.
> interop-testing: Clean up even if interrupted

- .travis.yml
- buildscripts/make_dependencies.sh
Wildcard apparently doesn't work... silently. Move versions into their
own directory so we can use a hard-coded string in the travis
configuration.
> travis.yml: Fix protobuf compilation caching

- .travis.yml
Throw away Travis-CI's custom Maven settings, because they are causing
massive CI failures when Maven slows to a crawl/hangs because of
failures contaicting repository.apache.org.
Travis-CI's settings includes repo.maven.apache.org, oss.sonatype
(releases and snapshots), and repository.apache.org (releases and
snapshots). Now we will just be using Maven's default, which may just
be repo.maven.apache.org.
> travis: Use default Maven settings

- core/src/main/java/io/grpc/NameResolverProvider.java
- core/src/test/java/io/grpc/NameResolverProviderTest.java
* Make the list of providers an immutable List
* Make obvious that the list is statically initialized
* Add documentation for when methods were added.
* Log on missing classes
* make more classes final, hide constructors.
* Use proper UnsupportedOperationException, rather than IllegalStateException.
> core: minor cleanup of NameResolverProvider

- core/src/main/java/io/grpc/ManagedChannelBuilder.java
- core/src/main/java/io/grpc/internal/HedgingPolicy.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/RetriableStream.java
- core/src/main/java/io/grpc/internal/RetryPolicy.java
- core/src/main/java/io/grpc/internal/ServiceConfigInterceptor.java
- core/src/main/java/io/grpc/internal/ServiceConfigUtil.java
- core/src/test/java/io/grpc/internal/HedgingPolicyTest.java
- core/src/test/java/io/grpc/internal/RetriableStreamTest.java
- core/src/test/java/io/grpc/internal/ServiceConfigInterceptorTest.java
- core/src/test/resources/io/grpc/internal/test_hedging_service_config.json
This is only API plumbing for hedging, following exactly the same way as its retry counterpart, so it is almost trivial.
> core: plumb hedging policy

- stub/src/main/java/io/grpc/stub/CallStreamObserver.java
The docs refer to the wrong places where this feature is ignored.
Fixes #4772
> stub: disableAutoInboundFlowControl javadoc correction

- buildscripts/kokoro/gae-interop.sh
The test has become very flakey recently. With GAE jdk7 going away
completely in early 2019, let's disable running the test in CI.
> buildscripts: disable gae jdk7 test

- README.md
This seems strictly better than #4582. We can always move the location around later.
> README.md: Link to Alpine's protoc-gen-grpc-java

- build.gradle
- core/build.gradle
- examples/pom.xml
- okhttp/build.gradle
Core and OkHttp are left with Java 6 for the moment. Once we resolve
their issues they could be bumped as well.
Updates #3961
----
@ericgribkoff, could you help out with Core and OkHttp, figuring out how we can handle the incompatibility?
> all: Swap to Java 7 source and bytecode

- core/build.gradle
- core/src/main/java/io/grpc/internal/Rescheduler.java
(This PR is a follow-up for an issue identified in https://github.com/grpc/grpc-java/pull/4799 and should not be merged without that change)
javac can produce code that invokes Object.requireNonNull when instantiating
an inner class using a instance variable. See
https://bugs.openjdk.java.net/browse/JDK-8202137
@ejona86 From the linked bug, I don't see that there is an option here other than marking the inner class non-static. It's slightly unsettling that we apparently need animalsniffer to catch javac including code that isn't present on old Android devices; I haven't had time to check if the android build system would otherwise do something fancy here to avoid issues at runtime on older devices.
If this looks alright, do you want to cherry-pick this commit into …
> core: allow Java 7 source and bytecode

- okhttp/build.gradle
- okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/Util.java
Leaving the method as-is seems to require both of the following annotations:
```
@SafeVarargs
@SuppressWarnings("varargs")
```
Rather than doing this (`@SafeVarargs` may or may not be fine for Android pre-API 19, didn't dig into it fully), it seems easier to just change the method signature to accept an array instead of varargs. The utility function is only used in two places, `io.grpc.okhttp.internal.ConnectionSpec#cipherSuites` and `io.grpc.okhttp.internal.ConnectionSpec#tlsVersions`.
> okhttp: use java 7, avoid compiler varargs warning

- alts/src/main/java/io/grpc/alts/AltsChannelBuilder.java
- alts/src/main/java/io/grpc/alts/AltsServerBuilder.java
- alts/src/main/java/io/grpc/alts/CheckGcpEnvironment.java
- alts/src/main/java/io/grpc/alts/FailingClientCall.java
- alts/src/main/java/io/grpc/alts/GoogleDefaultChannelBuilder.java
- alts/src/test/java/io/grpc/alts/AltsChannelBuilderTest.java
In ALTS, rather than throws RuntimeException if the application is not running on GCP, we fail at interceptCall.
> alts: if ALTS is not running on GCP, fails call

- examples/pom.xml
error message:
cmd: mvn verify
Downloading from central: https://repo.maven.apache.org/maven2/kr/motd/maven/os-maven-plugin/1.5.0.Final/os-maven-plugin-1.5.0.Final.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin kr.motd.maven:os-maven-plugin:1.5.0.Final or one of its dependencies could not be resolved: Failed to read artifact descriptor for kr.motd.maven:os-maven-plugin:jar:1.5.0.Final @ 
@ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.grpc:examples:1.16.0-SNAPSHOT (/home/travis/build/grpc/grpc-java/examples/pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin kr.motd.maven:os-maven-plugin:1.5.0.Final or one of its dependencies could not be resolved: …
> examples: Add google mirrored maven central to examples pom.xml to deflake kokoro.

- core/src/main/java/io/grpc/internal/CensusTracingModule.java
- core/src/test/java/io/grpc/internal/CensusModulesTest.java
skip populating trace header if no census impl is available.
> core: skip populating trace header if no census impl is available.

- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- okhttp/src/main/java/io/grpc/okhttp/OutboundFlowController.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
settings acks back after apply settings before sending any data as a result of the change.
Resolves #4809 also, make #4816 the not flaky.
> okhttp: settings acks back after apply settings before sending any data

- interop-testing/src/main/java/io/grpc/testing/integration/TestCases.java
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
- interop-testing/src/test/java/io/grpc/testing/integration/TestCasesTest.java
This was shown by https://github.com/grpc/grpc-java/issues/4809 to be a useful test. This change makes it easier to reproduce issues by running the test case manually with the interop client.
> interop-testing: add very_large_request case to test client

- core/src/main/java/io/grpc/internal/DnsNameResolver.java
- core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
- core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
DnsNameResolver caches refresh using java system property networkaddress.cache.ttl.
Resolves #4745
> core: DnsNameResolver caches refresh

- grpclb/src/main/java/io/grpc/grpclb/BackendAddressGroup.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
The addresses from the string dump of the LoadBalanceResponse proto is
in binary format and not human-readable.  We will log the
BackendAddressGroups when using a new list from the balancer.  The
original logging of LoadBalanceResponse is downgraded to FINER level.
> grpclb: more useful debug logs.

- README.md
> doc: update README because we have been requiring Java 7 (1.15.x backport)

- netty/src/test/java/io/grpc/netty/NettyTransportTest.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpTransportTest.java
- testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
This attempts to fix a flake seen exactly once with the
currently-disabled OkHttpTransportTest.flowControlPushBack:
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at io.grpc.internal.testing.AbstractTransportTest.flowControlPushBack(AbstractTransportTest.java:1300)
```
That was a failure for assertTrue(serverStream.isReady()), because the
awaitOnReady was finding the previous invocation of onReady. We now
track how many times it has been called. This was a bug introduced in
a8db154 but wouldn't have been noticed since the in-process transport
is deterministic.
----
It appears to be stable now. Ran for 1000s of times. I do see some
general flakiness in TransportTest, but it …
> Enable TransportTest.flowControlPushBack and fix a flake

- core/src/main/java/io/grpc/internal/DnsNameResolver.java
- core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
- core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
DnsNameResolver caches refresh using java security property networkaddress.cache.ttl.
Resolves #4745 
-----
This is a backport of #4812
This will wait until the the v1.15.0 build is made, for inclusion in v1.15.1. We'd like it to "sit" longer before being in a release to avoid reducing stability.
> core: DnsNameResolver caches refresh (1.15.x backport)

- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- okhttp/src/main/java/io/grpc/okhttp/OutboundFlowController.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
okhttp: setting acks back after apply settings before sending any data as a result of the change.
Resolves #4809 also, make #4816 the not flaky.
CC @zhangkun83 
This is a backport of #4825
> okhttp: settings acks back after apply settings before sending any data (1.15.x backport)

- alts/src/main/java/io/grpc/alts/GoogleDefaultChannelBuilder.java
- alts/src/main/java/io/grpc/alts/internal/GoogleDefaultProtocolNegotiator.java
- netty/src/main/java/io/grpc/netty/GrpcHttp2ConnectionHandler.java
- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
- netty/src/test/java/io/grpc/netty/NettyChannelBuilderTest.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
- netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
This simplifies the construction paradigm and leads to the eventual
removal of TransportCreationParamsFilterFactory. The eventual end goal
is to be able to shut down ProtocolNegotiators as is necessary for ALTS.
The only reason the initialization was delayed was for 'authority', so
we now plumb the authority through GrpcHttp2ConnectionHandler.
> netty: Initialize ProtocolNegotiators eagerly

- buildscripts/make_dependencies.bat
- buildscripts/make_dependencies.sh
A substantial portion of our build logs are just compiling protobuf.
This reduces the noise while still keeping most of the useful
information.
> buildscripts: Reduce verbosity of protobuf builds

- .github/lock.yml
These are settings for the Lock app: https://github.com/apps/lock
We'll probably want to reduce the daysUntilLock to something lower, but
want to try it out first and a larger value will impact fewer issues.
365 is the default, but making it clear what setting we are using.
I disable the comment because I don't want notification noise. I disable
the resolved feature because I'm not quite sure what it is and I'm not
really looking for anything fancy.
The defaults can be found at
https://github.com/dessant/lock-threads/blob/master/src/schema.js
> github/lock: Override some of the defaults before enabling

- services/src/main/java/io/grpc/services/BinlogHelper.java
- services/src/test/java/io/grpc/services/BinlogHelperTest.java
Let's simplify the implementation to just disallow duplicates. This
makes it easier to maintain.
Background info: https://github.com/grpc/proposal/pull/104
> services: disallow duplicate rules for a binlogging services or methods

- .github/lock.yml
What the "reason" means was explained in
https://github.com/grpc/grpc-java/pull/4862#issuecomment-423662264 , and
it's probably fair to accept the default.
> github/lock: Use reason "resolved", which is the default

- netty/src/main/java/io/grpc/netty/InternalNettyChannelBuilder.java
- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
This will be the replacement for TransportCreationParamsFilterFactory
and matches what used to be done and what is done on server-side.
> netty: Allow specifying a ProtocolNegotatior directly to Channels

- alts/src/main/java/io/grpc/alts/AltsChannelBuilder.java
- alts/src/main/java/io/grpc/alts/GoogleDefaultChannelBuilder.java
- alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java
- alts/src/main/java/io/grpc/alts/internal/GoogleDefaultProtocolNegotiator.java
- alts/src/test/java/io/grpc/alts/AltsChannelBuilderTest.java
- alts/src/test/java/io/grpc/alts/GoogleDefaultChannelBuilderTest.java
Provide a ProtocolNegotiator directly instead.
TransportCreationParamsFilterFactory is being removed.
-----
~The first two commits are just dependencies. This depends on #4835 and #4855~ Those are merged. Rebased.
CC @jiangtaoli2016
> alts: Remove usage of TransportCreationParamsFilterFactory

- alts/src/main/java/io/grpc/alts/AltsChannelBuilder.java
- alts/src/main/java/io/grpc/alts/AltsServerBuilder.java
- alts/src/main/java/io/grpc/alts/GoogleDefaultChannelBuilder.java
- alts/src/main/java/io/grpc/alts/internal/AltsClientOptions.java
- alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java
- alts/src/main/java/io/grpc/alts/internal/GoogleDefaultProtocolNegotiator.java
- alts/src/main/java/io/grpc/alts/internal/TsiHandshakerFactory.java
- alts/src/test/java/io/grpc/alts/AltsChannelBuilderTest.java
- alts/src/test/java/io/grpc/alts/internal/AltsClientOptionsTest.java
- alts/src/test/java/io/grpc/alts/internal/AltsHandshakerClientTest.java
- alts/src/test/java/io/grpc/alts/internal/AltsProtocolNegotiatorTest.java
- alts/src/test/java/io/grpc/alts/internal/FakeTsiHandshaker.java
Plumb authority into ALTS protocol negotiator and into AltsClientOption so that client can perform server authority (aka secure naming) check, which is done by the handshaker service.
> alts: plumb authority to ALTS protocol negotiator
