grpc/grpc-java

android/src/test/java/io/grpc/android/AndroidChannelBuilderTest.java
This is a lint discovered during import.
=> android: Robolectric shadows shouldn't be stored

examples/example-kotlin/android/helloworld/app/build.gradle
This fixes the bug described in #4647
=> examples: Fix bad copy/paste for tests with Android Studio

android-interop-testing/app/src/androidTest/java/io/grpc/android/integrationtest/InteropInstrumentationTest.java, buildscripts/kokoro/android-interop.cfg, buildscripts/kokoro/android-interop.sh
Adds a new Kokoro buildscript to build and test the android-interop-testing app.
Internal change is cl/201371950
=> Run Android interop instrumentation tests on Firebase

core/src/main/java/io/grpc/internal/HedgingPolicy.java
=> core: make HedgingPolicy final

stub/src/main/java/io/grpc/stub/AbstractStub.java
=> stub: stablize AbstractStub.withExecutor API

RELEASING.md
=> doc: new file to be sed'ed during the release (1.15.x  backport)

alts/src/main/java/io/grpc/alts/AltsChannelBuilder.java, alts/src/main/java/io/grpc/alts/GoogleDefaultChannelBuilder.java
This simplifies the construction process, as we have fewer "interesting"
phases to weed through.
----
~~The first commit is from #4834, which this PR depends on since TLS needs to
be eagerly initialized as well. I'll wait until #4834 is approved and then manually
rebase+merge.~~ Now rebased on master which includes that PR.
CC @jiangtaoli2016
=> alts: Initialize ProtocolNegotiators eagerly

RELEASING.md
I will backport this to v1.15.x.
=> RELEASING.md: Add missing TestDeprecatedService replacements

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
This is mainly to not have to figure out what anonymous class `$13` is when looking at stack traces.
=> core: name anonymous classes in ManagedChannel for clear stacktraces

netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java, netty/src/main/java/io/grpc/netty/NettyClientTransport.java, netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
=> netty: expose setting a local socket address

okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/Platform.java
See internal issue b/116007005 for additional details.
=> okhttp: Add SslGuard to list of allowed security providers. 

SECURITY.md, build.gradle, repositories.bzl
=> netty: update to 4.1.30 and 2.0.17

SECURITY.md, build.gradle, repositories.bzl
Cherry pick of 5362017c5af3f77607b4cf78b901bb017042afff
=> netty: update to 4.1.30 and tcn 2.0.17

core/src/main/java/io/grpc/internal/DnsNameResolver.java, core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
This change does 3 main things (in 3 commits):
1.  Refactor the resolution runnable to be testable
2.  Add Finer level logging to aid in debugging
3.  Check that there are addresses before passing them to ManagedChannelImpl.
=> core: make DnsNameResolver Error on empty addresses

core/src/main/java/io/grpc/internal/DnsNameResolver.java, core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
=> core: throw exception on resolution failure and no jndi resolver

core/src/main/java/io/grpc/internal/DnsNameResolver.java
=> core: enable SRV records lookup

alts/src/generated/main/java/io/grpc/alts/internal/Altscontext.java, alts/src/generated/main/java/io/grpc/alts/internal/Handshaker.java, alts/src/main/proto/grpc/gcp/altscontext.proto, alts/src/main/proto/grpc/gcp/handshaker.proto
The new field is not used yet.
=> alts: update handshaker proto

okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java, okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java, okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java, okhttp/src/main/java/io/grpc/okhttp/OutboundFlowController.java, okhttp/src/main/java/io/grpc/okhttp/Utils.java, okhttp/src/test/java/io/grpc/okhttp/OkHttpClientStreamTest.java, okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
=> okhttp: make flow control window size configurable

netty/src/main/java/io/grpc/netty/NettyClientTransport.java
=> netty: fix local socket bind

alts/src/main/proto/grpc/gcp/altscontext.proto, alts/src/main/proto/grpc/gcp/handshaker.proto, alts/src/main/proto/grpc/gcp/transport_security_common.proto
=> alts: remove empty line in the proto

stub/src/main/java/io/grpc/stub/MetadataUtils.java
Fixes #5045
I did a quick check for other similar issues but couldn't find any.
=> stub: Fix null check in MetadataUtils. Fixes #5045

examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/build.gradle, examples/example-kotlin/android/helloworld/app/build.gradle, examples/example-kotlin/build.gradle, examples/example-kotlin/settings.gradle, examples/settings.gradle
It's a lot of work to tackle #4084 but we can first do some cleanup in examples.
=> examples: prefer implementation to compile in build.gradle

core/src/main/java/io/grpc/LoadBalancer.java, core/src/main/java/io/grpc/internal/ManagedChannelImpl.java, core/src/main/java/io/grpc/util/ForwardingLoadBalancerHelper.java, core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
=> core: add LoadBalancer.Helper.refreshNameResolution()

SECURITY.md, build.gradle, examples/build.gradle, netty/src/test/java/io/grpc/netty/UtilsTest.java, repositories.bzl
This is a revival of @ST-DDT 's issue #5080
=> netty: bump to 4.1.32 and tcnative 2.0.20

alts/src/main/java/io/grpc/alts/GoogleDefaultChannelBuilder.java
This allows calling build() multiple times as well as prevents other
interceptors from being able to detect that we've implemented
CallCredential attachment via an interceptor. (Previously they could
have set their own CallCredentials which would have overridden the
default creds.)
=> alts: Eagerly add interceptor in GoogleDefaultChannelBuilder

build.gradle, examples/example-kotlin/build.gradle, repositories.bzl
See https://github.com/census-instrumentation/opencensus-java/issues/1635
=> all: update proto-google-common-proto to 1.12.0

core/src/jmh/java/io/grpc/internal/ChannelzBenchmark.java, core/src/main/java/io/grpc/InternalLogId.java, core/src/main/java/io/grpc/inprocess/InProcessTransport.java, core/src/main/java/io/grpc/internal/DelayedClientTransport.java, core/src/main/java/io/grpc/internal/InternalSubchannel.java, core/src/main/java/io/grpc/internal/ManagedChannelImpl.java, core/src/main/java/io/grpc/internal/OobChannel.java, core/src/main/java/io/grpc/internal/ServerImpl.java, core/src/test/java/io/grpc/InternalChannelzTest.java, core/src/test/java/io/grpc/InternalLogIdTest.java, core/src/test/java/io/grpc/internal/ChannelLoggerImplTest.java, core/src/test/java/io/grpc/internal/ChannelTracerTest.java, core/src/test/java/io/grpc/internal/InternalSubchannelTest.java, core/src/test/java/io/grpc/internal/ServerImplTest.java, core/src/test/java/io/grpc/internal/TestUtils.java, cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java, grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java, netty/src/main/java/io/grpc/netty/NettyClientTransport.java, netty/src/main/java/io/grpc/netty/NettyServer.java, netty/src/main/java/io/grpc/netty/NettyServerTransport.java, okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java, services/src/test/java/io/grpc/services/ChannelzTestHelper.java
A follow up PR to set the details in channelz.
=> core: standardize logid format and add details for channelz

examples/example-gauth/pom.xml, examples/example-tls/pom.xml, examples/pom.xml
matches to the url in build.gradle
=> examples: update url of project

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java, core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
=> core: (backport) fix a channel panic bug caused by calling NameResolver.refresh() when it's not started

examples/AUTHENTICATION_EXAMPLE.md, examples/README.md, examples/example-gauth/GOOGLE_AUTH_EXAMPLE.md, examples/example-tls/README.md
=> examples: Not to promise a supported bazel version

build.gradle
This is a cherry-pick of c10ca92598f1f7a14a9f6be8002ff08eb3ebe9be
=> xds: do not upload archives for xds for now (backport)

build.gradle
=> build: fix javadoc failure for java 11

services/src/main/java/io/grpc/services/HealthCheckingLoadBalancerFactory.java
This is required by the spec:
https://github.com/grpc/proposal/blob/master/A17-client-side-health-checking.md
=> services: log an error to java logger when health-check disabled.

okhttp/src/main/java/io/grpc/okhttp/AsyncSink.java, okhttp/src/test/java/io/grpc/okhttp/AsyncSinkTest.java
This change will suppress NPE logs when the transport encountered
any error during connection phrase.
resolves #5256
=> okhttp: throws correct exception in AsyncSink when write/flush before connected

okhttp/src/main/java/io/grpc/okhttp/AsyncSink.java, okhttp/src/test/java/io/grpc/okhttp/AsyncSinkTest.java
This change will suppress NPE logs when the transport encountered any error during connection phrase.
resolves #5256
=> okhttp: throws correct exception in AsyncSink when write/flush before connected (1.18.x backport)

java_grpc_library.bzl
The internal linter complains about the formatting of this file.
=> all: fix formating on bzl file

buildscripts/kokoro/android.sh
This reverts commit aaa3a86dd20d5eb2bc0dd4c94eac2db845e3fdad.
=> Revert "buildscripts: disable android size status check (#5278)"

core/src/main/java/io/grpc/internal/DnsNameResolver.java, core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
=> core: fix service config prefix matching in Dns

examples/src/main/java/io/grpc/examples/advanced/HelloJsonClient.java, examples/src/main/java/io/grpc/examples/advanced/HelloJsonServer.java
This PR was originally made by @chengsluo (#5159)
=> examples: fix the logger name to match actual class. 

CONTRIBUTING.md
Updated java style guide link in CONTRIBUTING.md.
[X] Fixed issue #5313
=> Issue #5313, Fix google java style guide link

build.gradle, repositories.bzl
Updates https://github.com/grpc/grpc-java/issues/5291.
v0.19.2 release includes a fix for OpenCensus gRPC metrics.
/cc @bogdandrutu @dinooliva @zhangkun83
=> all: upgrade OpenCensus version.

core/src/main/java/io/grpc/MethodDescriptor.java
Correct spelling for code comment.
=> Remove some duplicated words in comment

netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
Motivation:
WAUH may not be the first in the pipeline (esp. when there is a proxy first).  Don't bother checking state, which is difficult to do composably.
=> netty: make WaitUntilActiveHandler not check if the channel is active

build.gradle, core/BUILD.bazel, core/build.gradle, core/src/main/java/io/grpc/internal/JndiResourceResolverFactory.java, repositories.bzl
=> core: suppress android lint error for javax.naming.*

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
=> core fix 5450 (alternative approach)

buildscripts/build_docker.sh
This was missed from d7e53e871
=> buildscripts: Update protoc-artifacts to 3.7.0

core/src/main/java/io/grpc/SynchronizationContext.java
Similar to what's done in `SerializingExecutor`, it's easy to make `SynchronizationContext` non-blocking.
=> core: Avoid locks in SynchronizationContext

core/src/main/java/io/grpc/LoadBalancerProvider.java, core/src/main/java/io/grpc/NameResolver.java, core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java, core/src/main/java/io/grpc/internal/DnsNameResolver.java, core/src/main/java/io/grpc/internal/ManagedChannelImpl.java, core/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java, core/src/main/java/io/grpc/util/SecretRoundRobinLoadBalancerProvider.java, core/src/test/java/io/grpc/internal/DnsNameResolverTest.java, core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java, grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancerProvider.java, services/src/main/java/io/grpc/services/internal/HealthCheckingRoundRobinLoadBalancerProvider.java, xds/src/main/java/io/grpc/xds/XdsLoadBalancer.java, xds/src/main/java/io/grpc/xds/XdsLoadBalancerProvider.java
The type are turned out to not be very useful, so removing it.  
cc @zhangkun83
=> core: remove Type from ConfigOrError

netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
As discovered in the course of https://github.com/grpc/grpc/issues/18645 .
=> netty: ALPN negotiation failure should be UNAVAILABLE, not UNKNOWN

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
=> okhttp: wait until connection preface / settings during transport start to avoid deadlock (back port of #5567)

netty/src/main/java/io/grpc/netty/Utils.java
=> netty: make default number of event loops defer to netty

api/src/main/java/io/grpc/LoadBalancer.java, api/src/main/java/io/grpc/LoadBalancerProvider.java, api/src/main/java/io/grpc/NameResolver.java, api/src/test/java/io/grpc/LoadBalancerTest.java, core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java, core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java, core/src/main/java/io/grpc/internal/DnsNameResolver.java, core/src/main/java/io/grpc/internal/ManagedChannelImpl.java, core/src/main/java/io/grpc/internal/PickFirstLoadBalancer.java, core/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java, core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java, core/src/test/java/io/grpc/internal/DnsNameResolverTest.java, core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java, core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java, core/src/test/java/io/grpc/internal/PickFirstLoadBalancerTest.java, core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java, grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java, grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java, services/src/test/java/io/grpc/services/HealthCheckingLoadBalancerFactoryTest.java, xds/src/main/java/io/grpc/xds/XdsLoadBalancer.java, xds/src/test/java/io/grpc/xds/FallbackManagerTest.java, xds/src/test/java/io/grpc/xds/XdsLoadBalancerTest.java
=> core: update LB and NR API names

api/src/main/java/io/grpc/MethodDescriptor.java
=> api: Stabilize MethodDescriptor.Marshaller

api/src/main/java/io/grpc/Status.java
Per recent discussions.
Go: https://github.com/grpc/grpc-go/pull/2774
C: https://github.com/grpc/grpc/pull/18761
=> docs: add note about retrying UNAVAILABLE

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
The method is going to be removed.
=> interop-testing: remove Truth method named()

stub/src/main/java/io/grpc/stub/ServerCalls.java
fixing https://github.com/grpc/grpc-java/issues/5636
=> server-streaming: release reference on request after method call

stub/src/main/java/io/grpc/stub/ClientCalls.java, stub/src/main/java/io/grpc/stub/ServerCalls.java
when StreamObserver.onNext is called after the stream is terminated.
resolves #5656
=> stub: improve error message for Client/ServerCalls 

core/BUILD.bazel, core/src/main/java/io/grpc/perfmark/InternalPerfMark.java
Closed https://github.com/grpc/grpc-java/pull/5686, and resubmit with cleaned commit message.
=> core: add accessor for perfmark

SECURITY.md
=> SECURITY.md: Add Fedora 30 package installation instructions

examples/example-tls/README.md, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldClientTls.java, examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldServerTls.java
This back-ports #5715 and #5753. #5715 was included because it fixes the tcnative version specified in gradle.
=> Backport example-tls fixes (v1.21.x)

xds/src/main/java/io/grpc/xds/XdsLbState.java
Temporarily for integration testing.
=> xds: temporarily use ManagedChannelBuilder.forTarget for creating resolving oob channel

netty/src/main/java/io/grpc/netty/NettyServerHandler.java, netty/src/main/java/io/grpc/netty/NettyServerTransport.java, netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java, netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
This reverts commit f94b77c87fc3a559880928dd650e15d43bc00885.  It caused internal breakage and will be rolled forward later.
=> Revert "netty: change server to new protocol negotiator model"

api/src/main/java/io/grpc/ClientCall.java, api/src/main/java/io/grpc/ServerCall.java, stub/src/main/java/io/grpc/stub/CallStreamObserver.java
https://github.com/grpc/grpc-java/issues/1549#issuecomment-496564794 brought up that the documentation didn't really specify what it guaranteed.
CC @ulfjack
=> api,stub: Clarify isReady()/onReady() interaction semantics

xds/src/main/java/io/grpc/xds/XdsLoadBalancer.java, xds/src/test/java/io/grpc/xds/FallbackManagerTest.java
Make the code cleaner. Maybe we will add `STATE_INFO` back some day, but whether and where are uncertain.
=> xds: remove unused variables

core/src/main/java/io/grpc/internal/ServiceConfigUtil.java, core/src/test/java/io/grpc/internal/ServiceConfigUtilTest.java, xds/src/main/java/io/grpc/xds/XdsLoadBalancerProvider.java, xds/src/test/java/io/grpc/xds/XdsLoadBalancerProviderTest.java, xds/src/test/java/io/grpc/xds/XdsLoadBalancerTest.java
=>  xds: fix bug in XdsLoadBalancerProvider.parseLoadBalancingConfigPolicy

xds/build.gradle, xds/third_party/envoy/import.sh, xds/third_party/envoy/src/main/proto/envoy/api/v2/auth/cert.proto, xds/third_party/envoy/src/main/proto/envoy/api/v2/cds.proto, xds/third_party/envoy/src/main/proto/envoy/api/v2/cluster/circuit_breaker.proto, xds/third_party/envoy/src/main/proto/envoy/api/v2/cluster/outlier_detection.proto, xds/third_party/envoy/src/main/proto/envoy/api/v2/core/address.proto, xds/third_party/envoy/src/main/proto/envoy/api/v2/core/base.proto, xds/third_party/envoy/src/main/proto/envoy/api/v2/core/config_source.proto, xds/third_party/envoy/src/main/proto/envoy/api/v2/core/grpc_service.proto, xds/third_party/envoy/src/main/proto/envoy/api/v2/core/health_check.proto, xds/third_party/envoy/src/main/proto/envoy/api/v2/core/protocol.proto, xds/third_party/envoy/src/main/proto/envoy/api/v2/discovery.proto, xds/third_party/envoy/src/main/proto/envoy/api/v2/eds.proto, xds/third_party/envoy/src/main/proto/envoy/api/v2/endpoint/endpoint.proto, xds/third_party/envoy/src/main/proto/envoy/api/v2/endpoint/load_report.proto, xds/third_party/envoy/src/main/proto/envoy/type/percent.proto, xds/third_party/envoy/src/main/proto/envoy/type/range.proto, xds/third_party/gogoproto/LICENSE, xds/third_party/gogoproto/import.sh, xds/third_party/gogoproto/src/main/proto/gogoproto/gogo.proto
The generated grpc services are not changed.
=> xds: Add gogoproto dependency to xds

java_grpc_library.bzl
This avoids re-parsing the proto files and allows proto_library
to enforce more checks.
This is an export of cl/197343148
------
I discovered the incompatibilities with this internally were few and were due to extraneous dependencies. They have been fixed, so this is now safe.
CC @mjduijn
=> java_grpc_library: Swap to descriptor_set_in to protoc

all/build.gradle, build.gradle, cronet/build.gradle, cronet/settings.gradle, examples/gradle/wrapper/gradle-wrapper.properties, gradle/wrapper/gradle-wrapper.properties, okhttp/build.gradle, settings.gradle
=> Upgrade to Gradle 5

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
=> interop-testing: fix tests on Android

xds/src/test/java/io/grpc/xds/LocalityStoreTest.java, xds/src/test/java/io/grpc/xds/XdsLbStateTest.java
The test case `XdsLbStateTest.handleSubchannelState()` was introduced before `LocalityStore` refactored out of `XdsLbState`. After `LocalityStore` refactored out, the test case should not be in `XdsLbStateTest` anymore. The test case is already covered in `LocalityStoreTest`.
=> xds: cleanup XdsLbStateTest

SECURITY.md
See https://en.wikipedia.org/wiki/Cipher_suite
=> Fixing typo in SECURITY.md

alts/src/main/java/io/grpc/alts/internal/TsiFrameHandler.java, alts/src/test/java/io/grpc/alts/internal/TsiFrameHandlerTest.java
gRPC issues flushes after close in the WriteQueue, which can show up as an NPE in the framer.  This was thought to have been handled, by checking to see if there were any pending writes, but if the close() call gets far enough, the writes will be null.    This causes an NPE when the flush comes though.
The issue is difficult to reproduce, and I think my test case emulates the failure.  EmbeddedChannel is different than the normal Channels we use, making the precise ordering tough.  The test case isn't exactly what the production code would do, but it does have the same ordering.
cc @jiangtaoli2016 
Sample Stack trace:
```
Jun 10, 2019 2:09:03 PM io.grpc.ChannelLogger log
FINEST: [OobChannel<10>] Entering SHUTDOWN state
Jun 10, 2019 2:09:03 PM io.grpc.ChannelLogger log
FINEST: …
```
=> alts: handle inline flushes on close in frame handler

interop-testing/src/main/java/io/grpc/testing/integration/TestServiceImpl.java
This reverts commit e795f14bedc56af2f2ba60eef1b23add6106ab99. It breaks some of
our internal tests. At the very least the cast fails because we are reusing the
service for something without going through the normal stub. There may also
have been a test hang, but it'd take more effort to figure out.
=> Revert "interop-testing: Observe flow control in TestServiceImpl"

core/src/main/java/io/grpc/internal/DnsNameResolver.java, core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
=> core: Protect jndi loading against broken classloaders

alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java, alts/src/test/java/io/grpc/alts/internal/AltsProtocolNegotiatorTest.java
Followup to #5893 which causes a server side hang.  This is a hack.
=> alts: fix server hang

examples/BUILD.bazel, examples/README.md, examples/build.gradle, examples/src/main/java/io/grpc/examples/hedging/HedgingHelloWorldClient.java, examples/src/main/java/io/grpc/examples/hedging/HedgingHelloWorldServer.java, examples/src/main/resources/io/grpc/examples/hedging/hedging_service_config.json
See README change for details.
=> examples: hedging example

NOTICE.txt
=> doc: Update NOTICE.txt with gogoproto (backport)

java_grpc_library.bzl
Also fix grammar.
----
Export of cl/257355951 (OCL 257249394)
CC @lberki @mjduijn
=> Make .proto import path computation work with virtual protos in the main repository.

context/src/main/java/io/grpc/Context.java
The `pendingDeadline` variable is modified from the ctor of CancellableContext, but it isn't final.  The cancellation can happen before the variable is assigned.  It's generally bad practice to leak the this reference from the ctor to other threads anyways.
This code refactors the deadline calculation and scheduling so that `pendingDeadline` is modified under the lock, and the `this` reference is not exposed.
Discovered by TSAN.
=> context:  fix race between CancellableContext and cancel

alts/src/main/java/io/grpc/alts/HandshakerServiceChannel.java
=> alts: provide channel type to HandshakerServiceChannel to suppress warning

core/src/main/java/io/grpc/util/GracefulLbSwitch.java, core/src/main/java/io/grpc/util/GracefulSwitchLoadBalancer.java, core/src/test/java/io/grpc/util/GracefulSwitchLoadBalancerTest.java
Following the section "Gracefully Switching LB Policies" in the spec go/grpc-client-channel-spec
=> util: a util to gracefully switch load balancer when lb policy changes

benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadWorker.java, interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyLocalChannelTest.java, netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java, netty/src/main/java/io/grpc/netty/NettyServerBuilder.java, netty/src/test/java/io/grpc/netty/NettyChannelBuilderTest.java, netty/src/test/java/io/grpc/netty/NettyServerBuilderTest.java
includes fix in benchmarks and interop-testing.
resolves #5598
=> netty: Netty{Server,Channel}Builder requires all or none of ELG and ChannelType

core/src/main/java/io/grpc/internal/SharedResourceHolder.java, core/src/test/java/io/grpc/internal/SharedResourceHolderTest.java
Resolves #6002.
Backport of #6044.
=> core: handle removing partially-closed resources for throwing on close. Fixes #6002 (1.23.x backport)

core/src/main/java/io/grpc/internal/SharedResourceHolder.java, core/src/test/java/io/grpc/internal/SharedResourceHolderTest.java
Resolves #6002.
Backport of #6044.
=> core: handle removing partially-closed resources for throwing on close. Fixes #6002 (1.21.x backport)

grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java, grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java, grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
Each new instance of GrpcLbBalancer will have a different pick first index.
=> grpclb: shuffle pick first index

core/src/main/java/io/grpc/internal/GrpcUtil.java, core/src/main/java/io/grpc/internal/JndiResourceResolverFactory.java, core/src/main/java/io/grpc/internal/ManagedChannelImpl.java, core/src/main/java/io/grpc/internal/SharedResourceHolder.java, core/src/test/java/io/grpc/internal/DnsNameResolverProviderTest.java, core/src/test/java/io/grpc/internal/DnsNameResolverTest.java, okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java, okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelProvider.java, okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java, okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/Platform.java
=> removed GrpcUtil.IS_RESTRICTED_APPENGINE and dependent code

context/build.gradle, context/src/main/java/io/grpc/Deadline.java, context/src/test/java/io/grpc/DeadlineTest.java, core/src/main/java/io/grpc/internal/ClientCallImpl.java
Implement equals and hashCode for Deadline
Related issue: https://github.com/grpc/grpc-java/issues/6075
=> context: Implement equals and hashCode for Deadline (grpc#6075)

alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java, alts/src/main/java/io/grpc/alts/internal/TsiHandshakeHandler.java, alts/src/test/java/io/grpc/alts/internal/AltsProtocolNegotiatorTest.java
=> alts: convert TsiHandshakeHandler to implement ProtocolNegotiationHandler

xds/third_party/envoy/import.sh, xds/third_party/envoy/src/main/proto/envoy/api/v2/core/config_source.proto, xds/third_party/envoy/src/main/proto/envoy/api/v2/core/grpc_service.proto
Needed for xDS bootstrap implementation.
=> xds: import proto files for xDS LB bootstrap from upstream envoy repository

xds/src/main/java/io/grpc/xds/LocalityStore.java, xds/src/test/java/io/grpc/xds/LocalityStoreTest.java, xds/src/test/java/io/grpc/xds/XdsLoadBalancerTest.java
Implementing part of
https://docs.google.com/document/d/1fAfdllHJ3JaaKVIdrrBaMnZSHxGAnlx4BhABMQQOn_4/edit#heading=h.a0g231uhufm3
https://docs.google.com/document/d/1pVeKsFhFUuy-trYIGUEtnXBFPx27zSl5L7Ew19KvdF0/edit#heading=h.efc3n4j71930
=> xds: cache locality for 15 minutes

xds/src/main/java/io/grpc/xds/XdsAttributes.java, xds/third_party/envoy/import.sh, xds/third_party/envoy/src/main/proto/envoy/api/v2/auth/cert.proto
Need to define a new attribute so we can plumb SdsSecretConfig from the xDS LB to SSL code so the value can be passed on to the SDS module.
=> Create a new class XdsAttributes in xds to house XDS related attributes and define ATTR_SDS_CONFIG there

netty/src/main/java/io/grpc/netty/NettyServer.java, netty/src/main/java/io/grpc/netty/NettyServerBuilder.java, netty/src/main/java/io/grpc/netty/Utils.java, netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java, netty/src/test/java/io/grpc/netty/NettyServerTest.java, netty/src/test/java/io/grpc/netty/UtilsTest.java
=> netty: Rely on ChannelFactory in NettyServer instead of dynamic classes

examples/README.md, examples/example-kotlin/src/test/kotlin/io/grpc/examples/helloworld/HelloWorldClientTest.kt, examples/src/test/java/io/grpc/examples/helloworld/HelloWorldClientTest.java
=> examples: clarify about potential mistake in unit test

netty/src/main/java/io/grpc/netty/InternalProtocolNegotiators.java, netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java, netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java, netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
=> netty: converts Proxy handler into new protocol negotiation style backport of #6159

netty/src/main/java/io/grpc/netty/InternalProtocolNegotiators.java, netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java, netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java, netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
=> netty: converts Proxy handler into new protocol negotiation style backport of #6159.

android-interop-testing/app/build.gradle, android/build.gradle, build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, cronet/build.gradle, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-kotlin/android/helloworld/app/build.gradle, examples/example-kotlin/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/pom.xml
This reverts commit fa8f89a1a6302088f640c5592db258db5b4f83c2.
=> Revert "Start 1.25.0 development cycle (#6141)"

auth/build.gradle, auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java, build.gradle
=> auth: Avoid com.auth0:java-jwt dependency in test (backport 1.24.x)

.github/ISSUE_TEMPLATE/ask_question.md
it won't be part of actually rendered issue.
=> github: wrap question template in comment blocks

alts/src/main/java/io/grpc/alts/internal/AltsHandshakerClient.java
resolves [grpc/grpc#20384](https://github.com/grpc/grpc/issues/20384)
=> alts: make AltsHandshakerClient#close can be called multiple times

bom/build.gradle
resolves #6219
includes formatting (will rebase)
=> bom: specify pom type for protoc-gen-grpc-java

benchmarks/src/jmh/java/io/grpc/benchmarks/TransportBenchmark.java, benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncServer.java, core/src/main/java/io/grpc/internal/JndiResourceResolverFactory.java
Error Prone 2.1.2 removed the warning.
=> Remove vestigial SuppressWarnings("LiteralClassName")

xds/src/main/java/io/grpc/xds/sds/SecretManager.java, xds/src/main/java/io/grpc/xds/sds/SecretProvider.java, xds/src/main/java/io/grpc/xds/sds/SecretProviderMap.java, xds/src/main/java/io/grpc/xds/sds/TlsCertificateSecretProviderMap.java, xds/src/main/java/io/grpc/xds/sds/TlsCertificateSecretVolumeSecretProvider.java, xds/src/main/java/io/grpc/xds/sds/TlsCertificateStore.java, xds/src/test/java/io/grpc/xds/sds/SecretManagerTest.java, xds/src/test/java/io/grpc/xds/sds/TlsCertificateSecretProviderMapTest.java, xds/src/test/java/io/grpc/xds/sds/TlsCertificateSecretVolumeSecretProviderTest.java, xds/src/test/java/io/grpc/xds/sds/TlsCertificateStoreTest.java
Implementation of the SecretManager that will be used eventually for SDS implementation i.e. to fetch certs from the control plane
=> SecretManager implementation for file secrets

xds/src/main/java/io/grpc/xds/XdsAttributes.java, xds/src/main/java/io/grpc/xds/sds/SecretProvider.java
Needed for passing those values to the Sds component (channel and server builders)
Also address comments in a previous PR
=> Add tlsCertificate and certificateValidationContext to XdsAttributes

api/src/main/java/io/grpc/LoadBalancer.java, api/src/test/java/io/grpc/LoadBalancerTest.java
If a `LoadBalancer` implementation does not override `handleResolvedAddressGroups()`, or overrides `handleResolvedAddressGroups()` but calls `super.handleResolvedAddressGroups()` at the beginning or the end, it will be trapped in an infinite loop.
=> api: avoid infinite loop in handleResolvedAddresses

bom/build.gradle
related to #6243
backport to v1.22.x
=> bom: specify pom type for protoc-gen-grpc-java (backport of #6220)

xds/src/main/java/io/grpc/xds/sds/TlsContextManager.java
This unblocks other PRs related to implementation of TlsContextManager and SdsProtocolNegotiators using the TlsContextManager
=> xds: define interface for the new TlsContextManager that will replace the SecretManager

api/src/main/java/io/grpc/ForwardingChannelBuilder.java, api/src/main/java/io/grpc/ManagedChannelBuilder.java, core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java, cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java, netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java, okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
=> all: remove deprecated usePlaintext(boolean)

xds/src/main/java/io/grpc/xds/sds/trust/SdsX509TrustManager.java
There are couple minor issues caught during the import.
e.g. Protobuf fields cannot be null.
=> xds: clean up.

api/src/main/java/io/grpc/MethodDescriptor.java, api/src/test/java/io/grpc/MethodDescriptorTest.java
=> api: Allow streaming methods to be safe

compiler/BUILD.bazel
=> bazel: Add compatibility for --incompatible_load_cc_rules_from_bzl

api/src/main/java/io/grpc/MethodDescriptor.java, api/src/test/java/io/grpc/MethodDescriptorTest.java
=> api: Safe implies idempotent

api/src/main/java/io/grpc/MethodDescriptor.java
=> api: Clarify setting safe/idempotent may change other value

xds/src/generated/main/grpc/io/envoyproxy/envoy/api/v2/ScopedRoutesDiscoveryServiceGrpc.java, xds/third_party/envoy/import.sh, xds/third_party/envoy/src/main/proto/envoy/api/v2/srds.proto, xds/third_party/envoy/src/main/proto/envoy/config/filter/accesslog/v2/accesslog.proto, xds/third_party/envoy/src/main/proto/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto
Import `http_connection_manager.proto` (and its dependencies) from envoy repo. `HttpConnectionManager` is the bridging config between LDS and RDS.
=> xds: import http_connection_manager proto from envoy repo

examples/src/main/java/io/grpc/examples/advanced/HelloJsonClient.java, examples/src/main/java/io/grpc/examples/experimental/CompressingHelloWorldClient.java, examples/src/main/java/io/grpc/examples/header/CustomHeaderClient.java, examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java
=> examples: adjust comment

build.gradle, examples/pom.xml, grpclb/build.gradle, repositories.bzl, services/build.gradle, xds/build.gradle
=> xds: Bump perfmark

build.gradle, examples/pom.xml, grpclb/build.gradle, repositories.bzl, services/build.gradle, xds/build.gradle
=> all: Bump perfmark to 0.19.0 (backport to v1.24.x)

build.gradle, examples/pom.xml, grpclb/build.gradle, repositories.bzl, services/build.gradle, xds/build.gradle
=> all: Bump perfmark to 0.19.0 (backport to v1.23.x)

netty/src/main/java/io/grpc/netty/NettyServerTransport.java, netty/src/test/java/io/grpc/netty/NettyServerTransportTest.java, okhttp/src/main/java/io/grpc/okhttp/ExceptionHandlingFrameWriter.java, okhttp/src/test/java/io/grpc/okhttp/ExceptionHandlingFrameWriterTest.java
=> netty,okhttp: log FINE level for pure IOExceptions when transport terminated

xds/src/main/java/io/grpc/xds/XdsClient.java
Since @dapengzhang0 and @voidzcy will be working on different parts of the implementation underneath the `XdsClient`, it would be easier to have a commonly agreed interface defined upfront. This is a skeleton only, to show how each part underneath the `XdsClient` would integrate with each other.
This PR is similar to https://github.com/grpc/grpc/pull/20236. 
/cc @zhangkun83 and @ejona86
=> xds: define XdsClient interface

examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlServer.java
=> examples: add missing annotation

xds/src/main/java/io/grpc/xds/sds/ReferenceCountingSslContextProviderMap.java, xds/src/main/java/io/grpc/xds/sds/SecretVolumeSslContextProvider.java, xds/src/main/java/io/grpc/xds/sds/SslContextProvider.java, xds/src/test/java/io/grpc/xds/sds/ReferenceCountingSslContextProviderMapTest.java
=> xds: reference counting map for SslContextProvider needed for TlsContextManager

benchmarks/build.gradle, interop-testing/build.gradle
=> interop-testing,benchmarks: publish tar, zip

benchmarks/build.gradle, interop-testing/build.gradle
=> interop-testing,benchmarks: publish tar, zip (backport of #6369)

alts/src/main/java/io/grpc/alts/ComputeEngineChannelBuilder.java
=> alts: fix ComputeEngineChannelBuilder class signature

alts/src/main/java/io/grpc/alts/internal/AesGcmAeadCrypter.java
This is a backport of #6372
CC @zhangkun83
=> alts: Check Cipher before declaring Conscrypt working (v1.25.x backport)

netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java, netty/src/main/java/io/grpc/netty/KeepAliveEnforcer.java, netty/src/main/java/io/grpc/netty/NettyServerBuilder.java, netty/src/main/java/io/grpc/netty/NettyServerHandler.java, netty/src/test/java/io/grpc/netty/NettyServerBuilderTest.java
=> netty: unified log prompt

xds/src/main/java/io/grpc/xds/LocalityStore.java
Cleanup as per the review comment https://github.com/grpc/grpc-java/pull/6371#discussion_r343844969
=> xds: not use Immutable collections in method signature

netty/src/main/java/io/grpc/netty/KeepAliveEnforcer.java, netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java, netty/src/main/java/io/grpc/netty/NettyServerBuilder.java, netty/src/main/java/io/grpc/netty/NettyWritableBufferAllocator.java
Modifying some definitions improves readability
=> netty: improve readability

compiler/build.gradle
Adding support for s390x .
Please review
=> Adding s390x support to grpc-java

xds/build.gradle, xds/src/main/java/io/grpc/xds/sds/SdsClient.java, xds/src/test/java/io/grpc/xds/sds/SdsClientTest.java, xds/src/test/java/io/grpc/xds/sds/SdsClientUdsTest.java, xds/src/test/java/io/grpc/xds/sds/TestSdsServer.java
temporary implementation until merged with XdsClient
=> xds: implementation of SdsClient to be used by SDS based SslContextProviders 

netty/src/main/java/io/grpc/netty/Utils.java
This would cut the amount of per-thread direct buffer allocations by half, especially with light traffic. This will also cut the amount of file descriptors that's created per thread by half.
Internal benchmark results (median of 5 runs) doesn't show any significant change:
```
Before (STDEV)           After (STDEV)
grpc-java-java-multi-qps-integrity_only
Actual QPS               711,004 (6,246)         704,372 (6,873) 
QPS per Client CPU        23,921   (252)          24,188   (252)
grpc-java-java-multi-throughput-integrity_only
Actual QPS                35,326    (48)          35,294    (29) 
QPS per Client CPU         3,362    (17)           3,440    (13)
grpc-java-java-single-latency-integrity_only
Median latency (us)          127  (2.77)             129  (3.13) …
```
=> netty: reduce default worker ELG thread number from 2x to 1x of CPU cores

cronet/build.gradle
=> cronet: disable code shrinking for library build

cronet/build.gradle
Resolves #6447.
Backports #6448.
=> cronet: disable code shrinking for library build (backport of #6448)

netty/src/main/java/io/grpc/netty/NettyServerTransport.java, netty/src/test/java/io/grpc/netty/NettyServerTransportTest.java
=> netty: log NativeIoException as FINE level

xds/src/main/java/io/grpc/xds/LookasideLb.java
Fix build failure of 96da68bab3338b350cd79ed48c225a366b37ff6a
https://travis-ci.org/grpc/grpc-java/builds/620854037?utm_source=github_status&utm_medium=notification
=> xds: fix build

xds/src/main/java/io/grpc/xds/FallbackLb.java
Apply the same error handling for `FallbackLb.handleResolvedAddresses()` as `LookasideLb` and `CdsLoadBalancer`.
=> xds: apply error handling for FallbackLb.handleResolvedAddresses

xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java, xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java
@dapengzhang0 pls check as per our discussion.
=> xds: set UpstreamTlsContext in Attributes

netty/src/main/java/io/grpc/netty/NettyServer.java, netty/src/main/java/io/grpc/netty/ProtocolNegotiator.java, netty/src/test/java/io/grpc/netty/NettyServerTest.java
CC @jiangtaoli2016 @ZhenLian. Note that without this ALTS Server leaked its Channel
=> netty: NettyServer should close ProtocolNegotiator

xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java, xds/src/main/java/io/grpc/xds/LookasideLb.java
Channel logger uses the same message format as java util logger's.
=> xds: fix log format bug

xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java, xds/src/main/java/io/grpc/xds/LookasideLb.java
=> xds: fix logging message format bug again

context/src/main/java/io/grpc/Context.java
=> Update javadoc for withValue(s) to indicate withValue can be chained

.travis.yml, RELEASING.md, buildscripts/kokoro/unix.sh, examples/example-hostname/BUILD.bazel, examples/example-hostname/README.md, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-hostname/settings.gradle, examples/example-hostname/src/main/java/io/grpc/examples/hostname/HostnameGreeter.java, examples/example-hostname/src/main/java/io/grpc/examples/hostname/HostnameServer.java, examples/example-hostname/src/main/proto/helloworld/helloworld.proto, examples/example-hostname/src/test/java/io/grpc/examples/hostname/HostnameGreeterTest.java, services/BUILD.bazel
This is placed in its own directory since it depends on grpc-services.
--------
This example is intended to be used in documentation demonstrating load balancing, for example with XDS.
CC @donnadionne, @menghanl, y'all can comment since we'll create something like this for the other languages as well.
=> examples: Add hostname example

xds/src/main/java/io/grpc/xds/XdsNameResolver.java, xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
The change also fixed small typos in test.
=> xds: fix bug of xDS resolver parsing service config incorrectly

core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java, core/src/main/java/io/grpc/internal/ManagedChannelImpl.java, core/src/main/java/io/grpc/internal/OobChannel.java, core/src/main/java/io/grpc/internal/PickFirstLoadBalancer.java, core/src/main/java/io/grpc/util/GracefulSwitchLoadBalancer.java, core/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java, core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java, grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java, xds/src/main/java/io/grpc/xds/ClientLoadCounter.java
Let `ManagedChannelImpl` log picker update when updating balancing state. (https://github.com/grpc/grpc-java/compare/master...dapengzhang0:log-picker?expand=1#diff-354509714620f5c493a6810aab9419f2R1156)
=> all: log picker when updating balancing state

xds/src/main/java/io/grpc/xds/XdsClientImpl.java, xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
According to the [latest spec](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#how-the-client-specifies-what-resources-to-return), management server is able to handle client unsubscribing last CDS resource. Previously, an empty list of resources triggers "wildcard" mode, so we had special logic on client side to avoid sending that request. Now, this logic is no longer needed.
=> xds: remove special logic for unsubscribing last CDS resource

xds/src/main/java/io/grpc/xds/LookasideLb.java, xds/src/main/java/io/grpc/xds/XdsLoadBalancer2.java, xds/src/test/java/io/grpc/xds/LookasideLbTest.java, xds/src/test/java/io/grpc/xds/XdsLoadBalancer2Test.java
This reverts commit a223263134c2bd4bf97b943bc52a0a128bc67268 to unblock import.
=> Revert "xds: better error handling to avoid RPC hangup"

xds/src/main/java/io/grpc/xds/EdsLoadBalancer.java, xds/src/main/java/io/grpc/xds/EdsLoadBalancerProvider.java, xds/src/main/java/io/grpc/xds/LoadStatsStore.java, xds/src/main/java/io/grpc/xds/XdsLoadBalancer.java, xds/src/main/java/io/grpc/xds/XdsLoadBalancerProvider.java, xds/src/test/java/io/grpc/xds/EdsLoadBalancerTest.java, xds/src/test/java/io/grpc/xds/XdsLoadBalancerTest.java
This is a follow up cleanup of #6656 .
=> xds: rename LookasideLb to EdsLoadBalancer and XdsLoadBalancer2 to XdsLoadBalancer

context/src/test/java/io/grpc/ContextTest.java, stub/src/test/java/io/grpc/stub/ServerCallsTest.java
=> context, stub: check result of CountDownLatch.await() in test

README.md, cronet/README.md, documentation/android-channel-builder.md
=> Update README etc to reference 1.27.0

examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlClient.java, examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlServer.java
=> Fix typo in comments

build.gradle, gae-interop-testing/gae-jdk8/build.gradle, repositories.bzl
Addressing Issue https://github.com/grpc/grpc-java/issues/6725
=> Updating okhttp version from 2.5.0 to 2.7.4 to fix [CVE-2016-2402]

build.gradle, repositories.bzl
=> deps: update Truth and JUnit

api/src/main/java/io/grpc/ClientStreamTracer.java, api/src/main/java/io/grpc/LoadBalancerProvider.java
=> api: fix Javadoc warnings

RELEASING.md
=> RELEASING.md: update mac build version

android-interop-testing/app/build.gradle, android/build.gradle, android/src/test/java/io/grpc/android/AndroidChannelBuilderTest.java, examples/android/clientcache/app/build.gradle
=> android: Annotate tests to use Robolectric's LEGACY LooperMode. bump roboletric to 4.3.1, truth to 1.0.1 and sdk to 28.

build.gradle, repositories.bzl
=> deps: update guava to 28.2

xds/src/main/java/io/grpc/xds/XdsRoutingLoadBalancer.java, xds/src/main/java/io/grpc/xds/XdsRoutingLoadBalancerProvider.java, xds/src/main/resources/META-INF/services/io.grpc.LoadBalancerProvider, xds/src/test/java/io/grpc/xds/XdsRoutingLoadBalancerProviderTest.java
Implement xds_routing config part of go/grpc-xds-traffic-splitting-and-path-matching
=> xds: implement XdsRouting config parser

xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java, xds/src/main/java/io/grpc/xds/EdsLoadBalancer.java, xds/src/main/java/io/grpc/xds/FallbackLb.java, xds/src/main/java/io/grpc/xds/XdsLoadBalancerProvider.java, xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java, xds/src/test/java/io/grpc/xds/EdsLoadBalancerTest.java, xds/src/test/java/io/grpc/xds/FallbackLbTest.java, xds/src/test/java/io/grpc/xds/XdsLoadBalancerProviderTest.java
This is needed for the ongoing refactor of EdsLoadBalancer.
=> xds: refactor XdsConfig to use PolicySelection

all/build.gradle, xds/build.gradle
This will fix reporting of xDS code coverage.
CC @voidzcy
=> all: Add grpc-xds

all/build.gradle, grpclb/build.gradle, services/build.gradle
This adds to the published JavaDoc and reported code coverage.
=> all: Add more projects to the all super-project

stub/src/main/java/io/grpc/stub/ClientCalls.java, stub/src/test/java/io/grpc/stub/ClientCallsTest.java
=> stub: add Blocking StubType to blocking ClientCalls methods.

netty/src/main/java/io/grpc/netty/Utils.java
For debugging issues like #6926
=> netty: log the selection of allocators

context/src/main/java/io/grpc/Context.java
Lazy initialize the parentListener to optimize for the case when the Context does not have any CancellationListener.
=> Lazy initialize the parentListener in Context.

api/src/main/java/io/grpc/LoadBalancer.java
Update renamed components and references to deprecated APIs.
=> core: refine LoadBalancer javadoc

context/src/main/java/io/grpc/Context.java, context/src/test/java/io/grpc/ContextTest.java
Currently the logic of cancellation is split between Context and CancellableContext where some of the logic related to "isCancelled" lives in the CancellableContext, and some of the logic related to listeners added lives in "Context".
This PR ensures that the entire logic related to cancellation lives in one place (CancellableContext) and ensures clear separation of concerns, here are some benefits:
* Clear ownership of the listeners and cancellation property.
* Reduce the size of the Context object (2 empty pointers).
Because the list of listeners is shared between all child Contexts of a "CancellableContext" it may increases contention and slows the linear scanning during removal, but it seems like it won't be a problem because listeners seem to be rare, so 0→1 and 1→0 transitions …
=> Move everything related to cancellation to CancellableContext.

README.md, build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, cronet/README.md, documentation/android-channel-builder.md, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-kotlin/android/helloworld/app/build.gradle, examples/example-kotlin/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/README.md, examples/example-xds/build.gradle, examples/pom.xml
=> Release 1.29.0

buildscripts/kokoro/xds.sh
Added in https://github.com/grpc/grpc/pull/22538
=> buildscripts: use xds-test-server image

README.md
=> README.md: fix version typo

README.md
=> README.md: fix version typo (backport of #6976)

core/src/main/java/io/grpc/internal/ManagedChannelServiceConfig.java, core/src/main/java/io/grpc/internal/ServiceConfigInterceptor.java, core/src/test/java/io/grpc/internal/ManagedChannelServiceConfigTest.java, core/src/test/java/io/grpc/internal/ServiceConfigInterceptorTest.java, core/src/test/java/io/grpc/internal/ServiceConfigStateTest.java
References:
service config spec change: https://github.com/grpc/grpc-proto/pull/75
c-core implementation https://github.com/grpc/grpc/pull/22232
=> core: support default method config in service config

core/src/main/java/io/grpc/internal/PickSubchannelArgsImpl.java, rls/build.gradle, rls/src/main/java/io/grpc/rls/internal/CachingRlsLbClient.java, rls/src/main/java/io/grpc/rls/internal/RlsProtoData.java, rls/src/main/java/io/grpc/rls/internal/Throttler.java, rls/src/test/java/io/grpc/rls/internal/CachingRlsLbClientTest.java, rls/src/test/java/io/grpc/rls/internal/RlsRequestFactoryTest.java
the ASYNC_LOOKUP_DEFAULT_TARGET_ON_MISS will be removed via https://github.com/grpc/grpc-proto/pull/77. that is reflected here.
=> rls: caching rls client

xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java, xds/src/main/java/io/grpc/xds/internal/sds/SdsProtocolNegotiators.java, xds/src/main/java/io/grpc/xds/internal/sds/ServerWrapperForXds.java, xds/src/main/java/io/grpc/xds/internal/sds/XdsServerBuilder.java, xds/src/test/java/io/grpc/xds/XdsClientWrapperForServerSdsTest.java, xds/src/test/java/io/grpc/xds/XdsClientWrapperForServerSdsTestMisc.java, xds/src/test/java/io/grpc/xds/XdsSdsClientServerTest.java, xds/src/test/java/io/grpc/xds/XdsServerBuilderTest.java, xds/src/test/java/io/grpc/xds/internal/sds/SdsProtocolNegotiatorsTest.java
@ejona86 PR for the server-wrapper we discussed the other day
=> xds: create XdsServer wrapper for correct start and shutdown semantics

xds/third_party/envoy/import.sh, xds/third_party/envoy/src/main/proto/envoy/config/filter/fault/v2/fault.proto, xds/third_party/envoy/src/main/proto/envoy/config/filter/http/fault/v2/fault.proto, xds/third_party/udpa/import.sh
also, make import scripts to run within repo, clean up tempfiles when
exit with error.
=> xds: import fault injection xds proto

buildscripts/kokoro/linux_artifacts.cfg, buildscripts/kokoro/macos.cfg, buildscripts/kokoro/unix.sh, buildscripts/kokoro/upload_artifacts.sh, buildscripts/kokoro/windows.cfg, core/build.gradle, examples/example-hostname/build.gradle
The release script itself is untested, but I have tested the individual components. ~I'm going to check the CI results to make sure they look right.~ The artifact output of linux_artifacts looks correct.
=> Automate release process for example-hostname

repositories.bzl, rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java, rls/src/main/java/io/grpc/rls/LbPolicyConfiguration.java, rls/src/main/java/io/grpc/rls/RlsProtoConverters.java, rls/src/main/java/io/grpc/rls/RlsProtoData.java, rls/src/main/proto/grpc/lookup/v1/rls.proto, rls/src/main/proto/grpc/lookup/v1/rls_config.proto, rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java, rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java, rls/src/test/java/io/grpc/rls/RlsProtoConvertersTest.java, rls/src/test/java/io/grpc/rls/RlsRequestFactoryTest.java
the deprecated fields in this import will be removed shortly. update related code
=> rls: update proto

xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java, xds/src/main/java/io/grpc/xds/PriorityLoadBalancerProvider.java, xds/src/test/java/io/grpc/xds/PriorityLoadBalancerProviderTest.java, xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java
See details in refactoring design docs. Not including address filter yet.
=> xds: implement priority lb

README.md
Minor edit to fix a couple of broken URLs in readme.
=> README.md: Fixed broken documentation links in readme for quick-start and basics.

build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
This reverts commit 0865c74a8329de954f6b2a2cb30ef2c7f808c0cc.
=> Revert "Start 1.31.0 development cycle"

all/build.gradle
=> all: remove grpc-rls from grpc-all dependencies

xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java, xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java
=> xds: disable processing of UpstreamTlsContext in 1.30.x release branch

RELEASING.md
=> doc: config.toml changed to config.yaml in grpc.io

core/src/main/java/io/grpc/internal/AbstractStream.java, okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
=> core: disable MigratingThreadDeframer

build.gradle, examples/android/clientcache/build.gradle, examples/android/helloworld/build.gradle, examples/android/routeguide/build.gradle, examples/android/strictmode/build.gradle, examples/gradle/wrapper/gradle-wrapper.properties, gradle/wrapper/gradle-wrapper.properties
Fixes https://github.com/grpc/grpc-java/issues/7006
=> Upgrade to Gradle 6.5.1

android-interop-testing/src/main/java/io/grpc/android/integrationtest/InteropTask.java, core/src/main/java/io/grpc/internal/AbstractStream.java, core/src/main/java/io/grpc/internal/MigratingThreadDeframer.java, gae-interop-testing/gae-jdk8/src/main/java/io/grpc/testing/integration/NettyClientInteropServlet.java, interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java, interop-testing/src/main/java/io/grpc/testing/integration/StressTestClient.java, interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java, interop-testing/src/test/java/io/grpc/testing/integration/AutoWindowSizingOnTest.java, interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyLocalChannelTest.java, interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java, interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java, interop-testing/src/test/java/io/grpc/testing/integration/InProcessTest.java, interop-testing/src/test/java/io/grpc/testing/integration/TransportCompressionTest.java
Fixes #7168
-----
I plan to keep the two commits separate when merging.
=> core: Fix migrating deframer compatibility with RetriableStream

xds/src/main/java/io/grpc/xds/internal/certprovider/CertificateProviderStore.java, xds/src/test/java/io/grpc/xds/internal/certprovider/CertificateProviderStoreTest.java
=> xds: fix lint

api/src/main/java/io/grpc/InternalConfigSelector.java, api/src/test/java/io/grpc/InternalConfigSelectorTest.java
Apparently the change in ManagedChannelImpl for ConfigSelector will be complex, so I split out small PRs first.
=> api: add InternalConfigSelector abstract class

buildscripts/kokoro/xds.sh, interop-testing/src/main/java/io/grpc/testing/integration/XdsTestClient.java, interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java, interop-testing/src/main/proto/grpc/testing/messages.proto
Backport of https://github.com/grpc/grpc-java/pull/7207 and https://github.com/grpc/grpc-java/pull/7254 (will be merged as two commits)
=> Backport to v1.31.x of xDS header and path matching test support

xds/src/main/java/io/grpc/xds/XdsClientImpl.java, xds/src/test/java/io/grpc/xds/XdsClientImplTest.java, xds/src/test/java/io/grpc/xds/XdsClientTestHelper.java, xds/src/test/java/io/grpc/xds/XdsNameResolverIntegrationTest.java
=> xds: remove GRPC_XDS_EXPERIMENTAL_ROUTING flag (backport v1.31.x)

README.md
Re: https://github.com/grpc/grpc-java/issues/7244
=> Update minimum Android API in README

xds/src/main/java/io/grpc/xds/XdsClientImpl.java
In preparation of xds-v3 support.
=> xds: refactor AdsStream to envoy-proto-and-version-agnostic AbstractAdsStream

benchmarks/build.gradle, build.gradle, buildscripts/kokoro/upload_artifacts.sh, gae-interop-testing/gae-jdk8/build.gradle, interop-testing/build.gradle, settings.gradle, testing-proto/build.gradle
Each commit will be merged separately.
=> Gradle 6-driven updates

examples/README.md
- Update links into grpc.io (contributes to https://github.com/grpc/grpc.io/issues/362)
- A few copy edits
(Best reviewed by ignoring changes in whitespace. VS Code trims off trailing whitespace.)
@ejona86
=> examples/README: update links into grpc.io Java pages

xds/build.gradle
=> xds: shade the meshCA proto generated code

benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncClient.java
It's a lot of code and there are classes in Guava are better. This was noticed
with a lint checker. This commit does change the error-handling behavior, as
previous the code wrongly cancelled the Future instead of setting it to have an
exception.
------
CC @zhangkun83
=> benchmarks: Avoid implementing Future

xds/build.gradle, xds/src/generated/main/grpc/com/google/security/meshca/v1/MeshCertificateServiceGrpc.java, xds/third_party/istio/import.sh, xds/third_party/istio/src/main/proto/security/proto/providers/google/meshca.proto
completely fixes https://github.com/grpc/grpc-java/issues/7289
=> xds: get the correct meshca.proto version that has the needed Java annotations

examples/android/clientcache/build.gradle, examples/android/helloworld/build.gradle, examples/android/routeguide/build.gradle, examples/android/strictmode/build.gradle
=> examples: add mavenCentral for android example's dependency repository

xds/src/test/java/io/grpc/xds/internal/certprovider/MeshCaCertificateProviderTest.java
=> xds: replace mock(ScheduledFuture) with a TestScheduledFuture implementation

SECURITY.md, build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, repositories.bzl
=> Upgrade to Netty 4.1.51 and tcnative 2.0.31

xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java, xds/src/main/java/io/grpc/xds/internal/sds/ServerWrapperForXds.java, xds/src/main/java/io/grpc/xds/internal/sds/XdsServerBuilder.java, xds/src/test/java/io/grpc/xds/XdsClientWrapperForServerSdsTest.java, xds/src/test/java/io/grpc/xds/XdsClientWrapperForServerSdsTestMisc.java, xds/src/test/java/io/grpc/xds/XdsSdsClientServerTest.java, xds/src/test/java/io/grpc/xds/XdsServerBuilderTest.java, xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java
CC @ejona86 xds server start semantics as per the discussion/design
=> xds: add server start semantics as per the server api design

README.md, build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, cronet/README.md, documentation/android-channel-builder.md, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
Take two! This time #7407 avoiding issues in the release.
=> Release v1.32.1

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
Re-organization based on https://github.com/grpc/grpc-java/pull/7413#issuecomment-690756200
=> core: re-organize RealChannel with updateConfigSelector()

alts/src/main/java/io/grpc/alts/internal/AltsChannelCrypter.java
As an alternative of #7411, let's remove the existing workaround only which was devised to address the performance problem with Conscrypt prior to 2.5.0. Users need to upgrade Conscrypt to 2.5.0 or later to benefit all optimization.
=> Removing a temporary workaround for Conscrypt performance with ALTS (v1.32.x)

xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java, xds/src/main/java/io/grpc/xds/EdsLoadBalancer2.java, xds/src/main/java/io/grpc/xds/XdsClient.java, xds/src/main/java/io/grpc/xds/XdsClientImpl.java, xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java, xds/src/test/java/io/grpc/xds/EdsLoadBalancer2Test.java, xds/src/test/java/io/grpc/xds/XdsClientImplTest.java, xds/src/test/java/io/grpc/xds/XdsClientImplTestV2.java
This is just tedious renaming.
=> xds: rename CDS/EDS resource watch interface

xds/src/main/java/io/grpc/xds/EdsLoadBalancer2.java, xds/src/test/java/io/grpc/xds/EdsLoadBalancer2Test.java
This fixes error handling when TD sends `ClusterLoadAssignment` with no endpoint.
Existing way: the EDS LB policy propagates a TRANSIENT_ERROR to its parent LB policy and leave downstream LB policies running.
- If later receives another EDS response with exactly the same endpoints as previous EDS response, the downstream LB policies will just treat it as duplicated update and no working picker will be propagated up.
Fixed way: the EDS LB policy shuts down its downstream LB policies and then propagates a TRANSIENT_ERROR to its parent LB policy.
Observed failure:
https://g3c.corp.google.com/results/invocations/f0e05503-5bf7-4ac9-8b6c-6acd98943d00/targets/github%2Fgrpc%2Freports%2Fround_robin;config=default/tests
=> xds: shut down EDS downstream LB policies when no usable endpoints received

netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java, netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
Normally the first exception/event experienced is the cause and is
followed by a stampede of ClosedChannelExceptions. In this case,
SslHandler is manufacturing a ClosedChannelException of its own and
propagating it _before_ the trigger event. This might be considered a
bug, but changing SslHandler's behavior would be very risky and almost
certainly break someone's code.
Fixes #7376
CC @ahjohannessen
=> netty: TCP close during TLS handshake should be UNAVAILABLE

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java, rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
When picking subchannel, if the lookup request fails inline 
(https://github.com/grpc/grpc-java/blob/v1.31.0/rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java#L881-L882),
it will try to use fallback and the RPC will return an error status if fallback is also failing, which is correct behavior;
but if the lookup request eventually fails but not instantaneously failing (
https://github.com/grpc/grpc-java/blob/v1.31.0/rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java#L884
https://github.com/grpc/grpc-java/blob/v1.31.0/rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java#L188
https://github.com/grpc/grpc-java/blob/v1.31.0/rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java#L405),
the RLS lb will not update the channels state or trying to use fallback, and the client RPC is hanging. …
=> rls: fix RPC hanging if lookup request fails

xds/src/main/java/io/grpc/xds/LoadReportClient.java, xds/src/main/java/io/grpc/xds/XdsClientImpl2.java, xds/src/test/java/io/grpc/xds/LoadReportClientTest.java
=> xds: synchronize LoadReportClient operations with lock

interop-testing/src/generated/main/grpc/io/grpc/testing/integration/LoadBalancerStatsServiceGrpc.java, interop-testing/src/generated/main/grpc/io/grpc/testing/integration/XdsUpdateClientConfigureServiceGrpc.java, interop-testing/src/main/proto/grpc/testing/messages.proto, interop-testing/src/main/proto/grpc/testing/test.proto
Mirror of https://github.com/grpc/grpc/pull/24435
=> interop-testing: add proto definitions for xDS circuit breaking test

xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
=> xds: promote ServerXdsClient

xds/src/test/java/io/grpc/xds/internal/sds/trust/SdsX509TrustManagerTest.java
=> xds: re-add tests removed from a previous PR for v3 support

MAINTAINERS.md
Might be needed for https://issues.sonatype.org/browse/OSSRH-61680
=> Add sergiitk to MAINTAINERS.md

xds/src/main/java/io/grpc/xds/internal/certprovider/CertificateProviderRegistry.java, xds/src/main/java/io/grpc/xds/internal/certprovider/DynamicReloadingCertificateProviderProvider.java, xds/src/main/java/io/grpc/xds/internal/certprovider/FileWatcherCertificateProviderProvider.java, xds/src/main/java/io/grpc/xds/internal/certprovider/MeshCaCertificateProviderProvider.java
=> xds: replace static initializers with hardcoded registration of 3 cert providers

xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
=> xds: use 0.0.0.0 in the resource query for LDS

xds/src/test/java/io/grpc/xds/SharedCallCounterMapTest.java
`GcFinalization.awaitClear()` only guarantees the reference is cleared but no guarantee for the ref is enqueued. This could cause race for calling `cleanQueue()` in the test.
This should fix the flakiness for recent CI failures in `SharedCallCounterMapTest.autoCleanUp()`.
=> xds: use GC finalization predicate to avoid race between ref enqueued and calling cleanQueue()

netty/src/main/java/io/grpc/netty/InternalNettyServerBuilder.java, netty/src/main/java/io/grpc/netty/NettyServer.java, netty/src/main/java/io/grpc/netty/NettyServerBuilder.java, netty/src/main/java/io/grpc/netty/NettyServerHandler.java, netty/src/main/java/io/grpc/netty/NettyServerTransport.java, netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java, netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java, netty/src/test/java/io/grpc/netty/NettyServerTest.java, xds/src/main/java/io/grpc/xds/XdsServerBuilder.java, xds/src/main/java/io/grpc/xds/internal/sds/SdsProtocolNegotiators.java, xds/src/test/java/io/grpc/xds/XdsSdsClientServerTest.java, xds/src/test/java/io/grpc/xds/XdsServerBuilderTest.java
I'd like the Netty change to make it before the branch cut. The Xds change could come later if need be.
Yes, we'll get to coordinate this change with other XdsServerBuilder changes.
=> netty,xds: Plumb XdsClientWrapperForServerSds via eagAttributes

xds/src/main/java/io/grpc/xds/EdsLoadBalancer2.java, xds/src/test/java/io/grpc/xds/EdsLoadBalancer2Test.java
Should not merge until https://github.com/grpc/grpc/pull/24779 gets in.
=> xds: gate xDS circuit breaking feature with environment variable

android-interop-testing/src/generated/debug/grpc/io/grpc/testing/integration/LoadBalancerStatsServiceGrpc.java, android-interop-testing/src/generated/debug/grpc/io/grpc/testing/integration/XdsUpdateClientConfigureServiceGrpc.java, android-interop-testing/src/generated/debug/grpc/io/grpc/testing/integration/XdsUpdateHealthServiceGrpc.java, android-interop-testing/src/generated/release/grpc/io/grpc/testing/integration/LoadBalancerStatsServiceGrpc.java, android-interop-testing/src/generated/release/grpc/io/grpc/testing/integration/XdsUpdateClientConfigureServiceGrpc.java, android-interop-testing/src/generated/release/grpc/io/grpc/testing/integration/XdsUpdateHealthServiceGrpc.java
Update checked-in proto generated services for changes made in #7545.
=> interop-testing: update proto generated service files

alts/src/main/java/io/grpc/alts/internal/TsiHandshakeHandler.java
=> alts: Limit number of concurrent handshakes to 32

alts/src/main/java/io/grpc/alts/internal/TsiHandshakeHandler.java
=> alts: Limit number of concurrent handshakes to 32 (1.34.x backport)

api/src/main/java/io/grpc/LoadBalancer.java
Javadoc was messed up by #7748
=> api: fix LoadBalancer javadoc

api/src/main/java/io/grpc/LoadBalancer.java
=> api: fix LoadBalancer javadoc (back port v1.35.x)

netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java, netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
This reverts commit 9bc05fba67b709d1e816f47c462b22d976194cca.
----------------
Tests are broken https://travis-ci.org/github/grpc/grpc-java/jobs/753603250. Might be related to recent Netty upgrade. Reverting it for now.
/cc @ericgribkoff @huangqiangxiong
=> Revert "netty: add exporting SSL/TLS master key log feature (#7724)"

xds/src/test/java/io/grpc/xds/ClusterManagerLoadBalancerTest.java
Stylish things in tests. Make test units small and test one thing a time.
=> xds: slightly refactor and improve tests for cluster_manager LB policy

interop-testing/src/main/java/io/grpc/testing/integration/TestServiceServer.java
=> Revert "interop-testing: allow multiple port in test server"

xds/src/main/java/io/grpc/xds/CdsLoadBalancerProvider.java, xds/src/test/java/io/grpc/xds/CdsLoadBalancerProviderTest.java
This migrates to the new LB hierarchy of CDS -> cluster_resolver -> priority -> cluster_impl -> ...
=> xds: promote CdsLoadBalancer2

examples/example-tls/README.md
Context: https://stackoverflow.com/questions/65786059/how-to-create-a-start-script-for-the-example-grpc-java-tls-server-client/65816239#65816239
=> examples: Highlight the suggestion to checkout a tag

xds/third_party/envoy/import.sh, xds/third_party/envoy/src/main/proto/envoy/extensions/filters/common/fault/v3/fault.proto, xds/third_party/envoy/src/main/proto/envoy/extensions/filters/http/fault/v3/fault.proto
This is needed for fault injection.
=> xds: import fault proto

SECURITY.md
=> Add link to CVE process

README.md
This is part of the examples and other documentation, but a user
starting with the README would find things not working and it be very
unclear why.
Realized this was an issue because of
https://stackoverflow.com/q/66028045/4690866 .
=> README.md: Document protobuf-gradle-plugin config for lite

buildscripts/kokoro/xds.cfg
=> buildscripts: increase xds job timeouts (backport to v1.35.x of #7831)

interop-testing/src/main/java/io/grpc/testing/integration/AltsHandshakerTestService.java
=> interop-testing: fix test service race

xds/src/main/java/io/grpc/xds/ClientXdsClient.java, xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java, xds/src/test/java/io/grpc/xds/ClientXdsClientV2Test.java
=> xds: gate HttpFilter parsing by env flag (backport v1.36.x)

android-interop-testing/src/main/java/io/grpc/android/integrationtest/TesterOkHttpChannelBuilder.java, api/src/main/java/io/grpc/TlsChannelCredentials.java, api/src/main/java/io/grpc/TlsServerCredentials.java, interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java, interop-testing/src/test/java/io/grpc/testing/integration/ConcurrencyTest.java, interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java, interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java, netty/src/main/java/io/grpc/netty/FixedKeyManagerFactory.java, netty/src/main/java/io/grpc/netty/FixedTrustManagerFactory.java, netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java, netty/src/main/java/io/grpc/netty/UnhelpfulSecurityProvider.java, netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java, okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java, okhttp/src/test/java/io/grpc/okhttp/OkHttpChannelBuilderTest.java
It feels great cleaning up the test code.
=> Add mTLS and Trust/KeyManager Credentials API

README.md, build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, cronet/README.md, documentation/android-channel-builder.md, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
There are three commits. They will be merged as separate commits. The second one will be the released commit.
=> Release v1.36.0

xds/src/main/java/io/grpc/xds/GoogleCloudToProdNameResolverProvider.java, xds/src/test/java/io/grpc/xds/GoogleCloudToProdNameResolverProviderTest.java
Same with https://github.com/grpc/grpc/pull/25548.
=> xds: add env var protection for google-c2p resolver

xds/third_party/udpa/import.sh, xds/third_party/udpa/src/main/proto/udpa/type/v1/typed_struct.proto
Will be used for HttpFilter support
=> xds: import udpa/type/v1/typed_struct.proto

xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java, xds/src/main/java/io/grpc/xds/XdsServerBuilder.java, xds/src/main/java/io/grpc/xds/internal/sds/ServerWrapperForXds.java, xds/src/test/java/io/grpc/xds/ServerWrapperForXdsTest.java, xds/src/test/java/io/grpc/xds/XdsClientWrapperForServerSdsTestMisc.java, xds/src/test/java/io/grpc/xds/XdsServerBuilderTest.java
=> xds: implement listener deletion/re-add and server serving/not-serving logic

alts/src/main/java/io/grpc/alts/InternalCheckGcpEnvironment.java
=> remove confusing constant name in InternalCheckGcpEnvironment.java

xds/src/main/java/io/grpc/xds/EnvoyProtoData.java, xds/src/test/java/io/grpc/xds/EnvoyProtoDataTest.java
Backport of #7964 3f7aa8c592360e32bebab7b69a17ef1426c5e18d
=> xds: fix Node.toBuilder() bug (backport v1.36.x)

xds/src/main/java/io/grpc/xds/EnvoyProtoData.java, xds/src/test/java/io/grpc/xds/EnvoyProtoDataTest.java
=> xds: fix Node.toBuilder() bug (backport v1.35.x)

xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java, xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
=> xds:fix cdsLoadBalancer2 childLb shutdown

xds/src/main/java/io/grpc/xds/GoogleCloudToProdNameResolver.java, xds/src/test/java/io/grpc/xds/GoogleCloudToProdNameResolverTest.java
https://b.corp.google.com/issues/183205647#comment4 for context
=> xds: enable v3 API in bootstrap generated by cloud-to-prod resolver

xds/src/main/java/io/grpc/xds/XdsServerBuilder.java
=> xds: add/enhance Javadoc comments for XdsServerBuilder.

xds/src/main/java/io/grpc/xds/EnvoyServerProtoData.java, xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java, xds/src/test/java/io/grpc/xds/EnvoyServerProtoDataTest.java
=> xds: Fix validation of HCM filter and Router httpFilter (1.37.x backport) #8039

bom/build.gradle
Binder is not yet being published, so this artifact wouldn't exist.
CC @markb74
=> bom: Do not include grpc-binder

README.md, cronet/README.md, documentation/android-channel-builder.md
To be merged after release artifacts published to Maven Central.
=> Update README etc to reference 1.37.0

buildscripts/kokoro/xds-k8s.sh
In preparation to the Public Preview.
=> buildscript: use different xds-k8s cluster

buildscripts/kokoro/xds-k8s.cfg
=> buildscript: xds-k8s increase build timeout (v1.37.x backport)

buildscripts/kokoro/xds-k8s.cfg
=> buildscript: xds-k8s increase build timeout (v1.36.x backport)

buildscripts/kokoro/xds-k8s.cfg
=> buildscript: xds-k8s increase build timeout (v1.35.x backport)

buildscripts/kokoro/xds-k8s.cfg
=> buildscript: xds-k8s increase build timeout (v1.34.x backport)

repositories.bzl
This was missed from a81bf14
-----
CC @elharo
=> Bump Guava to 30.1 for Bazel

buildscripts/kokoro/xds.sh
As title.
https://fusion2.corp.google.com/invocations/480a03d9-7405-4bb2-8fed-6f36ccdaeb67/targets
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-java/8104)
=> Enable CSDS test

buildscripts/kokoro/xds.sh, interop-testing/src/main/java/io/grpc/testing/integration/XdsTestClient.java, interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java
As title.
sponge/a1956f60-14a8-40e9-896d-f08a56caf20f
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-java/8112)
=> [Backport][v1.37.x] Enable CSDS test

xds/src/main/java/io/grpc/xds/MessagePrinter.java
Adds ClusterConfig message descriptor to message printer.
=> xds: pretty print ClusterConfig message

xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java, xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
In cluster_resolver LB policy, we use the Channel authority to instantiate a DNS resolver for CFE cluster. When creating the `URI`, the Channel authority should be used as the _path_ in the standard URI definition and the scheme should be "dns". The test was _too fake_ for not being able to find the bug.
=> xds: fix URI creation used to instantiate DNS name resolver 

xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java
When the ring_hash LB policy enters TRANSIENT_FAILURE, it tries to connect one of the IDLE subchannels (added in #8144). Which subchannel to be connected to is non-deterministic, it just choose the first one from the [`subchannels` map](https://github.com/grpc/grpc-java/blob/e59604b7ce8cc3faee6f8252331ed6769d349f69/xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java#L64).
The existing test creates 4 subchannels, brings down 2 of them to let ring_hash LB policy enter TRANSIENT_FAILURE. But which one fo the remaining two subchannels to be kicked off connection is nondeterministic. This introduces trouble for verifying the behavior. This change simplifies the test, to only create 3 subchannels so that there is only one single subchannel remaining in IDLE after bringing the other two …
=> xds: eliminate test verification for nondeterministic behaviors

binder/src/androidTest/java/io/grpc/binder/internal/BinderTransportTest.java, binder/src/main/java/io/grpc/binder/internal/BinderServer.java, binder/src/main/java/io/grpc/binder/internal/BinderTransport.java, binder/src/test/java/io/grpc/binder/internal/BinderServerTransportTest.java
Addressing comment from #8031.
=> Fix the use of scheduler pools in BinderServer.

xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
Replace `java.util.PriorityQueue` with simple logic that keeps track of top-matches
=> xds: replace PriorityHeap with simpler logic that keeps track of top matches

binder/build.gradle, binder/src/androidTest/java/io/grpc/binder/BinderChannelSmokeTest.java, binder/src/androidTest/java/io/grpc/binder/BinderSecurityTest.java, binder/src/androidTest/java/io/grpc/binder/HostServices.java, binder/src/androidTest/java/io/grpc/binder/internal/BinderClientTransportTest.java, binder/src/main/java/io/grpc/binder/BinderChannelBuilder.java, binder/src/main/java/io/grpc/binder/BinderServerBuilder.java, binder/src/main/java/io/grpc/binder/IBinderReceiver.java, binder/src/main/java/io/grpc/binder/internal/BinderServer.java, binder/src/main/java/io/grpc/binder/internal/BinderTransport.java, binder/src/main/java/io/grpc/binder/internal/BinderTransportSecurity.java
With these builders, binderchannel should now be actually usable.
This also includes more tests for which cover some special cases.
=> binder: Server and Channel Builders for BinderChannel.

grpclb/src/main/proto/grpc/lb/v1/load_balancer.proto, repositories.bzl, rls/src/main/java/io/grpc/rls/RlsProtoConverters.java, rls/src/main/proto/grpc/lookup/v1/rls.proto, rls/src/main/proto/grpc/lookup/v1/rls_config.proto, rls/src/test/java/io/grpc/rls/RlsProtoConvertersTest.java
Update rls and grpc protos to the lastest (grpc/grpc-proto@08911e9)
Support for the new rls fields will be in an upcoming PR.
=> grpclb, rls: update protos

api/src/main/java/io/grpc/ForwardingServerBuilder.java, api/src/main/java/io/grpc/ServerBuilder.java, api/src/main/java/io/grpc/ServerCallExecutorSupplier.java, core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java, core/src/main/java/io/grpc/internal/SerializingExecutor.java, core/src/main/java/io/grpc/internal/ServerImpl.java, core/src/main/java/io/grpc/internal/ServerImplBuilder.java, core/src/test/java/io/grpc/inprocess/InProcessTransportTest.java, core/src/test/java/io/grpc/internal/SerializingExecutorTest.java, core/src/test/java/io/grpc/internal/ServerImplTest.java
https://github.com/grpc/grpc-java/pull/8289
=> core: fix jumpstream listener not set when closing stream inline

xds/src/main/java/io/grpc/xds/ClientXdsClient.java, xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
Implement check for non-unique filter-chain-match in the listener as per grfc https://github.com/grpc/proposal/blob/master/A36-xds-for-servers.md#filterchainmatch
=> xds: implement filter-chain uniqueness check as per grfc A36

binder/src/androidTest/java/io/grpc/binder/internal/BinderClientTransportTest.java, buildscripts/kokoro/android-interop.sh
=> binder: Run android emulator tests on kokoro.

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java, core/src/main/java/io/grpc/internal/ManagedChannelServiceConfig.java, core/src/main/java/io/grpc/internal/ScParser.java, core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java, xds/src/main/java/io/grpc/xds/ClientXdsClient.java, xds/src/main/java/io/grpc/xds/VirtualHost.java, xds/src/main/java/io/grpc/xds/XdsNameResolver.java, xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java, xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
Refactored ScParser to a public class for testing.
per_try_timeout is not supported for now.
=> xds: support xds retry policy

xds/src/main/java/io/grpc/xds/ClientXdsClient.java, xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java, xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java, xds/src/test/java/io/grpc/xds/ClientXdsClientV2Test.java, xds/src/test/java/io/grpc/xds/ClientXdsClientV3Test.java, xds/src/test/java/io/grpc/xds/internal/sds/CommonTlsContextTestsUtil.java
Implement validations for DownstreamTlsContext, UpstreamTlsContext and CommonTlsContext as described in https://github.com/grpc/proposal/pull/243/files
=> xds: add all validations related to security as described in A29 gRFC

netty/src/main/java/io/grpc/netty/NettyClientHandler.java, netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
Nginx and C core don't do graceful GOAWAY and retries have matured such
that transparent retries may soon be on by default. Refining the
workaround thus can reduces error rate for users.
Fixes #8310
----
CC  @c-s-t-z @hijerusalem
Backport of #8359
=> netty: Refine workaround for Netty header processing for transparent retries (1.40.x backport)

core/src/main/java/io/grpc/internal/GrpcUtil.java, core/src/test/java/io/grpc/internal/GrpcUtilTest.java
This is backport of #8381 
Fix a bug introduced in #8355 : old ClientStreamTracer.Factory implementation creates tracers twice.
=> core: fix old ClientStreamTracer.Factory creating tracers twice (backport v1.40.x)

buildscripts/kokoro/xds-k8s.sh, buildscripts/xds-k8s/cloudbuild.yaml
https://fusion2.corp.google.com/invocations/b85a0e20-c23b-4589-b44f-5f57d99f2215/targets
Related https://github.com/grpc/grpc/pull/26955 cl/389407788
@dapengzhang0 This is needed for the url-map tests on staging in the long run.
=> Update xDS client/server image per-branch tag after build

xds/src/main/java/io/grpc/xds/FilterChainMatchingProtocolNegotiators.java, xds/src/test/java/io/grpc/xds/FilterChainMatchingProtocolNegotiatorsTest.java
The FINE logging was just repeating the exceptions. But really, it is
trivial to avoid exceptions in this case and that is beneficial because
it will avoid an expensive error handling path in something that is
trivial to trigger remotely.
The WARNING may be a bit much if connections don't match the filter
chains often in production, but it seems most likely a misconfiguration
and not something that would be seen often.
=> xds: Avoid logging and throwing errors

xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
=> xds: fix RingHash LB null pointer issue [backport v1.38.x]

xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
Fix as per the comment https://github.com/grpc/grpc-java/pull/8435#discussion_r695047881
=> xds: set lbConfig=null if lbProvider is null [v1.39.x]

xds/src/main/java/io/grpc/xds/RingHashLoadBalancerProvider.java
=> xds: enable ring hash by default [backport v1.40.x]

xds/src/main/java/io/grpc/xds/GoogleCloudToProdNameResolver.java
=> Fix Java Style

api/src/main/java/io/grpc/CallCredentials2.java, auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java, core/src/test/java/io/grpc/internal/CallCredentials2ApplyingTest.java
Reverts grpc/grpc-java#8464
Need more external dependencies cleanup.
=> Revert "core/auth: Remove CallCredentials2"

census/src/main/java/io/grpc/census/CensusStatsModule.java
=> census: make internal linter happy

xds/src/main/java/io/grpc/xds/XdsServerWrapper.java, xds/src/test/java/io/grpc/xds/FilterChainMatchingProtocolNegotiatorsTest.java, xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java
backport https://github.com/grpc/grpc-java/pull/8491
=> xds: referenciate server routing config  (#8491) (1.41.x backport)

alts/src/main/java/io/grpc/alts/internal/AltsHandshakerClient.java, alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java, alts/src/main/java/io/grpc/alts/internal/AltsTsiHandshaker.java, alts/src/main/java/io/grpc/alts/internal/TsiHandshakerFactory.java, alts/src/test/java/io/grpc/alts/internal/AltsHandshakerClientTest.java, alts/src/test/java/io/grpc/alts/internal/AltsProtocolNegotiatorTest.java, alts/src/test/java/io/grpc/alts/internal/AltsTsiHandshakerTest.java, alts/src/test/java/io/grpc/alts/internal/AltsTsiTest.java, alts/src/test/java/io/grpc/alts/internal/FakeTsiHandshaker.java
The logs are to help with debugging issues for an internal customer.
=> alts: add channel logs in handshake

buildscripts/kokoro/xds_url_map.sh
grpc/grpc#27373
Test run: https://fusion2.corp.google.com/invocations/cf986474-d6b4-4709-8a5d-a7144e841aa2
@dapengzhang0
=> Add testing_version flag

xds/src/main/java/io/grpc/xds/RbacFilter.java, xds/src/test/java/io/grpc/xds/RbacFilterTest.java
fix https://github.com/grpc/grpc-java/issues/8576
=> rbac: fix status code PERMISSION_DENIED

xds/src/main/java/io/grpc/xds/BootstrapperImpl.java, xds/src/test/java/io/grpc/xds/BootstrapperImplTest.java
Backport of #8619 
See https://github.com/grpc/proposal/pull/268/files#diff-e68147af61f13db5bd497e86ffd970fef6af29b88f4f23fb486deefdb35dfea3R659 for detail.
=> xds: add protection flag for federation [backport v1.42.x]

README.md, cronet/README.md, documentation/android-channel-builder.md
=> Update README etc to reference 1.42.0

xds/src/main/java/io/grpc/xds/BootstrapperImpl.java
=> xds: Fix incorrect (old) javadoc for BootstrapperImpl

xds/src/main/java/io/grpc/xds/ClientXdsClient.java, xds/src/main/java/io/grpc/xds/EnvoyServerProtoData.java, xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
This is backport of https://github.com/grpc/grpc-java/pull/8663
=> xds: remove filter chain uuid name generator (1.42.x backport)

xds/src/main/java/io/grpc/xds/GoogleCloudToProdNameResolverProvider.java, xds/src/test/java/io/grpc/xds/GoogleCloudToProdNameResolverProviderTest.java, xds/src/test/java/io/grpc/xds/GoogleCloudToProdNameResolverTest.java
=> Backport "Replace C2P resolver env var with experimental scheme suffix (#8744)" to 1.43.x

build.gradle, examples/pom.xml, repositories.bzl
=> Bump GSON to 2.8.9 (1.43.x backport)

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
Backport of #8746
PR for Spikhalskiy/grpc-java@6d260b8
Hot fix of #8714
=> core: fix race condition in idleTimer & ManagedChannel#enterIdle [backport v1.43.x]

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
Backport of #8746
PR for Spikhalskiy/grpc-java@6d260b8
Hot fix of #8714
=> core: fix race condition in idleTimer & ManagedChannel#enterIdle [backport v1.42.x]

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
Backport of #8746
PR for Spikhalskiy/grpc-java@6d260b8
Hot fix of #8714
=> core: fix race condition in idleTimer & ManagedChannel#enterIdle [backport v1.41.x]

buildscripts/kokoro/xds.sh
=> [Backport][v1.43.x] use xds-test-server-5

COMPILING.md, build.gradle, buildscripts/make_dependencies.bat, buildscripts/make_dependencies.sh, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml, repositories.bzl
=> Bump protobuf to 3.19.2 (v1.43.x backport)

README.md, build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, cronet/README.md, documentation/android-channel-builder.md, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
This reverts commit 301d82cc6e00df48c5533f5515fa4e9310156a81.
=> Revert "1.44.0 release, version bump (#8862)"

observability/build.gradle, observability/src/main/java/io/grpc/observability/Observability.java, settings.gradle
We'll be adding new grpc observability features in this artifact as per the new design.
=> observability: create the grpc-observability artifact

api/src/main/java/io/grpc/ManagedChannelProvider.java, api/src/test/java/io/grpc/ManagedChannelRegistryTest.java, observability/build.gradle, observability/src/main/java/io/grpc/observability/LoggingChannelProvider.java, observability/src/main/java/io/grpc/observability/Observability.java, observability/src/main/java/io/grpc/observability/interceptors/InternalLoggingChannelInterceptor.java, observability/src/main/java/io/grpc/observability/interceptors/LoggingChannelInterceptor.java, observability/src/test/java/io/grpc/observability/LoggingChannelProviderTest.java, observability/src/test/java/io/grpc/observability/ObservabilityTest.java
=> observability: implement Observability.grpcInit() and LoggingChannelProvider

api/src/main/java/io/grpc/ServerProvider.java, api/src/test/java/io/grpc/ServerRegistryTest.java, netty/src/main/java/io/grpc/netty/NettyServerProvider.java, observability/build.gradle, observability/src/main/java/io/grpc/observability/LoggingServerProvider.java, observability/src/main/java/io/grpc/observability/Observability.java, observability/src/main/java/io/grpc/observability/interceptors/InternalLoggingServerInterceptor.java, observability/src/test/java/io/grpc/observability/LoggingServerProviderTest.java
=> observability: implement and integrate LoggingServerProvider into Observability

api/src/main/java/io/grpc/InternalManagedChannelProvider.java, api/src/main/java/io/grpc/InternalServerProvider.java, api/src/main/java/io/grpc/ManagedChannelProvider.java, api/src/main/java/io/grpc/ServerProvider.java, api/src/test/java/io/grpc/ManagedChannelRegistryTest.java, api/src/test/java/io/grpc/ServerRegistryTest.java, netty/src/main/java/io/grpc/netty/NettyServerProvider.java, observability/src/main/java/io/grpc/observability/LoggingChannelProvider.java, observability/src/main/java/io/grpc/observability/LoggingServerProvider.java
change visibility back to protected for certain methods of Providers
fixes #8887 
CC @ejona86
=> observability: revert previous visibility changes made in the provider APIs

binder/src/main/java/io/grpc/binder/internal/ServiceBinding.java, binder/src/test/java/io/grpc/binder/internal/ServiceBindingTest.java
Closes #8726
Backport of #8861
CC @markb74
=> binder: Fix a ServiceConnection leak (1.44.x backport)

core/src/main/java/io/grpc/internal/RetriableStream.java, core/src/test/java/io/grpc/internal/RetriableStreamTest.java
Limit the total number of local-only transparent retries per RPC for the moment to mitigate any potential bug that would trigger infinite loop of transparent retries. If the limit is exceeded, fail the RPC.
=> core: limit total number of local-only transparent retries

bom/build.gradle
Binder has had release artifacts since 0d25d8f7.
CC @ashithasantosh
=> bom: Include binder and exclude authz

observability/build.gradle
as discussed. Renaming of the artifact will be done later.
=> observability: do not publish our artifact to maven just yet

xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java, xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java
Consists of two commits, the fix is in 2nd one, and the 1st only improves the test and does not impact the fix even without it.
Backport of #8926
CC @apolcyn
=> xds: Do not failover priority when IDLE->CONNECTING (1.45.x backport)

xds/src/test/java/io/grpc/xds/FakeControlPlaneXdsIntegrationTest.java, xds/src/test/java/io/grpc/xds/XdsTestControlPlaneService.java
Some lint warning fixes from last week's Copybara import.
=> Copybara lint fixes

observability/src/main/java/io/grpc/observability/ObservabilityConfig.java, observability/src/test/java/io/grpc/observability/ObservabilityConfigTest.java
Implements g11y observability config parsing required for logging
=> observability: implement configuration parsing for observability

rls/src/main/java/io/grpc/rls/ChildLbResolvedAddressFactory.java, rls/src/main/java/io/grpc/rls/RlsProtoConverters.java, rls/src/main/java/io/grpc/rls/RlsProtoData.java, rls/src/main/java/io/grpc/rls/RlsRequestFactory.java, rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java, rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java, rls/src/test/java/io/grpc/rls/RlsProtoConvertersTest.java, rls/src/test/java/io/grpc/rls/RlsRequestFactoryTest.java
=> rls: backport two RLS bug fixes to v1.45.x 

context/src/test/java/io/grpc/PersistentHashArrayMappedTrieTest.java, core/src/test/java/io/grpc/internal/AtomicBackoffTest.java, core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java, rls/src/main/java/io/grpc/rls/RlsProtoConverters.java
=> Use `try/execute/fail/catch` instead of the strongly discouraged `@Test(expected=...)`

observability/src/main/java/io/grpc/observability/Observability.java, observability/src/main/java/io/grpc/observability/ObservabilityConfigImpl.java, observability/src/test/java/io/grpc/observability/ObservabilityConfigImplTest.java, observability/src/test/java/io/grpc/observability/ObservabilityTest.java
and make Observability implement AutoCloseable
=> observability: change the config parsing to not require logging_config

okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/proxy/HttpUrl.java
fix import failures cl/438834670
https://fusion2.corp.google.com/invocations/d7f2ba25-56a6-4994-a8ff-629a956ab3df/targets/%2F%2Fthird_party%2Fjava_src%2Fgrpc%2Fokhttp:okhttp;config=41c488ccb373ae72ac4ce1b2c0f36f321ef77157bbaa7b6fae7fd80eff8be128/log
=> okhttp: fix unreported exception

okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/proxy/HttpUrl.java
following up fix https://github.com/grpc/grpc-java/pull/9044
=> okhttp: Fix okio 2.x API incompatibility

xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java, xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java
ringHashPicker changes per gRFC: https://github.com/grpc/grpc/pull/29332:
previously it appears the picker logic is wrong, e.g. not request connecting on the any subchannel if it is in TRANSIENT_FAILURE
Refactored the logic to mirror the pseudo-code more so easier to understand.
backport of #9085
=> xds: fix ring-hash-picker behaviour  (#9085) (1.44.x backport)

api/src/test/java/io/grpc/ManagedChannelRegistryTest.java, xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java, xds/src/test/java/io/grpc/xds/LegacyLoadBalancerConfigFactoryTest.java
=> xds, api: minor cleanup to address linter suggestions

binder/src/main/java/io/grpc/binder/SecurityPolicies.java, binder/src/test/java/io/grpc/binder/SecurityPoliciesTest.java
adding a security policy that allows access if and only if all given security policies allow access. this contributes to b/221149437 and is similar to cl/442582915
=> add allOf security policy and test

binder/src/main/java/io/grpc/binder/SecurityPolicies.java, xds/src/test/java/io/grpc/xds/WrrLocalityLoadBalancerTest.java
=> binder, xds: address minor linter fixes

core/src/test/java/io/grpc/internal/ManagedChannelServiceConfigTest.java, gcp-observability/src/main/java/io/grpc/gcp/observability/GlobalLoggingTags.java, gcp-observability/src/main/java/io/grpc/gcp/observability/MetadataConfig.java, gcp-observability/src/main/java/io/grpc/gcp/observability/logging/GcpLogSink.java, gcp-observability/src/test/java/io/grpc/gcp/observability/GlobalLoggingTagsTest.java, googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolver.java, interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java, repositories.bzl, rls/src/main/java/io/grpc/rls/RlsRequestFactory.java, xds/src/main/java/io/grpc/xds/BootstrapperImpl.java, xds/src/main/java/io/grpc/xds/ClientXdsClient.java, xds/src/main/java/io/grpc/xds/LegacyLoadBalancerConfigFactory.java, xds/src/main/java/io/grpc/xds/XdsNameResolver.java, xds/src/main/java/io/grpc/xds/XdsServerWrapper.java, xds/src/test/java/io/grpc/xds/CsdsServiceTest.java, xds/src/test/java/io/grpc/xds/RouteLookupServiceClusterSpecifierPluginTest.java
=> Use `ImmutableMap.Builder.buildOrThrow()` instead of deprecated `build()`.

gcp-observability/src/main/java/io/grpc/gcp/observability/ObservabilityConfig.java, gcp-observability/src/main/java/io/grpc/gcp/observability/ObservabilityConfigImpl.java, gcp-observability/src/test/java/io/grpc/gcp/observability/ObservabilityConfigImplTest.java
=> gpc-observability: add configuration for metrics and tracing, sampler and sampler_rate and reading from file

xds/src/test/java/io/grpc/xds/LoadBalancerConfigFactoryTest.java
=> xds: More nuanced LoadBalancerConfigFactory tests

android-interop-testing/build.gradle, interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java, interop-testing/src/main/java/io/grpc/testing/integration/CustomBackendMetricsLoadBalancerProvider.java, interop-testing/src/main/java/io/grpc/testing/integration/TestCases.java, interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java, interop-testing/src/main/java/io/grpc/testing/integration/TestServiceImpl.java, interop-testing/src/main/java/io/grpc/testing/integration/TestServiceServer.java, interop-testing/src/main/proto/grpc/testing/messages.proto, interop-testing/src/test/java/io/grpc/testing/integration/TestCasesTest.java, services/src/main/java/io/grpc/services/CallMetricRecorder.java
backport of https://github.com/grpc/grpc-java/pull/9079
=> interop-test: add orca test case (1.47.x backport)

buildscripts/kokoro/xds.sh
As title.
Tested:
* https://fusion2.corp.google.com/invocations/716fb9d9-233b-48af-a24d-b2adfb7adc63/targets
=> interop-test: Remove duplicated GCE tests

RELEASING.md, examples/example-orca/README.md, examples/example-orca/build.gradle, examples/example-orca/settings.gradle, examples/example-orca/src/main/java/io/grpc/examples/orca/CustomBackendMetricsClient.java, examples/example-orca/src/main/java/io/grpc/examples/orca/CustomBackendMetricsLoadBalancerProvider.java, examples/example-orca/src/main/java/io/grpc/examples/orca/CustomBackendMetricsServer.java, examples/example-orca/src/main/proto/helloworld/helloworld.proto
the readme is valid but probably needs to be polished, send everything for early feedback.
=> examples: add examples-orca

RELEASING.md, examples/example-orca/README.md, examples/example-orca/build.gradle, examples/example-orca/settings.gradle, examples/example-orca/src/main/java/io/grpc/examples/orca/CustomBackendMetricsClient.java, examples/example-orca/src/main/java/io/grpc/examples/orca/CustomBackendMetricsLoadBalancerProvider.java, examples/example-orca/src/main/java/io/grpc/examples/orca/CustomBackendMetricsServer.java, examples/example-orca/src/main/proto/helloworld/helloworld.proto
backport https://github.com/grpc/grpc-java/pull/9204
=> examples: add examples-orca (backport 1.47.x)

buildscripts/kokoro/xds.sh, buildscripts/kokoro/xds_k8s_lb.cfg, buildscripts/kokoro/xds_k8s_lb.sh
Backports https://github.com/grpc/grpc-java/pull/8888 https://github.com/grpc/grpc-java/pull/8998 https://github.com/grpc/grpc-java/pull/8982 https://github.com/grpc/grpc-java/pull/9199.
* [xds](http://sponge/e581bedc-c036-47ad-9510-92d8704e1b2e)
* [xds_v3](http://sponge/ffd78f5f-8740-442b-8e6b-4c3828f64fec)
* [xds_k8s_lb](http://sponge/ae573c22-b7f2-472d-b2a2-243683c4b7e3)
* [xds_url_map](http://sponge/2703fbe3-cf5d-4b54-9b41-eada88517ee4)
=> interop-test: Opt-in GKE tests && Remove duplicated GCE tests (v1.44.x backport)

buildscripts/kokoro/xds.sh, buildscripts/kokoro/xds_k8s_lb.cfg, buildscripts/kokoro/xds_k8s_lb.sh
Backports https://github.com/grpc/grpc-java/pull/8888 https://github.com/grpc/grpc-java/pull/8998 https://github.com/grpc/grpc-java/pull/8982 https://github.com/grpc/grpc-java/pull/9199.
* [xds](http://sponge/bdfb7260-24f6-4bb2-81fe-889e20c6cd84)
* [xds_v3](http://sponge/50a0f1fd-4e11-4d38-af52-429284af3ff4)
* [xds_k8s_lb](http://sponge/20db85f3-826d-4767-9619-6c4e21126b0d)
* [xds_url_map](http://sponge/5889f1ba-9b5c-49b0-94a1-58f7e4f6a411)
=> interop-test: Opt-in GKE tests && Remove duplicated GCE tests (v1.43.x backport)

buildscripts/kokoro/xds.sh, buildscripts/kokoro/xds_k8s_lb.cfg, buildscripts/kokoro/xds_k8s_lb.sh, buildscripts/kokoro/xds_url_map.sh
Backports https://github.com/grpc/grpc-java/pull/8534 https://github.com/grpc/grpc-java/pull/8888 https://github.com/grpc/grpc-java/pull/8998 https://github.com/grpc/grpc-java/pull/8982 https://github.com/grpc/grpc-java/pull/9199.
* [xds](http://sponge/a5ec5c95-6a26-4297-8477-7d7202fa5a74)
* [xds_v3](http://sponge/c4e17e1d-aa98-4f05-8461-07d9da82bffc)
* [xds_k8s_lb](http://sponge/8121b3cb-560a-4f29-b254-10bdb0b88f2d)
* [xds_url_map](http://sponge/a3201eda-ac7f-4388-8f36-bec883d6286b)
=> interop-test: Opt-in GKE tests && Remove duplicated GCE tests (v1.41.x backport)

buildscripts/kokoro/xds.sh, buildscripts/kokoro/xds_k8s_lb.cfg, buildscripts/kokoro/xds_k8s_lb.sh, buildscripts/kokoro/xds_url_map.sh
Backports https://github.com/grpc/grpc-java/pull/8534 https://github.com/grpc/grpc-java/pull/8888 https://github.com/grpc/grpc-java/pull/8998 https://github.com/grpc/grpc-java/pull/8982 https://github.com/grpc/grpc-java/pull/9199.
* [xds](http://sponge/6d8f24ea-292c-426a-a28f-eaf2743a8fbf)
* [xds_v3](http://sponge/9b4a3f14-bab8-47d2-87a5-ddc566846121)
* [xds_k8s_lb](http://sponge/f3242333-8641-4858-8644-b7e262d1f8a5)
* [xds_url_map](http://sponge/e907b354-7bac-4b64-b4d9-ea627ad41937)
=> interop-test: Opt-in GKE tests && Remove duplicated GCE tests (v1.40.x backport)

buildscripts/kokoro/xds.sh, buildscripts/kokoro/xds_k8s_lb.cfg, buildscripts/kokoro/xds_k8s_lb.sh
Backports https://github.com/grpc/grpc-java/pull/8888 https://github.com/grpc/grpc-java/pull/8998 https://github.com/grpc/grpc-java/pull/8982 https://github.com/grpc/grpc-java/pull/9199.
* [xds](http://sponge/7475132f-c0d2-47f3-9b78-7f6f8066cde1)
* [xds_v3](http://sponge/b8dab431-dd2c-4857-9a2d-130100ebf149)
* [xds_k8s_lb](http://sponge/b461fa4b-5d15-45aa-8f5b-b90a7c7538c8)
* [xds_url_map](http://sponge/b7eb7a29-afb5-4e52-8caa-46225f2b8512)
=> interop-test: Opt-in GKE tests && Remove duplicated GCE tests (v1.42.x backport)

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java, interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
Alternative to https://github.com/grpc/grpc-java/pull/9187
=> interop client: bump operation timeout to 15 seconds

interop-testing/build.gradle, interop-testing/src/main/java/io/grpc/testing/integration/CustomBackendMetricsLoadBalancerProvider.java
=> interop-test: orca test change gradle dependency to xds non-shaded to allow bazel run

build.gradle, xds/build.gradle
=> xds: Remove unused Bouncy Castle dependency

xds/src/main/java/io/grpc/xds/ClientXdsClient.java, xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
=> xds: fix NullPointerException for unknown xdstp resources

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
https://source.cloud.google.com/results/invocations/220b8e97-1736-4c7e-ab30-6242895955df/log
=> interop-test: test_orca_oob add retry limit 5 

alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java, alts/src/test/java/io/grpc/alts/internal/AltsProtocolNegotiatorTest.java, alts/src/test/java/io/grpc/alts/internal/GoogleDefaultProtocolNegotiatorTest.java
https://b.corp.google.com/issues/234636098
support new style resource name
see discussions in https://github.com/grpc/grpc/pull/29764
=> alts: support google credential CFE cluster name in XDSTP format 

testing/src/main/java/io/grpc/testing/GrpcCleanupRule.java
=> testing: minor lint-suggested improvements

repositories.bzl
fb314d3 bumped deps in Gradle, but forgot to bump those same deps in
Bazel.
=> Bump Bazel deps missed in fb314d3

COMPILING.md, buildscripts/kokoro/windows32.bat, buildscripts/kokoro/windows64.bat, buildscripts/make_dependencies.bat, buildscripts/make_dependencies.sh, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-orca/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml, gcp-observability/build.gradle, gradle/libs.versions.toml, repositories.bzl
=> Bump protobuf to 3.21.1 (#9311) (v1.48.x backport)

repositories.bzl
fb314d3 bumped deps in Gradle, but forgot to bump those same deps in
Bazel.
Backport of #9331
=> Bump Bazel deps missed in fb314d3 (1.48.x backport)

xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java, xds/src/test/java/io/grpc/xds/ClusterManagerLoadBalancerTest.java
Do not perform picker updates while handling new addresses even if child
LBs request it. Assure that a single picker update is done.
=> xds: cluster manager to delay picker updates

xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- Reduce nesting level by using `continue`
- Rearrange the order when it's possible to bail out early
- Add comments explaining what case it is, and the logic behind it
cc @ejona86
=> xds: Refactor and document `ClientXdsClient.handleResourceUpdate()`

alts/build.gradle, api/build.gradle, auth/build.gradle, authz/build.gradle, benchmarks/build.gradle, census/build.gradle, core/build.gradle, gae-interop-testing/gae-jdk8/build.gradle, gcp-observability/build.gradle, googleapis/build.gradle, gradle/libs.versions.toml, grpclb/build.gradle, interop-testing/build.gradle, istio-interop-testing/build.gradle, netty/build.gradle, netty/shaded/build.gradle, okhttp/build.gradle, protobuf-lite/build.gradle, protobuf/build.gradle, rls/build.gradle, services/build.gradle, stub/build.gradle, testing-proto/build.gradle, testing/build.gradle, xds/build.gradle
Also added missing signatures. Swapping to version catalog will make
this process easier in the future.
=> Swap Animalsniffer to Java 8 and Android 19

xds/src/main/java/io/grpc/xds/ClientXdsClient.java
=> xds: Fix outlier detection env flag name. (1.49.x backport)

xds/src/main/java/io/grpc/xds/ClientXdsClient.java
=> core: Enable outlier detection by default. (1.49.x backport)

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java, core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java
Instead of strictly enforcing the max ejection percentage setting,
allow one additional ejection past the maximum. This quarantees at least
one ejection and matches Envoy proxy behavior.
=> core: Update outlier detection max ejection logic.

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java, core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java
When doing the failure percentage algorithm, ejections should be skipped
if there are not enough addresses that meet the minimum volume
requirement.
=> core: outlier detection to honor min host request volume

core/src/main/java/io/grpc/internal/MaxConnectionIdleManager.java, core/src/test/java/io/grpc/internal/MaxConnectionIdleManagerTest.java, netty/src/main/java/io/grpc/netty/NettyServerHandler.java
this is preparation work for adding `maxConnectionIdle` is okhttp-server
=> netty: move max connection idle manager to core

core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java
Implements a fake load balancer with round robin like behavior in order
to test an outlier detection scenario where a subchannel goes from
having multiple associated addresses to one.
=> core: Enable outlier detection unit test

okhttp/src/main/java/io/grpc/okhttp/OkHttpServerBuilder.java, okhttp/src/main/java/io/grpc/okhttp/OkHttpServerTransport.java, okhttp/src/test/java/io/grpc/okhttp/OkHttpServerTransportTest.java
This reverts commit 7291ad44c6d5d2b614762d4f549008c14eeff312.
=> Revert "okhttp: add max connection idle at OkHttpServer (#9494)"

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
https://github.com/grpc/proposal/blob/master/A54-restrict-control-plane-status-codes.md
=> core: Comment on "inappropriate" service config errors

xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java, xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java
=> xds: ringhash policy in TRANSIENT_FAILURE should not attempt connecting when already in connecting (#9535) (1.48 backport)) 

core/src/main/java/io/grpc/internal/PickFirstLoadBalancer.java, core/src/test/java/io/grpc/internal/PickFirstLoadBalancerTest.java
Migrate pick_first over to use the new acceptResolvedAddresses so that the old handleResolvedAddresses() can eventually be deprecated.
=> core: pick_first LB to use acceptResolvedAddresses()

gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java
=> observability: replace current OpenCensus registerAllGrpcViews with only selected views for GCP observability

COMPILING.md, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-orca/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml, gradle/libs.versions.toml, repositories.bzl
=> Bump Protobuf to 3.21.7 (1.50.x backport)

COMPILING.md, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-orca/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml, gradle/libs.versions.toml, repositories.bzl
=> Bump Protobuf to 3.21.7 (1.48.x backport)

COMPILING.md, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-orca/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml, gradle/libs.versions.toml, repositories.bzl
=> Bump Protobuf to 3.21.7 (1.49.x backport)

COMPILING.md, README.md, build.gradle, buildscripts/make_dependencies.bat, buildscripts/make_dependencies.sh, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml, repositories.bzl
=> Bump protobuf to 3.19.6 (v1.42.x) (1.41.x backport)

api/src/main/java/io/grpc/NameResolver.java
fix https://github.com/grpc/grpc-java/issues/9541
=> doc: name resolver start() should not throw

xds/src/main/java/io/grpc/xds/AbstractXdsClient.java, xds/src/main/java/io/grpc/xds/XdsClient.java, xds/src/main/java/io/grpc/xds/XdsClientImpl.java, xds/src/test/java/io/grpc/xds/CsdsServiceTest.java, xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java
=> xds: Fix AbstractXdsClient fromTypeUrl to use subscribedResources instead of hardcoded

xds/src/main/java/io/grpc/xds/WeightedTargetLoadBalancer.java
Part of a migration from handleResolvedAddresses().
=> xds: weighted_target to use acceptResolvedAddresses()

xds/src/main/java/io/grpc/xds/WrrLocalityLoadBalancer.java
Part of a migration to move load balancers away from handleResolvedAddresses().
=> xds: wrr_locality LB to use acceptResolvedAddresses()

gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java, gcp-observability/src/main/java/io/grpc/gcp/observability/ObservabilityConfig.java, gcp-observability/src/main/java/io/grpc/gcp/observability/ObservabilityConfigImpl.java, gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/ConfigFilterHelper.java, gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/InternalLoggingChannelInterceptor.java, gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/InternalLoggingServerInterceptor.java, gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/LogHelper.java, gcp-observability/src/main/java/io/grpc/gcp/observability/logging/GcpLogSink.java, gcp-observability/src/main/proto/grpc/observabilitylog/v1/observabilitylog.proto, gcp-observability/src/test/java/io/grpc/gcp/observability/LoggingTest.java, gcp-observability/src/test/java/io/grpc/gcp/observability/MetricsTest.java, gcp-observability/src/test/java/io/grpc/gcp/observability/ObservabilityConfigImplTest.java, gcp-observability/src/test/java/io/grpc/gcp/observability/ObservabilityTestHelper.java, gcp-observability/src/test/java/io/grpc/gcp/observability/TracesTest.java, gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/ConfigFilterHelperTest.java, gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/InternalLoggingChannelInterceptorTest.java, gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/InternalLoggingServerInterceptorTest.java, gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/LogHelperTest.java, gcp-observability/src/test/java/io/grpc/gcp/observability/logging/GcpLogSinkTest.java
Backport #9608, #9622.
CC @DNVindhya
=> gcp-observability: update logging schema and configuration for public preview (1.50.x backport)

README.md, build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, cronet/README.md, documentation/android-channel-builder.md, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-orca/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
=> Release v1.50.2

core/src/main/java/io/grpc/internal/ManagedChannelOrphanWrapper.java
=> doc: improve java doc ManagedChannelOrphanWrapper

api/src/main/java/io/grpc/LoadBalancerRegistry.java, api/src/main/java/io/grpc/ManagedChannelRegistry.java, api/src/main/java/io/grpc/NameResolverRegistry.java, api/src/main/java/io/grpc/ServerRegistry.java
[issue](https://github.com/grpc/grpc-java/issues/9644)
=> reduce redundant judgment

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
[issue](https://github.com/grpc/grpc-java/issues/9652)
=> ManagedChannelImpl.SubchannelImpl args check bug

README.md
I think we could probably do a better job of directing people places in the transport section, but let's start by not having it be out-of-date.
CC @markb74
=> README.md: Update support docs, OkHttp server, binder

MAINTAINERS.md
=> MAINTAINERS.md: Add Binder maintainers

xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java, xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java
ClusterImplLoadBalancer adds the ATTR_CLUSTER_NAME and ATTR_SSL_CONTEXT_PROVIDER_SUPPLIER attributes to the EAG list when it creates a new subchannel, but they are lost on subsequent address updates. This change assures the attributes are also included on address updates.
b/238261553
=> xds: Include additional EAG attributes on updates

binder/src/main/java/io/grpc/binder/AndroidComponentAddress.java, binder/src/main/java/io/grpc/binder/BinderInternal.java, binder/src/main/java/io/grpc/binder/SecurityPolicies.java
Additional suggested changes that were added post-submission of [#9669](https://github.com/grpc/grpc-java/pull/9669) for promoting out of experimental status.
=> binder: Additional documentation for promoting out of experimental status

xds/src/main/java/io/grpc/xds/XdsRouteConfigureResource.java
total_weight is deprecated and serves no value.
=> xds: Remove outdated comment about observing total weight

xds/src/test/java/io/grpc/xds/FakeControlPlaneXdsIntegrationTest.java, xds/src/test/java/io/grpc/xds/XdsTestControlPlaneService.java
documents: [go/fake-xds-control-plane-integration-test](http://goto.google.com/fake-xds-control-plane-integration-test)
=> doc: add fake control plane xds test comments

README.md, build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, cronet/README.md, documentation/android-channel-builder.md, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-orca/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
Release 1.51.1 to provide fix for Spanner's ConcurrentModificationException
=> Release 1.51.1

xds/src/main/java/io/grpc/xds/LoadReportClient.java, xds/src/test/java/io/grpc/xds/LoadReportClientTest.java
=> xds: refactor LoadReportClient with xds v2 dropped

netty/src/test/java/io/grpc/netty/TlsTest.java
Netty is known to not use SSL hostname verfication by default[1], although this is enabled for gRPC channels. This change validates that functionality by porting a test with a similar purpuse for OkHttp.
As benefit to users it helps build confidence that their clients aren't vulnerable to Improper Certificate Validation issues reported by vulnerability scanners such as Snyk[2].
* [1] https://github.com/netty/netty/issues/8537
* [2] https://security.snyk.io/vuln/SNYK-JAVA-IONETTY-1042268
=> Testing that Netty clients fail for mismatching TLS common names

README.md, examples/android/clientcache/build.gradle, examples/android/helloworld/build.gradle, examples/android/routeguide/build.gradle, examples/android/strictmode/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-hostname/build.gradle, examples/example-jwt-auth/build.gradle, examples/example-orca/build.gradle, examples/example-tls/build.gradle, examples/example-xds/build.gradle
Update all of the protobuf plugin versions per Ivy.
=> Upgrade protobuf plugin version to 0.8.19.

README.md, build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, cronet/README.md, documentation/android-channel-builder.md, examples/android/clientcache/app/build.gradle, examples/android/clientcache/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/helloworld/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/routeguide/build.gradle, examples/android/strictmode/app/build.gradle, examples/android/strictmode/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-orca/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
=> Release v1.52.0

README.md, build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, cronet/README.md, documentation/android-channel-builder.md, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-orca/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
Take 2 on updating version numbers.
=> Release v1.52.0 preparation

netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java, netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java, netty/src/main/java/io/grpc/netty/NettyClientHandler.java, netty/src/main/java/io/grpc/netty/NettyClientTransport.java, netty/src/main/java/io/grpc/netty/NettyServerHandler.java, netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java, netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java, netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java, netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
=> Revert "netty:Auto adjust BDP ping frequency"

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
Use a volatile to publish the value even though it is final. TSAN ignores the final aspect of a field, which is fair since another thread may not see the parent's pointer become updated and use a stale value. The lack of synchronization was clearly against lastServiceConfig's documentation.
Fixes #9267
=> core: Synchronize access to retry's throttle

interop-testing/src/main/java/io/grpc/testing/integration/XdsFederationTestClient.java
Address suggestions from an internal linter. There should be no functional changes in this PR.
cc @ejona86
=> [XDS federation interop client]: address internal linter suggestions

xds/src/main/java/io/grpc/xds/orca/OrcaOobUtil.java, xds/src/test/java/io/grpc/xds/orca/OrcaOobUtilTest.java
Needed by WRR
Descriptions [here](https://docs.google.com/document/d/1NXotgSMjcJa0q-uwynaLG6tD9oK6tYKXAvxAvR4GE2Q/edit#heading=h.gk9k0nbxkdk9)
=> orca: support remove listener in OrcaOobUtil

api/src/main/java/io/grpc/ServerBuilder.java
=> Remove ExperimentalApi from ServerBuilder.intercept

api/src/main/java/io/grpc/PartialForwardingServerCall.java, api/src/test/java/io/grpc/ForwardingServerCallTest.java
=> api: forward getSecurityLevel on PartialForwardingServerCall

api/src/main/java/io/grpc/ForwardingServerCall.java, api/src/test/java/io/grpc/ForwardingServerCallTest.java
=> api: Forward getMethodDescriptor() in ForwardingServerCall

xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java
fixes https://github.com/grpc/grpc-java/issues/10003
=> xds: fix flaky wrr test

xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java
backport of https://github.com/grpc/grpc-java/pull/10004
=> xds: fix wrr flaky test (v1.54 backport)

services/src/main/java/io/grpc/services/MetricRecorder.java, xds/src/test/java/io/grpc/xds/orca/OrcaServiceImplTest.java
https://github.com/grpc/proposal/pull/345
=> orca, services: rename to (clear)setQpsMetric

README.md, build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, cronet/README.md, documentation/android-channel-builder.md, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-gcp-observability/build.gradle, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-orca/build.gradle, examples/example-servlet/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
Release 1.54.1 needed for observability
=> Release v1.54.1

xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java, xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java
cc @danielzhaotongliu, @yousukseung
=> xds: fix wrr stuck in rr mode

xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java, xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java
=> xds: fix wrr stuck in rr mode (v1.54 backport)

xds/src/main/java/io/grpc/xds/LoadBalancerConfigFactory.java, xds/src/main/java/io/grpc/xds/XdsClusterResource.java, xds/src/main/java/io/grpc/xds/XdsListenerResource.java, xds/src/main/java/io/grpc/xds/XdsResourceType.java, xds/src/main/java/io/grpc/xds/XdsRouteConfigureResource.java, xds/src/test/java/io/grpc/xds/LoadBalancerConfigFactoryTest.java, xds/src/test/java/io/grpc/xds/XdsClientImplDataTest.java, xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java
fixes https://github.com/grpc/grpc-java/issues/10054
cc. @ejona86
=> xds: remove environmental variables

services/src/main/java/io/grpc/services/CallMetricRecorder.java, services/src/main/java/io/grpc/services/MetricRecorder.java, services/src/main/java/io/grpc/services/MetricRecorderHelper.java, services/src/test/java/io/grpc/services/CallMetricRecorderTest.java, xds/src/test/java/io/grpc/xds/orca/OrcaServiceImplTest.java
see gRFC: https://github.com/grpc/proposal/pull/358
=> services: allow cpu utilization greater than 1

services/src/main/java/io/grpc/services/CallMetricRecorder.java, services/src/main/java/io/grpc/services/MetricRecorder.java, services/src/main/java/io/grpc/services/MetricRecorderHelper.java, services/src/test/java/io/grpc/services/CallMetricRecorderTest.java, xds/src/test/java/io/grpc/xds/orca/OrcaServiceImplTest.java
backport of https://github.com/grpc/grpc-java/pull/10107
=> services: allow cpu utilization greater than 1 (v1.55 backport)

xds/src/main/java/io/grpc/xds/XdsResourceType.java, xds/src/test/java/io/grpc/xds/XdsClientImplDataTest.java
https://github.com/grpc/grpc-java/pull/10100 backport
=> xds: enable wrr env variable (v1.55 backport)

googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolver.java, googleapis/src/test/java/io/grpc/googleapis/GoogleCloudToProdNameResolverTest.java
CC @veblush, @apolcyn, @mohanli-ml
=> googleapis: Enable ignore_resource_deletion in bootstrap

googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolver.java, googleapis/src/test/java/io/grpc/googleapis/GoogleCloudToProdNameResolverTest.java
CC @veblush, @apolcyn, @mohanli-ml 
Backport of #10121
=> googleapis: Enable ignore_resource_deletion in bootstrap (1.55.x backport)

xds/src/main/java/io/grpc/xds/RoutingUtils.java, xds/src/test/java/io/grpc/xds/orca/OrcaServiceImplTest.java
=> xds: Avoid default locale and reset()

xds/src/main/java/io/grpc/xds/RoutingUtils.java, xds/src/test/java/io/grpc/xds/orca/OrcaServiceImplTest.java
Found via linter
CC @temawi 
Backport of #10141
=> xds: Avoid default locale and reset() (1.55.x backport)

okhttp/src/main/java/io/grpc/okhttp/OkHttpServerTransport.java
=> okhttp: Fix signed-byte comparison

all/build.gradle, authz/build.gradle, build.gradle
CC @temawi, note that we can't trivially upgrade to Gradle 8 because that requires upgrade Android Gradle Plugin, which requires Java 17
=> gradle: Improve compatibility with Gradle 8

xds/src/main/java/io/grpc/xds/RoutingUtils.java, xds/src/test/java/io/grpc/xds/orca/OrcaServiceImplTest.java
Found via linter
CC @temawi 
Backport of #10141
=> xds: Avoid default locale and reset() (1.54.x backport)

README.md, build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-debug/build.gradle, examples/example-debug/pom.xml, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-gcp-observability/build.gradle, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-orca/build.gradle, examples/example-reflection/build.gradle, examples/example-servlet/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
=> Release 1.55.1

build.gradle, gradle/libs.versions.toml
This allows the checkForUpdates task to look for newer versions.
=> gradle: Assocate an artifact to every version

api/src/main/java/io/grpc/HttpConnectProxiedSocketAddress.java, api/src/main/java/io/grpc/ManagedChannelBuilder.java, api/src/main/java/io/grpc/ProxiedSocketAddress.java, api/src/main/java/io/grpc/ProxyDetector.java
=> api: remove experimentalApi setting from proxyDetector and related classes

README.md
fixes #10215
@lowasser @ejona86 merge?
=> docs: Document use with Bazel, like Maven & Gradle (fixes #10215)

java_grpc_library.bzl
=> Add java toolchain type to all rules which are using java_common

README.md, build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-debug/build.gradle, examples/example-debug/pom.xml, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-gcp-observability/build.gradle, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-orca/build.gradle, examples/example-reflection/build.gradle, examples/example-servlet/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
Note that com.google.protobuf:protoc is updated from 3.21.7 to 3.22.3 in README.txt.
=> Release v1.56.0

README.md
com.google.protobuf:protoc updated from 3.21.7 to 3.22.3.
=> Update README etc to reference 1.56.0

xds/src/main/java/io/grpc/xds/XdsClusterResource.java, xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java
Fixes row 33 on go/grpc-lb-xds-tracker
=> require EDS service name in CDS resources with xdstp name

README.md, build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-debug/build.gradle, examples/example-debug/pom.xml, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-gcp-observability/build.gradle, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-orca/build.gradle, examples/example-reflection/build.gradle, examples/example-servlet/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
#10339 missed a search/replace in a file, so we do it again.
=> Release v1.56.1

protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java, protobuf/src/main/java/io/grpc/protobuf/ProtoUtils.java
=> Stabilize setExtensionRegistry() of ProtoLiteUtils and ProtoUtils

README.md, build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-debug/build.gradle, examples/example-debug/pom.xml, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-gcp-observability/build.gradle, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-orca/build.gradle, examples/example-reflection/build.gradle, examples/example-servlet/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
Reverts grpc/grpc-java#10417
Was mistakenly merged.
=> Revert "Release v1.57.0"

README.md, build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-debug/build.gradle, examples/example-debug/pom.xml, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-gcp-observability/build.gradle, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-orca/build.gradle, examples/example-reflection/build.gradle, examples/example-servlet/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
=> Release v1.57.0

api/src/main/java/io/grpc/ManagedChannelBuilder.java, api/src/main/java/io/grpc/ServerBuilder.java
This is to give users a place to look to learn more.
=> api: Link to gRFCs A8/A9 for keepalive and related settings

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java, interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java, interop-testing/src/main/java/io/grpc/testing/integration/XdsFederationTestClient.java
Internal bug: b/289109827
cc: @apolcyn @temawi
=> test: allow set request/response size in interop soak test

api/src/main/java/io/grpc/ServerBuilder.java
fixes https://github.com/grpc/grpc-java/issues/3706
=> api: stablize ServerBuilder.handshakeTimeout

interop-testing/src/main/java/io/grpc/testing/integration/StressTestClient.java, interop-testing/src/test/java/io/grpc/testing/integration/StressTestClientTest.java
OverrideAuthority() is the modern alternative to rewriting the InetAddress, and can also work if we change the channel creation to use target strings instead. We can use test CAs now without resorting to the Netty-specific APIs. After this change, only 4 classes in interop-testing depend on Netty.
=> interop-testing: Modernize stress test channel creation

testing/src/main/java/io/grpc/testing/TestMethodDescriptors.java
=> testing: Stabilize TestMethodDescriptors

core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java, netty/src/main/java/io/grpc/netty/Utils.java
This is a follow up of #10345
Best regards
=> core,netty: a few proposals to reduce allocations

netty/src/main/java/io/grpc/netty/Utils.java
=> netty: Use UNAVAILABLE for connections closed while writing

api/src/main/java/io/grpc/ClientStreamTracer.java, census/src/main/java/io/grpc/census/CensusTracingModule.java, census/src/test/java/io/grpc/census/CensusModulesTest.java, core/src/main/java/io/grpc/internal/ClientCallImpl.java, core/src/main/java/io/grpc/internal/ManagedChannelImpl.java, core/src/test/java/io/grpc/internal/ClientCallImplTest.java, core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
fixes https://github.com/grpc/grpc-java/issues/10525
=> core: DEADLINE_EXCEEDED gives hints for slow resolver

stub/src/main/java/io/grpc/stub/ClientCalls.java
Ran global presubmit on cl/563630388 and it looks fine.
=> stub: Enable rejected execution exception by default on ThreadlessExecutor

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java, xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java
=> Eliminate use of getOrDefault

xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
fix https://github.com/grpc/grpc-java/issues/10658
=> xds: fix ring hash childLB acceptResolvedAddress not in syncContext

inprocess/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
=> inprocess: Add missing anonymous address as supported (1.60.x backport)

README.md, build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-debug/build.gradle, examples/example-debug/pom.xml, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-gcp-observability/build.gradle, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-orca/build.gradle, examples/example-reflection/build.gradle, examples/example-servlet/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
Create 1.58.1 release to pickup fix for directpath problem.
=> Release 1.58.1

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
=> util:Add increment as identified by user in #10768

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java
=> util:Add increment as identified in #10768 (v1.60.x backport )

xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java, xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java, xds/src/main/java/io/grpc/xds/ControlPlaneClient.java, xds/src/main/java/io/grpc/xds/XdsClient.java, xds/src/main/java/io/grpc/xds/XdsClientImpl.java, xds/src/main/java/io/grpc/xds/XdsNameResolver.java, xds/src/main/java/io/grpc/xds/XdsServerWrapper.java, xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java, xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java, xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java, xds/src/test/java/io/grpc/xds/XdsClientImplV3Test.java, xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java, xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java, xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java
Fix b/317237071
Rollback of https://github.com/grpc/grpc-java/pull/10784
=> xds: fix flow control message not delivered when previous message type is unknown

binder/src/androidTest/java/io/grpc/binder/internal/LeakSafeOneWayBinderTest.java, binder/src/main/java/io/grpc/binder/internal/BinderTransport.java, binder/src/main/java/io/grpc/binder/internal/LeakSafeOneWayBinder.java
See https://developer.android.com/reference/android/os/IBinder#FLAG_ONEWAY
=> binder: oneway txns cannot arrive out of order

util/src/test/java/io/grpc/util/MultiChildLoadBalancerTest.java, util/src/testFixtures/java/io/grpc/util/AbstractTestHelper.java
Create a unit test for basic functionality of both MultiChildLoadBalancer and Endpoint.
=> util:create a test for MultiChildLoadBalancer and Endpoint

xds/src/main/java/io/grpc/xds/CsdsService.java, xds/src/test/java/io/grpc/xds/CsdsServiceTest.java
Redoes https://github.com/grpc/grpc-java/pull/8028
Ref cl/365582959
=> xds: (minor) address Java Code Clarity recommendations in CSDS

RELEASING.md
Makes it easier to track down / credit the author.
=> RELEASING.md: Include author email in shortlog

README.md
Note that protoc reference is updated to 3.25.1 as well.
=> Update README etc to reference 1.61.0

java_grpc_library.bzl
To support runfiles, the rule has to track more than just the executable. `files_to_run` has both the runfile and executable information (as separate fields), as does `files`, (combined as depset). So using those when able is inherently "safe." `files_to_run.executable` is only the executable, so does not propagate dependency information, so we make sure to pass `files` to the rule in addition. (`files_to_run.executable` is formatted into a string, so it wouldn't carry depset information anyway.)
As originally noticed in cl/597962426
=> java_grpc_library.bzl: Support runfiles for protoc and the plugin

api/src/main/java/io/grpc/LoadBalancer.java, core/src/main/java/io/grpc/internal/GrpcUtil.java, core/src/main/java/io/grpc/internal/PickFirstLeafLoadBalancer.java, core/src/test/java/io/grpc/internal/PickFirstLeafLoadBalancerTest.java
Fix the Happy Eyeballs work (pr #10486) done by Tony on PickFirstLeafLoadBalancer and enhance tests.
=> internal:Happy eyeballs

googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolver.java, googleapis/src/test/java/io/grpc/googleapis/GoogleCloudToProdNameResolverTest.java
=> Add check for empty addresses and if not there disable ipV6.

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java, interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java
Trying to reduce bogus CI test fails.
=> Relax some timeouts that have been flaky for the automated CI testing.

xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java, xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java
backport of https://github.com/grpc/grpc-java/pull/10868
=> xds: fix NPE in wrr in TF state [1.60.x backport]

core/src/main/java/io/grpc/internal/AbstractClientStream.java, core/src/main/java/io/grpc/internal/RetriableStream.java, interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java, testing/src/main/java/io/grpc/internal/testing/StatsTestUtils.java
=> Fix retries that timeout hanging forever. [ Backport to 1.60.x]

xds/src/main/java/io/grpc/xds/XdsListenerResource.java, xds/src/main/java/io/grpc/xds/XdsResourceType.java
For the xds-for-stubby purpose
cc. @ejona86
=> xds: hide TlsContextManager in XdsResourceType.Args

xds/src/main/java/io/grpc/xds/XdsClient.java
fix https://github.com/grpc/grpc-java/pull/10864
=> xds: mark XdsClient as experimental API

interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java
The RetryTest was flaky, and it seems to have been caused by the client and server getting assigned to the same event loop. Separating the two reduces the flake rate from ~3% to less than 0.1% (no flakes in a 1000).
While I was here fixing the executors, I reduced the number of threads created and shut down the threads after they are no longer used. This had no impact to the flake rate (no flakes in 1000).
=> interop-testing: Use separate event loops in RetryTest

build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-debug/build.gradle, examples/example-debug/pom.xml, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-gcp-observability/build.gradle, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-oauth/build.gradle, examples/example-oauth/pom.xml, examples/example-orca/build.gradle, examples/example-reflection/build.gradle, examples/example-servlet/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
=> Start 1.63.0 development cycle

api/src/main/java/io/grpc/Server.java
Fix https://github.com/grpc/grpc-java/issues/5332
=> api: stabilize server.getListenerSockets

xds/src/main/java/io/grpc/xds/LeastRequestLoadBalancer.java, xds/src/test/java/io/grpc/xds/LeastRequestLoadBalancerTest.java
This is similar to the changes to round robin in dca89b25.
=> xds: Replace isEquivalentTo with equals in LeastRequest

binder/src/test/java/io/grpc/binder/MainThreadScheduledExecutorService.java, binder/src/test/java/io/grpc/binder/RobolectricBinderSecurityTest.java
So it can be used by other robolectric tests.
=> Factor out MainThreadScheduledExecutorService.

util/src/test/java/io/grpc/util/MultiChildLoadBalancerTest.java
CI was broken by PR #10780, this fixes it
=> Fix compile failures blocking CI

README.md, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, compiler/src/testLite/golden/TestDeprecatedService.java.txt, compiler/src/testLite/golden/TestService.java.txt
=> Release v1.62.0

README.md
Because of the mess with the 1.62 release, there isn't a commit to cherry pick.
=> Update README to v1.62.2

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
The local race passes `rlsPicker` to the channel before CachingRlsLbClient is finished constructing. `RlsPicker` can use multiple of the fields not yet initialized. This seems not to be happening in practice, because it appears like it would break things very loudly (e.g., NPE).
The remote race seems incredibly hard to hit, because it requires an RPC to complete before the pending data tracking the RPC is added to a map. But with if a system is at 100% CPU utilization, maybe it can be hit. If it is hit, all RPCs needing the impacted cache entry will forever be buffered.
CC @temawi 
Backport of #10995
=> rls: Fix a local and remote race (1.62.x backport)

api/src/main/java/io/grpc/Attributes.java
Now tracked together with Attributes: https://github.com/grpc/grpc-java/issues/1764.
Closes #5777.
=> api: Remove ExperimentalApi from Attributes.Builder#discard

core/src/main/java/io/grpc/internal/PickFirstLeafLoadBalancer.java
=> core: Eliminate NPE seen in PickFirstLeafLoadBalancer

opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryMetricsModule.java
In OpenCensus recording an attempt was delayed in order to wait for inboundUncompressedSize(). But we don't need that in OpenTelemetry, and could have removed this code when copying from OpenCensus.
=> opentelemetry: Remove delayed attempt recording

opentelemetry/src/main/java/io/grpc/opentelemetry/OpenTelemetryMetricsModule.java
=> opentelemetry: Fix checking wrong metric for null

api/src/testFixtures/java/io/grpc/NoopMetricSink.java, rls/build.gradle, rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
=> rls: Add metric test with real channel

core/src/main/java/io/grpc/internal/PickFirstLeafLoadBalancer.java, core/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java, core/src/test/java/io/grpc/internal/PickFirstLeafLoadBalancerTest.java, rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java, xds/src/main/java/io/grpc/xds/XdsEndpointResource.java, xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java, xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java
Some g3 users are seeing problems.
Put the flag logic in a common place for PickFirstLeafLoadBalancer & WRR's test.
Backport of #11120
=> Change HappyEyeballs and new pick first LB flags default value to false (1.64.x backport)

api/src/testFixtures/java/io/grpc/NoopMetricSink.java, rls/build.gradle, rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
=> rls: Add metric test with real channel (1.64.x backport)

xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java
=> xds: Add WRR metric test with real channel (1.64.x backport)

opentelemetry/src/main/java/io/grpc/opentelemetry/GrpcOpenTelemetry.java
=> opentelemetry: Mark registerGlobal() as experimental

gradle/libs.versions.toml, interop-testing/build.gradle, interop-testing/src/main/java/io/grpc/testing/integration/XdsTestClient.java, interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java
~TODO: Don't submit until xds-test-descriptions.md is updated~ Decided not to wait
=> interop-testing: Add gcp-csm-o11y testing support

gcp-csm-observability/src/main/java/io/grpc/gcp/csm/observability/MetadataExchanger.java
This fixes csm_remote_workload_namespace_name being unknown when running the interop test.
=> gcp-csm-o11y: Add resource attributes from environment

binder/src/androidTest/java/io/grpc/binder/internal/BinderTransportTest.java, binder/src/androidTest/java/io/grpc/binder/internal/LeakSafeOneWayBinderTest.java, binder/src/main/java/io/grpc/binder/internal/BinderServer.java, binder/src/main/java/io/grpc/binder/internal/LeakSafeOneWayBinder.java
Fixes https://github.com/grpc/grpc-java/issues/8931
=> Reply to SETUP_TRANSPORT post-BinderServer shutdown

build.gradle, compiler/src/test/golden/TestDeprecatedService.java.txt, compiler/src/test/golden/TestService.java.txt, core/src/main/java/io/grpc/internal/GrpcUtil.java, examples/android/clientcache/app/build.gradle, examples/android/helloworld/app/build.gradle, examples/android/routeguide/app/build.gradle, examples/android/strictmode/app/build.gradle, examples/build.gradle, examples/example-alts/build.gradle, examples/example-debug/build.gradle, examples/example-debug/pom.xml, examples/example-gauth/build.gradle, examples/example-gauth/pom.xml, examples/example-gcp-observability/build.gradle, examples/example-hostname/build.gradle, examples/example-hostname/pom.xml, examples/example-jwt-auth/build.gradle, examples/example-jwt-auth/pom.xml, examples/example-oauth/build.gradle, examples/example-oauth/pom.xml, examples/example-orca/build.gradle, examples/example-reflection/build.gradle, examples/example-servlet/build.gradle, examples/example-tls/build.gradle, examples/example-tls/pom.xml, examples/example-xds/build.gradle, examples/pom.xml
FYI: I'm following the first part of https://github.com/grpc/grpc-java/blob/master/RELEASING.md (this is step 3 of "Branching the Release")
=> Start 1.66.0 development cycle

okhttp/src/main/java/io/grpc/okhttp/OkHttpServerTransport.java
MacOS is consistently failing the CI build, so can't do version updates for release. This should unblock.
Using --runs_per_test=1000, this changes the flake rate of TlsTest from 2% to 0%.
While I believe it is possible to write a reliable test for this (including noticing the SSLSocket behavior), it was becoming too invasive so I gave up.
Fixes #11012
Backport of #11266
=> okhttp: Workaround SSLSocket not noticing socket is closed (1.64.x backport)

README.md
Reverts grpc/grpc-java#11331
Was squashed - reverting
=> Revert "Release v1.64.1"

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java, core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
Context: https://github.com/grpc/grpc-java/issues/11274
=> grpc-core: use retryThrottling from defaultServiceConfig

buildscripts/kokoro/xds_k8s_lb.cfg
Increased timeout of the LB test suite to 5 hours
=> [LB] Increase Java PSM LB test timeout to 300 min

api/src/main/java/io/grpc/PartialMetricInstrument.java
This makes it much easier when testing to understand what the values/arguments are at various parts of the code.
=> api: Give instruments a toString() including their name

xds/src/test/java/io/grpc/xds/FakeControlPlaneXdsIntegrationTest.java
This can detect failures like the UnsupportedOperationException from ebffb0a6.
=> xds: Add test that uses real DnsNR with ClusterResolverLB

core/src/main/java/io/grpc/internal/PickFirstLeafLoadBalancer.java
Each usage of the subchannel immediately looked up the SubchannelData.
=> core: In PF, pass around SubchannelData instead of Subchannel

xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
There's no need to assume which child makes a subchannel based on the subchannel address.
=> xds: Replace WrrHelper with a per-child Helper

cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java, cronet/src/main/java/io/grpc/cronet/InternalCronetChannelBuilder.java
=> cronet: Add internal API to specify Network

buildscripts/kokoro/psm-dualstack.cfg
=> Add dualstack interop test kokoro config (1.66.x backport)

core/src/main/java/io/grpc/internal/PickFirstLeafLoadBalancer.java, core/src/test/java/io/grpc/internal/PickFirstLeafLoadBalancerTest.java
Each commit describes why the change was made.
=> core: Many small PickFirstLeafLb cleanups

util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java, xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java
This makes ClusterManagerLB more straight-forward, focusing on just the things that are relevant to it, and it avoids specialized map key handling in updateChildrenWithResolvedAddresses().
-----
FYI: This is the last of my MultiChildLB commit series.
=> Focus MultiChildLB updates around ResolvedAddresses of children

s2a/build.gradle
There may be more unused deps, but #11527 makes it far too painful for me to bother to clean it up more.
CC @rmehta19
=> s2a: Use new-style syntax for plugins and remove unused deps

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
If a panic is followed a panic, we'd ignore the second. But if an exception happens while entering panic mode we may fail to update the picker with the first error. This is "fine" from a correctness standpoint; all bets are off when panicking and we've already logged the first error. But failing RPCs can often be more easily seen than just the log.
Noticed because of http://yaqs/8493785598685872128
=> core: Handle NR/LB exceptions when panicking

api/src/main/java/io/grpc/StatusRuntimeException.java
=> Fix javadoc

stub/src/main/java/io/grpc/stub/ServerCalls.java, stub/src/test/java/io/grpc/stub/ServerCallsTest.java
This reverts commit 99f86835ed8a1c960d532e58b5fd51ec1bb99825.
The change doesn't handle `null` messages, which don't happen with protobuf, but can happen with other marshallers, especially in tests. See cl/689445172
This will reopen #5969
CC @NaveenPrasannaV
=> Revert "stub: Ignore unary response on server if status is not OK"

documentation/android-binderchannel-status-codes.md
https://developer.android.com/about/versions/15/behavior-changes-15#safer-intents
=> Update error codes cheat sheet for the new "Safer Intent" rules.

xds/src/test/java/io/grpc/xds/XdsSecurityClientServerTest.java
When spiffe support was added it caused
tlsClientServer_useSystemRootCerts_validationContext to become flaky. This is because test execution order was important for whether the race would occur.
Fixes #11678
-----
No failures in 2000 runs, when previously it was close to 1% in my testing environment.
=> xds: Fix XdsSecurityClientServerTest TrustManagerStore race

gradle/libs.versions.toml
This should have been done as part of 2b4f649b
=> Bump android animalsniffer signature to API 21

okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/OkHostnameVerifier.java
Implement fix to address a security issue related to maliciously crafted hostnames during certificate validation in OkHttp
grpc-java is susceptible to [CVE-2021-0341](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-0341)
This mirrors the okhttp patch for this exploit available in https://github.com/square/okhttp/pull/6353
Backport of #11749
=> fix security issue with okhttp (1.69.x backport)

servlet/src/main/java/io/grpc/servlet/ServletServerStream.java
=> servlet: remove 4096 min buffer size

rls/src/main/java/io/grpc/rls/RlsProtoConverters.java, rls/src/test/java/io/grpc/rls/RlsProtoConvertersTest.java
=> rls: allow maxAge to exceed 5m if staleAge is set

examples/README.md
Small PR - Commit 0f5f07f87696b37b91df55fc42d49c61742fd93e moved `foam-logging-in-vscode.md`. This PR adjusts sources to changes.
=> examples: Update InProcess sources in examples

util/src/main/java/io/grpc/util/GracefulSwitchLoadBalancer.java, util/src/test/java/io/grpc/util/GracefulSwitchLoadBalancerTest.java, xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java
I think at some point there were more usages in the tests. But now it is pretty easy.
=> util: Replace BUFFER_PICKER with FixedResultPicker

api/src/main/java/io/grpc/InternalConfigSelector.java, core/src/main/java/io/grpc/internal/RetriableStream.java, xds/src/main/java/io/grpc/xds/package-info.java
I found small typo while I was analyzing grpc-java soure code.
I think that PRC in comment actually means RPC.
If my PR is incorrect, please let me know. Then I will close this PR myself.
Thank you for your reading.
=> (minor) Fix comment's typo

xds/src/main/java/io/grpc/xds/XdsClusterResource.java, xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java
It has seen good testing by users and behaved as expected.
Fixes #11996
-----
CC @atollena, @yannickepstein
=> xds: Enable least request by default

alts/src/main/java/io/grpc/alts/HandshakerServiceChannel.java
This adds a flag to use experimental timeouts for the ALTS library
Backport of #12076
CC @gtcooke94
=> alts: add experimental keepalive (1.73.x backport)

xds/src/main/java/io/grpc/xds/GcpAuthenticationFilter.java, xds/src/test/java/io/grpc/xds/GcpAuthenticationFilterTest.java
Backport of #11992 to v1.72.x.
---
null
=> xds: float LRU cache across interceptors (v1.72.x backport)

xds/BUILD.bazel, xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java, xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java, xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancerProvider.java, xds/src/main/java/io/grpc/xds/Endpoints.java, xds/src/main/java/io/grpc/xds/GcpAuthenticationFilter.java, xds/src/main/java/io/grpc/xds/MetadataRegistry.java, xds/src/main/java/io/grpc/xds/XdsClusterResource.java, xds/src/main/java/io/grpc/xds/XdsEndpointResource.java, xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java, xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java, xds/src/test/java/io/grpc/xds/GrpcXdsClientImplDataTest.java, xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java, xds/src/test/java/io/grpc/xds/XdsTestUtils.java, xds/third_party/envoy/import.sh, xds/third_party/envoy/src/main/proto/envoy/extensions/transport_sockets/http_11_proxy/v3/upstream_http_11_connect.proto
Backport of #11861 to v1.71.x.
---
Implements gRFC A86 (https://github.com/grpc/proposal/pull/455)
=> xds: xDS-based HTTP CONNECT configuration (v1.71.x backport)

core/src/main/java/io/grpc/internal/InternalSubchannel.java
=> core: Use lazy message formatting in checkState

binder/src/androidTest/java/io/grpc/binder/internal/BinderClientTransportTest.java
Related to comments in CR/769886275.
=> Mark a few test helper methods as @CanIgnoreReturnValue

xds/src/main/java/io/grpc/xds/client/XdsClientImpl.java, xds/src/test/java/io/grpc/xds/GrpcXdsClientImplTestBase.java
Backport of #12262 to v1.75.x.
---
Fixes #11672
=> xds: xdsClient caches transient error for new watchers (v1.75.x backport)

gradle/libs.versions.toml, servlet/src/main/java/io/grpc/servlet/AsyncServletOutputStreamWriter.java
This should fix #12268
Credits go to @ejona86 for https://github.com/grpc/grpc-java/pull/9948#issuecomment-1485353980
=> servlet: fix unpark() of onWritePossible() thread
