grpc/grpc-java

.github/lock.yml

The earlier year was just for testing. Things are working as we'd hope.
Choosing 90 days for now. If an issue is closed at the beginning of a
release cycle, that gives release cycle + 6 weeks to upgrade, which
seems plenty. Worst-case, is users open a new issue referencing the old
one they found.

github/lock.yml: Lock GitHub issues after 90 days

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

Getting the authority must not rely on the name resolver being
non-null, because that can trivially happen if the channel is shut
down.

core: permanently store authority at channel creation

---

alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java
alts/src/test/java/io/grpc/alts/internal/AltsProtocolNegotiatorTest.java
core/src/main/java/io/grpc/Attributes.java
core/src/main/java/io/grpc/CallCredentials.java
core/src/main/java/io/grpc/ClientCall.java
core/src/main/java/io/grpc/EquivalentAddressGroup.java
core/src/main/java/io/grpc/Grpc.java
core/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/NameResolver.java
core/src/main/java/io/grpc/ServerCall.java
core/src/main/java/io/grpc/internal/GrpcAttributes.java

Keys and Attributes instances are annotated with the following annotations:
1. `Grpc.TransportAttr`: transport attributes returned by `{Client,Server}Call.getAttributes()`.
2. `NameResolver.ResolutionResultAttr`: attributes passed as the argument of `NameResolver.Listener.onAddresses()` and `LoadBalancer.handleResolvedAddressGroups()`
3. `EquivalentAddressGroup.Attr`: attributes from `EquivalentAddressGroups`.
This is a better form of documentation than plan words in javadoc. Uses of an annotation is searchable in IDE and javadoc.

doc: organize Attributes with annotations.

---

alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java
alts/src/main/java/io/grpc/alts/internal/GoogleDefaultProtocolNegotiator.java
netty/src/main/java/io/grpc/netty/InternalNettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/ProtocolNegotiator.java
netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java

There's two commits here that are easiest to review separately. Removing the FilterFactory was necessary to have a clear lifecycle of the ProtocolNegotiator.
@jiangtaoli2016, after this is merged you can plumb cleanup login in ALTS.
After this is approved but before merging I'll add the necessary close() internally, to make the sync easy.

netty: Remove TransportCreationParamsFilterFactory and add ProtocolNegotiator.close

---

alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java
alts/src/test/java/io/grpc/alts/internal/AltsProtocolNegotiatorTest.java
core/src/main/java/io/grpc/Grpc.java
core/src/main/java/io/grpc/inprocess/InProcessTransport.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java

core: add Grpc.TRANSPORT_ATTR_LOCAL_ADDR

---

services/src/main/java/io/grpc/services/BinaryLogProviderImpl.java
services/src/main/java/io/grpc/services/BinaryLogs.java

Do not require binlog str to be defined by env var.
This allows --flag=value styled configuration, which is more common
internally.

services: allow config str to be passed into binlog object

---

services/src/main/java/io/grpc/services/BinlogHelper.java
services/src/test/java/io/grpc/services/BinlogHelperTest.java

The callback must be forwarded otherwise the RPC hangs.

services: fix callbacks not being forwarded in binlog interceptors

---

okhttp/src/main/java/io/grpc/okhttp/AsyncFrameWriter.java
okhttp/src/test/java/io/grpc/okhttp/AsyncFrameWriterTest.java

AsyncFrameWriter quietly log when socket is already closed. 
also, default log level down to INFO which is same as NettyServerTransport.
resolves #3046

okhttp: make AsyncFrameWriter quietly log

---

auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java
core/src/main/java/io/grpc/CallCredentials.java
core/src/main/java/io/grpc/CallCredentials2.java
core/src/main/java/io/grpc/inprocess/InProcessTransport.java
core/src/main/java/io/grpc/internal/CallCredentialsApplyingTransportFactory.java
core/src/main/java/io/grpc/internal/GrpcAttributes.java
core/src/main/java/io/grpc/internal/MetadataApplierImpl.java
core/src/test/java/io/grpc/internal/CallCredentials2ApplyingTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java
cronet/src/test/java/io/grpc/cronet/CronetClientTransportTest.java
netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java

This is the first step of introducing the 2nd edition of CallCredentials API (#4901)
Security level and authority are parameters required to be passed to
applyRequestMetadata(). This change wraps them, along with
MethodDescriptor and the transport attributes to RequestInfo, which is
more clear to the implementers.
ATTR_SECURITY_LEVEL is moved to the internal GrpcAttributes and
annotated as TransportAttr, because transports are required to set it,
but no user is actually reading them from
{Client,Server}Call.getAttributes().
ATTR_AUTHORITY is removed, because no transport is overriding it.
All involved interfaces are changed to abstract classes, as this will
make further API changes smoother.

core: add CallCredentials2 and deprecate CallCredentials' old interface

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

(I think this will always be non-null, but I am not certain)

core: include what name resolver was used when it fails

---

run-test-client.sh
run-test-server.sh

This reduces the amount of logspam generated during interop testing.
Telling someone how to build when they have already obviously built
doesn't serve much purpose, now that everyone is used to it not
building automatically.

Avoid interop build instructions when already built

---

netty/src/test/java/io/grpc/netty/NettyServerTest.java

Null is never allowed, so will cause exceptions and not behave properly.

netty: Don't return null ServerTransportListener in tests

---

testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java

The transport test flakes at the timeout(100) about .05% of the time.
There's really no reason it should have a smaller timeout compared to
the other timeouts.
The timeout(250) wasn't flaking at all, but it should follow the
convention.

testing: Wait for TIMEOUT_MS instead of 100ms

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java

Use smaller DNS cache TTL (2s) for android device, this value default on android. For more detail see #4942.
Resolves #4942

core: android use smaller(2s) DNS cache TTL

---

services/src/main/java/io/grpc/services/HealthServiceImpl.java
services/src/test/java/io/grpc/services/HealthStatusManagerTest.java

services: implement Health.Watch

---

core/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/inprocess/InProcessTransport.java
core/src/main/java/io/grpc/internal/AbstractClientStream.java
core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/main/java/io/grpc/internal/InUseStateAggregator.java
core/src/main/java/io/grpc/internal/InternalSubchannel.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/OobChannel.java
core/src/main/java/io/grpc/internal/SubchannelChannel.java
core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java
netty/src/main/java/io/grpc/netty/CreateStreamCommand.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyClientStream.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientStreamTest.java
testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java

Returns a Channel that allows a LoadBalancer to make auxiliary RPCs on already-established application connections.  We need this to implement client-side health-checking (#4932)
See comments on the API for its semantics.
Notable changes:
- Transports are modified to use InUseStateAggregator so that they can exclude RPCs made on Subchannel.asChannel() when reporting in-use state for idle mode.
- OobChannel shares the same Executor as Subchannel.asChannel(). Because the latter is not a ManagedChannel and doesn't have life-cycle, thus can't determine when to return the Executor to a pool, the Executor is now returned only when ManagedChannelImpl is terminated.

core: add internal Subchannel.asChannel()

---

core/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/util/ForwardingLoadBalancerHelper.java
core/src/test/java/io/grpc/PickFirstLoadBalancerTest.java
core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
grpclb/src/test/java/io/grpc/grpclb/CachedSubchannelPoolTest.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

Those overrides are kept for backward compatibility and convenience
for callers.  Documentation already says implementations should not
override them.  Making them final reduces confusion around which
override should be verified in tests and be overridden in forwarding
classes, thus prevents bugs caused by such confusion.

core: finalize convenient overrides on LoadBalancer.Helper and Subchannel.

---

.travis.yml

oracle10 is failing during setup with:
The command "bash install-jdk.sh -F 10 -L BCL --target $JAVA_HOME --workspace ${TRAVIS_HOME}/.cache/install-jdk" failed and exited with 8 during .
We should be adding support for Java 11 and dropping Java 9-10 anyway,
since Java 9-10 are unsupported.

travis: Drop testing for Java 10

---

.travis.yml

oracle10 is failing during setup with:
The command "bash install-jdk.sh -F 10 -L BCL --target $JAVA_HOME --workspace ${TRAVIS_HOME}/.cache/install-jdk" failed and exited with 8 during .
We should be adding support for Java 11 and dropping Java 9-10 anyway,
since Java 9-10 are unsupported.
-----
This is a backport of #4957

travis: Drop testing for Java 10 (1.16 backport)

---

.travis.yml
alts/build.gradle
build.gradle
compiler/build.gradle
examples/build.gradle
examples/pom.xml
netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
services/build.gradle

It appears everything was already working on Java 11, except
build-specific and testing issues. Updating to Netty 4.1.30 (#4940)
probably fixed the last true Java 11 incompatibility.
Fixes #4933

Add build support for Java 11

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java

Backport of #4953 
Updates #4951

core: throw exception on resolution failure and no jndi resolver (1.16 backport)

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java

Roll forward the PR (#4812), rollback is #4947, with a change that no cache for android environment.

core: roll forward DNS cache except for android

---

core/src/main/java/io/grpc/ForwardingChannelBuilder.java
core/src/main/java/io/grpc/ManagedChannelBuilder.java
core/src/main/java/io/grpc/ServerBuilder.java
core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
core/src/main/java/io/grpc/inprocess/InProcessServer.java
core/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java
core/src/main/java/io/grpc/inprocess/InProcessTransport.java
core/src/test/java/io/grpc/ForwardingChannelBuilderTest.java
core/src/test/java/io/grpc/ForwardingTestUtil.java
core/src/test/java/io/grpc/inprocess/InProcessServerTest.java
core/src/test/java/io/grpc/inprocess/InProcessTransportTest.java
core/src/test/java/io/grpc/util/ForwardingLoadBalancerHelperTest.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
netty/src/test/java/io/grpc/netty/NettyServerBuilderTest.java
netty/src/test/java/io/grpc/netty/NettyTransportTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpTransportTest.java
testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java

Support was added to InProcess and OkHttp transports. As mentioned
in #4567 OkHttp will not actually limit the memory used.
This API was a minor rename to the pre-existing Netty API,
so has already undergone API review and thus is not ExperimentalApi.
In adding transport tests I discovered Netty's behavior for trailers is
broken causing the stream to be orphaned and the client to hang. I have
verified this is fixed by https://github.com/netty/netty/pull/8332 .
The commits will remain separate when merging. They may help during
review, but probably aren't too necessary.
Fixes #4050 and #4567.
CC @garrettjonesgoogle

Add ManagedChannelBuilder/ServerBuilder.maxInboundMetadataSize

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java

This change is mainly to fix a test, but it also is an implementation of the proposal here: https://github.com/grpc/proposal/pull/79
In short:
* Do not do SRV or TXT lookups when the target name is `localhost`.  This can be overriden by a system property
* Do not do SRV or TXT lookups when the target name is an IPv6 or IPv4 address.  This _cannot_ be overriden.  The constructed domains for these queries would themselves not be valid.  (e.g. _grpclb._tcp.192.168.0.1)
* Speeds up initial connection when communicating over local host, since it is extremely uncommon that such a connection would need gRPCLB or SRV records
I expect to remove the system property after a release if no one asks about it.   
cc: @apolcyn

core: ignore localhost and IP addresses for JNDI

---

core/src/main/java/io/grpc/EquivalentAddressGroup.java
core/src/main/java/io/grpc/Grpc.java
core/src/main/java/io/grpc/NameResolver.java

Also annotate NameResolver.Listener as experimental because
annotations of an outer class don't show in the javadoc page of its
inner classes.

core: annotate Attributes key annotations as experimental API.

---

alts/src/test/java/io/grpc/alts/internal/FakeTsiHandshaker.java
benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncServer.java
build.gradle
core/src/main/java/io/grpc/Metadata.java
core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/test/java/io/grpc/MetadataTest.java
core/src/test/java/io/grpc/ServerServiceDefinitionTest.java
core/src/test/java/io/grpc/ServiceDescriptorTest.java
core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java
core/src/test/java/io/grpc/internal/ServerCallImplTest.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceImpl.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceServer.java
interop-testing/src/test/java/io/grpc/testing/integration/NettyFlowControlTest.java
netty/src/jmh/java/io/grpc/netty/InboundHeadersBenchmark.java
netty/src/main/java/io/grpc/netty/CancelServerStreamCommand.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/netty/SendGrpcFrameCommand.java
netty/src/main/java/io/grpc/netty/SendResponseHeadersCommand.java
netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersUtilsTest.java
netty/src/test/java/io/grpc/netty/GrpcHttp2InboundHeadersTest.java
netty/src/test/java/io/grpc/netty/UtilsTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/OkHostnameVerifier.java
services/src/main/java/io/grpc/services/BinlogHelper.java
services/src/main/java/io/grpc/services/ChannelzProtoUtil.java
services/src/test/java/io/grpc/protobuf/services/ProtoReflectionServiceTest.java

This will allow enabling Error Prone on JDK 10+ (after
updating the net.ltgt.errorprone plugin), and is also a
prerequisite to that plugin update.
Also remove net.ltgt.apt plugin, as Gradle has native
support for annotationProcessor.

all: update Error Prone to 2.3.2

---

core/src/main/java/io/grpc/EquivalentAddressGroup.java
core/src/main/java/io/grpc/Grpc.java
core/src/main/java/io/grpc/NameResolver.java

Also annotate NameResolver.Listener as experimental because
annotations of an outer class don't show in the javadoc page of its
inner classes.
This is a backport of #4974

core: annotate Attributes key annotations as experimental API. (#4974) (1.16.x backport)

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java

This change is mainly to fix a test, but it also is an implementation of the proposal here: https://github.com/grpc/proposal/pull/79
In short:
* Do not do SRV or TXT lookups when the target name is `localhost`.  This can be overriden by a system property
* Do not do SRV or TXT lookups when the target name is an IPv6 or IPv4 address.  This _cannot_ be overriden.  The constructed domains for these queries would themselves not be valid.  (e.g. _grpclb._tcp.192.168.0.1)
* Speeds up initial connection when communicating over local host, since it is extremely uncommon that such a connection would need gRPCLB or SRV records
I expect to remove the system property after a release if no one asks about it.

core: ignore localhost and IP addresses for JNDI (1.16.x backport)

---

alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java
alts/src/test/java/io/grpc/alts/internal/AltsProtocolNegotiatorTest.java
auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java
core/src/main/java/io/grpc/CallCredentials.java
core/src/main/java/io/grpc/CallCredentials2.java
core/src/main/java/io/grpc/internal/CallCredentialsApplyingTransportFactory.java
core/src/main/java/io/grpc/internal/GrpcAttributes.java
core/src/test/java/io/grpc/internal/CallCredentials2ApplyingTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

This reverts commit ef8a84421d821e01185c289a4f1fb502a003c4f3.
Firebase is not yet ready to migrate to the new API. Will try again once we made the release and migrated them to CallCredentials2.

Revert "core: promote CallCredentials API v2. (#4952)"

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java

This reverts commit 189991012bbff42b975c51045c32efceaa07f462.
resolves #4948

Revert "core: DnsNameResolver caches refresh (#4812)" (1.16.x backport)

---

.travis.yml
core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java

This reverts commit 189991012bbff42b975c51045c32efceaa07f462.

Revert "core: DnsNameResolver caches refresh (#4812)" (1.15.x backport)

---

grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

Previously the client waits ~10 seconds until the fallback timer has
expired. While the timer is useful to address the long tail, it
shouldn't delay using the fallback in case of obvious errors, like the
channel failing to connect or an UNIMPLEMENTED response.
Resolves #4987

grpclb: enter fallback when LB stream broken even before fallback timer expires

---

grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

Previously the client waits ~10 seconds until the fallback timer has
expired. While the timer is useful to address the long tail, it
shouldn't delay using the fallback in case of obvious errors, like the
channel failing to connect or an UNIMPLEMENTED response.
This is a cherry-pick of b701e8920daaccf9e6eb2916d2ea94da8df74be5 (#4990) from master.

grpclb: enter fallback when LB stream broken even before fallback timer expires (#4990) (1.16.x backport)

---

android-interop-testing/build.gradle

This should fix a build issue we're seeing where a transitive dependency is not being pulled in properly from the google() repository when building an Android target. A successful build (e.g., [this one](https://source.cloud.google.com/results/invocations/877dd72a-cd1a-4926-b5b1-d2c93fb8c2a8/log)) is fetching com/android/tools/* packages from the google() repository. The failing jobs are trying to get Android related jars, including lint-gradle-api, from bintray instead. 
This brings our android-interop-test build file in line with our other android builds and places the google() repository at the head of the ordered list.

android-interop-testing: put google() repo first

---

android-interop-testing/build.gradle

android-interop-testing: put google() repo first (1.16.x backport)

---

core/src/main/java/io/grpc/internal/JndiResourceResolverFactory.java
core/src/test/java/io/grpc/internal/JndiResourceResolverTest.java

The trailing dot denotes the hostname to be absolute. It is fine to
leave, but removing it makes the authority match the more common form
and hopefully reduces confusion.
This happens to works around SNI failures caused when using gRPC-LB,
since SNI prohibits the trailing dot. However, that is not the reason
for this change as we have to support users directly providing a
hostname with the trailing dot anyway (and doing so is not hard).
See #4912 
---
This is fundamentally a 4 line change, but with more changes to make it testable.

core: Trim trailing dot from SRV hostnames

---

core/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/SynchronizationContext.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/SynchronizationContextTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

Because otherwise the user logic around Subchannel creation will
likely to race with handleSubchannelState().
Will log a warning if LoadBalancer.Helper.createSubChannel() is called
outside of the SynchronizationContext.
Adds SynchronizationContext.throwIfNotInThisSynchronizationContext()
to facilitate this warning.  It can also be used by LoadBalancer
implementations to make it a requirement.

core: suggest LoadBalancer.Helper.createSubChannel() to be called from SynchronizationContext

---

core/src/main/java/io/grpc/internal/TransportFrameUtil.java
core/src/test/java/io/grpc/internal/TransportFrameUtilTest.java
netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java
netty/src/main/java/io/grpc/netty/Utils.java
netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersUtilsTest.java
okhttp/src/main/java/io/grpc/okhttp/Utils.java
testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java

Following the [spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) on duplicate header names:
**Custom-Metadata** header order is not guaranteed to be preserved except for values with duplicate header names. Duplicate header names may have their values joined with "," as the delimiter and be considered semantically equivalent. Implementations must split Binary-Headers on "," before decoding the Base64-encoded values.

core,netty,testing: Support dup headers joined with commas

---

.travis.yml

This migrates us ahead of the forced migration, so if there are problems
the CI would still work while we work on them.
https://changelog.travis-ci.com/linux-builds-run-on-vms-by-default-77106

travis: Remove sudo: false, as it is going away

---

core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java

The ManagedChannelImpl change prevents any LB initialization failure
from producing a useless exception like:
```
java.lang.NullPointerException
at io.grpc.internal.ManagedChannelImpl.shutdownNameResolverAndLoadBalancer(ManagedChannelImpl.java:321)
at io.grpc.internal.ManagedChannelImpl.panic(ManagedChannelImpl.java:738)
at io.grpc.internal.ManagedChannelImpl$1.uncaughtException(ManagedChannelImpl.java:144)
```
Instead, now it will have the expected panic behavior of an INTERNAL
Status with a proper cause.
Since the NPE in AutoConfiguredLoadBalancerFactory wouldn't mean much to
users, it now has a more explicit message.

core: Improve error for Auto-LB configuration failure

---

benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadWorker.java

Fixes https://github.com/grpc/grpc/issues/17101.
According to the docs the `shutdownNow()` kills all the inflight calls (including quitWorker method) before they can finish and hence the C++ benchmark driver reports `driver.cc:550]  Worker 0 could not be properly quit because Received RST_STREAM with error code 8`  (I misinterpreted the msg earlier, the error code 8 seems to mean "cancelled" according to http/2 spec).
Before I was able to reproduce reliably locally and after this change, I'm unable to reproduce, so I assume it fixes the problem.

benchmarks: driverServer graceful shutdown

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
okhttp/src/main/java/io/grpc/okhttp/OutboundFlowController.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

OkHttp transport's memory usage by merging Buffers in each pending data.
- in OutboundFlowController and OkHttpClientStream
NOTE: Buffer allocate at least ~4KB memory even if the actual data is small.
NOTE: this PR is split from #4916, most review was done in that PR.
Resolves #4860

okhttp: Optimize memory usage by mergeing buffers

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java

core: remove I/O from DNS test which caused flaky test

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

This is intended to convert errors thrown in the KeepAliveManager to a more appropriate error status. It will also catch exceptions from `io.grpc.okhttp.internal.framed.FrameReader#nextFrame`, for which INTERNAL also seems like an appropriate status code.

okhttp: error in frame handler closes with INTERNAL

---

services/src/main/java/io/grpc/services/HealthCheckingLoadBalancerFactory.java
services/src/test/java/io/grpc/services/HealthCheckingLoadBalancerFactoryTest.java

The health checking balancer won't receive an update about Subchannel
shutdown via handleSubchannelState(), because no more callback will be
called after LoadBalancer.shutdown() is called.
Tracking issue: #4932

services: cancel health-check when LoadBalancer.shutdown() is called.

---

build.gradle

This adds support for Java 1.8.0_191 and 192

Bump Jetty ALPN to 2.0.9

---

build.gradle
core/src/main/java/io/grpc/internal/CensusStatsModule.java
core/src/main/java/io/grpc/internal/DeprecatedCensusConstants.java
core/src/test/java/io/grpc/internal/CensusModulesTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
repositories.bzl
testing/src/main/java/io/grpc/internal/testing/StatsTestUtils.java

Related to https://github.com/census-instrumentation/opencensus-java/issues/1207.
OpenCensus has updated the RPC constants in [Specs](https://github.com/census-instrumentation/opencensus-specs/blob/master/stats/gRPC.md) recently, and in OpenCensus-Java these new constants are added since v0.13.0. This PR updates gRPC to use the latest OpenCensus version, ~~and record stats against the new RPC constants.~~
~~Note that gRPC also needs to record stats against the deprecated constants, to keep backwards compatibility.~~
/cc @bogdandrutu @dinooliva @sebright

core: Update OpenCensus version. 

---

core/src/main/java/io/grpc/internal/InternalSubchannel.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
services/src/test/java/io/grpc/services/HealthCheckingLoadBalancerFactoryTest.java

Remove unused variables and prefer ArrayDeque to LinkedList. The swap to
Queue from Deque was just to make it more obvious what the usage was,
since the original swap to Deque was to avoid the same LinkedList lint
violation (3d51756d).

Lint fixes

---

netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java

some internally referenced codes are migrated to maxInboundMessageSize.
Resolves #2507

netty: finalize deprecating of maxMessageSize in NettyChannelBuilder.

---

services/src/test/java/io/grpc/services/BinlogHelperTest.java

getNanos will return the fractional nanos of the duration, which is
not the same as toNanos for durations larger than 1s.

services: use Durations.toNanos instead of Duration.getNanos

---

core/src/main/java/io/grpc/internal/TransportTracer.java
core/src/test/java/io/grpc/internal/MessageDeframerTest.java

core: use fakeClock in MessageDeframer tests to fix flaky test

---

core/src/main/java/io/grpc/ManagedChannelBuilder.java
core/src/main/java/io/grpc/ServerBuilder.java

New users are much more likely to use MCB to add an interceptor instead
of ClientInterceptors, so may not be aware of the interesting execution
order.
CC @xCASx

core: Explicitly mention MCB.intercept's execution order

---

core/src/main/java/io/grpc/internal/TimeProvider.java

We should reflect changes in the system clock.

core: TimeProvider should not assume that the clock never changes

---

.travis.yml
examples/example-kotlin/android/helloworld/build.gradle
examples/example-kotlin/build.gradle

- add CI for kotlin non-android
- bump kotlin version to fix kotlin compiler issue on jdk11
- add javax.annotation dep to fix kotlin build on jdk 9 & 11
Fixes #4725

 buildscript: Add CI for kotlin non-android

---

core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
services/src/main/java/io/grpc/services/HealthCheckingLoadBalancerFactory.java

Raise visibility of AutoConfiguredLoadBalancerFactory as internal
tests need to access it from a different package.
Rename HealthCheckingLoadBalancerFactory.LoadBalancerImpl to
*.HealthCheckingLoadBalancer so that its toString() output is more
informative.

core/services: test/debug friendlier

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

This also fixes the bug where NameResolverRefresh is not run from
syncContext if run from ScheduledExecutorService.

core: use SynchronizationContext.schedule() for NameResolver refresh

---

build.gradle
core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
core/src/main/java/io/grpc/internal/CensusStatsModule.java
core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
core/src/test/java/io/grpc/internal/AbstractServerImplBuilderTest.java
core/src/test/java/io/grpc/internal/CensusModulesTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

There are currently three boolean flags, and there will be one more
soon.  Put them all in the top-level class instead of passing them as
arguments on lower levels.

core: refactor flags in CensusStatsModule.

---

build.gradle
core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
core/src/main/java/io/grpc/internal/CensusStatsModule.java
core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
core/src/test/java/io/grpc/internal/AbstractServerImplBuilderTest.java
core/src/test/java/io/grpc/internal/CensusModulesTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
netty/src/main/java/io/grpc/netty/InternalNettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/InternalNettyServerBuilder.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
repositories.bzl

Real-time metrics are total sent/received bytes and messages per
method, and are updated as the events occur rather than at the end of
RPCs.
/cc @songy23

core: record real-time metrics to OpenCensus (updated to 1.18.0)

---

interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java

Upgrading from HTTP/1.1 to h2c (HTTP/2 in cleartext).
This is best avoided if possible (since it not widely implemented and comes at
the cost of a roundtrip), but a nice option to have.
Based on work by @xujianhai in #3529
Related to #3528 and fixes #4518
Not sure how to properly test this...

Client-side support for h2c via Upgrade #4518

---

stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java
stub/src/main/java/io/grpc/stub/ServerCalls.java
stub/src/test/java/io/grpc/stub/ServerCallsTest.java

This restrains a cancellation `Exception` when an `onCancelHandler` is set in `ServerCallStreamObserverImpl`. Fixes #5061.

stub: disable exception if onCancelHandler set

---

SECURITY.md
build.gradle
examples/build.gradle

The helloworld TLS example can not run properly with the outdated `examples/build.gradle`.

all: sync tcnative version

---

examples/README.md
examples/src/main/java/io/grpc/examples/helloworldtls/HelloWorldClientTls.java

Such as `./build/install/examples/bin/hello-world-server-tls` should be `./build/install/examples/bin/hello-world-tls-server`

examples: make corrections to document of helloworld tls example

---

repositories.bzl

The old native.http_archive is disabled by default in Bazel 0.20.0.

bazel: use new http_archive

---

core/src/main/java/io/grpc/util/RoundRobinLoadBalancerFactory.java

> ````java
> * @deprecated use {@link io.grpc.LoadBalancerRegistry#getProvider} with "round-robin" policy.  This
> *             class will be deleted soon.
> [...]
> LoadBalancerRegistry.getDefaultRegistry().getProvider("round_robin")
> ````
The name of the policy and the mentioned policy in the deprecation warning does not match.

core: Fix typo in RoundRobinLoadBalancerFactory's deprecation warning

---

stub/src/main/java/io/grpc/stub/StreamObservers.java

re: #4558
I encountered the same issue as @biran0079 was seeing where `onReady` was getting called again after `onComplete` had already been called, resulting in an exception because the channel had already been half closed. This simply tracks whether the stream has previously been completed and refuses to call `onComplete`.
I opted not to make this thread-safe because it seems like many of these interfaces are generally not thread-safe (and AFAICT this will only get called from one thread).

StreamObservers: make sure onComplete only gets called once from onReadyHandler

---

core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java

When service owner turns on grpclb through service config, it
shouldn't break existing clients that don't have grpclb in their
classpath.
Resolves #4602

core: do not fail RPCs if balancer address exists but grpclb is unavailable

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java

This effectively reverts c729a0f. This is necessary because #4602 is
not resolved.
-----
This change will only be applied to 1.17. 1.18 is receiving a behavior change
in #5129, but the behavior change is a bit too invasive for the release. In
addition it would have to be reimplemented due to changes to changes in
#4996 that prevent a clean backport merge.

core: disable SRV records lookup

---

core/src/main/java/io/grpc/ForwardingChannelBuilder.java
core/src/main/java/io/grpc/ManagedChannelBuilder.java
core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

ManagedChannelBuilder.loadBalancingFactory() overrides the proper
policy selection logic implemented in AutoConfiguredLoadBalancer, thus
has problems in cases where NameResolver returns balancer addresses,
because custom LoadBalancers normally don't differentiate between
normal server addresses with balancer addresses.  The policy selection
logic will filter out balancer addresses.

core: add ManagedChannelBuilder.defaultLoadBalancingPolicy()

---

examples/README.md

Try to make `examples/README.md` better organized. There may be multiple ways to re-structure it, and I'm not opposed to alternatives.

doc: restructure examples/README.md

---

core/src/main/java/io/grpc/CallOptions.java
core/src/test/java/io/grpc/CallOptionsTest.java

Previously, overwriting an existing Key would cause the original CallOptions instance to also be mutated.
See #5142  
Also adds a regression test for this issue.

core: Fix for issue #5142 (CallOptions mutability)

---

core/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/util/ForwardingLoadBalancer.java
core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

Currently ManagedChannelImpl will interpret empty address list from
NameResolver as an error, and LoadBalancer will NEVER receive an empty
list from handleResolvedAddressGroups().  There is a case in the
request-routing design where a LoadBalancer only receives service
config with which it constructs children NameResolver/LoadBalancer
pairs, thus no address is expected at this level.
canHandleEmptyAddressListFromNameResolution() is a signal to Channel
(and to the parent LoadBalancer in case of hierachical LoadBalancers)
about whether it accepts empty address lists.  The default is false,
which is the current behavior.
The logic is currently duplicated in ManagedChannelImpl and
AutoConfiguredLoadBalancer.  The one in ManagedChannelImpl will be
removed once we delete …

core: add LoadBalancer.canHandleEmptyAddressListFromNameResolution()

---

interop-testing/src/test/java/io/grpc/testing/integration/ProxyTest.java

This also reduces the time of the bandwidth tests from ~6 seconds to ~2,
each (they have about 1s of overhead).
Fixes #2951. The flake is very frequent in #4980.

interop-testing: Sample to reduce ProxyTest flakiness

---

interop-testing/src/test/java/io/grpc/testing/integration/ProxyTest.java

Fixing the flakiness is tracked in #2951. The current flakiness is ~3/8
fail.

interop-testing: Disable flaky ProxyTest.smallLatency

---

core/src/main/java/io/grpc/inprocess/InProcessServer.java
core/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java
core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
core/src/main/java/io/grpc/internal/StatsTraceContext.java
core/src/test/java/io/grpc/internal/AbstractServerImplBuilderTest.java
core/src/test/java/io/grpc/internal/ServerImplTest.java
netty/src/main/java/io/grpc/netty/NettyServer.java
netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/netty/NettyServerTransport.java

This change:
* makes Census tracing factories at the end of the user added ones
* makes more vars in AbstractServerImplBuilder package private
* annotates methods in ASIB to be clearer
* simplifies several of the setters to be single line
* Makes the generics on the Tracer factories proper

core,netty: refactor server builder

---

.bazelignore

"bazel build ..." from the root will no longer build examples/. But
"cd examples; bazel build ..." still does.

bazel: ignore examples/ from root WORKSPACE

---

alts/build.gradle
alts/src/main/java/io/grpc/alts/AltsChannelBuilder.java
alts/src/main/java/io/grpc/alts/AltsServerBuilder.java
alts/src/main/java/io/grpc/alts/GoogleDefaultChannelBuilder.java
alts/src/main/java/io/grpc/alts/HandshakerServiceChannel.java
alts/src/test/java/io/grpc/alts/HandshakerServiceChannelTest.java

Since the Resource shared the executor service between invocations, but
didn't null it out on shutdown, it could bring up a new channel with a
terminated event loop. The channel would then proceed to panic on usage.
I noticed this problem while looking into what was necessary for #4755.

alts: Fix SHARED_HANDSHAKER_CHANNEL after first close

---

repositories.bzl

The fundamental issue is that the SHA-1 sums for the GitHub and Maven jars for re2j are different. (see https://github.com/google/re2j/issues/83 for discussion.) the SHA used at grpc-java HEAD corresponds to the re2j GitHub jar, but the target itself refers to the re2j Maven jar.
The reason no one has noticed is that `@com_google_re2j//jar` is not actually used as a dependency in any bazel target in this repo. This will change once the services/ directory becomes a bazel package. (the source files in services/ do depend on re2j.)

repositories.bzl: correct re2j sha.

---

core/src/main/java/io/grpc/CallOptions.java

They are, but weren't consistently marked like the other members

Mark CallOptions' deadline/executor as @Nullable

---

alts/src/main/java/io/grpc/alts/internal/TsiFrameHandler.java
alts/src/test/java/io/grpc/alts/internal/TsiFrameHandlerTest.java

also, error / log messages will contain life-cycle state of FrameHandler.

alts: TsiFrameHandler doesn't throw exception when flush after closed

---

alts/src/test/java/io/grpc/alts/internal/TsiFrameHandlerTest.java

Build failed internally:
```
ERROR: /google/src/cloud/zdapeng/copybara_181B7ACA96E2E83A27C4518F7ABC90FE_0/google3/third_party/java_src/grpc/alts/BUILD:69:1: Building third_party/java_src/grpc/alts/libalts_test_lib.jar (29 source files) failed (Exit 1) java failed: error executing command third_party/java/jdk/jdk11-k8/bin/java -Xms3072m -Xmx3072m '-XX:MaxGCPauseMillis=20000' -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -Xverify:none -Xss5m '-XX:ErrorFile=/dev/stderr' ... (remaining 16 argument(s) skipped).  [forge_remote_host=ikpa6]
[5 / 6] Building third_party/java_src/grpc/alts/libalts_test_lib.jar (29 source files); 10s forge
third_party/java_src/grpc/alts/src/test/java/io/grpc/alts/internal/TsiFrameHandlerTest.java:74: error: reference to assertThat is ambiguous …
```

alts: Fix ambiguous assertThat() in TsiFrameHandlerTest

---

okhttp/src/test/java/io/grpc/okhttp/AsyncSinkTest.java

Build failed internally:
```
third_party/java_src/grpc/okhttp/src/test/java/io/grpc/okhttp/AsyncSinkTest.java:75: error: [MockitoAnyIncorrectPrimitiveType] Matcher mismatch: expected matcher for parameter of type 'long', found matcher for parameter of type 'int'
inOrder.verify(mockedSink).write(any(Buffer.class), anyInt());
^
(see site.mockito.org/usage/bugpattern/MockitoAnyIncorrectPrimitiveType)
Did you mean 'inOrder.verify(mockedSink).write(any(Buffer.class), anyLong());'?
third_party/java_src/grpc/okhttp/src/test/java/io/grpc/okhttp/AsyncSinkTest.java:94: error: [MockitoAnyIncorrectPrimitiveType] Matcher mismatch: expected matcher for parameter of type 'long', found matcher for parameter of type 'int'
inOrder.verify(mockedSink).write(any(Buffer.class), anyInt());
^
(see …
```

okhttp: fix MockitoAnyIncorrectPrimitiveType error in test

---

alts/src/main/java/io/grpc/alts/internal/AltsChannelCrypter.java
alts/src/main/java/io/grpc/alts/internal/AltsTsiFrameProtector.java
auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
core/src/main/java/io/grpc/Metadata.java
core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/JndiResourceResolverFactory.java
core/src/main/java/io/grpc/internal/ServiceConfigInterceptor.java
core/src/main/java/io/grpc/internal/TransportFrameUtil.java
netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java
netty/src/main/java/io/grpc/netty/NettyClientStream.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
testing/src/main/java/io/grpc/testing/GrpcCleanupRule.java

We've been on newer versions of Guava for a while now; these no longer
do anything.
Reworded the comment for Stopwatch.createUnstarted(), because it is not
safe (it doesn't matter if the method isn't marked Beta; you have to use
Ticker), except for the fact it is only used in our tests.
----
I've confirmed this is compatible with #5196.

Remove old BetaApi failure suppressions

---

alts/build.gradle
build.gradle
core/build.gradle
protobuf-lite/build.gradle
protobuf-nano/build.gradle
protobuf/build.gradle
repositories.bzl

This is temporary for the 1.18 release to give users a bit more time to
get past the breaking changes to Beta APIs in Guava 26.
Fixes #5166
-----
This is a backport of #5196

Downgrade to Guava 25.1 (v1.18.x backport)

---

alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java
alts/src/test/java/io/grpc/alts/internal/AltsProtocolNegotiatorTest.java
auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java
core/src/main/java/io/grpc/CallCredentials.java
core/src/main/java/io/grpc/CallCredentials2.java
core/src/main/java/io/grpc/internal/CallCredentialsApplyingTransportFactory.java
core/src/main/java/io/grpc/internal/GrpcAttributes.java
core/src/main/java/io/grpc/internal/MetadataApplierImpl.java
core/src/test/java/io/grpc/internal/CallCredentials2ApplyingTest.java
core/src/test/java/io/grpc/internal/CallCredentialsApplyingTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

This is the 3rd step of #4901
- The deprecated `CC.applyRequestMetadata(... Attributes ...)` is now **replaced** by the new API `CC.applyRequestMetadata(... CC.MetadataApplier ...)` transformed from `CC2.applyRequestMetadata(... CC2.MetadataApplier ...)`.
- The Attributes keys in `CallCredentials` were deprecated, and now deleted.
- The deprecated interface `CC.MetadataApplier` is **replaced** by an equivalent abstract class.
- `CallCredentials2` is now marked as deprecated, while keeping its interface intact so that it won't break current implementations that are still on `CallCredentials2`.
- From this point on, implementations should do a one-line change from `extends CallCredentials2` to `extends CallCredentials`
- `GoogleAuthLibraryCallCredentials` is kept as `CallCredentials2` for …

core: promote the new API in CallCredentials2

---

buildscripts/kokoro/macos.cfg
buildscripts/kokoro/unix.sh

We've had a long run of test timeout failures on Mac with timeouts in
the seconds. Multiple of these haven't seemed like races, but simply
that the Mac machines were too slow. The most recent case for this is a
set of timeouts for
OkHttpTransportTest.earlyServerClose_serverFailure_withClientCancelOnListenerClosed
where it took over a second for a server stream to be created ("Timed
out waiting for server stream").
This commit reduces the number of workers to reduce the overall load,
hoping this lets tests complete within a reasonable amount of time.

kokoro: Reduce gradle workers on Mac to reduce flakes

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java

SRV has not yet been enabled in a release. Since work is rapidly
underway to replace GRPC-LB with a service config+XDS-based solution,
there's now thoughts that we won't ever enable grpclb by default (but
may allow it to be automatically enabled when using GoogleDefaultChannel
or similar). Since things are being worked out, disable it.
This effectively reverts c729a0f.
------
This is a backport of #5232

core: disable SRV records lookup (v1.18.x backport)

---

core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

It produces clearer result error messages where there are failures.

core: Use Truth's isEmpty/hasSize

---

build.gradle

During 1.18 release, I found xds directory was uploaded to Sonatype, so I had to manually delete it before releasing to maven central. This needs backport to v1.18.x branch in case for future patches v1.18.1+.

xds: do not upload archives for xds for now

---

interop-testing/src/test/java/io/grpc/testing/integration/MoreInProcessTest.java

Noticed when Census takes a long time to initialize.

interop-testing: deflake MoreInProcessTest

---

core/src/main/java/io/grpc/internal/AbstractClientStream.java
core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

The current behavior (RST_STREAM w/ NO_ERROR results in client seeing INTERNAL error, even if gRPC status code was already sent in trailing headers) seems to have been introduced in https://github.com/grpc/grpc-java/pull/4485. The added call to `transportReportStatus` within `deframerClosed` would have no effect when `statusReported` had already been set to true upon receipt of the rst stream.

core: do not lose status when RST_STREAM with NO_ERROR received

---

buildscripts/kokoro/android.sh

Temporarily disabled due to https://github.com/grpc/grpc-java/issues/5276

buildscripts: disable android size status check

---

core/src/main/java/io/grpc/internal/ManagedChannelOrphanWrapper.java
core/src/test/java/io/grpc/internal/ManagedChannelOrphanWrapperTest.java

This avoids a memory leak when the channel itself participates in a
reference cycle (e.g., when an interceptor retains a reference to an
Android app's context). With the current implementation, the static
`ManagedChannelOrphanWrapper.refs` map will keep the channel reachable
and prevent the ref cycle from being GCed.

core: remove channel reference from ManagedChannelWrapper

---

core/src/main/java/io/grpc/InternalChannelz.java
core/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java
core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
core/src/main/java/io/grpc/internal/ServerImpl.java
core/src/test/java/io/grpc/inprocess/InProcessServerBuilderTest.java
core/src/test/java/io/grpc/inprocess/InProcessTransportTest.java
core/src/test/java/io/grpc/internal/AbstractServerImplBuilderTest.java
core/src/test/java/io/grpc/internal/ServerImplTest.java
netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
netty/src/test/java/io/grpc/netty/NettyServerBuilderTest.java
netty/src/test/java/io/grpc/netty/NettyTransportTest.java
okhttp/src/test/java/io/grpc/internal/AccessProtectedHack.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpTransportTest.java
services/src/test/java/io/grpc/services/ChannelzProtoUtilTest.java
testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java

I did my best to make sure this was thread safe, please be forgiving!

netty: support listening on multiple port

---

cronet/src/main/java/io/grpc/cronet/CronetClientStream.java
cronet/src/test/java/io/grpc/cronet/CronetClientTransportTest.java

This was discovered by an internal user. `AbstractClientStream#start` will call `#writeHeaders`, and if the transport is already shutdown, the invocation of `startCallback.run()` here will not set `streamFactory`.
@ejona86 I went with the "safe" route of just adding null-checks before access to `streamFactory` and `stream`, which made things much easier to (a) write, (b) feel confident about, and (hopefully) (c) review.

cronet: avoid NPE in writeHeaders after transport shutdown

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java

This will reduce the method count, as okhttp's copy of ConnectionSpec will no
longer be retained when ProGuarded. It was deprecated in 25f357699, 10 months
ago.
----
There are no users of this constant internally. We never saw many people using it.

okhttp: Remove DEFAULT_CONNECTION_SPEC from builder

---

alts/build.gradle
build.gradle
core/build.gradle
protobuf-lite/build.gradle
protobuf-nano/build.gradle
protobuf/build.gradle
repositories.bzl

This reverts commit 4adcf2436381441d8d861b51554b5b26222fe21f. The downgrade of
Guava has gone out in a release, so we can upgrade it again in the next
release.

Upgrade Guava to 26.0-android

---

context/src/main/java/io/grpc/ThreadLocalContextStorage.java
context/src/test/java/io/grpc/ThreadLocalContextStorageTest.java

If you attach literal ROOT to the thread, if anyone else restores root
it will set the thread local to be null. This broke the "are you
detaching the current context" check, as ROOT != null. This was a
regression introduced in 55b08e67d.

context: fix detaching ROOT

---

RELEASING.md
bom/build.gradle
build.gradle
examples/example-gauth/pom.xml
examples/example-tls/pom.xml
examples/pom.xml
settings.gradle

adapted from gax-java's BOM: googleapis/gax-java#607
some of examples with maven pom is also converted to use bom.
resolves #3954

Adding Bom

---

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/main/java/io/grpc/testing/integration/TestCases.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
interop-testing/src/test/java/io/grpc/testing/integration/TestCasesTest.java

This PR adds the [google default credentials](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#google_default_credentials) test case for Java. As follow up, will also need to add thist into `run_interop_tests.py` on GCE linux and also on mac.

interop-testing:  Add GoogleDefaultCreds test case for java

---

core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
core/src/test/java/io/grpc/internal/AbstractServerStreamTest.java
core/src/test/java/io/grpc/internal/ProxyDetectorImplTest.java
netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
services/src/test/java/io/grpc/services/BinlogHelperTest.java

In Mockito 2, if a method expects a primitive type, but an any(<Primitive>.class) matcher is used in its place, it will throw an error. To prepare for this upcoming breakage, change
all existing any(<Primitive>.class) matchers to use the correct any<Primitive>() matcher.

Fix usages of any(<Primitive>.class) matchers

---

core/src/main/java/io/grpc/Server.java
core/src/main/java/io/grpc/inprocess/InProcessServer.java
core/src/main/java/io/grpc/internal/InternalServer.java
core/src/main/java/io/grpc/internal/ServerImpl.java
core/src/test/java/io/grpc/inprocess/InProcessServerTest.java
core/src/test/java/io/grpc/internal/ServerImplTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/test/java/io/grpc/testing/integration/AutoWindowSizingOnTest.java
interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
interop-testing/src/test/java/io/grpc/testing/integration/TransportCompressionTest.java
netty/src/main/java/io/grpc/netty/NettyServer.java
netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
netty/src/test/java/io/grpc/netty/NettyServerBuilderTest.java
netty/src/test/java/io/grpc/netty/NettyServerTest.java
netty/src/test/java/io/grpc/netty/NettyTransportTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpTransportTest.java
testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java
testing/src/main/java/io/grpc/internal/testing/TestUtils.java

core,netty: expose listening on multiple ports

---

repositories.bzl

See https://github.com/bazelbuild/bazel/issues/6799 for more information

Stop using native maven_jar rule in grpc

---

core/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java

This should lower the chance of the race between the pick and the
shutdown (#2562).

core: RoundRobinLoadBalancer updates picker before shutting down subchannels

---

alts/src/main/java/io/grpc/alts/HandshakerServiceChannel.java
alts/src/test/java/io/grpc/alts/HandshakerServiceChannelTest.java

This avoids using the search domains when not on GCE, which prevents
useless DNS requests.
This is the Java equivalent of grpc/grpc#17598
---
CC @apolcyn

alts: Use absolute domain name for metadata server

---

BUILD.bazel
java_grpc_library.bzl

This is a sync from our internal copy, so has lots of small changes.
But the most important change is strict_deps issues are worked around
within the rule. This means there should be no longer any reason to
specify more than one dep.
~~Bazel 0.22 started the migration from the 'proto' provider to ProtoInfo,
which this includes. That means this is only compatible with Bazel 0.22
and later. But if we use the old-style provider it will probably stop
working with 0.23 or 0.24.~~
Fixes #5314
----
Note that this does not include the changes in dex processing that
keep getting reverted internally.

java_grpc_library.bzl: workaround strict_deps

---

core/src/main/java/io/grpc/internal/ClientTransportFactory.java

Since Nullable is not a type annotation, it is normal to put it before any
modifiers (like "private"). This fixes a lint failure.

core: Place Nullable annotation before modifiers

---

core/BUILD.bazel
repositories.bzl

This allows users to upgrade to newer versions of Guava without breaking
the build due to missing transitive dependencies. Without it, when
increasing the Guava version to 27.0+ you see errors like:
```
stub/src/main/java/io/grpc/stub/ClientCalls.java:487: error: cannot access InternalFutureFailureAccess
private static final class GrpcFuture<RespT> extends AbstractFuture<RespT> {
^
class file for com.google.common.util.concurrent.internal.InternalFutureFailureAccess not found
```
Note that using a runtime_dep does not fix the compilation error.
Long-term we will want our users to migrate to
jvm_maven_import_external. However, if we use it ourselves, it will
effectively require our users to use it immediately themselves. It has
low penetration today, including lack of usage by tools like …

core: Add "fake" dependency on Guava's failureaccess

---

core/src/main/java/io/grpc/internal/CensusTracingModule.java
core/src/test/java/io/grpc/internal/CensusModulesTest.java

This reverts commit d47379947ff010b478ce9513c3d1778f49482db4.
This caused test failures internally, where gRPC failed with
"IllegalArgumentException: Invalid trace name". Not only was this
failure unexpected, it was also weird that it failed with an
IllegalArgumentException instead of the normal StatusRuntimeException.
CC @zhangkun83 @bogdandrutu

Revert "core: Update gRPC to use span kind and raw full method. (#5328)"

---

alts/build.gradle
build.gradle

0.13.0 is the latest version.
This honestly doesn't do much since any user of our auth API will be
depending on the library themselves (we only depend on the interface; no
implementation). But getting past 0.9.1 may encourage our users to use a
newer version with better JWT handling and 0.9.1 was released 10 months
ago, so we're overdue for an update.
Fixes #4700
----
CC @elharo
Note that this did not make the cut for the 1.19 release. It could easily be backported, but I'm not sure there's much point.

Update google-auth-library-java to 0.13.0

---

core/src/main/java/io/grpc/internal/CensusTracingModule.java
core/src/test/java/io/grpc/internal/CensusModulesTest.java

This reverts commit d47379947ff010b478ce9513c3d1778f49482db4.
This caused test failures internally, where gRPC failed with
"IllegalArgumentException: Invalid trace name". Not only was this
failure unexpected, it was also weird that it failed with an
IllegalArgumentException instead of the normal StatusRuntimeException.
----
This is a backport of #5355

Revert "core: Update gRPC to use span kind and raw full method. (#5328)" (v1.19.x backport)

---

core/src/main/java/io/grpc/NameResolver.java

This is a partial back-port of #5364

doc: document since 1.19.0 on NameResolver.Helper

---

core/src/main/java/io/grpc/NameResolver.java
core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/DnsNameResolverProviderTest.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

Resolves #2649
As a prerequisite, added `getSynchronizationContext()` to `NameResolver.Helper`.
`DnsNameResolver` has gone through a small refactor around the `Resolve` runnable, which makes it a little simpler.

core: make NameResolver not thread-safe

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpChannelBuilderTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

This is mainly aimed at allowing Android users to force the OkHttp channel to use a particular network, via providing a socket factory obtained from [`android.net.Network#getSocketFactory()`](https://developer.android.com/reference/android/net/Network.html#getSocketFactory()). The corresponding feature request from an internal user is at b/119564668.

okhttp: add socketFactory method to channel builder

---

core/src/jmh/java/io/grpc/internal/StatsTraceContextBenchmark.java
core/src/main/java/io/grpc/ClientStreamTracer.java
core/src/main/java/io/grpc/inprocess/InProcessTransport.java
core/src/main/java/io/grpc/internal/CensusStatsModule.java
core/src/main/java/io/grpc/internal/CensusTracingModule.java
core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/main/java/io/grpc/internal/StatsTraceContext.java
core/src/test/java/io/grpc/CallOptionsTest.java
core/src/test/java/io/grpc/internal/CensusModulesTest.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java
cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbClientLoadRecorder.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java

This will be a new override.  The old override is now deprecated.
In order to pass new information without adding new overrides, I shoved most information
into an object called StreamInfo.  The Metadata is left out to draw attention because
it's mutable.
Motivation: this is needed for correctly supporting pick_first in GRPCLB.  GRPCLB needs to
add a token to the headers, and the token varies among servers.  With round_robin, GRPCLB
create a Subchannel for each server, thus can attach the token when the Subchannel is picked.
To implement pick_first, all server addresses will be put in a single Subchannel, we will
need to add the header in newClientStreamTracer(), by looking up the server address from
the transport attributes and deciding which token to add.

core: pass transport attributes to ClientStreamTracer.Factory.newClientStreamTracer()

---

.travis.yml

JDK 11 is LTS and superceded JDK 9 and 10. Nobody should really be using JDK 9
(just like the already untested JDK 10) so let's not waste the CPU testing it.
As long as we support JDK 8 and 11 it is unlikely we break JDK 9, though.

travis.yml: Stop testing jdk9

---

SECURITY.md

In testing, I discovered that Alpine does in fact work. Update the
documentation with the error you might see if you are simply missing a
package (for Googling) as well as fixes.

SECURITY.md: tcnative/ALPN works on Alpine

---

examples/example-tls/README.md

Need a space between command-name and first argument

add a missing critical whitespace

---

SECURITY.md

I fixed many of these elsewhere in the document via 4ba168f28, but I
didn't update the troubleshooting section previously.

SECURITY.md: Don't suggest users to use Jetty ALPN

---

README.md
RELEASING.md
SECURITY.md
benchmarks/README.md
benchmarks/src/jmh/java/io/grpc/benchmarks/netty/README.md
gae-interop-testing/README.md

For security, we should change http into https links.
Co-Authored-By: Nguyen Van Trung [trungnvfet@outlook.com](mailto:trungnvfet@outlook.com)
Signed-off-by: Nguyen Quang Huy [huynq0911@gmail.com](mailto:huynq0911@gmail.com)

Change http to https for security links

---

java_grpc_library.bzl

Also pass in the binary correctly as a tool. This is required for #5383.
I have tested the build with older Bazel versions and this doesn't
appear to affect compatibility, ie grpc-java continues to be compatible
with Bazel >=0.19.

Use newer Bazel actions API

---

buildscripts/kokoro/bazel.sh
java_grpc_library.bzl

This is part of #5383. As Bazel 0.22.0 is the only supported version
now, use this in the Kokoro build.

bazel: update to new ProtoInfo provider

---

core/src/test/java/io/grpc/inprocess/InProcessTransportTest.java
core/src/test/java/io/grpc/internal/AbstractTransportTest.java
netty/src/test/java/io/grpc/netty/NettyTransportTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpTransportTest.java
testing/build.gradle

Fixes #5301 
----
CC @elharo @suztomo. This will be present in v1.20.

testing: Move AbstractTransportTest to core to avoid Truth dep

---

core/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/util/ForwardingLoadBalancerHelper.java

This can be used by xds LoadBalancer to create a channel to the XDS
traffic director, as the service config will only specify the target
name of the balancer.
This PR only adds the interface to unblock the xds work.
Implementation would take some time thus will come later.
I selected a slightly different name from the original `createOobChannel()`
to signify their difference. I am open to naming it just `createOobChannel()`.

core: add LoadBalancer.Helper#createResolvingOobChannel()

---

core/src/main/java/io/grpc/Grpc.java
core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
core/src/main/java/io/grpc/inprocess/InProcessTransport.java
core/src/main/java/io/grpc/internal/GrpcAttributes.java
core/src/test/java/io/grpc/inprocess/InProcessTransportTest.java
core/src/test/java/io/grpc/internal/AbstractTransportTest.java
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java
cronet/src/test/java/io/grpc/cronet/CronetClientTransportTest.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
netty/src/test/java/io/grpc/netty/NettyTransportTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpTransportTest.java

This is needed for GRPCLB pick_first support, which needs to attach
tokens to headers, and the tokens are per server.  In pick_first, all
addresses are in a single Subchannel, thus the LoadBalancer needs to
know which backend is used for a new stream.

core: add internal transport attribute ATTR_CLIENT_EAG_ATTRS

---

core/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/util/ForwardingLoadBalancerHelper.java
core/src/test/java/io/grpc/LoadBalancerTest.java
services/src/test/java/io/grpc/services/HealthCheckingLoadBalancerFactoryTest.java

This was added for the potential use case of needing to resolve target
names (of the same scheme as the top-level channel's target's) in the
LoadBalancer.  Now actual use cases come up in xDS that we need to
resolve fully-qualified target strings with arbitrary schemes.  This
method has never been used and won't fit future uses because it's too
restrictive.

core: deprecate LoadBalancer.Helper#getNameResolverFactory

---

core/src/test/java/io/grpc/internal/AbstractTransportTest.java

newClientStreamTracer() is called from transport implementations, thus
needs to be tested in AbstractTransportTest.

test: test the header mutation inside newClientStreamTracer()

---

buildscripts/kokoro/bazel.sh
java_grpc_library.bzl

More information: https://github.com/bazelbuild/bazel/issues/5824

Rename source jar outputs to avoid conflicts with java_common.compile

---

core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

Make sure the config for grpclb is passed to the `GrpclbLoadBalancer`, which will support two child policies -- "round_robin" (default) and "pick_first".
Previously the presence of balancer addresses would dictate "grpclb" policy, despite of the service config. Service config will now take precedence instead.
Implement config parsing logic in `GrpclbLoadBalancer`. Per offline discussions with @markdroth and @ejona86, we will ignore configuration errors for now. The more appropriate [config error handling](https://github.com/grpc/proposal/pull/100) is upcoming.

core/grpclb: propagation and parsing of grpclb config

---

java_grpc_library.bzl

--incompatible_generate_javacommon_source_jar was introduced in 0.22 and became
default in 0.23, but there isn't a way to support the old and new way at the
same time.
We generate a srcjar with the same lib${name}-src.jar, but now
java_common.compile is also producing a srcjar with that same name and causes a
conflict. This requires us to choose a different name for our srcjar, but any
existing users of the srcjar will break if on 0.22 and earlier (excepting they
specify the incompatible flag in 0.22) as the file name referenced is no longer
available. For such users, they will need to change their grpc version at the
same time as changing their Bazel version.
See #5395 and #5412
-----
Note that this is against v1.19.x and not master. Note also it differs from the solution performed on …

Workaround Bazel 0.23 incompatibility (v1.19.x version)

---

core/src/main/java/io/grpc/internal/ChannelTracer.java

Make the "logged" method be consistent, and refer to the public logging class name and method.  This makes the log statements return the same class name used to set the log level.  
Before:
```
190306 13:29:39.290:D 1 [io.grpc.internal.ChannelTracer.logOnly] [Channel<1>: (localhost:10000)] Channel for 'localhost:10000' created
190306 13:29:39.414:D 1 [io.grpc.internal.ChannelTracer.logOnly] [Channel<1>: (localhost:10000)] Exiting idle mode
190306 13:29:39.622:D 17 [io.grpc.internal.ChannelTracer.logOnly] [Channel<1>: (localhost:10000)] Resolved address: [[[/127.0.0.1:10000]/{}]], config={}
190306 13:29:39.623:D 17 [io.grpc.internal.ChannelTracer.logOnly] [Channel<1>: (localhost:10000)] Address resolved: [[[/127.0.0.1:10000]/{}]]
190306 13:29:39.624:D 17 …
```

core: normalize log statement callsite

---

grpclb/src/main/java/io/grpc/grpclb/CachedSubchannelPool.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/main/java/io/grpc/grpclb/SubchannelPool.java
grpclb/src/test/java/io/grpc/grpclb/CachedSubchannelPoolTest.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

The problem: GrpclbState tracks Subchannels' states as a mutable
attribute in Subchannel.getAttributes(). However, GrpclbState only
update this attribute for the Subchannels its managing. For those
cached in SubchannelPool, their state attributes are stale. When they
are given back to GrpclbState, IDLE state is assumed.  As a result, if
a Subchannel is READY when it's reclaimed from the pool, it will not
be picked.
To fix that, this change expands SubchannelPool interface to handle
Subchannel state updates, which GrpclbState will call. SubchannelPool
saves the latest state and delivers it when it's returned to
GrpclbState by scheduling a call to handleSubchannelState() in the
SynchronizationContext, so that GrpclbState will take the latest state
as if it was just reported from the …

grpclb: keep track of state updates for cached Subchannels.

---

grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

As per offline discussions with @ejona86 and @markdroth 
Resolves #5436

grpclb: use fallback addresses if no balancer address is given

---

SECURITY.md

Fixes #4905
------
These are the changes I had suggested in #4926

SECURITY.md: Fix syntax and typos in mutual TLS interceptor example

---

core/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/GrpcAttributes.java
core/src/main/java/io/grpc/internal/JsonParser.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/ServiceConfigInterceptor.java
core/src/main/java/io/grpc/internal/ServiceConfigUtil.java
core/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/HedgingPolicyTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/RetryPolicyTest.java
core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
services/src/main/java/io/grpc/services/HealthCheckingLoadBalancerFactory.java
services/src/test/java/io/grpc/services/HealthCheckingLoadBalancerFactoryTest.java
xds/src/main/java/io/grpc/xds/XdsLoadBalancer.java
xds/src/test/java/io/grpc/xds/FallbackManagerTest.java
xds/src/test/java/io/grpc/xds/XdsLoadBalancerTest.java

The main difference is that `Map<String, ?>` is used as a return type instead of `Map<String, Object>`.  The reason for the change is that it more accurately represents what types can be put into a service config (which is nothing at all, it's immutable) while leaving the gettable types as Object.   This also avoids some internal double casting (like from `List -> List<?> -> List<Map<...>)`.
Effectively it increases the compile time safety by turning `put()` calls into errors.

core,grpclb: use better generics on service config

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java

It's not supposed to throw. Any exception from it should be considered
a bug and deserves a panic.

core: stop catching exceptions from NameResolver.start()

---

repositories.bzl

`curl -sL https://github.com/google/protobuf/archive/384989534b2246d413dbcd750744faab2607b516.zip | shasum -a 256`
gives `79d102c61e2a479a0b7e5fc167bcfaa4832a0c6aad4a75fa7da0480564931bcc`.

grpc_java_repositories: fix com_google_protobuf_javalite sha256.

---

core/src/main/java/io/grpc/CallOptions.java
core/src/main/java/io/grpc/ServerCall.java
stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java

CC @AmiDavidW, as this came up in #5358

core,stub: Document grpc performs compression nego on server

---

COMPILING.md
android-interop-testing/app/build.gradle
build.gradle
buildscripts/make_dependencies.bat
buildscripts/make_dependencies.sh
core/build.gradle
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-kotlin/android/helloworld/app/build.gradle
examples/example-kotlin/build.gradle
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/pom.xml
grpclb/build.gradle
protobuf-lite/build.gradle
protobuf-nano/build.gradle
protobuf/build.gradle
repositories.bzl
services/build.gradle
xds/build.gradle

This version of Protobuf works with Bazel's
--incompatible_disable_deprecated_attr_params. It also avoids a noisy
reflective access warning in JDK 9+ (nothing was broken before; the warning was
overzealous).
Fixes #5383

Upgrade to Protobuf 3.7.0

---

examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlClient.java

Add a missing space in the comment before requestStream.setOnReadyHandler()
This is a very small change, but I thought I would submit it quickly since I noticed it. :)

Add a missing space in comment

---

alts/src/main/java/io/grpc/alts/CallCredentialsInterceptor.java
alts/src/main/java/io/grpc/alts/ComputeEngineChannelBuilder.java
alts/src/test/java/io/grpc/alts/ComputeEngineChannelBuilderTest.java

Add ComputeEngineChannelBuilder. This is similar to GoogleDefaultChannelBuilder, except that ComputeEngineChannelBuilder only runs on GCE and only fetches call credentials from metadata server.

alts: add ComputeEngineChannelBuilder

---

interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java

Add compute_engine_credentials as custom_credentials_type option.

alts: add ComputeEngineChannelBuilder to interop test

---

repositories.bzl
services/BUILD.bazel

Got tired of waiting on https://github.com/grpc/grpc-java/pull/5184/, so I forked and also did the integration with grpc-proto.
This PR should not be merged until https://github.com/grpc/grpc-proto/pull/44 has been merged, as we depend on the newly added java proto rules.
Manually tested, everything builds.

Bazel services + grpc_proto dependency

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/JsonParser.java
core/src/main/java/io/grpc/internal/ServiceConfigUtil.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java

The behavior of DNS error handling changed with proposal A5.  Now, if any service config is invalid they all  are considered bad.

core: Change DNS error handling to fail on all invalid configs

---

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/main/java/io/grpc/testing/integration/TestCases.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
interop-testing/src/test/java/io/grpc/testing/integration/TestCasesTest.java

The new interop test case that this implements is described in https://github.com/grpc/grpc/pull/18370/files#diff-3472a48e65e8a5a8b22c53c0033c8dbd in open PR: https://github.com/grpc/grpc/pull/18370.
This PR allows https://github.com/grpc/grpc/pull/18370 to proceed (so that the test starts passing)
cc @jiangtaoli2016

Interop-testing: implement compute engine channel creds test case in Java

---

benchmarks/src/jmh/java/io/grpc/benchmarks/TransportBenchmark.java

Netty `LocalChannel`s are meant to be used with the `DefaultEventLoopGroup`, but the gRPC channel/server builders use `NioEventLoopGroup`s by default.

benchmarks: Use correct ELG type for TransportBenchmark NETTY_LOCAL test

---

grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancerProvider.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
services/src/main/java/io/grpc/services/HealthCheckingLoadBalancerFactory.java
services/src/main/java/io/grpc/services/HealthCheckingLoadBalancerUtil.java
services/src/test/java/io/grpc/services/HealthCheckingLoadBalancerFactoryTest.java

Use a separate Stopwatch for Load Balancer to manage backoff time. Solves #5056

services/grpclb: use Stopwatch to provide elapsed time for backoffs

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java

This case was missed by oversight.    No tests because I have almost no way to test the class loading failure.

core: fix DNS JNDI not working if there is an unavailability cause

---

examples/example-kotlin/src/main/kotlin/io/grpc/examples/helloworld/HelloWorldClient.kt

examples/kotlin: fix typo in HelloWorld example

---

benchmarks/src/jmh/java/io/grpc/benchmarks/TransportBenchmark.java

This was an omission from #5492, sorry! Without it there are some ugly warnings in the log.

Ensure ELGs used by TransportBenchmark.NETTY_LOCAL are shutdown

---

core/src/main/java/io/grpc/NameResolver.java
core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/ForwardingNameResolver.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/ForwardingNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplGetNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/OverrideAuthorityNameResolverTest.java

This reverts commit f4a31ec62d038abf6faea7abaf377e2df3d308f0.
This change is part of a series of unfinished API changes and refactors for [Service Config Error Handling](https://github.com/grpc/proposal/blob/master/A21-service-config-error-handling.md#service-config-error-handling). It by its own should not go into the release.

Revert " core: deprecate NR.L and add NR.Results "

---

core/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/LoadBalancerProvider.java
core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/PickFirstLoadBalancer.java
core/src/main/java/io/grpc/util/ForwardingLoadBalancer.java
core/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/PickFirstLoadBalancerTest.java
core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
services/src/main/java/io/grpc/services/HealthCheckingLoadBalancerFactory.java
services/src/test/java/io/grpc/services/HealthCheckingLoadBalancerFactoryTest.java
xds/src/main/java/io/grpc/xds/XdsLoadBalancer.java
xds/src/test/java/io/grpc/xds/FallbackManagerTest.java
xds/src/test/java/io/grpc/xds/XdsLoadBalancerTest.java

This allows the load balancer to accept the service config object.   It is **not** yet wired up, this only creates the API do so.

all: add LoadBalancer overload for Resolution results

---

stub/src/main/java/io/grpc/stub/ClientCalls.java

The `ThreadlessExecutor` currently used for blocking calls uses `LinkedBlockingQueue` which is relatively heavy both in terms of allocations and synchronization overhead (e.g. when compared to `ConcurrentLinkedQueue`). It accounts for ~10% of allocations and ~5% of allocated bytes per-call in the `TransportBenchmark` when using in-process transport with [stats and tracing disabled](https://github.com/grpc/grpc-java/issues/5510).
Changing to use a `ConcurrentLinkedQueue` results in a ~5% speedup of that benchmark.

stub: optimize ThreadlessExecutor used for blocking calls

---

core/build.gradle
core/src/main/java/io/grpc/perfmark/PerfMark.java
core/src/main/java/io/grpc/perfmark/PerfMarkTask.java
core/src/main/java/io/grpc/perfmark/PerfMarker.java
core/src/main/java/io/grpc/perfmark/PerfTag.java
core/src/main/java/io/grpc/perfmark/Tag.java
core/src/main/java/io/grpc/perfmark/package-info.java

Currently unanswered:
1.  What should the visibility rules be?
2.  Do we really need all these methods?
3.  Should this be part of the main gRPC Maven package or Gradle package?
Mostly answered:
1.  This should be in its own Java package.
2.  No implementation yet.
3.  Absolute minimum number of dependencies, not even on io.grpc. (else a cycle)  (also, an exception for package-info, which can be easily removed).

perfmark: add a perf annotation package

---

android-interop-testing/app/build.gradle

android-interop-test now needs explicit mockito dependency because of #5535

android-interop-test: add mockito dependency

---

core/BUILD.bazel
core/src/main/java/io/grpc/ServerCall.java
core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/main/java/io/grpc/internal/ServerCallImpl.java
core/src/main/java/io/grpc/internal/ServerImpl.java

This code is highly experimental, so we can change it at will later.  This PR is to go ahead and try it out.
Perfmark task calls are added to the client and server calls public APIs, recording when the calls begin and end.  They use separate scope IDs (roughly these are Thread IDs) for the listener and the call due to no synchronization between them.  However, they both use the same PerfTags, which allows them to be associated.  
In the future, we can plumb the tag down into the stream to include deeper information about whats going on in a call.

 core: add client and server call perfmark annotations

---

interop-testing/build.gradle
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
testing/build.gradle

Cherry picks of 40526086eb612f07715b45b2181a7448d12a481f and 3325881eaec5b959b95915bdb83d0a9f0b61a06c
grpc-testing and grpc-interop-testing in v1.19.0 and earlier used to transitively depend on mockito 1. Now in v1.20.0, if they transitively depend on mocikito 2, it would be a bigger breaking change to our users than they are not depending on mockito at all. (And in next release (v1.21.0) they are no longer depending on mockito anyway.)
Also fixes #5523 in v1.20.x branch.

grpc-testing and grpc-interop-testing no longer transitively depend on mockito (v1.20.x)

---

core/src/main/java/io/grpc/ForwardingChannelBuilder.java
core/src/main/java/io/grpc/ManagedChannelBuilder.java
core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

Refactor as discussed in #5189. Will backport to v1.20.0 to reduce a cycle of deprecation process.

core: refactor lookUpServiceConfig(boolean) to disableServiceConfigLookUp()

---

cronet/README.md

Some markdown parsers require an empty line before lists to parse them as such.

Improved formatting for advantages list.

---

COMPILING.md
android-interop-testing/app/build.gradle
build.gradle
buildscripts/build_docker.sh
buildscripts/make_dependencies.bat
buildscripts/make_dependencies.sh
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-kotlin/android/helloworld/app/build.gradle
examples/example-kotlin/build.gradle
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/pom.xml
grpclb/build.gradle
repositories.bzl
services/build.gradle
xds/build.gradle

This mainly avoids protoc from 3.7.0 which has a dependency on libatomic. Most
of our systems have libatomic, so it mostly works, but the interop docker
container does not, so building fails. Version 3.7.1 was rebuilt to avoid
needing the libatomic shared library.
This has the added benefit that Bazel is now on the same version as Gradle, as
3.7.1 included fixes for Bazel.
----
This will be backported to 1.20, otherwise the release process will fail at the very end.

Update Protobuf to 3.7.1

---

core/src/main/java/io/grpc/internal/KeepAliveManager.java
core/src/test/java/io/grpc/internal/KeepAliveManagerTest.java

Use `ScheduledExecutorService` provided by `FakeClock` as the scheduler to run `KeepAliveManager` in `KeepAliveManagerTest`. Also modified how `nextKeepaliveTime` is managed in `KeepAliveManager` by using a Stopwatch. Solves #2868

core: use FakeClock.ScheduledExecutorService for KeepAliveManagerTest

---

COMPILING.md
android-interop-testing/app/build.gradle
build.gradle
buildscripts/build_docker.sh
buildscripts/make_dependencies.bat
buildscripts/make_dependencies.sh
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-kotlin/android/helloworld/app/build.gradle
examples/example-kotlin/build.gradle
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/pom.xml
grpclb/build.gradle
repositories.bzl
services/build.gradle
xds/build.gradle

This mainly avoids protoc from 3.7.0 which has a dependency on libatomic. Most
of our systems have libatomic, so it mostly works, but the interop docker
container does not, so building fails. Version 3.7.1 was rebuilt to avoid
needing the libatomic shared library.
This has the added benefit that Bazel is now on the same version as Gradle, as
3.7.1 included fixes for Bazel.
-----
This is a backport of #5548

Update Protobuf to 3.7.1 (v1.20.x backport)

---

core/src/main/java/io/grpc/NameResolver.java

Both the config and the error need to be passed to the managed channel so it can decide to keep or reject the config.   Passing only the parsed object means the managed channel cannot implement the error handling gRFC.

core: change service config to ConfigOrError

---

core/src/main/java/io/grpc/NameResolver.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

We assumed that we were the only caller.  Turns out there are
forwarding NameResolver too.  Implementing the old override will give
them time to migrate to the new API.
Resolves #5556

core: make newNameResolver() change backward compatible for callers.

---

core/src/main/java/io/grpc/LoadBalancer.java
core/src/test/java/io/grpc/LoadBalancerTest.java

This will give time for pre-existing external callers (e.g.,
forwarding LoadBalancers) to migrate to the new handleResolvedAddresses().

core: make the LoadBalancer.handleResolvedAddressGroups() change backward compatible

---

core/src/main/java/io/grpc/NameResolver.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

This will give time for pre-existing external callers (e.g.,
forwarding NameResolvers) to migrate to the new start().

core: make the NameResolver.start() change backward compatible for callers

---

core/src/main/java/io/grpc/NameResolver.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

We assumed that we were the only caller.  Turns out there are
forwarding NameResolver too.  Implementing the old override will give
them time to migrate to the new API.
(Backport of #5560)

core: (backport) make newNameResolver() change backward compatible for callers. 

---

okhttp/src/main/java/io/grpc/okhttp/ExceptionHandlingFrameWriter.java
okhttp/src/test/java/io/grpc/okhttp/ExceptionHandlingFrameWriterTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

OkhttpFrameLogger tests fail internally due to mocked logger. Do the test in another way by using collecting LogRecords and verify log messages.

okhttp: fix OkhttpFrameLogger mocking tests failure

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java

okhttp: wait until connection preface / settings during transport start to avoid deadlock (back port of #5567)

---

repositories.bzl
services/BUILD.bazel
services/build.gradle
services/src/main/java/io/grpc/services/BinlogHelper.java
services/src/test/java/io/grpc/services/BinlogHelperTest.java

re2j is a fairly unnecessary dependency. Our usage of Pattern is quite limited
and isn't all that hard to do manually. Our usage would be safe to use normal
java.util.regex, but it's sort of annoying to keep re-explaining to others who
are (rightly) concerned with java.util.regex's poor pathological behavior.

services: Remove dependency on re2j

---

buildscripts/kokoro/bazel.sh

For v1.18.x, we were using bazel 0.20.0. Using the version since newer version is no longer backward compatible.

buildscripts: set bazel version to 0.20.0 (v1.18.x)

---

context/src/main/java/io/grpc/Context.java
context/src/test/java/io/grpc/ContextTest.java

I'm not totally convinced this is better than previously, but I believe it avoids the class initialization problem.  
The performance difference is minimal, but it does avoid the extra stack frame, and avoids the atomic compiler barrier (cheap).   storage() is called quite frequently, so there may be an aggregate benefit to making this fast.

context: try out static final storage

---

core/src/main/java/io/grpc/NameResolver.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

We assumed that we were the only caller.  Turns out there are
forwarding NameResolver too.  Implementing the old override will give
them time to migrate to the new API.
Resolves #5556
Backport of #5560

core: make newNameResolver() change backward compatible for callers. (v1.19.x backport)

---

interop-testing/build.gradle
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/main/java/io/grpc/testing/integration/TestCases.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
interop-testing/src/main/proto/grpc/testing/messages.proto
interop-testing/src/test/java/io/grpc/testing/integration/TestCasesTest.java

New fields are added to the test protos according to https://github.com/grpc/grpc-proto/pull/51
This test needs to be run in an environment where "pick_first" or "grpclb" with child policy "pick_first" is configured.
/cc @apolcyn

interop-test: add test case for "pick_first" picking behavior

---

core/src/main/java/io/grpc/LoadBalancerProvider.java
core/src/main/java/io/grpc/NameResolver.java
core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java
core/src/main/java/io/grpc/util/SecretRoundRobinLoadBalancerProvider.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancerProvider.java
services/src/main/java/io/grpc/services/internal/HealthCheckingRoundRobinLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/XdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/XdsLoadBalancerProvider.java

This class is used in other places than just NameResolver.Helper.  It
should not be an inner class of Helper.
Strictly speaking this is an API-breaking change.  However, this is
part of the service config error handling API that hasn't been done
yet.  Nobody has a legitimate reason to use it.

core: Move ConfigOrError one level up.

---

core/src/main/java/io/grpc/util/ForwardingClientStreamTracer.java
core/src/test/java/io/grpc/util/ForwardingClientStreamTracerTest.java

A `ForwardClientStreamTracer` class is useful for intercepting an existing `ClientStreamTracer` instance.

core/util: create a ForwardingClientStreamTracer class for delegation use

---

context/src/main/java/io/grpc/Context.java

This change avoids an extra stack frame by removing synthetic methods like `io.grpc.Context$access100`.  These are removed by making the fields and methods package-private, which avoids the methods (and should have a minor improvement on method count and binary size).

context: avoid synthetic methods on Context

---

netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java
netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java

The last ping time was not set, leading to the bandwidth since last ping in `FlowControlPinger.updateWindow()` to always be zero.  
Fixes failures of the form:
```
io.grpc.netty.NettyClientHandlerTest > windowShouldNotExceedMaxWindowSize FAILED
java.lang.AssertionError: expected:<8388608> but was:<65535>
```

netty: deflake ping flow control logic

---

netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/main/java/io/grpc/netty/Utils.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
netty/src/test/java/io/grpc/netty/UtilsTest.java

Specified in [gRPC proposal A18](https://github.com/grpc/proposal/blob/master/A18-tcp-user-timeout.md).

netty: maybe set TCP_USER_TIMEOUT when epoll and keepalive is enabled

---

netty/src/main/java/io/grpc/netty/InternalNettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/InternalNettyServerBuilder.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
netty/src/test/java/io/grpc/netty/NettyChannelBuilderTest.java
netty/src/test/java/io/grpc/netty/NettyServerBuilderTest.java

channel type in the NettyServerBuilder is using null which in unfortunate. it wasn't able to tell if the user provided same type. 
Converting to channel factory was considered, but in the Server#start checks instance of channel type to set SocketChannel specific channel options. if we want to use channelFactory route, we can just blindly set those options which is probably not a big deal.

netty: add internal API to fall back to NIO transport

---

alts/src/main/java/io/grpc/alts/AltsChannelBuilder.java
alts/src/main/java/io/grpc/alts/AltsServerBuilder.java

The ALTS builders are supposed to act like ChannelCreds, as done in
other languages. ChannelCreds don't have the opportunity to change
settings like this. In addition, the options here weren't set in
GoogleDefaultChannelBuilder and ComputeEngineChannelBuilder.
CC @creamsoup

alts: Use normal defaults in Alts{Channel,Server}Builder

---

xds/third_party/envoy/import.sh

Existing `import.sh` script uses `sed` to remove `gogoproto` dependencies in imported proto files, which has compatibility issues on macOS due to:
1. `\|` is not supported in basic regex for macOS, so matching for `gogoproto` option does not work as expeced.
2. Usage of `-i` is different.
3. `t` command goes until the end of line, which does not count `;`.
Changes made to avoid above usages and only with usages work for cross platform.

xds/third_party: fixed compatibility issue of regex in BSD for import.sh sed command

---

xds/src/generated/main/grpc/io/envoyproxy/envoy/api/v2/ClusterDiscoveryServiceGrpc.java
xds/src/generated/main/grpc/io/envoyproxy/envoy/service/discovery/v2/AggregatedDiscoveryServiceGrpc.java
xds/src/generated/main/grpc/io/envoyproxy/udpa/service/orca/v1/OpenRcaServiceGrpc.java
xds/third_party/envoy/import.sh
xds/third_party/envoy/src/main/proto/envoy/api/v2/auth/cert.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/cds.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/cluster/circuit_breaker.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/base.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/config_source.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/grpc_service.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/health_check.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/protocol.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/discovery.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/eds.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/endpoint/load_report.proto
xds/third_party/envoy/src/main/proto/envoy/service/discovery/v2/ads.proto
xds/third_party/envoy/src/main/proto/envoy/type/range.proto
xds/third_party/envoy/src/main/proto/udpa/data/orca/v1/orca_load_report.proto
xds/third_party/envoy/src/main/proto/udpa/service/orca/v1/orca.proto

- Ran `xds/third_party/envoy/import.sh` to sync proto dependencies from [envoy](https://github.com/envoyproxy/envoy) repository.
- New proto files for Open Request Cost Aggregation (ORCA) are introduced, which will be used for xDS backend cost metrics report.
- Envoy made some small changes to existing api protos we are currently using. Most of them are doc references in comments. Changes would not break out current usage.

xds/third_party: import proto files from envoy repo

---

stub/src/main/java/io/grpc/stub/ClientCalls.java
stub/src/test/java/io/grpc/stub/ClientCallsTest.java

Interceptors need to see the onClose to clean up properly.
This also changes an isInterrupted() to interrupted(), since previously
the interrupted flag was still set when InterruptedException was thrown.
This caused an infinite loop with the new code. Previously, all callers
immediately re-set the interrupted flag, so there was no issue.
Fixes #5576
CC @ravirajj
CC @njhill, since I touched the ThreadlessExecutor because of isInterrupted()

stub: Wait for onClose when blocking stub is interrupted

---

compiler/BUILD.bazel
java_grpc_library.bzl

This removes the "java_import to work around error with android_binary"
hack; see the b/78647825 references to see the really important parts.
But in general using a toolchain cleans up the code considerably and
allows us to reduce the visibility of our protoc plugin. It also is
useful to enable using aspects in the future to avoid using
make_non_strict() which would improve compilation speed avoid avoid many
unnecessary rebuilds.
This is an export of cl/229763103 and brings external up-to-sync with
internal.

java_grpc_library: Use toolchain to enable DexArchiveAspect

---

java_grpc_library.bzl

https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring-header
Made some additional changes to make the doc more clear.

java_grpc_library.bzl: Fix docstring to match Bazel style

---

api/src/main/java/io/grpc/MethodDescriptor.java
api/src/main/java/io/grpc/ServerServiceDefinition.java
api/src/main/java/io/grpc/ServiceDescriptor.java
api/src/test/java/io/grpc/MethodDescriptorTest.java
auth/src/main/java/io/grpc/auth/ClientAuthInterceptor.java
auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
core/src/main/java/io/grpc/internal/ServiceConfigInterceptor.java

This method is needed for serviceConfig enforcement, and some security checks.  Rather than recreate the string each time, just cache it on the MD.

 core: add getService to MethodDescriptor

---

api/src/main/java/io/grpc/CallOptions.java
api/src/main/java/io/grpc/InternalCallOptions.java
api/src/test/java/io/grpc/CallOptionsTest.java

This is needed to properly implement the Service Config waitForReady underride.

api: expose if waitForReady has been set on CallOptions

---

stub/src/main/java/io/grpc/stub/ClientCalls.java
stub/src/test/java/io/grpc/stub/ClientCallsTest.java

This reverts commit 6d44f46f18fd2dcdbb5be8866cdbf79ab21b110f.
This is causing a test to hang internally. I am currently expecting that
the shutdown logic of the test is broken, but it will take time to
diagnose. Thus, revert this for the moment.

Revert "stub: Wait for onClose when blocking stub is interrupted"

---

api/src/main/java/io/grpc/LoadBalancer.java
api/src/main/java/io/grpc/NameResolver.java

Annotations on outer class don't show on the javadoc of inner classes.
cc @voidzcy

core: annotate experimental API's inner classes.

---

api/src/main/java/io/grpc/LoadBalancer.java
api/src/test/java/io/grpc/LoadBalancerTest.java

@zhangkun83 Do we write test for this? Also, do we need a api tracking issue?

api: augment CreateSubchannelArgs with custom options

---

api/src/main/java/io/grpc/LoadBalancer.java
api/src/test/java/io/grpc/LoadBalancerTest.java

This is something I missed in #5640.

api: patch CreateSubchannelArgs toString() with customOptions

---

api/src/main/java/io/grpc/LoadBalancer.java
api/src/test/java/io/grpc/LoadBalancerTest.java

This is the second (last) thing I missed in #5640 .

api: fix bugs of missing to copy customOptions when converting to a new builder, also trash hashCode/equals

---

api/src/main/java/io/grpc/ClientStreamTracer.java
core/src/main/java/io/grpc/internal/StatsTraceContext.java
core/src/test/java/io/grpc/ClientStreamTracerTest.java
core/src/test/java/io/grpc/internal/CensusModulesTest.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
grpclb/src/test/java/io/grpc/grpclb/TokenAttachingTracerFactoryTest.java
xds/src/test/java/io/grpc/xds/XdsLoadReportStoreTest.java

As we are now endorsing the wrapping of ClientStreamTracers by
providing ForwardingClientStreamTracer, there is a need for altering
StreamInfo, especially CallOptions before it's passed onto the
delegate.  A Builder class and a toBuilder() provides a robust way
to copy the rest of the fields.
Equality and hashcode are not supported, which was the case with the
previous internal implementation, as well as `CallOptions`.
This is a breaking change for anybody who creates StreamInfo, which is
unlikely in non-test code, because StreamInfo was added as late as
1.20.0.
/cc @voidzcy

core: change ClientStreamTracer.StreamInfo to a final class with a builder

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8

---

xds/third_party/envoy/import.sh

This reverts #5613 . The import script is synced with an internal upstream, we should not changed it manually.

xds/third_part: revert change of envoy import script

---

api/src/main/java/io/grpc/ClientInterceptor.java

api: Discourage using ClientInterceptor for credentials

---

build.gradle

It is just causing trouble. When using paddedCell() it doesn't reliably
complain about failures and without paddedCell() it won't finish its
check. And when it does complain you have to guess what it wants from
you because unrelated changes are complained about at the same time.
It also caused trouble because **/*.gradle is overly aggressive; it
searchs build/ folders and bazel folders. But when trying to swap it to
per-project checks on the build.gradle I was unable to get it to fail,
even with obvious problems like using tabs.

Remove spotless plugin for gradle formatting

---

build.gradle
core/src/main/java/io/grpc/internal/CensusStatsModule.java
core/src/main/java/io/grpc/internal/CensusTracingModule.java
core/src/test/java/io/grpc/internal/CensusModulesTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
repositories.bzl
testing/src/main/java/io/grpc/internal/testing/StatsTestUtils.java

Also updated CensusModule to use the new helper methods `ContextUtils.withValue()` instead of directly manipulating the context keys. See https://github.com/census-instrumentation/opencensus-java/pull/1864.
/cc @bogdandrutu @dinooliva @zhangkun83

 all: Upgrade OpenCensus versions.

---

api/src/main/java/io/grpc/NameResolver.java
api/src/test/java/io/grpc/NameResolverRegistryTest.java
core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/ForwardingNameResolver.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/ForwardingNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplGetNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/OverrideAuthorityNameResolverTest.java

This follows the sort of changes we've done in the past, where the '2'
implies "version 2." We can end up reclaiming the original name if we
wish in the future.
The main reason for this change is to avoid changing to Observer since
the rest of io.grpc consistently uses Listener.
CC @zhangkun83

api: Rename NameResolver.Observer to Listener2

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.20.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.12.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.13.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.14.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.15.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.17.x backport)

---

api/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/util/ForwardingLoadBalancerHelper.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
xds/third_party/envoy/import.sh

Hierarchical LoadBalancers such as xDS will need this to create NameResolvers to resolve locality target names.

api: add getters for NameResolver.Args and NameResolverRegistry in LoadBalancer.Helper

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (v1.11.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.9.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.8.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.6.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.5.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.7.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.4.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.3.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.2.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.1.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.0.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.19.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.18.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.16.x backport)

---

.travis.yml

travis.yml: Choose dist trusty to fix Java 8 (1.10.x backport)

---

api/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

We have seen even more cases of wrapping Helper and Subchannel during
the work of XdsLoadBalancer. To simplify the threading story, we will require
that all methods that involve mutable
state to be called from the Synchronization Context.  We will start
logging warnings first, and make them throw in a future release.
Helper.createSubchannel() is already doing so.  This change adds
warnings to the other eligible methods.
For more details: see #5015

api: make LoadBalancer.Helper and Subchannel further non-thread-safe.

---

examples/example-tls/README.md
examples/example-tls/build.gradle

* Make the server cert able to be verified by the ca cert in openssl
* Make the port number consistent in each example (easy to copy paste wrong one)
* use correct netty-tcnative
cc: @jtattermusch

examples: make tls example easier to run

---

.travis.yml

It isn't available any more.
-----
This is only applicable to v1.14.x

travis.yml: Remove openjdk10 from matrix (v1.14.x)

---

.travis.yml

OpenJDK 11 is failing to compile because it refuses the -html4 option,
because we are using -Werror. Removing it instead of figuring out a fix.
It's unclear if/how it worked previously.
---
This problem only applies to v1.17.x.

travis.yml: Remove openjdk11 from matrix (v1.17.x)

---

testing/src/main/java/io/grpc/internal/testing/TestUtils.java
testing/src/main/java/io/grpc/testing/TestUtils.java

Without this, test failures are generated within google3 for our
(firestore) integration tests.

testing: Close cert files to avoid resource leak

---

xds/third_party/envoy/import.sh
xds/third_party/envoy/src/main/proto/envoy/api/v2/cds.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/address.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/health_check.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/discovery.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/endpoint/endpoint.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/endpoint/load_report.proto
xds/third_party/envoy/src/main/proto/udpa/data/orca/v1/orca_load_report.proto

Envoy's xds load_report proto added a [new field](https://github.com/envoyproxy/envoy/blob/5a92867ab5437861b072921b11e9083cf0c63aa5/api/envoy/api/v2/endpoint/load_report.proto#L42) to `LoadStatsRequest`.

xds/third_party: update xds load report proto by importing latest files from envoy repo

---

examples/src/test/java/io/grpc/examples/helloworld/HelloWorldClientTest.java
examples/src/test/java/io/grpc/examples/helloworld/HelloWorldServerTest.java
examples/src/test/java/io/grpc/examples/routeguide/RouteGuideClientTest.java
examples/src/test/java/io/grpc/examples/routeguide/RouteGuideServerTest.java

Since the HelloWorld tests are atm the "documentation" for how to do unit tests for grpc I think it would be good to add a note about the danger of the `directExecutor()`, particularly in bidirectional streaming.
I considered removing the `directExecutor ` but it seems a common pattern in the grpc test suite and has it's merits so warning devs seems like a better solution.
related: 
- https://github.com/grpc/grpc-java/issues/3084
- https://github.com/grpc/grpc-java/issues/2263

docs: add note about directExecutor in example tests.

---

buildscripts/kokoro/bazel.sh

------
This was done for v1.20.x and later in #5411

buildscripts: Specify Bazel version to use (v1.19.x)

---

api/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java

Contrary to #5736, we will still keep the sync-context requirement of
requestConnection(), because it prevents API fragmentation.
PickFirstLoadBalancer is the only known violator.  We will fix it on
master, but we don't want to make that change on 1.21.x because the
release is soon.  We simply remove the warning in this release so that
users won't be annoyed.
This supersedes #5736

api: temporarily remove the warning about sync-context in requestConnection

---

buildscripts/kokoro/bazel.sh

Backport of #5719, but for a different bazel version

buildscripts: Specify Bazel version to use (1.17.x)

---

buildscripts/kokoro/bazel.sh

buildscripts: Specify Bazel version to use (1.16.x backport)

---

buildscripts/kokoro/bazel.sh

buildscripts: Specify Bazel version to use (1.15.x backport)

---

buildscripts/kokoro/bazel.sh

buildscripts: Specify Bazel version to use (1.13.x backport)

---

buildscripts/kokoro/bazel.sh

buildscripts: Specify Bazel version to use (1.12.x backport)

---

buildscripts/kokoro/bazel.sh

buildscripts: Specify Bazel version to use (1.11.x backport)

---

buildscripts/kokoro/bazel.sh

buildscripts: Specify Bazel version to use (1.10.x backport)

---

buildscripts/kokoro/bazel.sh

buildscripts: Specify Bazel version to use (1.14.x backport)

---

xds/src/main/java/io/grpc/xds/ClientLoadCounter.java
xds/src/main/java/io/grpc/xds/XdsLoadStatsStore.java
xds/src/test/java/io/grpc/xds/ClientLoadCounterTest.java
xds/src/test/java/io/grpc/xds/XdsLoadReportClientImplTest.java
xds/src/test/java/io/grpc/xds/XdsLoadStatsStoreTest.java

This supports the recent change of adding the [new field](https://github.com/envoyproxy/envoy/blob/c054a0faf1a7c959476ffcc1c4cfdcc77adff090/api/envoy/api/v2/endpoint/load_report.proto#L42) in load reporting proto.

xds: add counts for recently issued calls in client side load reporting

---

RELEASING.md

It's fine if the command changes in the future, but we do want to start making
the release notes earlier than later.

RELEASING.md: Document command to start making release notes

---

core/src/main/java/io/grpc/internal/DelayedClientTransport.java
core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java

We check for idle mode the first time we try newStream(), but failed to when
newStream races with reprocess(). This would normally be a very rare race,
except when you consider that AbstractChannelBuilder will call
managedChannel.enterIdle() when the network changes.
Fixes #5729

core: Handle IDLE MODE race in DelayedClientTransport

---

api/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/PickFirstLoadBalancer.java
core/src/main/java/io/grpc/util/ForwardingLoadBalancer.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/PickFirstLoadBalancerTest.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

We will require Subchannel.requestConnection() to be called from
sync-context (#5722), but SubchannelPicker.requestConnection() is
currently calling it with the assumption of thread-safety.  Actually
SubchannelPicker.requestConnection() is called already from
sync-context by ChannelImpl, it makes more sense to move this method
to LoadBalancer where all other methods are sync-context'ed, rather than
making SubchannelPicker.requestConnection() sync-context'ed and fragmenting
the SubchannelPicker API because pickSubchannel() is thread-safe.
C++ also has the requestConnection() equivalent on their LoadBalancer
interface.

api: move SubchannelPicker.requestConnection() to LoadBalancer.

---

api/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java

The warning is causing problem for imports.

api: (port from 1.21.x) temporarily remove the warning about sync-context in requestConnection()

---

core/src/main/java/io/grpc/internal/DelayedClientTransport.java
core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java

We check for idle mode the first time we try newStream(), but failed to when
newStream races with reprocess(). This would normally be a very rare race,
except when you consider that AbstractChannelBuilder will call
managedChannel.enterIdle() when the network changes.
Fixes #5729
-------
This is a backport of #5749

core: Handle IDLE MODE race in DelayedClientTransport (v1.21.x backport)

---

examples/example-tls/README.md
examples/example-tls/pom.xml
examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldClientTls.java
examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldServerTls.java

Also fix tcnative, which was the wrong version and would cause a crash
with NoSuchMethodError.
As noticed when looking into #5737

examples: Use encouraged APIs and avoid over-specifying configuration

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/netty/NettyServerTransport.java
netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java

Changes:
* PlaintextProtocolNegotiator is the same between client and server
* ServerTlsHandler is rewritten to not handle errors 
* Also, it now sets the security level attribute, which I don't think it did previously
* NettyServerTransport now uses WBAEH, similar to the client. I don't think the buffer is needed, but it does  correctly handle errors during the startup

netty: change server to new protocol negotiator model

---

api/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/PickFirstLoadBalancer.java
core/src/test/java/io/grpc/internal/PickFirstLoadBalancerTest.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

The pick_first policies in core and grpclb previously would call
Subchannel.requestConnection() from data-path.  They now will schedule
that call in the sync-context to avoid the warning.  They will only
call it for the first pick of each picker, to prevent storming the
sync-context.

api/core/grpclb: add warning about calling Subchannel.requestConnection() outside of sync-context

---

api/src/main/java/io/grpc/ManagedChannelBuilder.java

It appears the docs were not updated when this was changed in d74091f5, which
was first released in v1.1.

api: Fix doc for default value of idleTimeout()

---

api/src/main/java/io/grpc/NameResolver.java

We think NameResolver.Listener2 may still change, so don't yet encourage
people to migrate.
Fixes #5764

api: Don't yet deprecate NameResolver.Listener

---

examples/example-tls/README.md
examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldClientTls.java

The way of generating self-signed keys and certificates in TLS example does not work, since the generated certificates does not contain Subject Alternative Names. 
Generating self-sign certificates (which requires special config for subject alternative names) is quite involved and users may encounter problems doing that (#5737). For maintainability, we do not provide a separate set of certs here. We recommend users to use our test certs for running the TLS example.

examples: use test certs for running example-tls

---

xds/src/main/java/io/grpc/xds/XdsLoadBalancerProvider.java
xds/src/main/resources/META-INF/services/io.grpc.LoadBalancerProvider

Also changed `XdsLoadBalancerProvider` to avoid initialization error when using `ServiceLoader`.

xds: populate XdsLoadBalancerProvider to ServiceLoader

---

xds/src/main/java/io/grpc/xds/XdsComms.java

The `resource_name` field in EDS request should be the same as the one from a CDS response. Now we don't send CDS request, it's unclear what the value should be for now. In current integration test, the traffic director will fail with a wrong `resource_name` (authority is a wrong resource name), but with no `resource_name` it will succeed.

xds: not sending resource_name in EDS request

---

api/src/main/java/io/grpc/NameResolver.java

We think NameResolver.Listener2 may still change, so don't yet encourage
people to migrate.
Fixes #5764
------
This is a backport of #5767

api: Don't yet deprecate NameResolver.Listener (v1.21.x backport)

---

api/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/AbstractSubchannel.java
core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/main/java/io/grpc/internal/InternalSubchannel.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/OobChannel.java
core/src/main/java/io/grpc/internal/TransportProvider.java
core/src/main/java/io/grpc/util/ForwardingSubchannel.java
core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

Previously PickResult's Subchannel must be the actual implementation
returned from the Channel's Helper, and Channel would cast it to the
implementation class in order to use it.  This will be broken if
Subchannel is wrapped in the case of hierarchical LoadBalancers.
getInternalSubchannel() is the guaranteed path for the Channel to get
the InternalSubchannel implementation.  It is friendly for wrapping.
Background: #5676

api: add Subchannel.getInternalSubchannel().

---

core/src/main/java/io/grpc/internal/InternalSubchannel.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

Currently `Subchannel`'s `ChannelLogger` is created inside `InternalSubchannel`, which is instantiated in `Subchannel.start(SubchannelStateListener)`. Therefore, referring it (even though we are not using it but just assign to somewhere) before `Subchannel.start(SubchannelStateListener)` will cause NullPointerException. One example is in [`HealthCheckingLoadBalancerFactory`](https://github.com/grpc/grpc-java/blob/54bbd372ef34a66a777569216ba303b9c9f1d55f/services/src/main/java/io/grpc/services/HealthCheckingLoadBalancerFactory.java#L260).
This PR fixes this bug.

core: create subchannelLogger outside InternalSubchannel and before calling start()

---

api/src/main/java/io/grpc/Attributes.java
api/src/test/java/io/grpc/AttributesTest.java

Some Protocol Negotiators want to remove or rewrite certain attribute keys as they propagate along.  Add a `discard()` method similar to Metadata

core: add discard method for Attributes

---

RELEASING.md

search.maven.org is more authoritative than mvnrepository.com

RELEASING.md: Use search.maven.org instead of mvnrepository.com

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

The old createSubchannel() doesn't require being called from
sync-context, thus its implementation schedules start() on
sync-context because start() has such requirement.  However, if a
LoadBalancer call createSubchannel() in sync-context, start() is
queued and only called after the control exits the sync-context.  If
createSubchannel() is immediately followed by other Subchannel methods
that requires start(), such as requestConnection(), they will fail.
This will be a very common issue as most LoadBalancers call
createSubchannel() in the sync-context.
This fix splits out the real work of start() into internalStart() which
is called by the old createSubchannel().

core: fix a deterministic race between the old createSubchannel() and Subchannel.requestConnection().

---

core/src/main/java/io/grpc/internal/CensusStatsModule.java
core/src/test/java/io/grpc/internal/CensusModulesTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
testing/src/main/java/io/grpc/internal/testing/StatsTestUtils.java

The `method` and `status` tags shouldn't be propagated in the first place,
but in previous OpenCensus implementation all tags are propagating by
default. Now with the TagMetadata it may make sense to change them to
local tags.
This will be a breaking change to users who depend on the behavior that
these tags propagate through process boundaries.

core: Make OpenCensus tags non-propagating.

---

xds/src/main/java/io/grpc/xds/LocalityStore.java
xds/src/main/java/io/grpc/xds/XdsComms.java
xds/src/main/java/io/grpc/xds/XdsLoadBalancer.java
xds/src/test/java/io/grpc/xds/LocalityStoreTest.java
xds/src/test/java/io/grpc/xds/XdsCommsTest.java
xds/src/test/java/io/grpc/xds/XdsLoadBalancerTest.java

- Cancel fallback timer and/or exit fallback mode once receiving an EDS response indicating 100% drop.
- Also update balancing state once receiving the first EDS response with drop information when the channel is at the initial IDLE state.

xds: handle 100% drop for fallback mode

---

core/src/main/java/io/grpc/internal/GrpcUtil.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java

As mentioned in 5188[1], the default used with the enableKeepAlive API
conflicted with the default server enforcement. Instead of fixing it,
remove it. These APIs were deprecated in v1.3.0 in April 2017.
1. https://github.com/grpc/grpc-java/issues/5188#issuecomment-482269303

Remove deprecated enableKeepAlive API from transports

---

examples/README.md

As seen in hacker news comment https://news.ycombinator.com/item?id=20025085 of story https://news.ycombinator.com/item?id=20021759.

Explain why client stub mocking is discouraged

---

api/src/main/java/io/grpc/LoadBalancer.java
api/src/test/java/io/grpc/LoadBalancerTest.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/PickFirstLoadBalancer.java
core/src/main/java/io/grpc/util/ForwardingLoadBalancerHelper.java
core/src/main/java/io/grpc/util/ForwardingSubchannel.java
core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/PickFirstLoadBalancerTest.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

api: deprecate Helper.updateSubchannelAddresses() and add equivalent on Subchannel

---

core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

Previously, AutoConfiguredLoadBalancer was also handling it, but it
doesn't trigger retries.  By returning true for
canHandleEmptyAddressListFromNameResolution(),
AutoConfiguredLoadBalancer effectively by-passed the empty-result
handling logic in ManagedChannelImpl, thus resolution retries were
never triggered.
This change requires AutoConfiguredLoadBalancer to stop being a
LoadBalancer, for its tryHandleResolvedAddresses().  It doesn't
cause any trouble because AutoConfiguredLoadBalancer has become
less and less like a LoadBalancer during the service config changes.
Resolves #5692

core: only let ManagedChannelImpl convert empty resolution result to error

---

api/src/main/java/io/grpc/SynchronizationContext.java

This is the conceptual model we use. Document it to help aid others'
understanding and make it easier to understand when it is appropriate to
use.

api: Mention similarity of synccontext to a dedicated thread

---

interop-testing/build.gradle
interop-testing/src/main/java/io/grpc/testing/integration/GrpclbLongLivedAffinityTestClient.java

This is a long-running stand-alone test client for a specific customer that uses GRPCLB's pick_first mode.

 interop-testing: create GrpclbLongLivedAffinityTestClient

---

SECURITY.md
build.gradle
examples/example-tls/build.gradle
examples/example-tls/pom.xml
repositories.bzl

We are currently having issue with version 4.1.36.Final (see https://github.com/netty/netty/issues/9207), so bump to 4.1.35.Final.

netty: bump netty version to 4.1.35.Final and netty-tcnative version to 2.0.25.Final 

---

interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java

We want the interop client to be configured like a normal user would,
and a normal user wouldn't call sslSocketFactory to use the default
roots.

interop-testing: Only set okhttp's sslSocketFactory for test CA

---

core/src/main/java/io/grpc/inprocess/InProcessTransport.java
core/src/main/java/io/grpc/internal/ServerStream.java
core/src/test/java/io/grpc/internal/AbstractServerStreamTest.java
netty/src/main/java/io/grpc/netty/NettyServerStream.java

This is to use in the PerfMark tag. (once that PR is submitted)

core,netty: expose server stream id

---

android/build.gradle
buildscripts/kokoro/linux_artifacts.sh

com.github.dcendents:android-maven-gradle-plugin is incompatible with
Gradle 5 and the project hasn't seen any activity in over a year, so it
seems unlikely to get fixed.
We want to use maven-publish anyway, since that's what we use elsewhere.
--------
CC @creamsoup

android: Convert to maven-publish

---

alts/src/main/java/io/grpc/alts/internal/AltsHandshakerClient.java

alts: ensure only the first few bytes of key are used

---

build.gradle

There's only one classifier that we use today, and we really want the
compilation results to be the same independent of which machine you
compiled on.

Hard-code Netty's epoll classifier

---

java_grpc_library.bzl

Depending on jdk:toolchain causes java_grpc_library to always use the
_default_ toolchain, even if the user tried to override it. Changing to
:current_java_toolchain allows the rule to use the user-selected
toolchain when overridden.
Tested by adding to BUILD:
```
load("@bazel_tools//tools/jdk:default_java_toolchain.bzl", "default_java_toolchain")
default_java_toolchain(
name = "mychain",
misc = ["-Amy=flag"],
visibility = ["//visibility:public"],
)
```
And then verifying -Amy=flag is in the output of:
```
bazel aquery --java_toolchain=:mychain services:_reflection_java_grpc
```
Fixes #5841

java_grpc_library.bzl: Support alternative javac toolchains

---

services/src/main/java/io/grpc/services/HealthCheckingLoadBalancerFactory.java
services/src/test/java/io/grpc/services/HealthCheckingLoadBalancerFactoryTest.java

HealthCheckingLoadBalancer.shutdown() calls
hcState.onSubchannelState(SHUTDOWN) which removes that hcState from
helper.hcStates.  Therefore, if more than one Subchannels are present,
ConcurrentModificationException will be thrown.
Since HealthCheckingLoadBalancer.shutdown() will clear the hcStates
set after the loop, it's unnecessary to do the deletion within the
loop.  However, when a Subchannel is shutdown by LoadBalancer, its
HcState still needs to be removed.  To do that, change moves the
deletion to Subchannel.shutdown().

services: fix HealthCheckingLoadBalancer.shutdown().

---

build.gradle
core/BUILD.bazel
core/build.gradle
core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/main/java/io/grpc/internal/ServerCallImpl.java
core/src/main/java/io/grpc/internal/ServerImpl.java
core/src/main/java/io/grpc/perfmark/InternalPerfMark.java
core/src/main/java/io/grpc/perfmark/PerfMark.java
core/src/main/java/io/grpc/perfmark/PerfMarkTask.java
core/src/main/java/io/grpc/perfmark/PerfMarker.java
core/src/main/java/io/grpc/perfmark/PerfTag.java
core/src/main/java/io/grpc/perfmark/package-info.java
core/src/test/java/io/grpc/internal/ServerCallImplTest.java
core/src/test/java/io/grpc/internal/ServerImplTest.java
netty/BUILD.bazel
netty/src/main/java/io/grpc/netty/NettyClientStream.java
netty/src/main/java/io/grpc/netty/NettyServerStream.java
netty/src/main/java/io/grpc/netty/SendGrpcFrameCommand.java
netty/src/main/java/io/grpc/netty/WriteQueue.java
repositories.bzl

This causes internal breakage which needs to be resolved before continuing.
This reverts commit 71967622d635160172e0739541f88197f9da70a2.

Revert "core, netty: add io.perfmark Annotations"

---

xds/src/main/java/io/grpc/xds/XdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/XdsLoadBalancerProvider.java
xds/src/test/java/io/grpc/xds/FallbackManagerTest.java
xds/src/test/java/io/grpc/xds/XdsLoadBalancerTest.java

During migration, the name resolver may not know when the client has been upgraded to xds, so it may still send grpclb v1 addresses with a list of policies including both grpclb v1 and xds.

xds: allow grpclb balancer addresses for backward compatibility

---

xds/src/main/java/io/grpc/xds/XdsLoadStatsStore.java
xds/src/test/java/io/grpc/xds/XdsLoadReportClientImplTest.java
xds/src/test/java/io/grpc/xds/XdsLoadStatsStoreTest.java

[`total_dropped_requests`](https://github.com/envoyproxy/envoy/blob/68020a30525437ce3554f10e2fad7b02a5b9723c/api/envoy/api/v2/endpoint/load_report.proto#L131) should be set to sum of `dropped_count` in each `dropped_requests`. This is omitted in design doc, but the implementation has this.

xds: fix bug of missing total_dropped_requests field in ClusterStats proto

---

xds/src/main/java/io/grpc/xds/XdsLoadReportClientImpl.java
xds/src/main/java/io/grpc/xds/XdsLoadStatsStore.java
xds/src/test/java/io/grpc/xds/XdsLoadReportClientImplTest.java
xds/src/test/java/io/grpc/xds/XdsLoadStatsStoreTest.java

This is a bugfix as mentioned in #5863.
Fixed bug of using the wrong `cluster_name` in `ClusterStats` of `LoadStatsRequest`. This should be the GSLB service name, instead of the load-balanced service name (i.e., hostname) from client perspective. This `cluster_name` is received in `LoadStatsResponse` in load reporting response (as well as in EDS response). See [grpc-go](https://github.com/grpc/grpc-go/pull/2845)'s change as well.

xds: fix bug of using the wrong cluster name for client load reporting

---

netty/src/main/java/io/grpc/netty/NettyServerTransport.java
netty/src/test/java/io/grpc/netty/NettyServerTransportTest.java

Transport level exceptions (e.g. "Connection reset by peer") are not
useful and clutter the logs. `NettyServerTransport` contains logic to
log such exceptions at level `FINE`.
When running with epoll, transport level exceptions are prefixed with
additional contextual information (e.g. "syscall:read(..) failed:") that
causes the exceptions to be logged at level `INFO`.
Update the filtering logic to match on error messages _containing_ the
blacklisted messages, rather than using string equality.
Closes #5872.
Signed-off-by: Nick Travers <n.e.travers@gmail.com>

netty: refine filtering for benign transport level exceptions

---

xds/src/main/java/io/grpc/xds/LocalityStore.java
xds/src/main/java/io/grpc/xds/XdsComms.java
xds/src/main/java/io/grpc/xds/XdsLbState.java
xds/src/main/java/io/grpc/xds/XdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/XdsLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/XdsLoadReportClient.java
xds/src/main/java/io/grpc/xds/XdsLoadReportClientImpl.java
xds/src/test/java/io/grpc/xds/LocalityStoreTest.java
xds/src/test/java/io/grpc/xds/XdsCommsTest.java
xds/src/test/java/io/grpc/xds/XdsLbStateTest.java
xds/src/test/java/io/grpc/xds/XdsLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/XdsLoadBalancerWithLrsTest.java
xds/src/test/java/io/grpc/xds/XdsLoadReportClientImplTest.java

This PR is the second part of #5836, which adds load reporting into xds load balancer.
There are two parts of client load reporting: a `StatsStore` for managing recorded stats (e.g., load data, backend metrics, drops) and an `XdsLoadReportClient` for sending load reports to the remote balancer. 
Some main changes:
- `XdsLoadReportClient` stays the same lifecycle as the balancer `Channel`, which only changes upon balance name change.
- `LocalityStore` creates and maintains the `StatsStore` and expose a method `getStatsStore()` to allow accessing it for creating a `XdsLoadReportClient` instance.
- `addLocality()` and `removeLocality()` are called on `StatsStore` when `XdsComms` invokes `LocalityStore#updateLocalityStore()`.
- `XdsLoadBalancer` manages the lifecycle of balance channel as …

xds: integrate client load reporting with xds load balancer (part 2)

---

services/src/main/java/io/grpc/services/HealthCheckingLoadBalancerFactory.java
services/src/test/java/io/grpc/services/HealthCheckingLoadBalancerFactoryTest.java

This reverts commit c6f15162ff3d5e21c3cb037079ddf8292fb68140 (#5848). It broke
an internal health checking test because the server wouldn't shut down.
We assume the health checking RPC isn't getting closed.

Revert "services: fix HealthCheckingLoadBalancer.shutdown(). (#5848)"

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

panic mode was temporarily disabled by #4152 and re-enabled by #4245,
but the tests were not.  This has caused a few test code that was
broken but executed at all.
Also verify that panic mode is not triggered in the tests unexpectedly.

core/test: re-enable tests for panic mode.

---

xds/src/main/java/io/grpc/xds/XdsLoadStatsStore.java
xds/src/test/java/io/grpc/xds/XdsLoadStatsStoreTest.java

Previously I forgot to handle the case when the original `PickResult` is `NO_RESULT` specially. In that case, the `PickResult`'s `status` is `OK` while it has no `Subchannel` (returns `null` when calling `PickResult#getSubchannel()`). We should not intercept `PickResult` with no `Subchannel` as `PickResult.withSubchannel()` has the check for non-null `Subchannel`.
The test case was actually incorrect as I forgot to add the locality counter in `StatsStore` before testing intercepting invalid `PickResult`s (which is an invalid use case for `StatsStore`). Therefore, it didn't really go through.

xds: StatsStore#interceptPickResult should not intercept NO_RESULT

---

core/src/main/java/io/grpc/internal/ClientCallImpl.java

We were logging when withDeadline() was used, not when the Context was used. As
discovered while looking at https://stackoverflow.com/q/56593692/4690866 .
In e19e8f7d updateTimeoutHeaders was removed and logIfContextNarrowedTimeout
was called directly. However, the two methods had reverse ordering of
callDeadine/outerCallDeadline and the caller did not get their arguments
swapped.

core: Fix FINE deadline logging

---

api/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

No more methods on the `LoadBalancer` will be called after
`LoadBalancer#shutdown()` is called.  This includes
`LoadBalancer#handleSubchannelState()` too.  `SubchannelStateListener`
inherited this restriction.  However, this special case makes
`onSubchannelState(SHUTDOWN)` an unreliable way of being notified
about `Subchannel` SHUTDOWN, and may confuse/complicate a
wrapping `LoadBalancer` that expects the full notification (e.g., #5875).
The javadoc isn't clear whether this restriction applies.  I think
it's more useful to make it no apply.

 core: SubchannelStateListener continues to receive updates after LoadBalancer is shutdown.

---

xds/src/main/java/io/grpc/xds/ClientLoadCounter.java
xds/src/main/java/io/grpc/xds/StatsStore.java
xds/src/main/java/io/grpc/xds/XdsLoadStatsStore.java
xds/src/test/java/io/grpc/xds/XdsLoadStatsStoreTest.java

As discussed in https://github.com/grpc/grpc-java/pull/5878#discussion_r294055292, `ClientLoadCounter` will no longer extend `StatsCounter`.

xds: remove mockable abstraction for ClientLoadCounter

---

core/src/main/java/io/grpc/internal/ServerImpl.java
core/src/test/java/io/grpc/internal/ServerImplTest.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyClientStream.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/netty/NettyServerStream.java
netty/src/main/java/io/grpc/netty/SendGrpcFrameCommand.java
netty/src/main/java/io/grpc/netty/StreamIdHolder.java
netty/src/main/java/io/grpc/netty/WriteQueue.java
netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
netty/src/test/java/io/grpc/netty/NettyServerStreamTest.java

This change removes the WriteQueue linking and splits it out into each
of the commands, so that the trace is more precise, and the tag
information is correct.
It is still unclear what the initial Tag should be for ClientCallImpl,
since it should not access the TransportState to get the HTTP/2 stream id.

core,netty: use PerfMark tags with the HTTP/2 stream ids

---

java_grpc_library.bzl

Depending on jdk:toolchain causes java_grpc_library to always use the
_default_ toolchain, even if the user tried to override it. Changing to
:current_java_toolchain allows the rule to use the user-selected
toolchain when overridden.
Tested by adding to BUILD:
load("@bazel_tools//tools/jdk:default_java_toolchain.bzl", "default_java_toolchain")
default_java_toolchain(
name = "mychain",
misc = ["-Amy=flag"],
visibility = ["//visibility:public"],
)
And then verifying -Amy=flag is in the output of:
bazel aquery --java_toolchain=:mychain services:_reflection_java_grpc
Fixes #5841
Backport of #5844

java_grpc_library.bzl: Support alternative javac toolchains (1.21.x backport)

---

alts/src/main/java/io/grpc/alts/internal/TsiHandshakeHandler.java
alts/src/test/java/io/grpc/alts/internal/AltsProtocolNegotiatorTest.java
alts/src/test/java/io/grpc/alts/internal/GoogleDefaultProtocolNegotiatorTest.java
netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
netty/src/main/java/io/grpc/netty/WriteBufferingAndExceptionHandler.java
netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java

This change is needed after trying to use the new style protocol negotiators internally.  The problem is that some handlers fire the event in handlerAdded, which is too early.  The followup PNE is fired after handlerAdded, which breaks the composibility of the negotiators.
To fix this, this change modifies the negotiation flow.  Specifically:
* Negotiators should NEVER fire a negotiation from handlerAdded, instead they should wait until userEventTriggered
* Negotiators now do state checking on the PNE.  If it is set twice, it fails.  If it has not been received when doing the next stage of negotiation, it fails.
* WBAEH now fires the initial, default event.  This is the only handler that can fire it from handlerAdded
The tests updated are ones not using WBAEH (which they probably should). …

netty,alts: fire initial protocol negotiation event in WBAEH

---

netty/shaded/build.gradle

Maven does not include transitive runtime dependencies in the
compile-time classpath (testing shows Gradle 4 does). So if a user
references the shaded NettyServerBuilder without also depending on
grpc-core directly, compilation will fail because
AbstractServerImplBuilder couldn't be found.
This isn't technically a problem, since we're not wanting to encourage
users to reference the shaded classes directly. But some users will
certainly reference the classes anyway and the error is pretty confusing
while also being trivially worked around. In other words: it justs
wastes people's time and benefits nobody.
Fixes #5881

netty-shaded: Use compile instead of runtime dependency in pom

---

core/src/main/java/io/grpc/internal/ClientStream.java
core/src/main/java/io/grpc/internal/DelayedStream.java
core/src/test/java/io/grpc/internal/DelayedStreamTest.java

In #5892 getAttributes() is called without any regard of timing.
Currently DelayedStream.getAttributes() wil throw if called before
passThrough was set.  Just to be safe, we are removing that
restriction and making it clear on the javadoc.
On the other hand, we intend to keep the timing restriction on
ClientCall.getAttributes().

core: ClientStream.getAttributes() can be called at any time.

---

netty/src/main/java/io/grpc/netty/NettyServer.java

We only care about when closing is done, not whether it is successful or not.
If there's a failure, we're already going to log a warning. Use await to avoid
throwing unexpectedly.
------
Noticed this when double-checking that it was different methods that wait uninterruptably.

netty: Use await instead of sync

---

xds/src/main/java/io/grpc/xds/ClientLoadCounter.java
xds/src/main/java/io/grpc/xds/LocalityStore.java
xds/src/main/java/io/grpc/xds/StatsStore.java
xds/src/main/java/io/grpc/xds/XdsLoadStatsStore.java
xds/src/test/java/io/grpc/xds/ClientLoadCounterTest.java
xds/src/test/java/io/grpc/xds/LocalityStoreTest.java
xds/src/test/java/io/grpc/xds/XdsLbStateTest.java
xds/src/test/java/io/grpc/xds/XdsLoadStatsStoreTest.java

Previously we have `StatsStore#interceptPickResult()` for applying client load recording logic to `PickResult` returned by original `SubchannelPicker`. However, we need to do another layer of wrapping for applying another `ClientStreamTracer.Factory` to receive backend metrics, and we did not have method in `StatsStore` to do that. This becomes weird as one interception is done via calling a method in `StatsStore` and the other is on-the-fly.
Therefore, I removed `interceptPickResult()` method from `StatsStore` interface. Instead, provide two `SubchannelPicker` wrapper classes, `LoadRecordingSubchannelPicker` and `MetricsObservingSubchannelPicker`. xDS load balancer wraps its pickers with these two wrapper classes to enable both load and backend metrics recording.
Tests in xDS load …

xds: redesign client load recording and backend metrics receiving interface

---

xds/src/main/java/io/grpc/xds/LocalityStore.java

`LocalityStore` has clear-box tests such that inter-locality subchannel picking relies on the order of most recent locality update. Existing implementation loses the ordering when localities are stored in a `HashMap`, the order of `WeightedChildPicker`s (which are wrapped inter-localityo pickers) in `InterLocalityPicker` become indeterministic. This would cause test flakiness as the list of `WeightedChildPicker` passed into `FakePickerFactory#picker(...)` does not reflect the order of localities in most recent locality update.

xds: use order-deterministic locality map for preserving most recent locality update to eliminate test flakiness

---

xds/src/main/java/io/grpc/xds/LocalityStore.java
xds/src/main/java/io/grpc/xds/XdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/XdsLoadReportClient.java
xds/src/main/java/io/grpc/xds/XdsLoadReportClientImpl.java
xds/src/test/java/io/grpc/xds/LocalityStoreTest.java
xds/src/test/java/io/grpc/xds/XdsLoadBalancerWithLrsTest.java
xds/src/test/java/io/grpc/xds/XdsLoadReportClientImplTest.java

To integrate reporting OOB backend metrics, we wrap each xDS's child load balancer helper with `OrcaReportingHelperWrapper`, which invokes the registered `OrcaOobReportListener#onLoadReport(...)` upon receiving backend metrics reports. Client side aggregation happens naturally via creating the `OrcaOobReportListener` instance with the locality counter the child helper belongs to.
The interval for receiving backend metrics reports is set to be the same as the client side load reporting, which is received from traffic director in [load reporting response](https://github.com/grpc/grpc-java/blob/44bbccff79d108baf90f55226a4fbc62fcbcaab4/xds/third_party/envoy/src/main/proto/envoy/service/load_stats/v2/lrs.proto#L77). We pass this interval to each child helper through `XdsLoadReportCallback`, …

xds: integrate receiving and reporting OOB backend metrics in xDS load balancer

---

netty/shaded/build.gradle

Maven does not include transitive runtime dependencies in the
compile-time classpath (testing shows Gradle 4 does; docs say
Gradle 5 doesn't). So if a user references the shaded
NettyServerBuilder without also depending on grpc-core directly,
compilation will fail because AbstractServerImplBuilder couldn't
be found.
This isn't technically a problem, since we're not wanting to encourage
users to reference the shaded classes directly. But some users will
certainly reference the classes anyway and the error is pretty confusing
while also being trivially worked around. In other words: it justs
wastes people's time and benefits nobody.
Fixes #5881

netty-shaded: Use compile instead of runtime dependency in pom (backport of #5901)

---

core/src/main/java/io/grpc/internal/ManagedChannelServiceConfig.java
core/src/main/java/io/grpc/internal/ServiceConfigUtil.java
examples/README.md
examples/src/main/resources/io/grpc/examples/hedging/hedging_service_config.json

@carl-mastrangelo , this PR has two relaxations on retry/heding policies (to follow the [spec](https://github.com/grpc/proposal/blob/master/A6-client-retries.md)):
1. allow integer status codes
2. allow empty nonfatalStatusCodes
If this will introduce too much conflict to your ongoing work on service config error handling, I will revert 1. and let you implement it, and keep only 2.

core, examples: allow empty nonfatalStatusCodes, and integer status codes

---

netty/src/main/java/io/grpc/netty/WriteBufferingAndExceptionHandler.java
netty/src/test/java/io/grpc/netty/WriteBufferingAndExceptionHandlerTest.java

Incase a negotiating handler misses a read, and it reaches the WBAEH, it should cause a failure.  Also, if closing the channel fails while handling another error, log the second failure.

netty: make unexpected reads fail negotiation, and log close failures

---

netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java

copy paste error from adding ProtcolNegotiatorHandler

netty: don't use InternalProtocolNegotiators in ProtocolNegotiators

---

compiler/BUILD.bazel

Fixes #5942
Prior to 745aa0a2f570d74e7d7fe0c72334c24e21b8ab17, this target was visible publicly and is useful for external projects that depend on the protoc plugin.

Make //compiler:grpc_java_plugin publicly visible again

---

compiler/BUILD.bazel

The 3rd-party rules_proto project is referencing our compiler directly
and not using our java_grpc_library. This target is fine for them to
use (although we'd prefer using our java_grpc_library), but most users
shouldn't be touching it.
Related to #5942 and #5947

bazel: Add comment for public protoc plugin

---

compiler/BUILD.bazel

Backport of #5947 and #5952
CC @aaliddell

Make //compiler:grpc_java_plugin publicly visible again (1.21 backport)

---

xds/src/main/java/io/grpc/xds/XdsComms.java
xds/src/test/java/io/grpc/xds/XdsCommsTest.java

An edge case is that all localities report zero weight, did we decide what to do then?

xds: ignore zero-weighted locality

---

compiler/BUILD.bazel

Backport of #5947 and #5952
CC @aaliddell

Make //compiler:grpc_java_plugin publicly visible again (1.22 backport)

---

.gitignore

For Intellij there are two ways to import a project: file based and directory based. *.ipr and *.iws need to be ignore for file based project.

gitignore: Intellij filebased import

---

documentation/android-channel-builder.md

This is a complement of #5914
There is a bug for `CURRENT_GRPC_VERSION` in the modified lines which will be fixed in a follow up PR.

doc: Favor implementation to compile in documentation

---

java_grpc_library.bzl

In addition to this welcome functionality, this change also makes it
possible to fix http://github.com/bazelbuild/bazel/issues/7157 by
tolerating proto_library rules using a virtual import directory.
CC @lberki @mjduijn
This is an export of cl/256951455.
-------
@mjduijn, you may be interested to test with this. Medium/long-term, @lberki mentioned that proto_common will be receiving a function for us to use to avoid calling protoc directly.

java_grpc_library.bzl: Work with proto_library rules using strip_import_prefix / import_prefix

---

xds/src/generated/main/grpc/io/envoyproxy/envoy/api/v2/EndpointDiscoveryServiceGrpc.java
xds/src/main/java/io/grpc/xds/ClientLoadCounter.java
xds/src/test/java/io/grpc/xds/ClientLoadCounterTest.java
xds/third_party/envoy/import.sh
xds/third_party/envoy/src/main/proto/envoy/api/v2/auth/cert.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/cds.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/cluster/circuit_breaker.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/cluster/outlier_detection.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/address.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/base.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/config_source.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/grpc_service.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/health_check.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/protocol.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/discovery.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/eds.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/endpoint/endpoint.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/endpoint/load_report.proto
xds/third_party/envoy/src/main/proto/envoy/type/percent.proto
xds/third_party/envoy/src/main/proto/envoy/type/range.proto
xds/third_party/envoy/src/main/proto/udpa/data/orca/v1/orca_load_report.proto

One breaking change:
- The field `request_cost_or_utilization` in `OrcaLoadReport` is split into `request_cost` and `utilization` separately.
- This changes how gRPC backend metrics listener record received metrics.
DO NOT MERGE until envoy commit `3be027b1a661136ed2d9597f2e00ce035b6e3f1b` has been brought into Google internal and change our import again to match that.
**To patch this in google3:**
```
$ g4d && cd third_party/java_src/grpc
$ patch -p1 < <(curl -L https://github.com/grpc/grpc-java/pull/5929.diff)
```
**Then skip the generated Grpc classes:**
```
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/xds/src/generated/main/grpc/io/envoyproxy/envoy/api/v2/EndpointDisco …
```

xds: import third party envoy proto

---

repositories.bzl

The version of netty-common imported by `repositories.bzl` is out of sync with the rest of the netty deps, leading to `NoSuchMethodError` exceptions due to changes in method signatures between the versions. Presently common is using 4.1.35, whilst the rest of netty is using 4.1.37. This PR updates common to match the others at 4.1.37.

Fix mismatched Netty versions in repositories.bzl

---

core/src/main/java/io/grpc/internal/InternalSubchannel.java
core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

when we queue and execute the runnable in transport terminated, it may not be drained immediately if there's a already drain is running on the other thread. 
Adding a boolean to check shutdown is called before terminated.

core: fix terminated status check in TransportListener

---

xds/src/main/java/io/grpc/xds/LocalityStore.java
xds/src/test/java/io/grpc/xds/LocalityStoreTest.java

As discussed in https://github.com/grpc/grpc-java/pull/5973#discussion_r302289849, this PR fixed the bug and added test coverage without modifying `WeightChildPicker` implementation.

xds: Fix bug of locality store not update weights for existing localities

---

build.gradle
core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/main/java/io/grpc/internal/ServerImpl.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyClientStream.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/netty/NettyServerStream.java
netty/src/main/java/io/grpc/netty/SendGrpcFrameCommand.java
netty/src/main/java/io/grpc/netty/WriteQueue.java
repositories.bzl

The main changes how linking is done.  Linking is now always done
through the `PerfMark` entry class.   This is for two reasons:
1.  It make instrumenting the linking calls *much* easier.
2.  It follows the API pattern of "verbNoun()".  Previous callsites
would have `Link link = PerfMark.link(); link.link()`.  This
stuttering is not quick to follow.
Generated using:
```
find -name \*.java -exec sed -i 's#link = PerfMark.link();#link = PerfMark.linkOut();#g' {} \;
find -name \*.java -exec sed -i 's#link.link();#PerfMark.linkIn(link);#g' {} \;
find -name \*.java -exec sed -i 's#command.getLink().link();#PerfMark.linkIn(command.getLink());#g' {} \;
find -name \*.java -exec sed -i 's#cmd.getLink().link();#PerfMark.linkIn(cmd.getLink());#g' {} \;
find -name \*.java -exec sed -i …
```

Bump PerfMark to 0.17.0

---

interop-testing/src/test/java/io/grpc/testing/integration/CascadingTest.java

ServerCall.close() is meant to only be accessed from a single thread, but in the test it is accessed from the callbacks of several client calls.  Synchronize access to sate TSAN.

interop-testing: fix race in CascadingTest

---

core/src/main/java/io/grpc/internal/TransportTracer.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java

Found using TSAN, which shows the number of calls succeeded being incremented from multiple event loops

netty: don't share transport tracers across transports

---

cronet/src/main/java/io/grpc/cronet/InternalCronetChannelBuilder.java

Will make `CronetChannelBuilder#setTrafficStatsTag(...)` and `CronetChannelBuilder#setTrafficStatsUid(...)` package-private after resolving all the usages internally.

cronet: add accessor class for CronetChannelBuilder to avoid exposing setTrafficStats* API directly.

---

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/test/java/io/grpc/testing/integration/ConcurrencyTest.java
netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
netty/src/test/java/io/grpc/netty/WriteQueueTest.java

These tests don't really need such a high deadline, but when running under TSAN they do.

netty,interop-testing: increase timeouts on tests for TSAN

---

java_grpc_library.bzl

Migrate the provider containing information about protocol buffers from the old-style 'dep.proto' pattern to the new-style 'dep[ProtoInfo]' one.

java_grpc_library.bzl: Migrate from 'proto' to ProtoInfo syntax

---

services/src/main/java/io/grpc/services/CallMetricRecorder.java
services/src/main/java/io/grpc/services/InternalCallMetricRecorder.java
services/src/test/java/io/grpc/services/CallMetricRecorderTest.java

Most part is copied from existing `CallMetricRecorder`, removed methods that are no longer necessary and add a method to dump saved metric values.

services: implement a lb policy agnostic call metric recorder for backend applications

---

services/src/test/java/io/grpc/services/CallMetricRecorderTest.java

Missed something in #6004. Not critical, but it's good to have it.

xds: add a missing test case for CallMetricRecorder and polish test data

---

services/src/main/java/io/grpc/services/InternalCallMetricRecorder.java
xds/build.gradle
xds/src/main/java/io/grpc/xds/OrcaMetricReportingServerInterceptor.java
xds/src/test/java/io/grpc/xds/OrcaMetricReportingServerInterceptorTest.java

`ServerInterceptor` for intercepting server calls with context of holding a `CallMetricRecorder` and attaching saved metric values in RPC trailers in ORCA format.
PS: let me know if missing any important test cases.

xds: implement a server interceptor for taking server application metrics and sending to client side in ORCA format

---

compiler/README.md

It is very confusing trying to figure it out yourself.

compiler: add note about where to download precompiled version of plugin

---

api/src/test/java/io/grpc/CallOptionsTest.java
context/src/main/java/io/grpc/Deadline.java
context/src/test/java/io/grpc/DeadlineTest.java

This makes `Deadline` more test-friendly.  Next step is to allow
`ServerBuilder` to take a custom `Ticker` and use it for creating
incoming `Deadline`s.  With both changes in, application logic will be
able to verify the Deadlines they set.
For #2531
Tracked by #6030

context: allow creating Deadline with custom Ticker.

---

services/src/main/java/io/grpc/services/CallMetricRecorder.java
services/src/test/java/io/grpc/services/CallMetricRecorderTest.java

The internal implementation of `CallMetricRecorder` will be deleted. Found another two test methods used to exist in the old version.

services: add even more (context-related) test cases for CallMetricRecorder

---

core/build.gradle
core/src/main/java/io/grpc/internal/CensusStatsModule.java
core/src/main/java/io/grpc/internal/DeprecatedCensusConstants.java
core/src/test/java/io/grpc/internal/CensusModulesTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

Fixes #5593 and supersedes #5601
Now that https://github.com/census-instrumentation/opencensus-java/pull/1854 has been merged & released as 0.21.0. We can start using the method & status tags.
Background:
Opencensus introduced new tags for status and method (https://github.com/census-instrumentation/opencensus-java/pull/1115). The old views that used those tags were deprecated and new views were created that used the new tags. However grpc-java wasn't updated to use the new tags due to concern of breaking existing metrics. This resulted in the old views being deprecated while the new views were broken (goomics <span>#</span>50).
https://github.com/census-instrumentation/opencensus-java/pull/1854 added a compatibility layer to opencensus that would remap new tags to old tags for old views. …

core: Migrate to new OpenCensus method & status tags

---

context/src/main/java/io/grpc/Deadline.java
context/src/test/java/io/grpc/DeadlineTest.java
core/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java
core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
core/src/main/java/io/grpc/internal/ServerImpl.java
core/src/test/java/io/grpc/inprocess/InProcessServerBuilderTest.java
core/src/test/java/io/grpc/internal/FakeClock.java
core/src/test/java/io/grpc/internal/ServerImplTest.java

`ServerImpl` uses that ticker to create incoming `Deadline`s. This feature is specifically restricted to in-process, as it can also customize `ScheduledExecutorService`, and them together can fake out the clock which is useful in tests. On the other hand, a fake `Ticker` won't work with Netty's `ScheduledExecutorService`.
Also improved mismatch detection, documentation and tests in `Deadline`.
Resolves #2531

core: allow setting custom Deadline.Ticker to InProcessServerBuilder

---

core/src/main/java/io/grpc/internal/SharedResourceHolder.java
core/src/test/java/io/grpc/internal/SharedResourceHolderTest.java

core: handle removing partially-closed resources for throwing on close. Fixes #6002

---

core/src/main/java/io/grpc/internal/SharedResourceHolder.java
core/src/test/java/io/grpc/internal/SharedResourceHolderTest.java

Resolves #6002.
Backport of #6044.

core: handle removing partially-closed resources for throwing on close. Fixes #6002 (1.22.x backport)

---

netty/BUILD.bazel

There's no third_party directory.
This change makes the repository compatible with
Bazel change --incompatible_disallow_empty_glob.

Remove missing pattern from glob

---

cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
cronet/src/main/java/io/grpc/cronet/InternalCronetChannelBuilder.java

All Internal usages have been migrated through an accessor class.
TODO: we may also want to hide `CronetCallOptions#withAnnotation(..)` from external users. If we are going to do that, need to restrict internal usages first (there are a couple).

cronet: do not expose setTrafficStats* as public APIs

---

netty/build.gradle
netty/src/main/java/io/grpc/netty/Http2ControlFrameLimitEncoder.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java

Http2ControlFrameLimitEncoder is from Netty. It is copied here as a
temporary measure until we upgrade to the version of Netty that includes
the class.
See CVE-2019-9515

netty: Limit number of frames client can cause server to enqueue

---

netty/build.gradle
netty/src/main/java/io/grpc/netty/Http2ControlFrameLimitEncoder.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java

Http2ControlFrameLimitEncoder is from Netty. It is copied here as a
temporary measure until we upgrade to the version of Netty that includes
the class.
See CVE-2019-9515
This is a backport of #6056

netty: Limit number of frames client can cause server to enqueue (v1.23.x backport)

---

netty/build.gradle
netty/src/main/java/io/grpc/netty/Http2ControlFrameLimitEncoder.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java

Http2ControlFrameLimitEncoder is from Netty. It is copied here as a
temporary measure until we upgrade to the version of Netty that includes
the class.
See CVE-2019-9515
This is a backport of #6056

netty: Limit number of frames client can cause server to enqueue (v1.21.x backport)

---

netty/build.gradle
netty/src/main/java/io/grpc/netty/Http2ControlFrameLimitEncoder.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java

Http2ControlFrameLimitEncoder is from Netty. It is copied here as a
temporary measure until we upgrade to the version of Netty that includes
the class.
See CVE-2019-9515
This is a backport of #6056

netty: Limit number of frames client can cause server to enqueue (v1.22.x backport)

---

android/build.gradle
build.gradle

This fixes the following warning when building grpc-android:
WARNING: API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompiler(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

Upgrade gradle-errorprone-plugin to 0.8.1

---

java_grpc_library.bzl

`java_grpc_library` targets based on `java_proto_library` targets with more than one `proto_library` dependency can't be built on Windows, starting somewhere before 1.22. A minimal reproducing example is available on https://github.com/Xjs/bazel-grpc-java-win-repro (see `README.md` there for output on my machine as well as steps to reproduce). 
The issue stems from `protoc` [configuring a different path separator for Windows at compile time](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/command_line_interface.cc#L767) in combination with `java_grpc_library` [always using `:`](https://github.com/grpc/grpc-java/blob/master/java_grpc_library.bzl#L96).
This PR uses the path separator available from the bazel context's host_configuration to resolve the …

Fix java path separator bug on Windows

---

okhttp/BUILD.bazel
okhttp/src/main/java/io/grpc/okhttp/AsyncSink.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java

Did not find a proper approach to incorporate stream IDs/RPC method names as tags for tracing tasks running on Okio side (Netty's io happens in terms of a set of commands, each of which is associated with `TransportState` containing the tag. But Okhttp transport dumps bytes to `AsyncSink`, in which we do not keep track of what those bytes are).

okhttp: add PerfMark tracing for okhttp transport

---

android/build.gradle

The issue is dependencies are not in the classpath that `javadoc` uses to resolve type references in the source code.
We have to use `afterEvaluate` to fill `javadocs` task's `classpath` after android tasks have been executed.

android: fix Javadoc symbol/class not found errors

---

cronet/src/main/java/io/grpc/cronet/CronetCallOptions.java
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java
cronet/src/main/java/io/grpc/cronet/InternalCronetCallOptions.java
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java

Implementations in `CronetCallOptions` are moved into `CronetClientStream`, only keep indirections to them in `CronetCallOptions`. 
Created an `InternalCronetCallOptions` accessor class for restricting internal usages of those APIs.
After all internal usages are migrated to the internal accessor, `CronetCallOptions` will be deleted.

cronet: move call options APIs into an internal accessor class

---

xds/src/main/java/io/grpc/xds/XdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/XdsLoadBalancerProvider.java
xds/src/test/java/io/grpc/xds/XdsLoadBalancerProviderTest.java

`XdsLoadBalancer` will be replaced by `XdsLoadBalancer2`, and `XdsConfig` is better fit in `XdsLoadBalancerProvider`.

xds: move XdsLoadBalancer.XdsConfig to XdsLoadBalancerProvider

---

android/src/main/java/io/grpc/android/AndroidChannelBuilder.java
android/src/test/java/io/grpc/android/AndroidChannelBuilderTest.java

TODO: delete deprecated method after migrating all internal usages.

android: clean up AndroidChannelBuilder APIs

---

context/src/main/java/io/grpc/Deadline.java

doc: explicitly mention that Deadline might saturate

---

README.md
SECURITY.md
examples/example-gauth/pom.xml
examples/example-tls/pom.xml
examples/pom.xml

There are a few improvements available in the plugin updates and we should point to the latest version in our readme.
https://github.com/xolstice/protobuf-maven-plugin/compare/protobuf-maven-plugin-0.5.1...protobuf-maven-plugin-0.6.1?expand=1
* Mainly documentation improvements, but also some bugfixes (including Fixed Zip Slip(?))
https://github.com/trustin/os-maven-plugin/releases
* Improved/extended OS detection, better eclipse integration
I use the updated plugins myself and didn't encounter any problems with them yet.

docs: Update the maven plugins in the project readme

---

netty/BUILD.bazel
netty/shaded/BUILD.bazel
repositories.bzl

See census-instrumentation/opencensus-java#1963
CC @songy23 @blt-gw @creamsoup

netty: Add Bazel target similar to netty-shaded

---

cronet/src/main/java/io/grpc/cronet/InternalCronetCallOptions.java

Add this getter for some internal users wishing to retrieve annotations in their unit tests.

cronet: add getter for retrieving grpc cronet annotations in calloptions

---

android/src/main/java/io/grpc/android/AndroidChannelBuilder.java
android/src/test/java/io/grpc/android/AndroidChannelBuilderTest.java

All internal usages cleared. Delete deprecated methods. `fromBuilder` has only been deprecated recently, leave it for a while for external-import user migration (see https://github.com/grpc/grpc-java/issues/6043#issuecomment-523216599).

android: delete deprecated API methods

---

core/BUILD.bazel
netty/BUILD.bazel
repositories.bzl

This can be used to prevent duplicate classes in the classpath, one via
Maven and one via Bazel-native.
See census-instrumentation/opencensus-java#1963 and #5359
CC @songy23 @blt-gw @creamsoup

bazel: Add helper for maven_install's override_targets

---

auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java

auth: fix builder invocation for converting Google service account to Jwt access credential

---

README.md

The Plugins DSL has matured and is now preferred. It's also more terse,
which is nice.

README.md: Swap to Gradle Plugins DSL

---

auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java

Resolves #6105 .
Backport of #6106.

auth: fix builder invocation for converting Google service account to Jwt access credential (backport 1.21.x)

---

auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java

Resolves #6105 .
Backport of #6106.

auth: fix builder invocation for converting Google service account to Jwt access credential (backport 1.22.x)

---

auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java

Resolves #6105 .
Backport of #6106.

auth: fix builder invocation for converting Google service account to Jwt access credential (backport 1.23.x)

---

cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java

grpc-cronet relies on the feature of cronet's `BidirectionalStream`, which is created by `ExperimentalCronetEngine#newBidirectionalStreamBuilder(...)` (returns a `ExperimentalBidirectionalStream.Builder`). Since it's "experimental", we want to avoid calling APIs on `ExperimentalBidirectionalStream.Builder`.
We've removed grpc-cronet APIs that depends on `ExperimentalBidirectionalStream.Builder`'s APIs and only allow restricted internal usages. External users should have no chance calling them and result in breakage. Now we switch to load those unstable `ExperimentalBidirectionalStream.Builder` APIs and invoke them through reflection at runtime.
The three potentially unstable APIs are `setTrafficStatsTag`, `setTrafficStatsUid` and `addRequestAnnotation`. For now, we handle method not found …

cronet: use reflection to load and invoke experimental APIs in ExperimentalBidirectionalStream.Builder

---

xds/src/main/java/io/grpc/xds/LocalityStore.java
xds/src/main/java/io/grpc/xds/XdsComms.java

Change
```java
ImmutableMap.Builder<XdsLocality, LocalityLbInfo> builder = ImmutableMap.builder();
for (Map.Entry<XdsLocality, LocalityLbInfo> entry : localityMap.entrySet()) {
if (!entry.getKey().equals(locality)) {
builder.put(entry);
}
}
localityMap = builder.build();
```
into
```java
Map<XdsLocality, LocalityLbInfo> copy = new LinkedHashMap<>(localityMap);
copy.remove(locality);
localityMap = ImmutableMap.copyOf(copy);
```
The performance is almost the same, unless we use the beta API `ImmutableMap.builderWithExpectedSize()`. But the latter has much better readability.

xds: clean up some ImmutableMaps

---

cronet/build.gradle

- Added maven publish plugin and configurations.
- Changed grpc-cronet minSdkVersion to 16 as cronet dependency requires so.
- Changed cronet dependency configuration, `grpc-cronet` now only has dependency on [`cronet-api`](https://mvnrepository.com/artifact/org.chromium.net/cronet-api), which contains only the API layer of cronet without implementation providers. Cronet implementation is still needed for tests.

cronet: add grpc-cronet artifact publishing configurations

---

auth/build.gradle
auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java
build.gradle

Resolves #6129 
Previous we compare encoded JWT tokens to verify that service account information is correctly used for converting `ServiceAccountCredentials` to `ServiceAccountJwtAccessCredentials`. The encoded JWT payload contains issue/expiration information, which causes the test to be flaky when comparing two hashes that generated at slightly different time.
This change uses `java-jwt` to decode the token and verify if it contains our original information for test.

auth: verify information in decoded JWT token instead of comparing encoded hash values

---

xds/src/main/java/io/grpc/xds/LocalityStore.java
xds/src/test/java/io/grpc/xds/LocalityStoreTest.java

There is a bug in `LocalityStore.reset()` found during import cc @ejona86

xds: fix a bug locality reset not fully clean up

---

xds/src/test/java/io/grpc/xds/LoadReportClientImplTest.java

This is a test case that covers LRS client re-establishes load reporting (send a new initial request and receives new LRS response which contains new load reporting interval) after the LB stream is closed.
The slight difference between this test case and `lrsStreamClosedAndRetried` is that it focuses on load reporting being back to normal after retry while the other focuses on re-establishing the load reporting RPC.

xds: add test for LRS retry and re-send load reports after stream closed

---

core/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java
core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java

This allows plumbing information to the subchannel via Attributes, like
an authority override. RR still does not support multiple EAGs that only
differ by attributes.
CC @enguerrand

core: Propagate EAG Attributes in RoundRobinLoadBalancer

---

api/src/main/java/io/grpc/EquivalentAddressGroup.java
core/src/main/java/io/grpc/internal/InternalSubchannel.java
core/src/test/java/io/grpc/internal/InternalSubchannelTest.java

This enables NameResolvers to dynamically provide authority for each
Subchannel
Fixes #4469

core: Add Attributes.Key for authority in EquivalentAddressGroup (#4469)

---

all/build.gradle
alts/build.gradle
api/build.gradle
auth/build.gradle
benchmarks/build.gradle
bom/build.gradle
build.gradle
compiler/build.gradle
context/build.gradle
core/build.gradle
gae-interop-testing/gae-jdk8/build.gradle
gradle/wrapper/gradle-wrapper.properties
grpclb/build.gradle
interop-testing/build.gradle
netty/build.gradle
netty/shaded/build.gradle
okhttp/build.gradle
protobuf-lite/build.gradle
protobuf/build.gradle
services/build.gradle
settings.gradle
stub/build.gradle
testing-proto/build.gradle
testing/build.gradle
xds/build.gradle

This is a long patch series that looks intimidating. But it is split up into atomic comics that apply to one piece at a time. I spent effort to avoid changing existing behavior or to further simplify, so most large code movements have no differences within their body. The exception is cases where we had ifs checking which project we were processing; those were mostly removed in favor of triggering the behavior only if a project uses specific plugins.
This is in no way "complete." There's still plenty of other improvements available.
There were several objectives: 1) get the build file into stronger shape where related code is together, 2) allow more independence in projects (e.g., we shouldn't be forced to migrate all projects to java-library at once) and 3) allow Android to be part of …

Refactor top-level build.gradle to avoid enabling unhelpful plugins

---

xds/src/main/java/io/grpc/xds/XdsLoadBalancer2.java
xds/src/test/java/io/grpc/xds/XdsLoadBalancer2Test.java

- Get rid of `XdsLbState` and make config change handling into two layers: `LookasideLb` (handles balancer name) and `LookasideChannelLb` (handles child policy), under `XdsLoadBalanecer` (fallback manager layer)
- Move `XdsComms`/`AdsStream` to a layer under `LookasideChannelLb`. They don't keep the helper, but only `SyncCtx` and `ChannelLogger`
- For each layer, we pass in a `LoadBalancer.Factory` for the next/child layer. In test, 
+ we mock/fake the factory, so we don't care about the implementation details of the child layer.
+ we capture the helper of `factory.newBalancer(factory)`, so we can mimic `updateBalancingState() `from the child layer.
Part 1 contains fallback management logic. There is no change in fallback management logic.

xds: restructure XdsLoadBalancer part 1

---

netty/src/main/java/io/grpc/netty/InternalProtocolNegotiators.java
netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java

netty: converts Proxy handler into new protocol negotiation style

---

netty/src/main/java/io/grpc/netty/InternalProtocolNegotiators.java
netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java

related to #6167
1.22.x doesn't have the `ProtocolNegotiationHandler` interface, so the `ProxyProtocolNegotiationHandler` implements same mechanism.

netty: converts Proxy handler into new protocol negotiation style backport of #6159

---

build.gradle
xds/src/main/java/io/grpc/xds/XdsAttributes.java

The fileTree is supposed to be relative to the current project, which in
this case would be the child project, but apparently it isn't. Poked
around but couldn't find out why. In any case this fixes a regression
introduced in 4215b80b where checkstyle would no longer file any Java
files and thus it would not notice any failures.

gradle: Use absolute path with checkstyle fileTree

---

xds/src/main/java/io/grpc/xds/LocalityStore.java
xds/src/main/java/io/grpc/xds/XdsComms.java
xds/src/test/java/io/grpc/xds/LocalityStoreTest.java
xds/src/test/java/io/grpc/xds/XdsCommsTest.java
xds/src/test/java/io/grpc/xds/XdsLoadBalancerTest.java

- Implementing [priority failover](https://docs.google.com/document/d/1fAfdllHJ3JaaKVIdrrBaMnZSHxGAnlx4BhABMQQOn_4/view?pli=1#heading=h.krx7r69l2drb)
- Removed `localityWeight` field from `LocalityLbInfo` because this is always available and up to date in `edsResponsLocalityInfo`, otherwise need to create a new instance of `LocalityLbInfo` each time weight is updated.
- Introduced `PriorityManager` that manages all the priority failover logic.

xds: Priority failover

---

RELEASING.md
cronet/README.md

cronet: update README for using published grpc-cronet with play service Cronet implementation (backport 1.24.x)

---

alts/src/main/java/io/grpc/alts/internal/AltsTsiHandshaker.java
alts/src/main/java/io/grpc/alts/internal/NettyTsiHandshaker.java
alts/src/main/java/io/grpc/alts/internal/TsiHandshakeHandler.java
alts/src/main/java/io/grpc/alts/internal/TsiHandshaker.java
alts/src/test/java/io/grpc/alts/internal/AltsProtocolNegotiatorTest.java
alts/src/test/java/io/grpc/alts/internal/FakeTsiHandshaker.java

Some handshaker implementation has internal closable resources. It only works if everything goes well (current implementation relying on the internal resource closes itself).
In failure case, it may cause leak depends on the implementation of tsi handshaker. Having close in TsiHandshaker and TsiHandshakeHandler explicitly close the handshaker should avoid such leak; less error prone.

alts: add close to TsiHandshaker to avoid resource leak for some impls

---

netty/src/main/java/io/grpc/netty/NettyServerHandler.java

Checking too early leads to false-positives, like if a non-gRPC client
contacts the server or a grpc-web client.

netty: Check for TE header after checking Content-Type

---

core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java
cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java
cronet/src/test/java/io/grpc/cronet/CronetClientTransportTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyClientStream.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientStreamTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

This change adds two booleans to AbstractManagedChannelBuilderImpl to
allow transports to use get and put.   These are currently defaulted to
on, but unset on the method descriptors.   This change is 1/2 that will
allow the safe / idempotent bits to be set on generated proto code.
Part 2/2 will actually enable it.
The use case for this is for interceptors that implement caching logic.
They need to be able to access the safe/idempotent bits on the MD in
order to decide to how to handle the request, even if gRPC doesn't use
GET / PUT HTTP methods.

netty,okhttp,cronet: add option to use get/put when methods are safe/idempotent

---

android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/InteropTask.java
android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/TesterActivity.java
android-interop-testing/app/src/main/res/layout/activity_tester.xml
android-interop-testing/app/src/main/res/values/strings.xml

android-interop-testing: remove settings for using GET via setting MethodDescriptor to safe

---

xds/build.gradle

For SDS, we need the ProtocolNegotiator definitions for custom implementations in grpc-xds (as discussed offline)

Make grpc-xds dependent on grpc-netty 

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/JsonUtil.java
core/src/main/java/io/grpc/internal/ServiceConfigUtil.java

As discussed in https://github.com/grpc/grpc-java/pull/6201#discussion_r329135169, other packages may want to use those Json utility methods.

core: move generic Json util methods out of ServiceConfigUtil

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/JsonUtil.java
core/src/main/java/io/grpc/internal/ServiceConfigUtil.java

This PR patches #6211, `checkObjectList` and `checkStringList` should also be exposed.
TODO: may want to delete copies of json utility methods in grpclb and use those in `JsonUtil`.
https://github.com/grpc/grpc-java/blob/d3e86da6b61f93be81f5f807a0b1cef1c035cff0/grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java#L197-L229
https://github.com/grpc/grpc-java/blob/d3e86da6b61f93be81f5f807a0b1cef1c035cff0/grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancerProvider.java#L102-L133

core: move check Json object methods to JsonUtil

---

alts/build.gradle
alts/src/main/java/io/grpc/alts/internal/AesGcmAeadCrypter.java
alts/src/test/java/io/grpc/alts/internal/ChannelCrypterNettyTestBase.java
alts/src/test/java/io/grpc/alts/internal/TsiTest.java
build.gradle
testing/src/main/java/io/grpc/internal/testing/TestUtils.java

We depend on Conscrypt to help ensure Conscrypt 2.1.0 or newer is used.
It's not 100% clear this is the best approach, but it is the simplest at
present. If Conscrypt is not available then we will just use the JDK's
slower implementation of AES-GCM.
Fixes #6213

alts: Use Conscrypt when available

---

android-interop-testing/app/src/androidTest/java/io/grpc/android/integrationtest/InteropInstrumentationTest.java

Something missing from #6203. Should fix android-interop CI.

andriod-interop-testing: fix InteropTask construction failure with wrong parameters

---

repositories.bzl

The typo was present in the initial version added in 9d6f532
Thanks to @f355 for noticing.

repositories.bzl: Fix typo in maven_install override_targets

---

repositories.bzl

The typo was present in the initial version added in 9d6f532
This is a backport of #6224

repositories.bzl: Fix typo in maven_install override_targets (v1.24.x backport)

---

api/build.gradle
interop-testing/build.gradle
netty/build.gradle
okhttp/build.gradle
services/build.gradle
testing/build.gradle
xds/build.gradle

motivation: when I am running some test case often gradle fails. IIRC this can be environment specific (level of parallelism etc), but there is no real down side of doing it.
```
> % ./gradlew grpc-netty:cleanTest grpc-netty:test --tests "io.grpc.netty.ProtocolNegotiatorsTest.httpProxy_500"
Configuration on demand is an incubating feature.
FAILURE: Build failed with an exception.
* Where:
Build file '${MY_SECRET_HOME:~}/git/grpc-java/netty/build.gradle' line: 22
* What went wrong:
A problem occurred evaluating project ':grpc-netty'.
> Could not get unknown property 'sourceSets' for project ':grpc-core' of type org.gradle.api.Project.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* …
```

build: update modules to wait until dependent sourceSet is available

---

buildscripts/kokoro/android.sh

This reverts commit c240f270773a49eb9c78ad7bcf7ef33c09aa5094.
Fixing #6146 in v1.24.x branch.

Revert "buildscripts: android.sh to clean the build when building HEAD^"

---

xds/src/main/java/io/grpc/xds/LookasideChannelLb.java
xds/src/main/java/io/grpc/xds/LookasideLb.java
xds/src/main/java/io/grpc/xds/XdsLoadBalancer2.java
xds/src/test/java/io/grpc/xds/LookasideChannelLbTest.java
xds/src/test/java/io/grpc/xds/LookasideLbTest.java

Moved `ManagedChannel initLbChannel(Helper helper, String balancerName)` out of `LookasideChannelLb` because `LoadReportClientImpl` need channel be initialized already. 
Migration will be in an upcoming PR.

xds: plumbing restructured xds loadbalancer

---

xds/build.gradle

accidentally removed in a previous PR

re-add the grpc-netty dependency

---

xds/src/main/java/io/grpc/xds/XdsAttributes.java

Making XdsAttributes public and adding *TlsContext attrs to prepare for using *TlsContext in the new SecretManager

xds: XdsAttributes enhancements 

---

xds/src/main/java/io/grpc/xds/LookasideChannelLb.java
xds/src/main/java/io/grpc/xds/LookasideLb.java
xds/src/main/java/io/grpc/xds/XdsComms2.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/LookasideChannelLbTest.java
xds/src/test/java/io/grpc/xds/LookasideLbTest.java
xds/src/test/java/io/grpc/xds/XdsCommsTest.java
xds/src/test/java/io/grpc/xds/XdsNamResolverTest.java

`XdsNameResolver` will load bootstrap file and populate `Node` reference to the `XdsLoadBalancer` through attributes of `ResolvedAddresses`. This is only for demo purpose until `XdsClient` is available, whence `XdsNameResolver` will populate `XdsClient` reference to `XdsLoadBalancer` through attributes instead.

xds: bootstrap xDS load balancer with xDS name resolver

---

COMPILING.md

These changes avoid a dependency on automake, autoconf, and libtool. The
./configure script is only available via the release artifacts, not git.
For example, on Debian Buster only curl and build-essential need to be
installed.

COMPILING.md: Reduce dependencies when building protobuf

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNamResolverTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

The protobuf key balancer_name is corresponding to balancerName in json.

xds: fix wrong json key balancerName

---

COMPILING.md

we don't need Linux ldconfig and ld.so.conf stuff because of the --noshared option

COMPILING.md: fix protobuf build steps 

---

alts/src/main/java/io/grpc/alts/internal/AesGcmAeadCrypter.java
core/src/main/java/io/grpc/internal/ConscryptLoader.java
netty/src/main/java/io/grpc/netty/GrpcSslContexts.java
testing/src/main/java/io/grpc/internal/testing/TestUtils.java

This implicit loading is more conservative than the loading for
tcnative, as Conscrypt will only be implicitly loaded if there are no
other options. This means the Java 9+ JSSE is preferred over Conscrypt
without explicit user configuration.
While we would generally prefer Conscrypt over JSSE, we want to allow
the user to configure their security providers. There wasn't a good way
to do that with netty-tcnative and the performance of JSSE at the time
was abysmal.
While generally being a good way to allow adopting Conscrypt, this also
allows easily using App Engine Java 8's provided Conscrypt which can
substantially reduce binary size.
See googleapis/google-cloud-java#6425
-------
I plan to preserve the two commits when merging.

netty: Implicitly enable Conscrypt when it is available (and share some code)

---

stub/src/main/java/io/grpc/stub/ClientCalls.java
stub/src/test/java/io/grpc/stub/ClientCallsTest.java

This reverts commit 0604e14154ce9de8cdb4822100e84d32ac52bf27.
Previously, the change caused an internal test to hang. But this was caused by Exoblaze (Bazel's `BuildEventServiceModule`)'s timeout management. Not 100% sure, but I am suspecting that it's logic in waiting for shutdown on the same thread (which is the same thread as gRPC's transport thread) caused the `CancelClientStreamCommand` never had chance to run.
The issue was fixed in https://github.com/bazelbuild/bazel/commit/82f5090008b1115d29b3081fe1146ff51bd6aa22#diff-a4dcfc83b91b9ec1e362e379e4331377R417. So nothing needs to be done on our side and we can proceed to roll this forward.
Previous broken tests have passed after applying this change to latest Exoblaze.
Resolves #5576.

Revert "Revert "stub: Wait for onClose when blocking stub is interrupted""

---

okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/framed/Header.java
okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/framed/Hpack.java
okhttp/third_party/okhttp/test/java/io/grpc/okhttp/internal/framed/HpackTest.java

Copied implementation from [OkHttp3 Hpack.kt](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/http2/Hpack.kt). Most changes are on Writer.
Tests are copied from [OkHttp3 HpackTest.java](https://github.com/square/okhttp/blob/master/okhttp/src/test/java/okhttp3/internal/http2/HpackTest.java), but I was trying to avoid introducing dependency of `google/Truth` by preserving the usage of `org.junit.Assert.assertEquals`.
Upstream okhttp3 has pretty good coverage for unit tests. I also inspected packets after the change:
- Before:
`:scheme: https`, `:method: POST` and `:authority: localhost:8080` all represented in the format of `Literal Header Field without indexing - Indexed Name`.
- After:
`:scheme: https` and `:method: POST` are represented in the format of …

okhttp: add full implementation of HPACK header compression

---

repositories.bzl

net_zlib is no longer used ("zlib" is used instead). Zlib and skylib are
both included via protobuf_deps(). With the language-specific rules
needing to be imported (e.g., rules_proto, rules_java) we are relying on
protobuf_deps() pretty heavily starting in Protobuf 3.10, so we aren't
losing much to remove these two deps.

bazel: Remove deps that protobuf includes

---

alts/BUILD.bazel
examples/BUILD.bazel
examples/example-alts/BUILD.bazel
examples/example-tls/BUILD.bazel
grpclb/BUILD.bazel
repositories.bzl
services/src/main/proto/grpc/channelz/v1/channelz.proto

This flag will be enabled by default in Bazel 1.0
Since I changed the grpc-proto repo version for Bazel, I also synced the
protos.

bazel: Support --incompatible_load_proto_rules_from_bzl

---

okhttp/src/main/java/io/grpc/okhttp/Headers.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/HeadersTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientStreamTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

Get transport type by check if `sslSocketFactory` is `null`. Set scheme based on the transport type.
fixes: https://github.com/grpc/grpc-java/issues/6202

okhttp: fix header scheme does not match transport type.

---

okhttp/src/main/java/io/grpc/okhttp/Headers.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/HeadersTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientStreamTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

okhttp: fix header scheme does not match transport type.
(cherry picked from commit ba17682eb28ae9a026b55cf80cad3c73d1f9c1e4)

okhttp: fix header scheme does not match transport type. (backport of #6260)

---

api/src/main/java/io/grpc/ForwardingChannelBuilder.java
api/src/main/java/io/grpc/ManagedChannelBuilder.java
core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java

This reverts commit 296857b4e7a5bb6b5fe367ca6e9ac401dc134a38.
Revert because there are still some internal usages.

Revert "all: remove deprecated usePlaintext(boolean)"

---

xds/src/test/java/io/grpc/xds/sds/trust/SdsX509TrustManagerTest.java

This test is included in the most recent attempt of import, and it also broken with blaze. Disabling it.

xds: disable test that breaks on blaze.

---

api/src/main/java/io/grpc/ForwardingChannelBuilder.java
api/src/main/java/io/grpc/ManagedChannelBuilder.java
api/src/main/java/io/grpc/NameResolver.java
api/src/test/java/io/grpc/NameResolverTest.java
core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

Adds an Executor field to NameResolver.Args, which is optionally set on ManagedChannelBuilder. This allows NameResolver implementations to avoid creating their own thread pools if the application already manages its own pools. 
Addresses #3703.

api,core: Adds an Executor field to NameResolver.Args.

---

protobuf/src/main/java/io/grpc/protobuf/StatusProto.java
protobuf/src/test/java/io/grpc/protobuf/StatusProtoTest.java

the original intention was only generating Status proto from trailers. In actual use cases requires to handle null and derive the Status proto from status. The main reason is there are few cases when the server doesn't send trailers such as server UNREACHABLE, UNAVAILABLE or DEADLINE_EXCEEDED.

protobuf: StatusProto#fromStatusAndTrailers fall-back use status

---

.travis.yml

In 97cb0554 we pinned ourselves to trusty to workaround temporary Java 8
issues. Oracle JDK 8 is "dead" across the ecosystem because Oracle
removed download links to it, so we swap to openjdk 8 as we have done
elsewhere.  OpenJDK 8 is supported with xenial, so we can upgrade.
Unfortunately bionic on Travis does not include openjdk8, so we will be
unable to easily upgrade to newer versions of the distro unless we drop
JDK 8 compilation or we figure out a way to get it working. For example,
in may be possible to install the openjdk-8-jdk package.

travis: Upgrade from trusty to xenial

---

api/src/main/java/io/grpc/ManagedChannelBuilder.java
api/src/main/java/io/grpc/NameResolver.java

These should have been present when initially added in #6238, but we forgot.
CC @groakley

api: Add ExperimentalApi annotations for blockingExecutor

---

stub/src/main/java/io/grpc/stub/ClientCalls.java
stub/src/test/java/io/grpc/stub/ClientCallsTest.java

fixes: https://github.com/grpc/grpc-java/issues/5968

stub: ignore unary response msg if status is not OK

---

xds/third_party/envoy/NOTICE
xds/third_party/envoy/import.sh
xds/third_party/envoy/src/main/proto/envoy/api/v2/auth/cert.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/address.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/base.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/config_source.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/grpc_service.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/health_check.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/core/http_uri.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/discovery.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/eds.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/endpoint/endpoint.proto
xds/third_party/envoy/src/main/proto/envoy/api/v2/endpoint/load_report.proto
xds/third_party/envoy/src/main/proto/envoy/service/discovery/v2/ads.proto
xds/third_party/envoy/src/main/proto/envoy/service/load_stats/v2/lrs.proto
xds/third_party/envoy/src/main/proto/envoy/type/percent.proto
xds/third_party/envoy/src/main/proto/envoy/type/range.proto

Time to update envoy proto version. Corresponding internal import is cl/274202414.
This unblocks us from bringing in `cds.proto`, `lds.proto`, `rds.proto` etc, as there was a bugfix in https://github.com/envoyproxy/envoy/issues/8287, which breaks proto compilation.

xds: update envoy proto version to f709434b37e9ff74666d5b854aa11fb2f1ec37f3

---

core/src/main/java/io/grpc/internal/ServiceConfigUtil.java
core/src/test/java/io/grpc/internal/ServiceConfigUtilTest.java
xds/src/main/java/io/grpc/xds/XdsLoadBalancerProvider.java
xds/src/test/java/io/grpc/xds/XdsLoadBalancerProviderTest.java

Based on changed in cl/273761393. xDS LB policy config proto will contain two new fields:
- `eds_service_name` field, so that the CDS policy can tell the EDS
policy what name to use in the EDS query.  (For backward
compatibility, if this field is not set, it will default to the server
name from the channel's target URI.)
- `lrs_load_reporting_server_name` field to indicate whether LRS load
reporting should be enabled.
TODO: shift to use bootstrap (even though `xdsClient` has not been implemented, internal integration test is ready) and remove `balancer_name` field from `XdsConfig`.
TODO: add `CdsConfig` message for cds policy.

xds: add fields for EDS server and LRS server in XdsConfig

---

xds/build.gradle

The directory third_party/protoc-gen-validate/src/main/proto was removed in #6177.

xds: remove invalid srcDir third_party/protoc-gen-validate/src/main/proto

---

api/src/main/java/io/grpc/MethodDescriptor.java
compiler/src/java_plugin/cpp/java_generator.cpp
compiler/src/test/golden/TestService.java.txt
compiler/src/test/proto/grpc/testing/compiler/test.proto
compiler/src/testLite/golden/TestService.java.txt
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java

This PR is split into two commits, one to stabilize the MethodDescriptors, and the other to update the generated code.    
PTAL @ejona86 
Updates https://github.com/grpc/grpc-java/issues/1775

Expose Safe and Idempotent on Protobuf descriptors

---

grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

Previously, if the remote balancer doesn't close the stream after receiving the half-close, the OOB channel will hang there forever. It's safer to always cancel on the client-side so that the OOB channel can be cleaned up timely, regardless of what the remote balancer does.

grpclb: cancel stream instead of halfClose when balancer shutdown

---

.github/ISSUE_TEMPLATE/ask_question.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_report.md

Hide all descriptive content when issue is filed. Issue like 6330 can looks confusing if we do not hide those things.

github: wrap non-title content into comment blocks.

---

xds/src/main/java/io/grpc/xds/sds/SecretVolumeSslContextProvider.java
xds/src/main/java/io/grpc/xds/sds/SslContextProvider.java
xds/src/main/java/io/grpc/xds/sds/TlsContextManager.java
xds/src/main/java/io/grpc/xds/sds/internal/SdsProtocolNegotiators.java
xds/src/test/java/io/grpc/xds/sds/SecretVolumeSslContextProviderTest.java
xds/src/test/java/io/grpc/xds/sds/TlsContextManagerTest.java

We don't need SecretProvider for generic secrets - so rename appropriately

xds: rename SecretProvider to SslContextProvider and make it non-generic

---

build.gradle
cronet/build.gradle
examples/build.gradle
examples/example-gauth/pom.xml
examples/example-kotlin/build.gradle
examples/pom.xml

[Mockito 2.28.2 ](https://search.maven.org/artifact/org.mockito/mockito-core/2.28.2/jar) is the latest in its 2.X versions.
Grep result for mockito in build.gradle:
There's no 2.25.1 any more:
```
suztomo@suxtomo24:~/grpc-java$ grep -ilr 2.25.1 ./
suztomo@suxtomo24:~/grpc-java$ 
```
Last mockito version upgrade https://github.com/grpc/grpc-java/commit/d35fbd7eee072854c20b61ea7fcf7c70a8e8cb8e modified the 6 files.

all: upgrade to Mockito 2.28.2

---

xds/src/main/java/io/grpc/xds/Bootstrapper.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/BootstrapperTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

Existing `Bootstrapper` implementation reads bootstrap file statically at the first time getting an instance. This is not friendly for usage in resolver, especially for error propagation.
The resolver is doing the work at `NameResolver#start(Listener2)`, which passes resolution results or error to channel through the listener. With the existing `Bootstrapper` implementation, we would need to instantiate a `Bootstrapper` instance in `NameResolver#start(...)` in order to have correct error propagation. But this introduces difficulty for testing. This makes #6240 very awkward.
This PR restructures the implementation of `Bootstrapper`, which adds a `Bootstrapper#readBootstrap()` method that does the work of reading/parsing bootstrap. The bootstrapping result is saved in a static field so that …

xds: refactor Bootstrapper implementation to be more use friendly

---

xds/src/main/java/io/grpc/xds/EnvoyProtoData.java
xds/src/main/java/io/grpc/xds/LoadStatsStore.java
xds/src/main/java/io/grpc/xds/LoadStatsStoreImpl.java
xds/src/main/java/io/grpc/xds/LocalityStore.java
xds/src/main/java/io/grpc/xds/LookasideChannelLb.java
xds/src/test/java/io/grpc/xds/ClusterLoadAssignmentDataTest.java
xds/src/test/java/io/grpc/xds/EnvoyProtoDataTest.java
xds/src/test/java/io/grpc/xds/LoadStatsStoreImplTest.java
xds/src/test/java/io/grpc/xds/LocalityStoreTest.java
xds/src/test/java/io/grpc/xds/LookasideChannelLbTest.java

`EnvoyProtoData.java` defines gRPC's data types for proto messages used in xDS protocol. In gRPC's LB logic, we should only carry gRPC's data type around instead of envoy proto messages.
This provides benefits:
- All xDS communication logic is encapsulated in `XdsClient` (in the future) and `LrsClient` (which is also a component of `XdsClient`), they pass gRPC's own data types to LB policies.
- Since gRPC only uses a subset of envoy's API, most fields in envoy's proto messages are not used. Processing envoy's proto message in gRPC's logic is verbose and can mistakenly touch unused fields. Data types in `EnvoyProtoData` only contains the fields used by gRPC.
For better use experience, please follow the convention of using gRPC's data type in gRPC's logic, only convert to envoy's proto …

xds: refactor gRPC's data types for envoy proto messages

---

xds/src/main/java/io/grpc/xds/Bootstrapper.java

A lint warning is found during the import. http://go/java-practices/exceptions#abstract_throwables

xds: fix lint warning for throwing RuntimeException

---

xds/build.gradle
xds/src/main/java/io/grpc/xds/LookasideLb.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/BootstrapperTest.java
xds/src/test/java/io/grpc/xds/LookasideLbTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

The `XdsNameResolver` reads the bootstrap file and pass channel creds configuration in `ResolutionResult.Attributes` to `XdsLoadBalancer`. LB implementation populates the channel creds configurations and build channel to xDS resolver based on it.
Note: same as the hack for `Node`, this solution is temporary. We do not need to pass node and channel creds config in `ResolutionResult.Attributes` once we encapsulate logic for xDS communication into `XdsClient`. I know it's a bit messy now, but we are migrating to `XdsClient`. Things will be significantly cleaned up after that.

xds: build channel to xDS server with GoogleDefaultChannelBuilder if bootstrap file specifies so

---

api/src/main/java/io/grpc/ForwardingChannelBuilder.java
api/src/main/java/io/grpc/ManagedChannelBuilder.java
api/src/main/java/io/grpc/NameResolver.java
api/src/test/java/io/grpc/NameResolverTest.java
core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

The API review for #6279 came up with a more meaningful name that
better explains the intent. A setter for the old name was left in
ManagedChannelBuilder to ease migration to the new name by current
users.
CC @groakley 
I want to backport this before the release, since this is a brand-new API
in this release.

api: Rename blockingExecutor to offloadExecutor

---

alts/src/main/java/io/grpc/alts/ComputeEngineChannelBuilder.java

alts: fix ComputeEngineChannelBuilder class signature (backport v1.25.x)

---

alts/src/main/java/io/grpc/alts/ComputeEngineChannelBuilder.java

alts: fix ComputeEngineChannelBuilder class signature (backport v1.24.x)

---

alts/src/main/java/io/grpc/alts/ComputeEngineChannelBuilder.java

alts: fix ComputeEngineChannelBuilder class signature (backport v1.23.x)

---

alts/src/main/java/io/grpc/alts/ComputeEngineChannelBuilder.java

alts: fix ComputeEngineChannelBuilder class signature (backport v1.21.x)

---

alts/src/main/java/io/grpc/alts/ComputeEngineChannelBuilder.java

alts: fix ComputeEngineChannelBuilder class signature (backport v1.22.x)

---

alts/src/main/java/io/grpc/alts/ComputeEngineChannelBuilder.java

alts: fix ComputeEngineChannelBuilder class signature (backport v1.20.x)

---

api/src/main/java/io/grpc/ForwardingChannelBuilder.java
api/src/main/java/io/grpc/ManagedChannelBuilder.java
api/src/main/java/io/grpc/NameResolver.java
api/src/test/java/io/grpc/NameResolverTest.java
core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

The API review for #6279 came up with a more meaningful name that
better explains the intent. A setter for the old name was left in
ManagedChannelBuilder to ease migration to the new name by current
users.
This is a backport of #6389 
CC @zhangkun83

api: Rename blockingExecutor to offloadExecutor (v1.25.x backport)

---

benchmarks/build.gradle
interop-testing/build.gradle

backport of #6369 related to #6365

interop-testing,benchmarks: publish tar, zip (backport of #6369 to 1.24.x)

---

netty/src/test/java/io/grpc/netty/WriteBufferingAndExceptionHandlerTest.java

It appears the problem is that server.close() was missing sync(), so the
event loop was still processing the closure when the next test started.
This change is more aggressive than it needs to be, but should make it
less bug-prone.
Fixes #5574

netty: Deflake WriteBufferingAndExceptionHandlerTest

---

netty/src/main/java/io/grpc/netty/NettyServerTransport.java
netty/src/test/java/io/grpc/netty/NettyServerTransportTest.java
okhttp/src/main/java/io/grpc/okhttp/ExceptionHandlingFrameWriter.java
okhttp/src/test/java/io/grpc/okhttp/ExceptionHandlingFrameWriterTest.java

backport of #6334 related to #6322

netty,okhttp: log FINE level for pure IOExceptions when transport terminated (v1.25.x backport)

---

core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/test/java/io/grpc/internal/ClientCallImplTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

This matches the format in `Deadline.toString`

core: use seconds in deadline exceeded string

---

netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java

Remove redundant variable references

netty: remove redundant variable references

---

xds/src/main/java/io/grpc/xds/EnvoyProtoData.java
xds/src/main/java/io/grpc/xds/LocalityStore.java
xds/src/test/java/io/grpc/xds/LocalityStoreTest.java

Let child balancer (currently is Round Robin) handle the address list with only healthy addresses for its locality. If no healthy address available, let the child balancer `handleNameResolutionError`.
@voidzcy @zhangkun83 How do you think the approach?

xds: ignore endpoints with health_status != HEALTHY or UNKNOWN

---

xds/src/main/java/io/grpc/xds/XdsClient.java

Prerequisite for integrating LRS in XdsClient. 
[C++'s implementation](https://github.com/grpc/grpc/blob/970f703337ecc19017a737cc4eb831cd50fd0fec/src/core/ext/filters/client_channel/xds/xds_client.h#L104-L107) has similar APIs.

xds: add APIs for initiating LRS in XdsClient

---

android-interop-testing/app/build.gradle
build.gradle
compiler/build.gradle
examples/android/clientcache/app/build.gradle
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/strictmode/app/build.gradle
examples/example-kotlin/android/helloworld/app/build.gradle
protobuf-lite/build.gradle

This finally brings lite into version number sync with full proto.
-----
This was a change I made in September for proto 3.9. We have since upgraded to 3.10 and the commit message was no longer correct, but it seems the code didn't need to change at all. (You can see my branch name is lite-3.9 :-) )
Fixes #6405 
CC @liusheng, @kiwik, @rafi-kamal, @bubenheimer
See also protocolbuffers/protobuf#6867

Upgrade to protobuf lite 3.10

---

core/src/main/java/io/grpc/internal/ServerImpl.java
core/src/test/java/io/grpc/internal/ServerImplTest.java

fixes: https://github.com/grpc/grpc-java/issues/6300
With these change, it passes the reproducer in that issue.

core: delay attaching cancellation listener to context on server-side.

---

xds/src/main/java/io/grpc/xds/LookasideChannelLb.java
xds/src/main/java/io/grpc/xds/LookasideLb.java
xds/src/main/java/io/grpc/xds/XdsClient.java
xds/src/main/java/io/grpc/xds/XdsComms2.java
xds/src/main/java/io/grpc/xds/XdsLoadBalancerProvider.java
xds/src/test/java/io/grpc/xds/LookasideChannelLbTest.java
xds/src/test/java/io/grpc/xds/XdsCommsTest.java

This is a refactor of the existing xds policy to use XdsClient. It does neither create a copy of EDS policy as in #6371 nor re-implement an EDS policy. This should be similar to the idea of https://github.com/grpc/grpc/pull/20368 in C-core. 
Here it refactors `XdsComms2` to an implementation of `XdsClient`, which can be drop-in replaced by `XdsClientImp` when it's available.
I will add handling `XdsClientRef` in Attributes of `ResolvedAddresses` in after this refactor PR.

xds: refactor xds policy to use XdsClient

---

xds/src/main/java/io/grpc/xds/Bootstrapper.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

Each channel should trigger reading bootstrap file separately, instead of reading it once per JVM. It's not required to cache results of reading bootstrap file.

xds: do not globally cache results of reading bootstrap file

---

core/src/main/java/io/grpc/internal/ServerImpl.java

javadoc parameter name mismatches with the actual parameter name.

core: fix typo in javadoc

---

xds/src/main/java/io/grpc/xds/XdsAttributes.java
xds/src/main/java/io/grpc/xds/XdsClient.java
xds/src/test/java/io/grpc/xds/XdsClientTest.java

There are multiple choices on the type of the attribute key based on an offline discussion with @ejona86 . I'm now leaning to take the ObjectPool approach. The benefit of it could be:
Because both `XdsNameResolver` (The LDS path) and xds load balancer (The EDS-only path) can create XdsClient instance. The ObjectPool approach
- does not rely on the assumption that when shutting down the name resolver, all the balancers created by the name resolver (indirectly) will also be shutdown, although the assumption is true currently.
- does not rely on the order of shutdown events of resolver and any balancers. The xdsClient will be shutdown only once all the balancers and resolver using it are shutdown. No need to worry that `XdsClient` is not usable in any one of the reolver or balancers if other …

xds: add an Attributes for XdsClient reference

---

api/src/main/java/io/grpc/NameResolver.java
api/src/test/java/io/grpc/NameResolverRegistryTest.java
api/src/test/java/io/grpc/NameResolverTest.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/DnsNameResolverProviderTest.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplGetNameResolverTest.java
core/src/test/java/io/grpc/internal/OverrideAuthorityNameResolverTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverProviderTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

~TODO: create tracking issue for `NameResolver.Args.getChannelLogger()` API.~

api, core: make channel logger accessible through NameResolver.Args

---

api/src/main/java/io/grpc/ForwardingChannelBuilder.java
api/src/main/java/io/grpc/ManagedChannelBuilder.java
core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java

This reverts commit 316a739e67609e5be171d0b52c1e4d3c9023d360.

Revert "Revert "all: remove deprecated usePlaintext(boolean)""

---

protobuf/build.gradle

In 48929c4 the protobuf lite artifact name changed from protobuf-lite to
protobuf-javalite. However, the exclusion in grpc-protobuf was missed in the
update, allowing protobuf lite to leak into the classpath. This restores the
previous behavior of only having one protobuf implementation on the classpath.

protobuf: Exclude new javalite artifact name

---

core/src/main/java/io/grpc/internal/GrpcUtil.java
xds/src/main/java/io/grpc/xds/Bootstrapper.java
xds/src/test/java/io/grpc/xds/BootstrapperTest.java

- Make `node` object in bootstrap file (JSON) optional.
- Set `build_version` in `Node` parsed from bootstrap file to gRPC-Java's implementation version.

xds: add gRPC-Java build version into Node parsed for xDS protocol

---

stub/src/main/java/io/grpc/stub/ClientCalls.java
stub/src/main/java/io/grpc/stub/ServerCalls.java

This is already in the documentation in CallStreamObserver, but if the user
gets here the error didn't provide an actionable next step. The message now
provides more help of how they should have called the methods instead of
feeling more like a brick wall.

stub: Provide bread-crumb to user how to configure StreamObserver before start

---

xds/src/main/java/io/grpc/xds/LocalityStore.java
xds/src/main/java/io/grpc/xds/LookasideLb.java
xds/src/test/java/io/grpc/xds/LookasideLbTest.java

Currently `LoadStatsStore` is create by `LocalityStore` and `LoadReportClient` retrieves `LoadStatsStore` from `LocalityStore.getLoadStatsStore()`.
But `LocalityStore` is create by EDS policy, whereas `LoadReportClient` and `LoadStatsStore` should be created by CDS (if not EDS-only), before `LocalityStore` is created. If `LoadReportClient` is embedded in `XdsClientImpl`, it need a `LoadStatsStore` which shouldn't be created by `LocalityStore`.
Instead, `LoadStatsStore` should be create before `LocalityStore` is created, and be passed to `LocalityStore`'s constructor. A getter is not needed.

xds: remove getLoadStatsStore method from LocalityStore

---

core/src/main/java/io/grpc/inprocess/InProcessTransport.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java

Adding interop-test for getting remote server address from client interceptor. Also added this feature to inprocess transport.

interop-testing,core: add interop test to get remote address attributes

---

alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java

This was caught by security review.

alts: fix lazy_channel close

---

COMPILING.md
android-interop-testing/app/build.gradle
build.gradle
buildscripts/build_docker.sh
buildscripts/make_dependencies.bat
buildscripts/make_dependencies.sh
examples/android/clientcache/app/build.gradle
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/strictmode/app/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-kotlin/android/helloworld/app/build.gradle
examples/example-kotlin/build.gradle
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/pom.xml
repositories.bzl

Updating Protobuf to bring in improvements for Android.
Protobuf pulls in the newer version of gson and we are happy to update
to it.
CC @ericgribkoff; I'd like this to get into the release cut (but I can always backport it)

Update protobuf to 3.11.0 and gson to 2.8.6

---

netty/src/main/java/io/grpc/netty/NettyServerTransport.java
netty/src/test/java/io/grpc/netty/NettyServerTransportTest.java

netty: log NativeIoException as FINE level (backport  v1.25.x)

---

repositories.bzl

Bazel was stuck on the javalite branch of protobuf because the master
branch was lacking the toolchain necessary for javalite. The fix was
backported to 3.11 in protocolbuffers/protobuf#6976

Update Bazel+Javalite to 3.11

---

xds/src/main/java/io/grpc/xds/LookasideLb.java
xds/src/main/java/io/grpc/xds/XdsLoadBalancer2.java
xds/src/test/java/io/grpc/xds/LookasideLbTest.java
xds/src/test/java/io/grpc/xds/XdsLoadBalancer2Test.java

- Support `XdsConfig` without `balancerName` field, either get `XdsClient` instance from ResolvedAddresses attributes (XdsNameResolver case) or create one from bootstrap (EDS only case) (Not using `XdsClientImpl` for now because it does not handle EdsUpdate yet).
- The deprecated XdsConfig with `balancerName` field case is still supported for now but unsupported `balancerName` change in XdsConfig due to the extra complexity over things that are going to be entirely deleted.
- Whenever `XdsConfig` is changed (any field is changed), will create a new `EndpointWatcher` with a new `localityStore` and do a graceful switch.

xds: refactor EDS policy to use ObjectPool<XdsClient> with error handling fixes

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/CdsLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/LookasideLb.java
xds/src/main/java/io/grpc/xds/XdsAttributes.java
xds/src/main/resources/META-INF/services/io.grpc.LoadBalancerProvider
xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java

- Contains `ClusterWatcher` implementation. On cluster update, `ClusterWatcherImpl` spawns an EDS child balancer if not created, then based on the ClusterUpdate data, it sends an edsConfig to the EDS child balancer.
- `CdsLoadBalancer` reads `XdsClientRef` and `CdsConfig` from `resolvedAddresses`. Base on `resolvedAddresses`, it register a `ClusterWatcherImpl` to `XdsClient`.
- For a different cluster resource name in CdsConfig when `handleResolvedAddresses()`, `CdsLoadBalancer` will gracefully switch to the new cluster.

xds: add CdsLoadBalancer

---

api/build.gradle
build.gradle
protobuf-lite/build.gradle
protobuf/build.gradle
repositories.bzl

Upgrading animal-sniffer-annotation to the latest [1.18](https://search.maven.org/artifact/org.codehaus.mojo/animal-sniffer-annotations/1.18/jar).
There was a problem in upperBoundCheck in google-cloud-firestore:  https://github.com/googleapis/java-firestore/pull/34.

Animal-sniffer-annotation 1.18

---

alts/build.gradle
core/build.gradle
grpclb/build.gradle
okhttp/build.gradle
services/build.gradle
testing/build.gradle
xds/build.gradle

Followup of https://github.com/grpc/grpc-java/pull/6488#discussion_r354459784. These comments on exclusions with specific versions are hard to maintain.

Replaced outdated exclusion comments

---

xds/src/main/java/io/grpc/xds/Bootstrapper.java
xds/src/main/java/io/grpc/xds/LookasideLb.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/BootstrapperTest.java
xds/src/test/java/io/grpc/xds/LookasideLbTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

In the future, the xDS bootstrap may provides multiple xDS server, with each has its own server URI and channel credential configurations. gRPC client will try to connect to them one by one until found the first reachable one. For now, we only support using the first one.
In this PR:
- Changed the logic of parsing bootstrap file, including the format of data returned to gRPC client.
- Reformated JSON strings in bootstrap related tests.
- Added a couple of test cases for parsing bootstrap file.
- Changed constructor for `XdsClientIImpl` to take in a list of management servers.

xds: support multiple xDS servers in bootstrap file

---

buildscripts/build_artifacts_in_docker.sh
buildscripts/kokoro/linux_artifacts.sh
buildscripts/kokoro/unix.sh
buildscripts/kokoro/upload_artifacts.sh
buildscripts/make_dependencies.sh
compiler/build.gradle
compiler/check-artifact.sh

This change modified the building scripts to support cross compile
grpc-java for aarch64 platform
For grpc/grpc-java#6364

Add support for cross-compiling for aarch64 platform

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

`XdsNameResolver` will eventually send out a CDS config instead EDS config, but balancer_name should never be sent out from `XdsNameResolver` anyway.
This PR is mainly to unblock current staging test.

xds: remove xds balancer_name from resolved service config

---

buildscripts/build_artifacts_in_docker.sh
buildscripts/kokoro/linux_artifacts.sh
buildscripts/kokoro/unix.sh
buildscripts/kokoro/upload_artifacts.sh
buildscripts/make_dependencies.sh
compiler/build.gradle
compiler/check-artifact.sh

This change modified the building scripts to support cross compile
grpc-java for aarch64 platform
For grpc/grpc-java#6364
------
This is a backport of #6441
CC @liusheng

Add support for cross-compiling for aarch64 platform (v1.26.x backport)

---

api/src/main/java/io/grpc/LoadBalancerProvider.java
core/src/main/java/io/grpc/util/GracefulSwitchLoadBalancer.java
core/src/test/java/io/grpc/util/GracefulSwitchLoadBalancerTest.java
xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/LookasideLb.java

`GracefulSwitchLoadBalancer` was doing switch based on `LoadBalancerProvider.getPolicyName()`. This turned out to be very awkward when I have to synthesize a policy name for the provider, and what I actually care about is the identity of the lb provider not necessarily the policy name.
Now `GracefulSwitchLoadBalancer` is doing switch based on identity of `LoadBalancer.Factory`, which is simpler.

core: refactor GracefulSwitchLoadBalancer to switch based on LoadBalancer.Factory

---

xds/src/test/java/io/grpc/xds/XdsClientImplTest.java

When verifying xDS requests, the order of resource names should not matter. `DiscoveryRequestMatcher` can take care of that. 
The best practice is to use `DiscoveryRequestMatcher` for verifying all requests (even those without error message or single resource). You may see in `XdsClientImplTest.java` that a mixed usage of `DiscoveryRequestMatcher` and literal comparison of `DiscoveryRequest` messages. This is because  `DiscoveryRequestMatcher` was introduced later while there were a lot of usages of literal comparison that worked (i.e., for requests having only a single resource and no error_message) and I did not bother change them. 😢

xds: fix bug of verifying xDS requests with ordered resource names.

---

core/src/main/java/io/grpc/internal/ServiceConfigUtil.java
core/src/test/java/io/grpc/internal/ServiceConfigUtilTest.java
xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/LookasideLb.java
xds/src/main/java/io/grpc/xds/XdsLoadBalancerProvider.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/FallbackLbTest.java
xds/src/test/java/io/grpc/xds/LookasideLbTest.java
xds/src/test/java/io/grpc/xds/XdsLoadBalancerProviderTest.java

Verified in internal interop tests, we can drop balancer_name in XdsConfig now.

xds: drop support for balancer_name in XdsConfig

---

xds/src/main/java/io/grpc/xds/XdsClient.java

The naming of the `DEFAULT_INSTANCE` indicates it is a constant, but a `final` is missing.

xds: make XdsChannelFactory default instance a constant.

---

xds/src/main/java/io/grpc/xds/FallbackLb.java

In CDS flow, fallback is not supported. The fallback_policy in XdsConfig is null, causing NPE. This PR fixes that bug.

xds: fix NPE in fallback mode in CDS flow

---

api/src/main/java/io/grpc/InternalMetadata.java
api/src/main/java/io/grpc/Metadata.java
api/src/test/java/io/grpc/MetadataTest.java

Add a new a Metadata.BinaryStreamMarshaller interface which serializes to/from instances of InputStream, and a corresponding Key.of() factory method.
Values set with this type of key will be kept unserialized internally, alongside a reference to the Marshaller. A new method InternalMetadata.serializePartial(), returns values which are either
byte[] or InputStream, allowing transport-specific handling of lazily-serialized values.
For the regular serialize() method, stream-marshalled values will be converted to byte[] via InputStreams.
Transport-internal code can also create metadata with pre-parsed values.

Support for lazily serialized values in Metadata.

---

netty/src/main/java/io/grpc/netty/Utils.java

This reverts commit b0e00fd4bad58350bafbb0411b94c70979f7d3e1.
It may cause leak of netty native buffers when creating and shutting
down Channels on a regular basis.

Revert "netty: enable io.grpc.netty.useCustomAllocator by default"

---

grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

This reverts commit 1949ebd7ef96fa5bc35258da698a1429c4e61819.
The shuffling should be handled by the grpclb server instead.

Revert "grpclb: shuffle pick first index"

---

api/src/main/java/io/grpc/Server.java
examples/src/main/java/io/grpc/examples/advanced/HelloJsonServer.java
examples/src/main/java/io/grpc/examples/experimental/CompressingHelloWorldServerAllMethods.java
examples/src/main/java/io/grpc/examples/experimental/CompressingHelloWorldServerPerMethod.java
examples/src/main/java/io/grpc/examples/header/CustomHeaderServer.java
examples/src/main/java/io/grpc/examples/hedging/HedgingHelloWorldServer.java
examples/src/main/java/io/grpc/examples/helloworld/HelloWorldServer.java
examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlServer.java
examples/src/main/java/io/grpc/examples/routeguide/RouteGuideServer.java
examples/src/test/java/io/grpc/examples/routeguide/RouteGuideServerTest.java

The example servers do not properly wait until preexisting calls complete before shutting down (https://github.com/grpc/grpc-java/issues/6511).
This PR
- Adds a call to `awaitTermination` to wait for preexisting calls to complete (with a 30s timeout)
- Updates the API documentation for `Server.shutdown` to clarify that the call does not wait for preexisting calls to complete before returning.

Gracefully shutdown example servers

---

examples/src/test/java/io/grpc/examples/routeguide/RouteGuideServerTest.java

Throwing makes cleaner code and also is more helpful if the exception is ever
thrown, as the error will be more clear.
-----
I noticed this after #6512 was already merged. Minor, but good to fix in an example.
CC @dounan

examples: Throw exception in test instead of printStackTrace

---

xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/XdsClientImplTest.java

The condition for checking if RPC stream is in retry state is wrong. Should check if the retry task is in `pending` state.

xds: fix bug of concluding retry state without checking retry task status

---

SECURITY.md
api/src/main/java/io/grpc/ManagedChannelBuilder.java

The dns scheme is only the default scheme with grpc-java. Other
libraries could add more NameResolvers and thus change the default. For
compatibility reasons, the schema should therefore be specified
explicitly.
The current javadocs conflict with those of `NameResolverProdiver#priority()`, which allow setting a priority higher than DNS.
Users of grpc-spring-boot-starter who want to use a service discovery have the problem that many libraries don't provide a schema for DNS addresses and therefore don't work anymore without additional configuration.
https://github.com/yidongnan/grpc-spring-boot-starter/issues/268
https://github.com/yidongnan/grpc-spring-boot-starter/issues/304
https://github.com/yidongnan/grpc-spring-boot-starter/issues/300

api: Fix javadoc for ManagedChannelBuilder#forTarget(String)

---

stub/src/main/java/io/grpc/stub/AbstractAsyncStub.java
stub/src/main/java/io/grpc/stub/AbstractBlockingStub.java
stub/src/main/java/io/grpc/stub/AbstractFutureStub.java
stub/src/main/java/io/grpc/stub/AbstractStub.java

rolled forward missed the 1.25.0 branch cut.

stub: fix javadoc to indicate correct version(1.25.0 -> 1.26.0)

---

stub/src/main/java/io/grpc/stub/AbstractAsyncStub.java
stub/src/main/java/io/grpc/stub/AbstractBlockingStub.java
stub/src/main/java/io/grpc/stub/AbstractFutureStub.java
stub/src/main/java/io/grpc/stub/AbstractStub.java

stub: fix javadoc to indicate correct version1.25.0 -> 1.26.0 (backport of #6522 to 1.26.x)

---

xds/src/main/java/io/grpc/xds/XdsClientImpl.java

This is an implementation bug, I think we would not need to add a test case covering it (regardless for regression purposes).

xds: fix bug of not ignoring responses received after shutdown

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/main/java/io/grpc/xds/XdsNameResolverProvider.java
xds/src/test/java/io/grpc/xds/XdsNameResolverProviderTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

When `XdsNameResolver` starts, it instantiate an `XdsClient` instance to send out an xDS discovery RPC resolving cluster name for gRPC target. When a result found, return a `ResolutionResult` with service config containing `cds_experimental` as the load balancing config to the channel. The instantiated `XdsClient` instance is also passed as an `ResolutionResult.Attributes` to channel.

xds: integrate usage of XdsClient in XdsNameResolver

---

netty/src/main/java/io/grpc/netty/Utils.java

Since #6526 has resolved the memory leak, let's turn it back on.

netty: enable io.grpc.netty.useCustomAllocator by default (take 2)

---

repositories.bzl

bazel: Use https to download from Maven Central

---

protobuf-lite/BUILD.bazel

This was missed from 2d592642a, because the select hid the failure.

bazel: Fix renamed javalite target

---

alts/src/main/java/io/grpc/alts/AuthorizationUtil.java
alts/src/test/java/io/grpc/alts/AuthorizationUtilTest.java

Add a simple authorization utility library. 
@ejona86

alts: add client authorization util library

---

protobuf-lite/BUILD.bazel

This was missed from 2d592642a, because the select hid the failure.
-----
This is a backport of #6544

bazel: Fix renamed javalite target (v1.26.x backport)

---

repositories.bzl

Fixes #6536
----
This is a backport of #6543

bazel: Use https to download from Maven Central (v1.26.x backport)

---

repositories.bzl

bazel: Use https to download from Maven Central (1.25.x backport)

---

repositories.bzl

bazel: Use https to download from Maven Central (1.23.x backport)

---

repositories.bzl

bazel: Use https to download from Maven Central (1.24.x backport)

---

build.gradle
repositories.bzl

Grpc-java's proto-google-common-protos dependency is outdated. Upgrading to the latest version.
Motivation of this upgrade is below:
```
io.grpc:grpc-protobuf:1.25.0 x com.google.cloud:google-cloud-bigquerystorage:0.120.0-beta
Class com.google.api.ClientProto is not found (type: CLASS_NOT_FOUND)
com.google.cloud.bigquery.storage.v1beta1.Storage (com.google.api.grpc:proto-google-cloud-bigquerystorage-v1beta1:0.85.0)
Class com.google.api.FieldBehaviorProto is not found (type: CLASS_NOT_FOUND)
com.google.cloud.bigquery.storage.v1beta1.Storage (com.google.api.grpc:proto-google-cloud-bigquerystorage-v1beta1:0.85.0)
Class com.google.api.ResourceProto is not found (type: CLASS_NOT_FOUND)
com.google.cloud.bigquery.storage.v1beta1.Storage …
```

Upgrade proto-google-common-protos to 1.17.0

---

alts/src/main/java/io/grpc/alts/AuthorizationUtil.java
alts/src/test/java/io/grpc/alts/AuthorizationUtilTest.java

This is to be consistent with Golang. 
If altsContext is missing, we may want to return permission deny in clientAuthorizationCheck

alts: change error status to permission deny on clientAuthorizationCheck failure

---

api/src/main/java/io/grpc/Metadata.java

This was missed in d1078591 and the API has not yet been released.
CC @markb74. This is our standard procedure for new APIs. Shouldn't impact you much. If we make any incompatible changes we will fix internal references. Only risk is for unsubmitted CLs, but we aren't planning on any changes soon.

api: Add ExperimentalApi to Metadata.BinaryStreamMarshaller

---

core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
netty/src/main/java/io/grpc/netty/InternalProtocolNegotiators.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
netty/src/test/java/io/grpc/netty/NettyChannelBuilderTest.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
netty/src/test/java/io/grpc/netty/NettyTestUtil.java
netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java

This PR is to add one more Executor parameter when creating the SslContext.
In Netty, we already have this implementation for passing Executor when creating SslContext: https://github.com/netty/netty/pull/8847. This extra Executor is used to take some time-consuming tasks when doing SSL handshake. However, in current gRPC implementation, we are not using this API. 
In this PR, the relevant changes are:
- get the executorPool from ChannelBuilder or ServerBuilder
- pass the executorPool all the way down to ClientTlsHandler
- fill executorPool in when creating SslHandler

Add Executor When Creating SslContext

---

core/src/main/java/io/grpc/internal/RetriableStream.java
cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java

This supports releasing a new version of GuardedBy which finds more mistakes than it used to.

Add suppressions for GuardedBy violations

---

core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/JsonUtil.java
core/src/main/java/io/grpc/internal/ServiceConfigUtil.java

This should be functionally equivalent. More can be done, but wanted all the
changes to be "obvious" when reading them.
-----
I expect to have a followup where I inline the one-line methods into their callers, which should greatly reduce the size of ServiceConfigUtil. We can also move methods only used one place to their consumer. I think then we'd be left with just a handful of methods left, which is fine.

core: Simplify ServiceConfigUtil via utility methods

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/CdsLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

Incorporating comment https://github.com/grpc/grpc-java/pull/6504#discussion_r363463413. Currently there is no cross-language resolver sending CDS config so there is no impact of the change.

xds: rename experimental_cds policy name to cds_experimental

---

.travis.yml
COMPILING.md
build.gradle
buildscripts/kokoro/android.sh
buildscripts/kokoro/gae-interop.sh
buildscripts/kokoro/linux_artifacts.sh
buildscripts/kokoro/unix.sh
buildscripts/kokoro/windows32.bat
buildscripts/kokoro/windows64.bat
cronet/build.gradle
cronet/settings.gradle
cronet/src/main/java/io/grpc/cronet/CronetClientStream.java
cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java
settings.gradle

~~This is a draft as the CI still needs to be adjusted and at will cause merge conflicts with #6130. I'm sending this out now so that it is more clear what #6131 permits. Note that this includes #6131, so much of it is noise; just look at the last commit.~~

Add Cronet to main build

---

COMPILING.md

#6132 includes `cronet` into grpc-java's main build by default, which requires Android SDK. It would be good to add some instructions for installing Android SDK.

doc: add instruction for installing Android SDK

---

grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/main/proto/grpc/lb/v1/load_balancer.proto
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

FYI, the [proto](https://github.com/grpc/grpc-proto/blob/master/grpc/lb/v1/load_balancer.proto) is not updated yet.

grpclb: support explicit fallback from LB

---

build.gradle

If compiling `grpc-cronet` with Java 9+, unit tests fail with `java.lang.NoClassDefFoundError: android/content/pm/PackageManager$NameNotFoundException`. Upgrading to Robolectric 4 seems to fix this.
/cc @sanjaypujare

Upgrade robolectric version to 4.3.1

---

core/src/main/java/io/grpc/util/GracefulSwitchLoadBalancer.java
core/src/test/java/io/grpc/util/GracefulSwitchLoadBalancerTest.java

It makes more sense to go to TRANSIENT_FAILURE immediately than NOOP if GracefulSwitchLoadBalancer receives resolution error before switching to any delegate.
In most natural usecase, the `gracefulSwitchLb` is a child balancer of some `parentLb`, and the `gracefulSwitchLb` switches to a new `delegateLb` when `parentLb.handleResolvedAddressGroup()`. If the  `parentLb` receives a resolution error before receiving any resolved addresses, it should go to  TRANSIENT_FAILURE. In this case, it will be more convenient if the initial  `gracefulSwitchLb` can go to TRANSIENT_FAILURE directly.

core/util: Go to TRANSIENT_FAILURE on initial resolution error for GracefulSwitchLoadBalancer

---

examples/gradle/wrapper/gradle-wrapper.properties

The rest of the build went to Gradle 5.6.2 in 3c3a823a, but that commit
failed to update the examples. This brings the two back in sync.

examples: Bump Gradle to 5.6.2

---

alts/build.gradle

Previously `grpc-core` pulls in `opencensus-api` and we prefer that over google-oauth2's. After #6577, `grpc-core` no longer depends on `opencensus-api`, this exclusion should be removed.
Note: `interop-testing` depends on both `grpc-census` and `grpc-alts`, both of which will pull in `opencensus-api` dependency. Currently they depends on the same version of `opencensus-api`, but we should probably fix it.

alts: do not exclude opencensus-api from google-oauth2's transitive dependencies

---

netty/src/main/java/io/grpc/netty/NettyServer.java
netty/src/test/java/io/grpc/netty/NettyServerTest.java

A race condition was reported by user in #6601:
`ServerImpl.start()` calls `NettyServer.start()` while holding `ServerImpl.lock`. `NettyServer.start()` awaits a submitted runnable in eventloop. However, this pending runnable may never be executed because the eventloop might be executing some other task, like `ServerListenerImpl.transportCreated()`, that is trying to acquire `ServerImpl.lock` causing a deadlock.
This PR resolves the particular issue reported in #6601 for server with a single port, but `NettyServer` (https://github.com/grpc/grpc-java/blob/v1.26.0/netty/src/main/java/io/grpc/netty/NettyServer.java#L251) and `ServerImpl` (https://github.com/grpc/grpc-java/blob/v1.26.0/core/src/main/java/io/grpc/internal/ServerImpl.java#L184) in general still have the same potential risk of …

netty: fix a race for channelz at server transport creation

---

alts/build.gradle

Previously grpc-core pulls in opencensus-api and we prefer that over google-oauth2's. After #6577, grpc-core no longer depends on opencensus-api, this exclusion should be removed.
Note: interop-testing depends on both grpc-census and grpc-alts, both of which will pull in opencensus-api dependency. Currently they depends on the same version of opencensus-api, but we should probably fix it.
-------------------
Backport of #6607.

alts: do not exclude opencensus-api from google-oauth2's transitive dependencies (1.27.x backport)

---

xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

We use timeout to conclude resource not exist in xDS protocol.
RDS and EDS protocols are quasi-incremental, each response may not include all the requested resources that present on server side. The way to conclude a requested resource not exist is to use a timeout. In Envoy, this timeout is defined as [initial fetch timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/config_source.proto#envoy-api-field-core-configsource-initial-fetch-timeout), which is set up at the time client starts subscribing to some resource and disarmed at the time client receives update for that resource. In gRPC's implementation, we set this timeout to be constant 15 seconds, instead of getting its value from ConfigSource proto message.
Initial fetch timeout was initially considered to be not …

xds: incorporate initial fetch timeout as resource not found for xDS protocol

---

.travis.yml
RELEASING.md
buildscripts/kokoro/unix.sh
examples/example-hostname/BUILD.bazel
examples/example-hostname/README.md
examples/example-hostname/build.gradle
examples/example-hostname/pom.xml
examples/example-hostname/settings.gradle
examples/example-hostname/src/main/java/io/grpc/examples/hostname/HostnameGreeter.java
examples/example-hostname/src/main/java/io/grpc/examples/hostname/HostnameServer.java
examples/example-hostname/src/main/proto/helloworld/helloworld.proto
examples/example-hostname/src/test/java/io/grpc/examples/hostname/HostnameGreeterTest.java
services/BUILD.bazel

This is placed in its own directory since it depends on grpc-services.
This is a backport of #6604
I remembered to fix the version numbers to reference 1.27.0-SNAPSHOT

examples: Add hostname example (v1.27.x backport)

---

examples/gradle/wrapper/gradle-wrapper.properties

The rest of the build went to Gradle 5.6.2 in 3c3a823a, but that commit
failed to update the examples. This brings the two back in sync.
Backport of #6605

examples: Bump Gradle to 5.6.2 (v1.27.x backport)

---

core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java

Caught by lint warning during import. Compiler optimizations may cause issues with older Android versions.

core: change catch blocks for Android <19

---

netty/src/main/java/io/grpc/netty/NettyServer.java
netty/src/test/java/io/grpc/netty/NettyServerTest.java

This is a chery-pick of b8474d61c966f60cc0bad4e5abaca351e90afc9d
A race condition was reported by user in #6601:
`ServerImpl.start()` calls `NettyServer.start()` while holding `ServerImpl.lock`. `NettyServer.start()` awaits a submitted runnable in eventloop. However, this pending runnable may never be executed because the eventloop might be executing some other task, like `ServerListenerImpl.transportCreated()`, that is trying to acquire `ServerImpl.lock` causing a deadlock.
This PR resolves the particular issue reported in #6601 for server with a single port, but `NettyServer` (https://github.com/grpc/grpc-java/blob/v1.26.0/netty/src/main/java/io/grpc/netty/NettyServer.java#L251) and `ServerImpl` (https://github.com/grpc/grpc-java/blob/v1.26.0/core/src/main/java/io/grpc/internal/ServerImp …

netty: fix a race for channelz at server transport creation (backport v1.27.x)

---

xds/src/main/java/io/grpc/xds/XdsClient.java

XDS clients will use a keepalive time of 5 minutes ~~, and a keepalive timeout of 20 seconds~~.
Unfortunately it's not possible to be tested in unit test.

xds: enable keepalive for XDS channel

---

core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory2.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl2.java
core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest2.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest2.java
core/src/test/java/io/grpc/internal/ServiceConfigErrorHandlingTest.java

~1. Allow legacy way to pass service config via attributes~
2. fix AutoConfiguredLBFactory may populate ConfigOrError instead of
actual config.

core: fix bugs in service config error handling

---

examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java
examples/src/main/java/io/grpc/examples/routeguide/RouteGuideClient.java
examples/src/test/java/io/grpc/examples/routeguide/RouteGuideClientTest.java

The target can be provided on the command line to avoid needing to recompile
the example just to change where the server is located. We use a target instead
of addresses as that is the approach we have wanted to encourage for a while
since it allows choosing alternative name resolvers.
We typically encourage injecting Channels, not ManagedChannels, which has the
added benefit of simplifying the example. Less indirection makes for a better
example.
Swapping to target string could be done to examples-tls and examples-gauth as
well, but it would be much more invasive to the tls example and the gauth
example would need proper testing after the change.
------
These are things that I've wanted for a while, but now the target change is
necessary for the xds example and the rest sort of falls out …

examples: Allow passing target and simplify lifecycle

---

interop-testing/src/main/java/io/grpc/testing/integration/XdsTestClient.java
interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java

Hostname is more informative for tests running on GCP, and unlike server ID, doesn't require the client to have knowledge about the server's command-line arguments

interop-testing: use server hostname instead of id for xds test

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/LookasideLb.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java

`CdsLoadBalancer` was using `ATTR_LOAD_BALANCING_CONFIG` attributes to get service config. However, it did not work after 751faa6faa3fbccf46af74c6597218438f39c2ca and e9882ec78db581106f709ab5130bfe30af660e79 were merge (The cause should be fixed in #6648).

xds: use resolvedAddresses.getLoadBalancingPolicyConfig() to get LB config

---

examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlServer.java
stub/src/main/java/io/grpc/stub/CallStreamObserver.java

Fixes #6552.
Apart the class-level comment, there are a few unclear places in the documentation to the methods which I don't know how to improve--please make your suggestions.
1. `... without requiring excessive buffering internally ...` in `isReady()` suggests that there may be some internal buffer, in-process, which may have spare space, and then `isReady()` can return true. However, the documentation `setOnReadyHandler()` has phrase `when peer is ready to receive more messages` which doesn't consider the above option.
2. Phrase `On server-side it may only be called during the initial call to the application, before the service returns its {@code StreamObserver}.` -- cannot make sense of this phrase, because service implementations don't normally return `StreamObserver` instances. Does …

Clarify CallStreamObserver's Javadoc

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/EdsLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/LookasideLb.java
xds/src/main/resources/META-INF/services/io.grpc.LoadBalancerProvider
xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/LookasideLbTest.java

The `EdsLoadBalancerProvider` provides `LookasideLb` (Will rename `LookasideLb` to `EdsLoadBalancer` in future, but kept the name now to show better diff) with no-op callbacks for fallback.
- `CdsLoadBalancer` will load `EdsLoadBalancerProvider/LookasideLb` directly skipping fallback.
- The EDS-only flow is unchanged, still loading `XdsLoadBalancerProvider/XdsLoadBalancer2`, keeping current fallback behavior and producing horrible error message when both the primary and fallback policy fail.

xds: add EdsLoadBalancerProvider to short-circuit  CDS to EDS flow skipping fallback

---

java_grpc_library.bzl

These methods were used to migrate the Java toolchains to use toolchain
resolution. Now that the migration is complete, the toolchain providers
can be used directly.
------
Export of cl/292224245
~@cushon, you'll get to make a comment to make the CLA bot happy.~ Apparently not. CC @cushon

java_grpc_library: Inline find_java_toolchain and find_java_runtime_toolchain

---

build.gradle
examples/example-alts/build.gradle
repositories.bzl

update auth libraries

---

xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
xds/src/test/java/io/grpc/xds/XdsClientTestHelper.java

Implements the precise logic for choosing the virtual host in `RouteConfiguration` of RDS responses. Specifically, fixes logic for domain search order. Minor fix for checking `match` field in `RouteConfiguration`. Please see _RouteConfiguration Proto_ section in gRPC Client xDS API Flow design doc for specification.

xds: precise logic for selecting the virtual host in RDS responses

---

alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java
core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/GrpcAttributes.java
core/src/main/java/io/grpc/internal/JndiResourceResolverFactory.java
core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/JndiResourceResolverTest.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbConstants.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
xds/src/main/java/io/grpc/xds/FallbackLb.java

In this take:
- `DnsNameResolver` returns balancer addresses as a `GrpcAttributes.ATTR_LB_ADDRS` attribute in `ResolutionResult`.
- `AutoConfiguredLoadBalancerFactory` decides LB policy solely based on parsed service config without looking at resolved addresses. Behavior changes:
- If no LB policy is specified in service config, default to `pick_first`, even if there exist balancer addresses.
- If `grpclb` specified but not available and no other specified policies available, it will fail without fallback to `round_robin`.
- `GrpclbLoadBalancer` populates balancer addresses from `ResolvedAddresses`'s attribute (`GrpclbConstants.ATTR_LB_ADDRS`) instead of sieving from addresses.
Next step after this change is to separate logic for querying SRV record in `DnsNameResolver` to a `grpclb` …

core, grpclb: change policy selection strategy for Grpclb policy (take one: eliminate special logic for deciding grpclb policy in core)

---

.travis.yml
RELEASING.md
buildscripts/kokoro/unix.sh
examples/example-xds/README.md
examples/example-xds/build.gradle
examples/example-xds/settings.gradle

~~This depends on #6630, and includes a commit from it.~~

examples: Add XDS client example

---

grpclb/build.gradle
grpclb/src/main/java/io/grpc/grpclb/GrpclbConstants.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
grpclb/src/main/java/io/grpc/grpclb/InternalGrpclbConstantsAccessor.java

grpclb: internal accessor for balancer address related attribute keys

---

grpclb/src/main/java/io/grpc/grpclb/InternalGrpclbConstantsAccessor.java

Patches #6667. Add getters for tests that populate grpclb balancer address related attribute values.

grpclb: expose balancer address related attributes in internal accessor

---

alts/src/main/java/io/grpc/alts/internal/AesGcmAeadCrypter.java
alts/src/test/java/io/grpc/alts/internal/AesGcmAeadCrypterTest.java

Previously the check for Conscrypt would always fail because CONSCRYPT
was guaranteed to be null.

alts: _Actually_ use Conscrypt when available

---

interop-testing/build.gradle

In v1.27.0 release the grpc-interop-testing artifact in maven includes grpc-xds, but grpc-xds is not yet published. It should be removed from the dependency list in maven artifact.

interop-testing: fix bug for xds dependency not published yet

---

interop-testing/build.gradle

This is a cherry-pick of cd35a8153c097adfd3eeb3f1bde89814a32824ec
In v1.27.0 release the grpc-interop-testing artifact in maven includes grpc-xds, but grpc-xds is not yet published. It should be removed from the dependency list in maven artifact.

interop-testing: fix bug for xds dependency not published yet (backport v1.27.x)

---

interop-testing/build.gradle

This fixes a bug introduced in #6675 .
grpc-interop-testing should have added all dependency e.g. enovy that grpc-xds needs.

interop-testing: fix bug of xds test missing transitive dependency

---

interop-testing/build.gradle

This is backport of #6681 (a cherry-pick of 258fe12f0281e96f76d36cda6cbffeb6476e65d7)
This fixes a bug introduced in #6675 .
grpc-interop-testing should have added all dependency e.g. enovy that grpc-xds needs.

interop-testing: fix bug of xds test missing transitive dependency (backport v1.27.x)

---

census/src/main/java/io/grpc/census/CensusTracingModule.java

This PR sets the SpanKinds of Client/Server traces, in order to distinguish them more easily after export.

census: Set SpanKind on Client/Server traces

---

alts/src/main/proto/grpc/gcp/handshaker.proto
grpclb/BUILD.bazel
grpclb/src/main/proto/grpc/lb/v1/load_balancer.proto
repositories.bzl

This noticed that load_balancer.proto had local changes introduced
in #6549. This was not noticed by Bazel because grpclb was not using
the io_grpc_grpc_proto repository. These issues have been fixed.

Sync grpc-proto to 1ff78907

---

core/src/main/java/io/grpc/internal/ServiceConfigUtil.java
core/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java

core: revert stickiness from round robin

---

xds/src/main/java/io/grpc/xds/LoadReportClientImpl.java
xds/src/test/java/io/grpc/xds/LoadReportClientImplTest.java

The LRS implementation was kind of half-baked. We have APIs for adding `LoadStatsStore`s as source of load data (per cluster service) to be reported, but we expect management server to ask load reporting for only one cluster service. This doesn't make sense. 
The assumption for management server to ask load reporting for only one cluster service seems overly strong. It is not consistent with our LRS client's design that it is capable of _reporting loads for multiple services of a cluster_. The reality is that we still will only have at most one service per cluster for now, but management server may ask loads for multiple services even if rest are completely unknown or not used to the client. 
The most correct way is to support reporting loads for multiple services. The actual loads to be …

xds: support reporting loads for more than one cluster services

---

alts/src/main/java/io/grpc/alts/internal/AesGcmAeadCrypter.java
alts/src/test/java/io/grpc/alts/internal/AesGcmAeadCrypterTest.java

Previously the check for Conscrypt would always fail because CONSCRYPT
was guaranteed to be null.
-----------
This is a backport of #6672

alts: _Actually_ use Conscrypt when available (v1.26.x backport)

---

alts/src/main/java/io/grpc/alts/internal/AesGcmAeadCrypter.java
alts/src/test/java/io/grpc/alts/internal/AesGcmAeadCrypterTest.java

Previously the check for Conscrypt would always fail because CONSCRYPT
was guaranteed to be null.
-----
This is a backport of #6672

alts: _Actually_ use Conscrypt when available (v1.27.x backport)

---

buildscripts/kokoro/xds.sh

Mistakenly left this pointing to my fork in https://github.com/grpc/grpc-java/pull/6662

buildscripts: fix url of grpc core repo

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java

Previously when CdsConfig is changed, the old cluster watcher is canceled immediately even it's in graceful switch period, so the old cluster balancer won't receive any new updates. This behavior is not as good/clean as cancelling the old watch only once the old cluster balancer is shutdown.

xds: have cluster balancer cancel cluster watcher only during shutdown

---

xds/src/main/java/io/grpc/xds/EdsLoadBalancer.java

Previously when eds service name is changed, the old endpoint watcher is canceled immediately even it's in graceful switch period, so the old ClusterEndpointBalancer won't receive any new updates. This behavior is not as good/clean as cancelling the old watch only once the old ClusterEndpointBalancer is shutdown.

xds: have ClusterEndpointBalancer cancel endpoint watcher only during shutdown

---

interop-testing/src/main/proto/grpc/testing/messages.proto

The `grpclb_route_type` field already exists in the core and Go repos.

interop-testing: sync SimpleResponse definition with core and go

---

census/src/main/java/io/grpc/census/CensusTracingModule.java

This reverts commit 60bc74620fc88b321a46791241326939de70ed20.
This breaks internal tests. In the internal opencensus implementation, Span without kind needs to be in the format of "[Recv|Sent].Namespace.Service.Method" and Span with kind needs to be in the format of "Namespace.Service/Method".

Revert "census: Set SpanKind on Client/Server traces (#6680)"

---

grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

grpclb: handles empty address from LB

---

grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

grpclb: handles empty address from LB (backport of #6734 to 1.27.x)

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/EdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/LoadReportClient.java
xds/src/main/java/io/grpc/xds/XdsClient.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/main/java/io/grpc/xds/XdsLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/EdsLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/LoadReportClientTest.java
xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
xds/src/test/java/io/grpc/xds/XdsClientTest.java
xds/src/test/java/io/grpc/xds/XdsLoadBalancerProviderTest.java

Major changes in this PR:
1. Added `cluster` field for cluster name in EDS LB config (i.e., `XdsConfig`). CDS policy will set it to the cluster name it receives from CDS responses. 
- Currently, `cluster` is optional since the resolver in prod tests does not have it. So for EDS-only, it will be set to the hostname (including port) for creating the gRPC channel.
2. XdsClient will give `edsServiceName` exactly as it receives in CDS responses to CDS policy. That is, `edsServiceName` in `ClusterUpdate` can be `null`. LRS loads are grouped by each cluster:edsService, their values should match what is given in CDS responses exactly.
3. Updated LRS protocol. The `Node` sent in LRS requests use a special metadata `PROXYLESS_CLIENT_HOSTNAME` with value being the hostname (including port) for …

xds: update LRS protocol and fix usage of cluster name in ClusterStats

---

grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

grpclb: add description to lb sends no backends status (backport of #6751 to 1.27.x)

---

xds/build.gradle
xds/src/main/java/io/grpc/xds/Bootstrapper.java
xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/EdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/LoadStatsStore.java
xds/src/main/java/io/grpc/xds/OrcaMetricReportingServerInterceptor.java
xds/src/main/java/io/grpc/xds/OrcaOobUtil.java
xds/src/main/java/io/grpc/xds/OrcaPerRequestUtil.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/main/java/io/grpc/xds/XdsNameResolverProvider.java
xds/src/main/java/io/grpc/xds/internal/package-info.java
xds/src/main/java/io/grpc/xds/package-info.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

- Improve package-info.java and make minor changes to other javadoc.
- Make Orca API non-public for the moment.
- Make grpc-xds publishable.

Improve grpc-xds javadoc and make it publishable

---

xds/src/main/java/io/grpc/xds/FallbackLb.java
xds/src/test/java/io/grpc/xds/FallbackLbTest.java

#6637 changed to put grpclb balancer addresses in `ResolutionResult.attributes` instead of in `addresses`. We have also migrated the internal resolver to do the same. So LB policies will never receive grpclb balancer addresses in `ResolutionResult.getAddresses()`.

xds: clean up xDS fallback balancer filtering out grpclb balancer addresses

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/main/java/io/grpc/okhttp/OutboundFlowController.java
okhttp/src/main/java/io/grpc/okhttp/Utils.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

Addressing #6685 
Specifically, this addresses bugs that occur when the `OkHttpChannelBuilder.flowControlWindow(int)` setting is increased from its default value.
Two changes:
1. On starting a connection, ensure the value of `OkHttpChannelBuilder.flowControlWindow(int)` is sent via Settings.INITIAL_WINDOW_SIZE. Also send a WINDOW_UPDATE after Settings to update the connection-level window.
2. Always initialize the `OutboundFlowController` with an initialWindowSize of 65335 bytes per the [http2 spec](https://http2.github.io/http2-spec/#InitialWindowSize) instead of using the inbound window size.

okhttp: fix incorrect connection-level flow control handling at beginning of connection

---

api/src/main/java/io/grpc/InternalKnownTransport.java
api/src/main/java/io/grpc/MethodDescriptor.java
netty/src/main/java/io/grpc/netty/NettyClientStream.java

Continue to use enum `InternalKnownTransport` and extend it for ABI backward compatibility (hopefully).

api,netty: fix MethodDescriptor and InternalKnownTransport for netty-shaded

---

api/src/main/java/io/grpc/InternalKnownTransport.java
api/src/main/java/io/grpc/MethodDescriptor.java
netty/src/main/java/io/grpc/netty/NettyClientStream.java

cherry-pick of 5677a0b7237ca9d28768ee84f04f3e2a03f23fbb #6774 
Resolves #6765

api,netty: fix MethodDescriptor and InternalKnownTransport for netty-shaded (backport v1.28.x)

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/main/java/io/grpc/okhttp/OutboundFlowController.java
okhttp/src/main/java/io/grpc/okhttp/Utils.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

Specifically, this addresses bugs that occur when the `OkHttpChannelBuilder.flowControlWindow(int)` setting is increased from its default value.
Two changes:
1. On starting a connection, ensure the value of `OkHttpChannelBuilder.flowControlWindow(int)` is sent via Settings.INITIAL_WINDOW_SIZE. Also send a WINDOW_UPDATE after Settings to update the connection-level window.
2. Always initialize the `OutboundFlowController` with an initialWindowSize of 65335 bytes per the [http2 spec](https://http2.github.io/http2-spec/#InitialWindowSize) instead of using the inbound window size.
Fixes #6685
---------------
Backport of #6742.

okhttp: fix incorrect connection-level flow control handling at beginning of connection (v1.28.x backport)

---

core/src/main/java/io/grpc/internal/GrpcUtil.java
xds/src/main/java/io/grpc/xds/Bootstrapper.java
xds/src/test/java/io/grpc/xds/BootstrapperTest.java

Add "envoy.lb.does_not_support_overprovisioning" to xDS node identifier client features. Set the new user_agent_name and user_agent_version fields for build version.
Backport of #6766.

xds: set disable overprovisioning client feature and user agent in node identifier (v1.28.x backport)

---

bom/build.gradle

Backport of #6783 
cherry-pick of 9cb277d7af229546f68c4d2af0c322557d0cf2a0

bom: publish grpc-xds to bom (backport v1.28.x)

---

core/src/main/java/io/grpc/util/GracefulSwitchLoadBalancer.java

Fixes #6755
```
> Task :grpc-core:javadoc
core/src/main/java/io/grpc/util/GracefulSwitchLoadBalancer.java:43: warning - Tag @link: can't find switchTo(Factory) in io.grpc.util.GracefulSwitchLoadBalancer
1 warning
```

core: fix javadoc warnings

---

alts/build.gradle
gae-interop-testing/gae-jdk8/build.gradle
interop-testing/build.gradle
interop-testing/src/test/java/io/grpc/ChannelAndServerBuilderTest.java
xds/build.gradle

This reverts commit c5f48b8e384ca1ad91b67886f8cbff27c9bcfd8d.
Revert because caused a regression in the ALTS tests. https://source.cloud.google.com/results/invocations/691d9965-fea1-487d-b606-352a5234039e/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_toprod/log
2020-03-01 20:02:12,491 Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/SystemUtils
at io.grpc.alts.CheckGcpEnvironment.isRunningOnGcp(CheckGcpEnvironment.java:69)
at io.grpc.alts.CheckGcpEnvironment.isOnGcp(CheckGcpEnvironment.java:44)
at io.grpc.alts.ComputeEngineChannelBuilder.<init>(ComputeEngineChannelBuilder.java:62)
at io.grpc.alts.ComputeEngineChannelBuilder.forTarget(ComputeEngineChannelBuilder.java:72)
at io.grpc.alts.ComputeEngineChannelBuilder.forAddress(ComputeEngineChanne …

Revert "all: let interop test use shaded dependency correctly (#6780)"

---

alts/BUILD.bazel
alts/build.gradle
alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java
alts/src/test/java/io/grpc/alts/internal/GoogleDefaultProtocolNegotiatorTest.java
core/src/main/java/io/grpc/internal/GrpcAttributes.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbConstants.java
grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

Final cleanup following #6637 and #6723 to move all Grpclb related attributes out of grpc-core and into grpc-grpclb. Now grpc-alts will have a compile dependency on grpc-grpclb instead of runtimeOnly.

core, grpclb: clean up grpclb specific attributes in core

---

core/src/main/java/io/grpc/inprocess/InProcessTransport.java
core/src/main/java/io/grpc/inprocess/InternalInProcess.java
core/src/test/java/io/grpc/inprocess/StandaloneInProcessTransportTest.java

This allows an InProcessTransport instance to be created via a new internal accessor class InternalInProcess. We effectively just expose a method to create an InProcessTransport with a existing ServerListener instance.
This will be used for in-process channels to an under-development on-device server.

 Enable use of InProcessTransport outside of InProcessServer.

---

grpclb/src/main/java/io/grpc/grpclb/GrpclbConfig.java
grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java

These are dangling code in Grpclb's tests. Grpclb's implementation does not use `ATTR_LOAD_BALANCING_CONFIG` attributes any more. Leaving this in its test does not make any sense.
TODO: eliminate `ATTR_LOAD_BALANCING_CONFIG` usage in xds's `FallbackLb`. It turns out not to be a simple cleanup there, some logic needs to be rewritten. @dapengzhang0

grpclb: clean up usage of raw load balancing config attributes in tests

---

android/build.gradle
android/settings.gradle
android/src/test/java/io/grpc/android/AndroidChannelBuilderTest.java
build.gradle
buildscripts/kokoro/linux_artifacts.sh
settings.gradle

For #6775. Basically a mirror of #6132, which was for grpc-cronet. After this change, dependencies in grpc-android is kept in sync with main build.
This change also migrated deprecated Robolectric methods to androidx.test methods. See [Robolectric migration guide](http://robolectric.org/migrating/#migrating-to-40).
> Robolectric 4.0 includes initial support for androidx.test APIs. We strongly recommend adding androidx.test:core:1.0.0 as a test dependency and using those APIs whenever possible rather than using Robolectric-specific APIs.

android: add grpc-android into main build

---

benchmarks/build.gradle
settings.gradle

- Bump jmh plugin version to 0.5.0, which is compatible with current Gradle version.
- Removed unnecessary workaround for jmh known issues in previous version.
- Fix dependencies to avoid getting duplicated class error when running jmhJar.
Fixes #6762.

benchmark: clean up jmh plugin configurations

---

alts/build.gradle
gae-interop-testing/gae-jdk8/build.gradle
interop-testing/build.gradle
interop-testing/src/test/java/io/grpc/ChannelAndServerBuilderTest.java
xds/build.gradle

This include two commits: 
- first rolls forward #6791 
- then fixes the issue of missing transitive dependency for the shadow configuration.

all: let interop test use shaded dependency correctly take 2

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

The condition "effectiveServiceConfig != validServiceConfig" should
have been deleted in commit 2162ad043677e3cbaac969b96fd4faa05448874b.
The condition was there before that commit because
NAME_RESOLVER_SERVICE_CONFIG was already in "attrs", thus it needed to
be re-added only if "effectiveServiceConfig" differs from the original
"validServiceConfig".
In contrast, ATTR_HEALTH_CHECKING_CONFIG is not in the original
"attrs" and always needs to be added.

core: fix a bug in health check config propgation.

---

interop-testing/build.gradle

Currently the classpath for all startscripts in interop-testing includes alpnagent and grpc-xds, even if a lot of startscripts don't need them. Made a change to only include alpnagent or grpc-xds when a startscript really needs it.

interop-testing: set the right classpath for startscripts

---

xds/src/main/java/io/grpc/xds/XdsClient.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

Fixes usage of target hostname:port in xDS plugin.
The target hostname:port used to construct gRPC channel should be treated opaquely. XdsNameResolver should not try to split it and should use it opaquely for sending LDS requests. In received RouteConfiguration messages, do not stripe off port (if any) for finding the virtual host with domain name matching the requested LDS resource name.
-------------------------------
Backport of #6767.
_Manual change:_
- Since the original change [ef44795594a46c7c2ab58ca84fda02386a95f7a2](https://github.com/grpc/grpc-java/commit/ef44795594a46c7c2ab58ca84fda02386a95f7a2) was committed after #6705, which cleaned up usages of internal attribute NAME_RESOLVER_SERVICE_CONFIG in `XdsNameResolver`. This backport commit needs to revert the change of removing …

xds: treat target server authority opaquely for resolving cluster name (v1.28.x backport) (#6767) 

---

api/src/main/java/io/grpc/MethodDescriptor.java

The server does not _have_ to wait until half close in CLIENT_STREAMING, and
commonly wouldn't in error cases. {client,server}SendsOneMessage were way
over-specifying the behavior and included unnecessary and incorrect words like
"immediately." Those methods shouldn't be the defining the behavior in that
much precision anyway; that would be the job of the individual enum values, if
anything.

api: Fix MethodType documentation overspecification

---

buildscripts/kokoro/xds.cfg
buildscripts/kokoro/xds.sh

Cherry-pick of https://github.com/grpc/grpc-java/pull/6816

buildscripts: update xds test server arg (v1.28.x backport)

---

buildscripts/kokoro/xds.sh
buildscripts/xds_logging.properties
interop-testing/src/main/java/io/grpc/testing/integration/XdsTestClient.java

Cherry-pick of https://github.com/grpc/grpc-java/pull/6818

buildscripts,interop-testing: Increase logging for xDS tests (v1.28.x backport)

---

buildscripts/kokoro/xds.sh

Analogous to https://github.com/grpc/grpc-go/pull/3456 (some discussion already there). This will be needed to keep the `v1.28.x` branch xds test stable.

buildscripts: checkout matching grpc/grpc branch for xds test

---

buildscripts/kokoro/xds.sh

Cherry-pick of https://github.com/grpc/grpc-java/pull/6828

buildscripts: checkout matching grpc/grpc branch for xds test (v1.28.x backport)

---

android/src/main/java/io/grpc/android/AndroidChannelBuilder.java
android/src/test/java/io/grpc/android/AndroidChannelBuilderTest.java

#6773 bumped Android SDK version to 28, in which some constants in `ConnectivityManager` have been deprecated such as [`ConnectivityManager. CONNECTIVITY_ACTION`](https://developer.android.com/reference/android/net/ConnectivityManager#CONNECTIVITY_ACTION), [`ConnectivityManager. TYPE_WIFI`](https://developer.android.com/reference/android/net/ConnectivityManager#TYPE_WIFI), [`ConnectivityManager. TYPE_MOBILE`](https://developer.android.com/reference/android/net/ConnectivityManager#TYPE_MOBILE), etc. In grpc-android, they are used for supporting legacy SDK connectivity state monitoring (and its unit tests). They work as intended for legacy SDK versions. So we suppress those warnings for the target SDK version 28.

android: suppress warnings for deprecated constants in ConnectivityManager

---

buildscripts/kokoro/android-interop.sh
buildscripts/kokoro/android.sh

1. Fix the [breakage](https://source.cloud.google.com/results/invocations/3376bdb6-7bde-4d88-88fe-d3cb6f58a0a6/targets/grpc%2Fjava%2Fmaster%2Fbranch%2Fandroid-interop/log) in `android-interop-testing` for apk path change.
2. Building `android-interop-testing` does not require gRPC in maven local.
3. Slightly modified `android.sh` to reflect building `grpc-cronet`, `grpc-android` and `grpc-android-interop-testing` does not require gRPC in maven local.

buildscripts: clean up android related scripts

---

android-interop-testing/src/main/AndroidManifest.xml

Mistakenly deleted in #6829 due to warning when the refactoring was WIP. This should not be changed as this is how minSdkVersion specified for non-gradle builds.

android-interop-testing: set minSdkVersion to 14 in manifest

---

core/src/main/java/io/grpc/internal/ManagedChannelOrphanWrapper.java

Data race was detected internally when
`ManagedChannelOrphanWrapper.shutdown()` was called concurrently:
```
WARNING: ThreadSanitizer: data race (pid=5009)
Write of size 8 at 0x7fd2f7f37530 by thread T49:
#0 java.lang.ref.Reference.clear()V Reference.java:265
#1 io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.clearInternal()V ManagedChannelOrphanWrapper.java:118
#2 io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.clear()V ManagedChannelOrphanWrapper.java:110
#3 io.grpc.internal.ManagedChannelOrphanWrapper.shutdown()Lio/grpc/ManagedChannel; ManagedChannelOrphanWrapper.java:58
(stacktrace redacted)
Previous write of size 8 at 0x7fd2f7f37530 by thread T45 (mutexes: write M267260296638793720, write M267541771615505864, write M267823246592216728, write …
```

core: prevent data race in ManagedChannelOrphanWrapper

---

xds/src/test/java/io/grpc/xds/XdsRoutingLoadBalancerTest.java

This is required inside google for all tests.

xds: annotate XdsRoutingLoadBalancerTest with RunWith

---

buildscripts/kokoro/xds.cfg
buildscripts/kokoro/xds.sh

Set up in the test runner script by https://github.com/grpc/grpc/pull/22444

buildscripts: allow per-xds test case artifacts

---

buildscripts/kokoro/xds.cfg
buildscripts/kokoro/xds.sh

Cherry-pick of https://github.com/grpc/grpc-java/pull/6857

buildscripts: allow per-xds test case artifacts (v1.28.x backport)

---

core/src/main/java/io/grpc/internal/ServerImpl.java
core/src/test/java/io/grpc/internal/ServerImplTest.java

Previously AbstractServerStream would throw an exception which would kill the
RPC with a RST_STREAM. Now the server actually responds with a clean error
message and avoids spamming the logs.
```
WARNING: Exception in onHeadersRead()
java.lang.IllegalStateException
at com.google.common.base.Preconditions.checkState(Preconditions.java:495)
at io.grpc.internal.AbstractStream$TransportState.onStreamAllocated(AbstractStream.java:232)
at io.grpc.internal.AbstractServerStream$TransportState.onStreamAllocated(AbstractServerStream.java:224)
at io.grpc.netty.NettyServerHandler.onHeadersRead(NettyServerHandler.java:451)
at io.grpc.netty.NettyServerHandler.access$900(NettyServerHandler.java:101)
at io.grpc.netty.NettyServerHandler$FrameListener.onHeadersRead(NettyServerHandler.java:807)
at …
```

core: Add missing setListener if decompressor is unknown

---

NOTICE.txt
build.gradle
xds/build.gradle
xds/third_party/protoc-gen-validate/LICENSE
xds/third_party/protoc-gen-validate/NOTICE
xds/third_party/protoc-gen-validate/import.sh
xds/third_party/protoc-gen-validate/src/main/proto/validate/validate.proto

PGV is adding new fields (`well_known_regex` and `strict`) to proto and some of our new features require the most current envoy API which in turn requires the new fields in latest PGV proto (https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/core/base.proto#L251), but they are not available in the latest PGV maven release.

xds: rollback PGV dependency from using maven artifact to importing proto source

---

core/src/test/java/io/grpc/internal/AbstractTransportTest.java
netty/src/main/java/io/grpc/netty/NettyServer.java

netty: prevent interruption during bind from leaking channel

---

android-interop-testing/build.gradle
android-interop-testing/src/main/java/io/grpc/android/integrationtest/InteropTask.java

Resolves #6866. 
- Suppressed protobuf-javalite's redundant cast warning by adding `"-Xlint:-cast"` compiler argument.
- Suppressed errorprone `UnnecessaryAnonymousClass` warning for reused source code in `grpc-interop-testing`.
- Suppressed "throw in finally" warning. (I am confused by the output of that method, so suppressed the warning instead of trying to rewrite the logic).

android-interop-testing: resolve build warnings

---

api/src/main/java/io/grpc/ServerInterceptors.java

useInputStreamMessages ensures that the InputStream supports marking by wrapping the stream in a BufferedInputStream if markSupported() returns false. This change uses a new subclass of BufferedInputStream that also implements KnownLength, when the original stream also implements KnownLength.

core: preserve KnownLength when wrapping InputStream

---

api/src/main/java/io/grpc/ServerInterceptors.java

useMarshalledMessages works by duplicating a ServerServiceDefinition while replacing just the marshallers. It currently does not copy over the SchemaDescriptors, which breaks at least the ProtoReflectionService.

core: copy the SchemaDescriptor when rebuilding descriptor

---

xds/src/main/java/io/grpc/xds/LocalityStore.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/XdsClientImplTest.java

Changes in processing EDS responses:
- Localities without weight or with weight of 0 are ignored (as gRPC always enables [locality weighted load balancing](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/locality_weight)).
- Allow `LocalityLbEndpoints` to contain 0 `LbEndpoints` (relaxed restriction, see https://github.com/grpc/proposal/pull/173/files).
- Validate priority continuity for localities in each cluster, should NACK the response if priority values are skipping.

xds: filter EDS localities with clarified specifications

---

xds/src/main/java/io/grpc/xds/LocalityStore.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/XdsClientImplTest.java

Fix logic of filtering localites in EDS responses:
- Each LocalityLbEndpoints message is allowed to contain 0 LbEndpoints. 
- LocalityLbEndpoints without or with 0 weight are ignored. 
- NACK responses with sparse locality priorities.
----------
Backport of #6874

xds: filter EDS localities with clarified specifications (v1.28.x backport)

---

benchmarks/src/jmh/java/io/grpc/benchmarks/netty/AbstractBenchmark.java

note: for netty server, it requires to have all or nothing for channelType, boss/worker eventloop group settings.

benchmarks: fix missing configuration for netty server

---

xds/build.gradle

This resolves the problem described in https://github.com/grpc/grpc-java/pull/6876

xds: exclude 3 transitive deps from opencensus_proto to use our own

---

xds/src/test/java/io/grpc/xds/XdsClientImplTest.java

Patches #6874. Adding unit test to cover the change.

xds: patch unit tests to cover changes for locality filtering

---

xds/src/test/java/io/grpc/xds/XdsClientImplTest.java

Add unit test that covers handling EDS responses containing: locality with 0 endpoint, locality with 0 weight.
--------------
Backport of #6881

xds: patch unit tests for changes in locality filtering (backport v1.28.x)

---

all/build.gradle
okhttp/build.gradle
testing/build.gradle

The sourceSets.main.output.collect should probably be improved at some point to
improve loading performance, but this is technically better than what we had
before so let's call it a win and move on.
-----
This is in preparation for xds which has a lot of exclusions.

all: Move jacocoTestReport exclusions to individual projects

---

interop-testing/build.gradle
interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java

This enables use grpc health checks on GCP.

interop-testing: add health service to XdsTestServer

---

api/src/main/java/io/grpc/ManagedChannelBuilder.java

Updates the `ManagedChannelBuilder#nameResolverFactory()`'s javadocs to refer to the new `NameResolverRegistry` instead of the deprecated `NameResolverProvider#providers()` method.
This is also closer to the truth for the default implementations:
https://github.com/grpc/grpc-java/blob/84dd812db86cbfa77b0dda7839ae0ea876135057/core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java#L251-L255

api: Fix javadoc reference to deprecated method

---

buildscripts/kokoro/xds.sh
xds/src/main/java/io/grpc/xds/XdsExperimentalNameResolverProvider.java
xds/src/main/java/io/grpc/xds/XdsNameResolverProvider.java
xds/src/main/resources/META-INF/services/io.grpc.NameResolverProvider
xds/src/test/java/io/grpc/xds/XdsExperimentalNameResolverProviderTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverProviderTest.java

Change "xds-experimenal" scheme to "xds" and add a deprecated provider with "xds-experimenal" scheme for keeping interop tests working.

xds: migrating XdsNameResolver to "xds" scheme

---

compiler/src/java_plugin/cpp/java_generator.cpp

INFO: From Compiling external/io_grpc_grpc_java/compiler/src/java_plugin/cpp/java_generator.cpp [for host]:
external/io_grpc_grpc_java/compiler/src/java_plugin/cpp/java_generator.cpp:164:20: warning: unused function 'ShouldGenerateAsLite' [-Wunused-function]
static inline bool ShouldGenerateAsLite(const Descriptor* desc) {
^
1 warning generated.

Remove unused function

---

core/src/main/java/io/grpc/internal/InternalSubchannel.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/InternalSubchannelTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java

A user has been seeing "InternalSubchannel closed transport due to address
change" errors (b/153064566). It is unclear if they are predomenent, but they
are at least adding noise. Since #2562 is still far from being generally
solved, we delay the shutdown a while to side-step the race.

core: Delay transport shutdown during updateAddresses()

---

xds/src/main/java/io/grpc/xds/LocalityStore.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/LocalityStoreTest.java
xds/src/test/java/io/grpc/xds/XdsClientImplTest.java

Previously XdsClient sends an NACK after receiving an EDS response with 0 localities. [Updated gRFC](https://github.com/grpc/proposal/pull/174) considers such a response valid and should not be NACK. It's the LB policy's job to react (i.e., goes into TRANSIENT_FAILURE) regarding 0 localities.
The update, although contains 0 localities, should be propagated to downstream LB policies as much as possible (to the one that indeed requires endpoints/localities). Handling it too early leaves downstream policies in a half-baked state.
Mirrors https://github.com/grpc/grpc/pull/22612.

xds: handle EDS update with no localities

---

netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/WriteQueue.java
netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java

The race between new streams and transport shutdown is #2562, but it is still
far from being generally solved. This reduces the race window of new streams
from (transport selection → stream created on network thread) to (transport
selection → stream enqueued on network thread). Since only a single thread now
needs to do work in the stream creation race window, the window should be
dramatically smaller.
This only reduces GOAWAY races when the server performs a graceful shutdown
(using two GOAWAYs), as that is the only non-racy way on-the-wire to shutdown a
connection in HTTP/2.

netty: Reduce race window size between GOAWAY and new streams

---

alts/src/main/java/io/grpc/alts/internal/AltsHandshakerClient.java
alts/src/main/java/io/grpc/alts/internal/AltsTsiFrameProtector.java
alts/src/main/java/io/grpc/alts/internal/AltsTsiHandshaker.java
alts/src/test/java/io/grpc/alts/internal/AltsHandshakerClientTest.java
alts/src/test/java/io/grpc/alts/internal/AltsTsiFrameProtectorTest.java
alts/src/test/java/io/grpc/alts/internal/FakeTsiHandshaker.java

gRPC Java uses zero copy frame protectors, and hence are capable of handling larger frame size. Frame Size Negotiation support in ALTS, extends send frame size from 16KB to 128KB, and thereby improves performance.
Design Document: go/seal-frame-size-negotiation-alts

Implemented Frame Size Negotiation in ALTS for gRPC Java

---

rls/src/main/java/io/grpc/rls/internal/ChildLbResolvedAddressFactory.java
rls/src/test/java/io/grpc/rls/internal/ChildLbResolvedAddressFactoryTest.java

right now, this PR probably won't make sense. this class will be created in RlsLoadBalancer (it needs to be public). The factory will be passed to the downstream (cache) to create child lb. without this, I need to pass two variables (addresses, attributes) which can confuse reader.

rls: child lb resolved address factory

---

alts/src/main/java/io/grpc/alts/internal/AltsTsiHandshaker.java

In AltsTsiHandshaker.java, we log maximum frame size value. Changing the log level from INFO to FINE.

Change logging level from INFO to FINE.

---

xds/src/main/java/io/grpc/xds/EnvoyProtoData.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

- Allow duplicate route as discussed in design change https://docs.google.com/document/d/1r52-9_I5oso2b-b3BCZ_O5SYR6n7AolhXVpF9yETMxU/edit?disco=AAAAJTxmCz8
- Allow default matcher to be prefix match with either "" or "/".
I used a method `boolean isDefaultRoute()`. An alternative is to normalize the data by converting prefix "/" to "".

xds: allow duplicated route matcher and prefix='/'

---

xds/src/main/java/io/grpc/xds/EnvoyProtoData.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

Backport of #6932
cherry-pick of 3bd141bf184a82a2cc92c98c906141d5b32ee88e

xds: allow duplicated route matcher and prefix='/' (backport to v1.29.x)

---

context/src/main/java/io/grpc/Context.java
context/src/main/java/io/grpc/PersistentHashArrayMappedTrie.java

This PR removes N allocs where N is the number of key-values added to the Context. even when using withValues variants we allocated a PersistentHashArrayMappedTrie for each <K, V> pair.

Avoid extra allocation by directly using Trie.Node in Context

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpProtocolNegotiator.java

This reverts commit eb8e31409ea1bb0db4eb947a5df6aff267ba1f4b and commit 5803dfd9dcca0fba4483fccf724efc1c853a3ada
Will roll forward after fixing the breakage.

okhttp: revert changes for using new APIs to configure TLS in Android

---

netty/src/main/java/io/grpc/netty/NettyServer.java

as @ejona86 pointed out, we don't need to set `SO_BACKLOG` in netty. see https://github.com/grpc/grpc-java/pull/6947#issuecomment-617301450

netty: use netty default SO_BACKLOG

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpProtocolNegotiator.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpProtocolNegotiatorTest.java

Roll-forward of ee8b395f79a1154df602e7add4d4e2828799e5e1
The added unit test doesn't really reveal the issue being fixed, as the breakage happens only on Android. Just leave it for coverage.

okhttp: use new APIs to configure TLS in Android (roll forward #6959)

---

SECURITY.md

See details in https://github.com/google/conscrypt/issues/834.

SECURITY.md: add instruction for disabling Conscrypt's default TrustManager

---

examples/src/main/java/io/grpc/examples/routeguide/RouteGuideClient.java
examples/src/test/java/io/grpc/examples/routeguide/RouteGuideClientTest.java

As indicated in the proto file, "Points are represented as latitude-longitude pairs in the E7 representation".
@srini100

RouteGuideClient example: use E7 format for latitude & longitude

---

buildscripts/kokoro/xds.sh

Cherry pick of https://github.com/grpc/grpc-java/pull/6889. Speeds up runs by ~30%, saving 20 minutes of test time.

buildscripts: use xds-test-server image (v1.28.x backport)

---

buildscripts/kokoro/xds.sh

Cherry pick of https://github.com/grpc/grpc-java/pull/6889. Speeds up runs by ~30%, saving 20 minutes of test time.

buildscripts: use xds-test-server image (v1.29.x backport)

---

repositories.bzl

This is a moral backport of
https://github.com/grpc/grpc-java/commit/a4299eb6bed3c2f2497f583d0c4620c9f31ec455

bazel: Use https to download from Maven Central (backport 1.20.x)

---

build.gradle
examples/android/clientcache/app/build.gradle
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/strictmode/app/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-hostname/build.gradle
examples/example-hostname/pom.xml
examples/example-jwt-auth/build.gradle
examples/example-jwt-auth/pom.xml
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/pom.xml
repositories.bzl
services/BUILD.bazel
stub/BUILD.bazel

javax.annotation-api is licensed CDDL, which was not noticed when it was
introduced. Tomcat provides an Apache 2 version of the same annotation. Note
that this annotation is only used when compiling with Java 9+.
Unfortunately this may cause classpath collisions since there are _many_ copies
of this annotation on Maven Central; we wanted one canonical source and
javax.annotation-api seemed like that source. We hope this won't impact many
users since we have always suggested using it only for compilation. But it will
probably impact some users. However, we didn't create this mess, this seems to
be "standard practice" for J2EE, which this annotation is now part of, so we're
just impacted by it.
Fixes #6833
----
CC @ulfjack

Replace javax.annotation-api with Tomcat's annotations-api

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/EdsLoadBalancer.java
xds/src/main/java/io/grpc/xds/XdsClient.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
xds/src/test/java/io/grpc/xds/XdsClientImplTestForListener.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

Use `onResourceDoesNotExist()` API for notifying resource not found. Previously, it uses `onError()`, which mixes with errors for failures.
LB policies should go into TRANSIENT_FAILURE immediately after being notified with `onResourceDoesNotExist()`, even if its existing resource is working well. However, this is blocked by a TD's bug during resource transition. So currently, we still keep using the existing resource when even if it is removed.

xds: add onResourceDoesNotExist API for resource watchers

---

build.gradle

Previously the resolution strategy was applied on `complie` configuration which is not so accurate and does not suit for java-libary gradle plugin migration.

build.gradle: apply resolution strategy for runtimeClasspath
