grpc/grpc-java

- api/build.gradle
- build.gradle
- census/build.gradle
- core/build.gradle
- protobuf-lite/build.gradle
- protobuf/build.gradle
- testing/build.gradle
Define util function to exclude guava's transitive dependencies jsr305 and animal-sniffer-annotations, and always manually add them as runtimeOnly dependency. error_prone_annotations is an exception: It is also excluded but manually added not as runtimeOnly. It must always compile with guava, otherwise users will see warning spams if guava is in the compile classpath but error_prone_annotations is not.
> all: introduce gradle util functions to manage guava dependency

- all/build.gradle
- alts/build.gradle
- android-interop-testing/build.gradle
- android/build.gradle
- api/build.gradle
- auth/build.gradle
- benchmarks/build.gradle
- census/build.gradle
- compiler/build.gradle
- context/build.gradle
- core/build.gradle
- cronet/build.gradle
- gae-interop-testing/gae-jdk8/build.gradle
- grpclb/build.gradle
- interop-testing/build.gradle
- netty/build.gradle
- netty/shaded/build.gradle
- okhttp/build.gradle
- protobuf-lite/build.gradle
- protobuf/build.gradle
- rls/build.gradle
- services/build.gradle
- stub/build.gradle
- testing-proto/build.gradle
- testing/build.gradle
- xds/build.gradle
- Use gradle configuration `api` for dependencies that are part of grpc public api signatures.
- Replace deprecated gradle configurations `compile`, `testCompile`, `runtime` and `testRuntime`.
- With minimal change in dependencies: If we need dep X and Y to compile our code, and if X transitively depends on Y, then our build would still pass even if we only include X as `compile`/`implementation` dependency for our project. Ideally we should include both X and Y explicitly as `implementation` dependency for our project, but in this PR we don't add the missing Y if it is previously missing. A followup PR will try to add all such missing dependencies by setting 
```gradle
configurations {
compileClasspath.transitive = false
}
```
> all: migrate gradle build to java-library plugin

- examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlClient.java
- examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlServer.java
- services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java
- services/src/test/java/io/grpc/protobuf/services/ProtoReflectionServiceTest.java
- stub/src/main/java/io/grpc/stub/CallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ClientCalls.java
- stub/src/main/java/io/grpc/stub/ClientResponseObserver.java
- stub/src/main/java/io/grpc/stub/ServerCalls.java
- stub/src/test/java/io/grpc/stub/ClientCallsTest.java
- stub/src/test/java/io/grpc/stub/ServerCallsTest.java
The default behavior of requesting initial messages is applied even if disableAutoInboundFlowControl is called. ServerCalls disables all automatic flow control which is much more useful in case the user can't handle incoming messages until some time after the call has started.  This change creates a new StartableListener that has an onStart method that is invoked when the call is started which makes initial requests if necessary.
See #6806
> Add disableAutoRequest method that disables all automatic inbound flow-control requests

- stub/src/main/java/io/grpc/stub/CallStreamObserver.java
this prevents compile error for users extending Client/ServerCallStreamObserver.
> stub: default impl for disableAutoRequestWithInitial(int)

- README.md
We include this dep in our examples, but never mentioned it in the README.
Instead of getting into details about what it's for, the brief comment should
avoid most confusion for existing Java 8 users about why it appears to be
unnecessary.
------
#5950 didn't get the necessary fixes to be merged, and instead of me making those fixes now it seems this approach will be easier for users.
> README.md: Include annotations api dep in code snippets

- api/src/main/java/io/grpc/ClientCall.java
The original javadoc may be misunderstood as "one must call
halfClose() before calling cancel()".
> core/doc: clarify when ClientCall.cancel() can be called.

- xds/src/main/java/io/grpc/xds/XdsClientImpl.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
Rename according to the design doc.
> xds: rename experimental routing flag to GRPC_XDS_EXPERIMENTAL_ROUTING

- all/build.gradle
Use `api` configuration instead of `implementation` for grpc-all to avoid breaking users.
> grpc-all: use api configuration for dependencies

- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
> netty: enable auto flow control tuning by default

- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
If the server fails (e.g.: with an unimplemented status), the test still succeeds.
This change adds assertions to check the status code as well as the expected number of responses.
> interop-testing: adds assertions to empty_stream test case.

- context/src/main/java/io/grpc/Context.java
- Motivated Issue : #7024 
- Context.key(name) is the function to create Context.Key object instance.
- the name parameter of Context.key(name) is used as debug name and does not impact behavior.
- But, Users cannot create Context.Key without specifying debug name
- It means user must specify the debug name of Context.Key although the user don't want to use it.
- It is better that a parameter for debug (like the name parameter) is being optional
- It will make users recognize `multiple different keys may have a same name` from the code before they see the document of the function
> grpc-context: add a option to create Context.Key with default name

- netty/src/main/java/io/grpc/netty/NettyServerTransport.java
- netty/src/test/java/io/grpc/netty/NettyServerTransportTest.java
This PR changes the `NettyServerTransport#getLogLevel` method to log `SocketException`s to `LogLevel.FINE`, rather than exclusively pure IOExceptions. This may fix an unintentional regression introduced in c166ec2c4e0fa88ea9dfa6e5766ea04d80a21c8b, although the message in my java version (14.0.1) wouldn't have passed the old logic for quieting either. This also fixes the issue raised in https://github.com/grpc/grpc-java/issues/6423 that was locked for inactivity.
This fixes 
```
[2020/05/14 20:21:52   INFO] [io.grpc.netty.NettyServerTransport.connections] Transport failed
java.net.SocketException: Connection reset
at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:345)
at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:376)
at …
```
> netty: log SocketExceptions at FINE, too

- xds/build.gradle
- xds/src/main/java/io/grpc/xds/EnvoyProtoData.java
- xds/src/main/java/io/grpc/xds/XdsClientImpl.java
- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/test/java/io/grpc/xds/EnvoyProtoDataTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
- All objects of converted types should be valid to gRPC (if the original proto message contains invalid data, the conversion should fail and no object should be instantiated).
- Use `null` in converted objects for unset fields in proto messages. This puts a much stronger/clearer signal for proto's `oneof` type.
Most conversion logic and tests are trivial. But the way we represent data and perform checks matters.
> xds: add more route matching types in converted Route data structure

- xds/src/main/java/io/grpc/xds/EnvoyProtoData.java
- xds/src/main/java/io/grpc/xds/XdsClientImpl.java
- xds/src/test/java/io/grpc/xds/EnvoyProtoDataTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
- `Route`s with action of specifying `cluster_header` should be skipped.
- Eliminate unnecessary logic for validating converted data in XdsClientImpl.
> xds: change route data validation logic

- alts/src/main/java/io/grpc/alts/internal/AltsChannelCrypter.java
To avoid having too many `ShortBufferException` thrown in ALTS code path on Java 8, we came up with this workaround creating new managed buffer, filling it, and passing it to underlying Conscrypt not to hit the code path throwing the exception. This might look to introduce another inefficiency but it's more like making it explicit because Conscrypt will do for non-managed buffer which gRPC uses.
Fix: #6761
> Explicit ALTS buffer management to avoid too many ShortBufferException

- COMPILING.md
- build.gradle
- buildscripts/build_docker.sh
- buildscripts/make_dependencies.bat
- buildscripts/make_dependencies.sh
- examples/android/clientcache/app/build.gradle
- examples/android/helloworld/app/build.gradle
- examples/android/routeguide/app/build.gradle
- examples/android/strictmode/app/build.gradle
- examples/build.gradle
- examples/example-alts/build.gradle
- examples/example-gauth/build.gradle
- examples/example-gauth/pom.xml
- examples/example-hostname/build.gradle
- examples/example-hostname/pom.xml
- examples/example-jwt-auth/build.gradle
- examples/example-jwt-auth/pom.xml
- examples/example-tls/build.gradle
- examples/example-tls/pom.xml
- examples/pom.xml
- repositories.bzl
Version 3.12.0 is needed for the feature of support for proto3 field presence #7051
> all: bump protobuf to 3.12.0

- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
> netty: use getOrCreate() for new instances of ChannelLogger AttributeKey (backport #7048)

- compiler/src/java_plugin/cpp/java_plugin.cpp
Support proto3 field presence #7051.
This is the same change as https://github.com/grpc/grpc/pull/22998/files#diff-6c29ff8771ae54ddf2c14e2ef3eb554fR37-R44
> compiler: support proto3 field presence for codegen

- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- netty/src/main/java/io/grpc/netty/Utils.java
- netty/src/test/java/io/grpc/netty/NettyTransportTest.java
- netty/src/test/java/io/grpc/netty/UtilsTest.java
Closes #6954 
Bug fix to return status code `UNAVAILABLE` when a netty channel has an unresolved InetSocketAddress
> netty: return status code unavailable when netty channel has unresolved InetSocketAddress

- COMPILING.md
- build.gradle
- buildscripts/build_docker.sh
- buildscripts/make_dependencies.bat
- buildscripts/make_dependencies.sh
- compiler/src/java_plugin/cpp/java_plugin.cpp
- examples/android/clientcache/app/build.gradle
- examples/android/helloworld/app/build.gradle
- examples/android/routeguide/app/build.gradle
- examples/android/strictmode/app/build.gradle
- examples/build.gradle
- examples/example-alts/build.gradle
- examples/example-gauth/build.gradle
- examples/example-gauth/pom.xml
- examples/example-hostname/build.gradle
- examples/example-hostname/pom.xml
- examples/example-jwt-auth/build.gradle
- examples/example-jwt-auth/pom.xml
- examples/example-tls/build.gradle
- examples/example-tls/pom.xml
- examples/pom.xml
- repositories.bzl
This is backport of #7052 and #7054 .
> support proto3 field presence for codegen (backport v1.30.0)

- COMPILING.md
- compiler/README.md
older version can't compile new proto3 field presence changes (#7058)
```
> Task :grpc-compiler:compileJava_pluginExecutableJava_pluginCpp FAILED
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings
67 actionable tasks: 21 executed, 46 up-to-date
<-------------> 0% WAITING
> Resolve files of :grpc-android-interop-testing:debugCompileClasspath > Transf
> Transforming artifact annotations.jar (com.google.android:annotations:4.1.1.4
> Resolve files of :grpc-android-interop-testing:debugCompileClasspath > Transf
> :grpc-android:verifyReleaseResources …
```
> COMPILING.md: update protoc version requirement

- xds/src/main/java/io/grpc/xds/EnvoyProtoData.java
- xds/src/main/java/io/grpc/xds/XdsClientImpl.java
- xds/src/test/java/io/grpc/xds/EnvoyProtoDataTest.java
- Do not enforce format requirements for path matchers.
- Only require the last route to be a default route (prefix = "" or "/", and ignore any other matchers) when routing is disabled.
> xds: remove path matcher format requirements and default route requirement for routing enabled

- xds/src/main/java/io/grpc/xds/EnvoyProtoData.java
- xds/src/main/java/io/grpc/xds/XdsClientImpl.java
- xds/src/test/java/io/grpc/xds/EnvoyProtoDataTest.java
- Do not enforce format requirements for path matchers.
- Only require the last route to be a default route (prefix = "" or "/", and ignore any other matchers) when routing is disabled.
----------------
Backport of #7063
> xds: remove path matcher format requirements and default route requirement for routing enabled (v1.30.x backport)

- alts/src/main/java/io/grpc/alts/internal/AltsChannelCrypter.java
> Explicit ALTS buffer management to avoid too many ShortBufferException (backport of #7049 to 1.30.x)

- examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlServer.java
- services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java
- stub/src/main/java/io/grpc/stub/CallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ClientCallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ServerCalls.java
- stub/src/test/java/io/grpc/stub/ClientCallsTest.java
- stub/src/test/java/io/grpc/stub/ServerCallsTest.java
This splits server-side flow control from client-side, but tailors the API for
each case. Client-side continues having disableAutoRequestWithInitial(). While
client-side could have disableAutoRequest(), it seems like it will only rarely
be used and disableAutoRequestWithInitial(0) isn't that bad. So we leave it off
for now; we can always add it in the future.
------
When this is merged I will sync it internally by itself, so that I can fix up the one
user of the current API (being replaced).
This API change was discussed at https://github.com/grpc/grpc-java/issues/1788#issuecomment-628816809
This is intended to be backported into 1.30.
> stub: Have disableAutoRequest() on server-side

- examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlServer.java
- services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java
- stub/src/main/java/io/grpc/stub/CallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ClientCallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ServerCalls.java
- stub/src/test/java/io/grpc/stub/ClientCallsTest.java
- stub/src/test/java/io/grpc/stub/ServerCallsTest.java
This splits server-side flow control from client-side, but tailors the API for
each case. Client-side continues having disableAutoRequestWithInitial(). While
client-side could have disableAutoRequest(), it seems like it will only rarely
be used and disableAutoRequestWithInitial(0) isn't that bad. So we leave it off
for now; we can always add it in the future.
-----
This is a backport of #7071
> stub: Have disableAutoRequest() on server-side (v1.30.x backport)

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/ServiceConfigErrorHandlingTest.java
The original service config error handling design was unclear about the case when an updated resolution result with valid service config and empty address is returned to Channel, and the selected LB policy does not accept empty addresses. Existing implementation silently triggers resolver backoff after LB policy is changed, while leaving Channel being CONNECTING state, if there was an old service config resolved. This change converge the behaviors of whether the received service config is the first one or an update to a previous config, in both cases, Channel goes into TRANSIENT_FAILURE if the selected LB policy cannot handle empty addresses.
------------
Backport of #7073.
> core: turn Channel into TF if resolver gives empty addresses with policy selection cannot handle it (backport v1.30x)

- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
> xds: return empty service config to Channel when the requested LDS/RDS resource does not exist (backport v1.30x)

- xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
- xds/src/main/java/io/grpc/xds/EdsLoadBalancer.java
- xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/EdsLoadBalancerTest.java
Put Channel into TRANSIENT_FAILURE when CDS/EDS resource that is currently being watched becomes unavailable.
- For CDS policy, it simply shuts down its child EDS policy and propagate TRANSIENT_FAILURE to its parent policy.
- For EDS policy, existing `LocalityStore.reset()` works similar to shutting down downstream balancers and doing cleanup. Whether or not stop load reporting for current {cluster:eds_service} (note EDS resource = `if eds_service != null then eds_service else cluster`) is an open question. In this change, it will be stopped.
- Tests for `EdsLoadBalancer` is sort of messy, largely because we are also trying to maintain the functionality of it being working alone (although the internal interop tests for real use cases had been deleted). It might get cleaner after we …
> xds: no longer use existing Subchannels after xDS resource becomes unavailable

- xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
- xds/src/main/java/io/grpc/xds/EdsLoadBalancer.java
- xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/EdsLoadBalancerTest.java
Put Channel into TRANSIENT_FAILURE when CDS/EDS resource that is currently being watched becomes unavailable. CDS/EDS LB policies should shut down their downstream policy instances (stop using current Subchannels for new RPCs) and propagate TRANSIENT_FAILURE status to their parent policies (and may eventually to the Channel).
-------------
Backport of #7081.
> xds: no longer use existing Subchannels after xDS resource becomes unavailable (backport v1.30x)

- core/src/main/java/io/grpc/internal/RetriableStream.java
This fixes #6817 for the normal retry case, although it makes the hedging issue #7089 more broken, and there is still space of optimization for normal retry.
> core: always propagate RetriableStream.Sublistener.onReady()

- xds/src/main/java/io/grpc/xds/LocalityStore.java
- xds/src/test/java/io/grpc/xds/LocalityStoreTest.java
Bug description: 
- When receiving an EDS update that removes a locality, the child balancer for that locality is not deleted immediately (delayed deletion for 15 minutes). However, the load stats counter for that locality is always deleted from the LoadStatsStore immediately! After a while (< 15 minutes) when this locality is added back, a new counter is created for it. However, the undeleted leaf balancer for this locality is still using the old counter. All loads are still recorded into the counter. This results in load reporting always reports 0 RPCs for that locality.
Fix:
- Create the counter for recording per locality stats upon creating the child balancer for that locality. When the locality is deactivated (due to EDS response update removes it), the counter is not deleted from …
> xds: retain locality stats counter when the child balancer for that locality is deactivated

- xds/src/main/java/io/grpc/xds/LocalityStore.java
- xds/src/test/java/io/grpc/xds/LocalityStoreTest.java
Create the counter for recording per locality stats upon creating the child balancer for that locality. When the locality is deactivated (due to EDS response update removes it), the counter is not deleted from the LoadStatsStore. Delete it when the child balancer for that locality is shut down. In this way, the lifecycle of the load stats counter for a certain locality stays same with the child balancer for that locality. This is exactly what will happen after we refactor LocalityStore to PriorityLoadBalancer and LrsLoadBalancer (i.e., when some priority is deactivated, its subtree is not deleted immediately, so the LrsLoadBalancer instances for localities still hold the load stats counters).
Backport of #7096.
> xds: retain locality stats counter when the child balancer for that locality is deactivated (backport v1.30.x)

- all/build.gradle
> all: remove grpc-rls from grpc-all dependencies (backport v1.30.x)

- android-interop-testing/src/androidTest/AndroidManifest.xml
- android-interop-testing/src/main/AndroidManifest.xml
Android Studio gives warning: "The minSdk version should not be declared in the android manifest file". Typically `minSdkVersion` should be configured in `build.gradle`, it was set in manifest since internally we use Blaze. cl/316513856 is created to update the internal BUILD file that configures `minSdkVersion`. After that CL is merged, this changed can be imported (or patch that CL to the import CL).
> android-interop-testing: remove SDK version configurations from manifest to avoid Android Studio warnings

- interop-testing/src/generated/main/grpc/io/grpc/testing/integration/XdsUpdateHealthServiceGrpc.java
- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java
- interop-testing/src/main/proto/grpc/testing/test.proto
This adds a simple service to the XdsTestServer to allow dynamically changing the server's health status to/from serving/not-serving. The existing xds tests simply kill the VM to simulate an unhealthy server - in retrospect this approach seems suboptimal generally, but in particular it made it impossible to test the new gentle failover feature which relies on VMs existing but reporting unhealthy. Now the test runner can simply send an RPC to the server and have it ~instantly switch between health statuses rather than waiting for VMs to start/stop.
> interop-testing: add xds test service to set healthy/unhealthy

- examples/README.md
- examples/build.gradle
- examples/gradle/wrapper/gradle-wrapper.properties
- examples/src/main/java/io/grpc/examples/retrying/RetryingHelloWorldClient.java
- examples/src/main/java/io/grpc/examples/retrying/RetryingHelloWorldServer.java
- examples/src/main/resources/io/grpc/examples/retrying/retrying_service_config.json
Provides an example HelloWorld GRPC client & server which demos the effect of client retry policy configured to the [ManagedChannel](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#defaultServiceConfig-java.util.Map-) via [GRPC ServiceConfig](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ManagedChannelServiceConfig.java).
Retry policy configuration is outlined in its [proposal](https://github.com/grpc/proposal/blob/master/A6-client-retries.md), and this example is very similar to the [Hedging Example](https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/hedging).
I created this example to prove that client GRPC retry via service config does indeed work (although still marked as experimental). …
> examples: Adds client/server retrying example via service config

- api/src/main/java/io/grpc/LoadBalancer.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/util/ForwardingLoadBalancerHelper.java
this allows RLS or any LB to configure OobChannel such as service config.
> api,core: add LoadBalancer.Helper#createResolvingOobChannelBuilder api

- xds/src/main/java/io/grpc/xds/internal/sds/SdsProtocolNegotiators.java
- xds/src/test/java/io/grpc/xds/XdsSdsClientServerTest.java
- xds/src/test/java/io/grpc/xds/internal/sds/SdsProtocolNegotiatorsTest.java
As promised in PR [#7131](https://github.com/grpc/grpc-java/pull/7131#discussion_r441212806) this takes care of default values in tlsContext
> xds: use fallback PN if you get exception while retrieving SslContextProvider

- core/src/main/java/io/grpc/inprocess/InProcessTransport.java
- core/src/main/java/io/grpc/internal/AbstractClientStream.java
- core/src/main/java/io/grpc/internal/AbstractServerStream.java
- core/src/main/java/io/grpc/internal/AbstractStream.java
- core/src/main/java/io/grpc/internal/ApplicationThreadDeframer.java
- core/src/main/java/io/grpc/internal/ApplicationThreadDeframerListener.java
- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/DelayedStream.java
- core/src/main/java/io/grpc/internal/ForwardingClientStream.java
- core/src/main/java/io/grpc/internal/ForwardingDeframerListener.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/main/java/io/grpc/internal/MessageDeframer.java
- core/src/main/java/io/grpc/internal/MigratingThreadDeframer.java
- core/src/main/java/io/grpc/internal/NoopClientStream.java
- core/src/main/java/io/grpc/internal/RetriableStream.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
- core/src/main/java/io/grpc/internal/SquelchLateMessagesAvailableDeframerListener.java
- core/src/main/java/io/grpc/internal/Stream.java
- core/src/main/java/io/grpc/internal/ThreadOptimizedDeframer.java
- core/src/test/java/io/grpc/internal/AbstractClientStreamTest.java
- core/src/test/java/io/grpc/internal/AbstractServerStreamTest.java
- core/src/test/java/io/grpc/internal/ApplicationThreadDeframerTest.java
- cronet/src/main/java/io/grpc/cronet/CronetClientStream.java
- netty/src/main/java/io/grpc/netty/NettyClientStream.java
- netty/src/main/java/io/grpc/netty/NettyServerStream.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
- stub/src/main/java/io/grpc/stub/ClientCalls.java
Possible alternative to #5800 which also helps reading many small messages. Not a direct replacement because onHalfClose() still delays the server from responding earlier when using our stubs.
CC @carl-mastrangelo 
I hacked the server stub to avoid waiting for onHalfClose for these numbers:
```
Before
After
Benchmark                                               (direct)  (transport)    Mode    Cnt        Score     Error  Units
Benchmark                                               (direct)  (transport)    Mode    Cnt         Score     Error  Units
TransportBenchmark.unaryCall1024                           false        NETTY  sample  55343   180432.321 ± 960.495  ns/op
TransportBenchmark.unaryCall1024                           false        NETTY  sample  63613   156958.498 ± 996.485 …
```
> core: Add migrating deframer

- rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
- rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
- rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
this allows client libraries to use directpath enabled RLS target while open source users can disable it when directpath is not used.
> rls: use system property to use direct path for oob channel

- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/main/java/io/grpc/xds/XdsClientImpl.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
Since CDS is a state-of-the-world protocol, an CDS response contains resource data (if exists) for all requested clusters. It should avoid pushing identical data to the watching parties that has previously received it.
- EDS does not have such a problem: according to the xDS protocol, the management server will only send resources with changes, and EDS is an incremental protocol, each EDS response should not contain `ClsuterLoadAssignment` that identical to a previously sent one.
- LDS does not have such a problem: we will request at most one `Listener` resource, and TD will not send extra. It will also not send it again if nothing has changed to the resource according to the xDS protocol.
- RDS does not have such a problem: same reason as LDS, plus it's incremental.
The reason that this …
> xds: avoid pushing duplicate (CDS) resource data to watchers

- xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
- xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java
Will make the same fix in 1.30 once approved/merged
> xds: disable processing of UpstreamTlsContext until we are ready to test the feature

- alts/src/main/java/io/grpc/alts/internal/AltsAuthContext.java
- alts/src/test/java/io/grpc/alts/internal/AltsAuthContextTest.java
@ZhenLian For code review
Added and tested accessing peer attributes map from the handshaker result
> alts: add peer attribute access for the ALTS context

- build.gradle
- netty/src/test/java/io/grpc/netty/TlsTest.java
Since Travis in on Java 8u252, we won't actually be testing Jetty ALPN at this
point. We're also not testing the Java 9 ALPN API on Java 8, since our current
version of Netty doesn't support it (but an upgrade is available that does).
> Bump Jetty ALPN to 2.0.10 for Java 8u252

- .github/ISSUE_TEMPLATE/bug_report.md
We've been using the bug label for "confirmed" bugs. Many issues filed as bugs
turn out not to be bugs, but we've not generally remembered to remove the bug
label. This has been causing trouble for tracking bug closure rate, as the data
is now mostly garbage. This change is to put us back into our old flow where
confirmed bugs have the label.
CC @srini100
> github: Remove bug label from newly filed bugs

- api/src/main/java/io/grpc/ForwardingChannelBuilder.java
- api/src/main/java/io/grpc/LoadBalancerProvider.java
- api/src/main/java/io/grpc/ManagedChannelBuilder.java
- api/src/main/java/io/grpc/ManagedChannelProvider.java
- api/src/main/java/io/grpc/NameResolverProvider.java
- api/src/main/java/io/grpc/ServerProvider.java
- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
- xds/src/test/java/io/grpc/xds/XdsSdsClientServerTest.java
It has been our intention for years to remove nameResolverFactory. We should
make it clear to users to avoid new code depending on it and so they can tell
us why they need it so we can provide replacements.
Also added documentation for Provider SPI discovery
----
I plan to merge the two commits separately.
> api: Deprecate ManagedChannelBuilder.nameResolverFactory

- stub/src/main/java/io/grpc/stub/ServerCalls.java
The method did nothing; just inline its contents. Brought up as part of #7173's
review.
> stub: Remove useless private method indirection

- stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java
This avoids the "changes" description, which could be understood to mean that
the transition is important instead of the steady-state and thus a callback
might not be called (which is not the case).
Much of the language was copied from ServerCall.
> stub: Clarify ServerCallStreamObserver cancellation

- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
This should avoid messages being leaked when a Listener throws an exception and
the executor is shut down immediately after the call completes. This is related
to #7105 but a different scenario and we aren't aware of any user having
observed the previous behavior.
Note also this does _not_ fix the similar case of reordering caused by
delayedCancelOnDeadlineExceeded().
CC @njhill
> core: Delay client listener exception notification until normal close

- build.gradle
- examples/build.gradle
- examples/example-alts/build.gradle
- examples/example-alts/settings.gradle
- examples/example-gauth/build.gradle
- examples/example-gauth/settings.gradle
- examples/example-hostname/build.gradle
- examples/example-jwt-auth/build.gradle
- examples/example-jwt-auth/settings.gradle
- examples/example-tls/build.gradle
- examples/example-tls/settings.gradle
- examples/example-xds/build.gradle
- examples/settings.gradle
- gae-interop-testing/gae-jdk8/build.gradle
As seen at https://maven-central.storage.googleapis.com/index.html . The old
URL still has content, but apparently is no longer being updated. For example,
jetty-alpn-agent-2.0.10.pom is not present.
> Swap to new Google Maven Central mirror URL

- core/src/main/java/io/grpc/internal/AbstractStream.java
- core/src/main/java/io/grpc/internal/MigratingThreadDeframer.java
This reverts commit bcb287bb1573a864a45fa1903465277bf3c80772 in #7195, which caused weighted_round_robin_test_cpp_java (cl/320536176) failing consistently.
> Revert "core: Fix migrating deframer compatibility with RetriableStream"

- core/build.gradle
The first such class was added in fd5f4aac6.
> core: Hide Javadoc for Internal* in-process transport classes

- gae-interop-testing/gae-jdk8/build.gradle
- interop-testing/build.gradle
This prevents grpc-xds and its transitive dependencies from being included
twice in distTar and distZip, which reduces the size from 60 MB to 40 MB. It
does mean that interop-testing as a whole depends on xds, but that should not
be an issue any longer. It was an issue before we started providing grpc-xds on
Maven Central.
> interop-testing: Use normal runtimeOnly dep for xds

- benchmarks/build.gradle
'runtime' is the old classpath, pre-java-library plugin. We could swap to
'runtimeClasspath', but it is cleaner to just use startScript's defaults. We
already use that approach in interop-testing.
Fixes #7218
CC @raboof
> benchmarks: Use correct classpath for scripts

- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
Motivation:
`AbstractInteropTest.deadlineExceeded()` sometimes fails with the following exception:
```
java.lang.AssertionError: ClientCall started after deadline exceeded: -0.156096736s from now
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at io.grpc.testing.integration.AbstractInteropTest.deadlineExceeded(AbstractInteropTest.java:1116)
```
.. because a client call can expire even before sending any request depending on how OS schedules, etc.
Modifications:
- Do not fail the test when a call failed with `ClientCall started after deadline exceeded:`.
Result:
- More stable build for gRPC implementations that test themselves by extending `AbstractInteropTest`
- Closes #7189
> interop-testing: fix flakiness of deadlineExceeded test

- api/src/main/java/io/grpc/InternalConfigSelector.java
- api/src/test/java/io/grpc/InternalConfigSelectorTest.java
Based on offline discussion with @ejona86 we found that the interceptor approach for `ConfigSelector` would be ~extremely difficult~(Edited) adding a layer of indirection for no gain:
The API Result selectConfig(LoadBalancer.PickSubchannelArgs args) consumes headers among other inputs, because route matching might need to match the headers; and the API produces ClientInterceptor among other outputs. But the headers is not available until clientCall.start(listner, headers), whereas the interceptor need be applied to the call before clientCall.start(). So the input is not available until the output is applied. That means we will need to delay calling the downstream newCall() (which will either be RealChannel or the interceptor) until start() is called.
So we want to change to the other …
> api: change ConfigSelector.Result to use callback instead of interceptor

- xds/src/main/java/io/grpc/xds/RouteMatch.java
- xds/src/main/java/io/grpc/xds/XdsRoutingLoadBalancer.java
- xds/src/test/java/io/grpc/xds/RouteMatchTest.java
Combine values of header fields with the same key to a comma-separated string before performing header matching.
-------------------
Backport of #7215
> xds: perform header matching on concatenated values (v1.31.x backport)

- grpclb/src/main/java/io/grpc/grpclb/GrpclbConstants.java
This is used for an internal name resolver.
> grpclb: Make ATTR_LB_ADDRS public.

- xds/src/main/java/io/grpc/xds/RouteMatch.java
- xds/src/main/java/io/grpc/xds/XdsRoutingLoadBalancer.java
- xds/src/test/java/io/grpc/xds/RouteMatchTest.java
- Expose "content-type" header (hard-coded) at header matching, pretend it's already there.
- ~Hide "grpc-tags-bin", "grpc-trace-bin" and "grpc-previous-rpc-attempts", pretend they are not there.~
- ~Do not exclude binary headers from header matching, they can still be useful for present matchers (which checks if a given header present regardless its value).~
Details in b/159631362
> xds: add header matching special cases for hiding/exposing some gRPC headers

- xds/src/main/java/io/grpc/xds/LoadReportClient.java
- xds/src/test/java/io/grpc/xds/LoadReportClientTest.java
Two changes for `LoadReportClient` in this PR:
- Add support for `send_all_clusters` field in LRS response.
- When it is set to `true`, just send load reports for clusters that the client is currently tracking (aka, is sending load to).
- The [actual load report interval](https://github.com/grpc/grpc-java/blob/8ef09d74283c0a5fb768b39a3e84023c7cb5422c/xds/third_party/envoy/src/main/proto/envoy/api/v2/endpoint/load_report.proto#L154) (in each `ClusterStats` message, which contains the stats for each cluster:eds_service) is tracked individually.
- Example:
Initially, if the client has load stats recorded for `cluster-foo:eds_service-foo` and `cluster-bar:eds_service-bar` while the management server is only asking for load stats for `cluster-foo:eds_service-foo` to be reported every 10 …
> xds: support load reporting all clusters option and fix actual report interval measurement

- xds/src/main/java/io/grpc/xds/XdsRoutingLoadBalancer.java
- xds/src/test/java/io/grpc/xds/XdsRoutingLoadBalancerTest.java
The routing LB policy should immediately the Channel's picker that delegates picking to the updated routes. Otherwise, new RPCs will keep being sent through old routes even if they are removed. This change also includes the fix for syncing state change for child balancers in deactivated state.
------------
This is backport of #7233.
> xds: routing policy should immediately update a picker that selects base on updated config (backport v1.31.x) (#7233)

- buildscripts/kokoro/upload_artifacts.sh
The previous 'git ls-remote' was returning the tag-referenced commits via
vF.O.O^{} which was confusing the version check (as v1.30.0 would not match
v1.30.0^{}). Passing --refs filters those ^{} tags.
There was also a missing 'v' in the version check. It was added explicitly to
generate the list but not to check the result.
> buildscripts: Fix check for java-example-hostname:latest tagging

- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/OobChannel.java
- core/src/main/java/io/grpc/internal/SubchannelChannel.java
- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
Replace the two APIs of `ClientCallImpl.ClientTransportProvider` with a single API: newStream()
~This might make `ManagedChanelImpl` more flexible to apply `ConfigSelector`.~
> core: refactor ClientTransportProvider to ClientStreamProvider

- android-interop-testing/build.gradle
- android/build.gradle
- cronet/build.gradle
- examples/android/helloworld/app/build.gradle
- examples/android/routeguide/app/build.gradle
Resolves #7244. 
This also includes the change to avoid pulling google auto-service from Robolectric, which gives a warning of
```
Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the testAnnotationProcessor configuration.
- auto-service-1.0-rc4.jar (com.google.auto.service:auto-service:1.0-rc4)
```
cl/323410410 cleans up the internal interop tests.
> android, cronet, android-interop-testing, example/drop support for android SDK versions older than 16

- buildscripts/kokoro/xds.sh
- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestClient.java
- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java
- interop-testing/src/main/proto/grpc/testing/messages.proto
New test cases require the `--rpc` and `--metadata` flags. This PR is the Java analog/port of the Go change in https://github.com/grpc/grpc-go/pull/3737
cc @menghanl
> Add xds client flags

- api/src/main/java/io/grpc/InternalConfigSelector.java
- api/src/test/java/io/grpc/InternalConfigSelectorTest.java
This is needed for cases like the ConfigSelector fails to find a route/cluster for the RPC.
> xds: include a status for the result of ConfigSelector

- xds/src/main/java/io/grpc/xds/Bootstrapper.java
- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/main/java/io/grpc/xds/XdsClientImpl.java
- xds/src/test/java/io/grpc/xds/BootstrapperTest.java
- xds/src/test/java/io/grpc/xds/EdsLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTestForListener.java
- xds/src/test/java/io/grpc/xds/XdsClientTest.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverIntegrationTest.java
In preparation for xds-v3 support.
> xds: Add server features support to Bootstrapper

- xds/src/main/java/io/grpc/xds/internal/rbac/engine/cel/IncompleteData.java
This PR added `IncompleteData` interface into the mock CEL library in gRPC-Java.
CEL `eval` function will return an `IncompleteData` object if there are missing attributes.
@ZhenLian
> xds: Added IncompleteData interface in mock CEL library

- xds/src/main/java/io/grpc/xds/EnvoyProtoData.java
- xds/src/test/java/io/grpc/xds/EnvoyProtoDataTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
A small part of implementing per-method timeout configuration.
> xds: parse timeout from RDS responses

- xds/src/main/java/io/grpc/xds/XdsClientImpl.java
- xds/src/test/java/io/grpc/xds/EdsLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTestForListener.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTestV2.java
- xds/src/test/java/io/grpc/xds/XdsClientTestHelper.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverIntegrationTest.java
Duplicated `XdsClientImptTest` for V3. `XdsClientImptTestV2` and all other tests are still using V2. Even for `XdsClientImptTest`, although the protocol is V3, the test xds server still sends V2 resources in its V3 response.
> xds: support v3 for XdsClient

- xds/src/test/java/io/grpc/xds/XdsClientImplTestV2.java
Resolve conflicts between 14af76cab1004dede876521f76d5bac49c5471b7 and 5bf68ff28c4dd67c1f44c5d156c73cb2c102c903
#7257 added a new field in the RouteAction data structure, while #7273 duplicated the old tests for xDS v2 while not including the new change.
Some background:
The parsed RouteAction should have a 15-second timeout by default if the xDS server does not specify any timeout in the corresponding route.
> xds: resolve conflicts by adding timeout field in parsed RouteAction for v2 tests

- core/src/main/java/io/grpc/internal/DelayedClientCall.java
- core/src/test/java/io/grpc/internal/DelayedClientCallTest.java
Adding `DelayedClientCall` in preparation of implementing `ConfigSelector` in core. Big picture is shown in #7259. 
`DelayedClientCall` is implemented exactly in the same way as `DelayedStream`. Only added logic to monitor initial DEADLINE.
> core: Add DelayedClientCall

- api/src/test/java/io/grpc/ServerInterceptorsTest.java
- build.gradle
- census/src/test/java/io/grpc/census/CensusModulesTest.java
- core/src/test/java/io/grpc/internal/ApplicationThreadDeframerTest.java
- core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java
- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- core/src/test/java/io/grpc/internal/MessageFramerTest.java
- core/src/test/java/io/grpc/util/MutableHandlerRegistryTest.java
- netty/src/test/java/io/grpc/netty/NettyServerStreamTest.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
- services/src/test/java/io/grpc/services/HealthCheckingLoadBalancerFactoryTest.java
- xds/src/test/java/io/grpc/xds/OrcaOobUtilTest.java
- xds/src/test/java/io/grpc/xds/OrcaPerRequestUtilTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTestV2.java
verifyZeroInteractions has the same behavior as verifyNoMoreInteractions. It
was deprecated in Mockito 3.0.1 and replaced with verifyNoInteractions, which
does not change behavior depending on previous verify() calls. All instances
were replaced with verifyNoInteractions, except those in
ApplicationThreadDeframerTest which were replaced with verifyNoMoreInteractions
since there is a verify() call in `@Before`.
-----
3.3.3 was chosen as that is the last version that matches the internal mockito version. The internal linter was complaining about verifyZeroInteractions being deprecated.
> Upgrade to Mockito 3.3.3

- compiler/src/java_plugin/cpp/java_generator.cpp
FALLTHROUGH_INTENDED was defined by Abseil, but is now getting an ABSL
prefix and the old name will be removed. Swapping to a new define name
to avoid redefining the existing-but-soon-to-be-deleted
FALLTHROUGH_INTENDED.
> compiler: Swap to ABSL_FALLTHROUGH_INTENDED

- examples/android/clientcache/build.gradle
- examples/android/helloworld/build.gradle
- examples/android/routeguide/build.gradle
- examples/android/strictmode/build.gradle
> examples: add mavenCentral for android example's dependency repository (v1.31.x backport) (#7293)

- compiler/src/java_plugin/cpp/java_generator.cpp
- compiler/src/java_plugin/cpp/java_generator.h
- compiler/src/java_plugin/cpp/java_plugin.cpp
Due to historical reasons, protobuf is in the proto2:: namespace
internally instead of google::protobuf. We have been maintaining diffs
that replace each occurence of one with the other. Instead we can simply
create a namespace alias and use that alias instead of the canonical
name. That greatly reduces the size of the diff and its likelihood to
break.
If the names ever align in the future, we can swap back to the canonical
names.
> compiler: Use namespace aliases to reduce internal diff

- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
A user has reported a GOAWAY with too_many_pings when using BDP. We
aren't certain why it is happening, but want to provide a way to disable
BDP while we continue investigating. b/162162973
> netty: Provide an environment variable to toggle BDP monitoring

- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
A user has reported a GOAWAY with too_many_pings when using BDP. We
aren't certain why it is happening, but want to provide a way to disable
BDP while we continue investigating. b/162162973
--------
This is a backport of #7302
> netty: Provide an environment variable to toggle BDP monitoring (v1.31.x backport)

- xds/src/main/java/io/grpc/xds/RouteMatch.java
- xds/src/test/java/io/grpc/xds/RouteMatchTest.java
Expose "content-type" header (hard-coded) at header matching, pretend it's already there.
Backport of #7224
> xds: add header matching special cases for hiding/exposing some gRPC headers (v1.31.x backport)

- xds/src/main/java/io/grpc/xds/LoadReportClient.java
- xds/src/test/java/io/grpc/xds/LoadReportClientTest.java
- Add support for send_all_clusters field in LRS response. When it is set to true, just send load reports for clusters that the client is currently tracking (aka, is sending load to).
- The actual load report interval (in each ClusterStats message, which contains the stats for each cluster:eds_service) should be tracked individually.
----------------
Backport of #7209
> xds: support load reporting all clusters option and fix actual report interval measurement (v1.31.x backport)

- rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
- rls/src/test/java/io/grpc/rls/RlsProtoConvertersTest.java
- rls/src/test/java/io/grpc/rls/RlsRequestFactoryTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTestV2.java
Export internal CL (cl/324443300, see hidden reverted files in the CL) that cleans up parameter comments that don't match the formal parameter name.
> rls, xds: fix parameter comments that do not match the formal parameter name

- xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTestV2.java
This reverts a mistaken and unnecessary change introduced by #7299.
There was a syncing mistake:
#7282 upgraded Mockito to 3.3.3 and replaced verifyZeroInteractions with verifyNotInteractions. But when I merged the master with #7299, the IDE did not pull and index the latest Mockito dependency, which marked verifyNoInteractions as unresolved. I thought it was the method being deprecated and didn't realize it was already the new method that #7282 migrated.
> xds: replace verifyNoMoreInteractions with verifyNoInteractions

- README.md
Followup to #7267. The rest of the README page refers to v1.31.0, so it would seem reasonable to link to the example folders of v1.31.0 too -- rather than v1.30.0.
@ejona86
> README: link to v1.31.0 example directories

- README.md
Followup to #7267. The rest of the README page refers to v1.31.0, so it would seem reasonable to link to the example folders of v1.31.0 too -- rather than v1.30.0.
CC @chalin, @ericgribkoff 
This is a backport of #7287
> README: link to v1.31.0 example directories (v1.31.x backport)

- api/src/main/java/io/grpc/ForwardingChannelBuilder.java
- api/src/main/java/io/grpc/ManagedChannelBuilder.java
All blockingExecutor usages have been cleaned up, so removing the method.
> removed deprecated method blockingExecutor

- interop-testing/src/main/java/io/grpc/testing/integration/GrpclbLongLivedAffinityTestClient.java
Proto fields aren't null. The getter will return an empty string instead
of null.
cl/326415191
> interop-testing: Remove comparison of proto field to null

- core/src/main/java/io/grpc/internal/RetriableStream.java
- cronet/src/main/java/io/grpc/cronet/CronetClientTransport.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
The Java GRPC Bazel rules in `rule_proto_grpc` fail with Bazel 3.4.1 due to GuardedBy errorprone rule. Cherry pick the fix.
This supports releasing a new version of GuardedBy which finds more mistakes than it used to.
Filed ~#6578~#7297 to try to clean up the suppressions.
> all: Add suppressions for GuardedBy violations to v1.24.x to fix Bazel rules_grpc in Bazel 3.4.1

- core/src/main/java/io/grpc/internal/RetriableStream.java
- core/src/test/java/io/grpc/internal/RetriableStreamTest.java
Resolves #7222: If a hedging substream fails triggering throttling threshold, the call should be committed.
Refactored `RetryPlan` to two separate classes `RetryPlan` and `HedgingPlan`.
> core: fix a bug for hedging with throttling

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
#7259 failed internally and there seems to be a bug. Temporarily disable PendingCall.
> core: disable usage of PendingCall due to a bug

- api/src/main/java/io/grpc/NameResolver.java
It appears getAttributes() javadoc was accidentally copied when
ConfigOrError was moved in commit 0244418d2. This restores the
documentation from before the move.
CC @zhangkun83
> api: Fix NameResolver.ConfigOrError javadoc

- alts/src/main/java/io/grpc/alts/internal/AltsFraming.java
- alts/src/main/java/io/grpc/alts/internal/AltsHandshakerClient.java
- alts/src/main/java/io/grpc/alts/internal/AltsTsiHandshaker.java
- alts/src/test/java/io/grpc/alts/internal/AltsFramingTest.java
- alts/src/test/java/io/grpc/alts/internal/AltsHandshakerClientTest.java
- alts/src/test/java/io/grpc/alts/internal/AltsTsiHandshakerTest.java
- alts/src/test/java/io/grpc/alts/internal/FakeTsiTest.java
- alts/src/test/java/io/grpc/alts/internal/MockAltsHandshakerResp.java
- alts/src/test/java/io/grpc/alts/internal/TsiTest.java
- core/src/main/java/io/grpc/internal/CompositeReadableBuffer.java
- core/src/main/java/io/grpc/internal/ReadableBuffers.java
- core/src/test/java/io/grpc/internal/CompositeReadableBufferTest.java
- core/src/test/java/io/grpc/internal/ReadableBufferTestBase.java
- cronet/src/main/java/io/grpc/cronet/CronetClientStream.java
- cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java
Java 9 introduces overridden methods with covariant return types for the following methods in java.nio.ByteBuffer:
- position​(int newPosition)
- limit​(int newLimit)
- flip​()
- clear​()
- mark​()
- reset​()
- rewind​()
In Java 9 they all now return ByteBuffer, whereas the methods they override return Buffer, resulting in exceptions like this when executing on Java 8 and lower:
java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer
This is because the generated byte code includes the static return type of the method, which is not found on Java 8 and lower because the overloaded methods with covariant return types don't exist (the issue appears even with source and target 8 or lower in compilation parameters).
The solution is to cast ByteBuffer instances to Buffer …
> core, alts, cronet: fix ByteBuffer covariant method usages

- core/src/main/java/io/grpc/internal/HedgingPolicy.java
- core/src/main/java/io/grpc/internal/ManagedChannelServiceConfig.java
- core/src/main/java/io/grpc/internal/RetriableStream.java
- core/src/main/java/io/grpc/internal/RetryPolicy.java
- core/src/main/java/io/grpc/internal/ServiceConfigInterceptor.java
- core/src/test/java/io/grpc/internal/HedgingPolicyTest.java
- core/src/test/java/io/grpc/internal/RetriableStreamTest.java
- core/src/test/java/io/grpc/internal/RetryPolicyTest.java
- core/src/test/java/io/grpc/internal/ServiceConfigInterceptorTest.java
We used `null` and `RetryPolicy.DEFAULT` for the value of `retryPolicy` in `RetriableStream` to distinguish the state between name resolution not being completed and name resolution being completed but no retry policy. After the change #7259 , name resolution is always completed when creating a `RetriableStream`, so the distinction will be gone. It will be cleaner to get rid of `RetryPolicy.DEFAULT` and simply use `null` for absence of RetryPolicy. `RetryPolicy.Provider` will be deleted in upcoming PR.
> core: refactor to delete RetryPolicy.DEFAULT

- benchmarks/build.gradle
The Jetty ALPN is not needed for benchmarks. This change removes the `-javaagent` lines from the benchmarks/build.gradle file as suggested by @ejona86.
> Remove -javaagent in benchmark CreateStartScripts

- api/src/test/java/io/grpc/ForwardingChannelBuilderTest.java
> api: fix a small typo in ForwardingChannelBuilderTest

- xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
- xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java
This reverts commit 1260db3305074e9537513be48e275bd880e0277a.
Not ready to enable this change. Existing xDS resolver will still generate a load balancing config that chooses CDS LB policy as the top-level LB policy. This should have been changed when enabling routing by default (#7251), it should always have the routing policy as the top-level policy, even if there is only one route received.
Now we revert this change. We should either change the [existing resolver behavior](https://github.com/grpc/grpc-java/blob/1260db3305074e9537513be48e275bd880e0277a/xds/src/main/java/io/grpc/xds/XdsNameResolver.java#L245.) (follow-up cleanup for enabling routing by default) or enabling this codepath until migrating to XdsNameResolver2.
> Revert "xds: eliminate cluster name change logic in CDS LB policy and reimplement tests (#7356)"

- benchmarks/src/jmh/java/io/grpc/benchmarks/TransportBenchmark.java
- core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
- core/src/main/java/io/grpc/inprocess/InternalInProcessChannelBuilder.java
- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplBuilderTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- core/src/test/java/io/grpc/internal/ServiceConfigErrorHandlingTest.java
- cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
- interop-testing/src/test/java/io/grpc/testing/integration/AutoWindowSizingOnTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyLocalChannelTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/InProcessTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/TransportCompressionTest.java
- netty/src/main/java/io/grpc/netty/InternalNettyChannelBuilder.java
- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- netty/src/test/java/io/grpc/netty/NettyChannelBuilderTest.java
- okhttp/src/main/java/io/grpc/okhttp/InternalOkHttpChannelBuilder.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpChannelBuilderTest.java
- testing/src/main/java/io/grpc/internal/TestingAccessor.java
The first part of #7211: Hide `AbstractManagedChannelImplBuilder` from public API.
I broke down changes into more-or-less logically encapsulated commits. It might be more convenient to review them one by one. An exception is `Internal*ChannelBuilder` classes, their purpose becomes clear only in commit `interop-testing, testing: setup channels with internal channel builders`.
> Channel builders extend public API

- core/src/test/java/io/grpc/internal/AbstractTransportTest.java
- gae-interop-testing/gae-jdk8/src/main/java/io/grpc/testing/integration/NettyClientInteropServlet.java
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyLocalChannelTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
- netty/src/test/java/io/grpc/netty/NettyTransportTest.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpTransportTest.java
Move `65 * 1024` used in tests to a constant, and explain the reasoning behind this specific choice.
> Explain test value for flow control window

- api/src/main/java/io/grpc/MethodDescriptor.java
- api/src/test/java/io/grpc/MethodDescriptorTest.java
To implement credential restrictions based on not only service names but also (non-qualified) method names, we need to expose this property just like the service name got exposed through the API.
This reuses the same experimental tracking issue as getServiceName, but I can to file a new one if necessary.
> core: add accessor for bare method name in MethodDescriptor

- okhttp/src/main/java/io/grpc/okhttp/InternalOkHttpChannelBuilder.java
Allow tests to control OKHttp authority check via `InternalOkHttpChannelBuilder`.
> okhttp: allow disable check authority via internal channel builder

- okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpChannelBuilderTest.java
Keep deprecated `OkHttpChannelBuilder.checkAuthority()` for backward compatibility.
> okhttp: Keep checkAuthority() for backward compatibility

- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverIntegrationTest.java
To unblock merging #7395, given that we are not able to migrate to XdsNameResolver2 shortly.
> xds: always generate xds_routing LB policy as the top-level LB policy in legacy xDS resolver (to be deprecated)

- xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
- xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java
Eliminated the logic in CDS LB policy that handles CDS config change (aka, cluster name change). A CDS LB policy should be used for a single cluster, the cluster should be effectively final. If the upstream LB policy needs to change routing cluster, it should create separate CDS LB policies, one for each cluster.
This change also reimplemented the unit tests for CDS LB policy.
-------------------------
This rolls forward #7356, which was reverted in #7379.
> xds: eliminate cluster name change logic in CDS LB policy and reimplement tests (roll forward #7356)

- netty/shaded/build.gradle
96ad6338 accidentally caused the javadoc and sources jars to no longer
be published for grpc-netty-shaded. It would appear to be due to the
jars being empty. This commit causes them to be published again.
-------
This bug broke the v1.32.0 release. I'll need to cut a v1.32.1 release.
> netty-shaded: Fix publish regression for javadoc and sources

- netty/shaded/build.gradle
96ad6338 accidentally caused the javadoc and sources jars to no longer
be published for grpc-netty-shaded. It would appear to be due to the
jars being empty. This commit causes them to be published again.
-------
This is a backport of #7405
> netty-shaded: Fix publish regression for javadoc and sources (v1.32.x backport)

- xds/src/main/java/io/grpc/xds/internal/certprovider/MeshCaCertificateProvider.java
- xds/src/main/java/io/grpc/xds/internal/certprovider/MeshCaCertificateProviderProvider.java
- xds/src/test/java/io/grpc/xds/internal/certprovider/CommonCertProviderTestUtils.java
- xds/src/test/java/io/grpc/xds/internal/certprovider/MeshCaCertificateProviderProviderTest.java
- xds/src/test/java/io/grpc/xds/internal/certprovider/MeshCaCertificateProviderTest.java
As described here https://cloud.google.com/kubernetes-engine/docs/reference/rest we should support both `/v1/` and `/v1beta1/` and `/locations/` and `/zones/` in the GKE Cluster URL we read from the bootstrap file.
Also the location metadata header value should be `location=locations/$ZONE`
> xds: accept all forms of gkeClusterUrl and fix the 'x-goog-request-params' value

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
There was bug that new pending calls were not drained after channel is shutdown. The bug was worked around by #7354 .
Fixing by making sure new calls fail immediately if the channel is already shutdown.
The tests added will be breaking if #7354 is simply reverted without fix.
> core: fix pending call not drained when shutdown

- alts/src/main/java/io/grpc/alts/internal/AltsChannelCrypter.java
- build.gradle
This PR has two things; 
- Upgrading Conscrypt to 2.5.1 which has
- https://github.com/google/conscrypt/pull/859 Removed unnecessary ByteBuffer to Byte Array conversion for Cipher.doFinal calls
- https://github.com/google/conscrypt/pull/867 Added AOSP OkHostnameVerifier to have usable default ConscryptHostnameVerifier
- https://github.com/google/conscrypt/pull/849 Suppress stack-trace filling of ShortBufferException
- Reverting #7049 because this new Conscrypt fixed the issue in a different way and original PR now spends more CPU time.
> Upgrading Conscrypt to 2.5.1

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
If two consecutive name resolution updates are queued together in SynchronizationContext, `drainPendingCalls()` might be called twice and be broken.
> core: fix drainPendingCalls might be called twice

- xds/src/main/java/io/grpc/xds/Bootstrapper.java
- xds/src/test/java/io/grpc/xds/BootstrapperTest.java
This PR only adds validation to the bootstrap file to require users specify at least one channel creds configuration.
In a following up PR, creating the xDS channel will select the first supported channel creds and fail (e.g., an exception thrown) to create the channel if none is supported (instead of failing back to use parent channel's channel creds). Need to clean up the interfaces for creating XdsClient/Channel.
Also, Ideally I am thinking about having a `BootstrapException`. Using `IOException` is not accurate here.
> xds: make channel creds required in bootstrap file

- core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
Use `builder` instance in all tests.
> core: cleanup AbstractManagedChannelImplBuilderTest

- core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplBuilderTest.java
- netty/src/main/java/io/grpc/netty/InternalNettyChannelBuilder.java
- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- netty/src/test/java/io/grpc/netty/NettyChannelBuilderTest.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpChannelBuilderTest.java
A part of #7211.
OverrideAuthorityChecker was replaced with `disableCheckAuthority()` / `enableCheckAuthority()` in #7359 and #7399 for internal backward compatibility.
cc @ejona86.
> all: remove deprecated internal OverrideAuthorityChecker

- netty/src/main/java/io/grpc/netty/GrpcSslContexts.java
I made this very simple change to test for IBMJSSE2 security provider in addition to the others.
IBM JRE does not support the Sun provider, but instead has IBMJSSE2 which supports the same API calls.
I tested this on Z/OS machine as now it works when before it couldn't find a security provider
> Add support for IBMJSSE2 into grpc-java

- xds/src/main/java/io/grpc/xds/XdsClientImpl.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTestForListener.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTestV2.java
As discussed previously, the `version_info` in the xDS protocol represents the client's knowledge for the state of that resource type. It should persist across ADS stream recreation. Even if the ADS stream is recreated, the XdsClient should persist its knowledge for resources it has received. With this implementation, client and server are stateful across the xDS communication. With persisted version_info, the management server knows resources that the client currently knows even after the stream is recreated. So it does not need to re-send resources that the client received with the previous stream.
> xds: resource (with version info) should persist across ADS streams along with XdsClient lifetime

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
This `SubchannelStateListener` field is redundant. It adds confusion for readers.
> core: remove redundant field

- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
An issue was found during CBT RLS client testing: The RLS lb creates grplb child balancer, calls `grpclb.handleResolvedAddress()` then immediately calls `grpclb.requestConnection()`. The subchannel in `GrpclbState.currentPicker.pickList` contains only `GrpclbState.BUFFER_ENTRY` at the moment `grpclb.requestConnection()` is called, and therefore the `requestConnection()` is no-op, and RPC is hanging.
> grpclb: cache requestConnection if no subchannel created

- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
`ConfigSelector.selectConfig()` is called for every single RPC. Having a log there is too verbose. Developers generally just enables `FINEST` for debugging xDS, so lowering its log level doesn't help, would rather just not log it.
> xds: remove log in data path

- xds/src/main/java/io/grpc/xds/EdsLoadBalancer.java
- xds/src/main/java/io/grpc/xds/XdsChannelFactory.java
- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/main/java/io/grpc/xds/XdsClientImpl.java
- xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/main/java/io/grpc/xds/XdsNameResolverProvider.java
- xds/src/test/java/io/grpc/xds/EdsLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/XdsChannelFactoryTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTestForListener.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTestV2.java
- xds/src/test/java/io/grpc/xds/XdsClientTest.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
Follow up for #7396.
The main change is to create the xDS channel outside XdsClient and creating the xDS channel can fail.
> xds: fail to create xDS channel if no server with supported channel creds found

- xds/src/main/java/io/grpc/xds/EdsLoadBalancerProvider.java
Looks the header matching interop test is passing now. Rerunning all the tests.
This PR only promotes `EdsLoadBalancer2`. Cleanup will be done later in a separate PR.
> xds: promote EdsLoadBalancer2

- xds/src/main/java/io/grpc/xds/EnvoyProtoData.java
- xds/src/main/java/io/grpc/xds/XdsClientImpl.java
- xds/src/test/java/io/grpc/xds/EnvoyProtoDataTest.java
- xds/third_party/envoy/import.sh
- xds/third_party/envoy/src/main/proto/envoy/api/v2/cluster.proto
- xds/third_party/envoy/src/main/proto/envoy/api/v2/route/route_components.proto
- xds/third_party/envoy/src/main/proto/envoy/config/accesslog/v3/accesslog.proto
- xds/third_party/envoy/src/main/proto/envoy/config/cluster/v3/cluster.proto
- xds/third_party/envoy/src/main/proto/envoy/config/core/v3/address.proto
- xds/third_party/envoy/src/main/proto/envoy/config/core/v3/base.proto
- xds/third_party/envoy/src/main/proto/envoy/config/core/v3/grpc_service.proto
- xds/third_party/envoy/src/main/proto/envoy/config/core/v3/protocol.proto
- xds/third_party/envoy/src/main/proto/envoy/config/core/v3/substitution_format_string.proto
- xds/third_party/envoy/src/main/proto/envoy/config/listener/v3/listener.proto
- xds/third_party/envoy/src/main/proto/envoy/config/listener/v3/listener_components.proto
- xds/third_party/envoy/src/main/proto/envoy/config/route/v3/route_components.proto
- xds/third_party/envoy/src/main/proto/envoy/config/route/v3/scoped_route.proto
- xds/third_party/envoy/src/main/proto/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
- xds/third_party/envoy/src/main/proto/envoy/extensions/transport_sockets/tls/v3/common.proto
- xds/third_party/envoy/src/main/proto/envoy/extensions/transport_sockets/tls/v3/tls.proto
- xds/third_party/envoy/src/main/proto/envoy/type/matcher/v3/metadata.proto
- xds/third_party/envoy/src/main/proto/envoy/type/matcher/v3/number.proto
- xds/third_party/envoy/src/main/proto/envoy/type/matcher/v3/string.proto
- xds/third_party/envoy/src/main/proto/envoy/type/matcher/v3/value.proto
Import RouteAction protos with change introduced by https://github.com/envoyproxy/envoy/pull/13018, which is used for gRPC xDS timeout.
Internal envoy import CL: cl/332279092
--------------
Manual changes:
- Suppress warnings for using `listening_addresses` in `io.envoyproxy.envoy.config.core.v3.Node` as it's been deprecated.
> xds: sync Envoy proto to commit fd28e42f31730f5ed6f13f52999692a4885dd312 (2020-09-15)

- xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
- xds/src/main/java/io/grpc/xds/EdsLoadBalancerProvider.java
- xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/EdsLoadBalancerTest.java
This cleans up the temporary workaround code that implicitly includes the locality picking policy internally inside the EDS LB config creation.
> xds: generate EDS config with hardcoded locality picking policy

- xds/src/main/java/io/grpc/xds/LoadReportClient.java
- xds/src/main/java/io/grpc/xds/XdsClientImpl.java
Logging raw response messages should be run in the same synchronization context as other response handling logics. Otherwise, logs for the same response message will be interleaved.
Including minor cosmetic improvements.
> xds: log raw response messages in sync context

- xds/src/main/java/io/grpc/xds/EnvoyProtoData.java
- xds/src/main/java/io/grpc/xds/XdsClient.java
Sadly, `ListenerUpdate` is taken. So I made it `LdsUpdate`. I am going to rename existing update/watchers to `CdsUpdate`/`CdsResourceWatcher`, `EdsUpdate`/`EdsResourceWatcher` for consistency.
Corresponding APIs in C-core:
https://github.com/grpc/grpc/blob/master/src/core/ext/xds/xds_client.h
https://github.com/grpc/grpc/blob/master/src/core/ext/xds/xds_api.h
> xds: define individual LDS/RDS data watch interface

- xds/src/main/java/io/grpc/xds/AddressFilter.java
- xds/src/main/java/io/grpc/xds/CdsLoadBalancerProvider.java
- xds/src/main/java/io/grpc/xds/EdsLoadBalancerProvider.java
- xds/src/main/java/io/grpc/xds/LrsLoadBalancerProvider.java
Do not implement equals()/hashCode() unless there is a reason to.
There is probably more equals()/hashCode() to be deleted. e.g., `WeightedTargetConfig`. But its test is relying on its equals()/hashCode() implementation.
> xds: add toString() and delete unnecessary equals()/hashCode() for LB configs

- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
From #7105, #6328 introduced a memory leak, revert the PR for now. Will come back and fix the race condition in deadline expire cancels.
This reverts commit f6544bf9
> Revert "core: delay sending cancel request on client-side when deadline expires (#6328)"

- xds/src/main/java/io/grpc/xds/LoadReportClient.java
- xds/src/test/java/io/grpc/xds/LoadReportClientTest.java
Corresponding change in C-core: https://github.com/grpc/grpc/pull/24136
> xds: stop setting PROXYLESS_CLIENT_HOSTNAME node metadata in LRS requests

- stub/src/main/java/io/grpc/stub/ServerCalls.java
- stub/src/test/java/io/grpc/stub/ServerCallsTest.java
Unary are far more common than streaming, and we're throwing for unary even
though it doesn't help the service. Let's stop doing that. We also stop
throwing in onComplete() for all cases, because it doesn't help any service;
it doesn't stop the service's processing and isn't even all that informative
since the cancellation can happen even after onComplete() is called.
-------
This is related to #7172, and the docs there would need to be updated. Whichever is merged last will need to be updated.
Note that I saw it is weird that we call both the cancellation and onError callbacks. We should probably just call onError, but that has a greater chance of "being noticed" so I didn't want it to add risk to this PR.
> stub: Only throw on cancellation for streaming responses

- netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
- netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
Normally the first exception/event experienced is the cause and is
followed by a stampede of ClosedChannelExceptions. In this case,
SslHandler is manufacturing a ClosedChannelException of its own and
propagating it _before_ the trigger event. This might be considered a
bug, but changing SslHandler's behavior would be very risky and almost
certainly break someone's code.
Fixes #7376
----
This is a backport of #7476
> netty: TCP close during TLS handshake should be UNAVAILABLE (v1.32.x backport)

- xds/third_party/envoy/import.sh
- xds/third_party/envoy/src/main/proto/envoy/config/accesslog/v3/accesslog.proto
- xds/third_party/envoy/src/main/proto/envoy/config/cluster/v3/cluster.proto
- xds/third_party/envoy/src/main/proto/envoy/config/core/v3/substitution_format_string.proto
- xds/third_party/envoy/src/main/proto/envoy/config/route/v3/route_components.proto
- xds/third_party/envoy/src/main/proto/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
- xds/third_party/envoy/src/main/proto/envoy/extensions/transport_sockets/tls/v3/common.proto
- xds/third_party/envoy/src/main/proto/envoy/extensions/transport_sockets/tls/v3/tls.proto
The xDS timeout fields have been renamed by https://github.com/envoyproxy/envoy/pull/13247, so update the protos to pick up that change.
Internal Envoy import CL: cl/335029474
> xds: sync envoy proto to commit 1c27396b1f7e756ba79eed72b47f485d44da1d41

- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/main/java/io/grpc/xds/XdsClientImpl2.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTest2.java
- xds/src/test/java/io/grpc/xds/XdsClientTestHelper.java
First take for replacing ConfigWatcher with LdsResourceWatcher and RdsResourceWatcher. The next take is #7469.
Effective changes should be for LDS/RDS protocols only. Tests for XdsClientImpl are cleaned up.
> xds: implement XdsClient APIs for watching LDS/RDS resources individually

- rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
- rls/src/main/java/io/grpc/rls/RlsProtoData.java
- rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
The `default_target` field can be unset per the [spec](http://go/grpc-rls-lb-policy-design)
Also fixed a synchronization bug (related to #7460 cc @ejona86 ) that `createOrGet()` should be guarded by lock.
> rls: allow defaultTarget in RouteLookupConfig unset

- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
- Resolving an issue that when there are multiple grpclb balancers in the hierarchical balancer tree (e.g. in the case RLS), logs for grpclb streaming from them are interleaving, it's hard to tell which grpclb is doing what. Prepend the `serviceName` in each log to distinguish their identities.
- Adding logs when resolved address is received, oob channel is created, and initial request is sent.
(I thought about adding some static util methods like `log()` to append the `serviceName` but that seems to be overkill.)
(A lot of tests are testing logging behaviors which seem not necessary. However, I kept those test cases to minimize the PR.)
> grpclb: enhance grpclb logging

- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
alts requires netty-shaded, not netty.
----
This fixes the interop tests that are failing on grpc/grpc: https://source.cloud.google.com/results/invocations/df375b99-abd8-47e7-a044-2677adae9f42/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_alts/log
> interop-testing: Avoid alts incompatibility with netty

- netty/src/main/java/io/grpc/netty/InternalNettyChannelCredentials.java
- xds/src/main/java/io/grpc/xds/XdsChannelCredentials.java
- xds/src/main/java/io/grpc/xds/internal/sds/SdsProtocolNegotiators.java
- xds/src/test/java/io/grpc/xds/XdsSdsClientServerTest.java
> xds: implement XdsChannelCredentials

- xds/src/main/java/io/grpc/xds/EnvoyProtoData.java
- xds/src/main/java/io/grpc/xds/EnvoyServerProtoData.java
- xds/src/main/java/io/grpc/xds/XdsClientImpl2.java
- xds/src/test/java/io/grpc/xds/EnvoyServerProtoDataTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTestForListener.java
- xds/src/test/java/io/grpc/xds/XdsClientTestHelper.java
The comment in envoy/src/api/envoy/config/cluster/v3/cluster.proto line 896 mentions using "tls" as the name but the actual string is "envoy.transport_sockets.tls" as per the example on line 654 in the same file.
> xds: fix the transport-socket-name to match what control plane sends

- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
> xds: gate xDS timeout with env variable (v1.33.x backport)

- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
The main() Thread will call tearDown() itself. It appears this
redundancy has existed since e813eaae2f, where the normal error handling
was enhanced at the same time as cleaning up resource management. The
cleanup should have made it obvious the hook was no longer needed, but
alas. Technically, it did originally provide a purpose if setup()
failed, but it would have been better to just move setup() into the
try-catch instead. Today it doesn't even provide that purpose.
> interop-testing: Remove redundant tearDown() in hook

- alts/src/main/java/io/grpc/alts/internal/AltsAuthContext.java
- xds/src/main/java/io/grpc/xds/internal/rbac/engine/AuthorizationEngine.java
Migrate java proto map getter from get<field> to get<field>Map. 
This is part of a set of changes to java proto map API described here: go/java-proto-maplike
More information: go/java-proto-maplike-getFooMap
-----------
See internal cl/336170181
> alts: migrate java proto map getter from get<field> to get<field>Map

- xds/src/main/java/io/grpc/xds/CdsLoadBalancer.java
- xds/src/main/java/io/grpc/xds/EdsLoadBalancer2.java
- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java
Similar to https://github.com/grpc/grpc/pull/24200 in C-core's implementation. Watcher callbacks needs to be executed in its own channel SynchronizationContext. This is required for removing the SynchronizationContext in the XdsClient.
> xds: run watcher callbacks in its own channel synchronization context

- okhttp/build.gradle
Add missing exclusion of `Internal*` classes from okhttp javadoc, similar to [netty's](https://github.com/grpc/grpc-java/blob/master/netty/build.gradle#L46).
Javadoc for `1.33.0` was generated for `@Internal` public class I added [`InternalOkHttpChannelBuilder`](https://github.com/grpc/grpc-java/blob/0ec3bfb47167b86f0689a14ac824fbbdeafc8411/okhttp/src/main/java/io/grpc/okhttp/InternalOkHttpChannelBuilder.java#L22): https://grpc.github.io/grpc-java/javadoc/index.html?io/grpc/okhttp/InternalOkHttpChannelBuilder.html
> okhttp: exclude Internal* from javadoc

- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
The stream creation was failing because the stream id was disallowed:
```
Caused by: io.grpc.StatusRuntimeException: INTERNAL: http2 exception
at io.grpc.Status.asRuntimeException(Status.java:533)
at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:629)
... 16 more
Caused by: io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception$StreamException: Cannot create stream 222691 greater than Last-Stream-ID 222689 from GOAWAY.
```
The problem was introduced in 9ead606. Fixes #7357
> netty: Abrupt GOAWAY should not cause INTERNAL status

- xds/third_party/envoy/import.sh
- xds/third_party/envoy/src/main/proto/envoy/config/cluster/aggregate/v2alpha/cluster.proto
`ClusterConfig` specifies the list of cluster names within an aggregate cluster. Needed for aggregate cluster support.
> xds: import envoy proto envoy/config/cluster/aggregate/v2alpha/cluster.proto

- interop-testing/src/main/proto/grpc/testing/messages.proto
Mirror of https://github.com/grpc/grpc/pull/24569.
> interop-testing: only need to count total number of succeeded RPCs for accumulated stats in xDS tests

- xds/src/main/java/io/grpc/xds/AbstractXdsClient.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/XdsClientImpl2.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestV2.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTest2V2.java
V2 tests were deleted in  https://github.com/grpc/grpc-java/pull/7461. This adds one test each for ClientXdsClient and XdsClientImpl2 to partially address lack of test coverage
> xds: add a V2 test for CDS response with UpstreamTlsContext and fix the broken CDS response processing

- xds/src/main/java/io/grpc/xds/AbstractXdsClient.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/ServerXdsClient.java
- xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
- xds/src/test/java/io/grpc/xds/ServerXdsClientNewServerApiTest.java
- xds/src/test/java/io/grpc/xds/ServerXdsClientTest.java
The XdsClient will create its own SynchronizationContext internally. All of its work will be done inside that SynchronizationContext. Watcher callbacks need to be synchronized with the watching party (on client side this is done by scheduling the task back to client channel's SynchronizationContext).
> xds: use internal SynchronizationContext for XdsClient's synchronization

- xds/src/main/java/io/grpc/xds/ClientLoadCounter.java
- xds/src/main/java/io/grpc/xds/LoadStatsManager.java
- xds/src/main/java/io/grpc/xds/LoadStatsStoreImpl.java
A `LoadStatsStore` instance will be used for tracking stats for a global cluster, and multiple client channel may retrieve the same instance for recording loads sent to the same global cluster.
`ClientLoadCounter` is already thread-safe for recording loads, mostly are just document improvements.
> xds: make stats objects thread-safe

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/LoadReportClient.java
- xds/src/main/java/io/grpc/xds/XdsClientImpl2.java
- xds/src/test/java/io/grpc/xds/LoadReportClientTest.java
- xds/src/test/java/io/grpc/xds/XdsClientImplTest2.java
LoadReportClient is a subcomponent of XdsClient. #7559 makes the XdsClient use its internal SynchronizationContext, it calls LoadReportClient APIs in that SynchronizationContext. We can pass this SynchronizationContext to LoadReportClient for its synchronization usages as well.
> xds: use passed-in SynchronizationContext for load report client

- context/src/main/java/io/grpc/Deadline.java
- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/DelayedClientCall.java
In some Locale, floating-point number like `1,234.56` is formatted as `1.234,56`; and in some Locale, integers are formatted with non-ASCII decimal digits.
https://developer.android.com/reference/java/util/Locale.html#default_locale
> core: fix floating-point number formatting Locale

- rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
The `request` field is totally redundant because it is encoded in the CachedEntry already.
> rls: remove redundant request field in CachedRouteLookupResponse

- core/src/main/java/io/grpc/internal/GrpcUtil.java
- netty/src/main/java/io/grpc/netty/ClientTransportLifecycleManager.java
- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
With this, it will be clear if the RPC failed because the server didn't
use a double-GOAWAY or if it failed because of MAX_CONCURRENT_STREAMS or
if it was due to a local race. It also fixes the status code to be
UNAVAILABLE except for the RPCs included in the GOAWAY error (modulo the
Netty bug).
Fixes #5855
-----
This depends on #7501
> netty: Differentiate GOAWAY closure status descriptions

- api/src/main/java/io/grpc/ForwardingServerBuilder.java
- core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
- core/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java
- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
- core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
- core/src/test/java/io/grpc/internal/AbstractServerImplBuilderTest.java
- cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
Brings back `io.grpc.internal.AbstractManagedChannelImplBuilder` and `io.grpc.internal.AbstractServerImplBuilder` to the class hierarchy to fix broken ABI backward compatibility.
`AbstractManagedChannelImplBuilder` brought back as a copy of `ForwardingChannelBuilder` support pre-v1.33 binary interface, e.g. `io.grpc.netty.NettyChannelBuilder.maxInboundMessageSize(I)Lio/grpc/internal/AbstractManagedChannelImplBuilder;`
- Brings back `io.grpc.internal.AbstractManagedChannelImplBuilder` and `io.grpc.internal.AbstractServerImplBuilder` to the class hierarchy to fix broken ABI backward compatibility.
- Since `ForwardingServerBuilder` was introduced in v1.33.0, I changed it to `ForwardingServerBuilder<T extends ServerBuilder<T>>`. and made it package-private.
- Fixes #7552
- Partially undoes …
> Fix builders ABI backward compatibility broken in v1.33.0

- core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
- core/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java
- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
- core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
- core/src/test/java/io/grpc/internal/AbstractServerImplBuilderTest.java
- cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
* fix channel builders ABI backward compatibility broken in v1.33.0
* fix server builders ABI backward compatibility broken in v1.33.0
* makes ForwardingServerBuilder package-private
-----
This is a backport of #7564
> Fix builders ABI backward compatibility broken in v1.33.0 (v1.33.x backport)

- context/src/main/java/io/grpc/Deadline.java
- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/DelayedClientCall.java
In some Locale, floating-point number like `1,234.56` is formatted as `1.234,56`; and in some Locale, integers are formatted with non-ASCII decimal digits.
https://developer.android.com/reference/java/util/Locale.html#default_locale
---
This is a backport of #7473
> core: fix floating-point number formatting Locale (v1.33.x backport)

- okhttp/build.gradle
Add missing exclusion of `Internal*` classes from okhttp javadoc, similar to [netty's](https://github.com/grpc/grpc-java/blob/master/netty/build.gradle#L46).
Javadoc for `1.33.0` was generated for `@Internal` public class I added [`InternalOkHttpChannelBuilder`](https://github.com/grpc/grpc-java/blob/0ec3bfb47167b86f0689a14ac824fbbdeafc8411/okhttp/src/main/java/io/grpc/okhttp/InternalOkHttpChannelBuilder.java#L22): https://grpc.github.io/grpc-java/javadoc/index.html?io/grpc/okhttp/InternalOkHttpChannelBuilder.html
---
This is a backport of #7543
> okhttp: exclude Internal* from javadoc (v1.33.x backport)

- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
The stream creation was failing because the stream id was disallowed:
Caused by: io.grpc.StatusRuntimeException: INTERNAL: http2 exception
at io.grpc.Status.asRuntimeException(Status.java:533)
at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:629)
... 16 more
Caused by: io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception$StreamException: Cannot create stream 222691 greater than Last-Stream-ID 222689 from GOAWAY.
The problem was introduced in 9ead606. Fixes #7357
-----
This is a backport of #7501
> netty: Abrupt GOAWAY should not cause INTERNAL status (v1.33.x backport)

- xds/third_party/envoy/import.sh
- xds/third_party/envoy/src/main/proto/envoy/config/cluster/aggregate/v2alpha/cluster.proto
Previously we thought v2alpha was a separate version than v2, but it is same version of API. We need to support aggregate cluster for xDS v2 as well.
-------------
Manual revert of #7554 for the part deleted.
> xds: import v2 version of aggregate.ClusterConfig proto

- api/src/main/java/io/grpc/ServerCall.java
> api: Clarify expectations regarding ServerCall#close

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTest.java
#7427 changed to have xDS resource version info persist across ADS stream recreation so that the management server can choose to not send client resources that have already been sent previously (in the previous stream). It means the client should not consider previously received (resolved) resources not exist if it does not receive them on the new ADS stream. This PR fixes that.
> xds: only reschedule time for unresolved resources upon ADS stream restarts

- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java
Sending out server changes separately to unblock other languages' test client.
/cc @donnadionne @menghanl
> interop-testing: support rpc keep-open for xDS test server

- core/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
- core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
Round robin is keeping use of READY subchannels even if there is name resolution error. However, it moves Channel state to TRANSIENT_ERROR.
In hierarchical load balancers, the upstream LB policy may need to aggregate pickers from multiple downstream round_robin LB policy while filtering out non-ready subchannels. It cannot infer if the subchannel can be used just from the `SubchannelPicker` interface. It relies on the state that the round_robin intends to set channel to.
So the change is to match the readiness of the picker/subchannel with the state that round_robin tries to update. It will completely ignore name resolution error if there are READY subchannels.
/cc @zhangkun83
> core: round robin should ignore name resolution error for channel state change when there are READY subchannels

- benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadWorker.java
The behavior is as follows:
https://github.com/grpc/grpc-java/blob/59528d8efec465326b071ffc6f3f2220bcf641c9/benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadWorker.java#L136
(ServerConfig.port takes precedence if set).
grpc-go's documentation is clearer:
https://github.com/grpc/grpc-go/blob/02cd07d9bb5609fe76f8bb8d948037e79a8b29c7/benchmark/worker/main.go#L44
> LoadWorker: clarify the semantics of --server_port flag

- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestClient.java
My bad, forgot to complete the call.
> interop-testing: fix bug of not completing client configure RPC in xDS test client

- netty/src/main/java/io/grpc/netty/NettyServer.java
Adds the address we are attempting to bind to. This context is useful for tracking down errors in configuration.
> netty: Improve an exception message with more context.

- xds/src/main/java/io/grpc/xds/EdsLoadBalancer2.java
- xds/src/test/java/io/grpc/xds/EdsLoadBalancer2Test.java
This is a bug fix. Previously the EDS LB policies does not propagate an updated picker that uses the new circuit breaker threshold and drop policies when those values change. The result is new circuit breaker/drop policies are not dynamically applied to new RPCs unless subchannel state has changed.
> xds: immediately update picker when circuit breakers/drop policies change

- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestClient.java
- interop-testing/src/main/proto/grpc/testing/messages.proto
Mirrored proto change as https://github.com/grpc/grpc/pull/24703 and its corresponding change for the test client.
> interop-testing: aggregate accumulated stats by RPC methods in xDS test client

- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestClient.java
- interop-testing/src/main/proto/grpc/testing/messages.proto
This is something I found very confusing and error-prone.
The proto field is named as `num_failures` but its comment is saying it is for number of RPCs that failed to record a remote peer.
RPC failed == RPC failed to record a remote peer was true previously (so no existing tests should be affected by this changed) as server completed RPCs immediately. It is no longer true with server capability to keep the call open/delayed.
No change needed for implemented the circuit breaking test as it uses accumulated stats for test logic (connection warmup is not affected).
-----------
/cc @menghanl @donnadionne if other languages are also having this issue (you might be in a debug hell in the future with the existing semantics 😢 )
> interop-testing: fix wrong semantics for RPC failure stats in xDS test client

- xds/src/main/java/io/grpc/xds/EdsLoadBalancer2.java
- xds/src/main/java/io/grpc/xds/SharedCallCounterMap.java
- xds/src/test/java/io/grpc/xds/EdsLoadBalancer2Test.java
- xds/src/test/java/io/grpc/xds/SharedCallCounterMapTest.java
Use WeakReference to hold atomics. Circuit breaking will always be enabled, with the limit of per-cluster concurrent requests default to 1024. Each EDS LB policy will get or create the counter for aggregating outstanding requests sent through it at the time it is instantiated. This holds a strong reference to the counter (as well as the picker instance spawned). When the EDS LB policy and the picker instance are destroyed, strong references will be gone. Atomics will be GCed when strong references are gone and the global map will be cleaned up upon each call of `getOrCreate()`.
> xds: implement a global map for holding circuit breaker request counters

- examples/example-xds/README.md
- xds/src/main/java/io/grpc/xds/Bootstrapper.java
- xds/src/test/java/io/grpc/xds/XdsClientWrapperForServerSdsTestMisc.java
- xds/src/test/java/io/grpc/xds/XdsServerBuilderTest.java
While most languages support setting environment variables during runtime,
Java does not. In Java, the preferred approach is to use Java System Properties
in order so specify configuration options. By checking for the existence
of the io.grpc.xds.bootstrap property if GRPC_XDS_BOOTSTRAP is not found,
it is possible to either supply the bootstrap location during runtime or as
a Java argument. The environment variable still takes precedence in order
to not break any existing documentation.
For discussion see #7605 .
> xds: add support for setting bootstrap file with java system property

- buildscripts/kokoro/xds.sh
Enables xDS circuit breaking interop test for Java.
BTW, we'd better change the test client argument `--stats_port` to `--service_port` (or just `--port` or something better) as it is not just used for stats service now. But that change requires coordination for all languages and test driver. And we need to do it with two steps (add the new argument and then remove the old one). It's a bit annoying, we can live with it now.
> buildscripts: enable xDS circuit breaking test

- netty/src/main/java/io/grpc/netty/GrpcHttp2ConnectionHandler.java
- netty/src/main/java/io/grpc/netty/NettyAdaptiveCumulator.java
- netty/src/test/java/io/grpc/netty/NettyAdaptiveCumulatorTest.java
- netty/src/test/java/io/grpc/netty/NettyTestUtil.java
Creates "Adaptive" cumulator: cumulate ByteBuf's by dynamically switching between merge and compose strategies.
This cumulator applies a heuristic to make a decision whether to track a reference to the buffer with bytes received from the network stack in an array ("zero-copy"), or to merge into the last component (the tail) by performing a memory copy.
It is necessary as a protection from a potential attack on the COMPOSITE_CUMULATOR. Consider a pathological case when an attacker sends TCP packages containing a single byte of data, and forcing the cumulator to track each one in a separate buffer. In this case we'll be paying a memory overhead for each buffer, as well as extra compute to read the cumulation.
Implemented heuristic establishes a minimal threshold for the total size of the …
> netty: create adaptive cumulator

- android/src/main/java/io/grpc/android/AndroidChannelBuilder.java
- android/src/test/java/io/grpc/android/AndroidChannelBuilderTest.java
Related issue: #5610 
On Android, there is a race between making new RPCs and reconnecting after network comes back. If the former happens first, RPCs fail immediately. This is because resetConnectBackoff() does not update the picker before trying to reconnect and new RPCs are sent with the old picker, which fails RPCs immediately.
--------------
Note #7192 is open for enterIdle(). But that shouldn't affect the usage in AndroidChannelBuilder for reconnecting.
> android: make Channel always enterIdle upon network recover 

- alts/src/main/java/io/grpc/alts/internal/AltsHandshakerStub.java
This PR fixes bug described in https://github.com/grpc/grpc-java/issues/7622
> alts: create handshaker RPC lazily

- xds/build.gradle
The xds package is not at all pretty. There's lots of stuff leaking that
shouldn't. For the moment accept that and just clean up the javadoc.
This is a bit more important now because XdsChannelCredentials and
XdsServerBuilder will be exposed, so users will start noticing stuff
here. Unfortunately this change doesn't fix IDEs auto-suggesting classes
that users shouldn't use.
> xds: Filter Javadoc of "private" classes

- api/src/main/java/io/grpc/ForwardingServerBuilder.java
- xds/src/main/java/io/grpc/xds/XdsServerBuilder.java
This reduces ABI issues caused by returning the more precise
XdsServerBuilder in the API. See
https://github.com/grpc/grpc-java/issues/7552.
> api: Expose ForwardingServerBuilder for XdsServerBuilder

- api/src/main/java/io/grpc/ForwardingChannelBuilder.java
- api/src/main/java/io/grpc/ForwardingClientCall.java
- api/src/main/java/io/grpc/ForwardingServerBuilder.java
- api/src/main/java/io/grpc/ForwardingServerCall.java
all its methods belong to us
Ref https://github.com/grpc/grpc-java/pull/7633/files#r525631830
Fixing sources - that was a typo from copy paste of a copy paste
> core: fix typos in Forwarding* classes

- netty/src/main/java/io/grpc/netty/InternalNettyServerCredentials.java
- xds/src/main/java/io/grpc/xds/XdsServerBuilder.java
- xds/src/main/java/io/grpc/xds/XdsServerCredentials.java
- xds/src/main/java/io/grpc/xds/internal/sds/SdsProtocolNegotiators.java
- xds/src/test/java/io/grpc/xds/XdsSdsClientServerTest.java
Will remove the `useXdsSecurity*` methods from `XdsServerBuilder` in the next PR.
> xds: implement XdsServerCredentials

- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/HelloWorldServerXds.java
- xds/src/main/java/io/grpc/xds/XdsServerBuilder.java
- xds/src/test/java/io/grpc/xds/XdsSdsClientServerTest.java
- xds/src/test/java/io/grpc/xds/XdsServerBuilderTest.java
xds example with new API tested. This can be backported to 1.34...
> xds: remove temporary APIs and update xds example to use new ServerCreds

- api/src/main/java/io/grpc/ClientCall.java
If a ClientInterceptor implementation throws from `onClose`, the call will hang forever. This is a known issue, but issue appears unresolvable given the current API. So I'm adding guidance here for implementing `onClose`
> Added documentation for onClose hanging problem

- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/HelloWorldServerXds.java
- xds/src/main/java/io/grpc/xds/XdsServerBuilder.java
- xds/src/test/java/io/grpc/xds/XdsSdsClientServerTest.java
- xds/src/test/java/io/grpc/xds/XdsServerBuilderTest.java
> xds: remove temporary APIs and update xds example to use new ServerCreds (#7644) (v1.34.x backport)

- xds/src/main/java/io/grpc/xds/EdsLoadBalancer2.java
- xds/src/main/java/io/grpc/xds/SharedCallCounterMap.java
- xds/src/main/java/io/grpc/xds/XdsAttributes.java
- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/main/java/io/grpc/xds/XdsNameResolverProvider.java
- xds/src/test/java/io/grpc/xds/EdsLoadBalancer2Test.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
This is something I discussed with @ejona86 offline. It's better to obtain global resources in the resolver instead of in LB policies (similar to XdsClient). With that, the resolver has the control for what to be used by LB policies and maintaining this feature is easier for us.
> xds: obtain the global SharedCallCounterMap in the xDS resolver only

- xds/src/main/java/io/grpc/xds/AbstractXdsClient.java
> xds: fix mistake of taking wrong argument in log message (v1.34.x backport) (#7653)

- build.gradle
This PR fixes the problems during build due to deprecated html4 and html5 options in JDK 11 as mentioned in #7637.
> Remove deprecated javadoc options

- examples/example-xds/README.md
- examples/example-xds/build.gradle
- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/HelloWorldClientXds.java
- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/HelloWorldServerXds.java
- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/HostnameGreeter.java
- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/XdsHelloWorldClient.java
- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/XdsHelloWorldServer.java
--secure was moved to front since many languages need flags to precede
positional parameters, and we'd like other languages to use the same
flags when feasible.
:8000 was removed from xds: target in the README, as it isn't all that
useful and is confusing as xDS itself provides the backend port numbers.
> example-xds: Mirror helloworld and hostname example

- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/XdsHelloWorldClient.java
- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/XdsHelloWorldServer.java
The xds creds don't actually guarantee anything is secure. We don't want
to give new users a false impression.
-----
I inserted a new blank line to avoid needing to align the position argument descriptions with the flag description.
> example-xds: Change arg from --secure to --xds-creds

- buildscripts/kokoro/xds-k8s.cfg
- buildscripts/kokoro/xds-k8s.sh
To be used for testing new `xds-k8s` test job.
> buildscripts: Add xDS Kubernetes Interop tests buildscript placeholder

- api/src/main/java/io/grpc/InternalConfigSelector.java
- api/src/test/java/io/grpc/InternalConfigSelectorTest.java
- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/ConfigSelectingClientCall.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/ManagedChannelServiceConfig.java
- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
- core/src/test/java/io/grpc/internal/ConfigSelectingClientCallTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
Interceptor-based config selector will be needed for fault injection.
Add `interceptor` field to `InternalConfigSelector.Result`. Keep `callOptions` and `committedCallback` fields for the moment, because it needs a refactoring to migrate the existing xds config selector implementation to the new API.
> api,core: interceptor-based config selector

- examples/example-xds/README.md
- examples/example-xds/build.gradle
- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/HelloWorldClientXds.java
- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/HelloWorldServerXds.java
- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/HostnameGreeter.java
- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/XdsHelloWorldClient.java
- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/XdsHelloWorldServer.java
--secure was moved to front since many languages need flags to precede
positional parameters, and we'd like other languages to use the same
flags when feasible.
:8000 was removed from xds: target in the README, as it isn't all that
useful and is confusing as xDS itself provides the backend port numbers.
Backport of #7664
CC @voidzcy
> example-xds: Mirror helloworld and hostname example (1.34.x backport)

- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/XdsHelloWorldClient.java
- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/XdsHelloWorldServer.java
The xds creds don't actually guarantee anything is secure. We don't want
to give new users a false impression.
-----
I inserted a new blank line to avoid needing to align the position argument descriptions with the flag description.
Backport of #7668
> example-xds: Change arg from --secure to --xds-creds (1.34.x backport)

- examples/example-xds/README.md
- examples/example-xds/src/main/java/io/grpc/examples/helloworldxds/XdsHelloWorldClient.java
> xds: fix text in the readme and the comment about the --secure flag (#7676) (backport to 1.34.x)

- xds/src/main/java/io/grpc/xds/AbstractXdsClient.java
Currently xDS response messages are printed with protobuf JsonFormat as they may contain `Any`-type messages. JsonFormat internally uses Gson for generating human-readable message representations. The [default Gson instance](https://github.com/protocolbuffers/protobuf/blob/9ee163a5d77c99ba0ed64a9728d3963b4a240849/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L727) [escapes HTML characters](https://www.javadoc.io/doc/com.google.code.gson/gson/2.7/com/google/gson/GsonBuilder.html#disableHtmlEscaping--), which causes characters like '=' to be printed as '\u003d'. There is nothing can be done on our side to disable this as it is protobuf's internal implementation (https://github.com/protocolbuffers/protobuf/issues/7273).
To make the same content consistent in both request …
> xds: print xDS request messages with JsonFormat

- xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
- xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java
When all priorities fail, update the overall picker with the picker from the last priority. This still does not provide the full detail why all priorities fail but is better than nothing being provided currently.
> xds: provide more debug info for priority lb error-picker

- RELEASING.md
- buildscripts/build_docker.sh
- buildscripts/grpc-java-artifacts/Dockerfile
- buildscripts/make_dependencies.sh
- buildscripts/run_in_docker.sh
than nothing.
-----
Even if we don't want to do this in the future, I imagine this is "good enough"
for the moment just to fix the build.
> Build Linux artifacts using CentOS 7

- buildscripts/grpc-java-artifacts/Dockerfile
Re-sort packages, now that the tabs aren't skewing the sorting.
I'm quite confident I had fixed this already, but I had multiple copies
of this file on multiple machines and must have fixed the wrong copy.
> buildscripts: Fix grpc-java-artifacts indentation

- xds/build.gradle
We have been leaking classes since grpc-xds's inception. That's no good.
Lists are now sorted and use the same package names so they can be
easily compared. Excluding things like com/github/** is too aggressive,
and is unclear what is being targeted.
CC @dapengzhang0, @sanjaypujare
> xds: Add missing relocations and jacoco exclusions

- buildscripts/kokoro/android.sh
Issues like that fixed in 05048cf3 should have failed the CI, like it
does for the rest of the build (on both Travis and linux_artifacts).
> buildscripts: Check for out-of-date codegen after android builds

- RELEASING.md
- buildscripts/build_docker.sh
- buildscripts/grpc-java-artifacts/Dockerfile
- buildscripts/make_dependencies.sh
- buildscripts/run_in_docker.sh
than nothing.
-----
Backport of #7693
> Build Linux artifacts using CentOS 7 (1.34.x backport)

- buildscripts/kokoro/android.sh
- buildscripts/kokoro/unix.sh
It would be best if we can have our CIs cover as much as possible.
- Added coverage for `example/android/strictmode`, although it is most identical to helloworld.
- Added coverage for `examples/example-jwt-auth`.
- Added missing gradle build coverage for `examples/example-tls`.
> buildscripts: add missing CI coverage for examples

- buildscripts/kokoro/android.sh
Previously the android projects were separate from the main build and
each other. For quite a while now they have been integrated in the main
project. There's no longer any need to build each separately.
-------
That's assuming the gradle process doesn't OOM :smile:. But we'll learn
that quickly enough.
> buildscripts: Combine android builds together

- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestClient.java
- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java
Server-side channelz checks will be used in non-secure (baseline) interop tests as well.
> interop: add channelz to xds interop test server running in non-secure mode

- CONTRIBUTING.md
The CLA system swapped a while back and this was left behind.
CC @markdroth, @dfawley, as grpc and grpc-go repos have this same issue.
> CONTRIBUTING.md: Fix out-of-date CLA documentation

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/CallCredentialsApplyingTest.java
- core/src/test/java/io/grpc/internal/FakeCallCredentials.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
The addition of CompositeChannelCredentials allowed CallCredentials to
be passed to the ManagedChannel itself. But the implementation was buggy
and used the call creds for out-of-band channels as well, which is
inappropriate since they have a different authority.
This also fixes a bug where resolving OOB channels would have CallCreds
duplicated; that wasn't noticed or important because we don't use
CallCreds in OOB channels.
Fixes #7643
-----
Note that the originalTransportFactory usage vs oobTransportFactory usage is
subtle. If you use the wrong one then CallCreds are duplicated. That's not great,
but also not the worst thing that could happen.
> core: Don't leak CallCredentials into OOB channels

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/CallCredentialsApplyingTest.java
- core/src/test/java/io/grpc/internal/FakeCallCredentials.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
The addition of CompositeChannelCredentials allowed CallCredentials to
be passed to the ManagedChannel itself. But the implementation was buggy
and used the call creds for out-of-band channels as well, which is
inappropriate since they have a different authority.
This also fixes a bug where resolving OOB channels would have CallCreds
duplicated; that wasn't noticed or important because we don't use
CallCreds in OOB channels.
Fixes #7643
-----
Backport of #7712
> core: Don't leak CallCredentials into OOB channels (1.34.x backport)

- xds/build.gradle
We have been leaking classes since grpc-xds's inception. That's no good.
Lists are now sorted and use the same package names so they can be
easily compared. Excluding things like com/github/** is too aggressive,
and is unclear what is being targeted.
CC @dapengzhang0, @sanjaypujare 
Backport of #7702
> xds: Add missing relocations and jacoco exclusions (1.34.x backport)

- core/src/main/java/io/grpc/internal/Http2ClientStreamTransportState.java
Empty DATA frames with EOS tell a stronger tale as to where the server
may have its bug.
----
This is an alternative to #7277
CC @kmjung, @birenroy
> core: On unexpected EOS, mention whether the frame was empty

- rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
- rls/src/main/java/io/grpc/rls/LbPolicyConfiguration.java
Cleanup toString() for cache entries, and print more debug information about cache entry when `pickSubchannel()`. This will be more helpful to debug.
> rls: cleanup and minor enhancement for rls logging

- build.gradle
- examples/build.gradle
- examples/example-gauth/pom.xml
- examples/example-jwt-auth/build.gradle
- examples/example-jwt-auth/pom.xml
- examples/pom.xml
- okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
- repositories.bzl
I didn't touch Protobuf and Netty; we upgrade those individually. Below
are issues I encountered that caused me to not upgrade (further).
Guava 30.1-android fails to build with Android without enabling
desugaring. https://github.com/google/guava/issues/5358
Robolectric 4.4 breaks AndroidChannelBuilderTest.
https://github.com/grpc/grpc-java/issues/7731
Opencensus 0.28.1+ is incompatible with gRPC.
https://github.com/census-instrumentation/opencensus-java/issues/2069
https://github.com/grpc/grpc-java/issues/7732
Truth now defines the asm dependency as "compile" although it is still
optional. But asm appears to have accidentally included incorrect gradle
module metadata in their release (I see they've disabled the metadata on
master) which make gradle think it requires Java 8. We could asm …
> Bump versions for lots of dependencies

- android-interop-testing/build.gradle
- build.gradle
This silences many MutablePublicArray warnings that we can't do anything
about.
> android-interop-testing: ErrorProne should ignore generated R class

- alts/build.gradle
- core/src/test/java/io/grpc/internal/JndiResourceResolverTest.java
- examples/example-hostname/build.gradle
- examples/gradle/wrapper/gradle-wrapper.properties
- gradle/wrapper/gradle-wrapper.properties
- netty/shaded/build.gradle
- settings.gradle
- xds/build.gradle
- xds/src/test/java/io/grpc/xds/internal/sds/trust/SdsX509TrustManagerTest.java
Android plugins weren't touched, since they will need a lot more testing
when doing so.
-----
CC @sanjaypujare, it is generally wrong to depend on `sun.*` classes. ValidatorException extends CertificateException
> Bump Gradle and plugin versions

- stub/build.gradle
This resolves the following warning when building with JDK 8 introduced
in 9c5427fd4:
javadoc: warning - Error fetching URL: https://google.github.io/guava/releases/30.0-android/api/docs/
Guava is now building their Javadoc with JDK 11. JDK 11 swapped from
producing package-list to element-list, and stopped creating
package-list entirely. This file is what Javadoc uses to cross-link
documentation, and so it no longer works on the JDK 8 build, even though
the files have virtually the same contents.
ListenableFuture was the only reason we were including the Guava
Javadoc; let's just drop the link instead of worrying about this
silliness.
> stub: Stop linking to Guava Javadoc

- alts/build.gradle
- auth/build.gradle
- build.gradle
- interop-testing/build.gradle
After #7733, grpc-all has dependency conflicts for opencensus-api
```
> Task :grpc-all:dependencyInsight
Dependency resolution failed because of conflict(s) on the following module(s):
- io.opencensus:opencensus-api between versions 0.28.0 and 0.24.0
io.opencensus:opencensus-api:0.28.0
variant "runtime" [
org.gradle.status              = release (not requested)
org.gradle.usage               = java-runtime
org.gradle.libraryelements     = jar
org.gradle.category            = library
Requested attributes not found in the selected variant:
org.gradle.dependency.bundling = external
org.gradle.jvm.version         = 7
]
Selection reasons:
- By conflict resolution : between versions 0.28.0 and 0.24.0
io.opencensus:opencensus-api:0.28.0
\--- project :grpc-testing
\--- runtimeClasspath …
```
> all: Fix opencensus-api dependency conflict

- core/src/main/java/io/grpc/internal/DelayedClientTransport.java
- core/src/main/java/io/grpc/internal/DelayedStream.java
- core/src/main/java/io/grpc/internal/MetadataApplierImpl.java
- core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java
- core/src/test/java/io/grpc/internal/DelayedStreamTest.java
Reverts grpc/grpc-java#7720 
in favor of alternative https://github.com/grpc/grpc-java/pull/7743 to fix the same problem.
> Revert " check pending stream completion at delayed transport lifecycle"

- api/src/main/java/io/grpc/ChannelCredentials.java
- api/src/main/java/io/grpc/ChoiceChannelCredentials.java
- api/src/main/java/io/grpc/CompositeChannelCredentials.java
- api/src/main/java/io/grpc/LoadBalancer.java
- api/src/main/java/io/grpc/TlsChannelCredentials.java
- api/src/test/java/io/grpc/ChoiceChannelCredentialsTest.java
- api/src/test/java/io/grpc/CompositeChannelCredentialsTest.java
- api/src/test/java/io/grpc/InsecureChannelCredentialsTest.java
- api/src/test/java/io/grpc/ManagedChannelRegistryTest.java
- api/src/test/java/io/grpc/TlsChannelCredentialsTest.java
- core/src/main/java/io/grpc/util/ForwardingLoadBalancerHelper.java
- netty/src/main/java/io/grpc/netty/NettyChannelCredentials.java
- netty/src/test/java/io/grpc/netty/NettyChannelCredentialsTest.java
- netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
- okhttp/src/main/java/io/grpc/okhttp/SslSocketFactoryChannelCredentials.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpChannelBuilderTest.java
- okhttp/src/test/java/io/grpc/okhttp/SslSocketFactoryChannelCredentialsTest.java
API change (See go/grpc-rls-callcreds-to-server):
- Add `ChannelCredentials.withoutBearerTokens()`
- Add `createResolvingOobChannelBuilder(String, ChannelCredentials)`, `getChannelCredentials()` and `getUnsafeChannelCredentials()` for `LoadBalancer.Helper`
This PR does not include the implementation of `createResolvingOobChannelBuilder(String, ChannelCredentials)`.
> all: ChannelCredentials.withoutBearerTokens() and LoadBalancer.Helper API change

- buildscripts/kokoro/xds-k8s-install-test-driver.sh
- buildscripts/kokoro/xds-k8s.cfg
- buildscripts/kokoro/xds-k8s.sh
- buildscripts/xds-k8s/cloudbuild.yaml
- buildscripts/xds-k8s/logging-debug.properties
- buildscripts/xds-k8s/logging-json.properties
- buildscripts/xds-k8s/logging.properties
- buildscripts/xds-k8s/test-client.Dockerfile
- buildscripts/xds-k8s/test-server.Dockerfile
- interop-testing/build.gradle
Buildscript for xDS Kubernetes Interop security tests.
- Test Driver: https://github.com/grpc/grpc/tree/master/tools/run_tests/xds_k8s_test_driver#basic-usage
- Invocation examples (commit sha): [`225ab7b`](https://source.cloud.google.com/results/invocations/f68ccd84-b763-4363-86da-82ae98a0dd12/targets),  [`016af9e07`](https://source.cloud.google.com/results/invocations/7f31b781-3dd3-4c0a-9f77-b685d4bd8dd8/targets), [`9d60157`](https://source.cloud.google.com/results/invocations/0d65ffca-a946-48a6-991e-50260ba3f234/targets)
- Ref [Shell Style Guide](https://google.github.io/styleguide/shellguide.html)
> buildscripts: xDS Kubernetes Interop tests buildscript

- buildscripts/kokoro/xds-k8s-install-test-driver.sh
- buildscripts/kokoro/xds-k8s.cfg
- buildscripts/kokoro/xds-k8s.sh
- buildscripts/xds-k8s/cloudbuild.yaml
- buildscripts/xds-k8s/logging-debug.properties
- buildscripts/xds-k8s/logging-json.properties
- buildscripts/xds-k8s/logging.properties
- buildscripts/xds-k8s/test-client.Dockerfile
- buildscripts/xds-k8s/test-server.Dockerfile
- interop-testing/build.gradle
Buildscript for xDS Kubernetes Interop security tests.
- Test Driver: https://github.com/grpc/grpc/tree/master/tools/run_tests/xds_k8s_test_driver#basic-usage
- Invocation examples (commit sha): [`225ab7b`](https://source.cloud.google.com/results/invocations/f68ccd84-b763-4363-86da-82ae98a0dd12/targets),  [`016af9e07`](https://source.cloud.google.com/results/invocations/7f31b781-3dd3-4c0a-9f77-b685d4bd8dd8/targets), [`9d60157`](https://source.cloud.google.com/results/invocations/0d65ffca-a946-48a6-991e-50260ba3f234/targets)
- Ref [Shell Style Guide](https://google.github.io/styleguide/shellguide.html)
---
This is a backport of #7670 (buildscript placeholder), #7742 (buildscript implementation)
> buildscripts: xDS Kubernetes Interop tests buildscript (v1.34.x backport)

- api/src/main/java/io/grpc/Status.java
> api: Improve code clarity by using Arrays.copyOf()

- core/src/main/java/io/grpc/internal/DelayedClientTransport.java
- core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java
There was a report from a user in b/176088054 that experienced an RPC
waiting_for_connection that failed after 45 minutes due to deadline.
That would be quite normal for wait-for-ready, but because we didn't
include that detail in the status we have to do code inspection to
determine if wait-for-ready was enabled.
CC @zhangkun83
> core: Include wait-for-ready in deadline exceeded insights

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
A bug was introduced in #7696 for processing CDS responses.
Upon receiving a CDS response (state of the world), EDS resources no longer referenced by CDS resources in the latest response should be removed. Every EDS resource is referenced by some CDS resource either by appearing as its `edsServiceName` field or has the same name as the CDS resource if `edsServiceName == null`. #7696 did not retain EDS resources that has the same name as CDS resources.
> xds: fix regression for deleting EDS resources referenced by unchanged CDS resources

- interop-testing/build.gradle
- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestClient.java
- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java
Backport of xDS Security support for XdsTestServer and XdsTestClient. 
- b5330f8 / interop: create PSM security xDS interop tests - server & client #7609
- f6a7880 / interop-testing: rename XdsTestClient secure_mode argument #7665
- badf703 / interop: add channelz and reflection support to xds interop test client and server #7701
- 385f36c / interop: add channelz to xds interop test server running in non-secure mode #7710
> interop: create PSM security xDS interop tests - server & client (v1.34.x backport)

- xds/src/main/java/io/grpc/xds/ServerXdsClient.java
- xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
- xds/src/main/java/io/grpc/xds/XdsServerBuilder.java
- xds/src/main/java/io/grpc/xds/internal/sds/ServerWrapperForXds.java
- xds/src/test/java/io/grpc/xds/XdsServerBuilderTest.java
- check to allow XdsServerBuilder.build() only once
- add transportBuilder() to XdsServerBuilder
- remove "grpc/server" hardcoding
- reorder the shutdown of delegate and xdsClient as per new design
CC @ejona86
> xds: multiple changes needed for PSM security GA as discussed

- xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java
- xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
- xds/src/main/java/io/grpc/xds/WeightedTargetLoadBalancer.java
- xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/ClusterManagerLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/WeightedTargetLoadBalancerTest.java
Delaying `handleResolvedAddresses()` for propagating configs to the child LB policy can be problematic. For example, if channel shutdown has been enqueued when calling child policy's `handleResolvedAddresses()` is being enqueued (e.g., receiving updates from XdsClient), it should not be executed. Otherwise, subchannels may be created by LBs that have already been shut down.
We should follow the convention that never delay update/error propagation to downstream LB policies. To avoid reentrancy of downstream LB policies calling `updateBalancingState()` in-place, LB policy implementations can wrap the helper to delay such upcalls.
In the existing implementation, such problem exists in LB policies that manages a group of child policies. Specifically they are `ClusterManagerLoadBalancer` …
> xds: fix LB policy address and balancing state update propagations

- android-interop-testing/build.gradle
Fixes bug introduced by #7781.
> android-interop-testing: fix wrong instrumented test runner

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
- xds/src/main/java/io/grpc/xds/EdsLoadBalancer2.java
- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/EdsLoadBalancer2Test.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
It's common in xDS for passing around configurations, which are (effectively) immutable. In most cases, those configuration instances are created by internal implementations and used internally as well. As configurations become complicated, getters and builders are verbose. They contribute to a significant amount of trivial code (e.g., adding one field requires adding one getter and one setter on builder). In #7696, CdsUpdate is extended to represent a complex combination of cluster types and usages of the data structure are non-homogenous. It would be extremely cumbersome to use getters and builder(s) for such cases. So to make data types consistent (on XdsClient interface) and reduce the verbosity of usage, this change eliminates getters and builders for xDS updates on XdsClient …
> xds: clean up verbose getters and builders on XdsClient interface

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
A bug was introduced in the previous change for processing CDS responses. It mistakenly deleted EDS resources valid still referenced by CDS resources. EDS resource names either appear as the edsServiceName for CDS resources or has the same name as the CDS resources whose edsServiceName is null.
In the previous change, EDS resources having the same name as CDS resources are not retained. This caused LB subtrees for those EDS resources are shut down mistakenly, leading to RPC fails.
---------------------------
Backport of #7778
> xds: fix regression for deleting EDS resources referenced by unchanged CDS resources (v1.35 backport)

- xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java
- xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
- xds/src/main/java/io/grpc/xds/WeightedTargetLoadBalancer.java
- xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/WeightedTargetLoadBalancerTest.java
Delaying handleResolvedAddresses() for propagating configs to the child LB policy can be problematic. For example, if channel shutdown has been enqueued when calling child policy's handleResolvedAddresses() is being enqueued (e.g., receiving updates from XdsClient), it should not be executed. Otherwise, subchannels may be created by LBs that have already been shut down.
This change fixes LB config propagations in LB policies that manage a group of child LBs and delay the propagation for avoiding reentrancy. LB policies will always directly propagate child LB config/addresses updates directly. On the other hand, upcalls from child LB policies for balancing state updates will be queued and executed later.
------------------
Backport of #7772
> xds: fix LB policy address and balancing state update propagations (v1.35 backport)

- xds/src/main/java/io/grpc/xds/internal/sds/ServerWrapperForXds.java
@ejona86 one of the items in the TODOs we discussed.
> xds: reorder the shutdown of delegate and xds-client for better semantics of ServerWrapperForXds

- netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java
- netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
@ejona86 Could you help to review this PR?
Enable this feature by setting the system property in command argument
```
-Dio.netty.ssl.masterKeyHandler=true
```
or in java code
```java
System.setProperty(SslMasterKeyHandler.SYSTEM_PROP_KEY, "true");
```
The keys will be written to the log named "io.netty.wireshark" in the warnning level. To export the keys to a file, you can configure log factory like: (log4j.xml for example)
```xml
...
<appender name="key-file" class="org.apache.log4j.RollingFileAppender">
<param name="file" value="d:/keyfile.txt"/>
<layout class="org.apache.log4j.PatternLayout">
<param name="ConversionPattern" value="%m%n"/>
</layout>
</appender>
<category name="io.netty.wireshark">
<priority value="DEBUG" />
<appender-ref ref="key-file" />
</category>
...
```
Wireshark …
> Add exporting SSL/TLS master key log feature

- api/src/main/java/io/grpc/LoadBalancer.java
- api/src/test/java/io/grpc/LoadBalancerTest.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/util/ForwardingLoadBalancerHelper.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- core/src/test/java/io/grpc/internal/PickFirstLoadBalancerTest.java
- core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
- rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
- rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
- services/src/test/java/io/grpc/services/HealthCheckingLoadBalancerFactoryTest.java
- xds/src/test/java/io/grpc/xds/CdsLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/EdsLoadBalancer2Test.java
- xds/src/test/java/io/grpc/xds/OrcaOobUtilTest.java
Delete a bunch of old LoadBalancer.Helper APIs that had been deprecated for a long time.
- `createSubchannel(EquivalentAddressGroup addrs, Attributes attrs)`
`createSubchannel(List<EquivalentAddressGroup> addrs, Attributes attrs)`
Deprecated in #5722 (v1.22)
- `updateSubchannelAddresses(Subchannel subchannel, EquivalentAddressGroup addrs)`
`updateSubchannelAddresses(Subchannel subchannel, List<EquivalentAddressGroup> addrs)`
Deprecated in #5802 (v1.22)
These deprecated APIs has stronger implementation requirement for synchronization as they originally did not require invocations to be from the SynchronizationContext (although a logged warning was added later if detected the call is not from the SynchronizationContext). Their replacements relaxed the burden for implementations to be …
> api: delete LoadBalancer.Helper APIs that had been deprecated for a long time

- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceServer.java
`$ ./run-test-server.sh --use_tls=false --port=2,3`
`$ ./run-test-server.sh --use_tls=false --port=8080`
```
$ ./run-test-server.sh --use_tls=false --port=2,2
Exception in thread "main" java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:2
at io.grpc.netty.NettyServer.start(NettyServer.java:328)
at io.grpc.internal.ServerImpl.start(ServerImpl.java:179)
at io.grpc.internal.ServerImpl.start(ServerImpl.java:90)
at io.grpc.testing.integration.TestServiceServer.start(TestServiceServer.java:165)
at io.grpc.testing.integration.TestServiceServer.main(TestServiceServer.java:68)
Caused by: java.net.BindException: Address already in use
at sun.nio.ch.Net.bind0(Native Method)
at sun.nio.ch.Net.bind(Net.java:433)
at sun.nio.ch.Net.bind(Net.java:425)
at …
```
> interop-testing: allow multiple port in test server

- api/src/main/java/io/grpc/ManagedChannelBuilder.java
Multiple users have tried things like
`mcb.enableRetry().maxRetryAttempts(3)` and been confused when no
retries were performed. Providing a reference to the gRFC and
`defaultServiceConfig()` should greatly increase the clarity of how to
use the method.
> api: Reword retry javadoc to make clear service config is source of configuration

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
Throw for subchannel creation if the channel is being shutting down and the delayed transport is terminated (aka, all retry calls has been finished). 
This enforces a tighter timing restriction on load balancer implementations to ensure no subchannel should be created after the balancer itself has been shut down. A load balancer implementation may not always check its state before creating new subchannels. They can be out of sync when the subchannel creation is queued and executed later. We had run into exceptions below in xDS where [PriorityLoadBalancer enqueues addresses propagation to its child policy](https://github.com/grpc/grpc-java/blob/1a3db6701385ecfd8122b7093bc7b73ae5393c42/xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java#L251-L270) (to avoid reentrancy by …
> core: make subchannel creation timing restriction stricter

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
As promised in https://github.com/grpc/grpc-java/pull/7790#issuecomment-759142113, this cleans up leftovers after #7793. We can close #5015 after this gets merged.
> core: further clean up leftovers in ManagedChannelImpl's LoadBalancer.Helper and Subchannel implementations

- xds/build.gradle
- xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
- xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
- xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
- xds/src/main/java/io/grpc/xds/InternalXdsAttributes.java
- xds/src/main/java/io/grpc/xds/LrsLoadBalancer.java
- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/main/java/io/grpc/xds/internal/sds/SdsProtocolNegotiators.java
- xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
- xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/LrsLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
- xds/src/test/java/io/grpc/xds/XdsSdsClientServerTest.java
- xds/src/test/java/io/grpc/xds/internal/sds/SdsProtocolNegotiatorsTest.java
The real change is in `XdsAttributes` -> `InternalXdsAttributes`.
> xds: make XdsAttributes really public internal

- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
If all RR servers are unhealthy, it's possible that at least one
connection is CONNECTING at every moment which causes RR to stay in
CONNECTING. It's better to keep the TRANSIENT_FAILURE state in that
case so that fail-fast RPCs can fail fast.
The same changes have been made for RoundRobinLoadBalancer in #6657
> grpclb: keep RR Subchannel state in TRANSIENT_FAILURE until becoming READY

- .gitignore
- buildscripts/grpc-java-linux-arm64-tests/Dockerfile
- buildscripts/grpc-java-linux-arm64-tests/build_and_run_tests.sh
- buildscripts/run_arm64_tests_in_docker.sh
Not ready to merge, but demonstrates a neat way how to test grpc-java on x86 using a docker container and ARM emulator with just a few commands.
FTR I tried this on my linux workstation and the entire build & tests took ~40mins (which is reasonable considering the fact that the ARM environment is being emulated).
CC @ejona86
> Add a simple way to run grpc-java test inside emulated ARM64 docker container

- testing/src/main/java/io/grpc/internal/testing/TestUtils.java
(As discussed offline)
Currently concrypt doesn't offer an ARM version of the native components, so running Http2OkHttpTest ends up with a failure when ran on an ARM machine (which pollutes the otherwise green test results).
```
> Task :grpc-interop-testing:test
[jetty-alpn-agent][ warn] Could not parse java.version: 11.0.9.1
[jetty-alpn-agent][ warn] Could not find a matching alpn-boot jar for Java version: 11.0.9.1
io.grpc.testing.integration.Http2OkHttpTest > classMethod FAILED
java.lang.RuntimeException: Could not create Conscrypt provider
at io.grpc.internal.testing.TestUtils.installConscryptIfAvailable(TestUtils.java:198)
at io.grpc.testing.integration.Http2OkHttpTest.loadConscrypt(Http2OkHttpTest.java:66)
Caused by:
java.lang.reflect.InvocationTargetException
at …
```
> make io.grpc.testing.integration.Http2OkHttpTest pass on ARM

- alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java
- alts/src/test/java/io/grpc/alts/internal/GoogleDefaultProtocolNegotiatorTest.java
A bug was introduced in #7783 that made google_default creds select ALTS for connections to TD (should be TLS instead), which cased recent CI failures. More specifically, [`!"google_cfe".equals(grpcHandler.getEagAttributes().get(clusterNameAttrKey))`](https://github.com/grpc/grpc-java/blob/1b23cf4f39ab26728336edbda8bb6af22dfe0a01/alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java#L251) is the buggy line that oversees the case for TD's address.
> xds: google_default should use TLS if address contains no cluster name 

- buildscripts/kokoro/xds.sh
Didn't notice there is `set -u` in xds.sh.
Failure:
http://sponge2.corp.google.com/3224b1bd-d6b2-472d-b8ae-4e61898de598
Manual test of the fix:
https://sponge2.corp.google.com/df820274-0ff0-4d9b-aaf8-8528437e0f93
> buildscripts: fix buildscript unbound variable error

- xds/src/main/java/io/grpc/xds/Bootstrapper.java
- xds/src/main/java/io/grpc/xds/BootstrapperImpl.java
- xds/src/main/java/io/grpc/xds/SharedXdsClientPoolProvider.java
- xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
- xds/src/main/java/io/grpc/xds/internal/sds/TlsContextManagerImpl.java
- xds/src/test/java/io/grpc/xds/BootstrapperImplTest.java
Split Bootstrapper into Bootstrapper interface and BootstrapperImpl. Bootstrapper's implementation is getting complicated, the way how its code is organized gets bad for readability and testing. Also, having the singleton instance on Bootstrapper itself does not provide any benefit. The singleton `SharedXdsClientProvider` is already making use of a single Bootstrapper instance. We would still want Bootstrapper mockable as using a real instance in its consumer's tests is cumbersome. So we make Bootstrapper as an interface and implement a separate concrete implementation BootstrapperImpl. This is quite similar to NameResolver and DnsNameResolver.
> xds: refactor Bootstrapper

- buildscripts/kokoro/xds_v3.sh
Manual test:
http://sponge2/63654a23-efdd-4acd-a274-ecf67856968b
> buildscripts: fix execution path of xds.sh in xds_v3.sh

- core/src/main/java/io/grpc/internal/DelayedClientTransport.java
- core/src/main/java/io/grpc/internal/DelayedStream.java
- core/src/main/java/io/grpc/internal/MetadataApplierImpl.java
- core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java
- core/src/test/java/io/grpc/internal/DelayedStreamTest.java
DelayedClientTransport needs to avoid becoming terminated while it owns
RPCs. Previously DelayedClientTransport could terminate when some of its
RPCs had their realStream but realStream.start() hadn't yet been called.
To avoid that, we now make sure to call realStream.start()
synchronously with setting realStream. Since start() and the method
calls before start execute quickly, we can run it in-line. But it does
mean we now need to split the Stream methods into "before start" and
"after start" categories for queuing.
Fixes #6283
CC @voidzcy
> core: DelayedStream should start() real stream immediately

- xds/src/main/java/io/grpc/xds/BootstrapperImpl.java
- xds/src/test/java/io/grpc/xds/BootstrapperImplTest.java
- xds/src/test/java/io/grpc/xds/XdsClientWrapperForServerSdsTestMisc.java
- xds/src/test/java/io/grpc/xds/XdsServerBuilderTest.java
Currently, gRPC uses the `GRPC_XDS_BOOSTRAP` env variable to find the bootstrap file. There are use cases where file based bootstrap config is not optimal like when a file system is not mounted. We want to have an option to input bootstrap config directly via an env variable. This change supports reading the bootstrap config from the following places (in order):
- If `GRPC_XDS_BOOTSTRAP` exists then use its value as the name of the bootstrap file. If the file is missing or the contents of the file are malformed, return an error.
- Else if `io.grpc.xds.bootstrap` exists then use its value as the name of the bootstrap file. If the file is missing or the contents are malformed, return an error.
- Else, if `GRPC_XDS_BOOTSTRAP_CONFIG` exists then use its value as the bootstrap config. If the …
> xds: support reading bootstrap config directly from env var or system property values

- buildscripts/kokoro/xds.cfg
- buildscripts/kokoro/xds_v3.cfg
We have lots more test cases now, and we've been seeing the average run time creep towards 90 minutes - which means we've gotten some failure when test teardown hasn't completed by then and the VM is terminated.
> buildscripts: increase xds job timeouts

- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java
For testing xds timeout support.
Tested by running interop tests manually with and without `rpc-behavior:"sleep-N"` metadata set.
> interop-testing: support rpc sleep behavior for xDS test server

- core/build.gradle
This provides us a path forward with #7211 (hiding
AbstractManagedChannelImplBuilder and AbstractServerImplBuilder) while
providing users a migration path to manage the ABI breakage (#7552). We
do a .class hack so that recompiling avoids the internal class reference
yet the old methods are still available.
Leaving the classes as-is causes javac to compile two versions of each
method, one returning the public class (e.g. ServerBuilder) and one
returning the internal class (e.g., AbstractServerImplBuilder). However,
we rewrite the signature that is used at compile time so that new
compilations will not reference internal-returning methods.
This is intended to be temporary, just to give a migration path. Once we
have given users some time to recompile we will remove this rewriting
and change …
> core: Rewrite builder class signatures to avoid internal class

- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestClient.java
- interop-testing/src/main/proto/grpc/testing/messages.proto
Implements test client's support for xDS timeout test.
- Synced xDS test proto messages with [grpc-proto](https://github.com/grpc/grpc-proto/blob/master/grpc/testing/messages.proto).
- Changed `RpcConfig` to be the configuration for per test method type. Added `timeoutSec` for its deadline configuration.
- Changed accumulated stats to include RPC status instead of just succeeded/failed.
Go's implementation: https://github.com/grpc/grpc-go/pull/4156, https://github.com/grpc/grpc-go/pull/4157
> interop-testing: implement test client support for xDS timeout test

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/EnvoyProtoData.java
- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientV2Test.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientV3Test.java
- xds/src/test/java/io/grpc/xds/EnvoyProtoDataTest.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
Parse [HTTPFault](https://github.com/envoyproxy/envoy/blob/18db4c90e3295fb2c39bfc7b2ce641cfd6c3fbed/api/envoy/extensions/filters/http/fault/v3/fault.proto#L57) from 3 possible places:
- HttpFilters in HttpConnectionManager in LDS response
- `EnvoyProtoData.HttpFault` will be a field of `LdsUpdate`
- TypedPerFilterConfigMap in VirtualHost
- `EnvoyProtoData.HttpFault` will be a field of `EnvoyProtoData.VirtualHost`
- TypedPerFilterConfigMap in Route
- `EnvoyProtoData.HttpFault` will be a field of `EnvoyProtoData.Route`
- TypedPerFilterConfigMap in ClusterWeight
- `EnvoyProtoData.HttpFault` will be a field of `EnvoyProtoData.ClusterWeight`
Design doc: https://github.com/grpc/proposal/pull/201
> xds: parse HttpFault filter from LDS/RDS response

- core/src/main/java/io/grpc/internal/DelayedStream.java
- core/src/test/java/io/grpc/internal/DelayedStreamTest.java
More delayedStream tests related to #7750 as promised in #7749, where we changed to call realStream.start() synchronously with setting realStream.
> core: add more delayedStream tests

- api/src/main/java/io/grpc/InternalChannelz.java
- services/src/main/java/io/grpc/services/ChannelzService.java
- services/src/test/java/io/grpc/services/ChannelzServiceTest.java
Add support for `grpc.channelz.v1.Channelz.GetServer`, as defined in [`channelz.proto`](https://github.com/grpc/grpc-proto/blob/f5c9cf6eecbe948b8744bd0398a1ddc937ec5237/grpc/channelz/v1/channelz.proto#L429-L430):
```proto
// Returns a single Server, or else a NOT_FOUND code.
rpc GetServer(GetServerRequest) returns (GetServerResponse);
```
> services: add support for channelz.GetServer()

- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
See this PR in netty: https://github.com/netty/netty/pull/9798 . It's possible that one peer has closed the stream, yet another frame from peers arrives after it. This is largely harmless, as explained in the PR from netty repository. If we don't do this, the log will be polluted with these harmless logs.
> Log expected STREAM_CLOSED exceptions for already closed streams at FINE level

- xds/src/main/java/io/grpc/xds/BootstrapperImpl.java
- xds/src/test/java/io/grpc/xds/BootstrapperImplTest.java
Broken by #7863.
Previously this is done in Locality creation. We could also do it, but would be better to just use empty strings outside explicitly.
> xds: be tolerant for unspecified locality fields in bootstrap

- rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
RLS RPC deadline is configured by service config, and could be extremely long. When RLS lb is shutdown, any pending RLS PRC should be cancelled. Now using `shutdownNow()` to forcefully close the RLS channel.
> rls: forcefully close rls channel when lb is shutdown

- rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
- rls/src/main/java/io/grpc/rls/RlsRequestFactory.java
- rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
- rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
- rls/src/test/java/io/grpc/rls/RlsRequestFactoryTest.java
The server filed in lookup request as specified in go/dynamic-request-routing/#heading=h.eqjtcpo6u8ep should be the original target, not the RLS server where the lookup request is sent to.
(It was wrong from the beginning of java implementation. In the past, we made a [hack](https://github.com/dapengzhang0/grpc-java/commit/021d33a240ee0d1d14e8e49a73d87cc7fa39433b) for testing, because it worked only for "test-directpath.cloudbigtable.sandbox.....", and did not work with the original target either.)
> rls: fix wrong server field in lookup request

- RELEASING.md
- buildscripts/build_docker.sh
- buildscripts/grpc-java-artifacts/Dockerfile
- buildscripts/make_dependencies.sh
- buildscripts/run_in_docker.sh
than nothing.
---------------
Backport of #7693.
> Build Linux artifacts using CentOS 7 (1.31.x backport)

- RELEASING.md
- buildscripts/build_docker.sh
- buildscripts/grpc-java-artifacts/Dockerfile
- buildscripts/make_dependencies.sh
- buildscripts/run_in_docker.sh
than nothing.
------------
Backport of #7693.
> Build Linux artifacts using CentOS 7 (1.32.x backport)

- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
[JsonUtil](https://github.com/grpc/grpc-java/blob/b1daad6f30f064d8b1fd423fc9051fc345cb310f/core/src/main/java/io/grpc/internal/JsonUtil.java#L108-L111) is expecting numbers from parsed JSON string to be `Double`.
--------------
This should the fix interop header matching test failure.
TODO: Need to backport to 1.31 as well.
> xds: fix wrong number type for generated raw config

- all/build.gradle
- bom/build.gradle
- rls/build.gradle
Making `io.grpc:grpc-rls` a maven artifact from next release.
> all: publish grpc-rls

- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
JsonUtil is expecting numbers in Map<String, ?> to be Double. The generated raw config (Ma<String, ?>) should use Double for numerical values put into it.
-------------
Backport of #7880
> xds: fix wrong number type for generated raw config (1.31.x backport)

- api/src/main/java/io/grpc/Status.java
At the moment `Status.trailersFromThrowable()` does not play well with Kotlin since compiler treats this functions as a null safe even though it is not.
> api: Add nullable annotation to trailersFromThrowable

- rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
- rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
The previous fix #7878 didn't work because the [server field](http://go/dynamic-request-routing/#heading=h.eqjtcpo6u8ep) is expected to be full hostname (without port number). Need strip the port part from the authority.
> rls: fix wrong server field in lookup request again

- buildscripts/kokoro/xds.cfg
> buildscripts: increase xds job timeouts (backport to 1.34.x of #7831)

- xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
- xds/src/main/java/io/grpc/xds/XdsServerBuilder.java
- xds/src/main/java/io/grpc/xds/internal/sds/ServerWrapperForXds.java
- xds/src/test/java/io/grpc/xds/XdsClientWrapperForServerSdsTestMisc.java
- xds/src/test/java/io/grpc/xds/XdsServerBuilderTest.java
This implements parts of the new gRFC (https://github.com/grpc/proposal/pull/214) esp the XdsServingStatusListener. Note that the server restart part is coming as a separate PR. 
cc @ejona86
> xds: Implement XdsServingStatusListener as per the new xDS server gRFC

- interop-testing/src/main/java/io/grpc/testing/integration/AltsHandshakerTestService.java
https://travis-ci.org/github/grpc/grpc-java/jobs/758605192
```
io.grpc.testing.integration.AltsHandshakerTest > testAlts FAILED
io.grpc.StatusRuntimeException: UNKNOWN
at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:624)
at io.grpc.testing.integration.AltsHandshakerTest.testAlts(AltsHandshakerTest.java:98)
Caused by:
io.grpc.netty.shaded.io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Invalid header field: frame size too small
at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(B …
```
> interop-testing: fix alts handshaking race

- alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java
- alts/src/main/java/io/grpc/alts/internal/AsyncSemaphore.java
- alts/src/main/java/io/grpc/alts/internal/TsiHandshakeHandler.java
The handshake limit is more a property of ALTS than TSI. This allows
other TSI implementations to accept a high connection rate (b/179376431)
---
Mostly just rearranging code.
> alts: Make concurrent handshake limit part of ALTS instead of TSI

- xds/build.gradle
attempt to fix #7703:
Create a new Gradle task depends on shadowJar. It examines the outputs of shadowJar package prefix to make sure it is inside within the package.
> xds: add proto leakage check at gradle build

- rls/build.gradle
- rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
- rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
The `serviceName` field in oobChannel grpclb config should not be null, otherwise it will default to the `lbHelper.getAuthority()`, which perviously defaulted to the lookup service before #7852,  but has been overridden to the backend service for authentication in #7852.
> rls: fix rls oobChannel grpclb config service name

- rls/build.gradle
- rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
- rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
This is backport of #7902 
The serviceName field in oobChannel grpclb config should not be null, otherwise it will default to the lbHelper.getAuthority(), which perviously defaulted to the lookup service before #7852, but has been overridden to the backend service for authentication in #7852.
> rls: fix rls oobChannel grpclb config service name (backport v1.36.x)

- context/src/main/java/io/grpc/Context.java
When running JFR I found a short lock contention for this code - a thread was blocked for 16 ms.
Stacktrace:
```
io.grpc.Context$CancellableContext.cancel(Throwable)	1
io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(Status)	1
io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(Status)	1
io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext()	1
io.grpc.internal.ContextRunnable.run()	1
io.grpc.internal.SerializingExecutor.run()	1
com.spotify.metrics.core.InstrumentedExecutorService$InstrumentedRunnable.run()	1
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker)	1
java.util.concurrent.ThreadPoolExecutor$Worker.run()	1
java.lang.Thread.run()	1
```
This PR is an attempt to reduce the amount of …
> Move pendingDeadline.cancel out of synchronized block

- xds/src/main/java/io/grpc/xds/AbstractXdsClient.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientV2Test.java
New features should be env flag protected even for proto parsing, because otherwise if there is a bug in parsing the new fields, users will break even if they are not using new feature.
> xds: gate HttpFilter parsing by env flag

- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/main/java/io/grpc/netty/NettyClientTransport.java
- netty/src/main/java/io/grpc/netty/WriteBufferingAndExceptionHandler.java
If a handshake is ongoing during shutdown, this would substantially
reduce the time it takes to shut down. Previously, you would need to use
channel.shutdownNow() to have fast shutdown behavior, which is an
unnecessary use of the variant.
When the current approach was written WriteBufferingAndExceptionHandler
didn't exist and so it was hard to predict how the pipeline would react
to events (particularly because of HTTP/2 handler's re-definition of
close()). Now that WBAEH exists, this is more straight-forward.
-----
@susinmotion, this dramatically speeds the exit of your toy client after the RPCs complete.
> netty: Allow handshakes to be interrupted by channel shutdown

- xds/src/main/java/io/grpc/xds/ServerXdsClient.java
- xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
- xds/src/test/java/io/grpc/xds/ServerXdsClientNewServerApiTest.java
- xds/src/test/java/io/grpc/xds/ServerXdsClientTest.java
remove dependency on the env var GRPC_XDS_EXPERIMENTAL_NEW_SERVER_API so the change in https://github.com/grpc/grpc/pull/25529 wouldn't be needed.
> xds: remove the env var GRPC_XDS_EXPERIMENTAL_NEW_SERVER_API

- stub/src/main/java/io/grpc/stub/ClientCalls.java
Changes originally proposed as part of #7106.
Fixes #3557
> stub: Have ClientCalls.ThreadlessExecutor reject Runnables after end of RPC

- stub/src/main/java/io/grpc/stub/ClientCalls.java
This reverts commit 61e0f30e387c1dfead3e5d62890ab2a9f3b215a1 (#7798).
Our stub/core implementation had a bug (#7921) that might make it possible to leak cancellation through to the executor multiple times, typically when a custom interceptor is used. Revert this commit because import of grpc to google internal fails.
cc @njhill
> Revert "stub: Have ClientCalls.ThreadlessExecutor reject Runnables after end of RPC

- README.md
We find codecov.io generally more useful than coveralls.io, so make it a
bit easier to dig into the coverage.
We put it second simply because when people think "test coverage"
without any other details they (rightly) generally assume line coverage;
condition coverage is generally a separate metric. Codecov uses a
combined line+condition coverage metric which is pretty nice, but
if you are unfamiliar with it it appears like code coverage is lower
than it actually is.
-----
This is an alternative to #7915
> Add Codecov.io badge for code coverage

- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
Race scenario:
The LB stream was closed and a retry task has been scheduled. Receiving a ResolvedAddress update with LB addresses immediately creates a new RPC stream again. Then when the retry task fires, a LB stream already exists.
There are a couple of ways to mitigate the race. This change cancels the retry task when the address update causing a new LB stream to be created.
See b/181708023
> grpclb: fix race between address update and LB stream recreation

- api/src/main/java/io/grpc/NameResolver.java
- api/src/main/java/io/grpc/NameResolverProvider.java
- api/src/test/java/io/grpc/NameResolverTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
I am trying to add a new API for exposing some unique ID that represents the Channel to its resolver. It could just be `ManagedChannelImpl`'s logId (the `long` value). 
We want this to be a required attribute for `NameResolver.Args` to avoid confusion. So deleting old APIs (`NameResolver.Helper`) without the necessity to add such an attribute for it as well.
> api: delete deprecated NameResolver APIs

- alts/src/main/java/io/grpc/alts/AltsServerBuilder.java
- api/src/main/java/io/grpc/ForwardingServerBuilder.java
- api/src/main/java/io/grpc/ServerBuilder.java
- api/src/test/java/io/grpc/ForwardingServerBuilderTest.java
- api/src/test/java/io/grpc/ForwardingTestUtil.java
- core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
- core/src/test/java/io/grpc/internal/AbstractServerImplBuilderTest.java
Make AltsServerBuilder extend ForwardingServerBuilder so we do not need to worry about method forwarding test.
More context in https://github.com/grpc/grpc-java/pull/7926#issuecomment-790202011
Internal changes: cl/361042897
> api: make AltsServerBuilder extend ForwardingServerBuilder and clean up addServices() API

- xds/src/main/java/io/grpc/xds/ThreadSafeRandom.java
- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/test/java/io/grpc/xds/WeightedRandomPickerTest.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
Generate a hash value for each RPC based on the HashPolicies configured for the Route that the RPC is routed to.
> xds: implement per-RPC hash generation

- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientV2Test.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientV3Test.java
In preparation for ADS parsing changes, I was reading through ClientXdsClientTestBase and ended up refactoring some pieces to make it easier to add [upcoming resource metadata capture](https://github.com/sergiitk/grpc-java/pull/12/commits/9cf1b78b173043aad865290f577042d76146d2b7).
- The same `Any` resources used in different places moved to private fields to make it easier to know when a different resource is used in tests on purpose
- Added some constants to make assertions for the same values easier to read/conceptualize
- Added helpers for single-resource `sendResponse()`, `verifyRequest()`, etc, to skip single-element collection so it's a bit easier to read
- Re-ordered arguments of  `sendResponse()`, `verifyRequest()` to make them consistent between each other, and upcoming similar …
> xds: Simplify ClientXdsClientTestBase by reusing test resources

- stub/src/main/java/io/grpc/stub/CallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ClientCallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ClientResponseObserver.java
- stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java
- stub/src/test/java/io/grpc/stub/ClientCallsTest.java
- stub/src/test/java/io/grpc/stub/ServerCallsTest.java
> stub: stabilize StreamObserver APIs

- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
- interop-testing/src/test/java/io/grpc/testing/integration/TestServiceClientTest.java
This is needed as a pre-req for internal issue b/175066772 (in order to use a more recent grpc-java in those tests, we need to configure an explicit grpclb service config).
The same flag also exists in the C++ test clients (added in https://github.com/grpc/grpc/pull/22540).
> Add a flag to interop clients to allow statically configuring grpclb

- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
When aggregating the overall load balancing state, we should treat both IDLE and CONNECTING subchannels as "connection in progress". Otherwise, RPCs could fail prematurely if one subchannel enters TF while all the others are still in CONNECTING. 
#7816 made each individual subchannel stay in TF until READY if it previously was in TF. So subchannels with CONNECTING state are those in first time connecting. We should give them time to connect.
See more comment in https://github.com/grpc/grpc-java/pull/7816#discussion_r592794512.
> grpclb: should not ignore subchannels with CONNECTING state in aggregating the overall LB state

- xds/src/main/java/io/grpc/xds/BootstrapperImpl.java
Changes from "io.grpc.xds.bootstrapValue" to "io.grpc.xds.bootstrapConfig".
-------------------
Backport of #7961
> xds: change system property for reading bootstrap config (backport v1.36.x)

- examples/example-tls/build.gradle
- examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldClientTls.java
- examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldServerTls.java
Using the new credentials API allows using generic APIs instead of
Netty-specific ones and allows using grpc-netty-shaded. The new API is
still marked experimental, but it is intended to be stabilized which
isn't the case for the Netty-specific API.
The client now looks more similar to HelloWorldClient.
> example-tls: Port to Tls{Channel,Server}Credentials

- .gitignore
.ijwb is used for the Bazel IntelliJ plugin.
> Add .ijwb to .gitignore

- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
- netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java
- netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersUtilsTest.java
Starting in Netty 4.1.60, Netty will validate Content-Length headers
using getAll() and setLong(). While getAll() was documented as only used
in tests, it doesn't appear it was currently used in any tests.
While Http2NettyTest.contentLengthPermitted() was added to confirm that
Content-Length works, it won't actually exercise any interesting
behavior until we upgrade to Netty 4.1.60. However, I did test with
Netty 4.1.60 and it reproduced the failure in
https://github.com/grpc/grpc-java/issues/7953 and passed with this
change.
Since Netty is now observing/modifying the headers, it would seem
appropriate to implement a substantial portion of the Http2Headers API.
However, the surface is much larger than we'd want to implement for a
'quick fix' that could be backported. In addition, it seems …
> netty: Add Http2Headers.setLong() for inbound headers

- xds/src/main/java/io/grpc/xds/Bootstrapper.java
- xds/src/main/java/io/grpc/xds/BootstrapperImpl.java
- xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
- xds/src/test/java/io/grpc/xds/BootstrapperImplTest.java
- xds/src/test/java/io/grpc/xds/XdsClientWrapperForServerSdsTestMisc.java
- xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java
To match the spec in https://github.com/grpc/proposal/blob/master/A36-xds-for-servers.md#xds-protocol .
> xds: use the correct resource id template as per xDS server gRFC

- buildscripts/kokoro/xds.sh
Tested in https://fusion2.corp.google.com/invocations/e3e74b51-c96e-407c-8571-4b962dc977c3
(fault injection in v2 test can be automatically skipped by the test runner)
> buildscripts: enable fault injection interop test

- xds/src/main/java/io/grpc/xds/MessagePrinter.java
- xds/third_party/envoy/import.sh
- xds/third_party/envoy/src/main/proto/envoy/config/filter/http/router/v2/router.proto
- xds/third_party/envoy/src/main/proto/envoy/extensions/filters/http/router/v3/router.proto
Interop test logs showed that router filter in v3 can not be printed, and router filter as well as fault filter in v2 can not be printed. Imported protos and added proto descriptors to `MessagePrinter`.
> xds: pretty print http filters

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
Initially we were about to support both xx_hash and murmur_hash. But later we decided to support xx_hash only. So for any hashing we are using in xDS, it's going to be xx_hash. Therefore, we do not need to define and carry this configuration around.
> xds: delete redundant hash function configuration

- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
- netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java
- netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersUtilsTest.java
Starting in Netty 4.1.60, Netty will validate Content-Length headers
using getAll() and setLong(). While getAll() was documented as only used
in tests, it doesn't appear it was currently used in any tests.
While Http2NettyTest.contentLengthPermitted() was added to confirm that
Content-Length works, it won't actually exercise any interesting
behavior until we upgrade to Netty 4.1.60. However, I did test with
Netty 4.1.60 and it reproduced the failure in
https://github.com/grpc/grpc-java/issues/7953 and passed with this
change.
Since Netty is now observing/modifying the headers, it would seem
appropriate to implement a substantial portion of the Http2Headers API.
However, the surface is much larger than we'd want to implement for a
'quick fix' that could be backported. In addition, it seems …
> netty: Add Http2Headers.setLong() for inbound headers (1.36.x backport)

- interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
- netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java
- netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersUtilsTest.java
Starting in Netty 4.1.60, Netty will validate Content-Length headers
using getAll() and setLong(). While getAll() was documented as only used
in tests, it doesn't appear it was currently used in any tests.
While Http2NettyTest.contentLengthPermitted() was added to confirm that
Content-Length works, it won't actually exercise any interesting
behavior until we upgrade to Netty 4.1.60. However, I did test with
Netty 4.1.60 and it reproduced the failure in
https://github.com/grpc/grpc-java/issues/7953 and passed with this
change.
Since Netty is now observing/modifying the headers, it would seem
appropriate to implement a substantial portion of the Http2Headers API.
However, the surface is much larger than we'd want to implement for a
'quick fix' that could be backported. In addition, it seems …
> netty: Add Http2Headers.setLong() for inbound headers (1.35.x backport)

- xds/src/main/java/io/grpc/xds/WeightedTargetLoadBalancer.java
- xds/src/test/java/io/grpc/xds/WeightedTargetLoadBalancerTest.java
> xds: weightedTargetLB do a pick to get more failure details improving logs

- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
- xds/src/main/java/io/grpc/xds/GoogleCloudToProdNameResolver.java
Internal issue b/183205647 for context.
The need to configure channels without an explicit port has more context in b/181142141 (and is the method currently used for C++)
The `GRPC_TEST_ONLY_GOOGLE_C2P_RESOLVER_TRAFFIC_DIRECTOR_URI` env var is needed to reach alternative instances of TD for testing, and is supported by Go and C++.
> Allow using TestServiceClient for making Traffic Director RPCs

- alts/src/main/java/io/grpc/alts/ComputeEngineChannelCredentials.java
- alts/src/main/java/io/grpc/alts/GoogleDefaultChannelCredentials.java
- alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java
- alts/src/test/java/io/grpc/alts/internal/GoogleDefaultProtocolNegotiatorTest.java
GoogleDefaultChannelCredentials and ComputeEngineChannelCredentials are literally the same thing for DirectPath, both of them should behave the same for choosing the protocol negotiator for talking to backends given by Traffic Director.
> alts: make both GoogleDefaultChannelCredentials and ComputeEngineChannelCredentials choose ALTS for backends given by xDS TD

- okhttp/src/main/java/io/grpc/okhttp/OkHttpReadableBuffer.java
okio 2.x is ABI compatible with 1.x but not API compatible. This hasn't
been a problem as users use binaries from Maven Central so the ABI
compatibility is the important part. However, when building with Bazel
the API compatibily is the important part.
Tested with okio 2.10.0
Fixes #8004
CC @Kernald
> okhttp: Fix okio 2.x API incompatibility

- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
XdsNameResolver is stateful in terms of received xDS configurations (e.g., routes, httpMaxStreamDuration, clusters being exposed in service config). The full suite of configurations should always be updated whenever receiving new resource updates, including updates that revoke currently in-use resources. Reference counts for currently in-use clusters should also be cleaned up properly. Otherwise, re-receiving (after being revoked) the same resource can be treated as if the configuration never changed.
In short, all of XdsNameResolver's states should always be consistent with the most recent xDS update, including the updates for revoking resources.
-------------
Fixes #8009
> xds: update (local) configurations atomically for each LDS/RDS resource update

- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestClient.java
- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java
`XdsTestClient` and `XdsTestService` load `ChannelzService` and `CsdsService` via `AdminInterface`.
> interop-testing: xDS interop app uses AdminInterface

- xds/src/main/java/io/grpc/xds/AbstractXdsClient.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/CsdsService.java
- xds/src/main/java/io/grpc/xds/SharedXdsClientPoolProvider.java
- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/CsdsServiceTest.java
- xds/src/test/java/io/grpc/xds/SharedXdsClientPoolProviderTest.java
This PR is needed for further changes to eliminate the Bootstrapper from TlsContextManagrerImpl and related classes.
> xds: expose bootstrap through XdsClient interface

- netty/src/main/java/io/grpc/netty/GrpcSslContexts.java
Tested with the interop client on Zulu 8 and Zulu 11 with
-XX:+UseOpenJSSE (after disabling tcnative). I was unable to add a new
case to TlsTest because adding OpenJSSE as a dependency in a Gradle
build fails: https://github.com/openjsse/openjsse/issues/19
Fixes #7907
CC @badabapidas
> netty: Add support for OpenJSSE

- xds/src/main/java/io/grpc/xds/EnvoyServerProtoData.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
- xds/src/test/java/io/grpc/xds/EnvoyServerProtoDataTest.java
- Don't enforce a specific name-match for HCM and Router httpFilter
- Don't allow "managed-mtls" in the application-protocols
CC @ejona86
> xds: Fix validation of HCM filter and Router httpFilter

- netty/src/main/java/io/grpc/netty/GrpcSslContexts.java
Tested with the interop client on Zulu 8 and Zulu 11 with
-XX:+UseOpenJSSE (after disabling tcnative). I was unable to add a new
case to TlsTest because adding OpenJSSE as a dependency in a Gradle
build fails: https://github.com/openjsse/openjsse/issues/19
Fixes #7907
CC @badabapidas 
Backport of #8042
> netty: Add support for OpenJSSE (1.37.x backport)

- bom/build.gradle
Binder is not yet being published, so this artifact wouldn't exist.
CC @markb74 
Backport of #8038
> bom: Do not include grpc-binder (1.37.x backport)

- xds/src/main/java/io/grpc/xds/internal/sds/ClientSslContextProviderFactory.java
- xds/src/main/java/io/grpc/xds/internal/sds/ServerSslContextProviderFactory.java
- xds/src/test/java/io/grpc/xds/internal/sds/ClientSslContextProviderFactoryTest.java
- xds/src/test/java/io/grpc/xds/internal/sds/ServerSslContextProviderFactoryTest.java
The 2 Factory classes are modified to save bootstrapInfo locally to avoid re-reading bootstrap file.
> xds: cache bootstrapInfo in the SslContextProviderFactory to prevent rereading

- xds/src/main/java/io/grpc/xds/internal/sds/ClientSslContextProviderFactory.java
- xds/src/main/java/io/grpc/xds/internal/sds/ServerSslContextProviderFactory.java
- xds/src/test/java/io/grpc/xds/internal/sds/ClientSslContextProviderFactoryTest.java
- xds/src/test/java/io/grpc/xds/internal/sds/ServerSslContextProviderFactoryTest.java
The 2 Factory classes are modified to save bootstrapInfo locally to avoid re-reading bootstrap file.
> xds: cache bootstrapInfo in the SslContextProviderFactory to prevent rereading (backport 1.37.x) #8051

- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
Enhance error information reflected by RPC status when failing to fallback (aka, no fallback addresses provided by resolver), by including the original cause of entering fallback. This falls into cases:
- balancer RPC timeout before receiving any backend addresses (includes a timeout message)
- balancer RPC failed before receiving any backend addresses (use the error occurred in balancer RPC)
- all balancer-provided addresses failed, while balancer RPC had failed causing fallback (use the error status for one of the balancer-provided backend)
Note for cases that connections to fallback address fail, it's already using one of fallback addresses' error. See `handleSubchannelState(...)` -> `maybeUseFallbackBackends()` (no-op as it's already using fallback backends) -> `maybeUpdatePicker()` …
> grpclb: include fallback reason in error status of failing to fallback

- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
Fix internal check nagging about unnecessary `@SuppressWarnings("unchecked")`.
Error Prone
UnnecessaryJavacSuppressWarnings
Unnecessarily suppressed warnings: unchecked
> xds: Fix error prone UnnecessaryJavacSuppressWarnings in a test

- RELEASING.md
JFrog [has announced](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) that they are shutting down the JCenter.
> RELEASING.md: remove JCenter note

- xds/src/main/java/io/grpc/xds/InternalXdsAttributes.java
- xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
- xds/src/main/java/io/grpc/xds/RingHashLoadBalancerProvider.java
- xds/src/main/resources/META-INF/services/io.grpc.LoadBalancerProvider
- xds/src/test/java/io/grpc/xds/RingHashLoadBalancerProviderTest.java
- xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java
Implements the [ring hash](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers#ring-hash) load balancing policy.
- The policy can accept addresses weighted by the per-address weight attribute or having multiple instances of the same address. E.g., [addr0(ATTR=1), addr1(ATTR=2)] is equivalent to [addr0, addr1, addr1].
- The ring hash policy will not proactively connect to all addresses. Instead, it will wait for a request to hit a given address before it attempts to connect. 
Special subchannel and picker behaviors:
- At any point of time, there will be at least one subchannel making connection (or has been connected). This comes with the following picking algorithm:
- If the host hit by RPC's hash is connected, return the READY subchannel …
> xds: implement ring_hash load balancing policy

- buildscripts/kokoro/xds-k8s.sh
> buildscript: add xds-k8s cluster endpoint override

- buildscripts/kokoro/xds-k8s.sh
ref:
https://github.com/grpc/grpc-java/pull/8063
https://github.com/grpc/grpc-java/pull/8064
> buildscript: use different xds-k8s cluster (v1.36.x backport)

- buildscripts/kokoro/xds-k8s.sh
ref:
https://github.com/grpc/grpc-java/pull/8063
https://github.com/grpc/grpc-java/pull/8064
> buildscript: use different xds-k8s cluster (v1.37.x backport)

- buildscripts/kokoro/xds-k8s.sh
ref:
https://github.com/grpc/grpc-java/pull/8063
https://github.com/grpc/grpc-java/pull/8064
> buildscript: use different xds-k8s cluster (v1.35.x backport)

- buildscripts/kokoro/xds-k8s.sh
ref:
https://github.com/grpc/grpc-java/pull/8063
https://github.com/grpc/grpc-java/pull/8064
> buildscript: use different xds-k8s cluster (v1.34.x backport)

- xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java
In the ring hash LB policy, building the ring is computationally heavy. Although using a larger ring can make the RPC distribution closer to the actual weights of hosts, it takes long time to finish the test.
Internally, each test class is expected to finish within 1 minute, while each of the test cases for testing pick distribution takes about 30 sec. By reducing the ring size by a factor of 10, the time spent for those test cases reduce to 1-2 seconds. Now we need larger tolerance for the distribution (three hosts with weights 1:10:100):
- With a ring size of 100000, the 10000 RPCs distribution is close to 91 : 866 : 9043
- With a ring size of 10000, the 10000 RPCs distribution is close to 104 : 808 : 9088
Roughly, this is still acceptable.
> xds: reduce the size of ring for testing pick distributions

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/ConfigSelectingClientCallTest.java
Fix the following bug:
`ManagedChannelImpl.ConfigSelectingClientCall` may return early in `start()` leaving `delegate` null, and fails `request()` method after `start()`.
Currently the bug can only be triggered when using xDS.
Example stacktrace:
```
FINEST: [Channel<4>: (xds:///grpc-test1618369345:8268)] Entering CONNECTING state with picker: EmptyPicker{}
Apr 13, 2021 9:34:20 PM io.grpc.testing.integration.XdsTestClient run
SEVERE: Error running client
java.util.concurrent.ExecutionException: java.lang.NullPointerException
at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:104)
at …
```
> core: fix NPE in ConfigSelectingClientCall

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/ConfigSelectingClientCallTest.java
backport of #8087 
Fix the following bug:
ManagedChannelImpl.ConfigSelectingClientCall may return early in start() leaving delegate null, and fails request() method after start().
Currently the bug can only be triggered when using xDS.
> core: fix NPE in ConfigSelectingClientCall (backport v1.37.x)

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/test/java/io/grpc/internal/ConfigSelectingClientCallTest.java
Backport of #8087 
Fix the following bug:
ManagedChannelImpl.ConfigSelectingClientCall may return early in start() leaving delegate null, and fails request() method after start().
Currently the bug can only be triggered when using xDS.
> core: fix NPE in ConfigSelectingClientCall (backport v1.36.x)

- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
> OkHttpClientTransportTest's proxy to use loopback address

- context/src/main/java/io/grpc/Context.java
This recently came up in https://stackoverflow.com/a/67062503/4690866,
but it has come up multiple times before. These docs aren't ideal, as
they may be missed by a reader and so references in other parts of the
API would probably be appropriate. There could also be something about
"Context is not a general purpose map." But this is an improvement, and
I didn't want to let the perfect be the enemy of the good.
CC @sanjaypujare due to support role
> context: Add docs describing common Key usage

- api/src/main/java/io/grpc/LoadBalancer.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/PickFirstLoadBalancer.java
- core/src/main/java/io/grpc/util/ForwardingLoadBalancerHelper.java
- core/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- core/src/test/java/io/grpc/internal/PickFirstLoadBalancerTest.java
- core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
- rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
- xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
- xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
- xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java
Currently each subchannel [implicitly refreshes the name resolution](https://github.com/grpc/grpc-java/blob/5e9a7b6e2f4e5ae2789fb7efc597c6a80c8beabd/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L1929) when its connection is broken. That is, this feature is built into subchannel's internal implementation. Although it eliminates the burden of having LB implementations refreshing the resolver when connections to backends are broken, this is gives LB policies no chance to disable or override this refresh (e.g., in some complex load balancing hierarchy like xDS, LB policies may embed a resolver inside for resolving backends so the refreshing resolution operation should be hooked to the resolver embedded in the LB policy instead of the one in Channel).
This is likely to be a …
> core, grpclb,xds: let leaf LB policies explicitly refresh name resolution when subchannel connection is broken

- all/build.gradle
Otherwise the executionData would be out-of-date.
> all: JacocoMerge must run after grpc-interop-testing's tests

- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
> netty: fix status message when GOAWAY at MAX_CONCURRENT_STREAMS limit

- android-interop-testing/build.gradle
- android/build.gradle
- build.gradle
- examples/android/clientcache/app/build.gradle
- examples/android/helloworld/app/build.gradle
- examples/android/routeguide/app/build.gradle
- examples/android/strictmode/app/build.gradle
This change can have large impact from two aspects:
1. It calls out a _large_ impact on the _few_ Java 7 users.
2. It may have _small_ impact on the _many_ Android users.
https://github.com/grpc/grpc-java/issues/4671 tracks gRPC's removal of
Java 7 support. We are quite eager to drop Java 7 support as that would
allow using new language features like default methods. Guava is also
dropping Java 7 support and starting in 30.1 it will warn when used on
Java 7. The purpose of the warning is to help discover users that are
negatively impacted by dropping Java 7 before it becomes a bigger
problem.
The Guava logging check was implemented in such a way that there is an
optional class that uses Java 8 bytecode. While the class is optional at
runtime, the Android build system notices when dexing …
> Upgrade to Guava 30.1, which warns on Java 7

- all/build.gradle
Back in 10fb206 when this for loop was added, we didn't have the
subprojects list. That was added in 9bd7bab, but I failed to update one
reference to rootProject. So all has had an evaluation dependency on all
projects, even though it only needs a subset.
This should have little impact, but would prevent weird scenarios like
an issue in :grpc-gae-interop-testing-jdk8 preventing :all-all from
being loaded. Not to say things wouldn't still fail to load, but that
this bug could distract from the real problem. I noticed this
during #8049.
> all: Only depend on evaluation of enumerated subprojects

- core/src/main/java/io/grpc/util/CertificateUtils.java
- core/src/test/java/io/grpc/util/CertificateUtilsTest.java
This is to add a certificate/key loading class in `io.grpc.util`, under the help of base64 decoding support by Guava.
@ejona86 @sanjaypujare Feel free to take a look and let me know anything need to be improved. Thank you so much!
> advancedtls: Add a Utility Class For Loading Certs/Keys

- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
> netty: fix StreamBufferingEncoder GOAWAY bug (backport v1.37.x)

- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
> netty: fix StreamBufferingEncoder GOAWAY bug (backport v1.36.x) 

- android-interop-testing/build.gradle
- android/build.gradle
- binder/build.gradle
- cronet/build.gradle
- examples/android/clientcache/build.gradle
- examples/android/helloworld/build.gradle
- examples/android/routeguide/build.gradle
- examples/android/strictmode/build.gradle
- gae-interop-testing/gae-jdk8/build.gradle
Fixes #7990 
Replaces jcenter with mavenCentral.
If we found it to be too flaky, we can change to use google's mirror as gae-interop-testing is already doing.
> Migrate away from Jcenter

- xds/src/main/java/io/grpc/xds/internal/sds/ServerWrapperForXds.java
- xds/src/test/java/io/grpc/xds/ServerWrapperForXdsTest.java
fix tsan [complain](https://fusion2.corp.google.com/invocations;query=user:zivy%20tsan%20367298356%20failed;page_size=100/25354208-d976-4ecc-a390-487bc85d9d48/targets/%2F%2Fthird_party%2Fjava_src%2Fgrpc%2Fxds:src%2Ftest%2Fjava%2Fio%2Fgrpc%2Fxds%2FServerWrapperForXdsTest/tests)
> tsan, xds: fix data races in ServerWrapperForXds

- buildscripts/kokoro/xds-k8s-install-test-driver.sh
[`pip 21.1`](https://pypi.org/project/pip/21.1/) released on Apr 24 introduced a regression for `python 3.6.1`.
The regression was [identified](https://github.com/pypa/pip/issues/9831) on Apr 24, [the fix](https://github.com/pypa/pip/pull/9835) merged on Apr 25.
The fix is expected to be delivered in the [`21.1.1`](https://github.com/pypa/pip/milestone/50) patch.
There's no clear date when `21.1.1` will be released at the moment. Until then, I'll temporarily pin pip to the previous release, `21.0.1`.
Related: grpc/grpc#26087
> buildscripts: xds-k8s pin pip to 21.0.1

- buildscripts/kokoro/xds-k8s-install-test-driver.sh
Backports https://github.com/grpc/grpc-java/pull/8115 to `1.37.x`.
> buildscripts: xds-k8s pin pip to 21.0.1 (backport 1.37.x)

- buildscripts/run_arm64_tests_in_docker.sh
Due to https://github.com/grpc/grpc-java/issues/8118  the :grpc-xds:test currently doesn't provide useful signal.
It would be preferrable to fix https://github.com/grpc/grpc-java/issues/8118 of course - any chance you could take a look or at least provide some tips how to best approach it?
> skip flaky :grpc-xds:test in linux aarch64 tests

- xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
- xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java
Implements toString() for the wrapping SubchannelPickers so that we are able to see how hosts are selected when sending out RPCs.
> xds: implement toString() for pickers to visualize selectable hosts

- xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
- xds/src/main/java/io/grpc/xds/internal/sds/ServerWrapperForXds.java
- xds/src/test/java/io/grpc/xds/FilterChainMatchTest.java
- xds/src/test/java/io/grpc/xds/ServerWrapperForXdsTest.java
- xds/src/test/java/io/grpc/xds/XdsClientWrapperForServerSdsTestMisc.java
- xds/src/test/java/io/grpc/xds/XdsSdsClientServerTest.java
- xds/src/test/java/io/grpc/xds/XdsServerBuilderTest.java
- xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java
Use the `XdsClientPoolFactory` on the server side so that a singleton ClientXdsClient is used for both client and server side uses
> xds: use singleton XdsClient for server side

- core/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
- core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
After shutting down a Subchannel, (after 5s delay) its state listener will receive a [connectivity state update](https://github.com/grpc/grpc-java/blob/02ff64fa210d8b621dbeb6701c64b89a0d158874/core/src/main/java/io/grpc/internal/InternalSubchannel.java#L417) with SHUTDOWN state. Round_robin will pick up that state update and trigger a balancing state update with [TRANSIENT_FAILURE and an empty picker that buffers RPCs](https://github.com/grpc/grpc-java/blob/02ff64fa210d8b621dbeb6701c64b89a0d158874/core/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java#L195) to the upstream.
This can cause extremely-hard-to-debug problems such as when round_robin is shut down (e.g., switching to another LB policy, or in complex cases like xDS where endpoint-level load balancing is turned off due to …
> core: throw away subchannel references after round_robin is shutdown

- examples/build.gradle
This PR will output the [Flow control example](https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/manualflowcontrol) client & server to:
- ./examples/build/install/examples/bin/manual-flow-control-client
- ./examples/build/install/examples/bin/manual-flow-control-server
The [examples README.md](https://github.com/grpc/grpc-java/blob/master/examples/README.md#-to-build-the-examples) states that the script should be present, but it currently isn't.
This PR improves gRPC to honour the [examples README.md](https://github.com/grpc/grpc-java/blob/master/examples/README.md#-to-build-the-examples) and to quickly find out this example exists, instead of having to go through the source code.
> examples: export the manualflowcontrol example to the bin output folder

- alts/src/main/java/io/grpc/alts/AltsServerCredentials.java
- api/src/main/java/io/grpc/ChoiceServerCredentials.java
- api/src/main/java/io/grpc/Grpc.java
- api/src/main/java/io/grpc/InsecureServerCredentials.java
- api/src/main/java/io/grpc/ServerCredentials.java
- api/src/main/java/io/grpc/ServerRegistry.java
- api/src/main/java/io/grpc/TlsServerCredentials.java
- xds/src/main/java/io/grpc/xds/XdsServerCredentials.java
Some of the experimental API annotations were changed to other issues or
became @Internal to match their related APIs.
Fixes #7621
> Stabilize ServerCredentials

- alts/src/main/java/io/grpc/alts/ComputeEngineChannelCredentials.java
- alts/src/main/java/io/grpc/alts/GoogleDefaultChannelCredentials.java
- api/src/main/java/io/grpc/ChannelCredentials.java
- api/src/main/java/io/grpc/ChoiceChannelCredentials.java
- api/src/main/java/io/grpc/CompositeCallCredentials.java
- api/src/main/java/io/grpc/CompositeChannelCredentials.java
- api/src/main/java/io/grpc/Grpc.java
- api/src/main/java/io/grpc/InsecureChannelCredentials.java
- api/src/main/java/io/grpc/ManagedChannelRegistry.java
- api/src/main/java/io/grpc/TlsChannelCredentials.java
- xds/src/main/java/io/grpc/xds/XdsChannelCredentials.java
Some of the experimental API annotations were changed to other issues or
became `@Internal` to match their related APIs.
Fixes #7479
> Stabilize ChannelCredentials

- xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
- xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java
Same as #8132.
Clean up subchannels after the RingHashLoadBalancer itself is shutdown to prevent further balancing state updates being propagated to the upstream.
Note this should not be considered as a fix for any problem anybody is noticing. Upstreams of RingHashLoadBalancer should not rely on this, it should still have its own logic for maintaining the lifecycle of downstream LB and ignore invalid upcalls when necessary.
> xds: throw away subchannel references after ring_hash is shutdown

- xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java
- xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
- xds/src/main/java/io/grpc/xds/WeightedTargetLoadBalancer.java
- xds/src/test/java/io/grpc/xds/ClusterManagerLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/WeightedTargetLoadBalancerTest.java
Similar correspondence of #8132 for xDS.
LoadBalancers should not propagate balancing state updates after itself being shutdown. 
For LB policies that maintain a group of child LB policies with each having its independent lifetime, balancing state update propagations from each child LB policy can go out of the lifetime of its parent easily, especially for cases that balancing state update is put to the back of the queue and not propagated up inline. 
For LBs that are simple pass-through in the middle of the LB tree structure, it isn't a big issue as its lifecycle would be the same as its child. Transitively, It would behave correctly as long as its downstream is doing in the right way.
This change is a sanity cleanup for LB policies that maintain multiple child LB policies to preserve the …
> xds: ignore balancing state update from downstream after LB shutdown

- xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
- xds/src/main/java/io/grpc/xds/internal/sds/SslContextProviderSupplier.java
- xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java
This is the precursor to the next PR which will use SslContextProviderSupplier on the server side by passing DownstreamTlsContext and the resulting SslContextProviderSupplier will be used in place of DownstreamTlsContext in the translated Listener object.
> xds: extend SslContextProviderSupplier to use BaseTlsContext 

- buildscripts/kokoro/xds.cfg
- buildscripts/kokoro/xds_v3.cfg
Related https://github.com/grpc/grpc/pull/26090
With config update timeout pushed to 600s, we might need longer Kokoro build timeout as well.
> Extend the xDS interop tests timeout to 360 mins

- buildscripts/kokoro/xds-k8s.sh
Switch PSM Security interop tests from a testing cluster to the latest compatible prod GKE cluster.
ref b/185153211
> buildscripts: switch xds-k8s cluster to 1.20.x

- buildscripts/kokoro/xds-k8s.sh
Backports https://github.com/grpc/grpc-java/pull/8148 to `1.37.x`.
> buildscripts: switch xds-k8s cluster to 1.20.x (backport 1.37.x)

- xds/src/main/java/io/grpc/xds/AbstractXdsClient.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/LoadReportClient.java
- xds/src/main/java/io/grpc/xds/SharedXdsClientPoolProvider.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/LoadReportClientTest.java
Control plane RPCs are independent of application RPCs, they can stand for completely different lifetime. So the context for making application RPCs should not be propagated to control plane RPCs.
> xds: use a standalone Context for xDS control plane RPCs

- grpclb/BUILD.bazel
- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancerProvider.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
Similar to #8153 for gRPCLB.
Control plane RPCs are independent of application RPCs, they can stand for completely different lifetime. So the context for making application RPCs should not be propagated to control plane RPCs.
> grpclb: use a standalone Context for gRPCLB control plane RPCs

- core/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
- core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java
Triggering balancing state updates after already being shutdown can be confusing for the upstream of round_robin. In cases of the callers not managing round_robin's lifecycle (e.g., not ignoring updates after it shuts down round_robin, which it should), it can make problem very bad, especially with the behavior that round_robin is actually propagating TRANSIENT_FAILURE with a picker that buffers RPCs.
This change only polishes round_robin by always preserving its invariant. Callers/LBs should not rely on this and should still manage the balancing updates from its downstream correctly based on the downstream's lifetime.
Backport of #8132
> core: throw away subchannel references after round_robin is shutdown (v1.37.x backport)

- xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java
- xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
- xds/src/main/java/io/grpc/xds/WeightedTargetLoadBalancer.java
- xds/src/test/java/io/grpc/xds/ClusterManagerLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/WeightedTargetLoadBalancerTest.java
LoadBalancers should not propagate balancing state updates after itself being shutdown.
For LB policies that maintain a group of child LB policies with each having its independent lifetime, balancing state update propagations from each child LB policy can go out of the lifetime of its parent easily, especially for cases that balancing state update is put to the back of the queue and not propagated up inline.
For LBs that are simple pass-through in the middle of the LB tree structure, it isn't a big issue as its lifecycle would be the same as its child. Transitively, It would behave correctly as long as its downstream is doing in the right way.
This change is a sanity cleanup for LB policies that maintain multiple child LB policies to preserve the invariant that further balancing state …
> xds: ignore balancing state update from downstream after LB shutdown (v1.37 backport)

- xds/src/main/java/io/grpc/xds/AbstractXdsClient.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/LoadReportClient.java
- xds/src/main/java/io/grpc/xds/SharedXdsClientPoolProvider.java
- xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/LoadReportClientTest.java
Control plane RPCs are independent of application RPCs, they can stand for completely different lifetime. So the context for making application RPCs should not be propagated to control plane RPCs.
------------------
Manual backport of #8153. Mostly same as #8153, with added change for server side instantiation of ClientXdsClient. Done manually due to large amount of conflicts caused by other changes made to ClientXdsClient instantiations.
> xds: use a standalone Context for xDS control plane RPCs (manual v1.37.x backport)

- grpclb/BUILD.bazel
- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancerProvider.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
Inject a standalone Context that is independent of application RPCs to GrpclbLoadBalancer for control plane RPCs. The control plane RPC should be independent and not impacted by the lifetime of Context used for application RPCs.
Backport of #8154
> grpclb: use a standalone Context for gRPCLB control plane RPCs (v1.36.x backport)

- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
In normal cases, we only have a few header matchers but the number of headers can be completely up to the application. Indexing headers eagerly parses all headers, even for those with no matcher matching the key. We should only parse header values for those with key matching the header matcher (aka, only call Metadata.get() with key that has some matcher looking for).
> xds: lazily and only parse headers with matchers matching the key

- netty/shaded/build.gradle
The pom.properties are apparently present to allow tooling to know what
Maven artifact cooresponds to a JAR, just by looking at the JAR. Since
we shade Netty, that produces inaccurate results. This was noticed in
in #8077.
CC @camjohson
> netty: Remove Maven pom.properties from netty-shaded

- SECURITY.md
For clarity, also extract grpc-netty-shaded to a separate paragraph.
Closes: #7869.
> Document that xds uses grpc-netty-shaded

- api/BUILD.bazel
- api/src/main/java/io/grpc/ForwardingChannelBuilder.java
- api/src/main/java/io/grpc/ForwardingServerBuilder.java
- core/BUILD.bazel
- core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
- core/src/main/java/io/grpc/inprocess/InProcessServerBuilder.java
- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/ServerImplBuilder.java
- cronet/src/main/java/io/grpc/cronet/CronetChannelBuilder.java
- xds/src/main/java/io/grpc/xds/XdsServerBuilder.java
Since static methods are pseudo-inherited by Builder implementations but
are trivially accidentally used, we re-define static methods in each
builder to make them behave more like the caller would expect. However,
not all the methods actually work; some just throw because the caller
was certainly not getting what they would expect.
Annotating with `@DoNotCall` can expose the problems at compile time
instead of runtime. While `@Deprecated` would also be an option, it is a
bit harder to figure out the ramifications and whether we want to go
that route.
This change was suggested by a lint tool for XdsServerBuilder and it
seems appropriate so I applied it to the other similar cases I could
find.
> Use @DoNotCall for static methods in Builders that throw

- xds/src/main/java/io/grpc/xds/internal/sds/SslContextProviderSupplier.java
- xds/src/test/java/io/grpc/xds/internal/sds/SslContextProviderSupplierTest.java
Add null checks in SslContextProviderSupplier constructor and `close` (in case `updateSslContext` was never called)
> xds: add null reference checks in SslContextProviderSupplier

- netty/shaded/build.gradle
The pom.properties are apparently present to allow tooling to know what
Maven artifact cooresponds to a JAR, just by looking at the JAR. Since
we shade Netty, that produces inaccurate results. This was noticed in
in #8077.
CC @camjohson 
Backport of #8165
> netty: Remove Maven pom.properties from netty-shaded (1.38.x backport)

- buildscripts/kokoro/xds-k8s.sh
Backports https://github.com/grpc/grpc-java/pull/8148 to `1.38.x`.
> buildscripts: switch xds-k8s cluster to 1.20.x (backport 1.38.x)

- xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
- xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
The cluster_resolver LB policy resolves endpoints for _an ordered list of clusters_. The addresses its child LB policy (aka, PriorityLoadBalancer) receives is ordered first by clusters, then by priorities within each cluster. For example, if the cluster_resolver LB policy receives [clusterA, clusterB, clusterC], the priority LB policy should be expected to receive addresses ordered as [addrs_clusterA_priority0, addrs_clusterA_priority1, ..., addrs_clusterB_priority0, addrs_clusterB_priority1, ..., addrs_clusterC_priority0, ...].
This requires the cluster_resolver LB policy to _synchronize_ all of its resolutions. That is, it needs to wait until getting resolution results (or error if encounter) before propagating them to its child LB policy. Propagating partial results can result in RPCs …
> xds: cluster_resolver LB policy should wait until all clusters being resolved before propagating endpoints to child LB policy

- xds/src/main/java/io/grpc/xds/internal/sds/trust/SdsX509TrustManager.java
- xds/src/test/java/io/grpc/xds/internal/sds/trust/SdsX509TrustManagerTest.java
> xds: ignore unknown SAN name type instead of throwing exception

- core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java
- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- netty/src/test/java/io/grpc/netty/NettyChannelBuilderTest.java
This adds support for creating a Netty Channel with SocketAddress and ChannelCredentials.
This aligns with NettyServerBuilder.forAddress(SocketAddress address, ServerCredentials creds).
(sorry for all the commits, I don't have a local build environment, please squash)
> core, netty: Support SocketAddress with ChannelCredentials

- xds/src/main/java/io/grpc/xds/internal/certprovider/FileWatcherCertificateProvider.java
- xds/src/test/java/io/grpc/xds/internal/certprovider/FileWatcherCertificateProviderTest.java
Make sure threads are shut down when a FileWatcher provider is closed.
> xds: shutDown the scheduledExecutorService when the provider is shutdown

- xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
- xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancerProvider.java
- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientV2Test.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientV3Test.java
- xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
This change includes: 
- parse the _single_ endpoint address from the embedded `Cluster` resource in CDS responses as the DNS hostname for LOGICAL_DNS cluster and include it in CdsUpdate being notified to the CDS LB policy.
- propagate the DNS hostname to the cluster_resolver LB policy via its LB config (DiscoveryMechanism for LOGICAL_DNS cluster).
- cluster_resolver LB policy takes the DNS hostname from the DiscoveryMechanism for LOGICAL_DNS cluster and use it as the name for DNS resolution.
> xds: use load assignment endpoint address in Cluster as the DNS hostname for LOGICAL_DNS

- alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java
- alts/src/test/java/io/grpc/alts/internal/GoogleDefaultProtocolNegotiatorTest.java
gRPC client needs to be able to identify the CFE clusters in order for GoogleDefaultCredentials to choose between ALTS and TLS.  The current design has the client identifying the CFE cluster based on the name "google_cfe", but that won't work if there's a different CFE cluster (with a different name) for each DirectPath service.
Based on the new design, TD will generate a CFE cluster called "google_cfe_${service_name}" (e.g., for DirectPath service "cloud-bigtable.googleapis.com", the cluster name will be "google_cfe_cloud-bigtable.googleapis.com") for each DirectPath service. GoogleDefaultCreds will identify CFE clusters by the name having the prefix "google_cfe_".
> xds: change google_default/compute_engine creds protocol negotiator selection for DirectPath with xDS

- .github/workflows/gradle-wrapper-validation.yml
I've already limited the grpc-wide setting to read-only access, but
limiting it explicitly here seems like a good idea; all workflows should
explicitly set their permissions since any action can implicitly access
the GITHUB_TOKEN.
> Limit permissions to gradlew validator GH Action

- xds/src/main/java/io/grpc/xds/FaultFilter.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
When an RPC is injected with a delay and then fails with DEADLINE_EXCEEDED (partially) due to the delay, it could confuse users if the error message does not mention the existence of the delay injection, because end users normally are not the same people who configured fault injection policy in control plane.
> xds: enhance delay injection error message on DEADLINE_EXCEEDED

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/EnvoyServerProtoData.java
- xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
- xds/src/main/java/io/grpc/xds/internal/sds/SdsProtocolNegotiators.java
- xds/src/main/java/io/grpc/xds/internal/sds/SslContextProviderSupplier.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/EnvoyServerProtoDataTest.java
- xds/src/test/java/io/grpc/xds/FilterChainMatchTest.java
- xds/src/test/java/io/grpc/xds/ServerWrapperForXdsTest.java
- xds/src/test/java/io/grpc/xds/XdsClientWrapperForServerSdsTestMisc.java
- xds/src/test/java/io/grpc/xds/XdsSdsClientServerTest.java
- xds/src/test/java/io/grpc/xds/XdsServerBuilderTest.java
- xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java
- xds/src/test/java/io/grpc/xds/internal/sds/SdsProtocolNegotiatorsTest.java
- xds/src/test/java/io/grpc/xds/internal/sds/SslContextProviderSupplierTest.java
Use SslContextProviderSupplier instead of DownstreamTlsContext to ensure reference counting and lazy loading of SslContextProvider's in the current Listener object.
> xds: replace DownstreamTlsContext by SslContextProviderSupplier in the Listener

- xds/third_party/envoy/import.sh
- xds/third_party/envoy/src/main/proto/envoy/extensions/filters/http/rbac/v3/rbac.proto
#8145 only brings in RBAC configuration protos, but not the http filter protos. We may want to bring in v2 protos as we did for fault injection protos, in case TD sends responses with v2 messages. That would be for logging purposes only and we are not sure if they are necessary. So just import v3 protos for now.
> xds: import v3 RBAC http filter proto

- xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
When aggregating the endpoint resolution errors of the list of clusters in ClusterResolverLoadBalancer, clusters should be processed in its original order as received in the LB config. The last cluster's error is used as the overall error status.
---------
Fixes test flakiness https://fusion2.corp.google.com/invocations/c547cc03-f0b3-4b88-8322-c000aaf71932/targets/%2F%2Fthird_party%2Fjava_src%2Fgrpc%2Fxds:src%2Ftest%2Fjava%2Fio%2Fgrpc%2Fxds%2FClusterResolverLoadBalancerTest/tests
> xds: fix order of processing resolution errors with original cluster ordering 

- xds/src/main/java/io/grpc/xds/EnvoyServerProtoData.java
- xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
- xds/src/test/java/io/grpc/xds/EnvoyServerProtoDataTest.java
- xds/src/test/java/io/grpc/xds/FilterChainMatchTest.java
- xds/src/test/java/io/grpc/xds/XdsSdsClientServerTest.java
- xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java
reference b/183428450
Don't prune out "always-failing" filter chains at validation time. But remove them when we rank all the filter chains so that we get the correct outcome (matching Envoy and other gRPC languages)
> xds: move the unsupported filterChainMatch matchers to the ranking stage for correct outcomes

- .github/lock.yml
- .github/workflows/lock.yml
The Lock App [is unhealthy][1]. GitHub Actions now has [a better
security model][2] such that we think we can safely use it.
The time of day to run the action was randomly generated.
[1]: https://github.com/dessant/lock-threads-app/issues/2
[2]: https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
> Swap from the Lock GH App to lock-threads GH Action

- README.md
- examples/android/clientcache/build.gradle
- examples/android/helloworld/build.gradle
- examples/android/routeguide/build.gradle
- examples/android/strictmode/build.gradle
- examples/build.gradle
- examples/example-alts/build.gradle
- examples/example-gauth/build.gradle
- examples/example-hostname/build.gradle
- examples/example-jwt-auth/build.gradle
- examples/example-tls/build.gradle
- examples/example-xds/build.gradle
- settings.gradle
This version works around a warning about DuplicateStrategy in Gradle 6
that will be an error in Gradle 7 caused by [a bug in the plugin][1].
Bumping the version makes a clean build with `--warning-mode all` (at
least if skipping Android and codegen).
[1]: https://github.com/google/protobuf-gradle-plugin/issues/470
> Bump Protobuf Gradle Plugin to 0.8.16

- compiler/build.gradle
This fixes build on ppc64le on RHEL8 . As referenced in https://github.com/grpc/grpc-java/issues/7757
> fix build on ppc64le

- COMPILING.md
- build.gradle
- buildscripts/make_dependencies.bat
- buildscripts/make_dependencies.sh
- compiler/README.md
- examples/android/clientcache/app/build.gradle
- examples/android/helloworld/app/build.gradle
- examples/android/routeguide/app/build.gradle
- examples/android/strictmode/app/build.gradle
- examples/build.gradle
- examples/example-alts/build.gradle
- examples/example-gauth/build.gradle
- examples/example-gauth/pom.xml
- examples/example-hostname/build.gradle
- examples/example-hostname/pom.xml
- examples/example-jwt-auth/build.gradle
- examples/example-jwt-auth/pom.xml
- examples/example-tls/build.gradle
- examples/example-tls/pom.xml
- examples/example-xds/build.gradle
- examples/pom.xml
- repositories.bzl
Removed some references to the protobuf version from COMPILING.md and
compiler/README.md to make updates a tiny bit easier.
> Bump Protobuf to 3.17.2

- xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/RingHashLoadBalancerProvider.java
- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
- xds/src/test/java/io/grpc/xds/RingHashLoadBalancerProviderTest.java
Envoy uses default parameters for ring hash LB config (min_ring_size = 1024, max_ring_size = 8M). https://github.com/grpc/proposal/pull/239 is updated to use the same default as Envoy.
The change follows the way that C-core does this:
- gRPC's ring_hash LB config parser [sets default](https://github.com/grpc/grpc/blob/e8239ceb1d51f82513cf57d198c7895c4292ebd4/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.cc#L51-L52) values if the raw config does not specify min_ring_size or max_ring_size.
- Note, for us we need to do this in both ring_hash LB config parser and the CDS LB policy that instantiates the `RingHashConfig` directly.
/cc @apolcyn
> xds: use defaults for unspecified ring_hash_lb_config values

- netty/shaded/build.gradle
Previously it required manually listing the direct deps of grpc-netty
which is error-prone as evidinced by the fact that we were missing
multiple deps (guava, perfmark-api). This didn't cause a problem because
grpc-core happens to bring in these same deps.
> netty/shaded: Include deps automatically

- xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
- xds/src/main/java/io/grpc/xds/Endpoints.java
- xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
In xDS proto definition, the `load_balancing_weight` field of [LbEndpoint](https://github.com/grpc/grpc-java/blob/d4c31ffad4191afd08f6e1ddae790b90f5b24ebc/xds/third_party/envoy/src/main/proto/envoy/config/endpoint/v3/endpoint_components.proto#L108)) is optional. When parsing the LbEndpoint, the presence information is discarded. That is, if not specified in EDS, the parsed LbEndpoint will have a weight of 0. Then when computing the overall weights for endpoint-level load balancing (e.g., ring_hash), those endpoint will have an explicit attribute of 0 weight. This may cause trouble for the load balancing algorithm (e.g., in ring_hash if some endpoints have 0 weight, those endpoints will never have RPCs routed to; if all endpoints have 0 weight, the algorithm is broken).
The semantics of …
> xds: equally weight endpoints within locality if endpoint-level weight unspecified

- netty/shaded/build.gradle
https://github.com/johnrengelman/shadow/pull/543 fixed project support,
which means the workaround is no longer necessary.
> netty/shaded: Leverage shadow plugin's publishing support

- binder/src/main/java/io/grpc/binder/SecurityPolicy.java
Internally this was package visible to retain strict control
over the available policies. However, that kind of strict control
doesn't work with the open-source version, since projects will want
to create their own policies. E.g. There's at least one google-specific
policy internally.
> binder: Allow SecurityPolicy extensions.

- alts/build.gradle
- android-interop-testing/build.gradle
- android/build.gradle
- api/build.gradle
- auth/build.gradle
- binder/build.gradle
- build.gradle
- buildscripts/kokoro/unix.sh
- census/build.gradle
- core/build.gradle
- cronet/build.gradle
- examples/example-gauth/pom.xml
- examples/pom.xml
- grpclb/build.gradle
- interop-testing/build.gradle
- netty/build.gradle
- okhttp/build.gradle
- protobuf-lite/build.gradle
- protobuf/build.gradle
- rls/build.gradle
- services/build.gradle
- stub/build.gradle
- testing/build.gradle
- xds/build.gradle
failOnVersionConflict has never been good for us. It is equivalent to
Maven dependencyConvergence which we discourage our users to use because
it is too tempermental and _creates_ version skew issues over time.
However, we had no real alternative for determining if our deps would be
misinterpeted by Maven.
failOnVersionConflict has been a constant drain and makes it really hard
to do seemingly-trivial upgrades. As evidenced by protobuf/build.gradle,
in this change, it also caused _us_ to introduce a version downgrade.
This introduces our own custom requireUpperBoundDeps implementation so
that we can get back to simple dependency upgrades _and_ increase our
confidence in a consistent dependency tree.
-----
The main `build.gradle` is where the real changes are, but the rest would
have been …
> Replace failOnVersionConflict() with custom requireUpperBoundDeps

- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
Manually checks if the gRPCLB policy is already in fallback mode when trying to fallback due to receiving address update without LB addresses. 
Commit b956f8852d36adc54eb60649d7b82896b399d723 added an invariant check in the FallbackModeTask runnable to ensure the task is fired only when the LB is not already in fallback mode. However, that commit missed the case that receiving address updates without LB addresses can trigger the run of FallbackModeTask runnable, because the existing implementation chose to reuse the code in FallbackModeTask. In such case, running FallbackModeTask could break the invariant check as the LB policy may already in fallback mode.
This change eliminates the reuse of FallbackModeTask for handling address update without LB address. That is, every time receiving …
> grpclb: skip fallback if the LB is already in fallback mode (backport v1.38.x)

- api/src/main/java/io/grpc/InternalServerInterceptors.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
`interceptCallHandler()` and `interceptCallHandlerCreate()` appear to be exactly the same. Deleting the former.
> api: clean up duplicated method in InternalServerInterceptors

- netty/shaded/build.gradle
- netty/shaded/src/testShadow/java/io/grpc/netty/shaded/ShadingTest.java
This modifies the shading operation to transform native-image resources so they correctly reference shaded class names.
Fixes #7540.
cc/ @meltsufin
> Modify netty-shaded resources to reference shaded class names

- buildscripts/kokoro/xds-k8s-install-test-driver.sh
Makes it possible to use `TEST_DRIVER_REPO_OWNER` to clone test driver from a fork,  for debug purposes.
Simplifies dev workflow, so it's not necessary to make temporary "DO NOT MERGE" changes, [example](https://github.com/grpc/grpc/pull/26367/files#diff-b26061c1806481e73239048351181cd23e70fb1d3b29571113c8ad6501ac93c1L22-R24).
Related changes:
- https://github.com/grpc/grpc-java/pull/8265
- https://github.com/grpc/grpc/pull/26490
- https://github.com/grpc/grpc-go/pull/4548
- cl/379765815
> buildscripts: add option to use xds-k8s test driver from a fork

- interop-testing/src/test/java/io/grpc/testing/integration/StressTestClientTest.java
- services/src/test/java/io/grpc/protobuf/services/BinlogHelperTest.java
Because we are emulating aarch64 during testing the tests run slower
than normal. Bumping the timeout seems easy and obvious for
StressTestClientTest. The warmup for BinlogHelperTest mirrors what we've
done with timing-based tests in the past. Hopefully that is enough to
lower variance so that it passes consistently; seems likely. I'd rather
not increase the timing fuzziness if I can avoid it, as that reduces the
test's ability to detect issues.
Fixes #8135 (mostly+hopefully)
> Fix aarch64 emulation-triggered flakes

- netty/shaded/build.gradle
This is essentially re-adding #5901 after its behavior was "reverted"
in #8242. At the time grpc-core was the only dependency, so this change
only applies to grpc-core to make it a tiny bit easier to swap to
runtime scope in the future.
> netty-shaded: Use compile instead of runtime dep in pom for core

- netty/shaded/build.gradle
This is essentially re-adding #5901 after its behavior was "reverted"
in #8242. At the time grpc-core was the only dependency, so this change
only applies to grpc-core to make it a tiny bit easier to swap to
runtime scope in the future.
Backport of #8271
> netty-shaded: Use compile instead of runtime dep in pom for core (1.39.x backport)

- api/src/main/java/io/grpc/ForwardingServerBuilder.java
- api/src/main/java/io/grpc/ServerBuilder.java
- api/src/main/java/io/grpc/ServerCallExecutorSupplier.java
- core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
- core/src/main/java/io/grpc/internal/SerializingExecutor.java
- core/src/main/java/io/grpc/internal/ServerImpl.java
- core/src/main/java/io/grpc/internal/ServerImplBuilder.java
- core/src/test/java/io/grpc/internal/SerializingExecutorTest.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
For https://github.com/grpc/grpc-java/issues/7874
Technical strategy:
* Split StreamCreated() contextRunnable into two when this feature is needed: one for method lookup, the other for server call handling. methodLookup() runs on default executor, handleServerCall() may run on the executorSupplier executor.
*  callbacks are queued after methodLookup() and handleServerCall()
* Make executor settable in serializing executor to switch executor for the server call handling runnable as a result of the outcome of the method lookup runnable.
@ejona86  can I get your early feedback
tracking experimental API https://github.com/grpc/grpc-java/issues/8274
> core: allow per-service/method executor

- binder/src/androidTest/java/io/grpc/binder/BinderChannelSmokeTest.java
- binder/src/androidTest/java/io/grpc/binder/BinderSecurityTest.java
- binder/src/androidTest/java/io/grpc/binder/internal/BinderClientTransportTest.java
- binder/src/main/java/io/grpc/binder/AndroidComponentAddress.java
- binder/src/main/java/io/grpc/binder/ApiConstants.java
- binder/src/main/java/io/grpc/binder/BinderServerBuilder.java
- binder/src/main/java/io/grpc/binder/internal/BinderTransport.java
- binder/src/main/java/io/grpc/binder/internal/ServiceBinding.java
- binder/src/test/java/io/grpc/binder/AndroidComponentAddressTest.java
- binder/src/test/java/io/grpc/binder/BinderServerBuilderTest.java
- binder/src/test/java/io/grpc/binder/internal/ServiceBindingTest.java
By considering the binding Intent's action, data, type, identity and categories we align gRPC/Binder's addressing with Android's natural equivalence relation for "cached" IBinders.
> Update AndroidComponentAddress to wrap a binding Intent.

- core/src/main/java/io/grpc/internal/ServerImpl.java
- core/src/test/java/io/grpc/internal/ServerImplTest.java
Conformance failure due to blocking IO call (future.get())
[reproduced](https://fusion2.corp.google.com/invocations/7bd216bf-aebd-494a-83b4-238726e00c74/targets/%2F%2Fjavatests%2Fcom%2Fgoogle%2Fsocial%2Fboq%2Fhangouts%2Fbot%2Fbots%2Fomg%2Fdynamite%2Fbot%2Fspanner:inspection_conformance_test/tests) and [verified the fix](https://fusion2.corp.google.com/invocations/45574c99-d34e-460c-94b2-c52589ed8de8)
reference: go/boq-conformance-violations/BLOCKING#what-should-i-do-instead
> core: fix boq conformance failures

- xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
In 02ff64fa2 the SharedResourceHolder.get() was removed and it became
dead code.
> xds: Delete unused ScheduledExecutorService management code

- core/src/main/java/io/grpc/inprocess/InProcessTransport.java
- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/ClientStreamListener.java
- core/src/main/java/io/grpc/internal/DelayedStream.java
- core/src/main/java/io/grpc/internal/ForwardingClientStreamListener.java
- core/src/main/java/io/grpc/internal/InternalSubchannel.java
- core/src/main/java/io/grpc/internal/RetriableStream.java
- core/src/test/java/io/grpc/internal/AbstractTransportTest.java
- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
- core/src/test/java/io/grpc/internal/DelayedClientTransportTest.java
- core/src/test/java/io/grpc/internal/DelayedStreamTest.java
- core/src/test/java/io/grpc/internal/ForwardingClientStreamListenerTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- core/src/test/java/io/grpc/internal/NoopClientStreamListener.java
- core/src/test/java/io/grpc/internal/RetriableStreamTest.java
- cronet/src/test/java/io/grpc/cronet/CronetClientTransportTest.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
- netty/src/test/java/io/grpc/netty/NettyClientStreamTest.java
- netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
We used to have two `ClientStreamListener.closed()` methods. One is simply calling the other with default arg. This doubles debugging (e.g. #7921) and sometimes unit testing work. Deleting the 2-arg method to cleanup. 
This PR is purely refactoring.
> all: remove 2-arg ClientStreamListener.closed()

- binder/src/main/java/io/grpc/binder/AndroidComponentAddress.java
- binder/src/main/java/io/grpc/binder/internal/BinderTransportSecurity.java
Make BinderTransportSecurity.attachAuthAttrs public.
The class is internal, but make the method public so we can call it from
other internal packages. (Specifically google internal code being migrated to these APIs).
Also make AndroidComponentAddress non-final.
> binder: Updates to support migrations to this API from internal versions.

- binder/src/main/java/io/grpc/binder/AndroidComponentAddress.java
- binder/src/main/java/io/grpc/binder/internal/BinderTransport.java
- binder/src/main/java/io/grpc/binder/internal/BoundClientAddress.java
- binder/src/main/java/io/grpc/binder/internal/LeakSafeOneWayBinder.java
All marked with Internal to make it clear these APIs shouldn't be used normally.
> binder: More exposed APIs to support internal transition.

- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
It would be helpful to debug with the gRPC-LB's initial response info.
Change the log level to INFO so we can see this log in the ChannelTracer.
> Add Info log for gRPC-LB's initial response

- xds/src/main/java/io/grpc/xds/internal/sds/SslContextProviderSupplier.java
- xds/src/test/java/io/grpc/xds/internal/sds/SslContextProviderSupplierTest.java
This PR fixes the race condition where a `SslContextProviderSupplier` is returned for an inbound-connection and before the handshake for the connection starts, xDS replaces the listener content because of which the `SslContextProviderSupplier` is closed. With this change, the `SslContextProviderSupplier` will just re-allocate the SslContextProvider and release after the callback.
> xds: fix the race condition in SslContextProviderSupplier's updateSslContext and close

- testing/src/main/java/io/grpc/testing/GrpcCleanupRule.java
- testing/src/main/java/io/grpc/testing/GrpcServerRule.java
The previous text did explain to use GrpcCleanupRule, but a user just
skimming might not read the long paragraph. Now we have a TL;DR.
-----
Based on feedback from @charlesmunger.
I tried using `@deprecated` just in the javadoc to make things more obvious without causing compilation warnings, but the generated javadoc had `Deprecated` plastered on every method and was more "scary" than I was hoping for. So let's do this and see how things go.
> testing: Make more obvious that GrpcServerRule has been replaced

- binder/src/main/java/io/grpc/binder/AndroidComponentAddress.java
This returns the address as an "android-app://" uri, which can be used with AndroidAppNameResolverProvider, allowing the address of a binderserver to be passed around.
> Add an asAndroidAppUri() method to AndroidComponentAddress.

- core/src/main/java/io/grpc/util/CertificateUtils.java
This change adds a try-finally block around readers and streams
to control the closing of those objects when the method has completed
rather than relying on the GC to close them.
This issue was flagged by an analysis tool via binary analysis of the
grpc-core package as part of a dependency from another project.
fixes #8311
> core: correcting a minor resource releasing issue

- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
This has been wrong since the introduction of the code in df357cb8.
Noticed as part of https://github.com/grpc/grpc-go/pull/4491 . The error
text is generally ASCII, so this probably doesn't matter much.
> netty: Use charset=utf-8, not encoding=utf-8 for error pages

- api/src/main/java/io/grpc/NameResolverProvider.java
- api/src/main/java/io/grpc/NameResolverRegistry.java
- api/src/test/java/io/grpc/NameResolverRegistryTest.java
- xds/src/test/java/io/grpc/xds/XdsSdsClientServerTest.java
Part of https://github.com/grpc/grpc-java/issues/7133.
It makes scheme matching more explicit in name resolver API. It slightly changed the existing behaviour because in this PR we pick effective providers early/when refreshing.
But it should not change effectiveness of e.g. `SecretGrpclbNameResolverProvider`.
> api: use <scheme,provider> map in nameResoverRegistry

- README.md
- examples/android/clientcache/build.gradle
- examples/android/helloworld/build.gradle
- examples/android/routeguide/build.gradle
- examples/android/strictmode/build.gradle
- examples/build.gradle
- examples/example-alts/build.gradle
- examples/example-gauth/build.gradle
- examples/example-hostname/build.gradle
- examples/example-jwt-auth/build.gradle
- examples/example-tls/build.gradle
- examples/example-xds/build.gradle
- settings.gradle
We may/could remove the 'idea' plugin. I tried removing it locally, I don't see any problem for example projects. But grpc modules might have something more complicated.
> Bump Protobuf Gradle Plugin to 0.8.17

- api/src/main/java/io/grpc/ServerCallHandler.java
- Focus the summary fragment
- Clarify that implementations don't just have access to "call" and "headers" while running -- they in fact take ownership of these arguments from the caller.
- Discuss the owner's obligation to close()
- Make explicit the caller's obligation to the returned Listener.
> Clarify the ServerCallHandler API contract.

- buildscripts/kokoro/xds_url_map.cfg
- buildscripts/kokoro/xds_url_map.sh
Related PR https://github.com/grpc/grpc/pull/26764
Related CL cl/386366746
This test suite will be run every 6 hours, and takes around 30 minutes. The script is copied from `xds-k8s.sh`, and removed the generation of server image.
> Add xDS k8s url-map Kokoro job

- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestClient.java
- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
Extend XdsTestServer features as specified in go/xds-retry-interop-test
See also xds retry interop test case implementation https://github.com/grpc/grpc/pull/26746
Previously, rpc-behavior values in the request headers are handled in tow different places, one in interceptor and the other in service implementation via Context. I moved all the rpc-behavior handling in interceptor, Context is not needed any more.
> interop-testing: extend XdsTestServer features to support retry test

- buildscripts/kokoro/xds_url_map.cfg
> buildscripts: Fix a typo in xds_url_map.cfg

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
This is a workaround for b/194730975 . LDS update from TD has  empty defaultValidationContext. But this is a long standing behavior so gRPC in the mean time should accept it and check that it is empty (until there is a fix in TD)
> xds: accept an empty defaultValidationContext to support TD sending an LDSupdate like that

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
Protobuf fields will never be null.
go/bugpattern/ProtoFieldNullComparison
> xds: stop checking if protos are null

- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
Nginx and C core don't do graceful GOAWAY and retries have matured such
that transparent retries may soon be on by default. Refining the
workaround thus can reduces error rate for users.
Fixes #8310
----
CC  @c-s-t-z @hijerusalem
> netty: Refine workaround for Netty header processing for transparent retries

- api/src/main/java/io/grpc/ProxyDetector.java
NameResolver.Helper was a short-lived class that didn't get very far. We
chose NameResolver.Args instead and didn't mirror LoadBalancer.
> api: Fix Javadoc reference to NameResolver.Args

- build.gradle
Including the build user's name doesn't provide much value and may
surprise some people. Built-JDK is actually wrong, as it is reporting
Gradle's Java version, not the javac version. And Source-/Target-
Compatibility isn't useful if nobody looks at it. Generally people just
look at the bytecode version itself, which is much more reliable and
doesn't have questions as to whether it should be '8' or '1.8'.
> build.gradle: Remove non-standard MANIFEST.MF attributes

- buildscripts/kokoro/android.sh
- cronet/build.gradle
Binder's :build was missing. Cronet build failed without specifying
Java 8 because of the transitive Guava dependency.
-----
This will still fail to build until the `newStream()` API changes are integrated in the binder instrumentation tests. But as soon as that is in this should begin working (tested on older commit). I'll delay merging this until the newStream fixes are in and confirmed CI goes green.
> buildscripts: Build android instrumentation tests in android CI

- binder/src/androidTest/java/io/grpc/binder/internal/BinderClientTransportTest.java
This is backport of #8366 
The binder module fail to compile because in #8355, the class BinderClientTransportTest was not refactored correspondingly.
> binder: fix binder build (backport v1.40.x)

- core/src/main/java/io/grpc/util/CertificateUtils.java
This reverts commit b9becb5c8e797f202ed0e566e752bd7a91e599e1. It is the
caller's responsibility to close their InputStream. The change ended up
closing the passed InputStream.
-----
This is a backport of #8361
> Revert "core: correcting a minor resource releasing issue" (v1.40.x backport)

- xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
- xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java
Fix the NPE caused when `server-listener-resource-name-template` is not set in the bootstrap file. Fixes #8373
> xds: log error and fail start() if server-listener-resource-name-template not set or not using xds_v3

- xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
- xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java
Fix the NPE caused when server-listener-resource-name-template is not set in the bootstrap file. Fixes #8373
> xds: log error and fail start() if server-listener-resource-name-template not set or not using xds_v3 (backport to v1.39.x) (#8375)

- xds/src/main/java/io/grpc/xds/XdsClientWrapperForServerSds.java
- xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java
Fix the NPE caused when server-listener-resource-name-template is not set in the bootstrap file. Fixes #8373
> xds: log error and fail start() if server-listener-resource-name-template not set or not using xds_v3 (backport to 1.40.x) (#8375)

- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/test/java/io/grpc/internal/GrpcUtilTest.java
Fix a bug introduced in #8355 : old ClientStreamTracer.Factory implementation creates tracers twice.
> core: fix old ClientStreamTracer.Factory creating tracers twice

- netty/src/test/java/io/grpc/netty/NettyServerTest.java
Uncomments an assert in a test which was not possible previously
> netty: removes TODO in test for NettyServer

- core/src/main/java/io/grpc/internal/RetriableStream.java
There is a bug in the scenario of the following sequence of events:
- `call.start()` 
- received retryable status and about to retry
- The retry attempt Substream is created but not yet `drain()` 
- `call.cancel()`
But `stream.cancel()` cannot be called prior to `stream.start()`, otherwise retry will cause a failure with IllegalStateException. The current RetriableStream code must be fixed to not cancel a stream until `start()` is called in `drain()`.
> core: fix bug RetriableStream cancel() racing with start()

- api/src/main/java/io/grpc/Server.java
> api: Clarify Server APIs can be used before start()

- binder/build.gradle
Not using `@Ignore` because the tests can probably run successfully
under Bazel.
See #8391
> binder: Disable flaky SecurityPolicy tests

- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- stub/src/main/java/io/grpc/stub/MetadataUtils.java
We don't want other APIs to copy the stub-based API to attach the
interceptor. The API has a shorter name, but isn't actually all that
easier to use and isn't fluent like using the interceptor API.
These are _very_ old methods, so we won't be quick to delete them. Seems
we should have them deprecated at least a year or two; they are easy to
maintain in the mean time.
See API Review notes in #1789
> stub: Mark Stub-based MetadataUtils methods deprecated

- core/src/main/java/io/grpc/internal/RetriableStream.java
- core/src/test/java/io/grpc/internal/RetriableStreamTest.java
While adding regression tests to #8386, I found a bug in an edge case: while retry attempt is draining the last buffered entry, if it is in the mean time committed and then we cancel the call, the stream will never be cancelled. See the regression test case `commitAndCancelWhileDraining()`.
Although we can add regression test that reproduces any bug we found, we can not really unit-test race condition, so I try to make the concurrency control logic simple and readably, but it's still hard to prove the correctness, nay...
> core: fix RetriableStream edge case bug introduced in #8386

- core/src/main/java/io/grpc/internal/RetriableStream.java
- core/src/test/java/io/grpc/internal/RetriableStreamTest.java
This is backport of #8386 and #8393
> core: backport RetriableStream bug fix (backport v1.40.x)

- api/src/main/java/io/grpc/NameResolver.java
> api: Document that NameResolvers shouldn't block

- rls/src/main/java/io/grpc/rls/RlsLoadBalancer.java
~ClusterState.result may be null in `CdsLoadBalancer2`,can add not-null check to result to avoid NullPointerException, thanks~
`routeLookupClient` may be null in `RlsLoadBalancer.requestConnection()`
> rls: fix routeLookupClient may be null in RlsLoadBalancer.requestConnection()

- api/src/main/java/io/grpc/ManagedChannelBuilder.java
- core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
Stabilize `enableRetry()` and `disableRetry()`.
Disable retry in `ManagedChannelImplTest` because each call attempt will fork the headers to a new instance, and add a ClientStreamTracer.Factory for bufferSizeLimit in CallOptions, which makes verification not straightforward.
> core: enable retry by default

- api/src/main/java/io/grpc/ClientStreamTracer.java
- api/src/main/java/io/grpc/ManagedChannelBuilder.java
- census/src/main/java/io/grpc/census/CensusStatsModule.java
- census/src/main/java/io/grpc/census/CensusTracingModule.java
- census/src/test/java/io/grpc/census/CensusModulesTest.java
- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
- core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java
- core/src/main/java/io/grpc/internal/OobChannel.java
- core/src/main/java/io/grpc/internal/RetriableStream.java
- core/src/main/java/io/grpc/internal/SubchannelChannel.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- core/src/test/java/io/grpc/internal/RetriableStreamTest.java
- interop-testing/build.gradle
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
This backports
#8403 xds: enable xDS retry by default
#8402  core: enable retry by default  
#8401 core: fix retry flow control issue  
#8362 all: implement retry stats 
to v1.40.x
> [backport to v1.40.x] retry changes: retry stats impl, bug fix, enable retry by default

- buildscripts/kokoro/xds_url_map.sh
As title. Related b/196290351.
- xds_url_map: https://fusion2.corp.google.com/invocations/e43946b2-19fc-47b2-a045-02b6a87a8d7d/targets
- xds-k8s: https://fusion2.corp.google.com/invocations/c6dd2e77-551f-44f3-8a35-b150cc9f21fe/targets
> Fix branch name missing error in xds_url_map

- buildscripts/kokoro/android.sh
We've still been seeing random memory-related failures with the Android
CI, but it is nowhere near as severe as it was. But even when running
locally with "-Xmx512m -XX:MaxMetaspaceSize=512m" I get failures. Our CI
environment has lots of RAM; let's use it.
See also trouble in #8388
CC @nastra
> buildscripts: Increase memory for Gradle in Android CI

- core/BUILD.bazel
- core/src/main/java/io/grpc/util/AdvancedTlsX509KeyManager.java
- core/src/main/java/io/grpc/util/AdvancedTlsX509TrustManager.java
- netty/src/test/java/io/grpc/netty/AdvancedTlsTest.java
This pull request adds the following classes to `io.grpc.util`:
1. an `AdvancedTlsX509TrustManager` that supports 
-  reloading root certificates from the file system or memory
-  disabling host name verification check, and applying any custom-implemented  in-handshake verification checks 
2. an `AdvancedTlsX509KeyManager` that supports
-  reloading identity credentials(private key and certificate chain)  from the file system or memory
This also adds the integration tests to `io.grpc.netty`.
> advancedtls: adding AdvancedTlsX509TrustManager and AdvancedTlsX509KeyManager

- netty/shaded/build.gradle
Seems it was introduced unnecessarily in dc74a31b. This also removes the
jcenter reference which is a repository that no longer receives updates.
----
I noticed this when looking at upgrading the android plugin (because of the jcenter usage).
CC nastra
> netty: Don't use old-style classpath for shadow plugin

- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestClient.java
`logger.log(Level.WARNING, "Rpc failed: {0}", t)` will just print a literal "Rpc failed: {0}" followed by exception details.
> interop-testing: fix literal "{0}" in log message

- buildscripts/kokoro/xds_url_map.cfg
As title. We recently had one flake caused by the Kokoro job timeout.
@dapengzhang0
> fix: extend the xds_url_map job's timeout to 90 minutes

- buildscripts/kokoro/xds_url_map.cfg
Related https://github.com/grpc/grpc-java/pull/8429.
We recently had one flake caused by the Kokoro job timeout.
@dapengzhang0
> backport fix v1.40.x: extend the xds_url_map job's timeout to 90 minutes

- xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
This is a minimum fix. Would have fixed to disable the logic in parsing RDS update (hashPolicies) and CDS update (ring_hash lb) by the protection flag, but they are scattered in main source and tests. The parsing logic seemed to work fine in tests in later release.
> xds: fix RingHash LB null pointer issue [v1.39.x]

- xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
This is a minimum fix. Would have fixed to disable the logic in parsing RDS update (hashPolicies) and CDS update (ring_hash lb) by the protection flag, but they are scattered in main source and tests. The parsing logic seemed to work fine in tests in later release.
> xds: fix RingHash LB null pointer issue [v1.37.x]

- stub/src/main/java/io/grpc/stub/ClientCallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java
- stub/src/main/java/io/grpc/stub/StreamObserver.java
Missing docs were brought up in #8423
CC @morgwai
> stub: Document StreamObserver is an async API

- buildscripts/kokoro/xds_url_map.sh
Part of grpc/grpc#27189 and b/198291728.
By disabling the workload identity, we should be able to run tests faster and avoid future IAM policy size issue.
@dapengzhang0 PTAL.
Kokoro run: https://fusion2.corp.google.com/invocations/b52b1684-47de-406d-a9f6-644909755f34/targets
> Change to a non-workload-identity GKE cluster

- buildscripts/kokoro/xds_url_map.sh
Part of grpc/grpc#27189 and b/198291728.
By disabling the workload identity, we should be able to run tests faster and avoid future IAM policy size issue.
@dapengzhang0 PTAL.
Kokoro run: https://fusion2.corp.google.com/invocations/afb37d8a-0c11-43a5-ad55-f6ead4d680f7/targets
> [Backport v1.40.x] Change to a non-workload-identity GKE cluster

- xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java
Per internal suggestion:
> Methods and non-static variables should be named in lowerCamelCase.
> xds: fix java style

- xds/src/main/java/io/grpc/xds/Bootstrapper.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/internal/certprovider/CertProviderClientSslContextProvider.java
- xds/src/main/java/io/grpc/xds/internal/certprovider/CertProviderServerSslContextProvider.java
- xds/src/main/java/io/grpc/xds/internal/certprovider/CertProviderSslContextProvider.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/internal/sds/CommonTlsContextTestsUtil.java
Changes to comply with https://github.com/grpc/proposal/blob/master/A29-xds-tls-security.md . Specifically:
- check that cert-instance-name in CDS/LDS are defined in bootstrap file
- a number of fields are now ignored instead of NACKed (as per https://github.com/grpc/proposal/blob/master/A29-xds-tls-security.md#xds-protocol - look for "are ignored")
- additional check for transport-socket-matches - NACK if present
> xds: fix implementation to comply with gRFC for security

- core/src/main/java/io/grpc/internal/MessageFramer.java
Minor PR, but the comment confused me a bit while understanding the code since it seems to be pointing to the wrong method.
> Fix drift in MessageFramer comment

- census/src/main/java/io/grpc/census/CensusStatsModule.java
- interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java
(This is a modified version of #8422 using a lock for synchronization.)
There is data race in `CensusStatsModule. CallAttemptsTracerFactory`:
If client call is cancelled while an active stream on the transport is not committed, then a [noop substream](https://github.com/grpc/grpc-java/blob/v1.40.0/core/src/main/java/io/grpc/internal/RetriableStream.java#L486) will be committed and the active stream will be cancelled. Because the active stream cancellation triggers the stream listener closed() on the _transport_ thread, the closed() method can be invoked concurrently with the call listener onClose(). Therefore, one `CallAttemptsTracerFactory.attemptEnded()` can be called concurrently with `CallAttemptsTracerFactory.callEnded()`, and there could be data race on RETRY_DELAY_PER_CALL. See …
> census: Fix retry stats data race (v2)

- xds/src/main/java/io/grpc/xds/SharedCallCounterMap.java
- xds/src/test/java/io/grpc/xds/SharedCallCounterMapTest.java
Fixes #8397.
#8397 is caused by mistakenly clearing up a map entry right after the entry is recreated after gc. Reproduced in regression test.
(`SharedCallCounterMap` is hard to read and can easily be a source of bugs. It's impossible to sufficiently test the class with unit test because GC can happen anytime concurrently with the method being tested. I'm not 100% confident about the correctness of the fix. If possible I would avoid using WeakReference in the first place.)
> xds: Fix WeakReference bug in SharedCallCounterMap

- xds/src/main/java/io/grpc/xds/SharedCallCounterMap.java
- xds/src/test/java/io/grpc/xds/SharedCallCounterMapTest.java
Backport of #8466 
Fixes #8397.
#8397 is caused by mistakenly clearing up a map entry right after the entry is recreated after gc. Reproduced in regression test.
> xds: Fix WeakReference bug in SharedCallCounterMap [backport v1.40.x]

- netty/shaded/build.gradle
- netty/shaded/src/testShadow/java/io/grpc/netty/shaded/ShadingTest.java
This renames the netty-shaded resource folder to avoid configuration collisions with standard netty. Followup to: https://github.com/grpc/grpc-java/pull/8258#discussion_r652729213
> Rename netty-shaded native resources directory to avoid collisions

- core/src/main/java/io/grpc/internal/MessageDeframer.java
- core/src/test/java/io/grpc/internal/MessageDeframerTest.java
`SizeEnforcingInputStream` is applied on the decompressed stream. It looks like it has been the case since it was introduced in https://github.com/grpc/grpc-java/commit/15f02ba19c4a2c21afee39cb73cd0340ad2f9d1d.
> core: clarify exception message

- xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
- xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java
For v1.41.x PSM security needs to be enabled by default
CC @ejona86
> xds: enable PSM security by default

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
- Envoy ignores white spaces in `retryOn` field
https://github.com/envoyproxy/envoy/blob/v1.19.1/source/common/router/retry_state_impl.cc#L166
We should do the same.
- Envoy ignores unsupported values https://github.com/envoyproxy/envoy/blob/v1.19.1/source/common/router/config_impl.cc#L89-L90
and we should do the same.
> xds: fix parsing retryOn values

- buildscripts/kokoro/xds.cfg
- buildscripts/kokoro/xds_v3.cfg
> Extend the xDS interop tests timeout to 360 mins [backport v1.37.x]

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
Backport of #8477 
- Envoy ignores white spaces in `retryOn` field
https://github.com/envoyproxy/envoy/blob/v1.19.1/source/common/router/retry_state_impl.cc#L166
We should do the same.
- Envoy ignores unsupported values https://github.com/envoyproxy/envoy/blob/v1.19.1/source/common/router/config_impl.cc#L89-L90
and we should do the same.
> xds: fix parsing retryOn values [backport v1.40.x]

- buildscripts/kokoro/xds.cfg
- buildscripts/kokoro/xds_v3.cfg
> Extend the xDS interop tests timeout to 360 mins [backport v1.36.x]

- buildscripts/kokoro/xds.cfg
> Extend the xDS interop tests timeout to 360 mins [backport v1.35.x]

- buildscripts/kokoro/xds.cfg
> Extend the xDS interop tests timeout to 360 mins [backport v1.34.x]

- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientV3Test.java
- xds/src/test/java/io/grpc/xds/FilterChainMatchingProtocolNegotiatorsTest.java
- xds/src/test/java/io/grpc/xds/RbacFilterTest.java
- xds/src/test/java/io/grpc/xds/internal/sds/ClientSslContextProviderFactoryTest.java
- xds/src/test/java/io/grpc/xds/internal/sds/CommonTlsContextTestsUtil.java
- xds/third_party/envoy/import.sh
- xds/third_party/envoy/src/main/proto/envoy/api/v2/listener/listener_components.proto
- xds/third_party/envoy/src/main/proto/envoy/config/accesslog/v3/accesslog.proto
- xds/third_party/envoy/src/main/proto/envoy/config/bootstrap/v3/bootstrap.proto
- xds/third_party/envoy/src/main/proto/envoy/config/cluster/v3/cluster.proto
- xds/third_party/envoy/src/main/proto/envoy/config/core/v3/protocol.proto
- xds/third_party/envoy/src/main/proto/envoy/config/endpoint/v3/endpoint_components.proto
- xds/third_party/envoy/src/main/proto/envoy/config/listener/v3/api_listener.proto
- xds/third_party/envoy/src/main/proto/envoy/config/listener/v3/listener.proto
- xds/third_party/envoy/src/main/proto/envoy/config/listener/v3/listener_components.proto
- xds/third_party/envoy/src/main/proto/envoy/config/overload/v3/overload.proto
- xds/third_party/envoy/src/main/proto/envoy/config/rbac/v3/rbac.proto
- xds/third_party/envoy/src/main/proto/envoy/config/route/v3/route.proto
- xds/third_party/envoy/src/main/proto/envoy/config/route/v3/route_components.proto
- xds/third_party/envoy/src/main/proto/envoy/extensions/filters/common/fault/v3/fault.proto
- xds/third_party/envoy/src/main/proto/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
- xds/third_party/envoy/src/main/proto/envoy/extensions/transport_sockets/tls/v3/common.proto
- xds/third_party/envoy/src/main/proto/envoy/extensions/transport_sockets/tls/v3/tls.proto
- xds/third_party/envoy/src/main/proto/envoy/type/matcher/v3/string.proto
Update the envoy protos import to rev to c223756b0856f734a6a5cff2d0b95388cd2583d4 to get the latest definitions in envoy/extensions/transport_sockets/tls/v3/tls.proto and envoy/extensions/transport_sockets/tls/v3/common.proto related to new certProviderPluginInstance definitions. This corresponds to the latest internal import cl/394493931
> xds: update Envoy protos to a later revision for the new CertificateProvider definitions

- RELEASING.md
- buildscripts/build_docker.sh
- buildscripts/grpc-java-artifacts/Dockerfile
- buildscripts/make_dependencies.sh
- buildscripts/run_in_docker.sh
Backport of #7693
than nothing.
> Build Linux artifacts using CentOS 7 [backport v1.33.x]

- repositories.bzl
- rls/BUILD.bazel
- rls/build.gradle
- rls/src/main/java/io/grpc/rls/RlsProtoConverters.java
- rls/src/main/java/io/grpc/rls/RlsProtoData.java
- rls/src/main/java/io/grpc/rls/RlsRequestFactory.java
- rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
- rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
- rls/src/test/java/io/grpc/rls/RlsProtoConvertersTest.java
- rls/src/test/java/io/grpc/rls/RlsRequestFactoryTest.java
The [`server` and `path` fields](https://github.com/grpc/grpc-java/blob/v1.40.1/rls/src/main/proto/grpc/lookup/v1/rls.proto#L25-L32) in `RouteLookupRequest` are deprecated. Instead, we will send the server/path information in side of [`key_map`](https://github.com/grpc/grpc-java/blob/v1.40.1/rls/src/main/proto/grpc/lookup/v1/rls.proto#L45).
The keys for the server, service and method in the `key_map` will be the _values_ of `host`, `service`, `method` fields respectively in [`extraKeys`](https://github.com/grpc/grpc-java/blob/v1.40.1/rls/src/main/proto/grpc/lookup/v1/rls_config.proto#L69) in RlsConfig.
We will also include all entries in the [`constantKey`](https://github.com/grpc/grpc-java/blob/v1.40.1/rls/src/main/proto/grpc/lookup/v1/rls_config.proto#L80) in RlsConfig into …
> rls: migrate deprecated server/path to extraKeys

- core/src/main/java/io/grpc/util/AdvancedTlsX509KeyManager.java
- core/src/main/java/io/grpc/util/AdvancedTlsX509TrustManager.java
- netty/src/test/java/io/grpc/netty/AdvancedTlsTest.java
This is intended to fix https://github.com/grpc/grpc-java/issues/8454.
The problem was because at the time we scheduled the thread for the client, we didn't reserve enough time before starting the connection, so there could be a situation where the handshake has established, while the client hasn't finished its first read/reload yet. 
I added the code to sleep for 5 seconds and then begin our connection. Ideally, to fully remove the race condition, we might need some ways for the reloading thread telling us that the first read has been completed in the main test. But I can't think of any way that won't introduce any changes to the main code(I assume it is a bad practice to change code under "src" to better fit code under "test").
I've verified internally that this changes worked fine by …
> fix a flaky test in advanced TLS

- xds/src/main/java/io/grpc/xds/internal/sds/SslContextProviderSupplier.java
hashCode and equals() based on members of `SslContextProviderSupplier` is brittle because of mutation of the members. Leave them as `Object`'s impls.
Needs to be backported to 1.41 too
> xds: remove hashCode() and equals() for SslContextProviderSupplier

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/internal/certprovider/CertProviderClientSslContextProvider.java
- xds/src/main/java/io/grpc/xds/internal/certprovider/CertProviderServerSslContextProvider.java
- xds/src/main/java/io/grpc/xds/internal/certprovider/CertProviderSslContextProvider.java
- xds/src/main/java/io/grpc/xds/internal/sds/CommonTlsContextUtil.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientV2Test.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientV3Test.java
- xds/src/test/java/io/grpc/xds/internal/certprovider/CertProviderClientSslContextProviderTest.java
- xds/src/test/java/io/grpc/xds/internal/certprovider/CertProviderServerSslContextProviderTest.java
- xds/src/test/java/io/grpc/xds/internal/sds/CommonTlsContextTestsUtil.java
After importing the new protos (definitions) in PR #8490 this PR uses the new fields as per the gRFC [A29](https://github.com/grpc/proposal/blob/master/A29-xds-tls-security.md#xds-protocol). Specifically:
- use [`tls_certificate_provider_instance`](https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/transport_sockets/tls/v3/tls.proto#L247) if present
- use [`ca_certificate_provider_instance`](https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/transport_sockets/tls/v3/common.proto#L315) if present in either [`validation_context`](https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/transport_sockets/tls/v3/tls.proto#L261) or [`combined_validation_context.default_validation_context`](https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensio …
> xds: use the new cert-provider instances if present

- xds/src/main/java/io/grpc/xds/internal/sds/SslContextProviderSupplier.java
Backport of #8496 
hashCode and equals() based on members of SslContextProviderSupplier is brittle because of mutation of the members. Leave them as Object's impls.
> xds: remove hashCode() and equals() for SslContextProviderSupplier [backport v1.41.x] 

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/internal/certprovider/CertProviderClientSslContextProvider.java
- xds/src/main/java/io/grpc/xds/internal/certprovider/CertProviderServerSslContextProvider.java
- xds/src/main/java/io/grpc/xds/internal/certprovider/CertProviderSslContextProvider.java
- xds/src/main/java/io/grpc/xds/internal/sds/CommonTlsContextUtil.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientV2Test.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientV3Test.java
- xds/src/test/java/io/grpc/xds/internal/certprovider/CertProviderClientSslContextProviderTest.java
- xds/src/test/java/io/grpc/xds/internal/certprovider/CertProviderServerSslContextProviderTest.java
- xds/src/test/java/io/grpc/xds/internal/sds/CommonTlsContextTestsUtil.java
backport of #8494
After importing the new protos (definitions) in PR #8490 this PR uses the new fields as per the gRFC A29. Specifically:
use tls_certificate_provider_instance if present
use ca_certificate_provider_instance if present in either validation_context or combined_validation_context.default_validation_context
Various validations and translations take into account the above.
> xds: use the new cert-provider instances if present [backport v1.41.x]

- stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java
setOnCancelHandler tells gRPC that the application is handling
cancellation. But it's fine to have noop behavior within the handler
itself if the application doesn't need it. It is just a way to opt-in to
the more recent no-exception-from-onNext behavior. Let's mention this
use-case in the docs to make it more obvious it is a possibility.
Came up as part of #8409.
CC @morgwai
> stub: Document that noop onCancelHandler is useful

- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/main/java/io/grpc/xds/internal/Matchers.java
- xds/src/test/java/io/grpc/xds/internal/MatcherTest.java
https://github.com/envoyproxy/envoy/blob/0fae6970ddaf93f024908ba304bbd2b34e997a51/source/common/http/header_utility.cc#L130
> xds: fix header matcher for null value

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
Implementing [gRFC A46](https://github.com/grpc/proposal/pull/260)
> xds: apply valid resources while NACKing update

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
Envoy RetryPolicy with empty retryOn should not be ignored as no retry config when selecting Route config. Therefore, if xDS update for a route contains a RetryPolicy that has no RetryOn value that we support, but the virtual host config does, xds client should choose the Envoy RetryPolicy from the route (even with no RetryOn), rather than choosing the one from virtual host, and try to convert it into grpc RetryPolicy, and end up with no retry.
> xds: populate envoy RetryPolicy with no retryOn to resolver

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
Backport of #8511 
Envoy RetryPolicy with empty retryOn should not be ignored as no retry config when selecting Route config. Therefore, if xDS update for a route contains a RetryPolicy that has no RetryOn value that we support, but the virtual host config does, xds client should choose the Envoy RetryPolicy from the route (even with no RetryOn), rather than choosing the one from virtual host, and try to convert it into grpc RetryPolicy, and end up with no retry.
> xds: populate envoy RetryPolicy with no retryOn to resolver [backport v1.41.x]

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
Backport of #8511
Envoy RetryPolicy with empty retryOn should not be ignored as no retry config when selecting Route config. Therefore, if xDS update for a route contains a RetryPolicy that has no RetryOn value that we support, but the virtual host config does, xds client should choose the Envoy RetryPolicy from the route (even with no RetryOn), rather than choosing the one from virtual host, and try to convert it into grpc RetryPolicy, and end up with no retry.
> xds: populate envoy RetryPolicy with no retryOn to resolver [backport v1.40.x]

- census/src/main/java/io/grpc/census/CensusStatsModule.java
- census/src/main/java/io/grpc/census/InternalCensusStatsAccessor.java
- census/src/test/java/io/grpc/census/CensusModulesTest.java
- core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java
- core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java
- netty/src/main/java/io/grpc/netty/InternalNettyChannelBuilder.java
- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
Resolves b/197648853 for internal performance regression. Reporting retry stats caused significant amount of performance overhead internally.
> all: add internal API to disable retry stats

- api/src/main/java/io/grpc/Metadata.java
- netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java
- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
Although this is part of HTTP/2 and should have already been handled
already, it was noticed as part of RBAC work to avoid matching
hop-by-hop headers. See gRFC A41.
> netty: Requests with Connection header are malformed

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
Backport of #8506
Implementing [gRFC A46](https://github.com/grpc/proposal/pull/260)
> xds: apply valid resources while NACKing update [backport v1.41.x]

- api/src/main/java/io/grpc/Status.java
Removes the ExperimentalApi annotation from this call.
Contributes to: #4683
> api: Stabilize the Status.asException() call.

- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/main/java/io/grpc/internal/ServerCallImpl.java
- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
- core/src/test/java/io/grpc/internal/ServerCallImplTest.java
Since netty version v4.1.67, content-lenght header validation will be [enforced](https://github.com/Scottmitch/netty/commit/89c241e3b1795ff257af4ad6eadc616cb2fb3dc4#diff-09d9f8d0eacbca5a34ea3b3d3817b0adc115bf21d7908e976447073df0fd92fc). So once grpc upgrades netty to that version or above, RPCs with invalid content-length header will fail. 
Some libraries such as HTTP to gRPC adapters blindly copy all HTTP headers to gRPC metadata, but the content-length header is one of those that shouldn't be forwarded because gRPC uses different encoding. This mistake has already been in existence for a long time. 
Discard outbound content-length headers in gRPC, so that users who encounter invalid content-length issue when upgrading grpc-java version on server/client side would be able to workaround …
> core: discard outbound content-length header

- netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java
- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
We want to know the single, unambiguous authority for the request. If
there is no authority, we use host instead. While authority would be
most typical for HTTP/2, requests proxied from HTTP/1 may use host
instead of authority.
This is generally useful, but the impetus is RBAC. See gRFC A41.
> netty: Support Host header on server-side

- netty/src/main/java/io/grpc/netty/GracefulServerCloseCommand.java
- netty/src/main/java/io/grpc/netty/InternalGracefulServerCloseCommand.java
- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
- netty/src/main/java/io/grpc/netty/WriteBufferingAndExceptionHandler.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
- xds/src/main/java/io/grpc/xds/FilterChainMatchingProtocolNegotiators.java
- xds/src/main/java/io/grpc/xds/FilterChainSelectorManager.java
- xds/src/main/java/io/grpc/xds/InternalXdsAttributes.java
- xds/src/main/java/io/grpc/xds/XdsServerBuilder.java
- xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
- xds/src/test/java/io/grpc/xds/FilterChainMatchingProtocolNegotiatorsTest.java
- xds/src/test/java/io/grpc/xds/FilterChainSelectorManagerTest.java
- xds/src/test/java/io/grpc/xds/XdsClientWrapperForServerSdsTestMisc.java
- xds/src/test/java/io/grpc/xds/XdsServerBuilderTest.java
- xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java
This is necessary to make sure all connections are using the new
configuration.
CC @dapengzhang0, if you want to take a glance at the Netty changes
> xds: Drain old server connections on Listener updates

- api/src/main/java/io/grpc/Metadata.java
- netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java
- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
This reverts commit 6e89919e3265eadd33dc7e154ba291d46563f286.
This was found to break a test proxy. We'll work on fixing the proxy and
then roll this forward again.
#8514 CC @dapengzhang0
> Revert "netty: Requests with Connection header are malformed"

- xds/src/main/java/io/grpc/xds/internal/sds/SslContextProviderSupplier.java
The xdsClient uses `equals()` for duplicate detection/suppression so a proper `equals()` (and also `hashCode()`) is needed.  `sslContextProvider` and `shutdown` are excluded because these are implementation instances instead of pure data. This will be replaced by a more permanent solution later (such as removing the construction of implementation instances by XdsClient)
> xds: add hashCode and equals back to SslContextProviderSupplier

- xds/src/main/java/io/grpc/xds/internal/sds/SslContextProviderSupplier.java
backport of #8528
The xdsClient uses equals() for duplicate detection/suppression so a proper equals() (and also hashCode()) is needed. sslContextProvider and shutdown are excluded because these are implementation instances instead of pure data. This will be replaced by a more permanent solution later (such as removing the construction of implementation instances by XdsClient)
> xds: add hashCode and equals back to SslContextProviderSupplier [backport to 1.41.x] (#8528)

- xds/src/test/java/io/grpc/xds/FilterChainMatchingProtocolNegotiatorsTest.java
The internal build fails with "reference to assertThat is ambiguous". It
isn't clear why the internal build fails while the external one is okay,
but it is clear that the wildcard T return of readOutbound() is probably
confusing things as javac is considering assertThat(BigDecimal) as a
possible match.
The T return type is a hidden, convenience cast. We force the type
passed to assertThat() to be Object to avoid any ambiguity.
> xds: Fix test compilation for confused javac

- core/src/main/java/io/grpc/util/AdvancedTlsX509KeyManager.java
- core/src/main/java/io/grpc/util/AdvancedTlsX509TrustManager.java
- netty/src/test/java/io/grpc/netty/AdvancedTlsTest.java
Add two functions in AdvancedTls classes to load credentials from static files, making it easier to use for users who don't have the need to periodically refresh their credentials.
> AdvancedTls: add functions to load credentials from static files

- netty/src/main/java/io/grpc/netty/GracefulServerCloseCommand.java
- netty/src/main/java/io/grpc/netty/InternalGracefulServerCloseCommand.java
- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
- netty/src/main/java/io/grpc/netty/WriteBufferingAndExceptionHandler.java
- netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
- xds/src/main/java/io/grpc/xds/FilterChainMatchingProtocolNegotiators.java
- xds/src/main/java/io/grpc/xds/FilterChainSelectorManager.java
- xds/src/main/java/io/grpc/xds/InternalXdsAttributes.java
- xds/src/main/java/io/grpc/xds/XdsServerBuilder.java
- xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
- xds/src/test/java/io/grpc/xds/FilterChainMatchingProtocolNegotiatorsTest.java
- xds/src/test/java/io/grpc/xds/FilterChainSelectorManagerTest.java
- xds/src/test/java/io/grpc/xds/XdsClientWrapperForServerSdsTestMisc.java
- xds/src/test/java/io/grpc/xds/XdsServerBuilderTest.java
- xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java
This is necessary to make sure all connections are using the new
configuration.
Backport of #8526
> xds: Drain old server connections on Listener updates (1.41.x backport)

- xds/src/main/java/io/grpc/xds/FilterChainMatchingProtocolNegotiators.java
- xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
- xds/src/test/java/io/grpc/xds/FilterChainMatchingProtocolNegotiatorsTest.java
- xds/src/test/java/io/grpc/xds/FilterChainSelectorManagerTest.java
- xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java
Pre-build serverInterceptors to allow individual RPCs to reuse interceptors for one set of httpConfigs.
backport of https://github.com/grpc/grpc-java/pull/8524
> xds: build per route serverInterceptor for httpConfig (backport v1.41.x)

- api/src/main/java/io/grpc/ClientCall.java
- stub/src/main/java/io/grpc/stub/CallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ClientCallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ClientCalls.java
- stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java
- stub/src/main/java/io/grpc/stub/ServerCalls.java
Explicitly specify the param type of some `StreamObserver<>` classes and `ClientCall.Listener<>`.
> api,stub: make param types in StreamObserver and Listener explicit

- api/src/main/java/io/grpc/ChannelLogger.java
- core/src/main/java/io/grpc/internal/ChannelLoggerImpl.java
- core/src/test/java/io/grpc/internal/ChannelLoggerImplTest.java
Instead of `ChannelLogLevel.{DEBUG,INFO}` mapping to the same java level, `ChannelLogLevel.{WARNING,ERROR}` will shame the same java level. This allows us to be able to independently control the visibility of `ChannelLogLevel.DEBUG` logs which are the most verbose.
> core: change the mapping from ChannelLogLevel to java.util.logging.Level

- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
The server list updates are very verbose and currently logged every second, causing a huge log spam if `ChannelLogger` is completely enabled. For debugging an internal issue, we need to turn on `ChannelLogger` but hide the server list updates from the logs to keep the log size reasonable.
> grpclb: remove redundant logs and add a system property to hide server lists in logs

- binder/build.gradle
- binder/src/test/java/io/grpc/binder/SecurityPoliciesTest.java
- binder/src/test/java/io/grpc/binder/ServerSecurityPolicyTest.java
Using ShadowProcess to set the processes uID doesn't help since SecurityPolicies class fetches the ID in a static initializer, and it may have already been loaded.
Instead, just rely on whatever the uID is already, and ensure the other UIDs we test with are offset from that first value.
> Fix flake in security policy tests.

- buildscripts/run_arm64_tests_in_docker.sh
~~Based on https://github.com/grpc/grpc-java/pull/8126 (only the last commit is the actual change).~~
My experiments show that after upgrading netty-tcnative-boringssl-static, the tests are reasonably stable (i got a few consecutive passing runs).
> Re-enable previously disabled aarch64 tests

- RELEASING.md
For 1.40.0 the protobuf version was bumped to the latest version, which
we hadn't tested at all. We want to bump to the version used in the
release.
> RELEASING.md: Bump protobuf version to match build.gradle

- xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
- xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java
- xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
- xds/src/main/java/io/grpc/xds/FilterChainMatchingProtocolNegotiators.java
- xds/src/main/java/io/grpc/xds/RbacFilter.java
- xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
- xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
- xds/src/main/java/io/grpc/xds/internal/rbac/engine/GrpcAuthorizationEngine.java
- xds/src/main/java/io/grpc/xds/internal/sds/SdsProtocolNegotiators.java
- xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
- xds/src/test/java/io/grpc/xds/ClusterManagerLoadBalancerTest.java
* audited existing error messages in xds name resolver, xds lbs, xdsServerWrapper and made changes to add more error description verbosely. However, we should discuss how much error details of internal processing logics we should expose to messages visible to customers, e.g.
* what is the immediately/root cause of the error: what components, what config is missing, what is invalid, what is expected, or unknown errors?
* hint what is the possible action to fix the error?
* added more debug logs in xds server
> xds: error descriptions

- xds/src/main/java/io/grpc/xds/internal/sds/SdsProtocolNegotiators.java
The sslContextProviderSupplier is used by the xds creds themselves when
the control plane has security configured. But the fallback credentials
don't use such a supplier and may not even be using TLS.
Language tweak following #8554.
> xds: Log about fallback credentials, not supplier

- api/src/main/java/io/grpc/ManagedChannelBuilder.java
Tested with Jackson's `new ObjectMapper().readValue(json, Map.class)`.
Fixes #8300
> api: Add doc snippet to convert types for defaultServiceConfig()

- stub/src/main/java/io/grpc/stub/ServerCallStreamObserver.java
fix https://github.com/grpc/grpc-java/pull/8452
cc @ejona86
> stub: default throw ServerCallStreamObserver.setOnCloseHandler

- xds/src/test/java/io/grpc/xds/internal/certprovider/CertificateProviderStoreTest.java
See: https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/ArgumentMatchers.html#anyListOf-java.lang.Class-
> Migrate off deprecated mockito method

- android-interop-testing/src/main/AndroidManifest.xml
- buildscripts/kokoro/android-interop.sh
The tests run as part of the existing android-interop-testing job, using the same "apk under test".
The manifest under android-interop-testing/src/main is modified to declare Android Services needed for the binder tests.
> Make binder instrumentation tests run on kokoro.

- core/src/main/java/io/grpc/internal/AbstractStream.java
- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/ServerCallImpl.java
- core/src/test/java/io/grpc/internal/ClientCallImplTest.java
- core/src/test/java/io/grpc/internal/ServerCallImplTest.java
- netty/src/test/java/io/grpc/netty/NettyStreamTestBase.java
This fixes data race described in #8565.
We are doubtful whether checking closed in isReady() is necessary (#3201 might be a requirement), but it was easier to just maintain the existing behavior than think heavily about it.
> core: move closed check from Stream.isReady() to Call.isReady()

- xds/src/main/java/io/grpc/xds/MessagePrinter.java
Ideally we should plumb this through Filter, but FilterRegistry will
need to be plumbed to XdsClient and it started becoming non-trivial
compared to the "just add two lines." Expediency is helpful as the XDS
logs are pretty hard to read without the pretty-printing.
> xds: Register RBAC with pretty-printer

- .github/workflows/testing.yml
Adopt OpenJDK is longer seeing new releases, and instead has moved under
the Eclipse umbrella with Temurin releases.
https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/
https://github.com/actions/setup-java#supported-distributions
The adopt binaries still work, but won't see new versions.
> .github/workflows: Swap from adoptopenjdk to temurin

- context/src/main/java/io/grpc/Context.java
The example should unconditionally cancel the context, but fails to. And
it is really unclear what situation the example is demonstrating as the
Runnable looping on isCancelled() is guaranteed to have returned when
the Throwable catch is run.
It is non-trivial to fix up this example such that it is concise,
useful, and correct as it essentially needs a rewrite. We have other
examples demonstrating CancellableContext usage. We can just rely on
them instead.
> context: Remove misleading example that leaks CancellableContext

- buildscripts/kokoro/xds_url_map.sh
- buildscripts/xds-k8s/cloudbuild.yaml
This PR backports https://github.com/grpc/grpc-java/pull/8580 and adds support for tagging Docker image with branch name in Cloud Build. Before this PR, branch v1.40.x is manually tagged.
Test run: https://fusion2.corp.google.com/invocations/cba37e1d-ee5e-4da4-8b5a-42f4a87a2779/targets (ok)
> [Backport v1.40.x] add Docker tagging logic to the xds_url_map job

- android-interop-testing/build.gradle
- android/build.gradle
- binder/build.gradle
- cronet/build.gradle
- examples/android/helloworld/app/build.gradle
- examples/android/routeguide/app/build.gradle
As Google Play Service [discontinued updates for Jelly Bean (API levels 16, 17 & 18)](https://android-developers.googleblog.com/2021/07/google-play-services-discontinuing-jelly-bean.html).
> android: bump min Android SDK version to 19

- xds/src/main/java/io/grpc/xds/XdsServerBuilder.java
- xds/src/test/java/io/grpc/xds/XdsSdsClientServerTest.java
- xds/src/test/java/io/grpc/xds/XdsServerBuilderTest.java
- xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java
https://github.com/grpc/grpc-java/issues/7819
> xds: override bootstrap for xds server

- xds/src/main/java/io/grpc/xds/AbstractXdsClient.java
- xds/src/main/java/io/grpc/xds/Bootstrapper.java
- xds/src/main/java/io/grpc/xds/BootstrapperImpl.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/CsdsService.java
- xds/src/main/java/io/grpc/xds/SharedXdsClientPoolProvider.java
- xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
- xds/src/main/java/io/grpc/xds/internal/certprovider/CertProviderSslContextProvider.java
- xds/src/main/java/io/grpc/xds/internal/sds/ClientSslContextProviderFactory.java
- xds/src/main/java/io/grpc/xds/internal/sds/ServerSslContextProviderFactory.java
- xds/src/test/java/io/grpc/xds/BootstrapperImplTest.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/CommonBootstrapperTestUtils.java
- xds/src/test/java/io/grpc/xds/CsdsServiceTest.java
- xds/src/test/java/io/grpc/xds/SharedXdsClientPoolProviderTest.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverProviderTest.java
- xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java
- xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java
- xds/src/test/java/io/grpc/xds/internal/certprovider/CertProviderClientSslContextProviderTest.java
- xds/src/test/java/io/grpc/xds/internal/certprovider/CertProviderServerSslContextProviderTest.java
As many new fields will be added to `BootstrapInfo` for xds federation support, refactor `Bootstrapper.java` to use `AutoValue`. All the other files are just mechanical changes due to the refactoring.
> xds: migrate Bootstrapper data classes to use AutoValue

- core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java
- core/src/test/java/io/grpc/internal/AbstractManagedChannelImplBuilderTest.java
- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
In refactoring described in #7211, the implementation of #maxInboundMessageSize(int)
(and its corresponding field) was pulled down from internal AbstractManagedChannelImplBuilder
to concrete classes that actually enforce this setting. For the same reason, it wasn't ported
to ManagedChannelImplBuilder (the #delegate()).
Then AbstractManagedChannelImplBuilder was brought back to fix ABI backward compatibility,
and temporarily turned into a ForwardingChannelBuilder, ref PR #7564. Eventually it will
be deleted, after a period with "bridge" ABI solution introduced in #7834.
However, restoring AbstractManagedChannelImplBuilder unintentionally made ABI of
#maxInboundMessageSize(int) implemented by the concrete classes backward incompatible:
pre-refactoring builds expect it to be a method of …
> Fix AbstractManagedChannelImplBuilder#maxInboundMessageSize(int) ABI

- xds/src/main/java/io/grpc/xds/Bootstrapper.java
- xds/src/main/java/io/grpc/xds/BootstrapperImpl.java
- xds/src/test/java/io/grpc/xds/BootstrapperImplTest.java
Made changes as per **"Bootstrap File Changes"** section in  go/grpc-xds-federation and implemented bootstrap file parsing logic for the change. How the new parsed data will be used will be implemented in upcoming PRs.
> xds: add and parse new bootstrap fields for federation

- README.md
We dropped support for Android API levels <19 in #8583
> Update README for Android API level

- rls/src/main/java/io/grpc/rls/SubchannelStateManager.java
- rls/src/main/java/io/grpc/rls/SubchannelStateManagerImpl.java
- rls/src/test/java/io/grpc/rls/ChildLoadBalancerHelperTest.java
- rls/src/test/java/io/grpc/rls/SubchannelStateManagerImplTest.java
Fix connectivity state aggregation as per http://go/grpc-rls-lb-policy-design#heading=h.6e8tt7xcwcdn
> Note that, for the purposes of aggregation, when a child policy reports TRANSIENT_FAILURE, we consider it to continue to be in that state until it reports READY (i.e., we ignore CONNECTING in between the two, no matter how many times it bounces back and forth between TRANSIENT_FAILURE and CONNECTING).
> rls: fix connectivity state aggregation

- xds/src/main/java/io/grpc/xds/AbstractXdsClient.java
- xds/src/main/java/io/grpc/xds/MessagePrinter.java
- xds/src/test/java/io/grpc/xds/MessagePrinterTest.java
Just for cleanup. The printer might be used in other class e.g. to convert RLS proto to string/Map.
> xds: lazily init MessagePrinter

- binder/src/androidTest/java/io/grpc/binder/BinderChannelSmokeTest.java
- binder/src/main/java/io/grpc/binder/BinderChannelBuilder.java
- testing/src/main/java/io/grpc/internal/testing/FakeNameResolverProvider.java
- testing/src/main/java/io/grpc/testing/FakeNameResolverProvider.java
Allows BinderChannel to be used with name resolvers.
> Support BinderChannelBuilder.forTarget.

- xds/src/main/java/io/grpc/xds/AbstractXdsClient.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/LoadReportClient.java
- xds/src/main/java/io/grpc/xds/SharedXdsClientPoolProvider.java
- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/SharedXdsClientPoolProviderTest.java
See go/java-xds-client-api-for-federation for detailed description
> xds: refactor XdsClient in preparation to support federation

- binder/src/main/java/io/grpc/binder/SecurityPolicies.java
- binder/src/main/java/io/grpc/binder/SecurityPolicy.java
- binder/src/main/java/io/grpc/binder/UntrustedSecurityPolicies.java
- binder/src/test/java/io/grpc/binder/SecurityPoliciesTest.java
The previous attempt at this CL relied on guava's Hashing class which is still in beta.
Instead of comparing SHA256 hashs, this update compares Signature objects directly, removing the dependency on the Hashing class.
Add additional comments to the security policy class, to mention that
implementing new policies requires significant care.
With that in mind, add security policies to check the peer app's
signature, so people can create cross-app communication without
having to implement their own policy.
Finally, add the UntrustedSecurityPolicies class, since that's
inevitably a policy which is sometimes needed.
> binder: SecurityPolicy updates (take 2).

- binder/src/main/java/io/grpc/binder/SecurityPolicies.java
- binder/src/main/java/io/grpc/binder/SecurityPolicy.java
- binder/src/main/java/io/grpc/binder/UntrustedSecurityPolicies.java
- binder/src/test/java/io/grpc/binder/SecurityPoliciesTest.java
The previous attempt at this CL relied on guava's Hashing class which is still in beta.
Instead of comparing SHA256 hashs, this update compares Signature objects directly, removing the dependency on the Hashing class.
Add additional comments to the security policy class, to mention that
implementing new policies requires significant care.
With that in mind, add security policies to check the peer app's
signature, so people can create cross-app communication without
having to implement their own policy.
Finally, add the UntrustedSecurityPolicies class, since that's
inevitably a policy which is sometimes needed.
Backport of #8637
CC @markb74; squeezing this into the 1.42.0 release.
> binder: SecurityPolicy updates (take 2). (1.42.x backport)

- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
> grpclb: fallback timer only when not already using fallback backends (v1.42.x backport)

- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
> grpclb: fallback timer only when not already using fallback backends (v1.38.x backport)

- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
> grpclb: fallback timer only when not already using fallback backends (v1.40.x backport)

- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
> grpclb: fallback timer only when not already using fallback backends (v1.39.x backport)

- grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java
- grpclb/src/test/java/io/grpc/grpclb/GrpclbLoadBalancerTest.java
> grpclb: fallback timer only when not already using fallback backends (v1.41.x backport)

- interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java
fixes the issue about XdsTestServer mentioned in #8657. Make sure server is still assigned even if `start()` throws
> interop-testing: assign server as soon as it is built instead of after start

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/EnvoyServerProtoData.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
> xds: remove filter chain uuid name generator

- buildscripts/kokoro/xds-k8s.sh
It is successfully passing against prod:
https://source.cloud.google.com/results/invocations/e2be0996-ed4d-4a4c-90ad-20bc706f9f70/targets
CC @sergiitk
> kokoro: Enable xds authz_test

- buildscripts/kokoro/xds-k8s.cfg
The addition of the authz tests in 0d345721 is causing the tests to
exceed their timeout. By itself, the authz test takes about an hour in
this environment. Before the authz tests, xds-k8s was taking an hour
and a half.
> kokoro: Increase xds-k8s timeout to 3 hours

- buildscripts/kokoro/xds-k8s.cfg
- buildscripts/kokoro/xds-k8s.sh
This is a backport of #8664 and its fixup #8667
> kokoro: Enable xds authz_test (v1.42.x backport)

- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
A user has a proxy that is sending "Connection: close", which is against
the HTTP/2 spec, but will take time to fix.
Fixes #8674
CC @augi, @YifeiZhuang 
I'll backport this to v1.42.x. We're anticipating having a 1.42.1 release soon.
> netty: Add system property to disable Connection header check

- netty/src/main/java/io/grpc/netty/NettyServerHandler.java
A user has a proxy that is sending "Connection: close", which is against
the HTTP/2 spec, but will take time to fix.
Fixes #8674
CC @augi, @YifeiZhuang 
Backport of #8681
> netty: Add system property to disable Connection header check (1.42.x backport)

- buildscripts/kokoro/upload_artifacts.sh
_Hopefully_ fixes #7690 
I have no idea how to test this but thought I'd make this PR to get things moving. From what I can see, this _should_ produce signed aarch artifacts during the upload to a maven repository.
> Copy macOS x86 artifacts to aarch during upload

- xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
- xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancerProvider.java
- xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
- xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancerProvider.java
- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
Replace `String lrsServerName` with `ServerInfo lrsServerInfo` in `CdsUpdate`.
See http://go/grpc-xds-federation#heading=h.gh3gjftay27x for details.
This PR is only refactoring. Federation support is not implemented until the TODO [here](https://github.com/grpc/grpc-java/blob/a5c526c12f699af9a846d9faabc18038ef431675/xds/src/main/java/io/grpc/xds/ClientXdsClient.java#L2280) is addressed.
Resolves #8628
> xds: populate LRS ServerInfo to CdsUpdate

- xds/src/main/java/io/grpc/xds/AbstractXdsClient.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/CsdsService.java
- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/test/java/io/grpc/xds/CsdsServiceTest.java
Migrate deprecate `xds_config` field to `generic_xds_configs` 
https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/status/v3/csds.proto#service-status-v3-clientconfig
As per grpc/proposal#267.
The c++ version is grpc/grpc#27794
> xds: Migrate away deprecated fields in CsdsService

- rls/src/main/java/io/grpc/rls/RlsProtoData.java
- xds/build.gradle
- xds/src/main/java/io/grpc/xds/MessagePrinter.java
- xds/src/main/java/io/grpc/xds/RouteLookupServiceClusterSpecifierPlugin.java
- xds/src/test/java/io/grpc/xds/RouteLookupServiceClusterSpecifierPluginTest.java
- Partially revert the change of RlsProtoData.java  in #8612  by removing `public` accessor
- Have grpc-xds no longer strongly depend on grpc-rls. The application will need grpc-rls as runtime dependencies if they need route lookup feature in xds.
- Parse RouteLookupServiceClusterSpecifierPlugin config to the Json/Map representation of `io.grpc.lookup.v1.RouteLookupClusterSpecifier` instead of `io.grpc.rls.RlsProtoData.RouteLookupConfig`
> xds: fix parsing RouteLookupClusterSpecifier mistake

- buildscripts/kokoro/upload_artifacts.sh
Backport of #8680, for the right branch this time
CC @kdubb
It isn't entirely normal for us to backport something like this since it is technically a new feature, but it would fix an issue actively being experienced by users and give the release process change some testing while it is still fresh on our mind.
> Copy macOS x86 artifacts to aarch during upload (1.42.x backport)

- xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
- xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java
`XdsServerWrapper.start()` [blocks](https://github.com/grpc/grpc-java/blob/master/xds/src/main/java/io/grpc/xds/XdsServerWrapper.java#L162) until `LdsResourceWatcher`'s callback is called. If no callback is called due to whatever issue of the XdsClient, the server start() will be stuck forever, even we call `shutdownNow()`.
Changing the `shutdownNow()` behavior to unblock `start()` immediately.
> xds: terminate XdsServer start() thread when shutdownNow() is called

- xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
Logs:
```
io.grpc.xds.XdsE2eTest > pingPong FAILED
io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
at io.grpc.testing.protobuf.SimpleServiceGrpc$SimpleServiceBlockingStub.unaryRpc(SimpleServiceGrpc.java:355)
at io.grpc.xds.XdsE2eTest$1.run(XdsE2eTest.java:46)
at io.grpc.xds.XdsE2eTest.pingPong(XdsE2eTest.java:52)
```
Caused by:
java.lang.NullPointerException: stats
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:910)
at io.grpc.xds.ClusterImplLoadBalancer$CountingStreamTracerFactory.<init>(ClusterImplLoadBalancer.java:346)
at …
> xds: fix clusterImplLoadBalancer NPE when lrs is null

- core/src/main/java/io/grpc/internal/DnsNameResolver.java
- core/src/main/java/io/grpc/internal/JsonUtil.java
- core/src/main/java/io/grpc/internal/ServiceConfigUtil.java
- core/src/test/java/io/grpc/internal/JsonUtilTest.java
As documented in https://developers.google.com/protocol-buffers/docs/proto3#json,
the canonical proto-to-json converter converts int64 (Java long) values to string values in Json rather than Json numbers (Java Double). Conversely, either Json string value or number value are accepted to be converted to int64 proto value.
To better support service configs defined by protobuf messages, support parsing String values as numbers in `JsonUtil`.
> core: have JsonUtil support parsing String value as number

- xds/src/main/java/io/grpc/xds/Bootstrapper.java
- xds/src/main/java/io/grpc/xds/BootstrapperImpl.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/main/java/io/grpc/xds/XdsNameResolverProvider.java
- xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
- xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java
Implement applying `server_listener_resource_name_template` and `client_listener_resource_name_template` with xdstp scheme, extracting authorities from xdstp resource URI and lookup authorities map in bootstrap.
> xds: support xdstp scheme in resource URIs for federation

- buildscripts/kokoro/linux_artifacts.sh
- buildscripts/kokoro/upload_artifacts.sh
Without this, grpc-binder isn't published to maven.
> buildscripts: add config for building grpc-binder artifact

- census/src/main/java/io/grpc/census/CensusStatsModule.java
Fix the NPE as shown in the following stacktrace:
```
Caused by: java.lang.RuntimeException: java.lang.NullPointerException with message: null
at io.grpc.census.CensusStatsModule$ClientTracer.recordFinishedAttempt(CensusStatsModule.java:388) ~[grpc-census-1.42.0.jar:1.42.0]
at io.grpc.census.CensusStatsModule$CallAttemptsTracerFactory.recordFinishedCall(CensusStatsModule.java:525) ~[grpc-census-1.42.0.jar:1.42.0]
at io.grpc.census.CensusStatsModule$CallAttemptsTracerFactory.attemptEnded(CensusStatsModule.java:492) ~[grpc-census-1.42.0.jar:1.42.0]
at io.grpc.census.CensusStatsModule$ClientTracer.streamClosed(CensusStatsModule.java:345) ~[grpc-census-1.42.0.jar:1.42.0]
at io.grpc.internal.StatsTraceContext.streamClosed(StatsTraceContext.java:155) ~[grpc-core-1.42.0.jar:1.42.0]
at …
```
> census: fix NPE in calling recordFinishedAttempt()

- alts/src/main/java/io/grpc/alts/GoogleDefaultChannelCredentials.java
- okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
The `@since` version in commits 5a3b8e2141a9992f71361bd605ebc6f1184742e2 and a2398ce5dbe2eacf841d7af9c9aa5e912e8db0aa were missing and incorrect respectively.
> javadoc: update new API `@since` version

- census/src/main/java/io/grpc/census/CensusStatsModule.java
Backport of #8706
Fix the NPE as shown in the following stacktrace:
```
Caused by: java.lang.RuntimeException: java.lang.NullPointerException with message: null
at io.grpc.census.CensusStatsModule$ClientTracer.recordFinishedAttempt(CensusStatsModule.java:388) ~[grpc-census-1.42.0.jar:1.42.0]
at io.grpc.census.CensusStatsModule$CallAttemptsTracerFactory.recordFinishedCall(CensusStatsModule.java:525) ~[grpc-census-1.42.0.jar:1.42.0]
at io.grpc.census.CensusStatsModule$CallAttemptsTracerFactory.attemptEnded(CensusStatsModule.java:492) ~[grpc-census-1.42.0.jar:1.42.0]
at io.grpc.census.CensusStatsModule$ClientTracer.streamClosed(CensusStatsModule.java:345) ~[grpc-census-1.42.0.jar:1.42.0]
at io.grpc.internal.StatsTraceContext.streamClosed(StatsTraceContext.java:155) …
```
> census: fix NPE in calling recordFinishedAttempt() [backport v1.42.x]

- buildscripts/kokoro/linux_artifacts.sh
- buildscripts/kokoro/upload_artifacts.sh
Without this, grpc-binder isn't published to maven.
---
Backport of #8722
I manually published binder for 1.42.0 and 1.42.1, but we think there may be a 1.42.2, so getting this in place so I don't have to do another manual component release.
CC @markb74
> buildscripts: add config for building grpc-binder artifact (1.42.x backport)

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/EnvoyServerProtoData.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
backport of  #8663
Generating a uuid in filterChain breaks the de-duplication detection which causes XdsServer to cycle connections, so removing it.
An empty name is now allowed. The name is currently only used for debug purpose.
> xds: remove filter chain uuid name generator [backport v1.40.x]

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/EnvoyServerProtoData.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
backport of #8663
Generating a uuid in filterChain breaks the de-duplication detection which causes XdsServer to cycle connections, so removing it.
An empty name is now allowed. The name is currently only used for debug purpose.
> xds: remove filter chain uuid name generator [backport v1.41.x]

- xds/src/main/java/io/grpc/xds/GoogleCloudToProdNameResolverProvider.java
- xds/src/test/java/io/grpc/xds/GoogleCloudToProdNameResolverProviderTest.java
- xds/src/test/java/io/grpc/xds/GoogleCloudToProdNameResolverTest.java
Java analogue of https://github.com/grpc/grpc/pull/28294
> Replace C2P resolver env var with experimental scheme suffix

- binder/src/main/java/io/grpc/binder/internal/BinderTransport.java
Enclose all operations in BinderTransport using obtained Parcels in try-finally blocks that will recycle the Parcel in the case that any exception is thrown.
> Enclose all operations in BinderTransport using obtained Parcels in try-finally blocks.

- COMPILING.md
- WORKSPACE
- build.gradle
- buildscripts/make_dependencies.bat
- buildscripts/make_dependencies.sh
- examples/WORKSPACE
- examples/android/clientcache/app/build.gradle
- examples/android/helloworld/app/build.gradle
- examples/android/routeguide/app/build.gradle
- examples/android/strictmode/app/build.gradle
- examples/build.gradle
- examples/example-alts/build.gradle
- examples/example-gauth/build.gradle
- examples/example-gauth/pom.xml
- examples/example-hostname/build.gradle
- examples/example-hostname/pom.xml
- examples/example-jwt-auth/build.gradle
- examples/example-jwt-auth/pom.xml
- examples/example-tls/build.gradle
- examples/example-tls/pom.xml
- examples/example-xds/build.gradle
- examples/pom.xml
- repositories.bzl
Protobuf uses Guava 30.1.1, so I upgrade it at the same time. It also
caused an update to rules_jvm_external and reworking the Bazel build.
Protobuf no longer requires bind() so they were dropped. Although
Protobuf's protobuf_deps() brings in rules_jvm_external, and so we don't
need to define it ourselves, it seems better to define it directly and
not depend on transitive deps since we use it directly.
Protobuf now has support for maven_install() by exposing
PROTOBUF_MAVEN_ARTIFACTS, which required reorganizing the WORKSPACE to
use maven_install() after loading protobuf. Protobuf still doesn't
define target overrides for itself so we still maintain those. When
reorganizing the WORKSPACE I noticed http_archive should ideally be
above io_grpc_grpc_java as most users will need it there, so I …
> Upgrade Protobuf to 3.19.1 and Guava to 30.1.1

- COMPILING.md
- WORKSPACE
- build.gradle
- buildscripts/make_dependencies.bat
- buildscripts/make_dependencies.sh
- examples/WORKSPACE
- examples/android/clientcache/app/build.gradle
- examples/android/helloworld/app/build.gradle
- examples/android/routeguide/app/build.gradle
- examples/android/strictmode/app/build.gradle
- examples/build.gradle
- examples/example-alts/build.gradle
- examples/example-gauth/build.gradle
- examples/example-gauth/pom.xml
- examples/example-hostname/build.gradle
- examples/example-hostname/pom.xml
- examples/example-jwt-auth/build.gradle
- examples/example-jwt-auth/pom.xml
- examples/example-tls/build.gradle
- examples/example-tls/pom.xml
- examples/example-xds/build.gradle
- examples/pom.xml
- repositories.bzl
Protobuf uses Guava 30.1.1, so I upgrade it at the same time. It also
caused an update to rules_jvm_external and reworking the Bazel build.
Protobuf no longer requires bind() so they were dropped. Although
Protobuf's protobuf_deps() brings in rules_jvm_external, and so we don't
need to define it ourselves, it seems better to define it directly and
not depend on transitive deps since we use it directly.
Protobuf now has support for maven_install() by exposing
PROTOBUF_MAVEN_ARTIFACTS, which required reorganizing the WORKSPACE to
use maven_install() after loading protobuf. Protobuf still doesn't
define target overrides for itself so we still maintain those. When
reorganizing the WORKSPACE I noticed http_archive should ideally be
above io_grpc_grpc_java as most users will need it there, so I …
> Upgrade Protobuf to 3.19.1 and Guava to 30.1.1 (1.43.x backport)

- core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
PR for Spikhalskiy/grpc-java@6d260b8 
Hot fix of #8714
> core: Race condition in idleTimer & ManagedChannel#enterIdle

- core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
The method added in #5821 seems not used now.
> core: remove unused method in AutoConfiguredLoadBalancer

- api/src/main/java/io/grpc/ClientStreamTracer.java
- api/src/test/java/io/grpc/CallOptionsTest.java
- census/src/main/java/io/grpc/census/CensusStatsModule.java
- census/src/main/java/io/grpc/census/CensusTracingModule.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/main/java/io/grpc/internal/RetriableStream.java
- core/src/test/java/io/grpc/ClientStreamTracerTest.java
- core/src/test/java/io/grpc/internal/GrpcUtilTest.java
- core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
- grpclb/src/main/java/io/grpc/grpclb/GrpclbClientLoadRecorder.java
- grpclb/src/main/java/io/grpc/grpclb/TokenAttachingTracerFactory.java
- grpclb/src/test/java/io/grpc/grpclb/TokenAttachingTracerFactoryTest.java
- interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java
- xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
- xds/src/main/java/io/grpc/xds/OrcaPerRequestUtil.java
APIs such as `StreamInfo.getTransportAttrs()` were [deprecated](https://github.com/grpc/grpc-java/commit/860e97d12ab46e184ac4448eeca8a45671de6462#diff-aa4049f54d6d5d462700e9221344184a37d2068b3ba7d715abd417b1df5bf883R114) since 1.41.0. Removing now.
> all: remove deprecated StreamInfo.transportAttrs

- interop-testing/src/main/java/io/grpc/testing/integration/GrpclbFallbackTestClient.java
We are setting up fallback test based on TD. Currently the test client is compiled in google3, so we must run it in a container so that the client can have the GRTE dependency. However, container does not have `ip`, `iptables`, etc network command, so we plan to run the network command outside of the container. To do this, add a new flag `skipNetCmd` to skip network commands inside the test client.
> xds: add skipNetCmd flag to fallback test client

- buildscripts/kokoro/xds.sh
Related https://github.com/grpc/grpc/pull/28399.
> Use xds-test-server-5 as the GCE interop server

- buildscripts/kokoro/xds.sh
> [Backport][v1.41.x] use xds-test-server-5

- buildscripts/kokoro/xds.sh
> [Backport][v1.40.x] use xds-test-server-5

- buildscripts/kokoro/xds.sh
> [Backport][v1.38.x] use xds-test-server-5

- buildscripts/kokoro/xds.sh
> [Backport][v1.37.x] use xds-test-server-5

- buildscripts/kokoro/xds.sh
> [Backport][v1.36.x] use xds-test-server-5

- buildscripts/kokoro/xds.sh
> [Backport][v1.35.x] use xds-test-server-5

- buildscripts/kokoro/xds.sh
> [Backport][v1.34.x] use xds-test-server-5

- buildscripts/kokoro/xds.sh
> [Backport][v1.39.x] use xds-test-server-5

- buildscripts/kokoro/xds.sh
> [Backport][v1.42.x] use xds-test-server-5

- buildscripts/kokoro/unix.sh
> buildscripts: always make sure we are using jdk8 for build and test

- README.md
We should recommend runtime scope for grpc-netty-shaded.
https://github.com/grpc/grpc-java/issues/8606#issuecomment-1004504316
> readme: grpc-netty-shaded runtime scope

- .github/workflows/testing.yml
The GitHub Actions Linux Testing only reports limited information (can not see full stacktrace, time consumed, or stderr from child threads) when unit tests fail. Adding a step to upload the test report to Artifacts if the test fails. If the test is successful, no artifacts will be uploaded.
Also considered using the 'Publish Unit Test Results' github action. However, when [matrix strategy is used](https://github.com/marketplace/actions/publish-unit-test-results#use-with-matrix-strategy), the config will be more complex than this PR, it still will use the upload-artifact anyway, and there's a bug displaying the name of the check item like "Validate Gradle Wrapper / Publish Unit Test Results". So I chose to just use the upload-artifact action.
> .github/workflows: publish test results for failed job

- WORKSPACE
- build.gradle
- buildscripts/make_dependencies.bat
- buildscripts/make_dependencies.sh
- examples/WORKSPACE
- examples/android/clientcache/app/build.gradle
- examples/android/helloworld/app/build.gradle
- examples/android/routeguide/app/build.gradle
- examples/android/strictmode/app/build.gradle
- examples/build.gradle
- examples/example-alts/build.gradle
- examples/example-gauth/build.gradle
- examples/example-gauth/pom.xml
- examples/example-hostname/build.gradle
- examples/example-hostname/pom.xml
- examples/example-jwt-auth/build.gradle
- examples/example-jwt-auth/pom.xml
- examples/example-tls/build.gradle
- examples/example-tls/pom.xml
- examples/example-xds/build.gradle
- examples/pom.xml
- repositories.bzl
Protobuf bumped to Guava 30.1.1-android, so we need to follow suit.
See also #8805
> Bump protobuf to 3.18.2 and Guava to 30.1.1-android (v1.42.x)

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
This is to keep names of the top-level process* functions called from
handle*Response functions, and returning *Update resources consistent:
- `handleLdsResponse()` -> `LdsUpdate processClientSideListener()`
`LdsUpdate processServerSideListener()`
- `handleCdsResponse()` -> `CdsUpdate processCluster()`
- `handleRdsResponse()` -> `RdsUpdate processRouteConfiguration()`
- `handleEdsResponse()` -> `EdsUpdate processClusterLoadAssignment()`
For some reason, processCluster() was renamed to parseCluster() in
fa4b980e0 / PR #8237.
> xds: Rename parseCluster() back to processCluster() for consistency

- WORKSPACE
- build.gradle
- buildscripts/make_dependencies.bat
- buildscripts/make_dependencies.sh
- examples/WORKSPACE
- examples/android/clientcache/app/build.gradle
- examples/android/helloworld/app/build.gradle
- examples/android/routeguide/app/build.gradle
- examples/android/strictmode/app/build.gradle
- examples/build.gradle
- examples/example-alts/build.gradle
- examples/example-gauth/build.gradle
- examples/example-gauth/pom.xml
- examples/example-hostname/build.gradle
- examples/example-hostname/pom.xml
- examples/example-jwt-auth/build.gradle
- examples/example-jwt-auth/pom.xml
- examples/example-tls/build.gradle
- examples/example-tls/pom.xml
- examples/example-xds/build.gradle
- examples/pom.xml
- repositories.bzl
Protobuf bumped to Guava 30.1.1-android, so we need to follow suit.
Backport of #8806. See also #8805
> Bump protobuf to 3.18.2 and Guava to 30.1.1-android (v1.41.x backport)

- android-interop-testing/src/androidTest/java/io/grpc/android/integrationtest/InteropInstrumentationTest.java
- api/build.gradle
- auth/build.gradle
- context/build.gradle
- core/build.gradle
- core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java
- okhttp/build.gradle
- protobuf-lite/build.gradle
- stub/build.gradle
This cleanup could have been done right after #8583
Manual android-interop run:
https://fusion2.corp.google.com/invocations/09ea8ade-e7a4-4dd4-9212-5f417fd05f0a
> all: clean up code related to android api level less than 19

- all/build.gradle
- api/build.gradle
- benchmarks/build.gradle
- binder/build.gradle
- build.gradle
- context/build.gradle
- core/build.gradle
- examples/android/clientcache/build.gradle
- examples/android/helloworld/build.gradle
- examples/android/routeguide/build.gradle
- examples/android/strictmode/build.gradle
- examples/build.gradle
- examples/example-alts/build.gradle
- examples/example-gauth/build.gradle
- examples/example-jwt-auth/build.gradle
- examples/example-tls/build.gradle
- examples/example-xds/build.gradle
- examples/gradle/wrapper/gradle-wrapper.properties
- gradle/wrapper/gradle-wrapper.properties
- interop-testing/build.gradle
- netty/build.gradle
- settings.gradle
These changes make the build compatible with Gradle 7, except for
Android which requires plugin updates.
I removed animalsniffer from binder because it did nothing (as there
were no signatures) and it was failing after setting toolVersion. It
failed because animalsniffer is only compatible with java plugin. After
this change I put the withId(animalsniffer) loading inside the
withId(java) to avoid a plugin ordering failure. That made it safe again
for binder to load animalsniffer, but it is still best to remove the
plugin from binder as it is misleading.
I did not upgrade Android plugin versions as newer versions (even 3.6)
require dealing with androidx (#8421).
> Bump to Gradle 6.9 and update plugins

- xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
- xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
- xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancerProvider.java
- xds/src/main/java/io/grpc/xds/RingHashLoadBalancerProvider.java
- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientV2Test.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientV3Test.java
- xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
Ring hash can only be used from within xds currently, because that's
the only way to get a hash assigned to RPCs which is required for it
to function. So it should be using the _experimental suffix like the
other only-used-from-xds policies.
Fixes #8756
> xds: Rename ring_hash LB Policy to ring_hash_experimental

- build.gradle
When messing with error prone for another commit, Gradle started
producing a clear warning the dependsOn was missing. But the warning
was not reliable. However, even when no warning was printed it is clear
the task was broken.
> build.gradle: Add missing dependsOn for generated code sync

- android-interop-testing/src/main/res/layout/activity_tester.xml
As per https://developer.android.com/studio/write/lint.html#configuring-lint-checking-in-xml
(this replaces the internal android-interop-testing/android_lint_baseline.xml file and works for generated files as described in an internal article).
> android-interop-testing: add the linter error message ignore annotation in the source xml file

- interop-testing/build.gradle
e0dca93c broke the interop-testing script for unix because Gradle
changed the scripts for
https://github.com/gradle/gradle/security/advisories/GHSA-6j2p-252f-7mw8
The solution here looks weird, but we are inserting the replacement
string into a single-quoted string, so we stop that string, start a
double-quoted string to allow the variable replacement, and then resume
the previous string.
> interop-testing: Fix script rewrite for Gradle 7.2

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/CsdsService.java
- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/CsdsServiceTest.java
Fixes an issue with ClientXdsClient.getSubscribedResourcesMetadata()
executed out of shared synchronization context, and leading to:
- each individual config dump containing outdated data when
an xDS resource is updated during CsdsService preparing the response
- config dumps for different services being out-of-sync with each
other when any of the related xDS resources is updated during
CsdsService preparing the response
The fix replaces getSubscribedResourcesMetadata(ResourceType type)
with atomic getSubscribedResourcesMetadataSnapshot() returning
a snapshot of all resources for each type as they are
at the moment of a CSDS request.
Fix false negative in fetchClientConfig_unexpectedException,
where expected exception  was actually caused by missing
bootstrap data, not by throwing error …
> xds: fix a concurrency issue in CSDS ClientStatus responses

- alts/src/main/java/io/grpc/alts/internal/ChannelCrypterNetty.java
- alts/src/test/java/io/grpc/alts/internal/TsiTest.java
- api/build.gradle
- api/src/main/java/io/grpc/Attributes.java
- api/src/main/java/io/grpc/NameResolver.java
- build.gradle
- context/src/main/java/io/grpc/Context.java
- core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
- core/src/main/java/io/grpc/internal/JndiResourceResolverFactory.java
- interop-testing/src/test/java/io/grpc/testing/integration/NettyFlowControlTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/TrafficControlProxy.java
- netty/src/main/java/io/grpc/netty/GrpcHttp2ConnectionHandler.java
- netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
- netty/src/main/java/io/grpc/netty/NettyServerBuilder.java
- services/src/main/java/io/grpc/protobuf/services/BinaryLogProviderImpl.java
- stub/src/main/java/io/grpc/stub/ClientCalls.java
- stub/src/main/java/io/grpc/stub/ServerCalls.java
- xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java
Previous versions of error prone were incompatible with Java 17 javac.
In grpc-api, errorprone is now api dependency because it is on a public
API.  I was happy to see that Gradle failed the build without the dep
change, although the error message wasn't super clear as to the cause.
It seems that previously -PerrorProne=false did nothing. I'm guessing
this is due to a behavior change of Gradle at some point. Swapping to
using the project does build without errorProne, although the build
fails with Javac complaining certain classes are unavailable. It's
unclear why. It doesn't seem to be caused by the error-prone plugin.
I've left it failing as a pre-existing issue.
ClientCalls/ServerCalls had Deprecated removed from some methods because
they were only deprecated in the internal class, not …
> Bump ErrorProne to 2.10.0

- buildscripts/kokoro/kokoro.sh
- buildscripts/kokoro/linux_aarch64.cfg
- buildscripts/kokoro/linux_artifacts.cfg
- buildscripts/kokoro/linux_artifacts.sh
- buildscripts/kokoro/macos.cfg
- buildscripts/kokoro/macos.sh
- buildscripts/kokoro/unix.sh
- buildscripts/kokoro/windows.cfg
- buildscripts/kokoro/windows64.bat
Previously, only Windows had the plumbing to rename test results for
the Kokoro result viewers to pretty-print.
macos.cfg was the only CI that lacked a corresponding .sh, which maked
unix.sh harder to reason about. Created macos.sh so that unix.sh is now
just a helper script and will not be called directly by Kokoro.
> kokoro: Pretty test results

- testing/build.gradle
`io.grpc.internal.testing.StatsTestUtils` in `grpc-testing` is only used internally by `grpc-interop-testing` and unit tests. The opencensus dependency does not need to be exposed to `grpc-interop-testing` maven artifact.
> testing: remove opencensus dependency from grpc-testing

- rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
- rls/src/main/java/io/grpc/rls/LbPolicyConfiguration.java
- rls/src/main/java/io/grpc/rls/LinkedHashLruCache.java
- rls/src/main/java/io/grpc/rls/LruCache.java
- rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
- rls/src/test/java/io/grpc/rls/LbPolicyConfigurationTest.java
- rls/src/test/java/io/grpc/rls/LinkedHashLruCacheTest.java
Backport of #8750 
When client channel is shutting down, the RlsLoadBalancer is shutting down. However, the child loadbalancers of RlsLoadBalancer are not shut down. This is causing the issue b/209831670
> rls: fix child lb leak when client channel is shutdown [backport v1.44.x]

- android-interop-testing/build.gradle
- android-interop-testing/src/androidTest/AndroidManifest.xml
- android-interop-testing/src/androidTest/java/io/grpc/android/integrationtest/InteropInstrumentationTest.java
- Importing to google failed with
```
grpc/android/integrationtest/InteropInstrumentationTest.java:35: error: could not resolve AndroidJUnit4
@RunWith(AndroidJUnit4.class)
```
when using internal jetifier.
Migrate deprecated `androidx.test.runner.AndroidJUnit4` to `androidx.test.ext.junit.runners.AndroidJUnit4`.
- It also failed with
```
ClassNotFoundException: androidx.multidex.MultiDexApplication
```
Updated androidTest/AndroidManifest.xml for multidex.
- Leave the `android:debuggable attribute` unset as suggested by go/tiktok-conformance-violations/MANIFEST_DEBUGGABLE
Tested manually:
https://fusion2.corp.google.com/invocations/b6b87d6c-c1d2-42e1-bffe-198efccb0f59
> android-interop-testing: migrate AndroidJUnit4 runner and update AndroidManifest.xml

- binder/src/main/java/io/grpc/binder/internal/BinderTransport.java
Also call onTransportReady() only if isReady() still holds by the time
we get to a given Inbound. This dramatically reduces timeouts and
improves throughput when flow control has kicked in.
This approach is still not completely fair since each ongoing call might
consume a different amount of window on its turn, but because of the way
Outbound#writeMessageData() and BlockPool already work, everyone gets to
send at least 16kb.
Fixes #8834
> binder: Invoke onTransportReady() in a round-robin fashion.

- alts/build.gradle
- build.gradle
- context/build.gradle
- examples/build.gradle
- examples/example-alts/build.gradle
- examples/example-gauth/build.gradle
- examples/example-hostname/build.gradle
- examples/example-jwt-auth/build.gradle
- examples/example-tls/build.gradle
- examples/example-xds/build.gradle
Oracle's Premier Support for Java 7 ended in July 2019. Per gRFC P5,
dropping support for the only release. Android is able to desugar many
Java 8 language features.
Context left on Java 7 just to be super-conservative.
Draft PR because the gRFC has not yet merged (giving a bit more time for people to comment).
> Drop Java 7 support

- binder/src/main/java/io/grpc/binder/AndroidComponentAddress.java
Be more explicit that "packagename" is the application package name.
> Update javadoc for AndroidComponentAddress.

- netty/src/test/java/io/grpc/netty/KeepAliveEnforcerTest.java
This fixes a soon-to-be compile error via ErrorProne.
Alternatively, we could use assertThrows() instead of
@Test(expected = ...), but grpc doesn't yet require Java 8.
CC @kluever
> netty: Assign the result of a @CheckReturnValue'ed constructor to an unused variable

- api/build.gradle
- api/src/jmh/java/io/grpc/StatusBenchmark.java
- api/src/main/java/io/grpc/DecompressorRegistry.java
- api/src/main/java/io/grpc/InternalMetadata.java
- api/src/test/java/io/grpc/StatusTest.java
- auth/build.gradle
- context/build.gradle
- core/build.gradle
- core/src/main/java/io/grpc/internal/ClientCallImpl.java
- core/src/main/java/io/grpc/internal/GrpcUtil.java
- core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java
- cronet/src/main/java/io/grpc/cronet/CronetClientStream.java
- cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java
- examples/src/main/java/io/grpc/examples/advanced/JsonMarshaller.java
- examples/src/main/java/io/grpc/examples/routeguide/RouteGuideUtil.java
- interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
- interop-testing/src/test/java/io/grpc/testing/integration/CompressionTest.java
- okhttp/build.gradle
- okhttp/src/test/java/io/grpc/okhttp/OkHttpClientStreamTest.java
- okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/Util.java
- protobuf-lite/build.gradle
- services/src/test/java/io/grpc/protobuf/services/BinlogHelperTest.java
- stub/build.gradle
There are internal integration tests running on devices with Android API level lower than 19. Revert #8779 and #8814
Manual interop test run: https://sponge2.corp.google.com/86a7e171-da91-48f6-8fdb-f02381041786
> Revert android api level check to 14

- alts/build.gradle
- build.gradle
- context/build.gradle
- examples/build.gradle
- examples/example-alts/build.gradle
- examples/example-gauth/build.gradle
- examples/example-hostname/build.gradle
- examples/example-jwt-auth/build.gradle
- examples/example-tls/build.gradle
- examples/example-xds/build.gradle
Oracle's Premier Support for Java 7 ended in July 2019. Per gRFC P5,
dropping support for the only release. Android is able to desugar many
Java 8 language features.
Context left on Java 7 just to be super-conservative.
Backport of #8828
> Drop Java 7 support (1.44.x backport)

- xds/src/main/java/io/grpc/xds/GoogleCloudToProdNameResolver.java
- xds/src/test/java/io/grpc/xds/GoogleCloudToProdNameResolverTest.java
This was noticed because Mockito can't mock Random in Java 17, so it was
replaced with actual Random. But when doing that change it exposed that
negative numbers would cause the id to have a double '-'.
> xds: Handle negative random numbers in c2p resolver

- xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
- xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancerProvider.java
- xds/src/main/java/io/grpc/xds/LeastRequestLoadBalancer.java
- xds/src/main/java/io/grpc/xds/LeastRequestLoadBalancerProvider.java
- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/main/resources/META-INF/services/io.grpc.LoadBalancerProvider
- xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientV2Test.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientV3Test.java
- xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
- xds/src/test/java/io/grpc/xds/LeastRequestLoadBalancerProviderTest.java
- xds/src/test/java/io/grpc/xds/LeastRequestLoadBalancerTest.java
Implements least_request_experimental as defined by
[A48](https://github.com/grpc/proposal/blob/master/A48-xds-least-request-lb-policy.md)
These tests are mostly just a copy of
RoundRobinLoadBalancerTest.
The main difference is currently in the pickerLeastRequest test case.
All other tests should be the same.
This is a backport of #8739
CC @erikjoh
> xds: implement least_request load balancing policy (v1.44.x backport)

- xds/src/main/java/io/grpc/xds/GoogleCloudToProdNameResolver.java
- xds/src/test/java/io/grpc/xds/GoogleCloudToProdNameResolverTest.java
This was noticed because Mockito can't mock Random in Java 17, so it was
replaced with actual Random. But when doing that change it exposed that
negative numbers would cause the id to have a double '-'.
Backport of #8845
> xds: Handle negative random numbers in c2p resolver (1.44.x backport)

- RELEASING.md
git cherry is too conservative in determining backports. Showing all
commits between the branch point and the release is more reliable.
> RELEASING.md: Use git merge-base instead of cherry for backport summary

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
Adopting the change in the [spec](https://github.com/grpc/proposal/blob/367ba33a0acfc411e2d2590887053e6d1e235ab1/A47-xds-federation.md#xds-api-changes):
>Currently, for the ConfigSource fields in the LDS resource that points to the RDS resource and in the CDS resource that points to the EDS resource, gRPC requires the ConfigSource to have its ads field set. As part of supporting federation, gRPC will now also allow the ConfigSource to have its self field set. Both fields will have the same meaning.
> xds/federation: allow ConfigSource to have its self field set

- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
Fix percent encoding to comply with [RFC-3986 section 3.3](https://datatracker.ietf.org/doc/html/rfc3986#section-3.3) as specified in [gRFC A47](https://github.com/grpc/proposal/blob/367ba33a0acfc411e2d2590887053e6d1e235ab1/A47-xds-federation.md).
> xds/federation: fix percent encode

- xds/src/main/java/io/grpc/xds/ClientXdsClient.java
- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
On reading a new `xdstp:` resource name, do a validation on the URI and canonify the query params.
> xds/federation: validate and canonify resource name

- binder/src/main/java/io/grpc/binder/internal/ServiceBinding.java
- binder/src/test/java/io/grpc/binder/internal/ServiceBindingTest.java
> binder: Fix a ServiceConnection leak

- rls/src/main/java/io/grpc/rls/RlsLoadBalancerProvider.java
As pointed out by @easwars , the lb name of RLS lb should be "rls_experimental" instead of "rls-experimental", using underscore like "round_robin".
> rls: fix RLS lb name

- core/src/main/java/io/grpc/internal/InternalSubchannel.java
It would be good to print Cause when the transport is shutdown and has throwable exception messages.
The current log doesn't have this information for debugging:
`SHUTDOWN with UNAVAILABLE(io exception
Channel Pipeline: [HttpProxyHandler$HttpClientCodecWrapper#0, HttpProxyHandler#0, TsiHandshakeHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0])`
> Add Cause when printing Status

- rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
- rls/src/main/java/io/grpc/rls/LbPolicyConfiguration.java
- rls/src/main/java/io/grpc/rls/RlsLoadBalancerProvider.java
- rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
- rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
Implementing the latest change for RLS lb config.
```
The configuration for the LB policy will be of the following form:
{
"routeLookupConfig": <JSON form of RouteLookupConfig proto>,
"routeLookupChannelServiceConfig": {...service config JSON...},
"childPolicy": [
{"<policy name>": {...child policy config...}}
],
"childPolicyConfigTargetFieldName": "<name of field>"
}
```
>If the routeLookupChannelServiceConfig field is present, we will pass the specified service config to the RLS control plane channel, and we will disable fetching service config via that channel's resolver.
> rls: support routeLookupChannelServiceConfig in RLS lb config

- android/src/main/java/io/grpc/android/AndroidChannelBuilder.java
When an app goes to the background, onBlockedStatusChanged is called with true and then called with false when it comes back to the foreground. The function onAvailable isn't called in this case and the connection wasn't being reset. Closes #8850
I noticed the comment that this is used for API versions 24+ but onBlockedStatusChanged was added in 29. I'm not sure if some kind of guard needs to be added or not. 
https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback#onBlockedStatusChanged(android.net.Network,%20boolean)
> Fix for reconnecting when Android app comes to the foreground

- core/src/test/java/io/grpc/internal/JsonUtilTest.java
Verifies the behavior of `JsonUtil.getObject` when the map contains a null value for a given key.
Context: https://github.com/grpc/grpc-java/pull/8871#discussion_r796191392
> core: test JsonUtil.getObject with a map containing a null value

- buildscripts/kokoro/xds_k8s_lb.cfg
- buildscripts/kokoro/xds_k8s_lb.sh
Copy from psm-security kokoro configs.
It seems java is missing some general test cases. Psm-security is not suitable for this. Unless it gets renamed.
kokoro google3: https://critique.corp.google.com/cl/426268703
To be verified.
> buildscript: add kokoro basic tests xds k8s

- core/src/main/java/io/grpc/internal/ClientStreamListener.java
- core/src/main/java/io/grpc/internal/RetriableStream.java
- core/src/main/java/io/grpc/internal/SubchannelChannel.java
- core/src/test/java/io/grpc/internal/RetriableStreamTest.java
- interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java
- netty/src/main/java/io/grpc/netty/NettyClientHandler.java
- netty/src/main/java/io/grpc/netty/NettyClientStream.java
- netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
In core, add a new enum element to `RpcProgress` for the case that the stream is closed even before anything leaves the client. `RetriableStream` will do unlimited transparent retry for this type of `RpcProgress` since they are local-only.
In netty, call `tranportReportStatus()` for pending streams on failure.
> core/netty: infinite local-only transparent retry for netty

- xds/src/main/java/io/grpc/xds/internal/sds/CommonTlsContextUtil.java
- xds/src/test/java/io/grpc/xds/internal/sds/ClientSslContextProviderFactoryTest.java
- xds/src/test/java/io/grpc/xds/internal/sds/ServerSslContextProviderFactoryTest.java
Update `CommonTlsContextUtil` validation functions to accept new-style `CertificateProviderPluginInstance`
fixes #8885
> xds: fix the validation code to accept new-style CertificateProviderPluginInstance wherever used

- benchmarks/build.gradle
- benchmarks/src/main/java/io/grpc/benchmarks/SocketAddressValidator.java
- benchmarks/src/main/java/io/grpc/benchmarks/Transport.java
- benchmarks/src/main/java/io/grpc/benchmarks/Utils.java
- benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadClient.java
- benchmarks/src/main/java/io/grpc/benchmarks/qps/ClientConfiguration.java
- benchmarks/src/main/java/io/grpc/benchmarks/qps/ServerConfiguration.java
This allows using LoadClient with xDS.
The changes to SocketAddressValidator are a bit hacky, but we really
don't care about cleanliness there. Eventually on client-side, we should
be deleting the unix special case entirely, as we'll have a unix name
resolver.
Fixes #8877
----
I manually tested the QPS client, but not LoadClient. The change is small there, so I assume/hope it works; I find it really annoying to set up.
> benchmarks: Modernize client to use target and credentials

- xds/src/main/java/io/grpc/xds/XdsClient.java
- xds/src/main/java/io/grpc/xds/XdsNameResolver.java
- xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
- xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
- xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
Overlooked in #8857 on server side. Since `XdsNameResolver.percentEncodePath()` will be also used for server side, I moved the method to `XdsClient`.
> xds/federation: fix percent encoding on server side
