grpc/grpc-java

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
rls/src/main/java/io/grpc/rls/RlsLoadBalancer.java
rls/src/main/java/io/grpc/rls/RlsProtoConverters.java
rls/src/main/java/io/grpc/rls/RlsProtoData.java
rls/src/main/java/io/grpc/rls/RlsRequestFactory.java
rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
rls/src/test/java/io/grpc/rls/RlsProtoConvertersTest.java
rls/src/test/java/io/grpc/rls/RlsRequestFactoryTest.java

Refactor to use `@AutoValue` for data types. This reduces human mistakes on `equals()`, `hashCode()`, and `toString()` while we are constantly adding and changing member fields of the data type.

rls: migrate data types to AutoValue

---

xds/src/main/java/io/grpc/xds/internal/sds/CommonTlsContextUtil.java
xds/src/test/java/io/grpc/xds/internal/sds/ClientSslContextProviderFactoryTest.java
xds/src/test/java/io/grpc/xds/internal/sds/ServerSslContextProviderFactoryTest.java

xds: fix the validation code to accept new-style CertificateProviderPluginInstance wherever used (backport to 1.43.x))

---

xds/src/main/java/io/grpc/xds/internal/sds/CommonTlsContextUtil.java
xds/src/test/java/io/grpc/xds/internal/sds/ClientSslContextProviderFactoryTest.java
xds/src/test/java/io/grpc/xds/internal/sds/ServerSslContextProviderFactoryTest.java

CC @ejona86 
backport of #8892

xds: fix the validation code to accept new-style CertificateProviderPluginInstance wherever used (v1.44.x backport)

---

android/src/main/java/io/grpc/android/AndroidChannelBuilder.java

When an app goes to the background, onBlockedStatusChanged is called with true and then called with false when it comes back to the foreground. The function onAvailable isn't called in this case and the connection wasn't being reset. Closes #8850
I noticed the comment that this is used for API versions 24+ but onBlockedStatusChanged was added in 29. I'm not sure if some kind of guard needs to be added or not. 
https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback#onBlockedStatusChanged(android.net.Network,%20boolean)
Backport of #8855
CC @litclimbing, @larssn

Fix for reconnecting when Android app comes to the foreground (1.43.x backport)

---

android/src/main/java/io/grpc/android/AndroidChannelBuilder.java

When an app goes to the background, onBlockedStatusChanged is called with true and then called with false when it comes back to the foreground. The function onAvailable isn't called in this case and the connection wasn't being reset. Closes #8850
I noticed the comment that this is used for API versions 24+ but onBlockedStatusChanged was added in 29. I'm not sure if some kind of guard needs to be added or not. 
https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback#onBlockedStatusChanged(android.net.Network,%20boolean)
Backport of #8855
CC @litclimbing, @larssn

Fix for reconnecting when Android app comes to the foreground (1.44.x backport)

---

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java

Should consistently use the last '/' in the full method name as the separator between service name and method name in MethodDescriptor. (See https://github.com/grpc/grpc-java/blob/v1.44.0/api/src/main/java/io/grpc/MethodDescriptor.java#L421)

rls: fix service name and method name splitter

---

testing/src/main/java/io/grpc/testing/GrpcCleanupRule.java

Fix an issue in GrpcCleanupRule when tests are retried and the
teardown() method is invoked multiple times, causing Stopwatch instance
to throw an IllegalStateException.
fixes grpc/grpc-java#8917.

testing: fix GrpcCleanupRule issue when retrying tests

---

stub/src/main/java/io/grpc/stub/StreamObserver.java

"Characterizing thread safety" article is not available on ibm.com anymore. Linking to web archive.

doc: fix outdated external link

---

build.gradle
context/build.gradle

The Google Auth version is getting quite old. The new version pulls in
newer Guava and Auto Value. Two require Java 8: Google Auth since 1.x,
Guava since 31.x. Google Auth only needs Auto Value 1.8.2, but this
bumps to the latest, so all three are at their latest versions.

Bump Google Auth, Guava, Auto Value

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

The test for 10,000 took 10s to run and would time out when using other
tools like TSAN. "10000" was just a "very large number less than
infinity" and 1000 serves the same purpose and should similarly never
trigger. Using 1000 has the test run in 1s and TSAN completes in 17s.
The limit was originally added in dc6eaccc.

core: Decrease transparent retry limit to 1000

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java

Workaround for #8886, as we wait on a real fix. The regular load
balancing disconnections are confusing users and will train users to
start ignoring gRPC warnings. At present, it is better to have no log
than excessively log.
CC @YifeiZhuang, @erikjoh
----
I've not manually tested this and I'd be happy if someone confirmed it cleaned up the 15 minute RPC churn logging with TD.

xds: Squelch ADS reconnection error logs

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java

Workaround for #8886, as we wait on a real fix. The regular load
balancing disconnections are confusing users and will train users to
start ignoring gRPC warnings. At present, it is better to have no log
than excessively log.
CC @YifeiZhuang, @erikjoh
----
Backport of #8941

xds: Squelch ADS reconnection error logs (1.45.x backport)

---

xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java

Consists of two commits, the fix is in 2nd one, and the 1st only improves the test and does not impact the fix even without it.

xds: Do not failover priority when IDLE->CONNECTING

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

fix https://github.com/grpc/grpc-java/issues/8950

xds: fix XdsNameResolver blindly propagates XdsClient errors

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

2a45524 introduced '.' to the end of some status descriptions. We
typically don't end status descriptiosn in periods, but that's minor. In
this case though if the causal status ends in period then the new status
will end in two periods, which could easily be confusing to users.

xds: Don't end status with '.' in XdsNameResolver

---

binder/src/androidTest/java/io/grpc/binder/internal/BinderClientTransportTest.java
binder/src/main/java/io/grpc/binder/internal/BinderTransport.java
core/src/main/java/io/grpc/internal/ManagedClientTransport.java
core/src/test/java/io/grpc/internal/AbstractTransportTest.java

Update javadoc to mention this previously-unwritten rule.
Update earlyServerClose_serverFailure_withClientCancelOnListenerClosed to obey it.
Update BinderTransport to fail sooner and with a better message if this rule is broken.

New streams before transportReady() are not guaranteed to work

---

googleapis/build.gradle
googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolver.java
googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolverProvider.java
googleapis/src/main/resources/META-INF/services/io.grpc.NameResolverProvider
googleapis/src/test/java/io/grpc/googleapis/GoogleCloudToProdNameResolverProviderTest.java
googleapis/src/test/java/io/grpc/googleapis/GoogleCloudToProdNameResolverTest.java
settings.gradle
xds/src/main/java/io/grpc/xds/InternalSharedXdsClientPoolProvider.java
xds/src/main/resources/META-INF/services/io.grpc.NameResolverProvider

GoogleCloudToProdNameResolver has a hard dependency on alts whereas xds
only has a weak dependency on alts that can be solved by a
ChannelCredentialsRegistry. So split out the code to a separate
artifact.
CC @apolcyn

googleapis: Move GoogleCloudToProdNameResolver from xds

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

backport of https://github.com/grpc/grpc-java/pull/8953

xds: fix XdsNameResolver blindly propagates XdsClient errors (1.45.x backport)  (#8953)

---

googleapis/build.gradle
googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolver.java
googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolverProvider.java
googleapis/src/main/resources/META-INF/services/io.grpc.NameResolverProvider
googleapis/src/test/java/io/grpc/googleapis/GoogleCloudToProdNameResolverProviderTest.java
googleapis/src/test/java/io/grpc/googleapis/GoogleCloudToProdNameResolverTest.java
settings.gradle
xds/src/main/java/io/grpc/xds/InternalSharedXdsClientPoolProvider.java
xds/src/main/resources/META-INF/services/io.grpc.NameResolverProvider

GoogleCloudToProdNameResolver has a hard dependency on alts whereas xds
only has a weak dependency on alts that can be solved by a
ChannelCredentialsRegistry. So split out the code to a separate
artifact.
CC @apolcyn 
Backport of #8961

googleapis: Move GoogleCloudToProdNameResolver from xds (1.45.x backport)

---

xds/src/main/java/io/grpc/xds/BootstrapperImpl.java

It isn't used outside the package and is showing up in Javadoc. Instead
of excluding it from the Javadoc, just make it package-private.

xds: BootstrapperImpl should not be public

---

xds/src/main/java/io/grpc/xds/BootstrapperImpl.java

It isn't used outside the package and is showing up in Javadoc. Instead
of excluding it from the Javadoc, just make it package-private.
Backport of #8962

xds: BootstrapperImpl should not be public (1.45.x backport)

---

interop-testing/src/main/java/io/grpc/testing/integration/GrpclbFallbackTestClient.java

We currently use a 5 second fallback timeout with this client in certain cases where we expect fallback to happen ~immediately.
However, we frequently surpass that 5 second timeout in automated runs. Repro'ing manually, I can see the test client consistently spend its first few seconds burning 100% CPU - so I suspect there is some expensive stuff that happens the first time we make an RPC, loading dependencies etc.
Adding a warmup phase to the test should get the initialization things out of the way (which is not relevant for the test), and let us keep the 5 second timeout.
b/213963877

Add a configurable warmup phase to fallback test client

---

stub/src/main/java/io/grpc/stub/ClientCalls.java
stub/src/test/java/io/grpc/stub/ClientCallsTest.java

redo https://github.com/grpc/grpc-java/pull/8847 but disable by default, we will enable after we fix https://github.com/grpc/grpc-java/issues/8928

stub: ClientCalls.ThreadlessExecutor throws rejectedExecutorException disable by default

---

binder/src/androidTest/java/io/grpc/binder/internal/BinderTransportTest.java
binder/src/main/java/io/grpc/binder/internal/BinderTransport.java
binder/src/main/java/io/grpc/binder/internal/OneWayBinderProxy.java
binder/src/main/java/io/grpc/binder/internal/Outbound.java
binder/src/main/java/io/grpc/binder/internal/ParcelHolder.java
binder/src/test/java/io/grpc/binder/internal/OneWayBinderProxyTest.java

binder: Dispatch transact() calls on an Executor when FLAG_ONEWAY would not be respected.

---

buildscripts/kokoro/xds.sh

Giving this task another thought, we don't need to redirect older branches, as they are working fine. We are solving the issue of grpc/grpc delaying the release, causing GCE tests to fail. Updating the master branch prevents similar cases from happening.
Tested: [prod:grpc/java/master/branch/xds_v3](http://sponge/010f5353-e65e-4b1a-b6d3-f5a84e31546b )
Attempted: https://github.com/grpc/grpc-java/pull/8979

Redirect xDS tests to use grpc/grpc's master branch

---

observability/src/main/java/io/grpc/observability/Observability.java
observability/src/main/java/io/grpc/observability/interceptors/InternalLoggingServerInterceptor.java
observability/src/main/java/io/grpc/observability/interceptors/LogHelper.java
observability/src/test/java/io/grpc/observability/LoggingServerProviderTest.java
observability/src/test/java/io/grpc/observability/LoggingTest.java
observability/src/test/java/io/grpc/observability/LoggingTestHelper.java
observability/src/test/java/io/grpc/observability/interceptors/InternalLoggingServerInterceptorTest.java
observability/src/test/java/io/grpc/observability/interceptors/LogHelperTest.java

This PR implements Server Interceptor for logging i.e InternalLoggingServerInterceptor. Events are intercepted and a log record is written to logging as part of intercepting methods.
RPC messages will be logged if they are of following types:
- `com.google.protobuf.Message`
- `byte[]`

observability: implement server interceptor for logging

---

xds/src/main/java/io/grpc/xds/BootstrapperImpl.java
xds/src/main/java/io/grpc/xds/ClientXdsClient.java
xds/src/test/java/io/grpc/xds/BootstrapperImplTest.java
xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
xds/src/test/java/io/grpc/xds/ClientXdsClientV2Test.java
xds/src/test/java/io/grpc/xds/ClientXdsClientV3Test.java

The client sends the `xds.config.resource-in-sotw` capability to let the server know it can do this.
https://github.com/envoyproxy/envoy/blob/main/docs/root/api/client_features.rst
mirrors change in c core: https://github.com/grpc/grpc/pull/29090

xds: accept resources wrapped in a Resource message

---

interop-testing/src/main/java/io/grpc/testing/integration/GrpclbFallbackTestClient.java

For one test where we happen to be using the ring hash LB policy and packets towards backend addresses are dropped, we need to increase the fallback deadline to > 60 seconds, since the ring hash LB policy needs two connections to time out (and it looks like each has a 30 second initial/default timeout).
This parameterizes the fallback deadline, allowing us to do this, and also since it seems useful to have a flag for this for experimentation anyways.

Simplify fallback test client and parameterize fallback deadline

---

buildscripts/kokoro/xds_k8s_lb.sh

This test suite is only fully enabled for C++ and Python at this moment: https://github.com/grpc/grpc/blob/master/tools/internal_ci/linux/grpc_xds_k8s_lb.sh
This PR enables the rest of the test suite for grpc-java:
* change_backend_service_test
* failover_test
* remove_neg_test
* round_robin_test
* affinity_test
(CC @YifeiZhuang you mentioned that the tests were failing when deployed to Kokoro, it might be caused by using the wrong GKE clusters. You were using the "basic" cluster, which don't have workload-identity turned on.)
Tested: [prod:grpc/java/master/branch/xds_k8s_lb](https://fusion2.corp.google.com/invocations/66db2c32-2cbc-4a14-94e8-c7c49e9b25a0/targets)

Add more xds_lb test cases

---

rls/src/main/java/io/grpc/rls/RlsProtoConverters.java
rls/src/main/java/io/grpc/rls/RlsProtoData.java
rls/src/main/java/io/grpc/rls/RlsRequestFactory.java
rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java
rls/src/test/java/io/grpc/rls/RlsProtoConvertersTest.java
rls/src/test/java/io/grpc/rls/RlsRequestFactoryTest.java

The `grpcKeybuilders` [field](https://github.com/grpc/grpc-proto/blob/9fb243ce29b2e2576d3ef4fa2bd00ecba36aee31/grpc/lookup/v1/rls_config.proto#L176) should not be `grpcKeyBuilders` in json format.
The mistake in Java was introduced since the [beginning](https://github.com/grpc/grpc-java/commit/0fd4975d4c519056ec027dadc04872365369866e#diff-585b634c79155b4ac9417f7805e1b9d5f6d5c11a940c88e27fdf53c209e619cfR104).

rls: fix wrong grpcKeybuilders field name

---

observability/src/main/java/io/grpc/observability/GlobalLoggingTags.java
observability/src/main/java/io/grpc/observability/LoggingChannelProvider.java
observability/src/main/java/io/grpc/observability/LoggingServerProvider.java
observability/src/main/java/io/grpc/observability/Observability.java
observability/src/main/java/io/grpc/observability/ObservabilityConfig.java
observability/src/main/java/io/grpc/observability/ObservabilityConfigImpl.java
observability/src/main/java/io/grpc/observability/interceptors/InternalLoggingChannelInterceptor.java
observability/src/main/java/io/grpc/observability/interceptors/InternalLoggingServerInterceptor.java
observability/src/main/java/io/grpc/observability/interceptors/LogHelper.java
observability/src/test/java/io/grpc/observability/LoggingChannelProviderTest.java
observability/src/test/java/io/grpc/observability/LoggingServerProviderTest.java
observability/src/test/java/io/grpc/observability/LoggingTest.java
observability/src/test/java/io/grpc/observability/ObservabilityConfigImplTest.java
observability/src/test/java/io/grpc/observability/ObservabilityTest.java
observability/src/test/java/io/grpc/observability/interceptors/InternalLoggingChannelInterceptorTest.java
observability/src/test/java/io/grpc/observability/interceptors/InternalLoggingServerInterceptorTest.java
observability/src/test/java/io/grpc/observability/interceptors/LogHelperTest.java

wire observabilityConfig and globalTags into Observability and make
these available to the channel and server interceptors and specifially
to the LogHelper
CC @DNVindhya

observability: integrate globalTags and configuration into rest of observability

---

netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java
netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersUtilsTest.java

The previous code assumed that only gRPC would be using these methods.
But twice now Netty has made a change (generally relating to security)
that used a method for pseudo headers that previously wasn't supported.
Let's stop the whack-a-mole and just implement them all.
This restores compatibility with Netty 4.1.75.Final. Fixes #8981
CC @njhill
Alternative to #9001

netty: Support pseudo headers in all GrpcHttp2RequestHeaders methods

---

rls/src/main/java/io/grpc/rls/ChildLbResolvedAddressFactory.java

We shouldn't require addresses to be non-empty for the child lb of rls_lb. That might be a right requirement when the child lb is grpclb, but in our new usecase, the child lb will be cds lb and will only work if empty address is allowed.
Fixing b/223866089#comment24

rls: remove wrong empty address check for child lb

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java

This is similar to 2a45524 (for #8950) but for additional similar cases.

xds: Fix LBs blindly propagating XdsClient errors

---

netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java
netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersUtilsTest.java

The previous code assumed that only gRPC would be using these methods.
But twice now Netty has made a change (generally relating to security)
that used a method for pseudo headers that previously wasn't supported.
Let's stop the whack-a-mole and just implement them all.
This restores compatibility with Netty 4.1.75.Final. Fixes #8981
CC @njhill
Alternative to #9001
Backport of #9004

netty: Support pseudo headers in all GrpcHttp2RequestHeaders methods (1.44.x backport)

---

netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersUtils.java
netty/src/test/java/io/grpc/netty/GrpcHttp2HeadersUtilsTest.java

The previous code assumed that only gRPC would be using these methods.
But twice now Netty has made a change (generally relating to security)
that used a method for pseudo headers that previously wasn't supported.
Let's stop the whack-a-mole and just implement them all.
This restores compatibility with Netty 4.1.75.Final. Fixes #8981
CC @njhill
Alternative to #9001
Backport of #9004

netty: Support pseudo headers in all GrpcHttp2RequestHeaders methods (1.45.x backport)

---

xds/src/main/java/io/grpc/xds/ClientXdsClient.java
xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java

Return a null RouteAction when cluster has no cluster_specifier or route lookup is not enabled with a cluster_specifier_plugin.
We want to ignore the route in these situations, which is achieved by returning a null. The current behavior of returning an error triggers a NACK to the update.
cc: @ejona86 @sergiitk

xds: Allow unsupported cluster specifiers

---

android/src/main/java/io/grpc/android/AndroidChannelBuilder.java

Doing any reflection on OkHttpChannelBuilder requires that all methods
can have their arguments resolved. We'd like to make okhttp an optional
dependency (to support okhttp 2 and 3/4 simultaneously). But making
okhttp optional means we can no longer construct OkHttpChannelBuilder
reflectively. We swap to the Provider that doesn't have this problem.
See #8971.
Note that ManagedChannelProvider itself only exposes its methods as
protected, so they wouldn't be accessible. However OkHttpChannelProvider
has its methods public. It is an open question of whether
ManagedChannelProvider's methods should become public, but in any case
we can hide a public OkHttpChannelProvider inside a package-private
class so it is only accessable via reflection. So this code assuming
public methods doesn't prevent …

android: Use Provider to construct OkHttpChannelBuilder

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java

This is similar to 2a45524 (for #8950) but for additional similar cases.
Backport of #9012

xds: Fix LBs blindly propagating XdsClient errors (1.44.x backport)

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java

This is similar to 2a45524 (for #8950) but for additional similar cases.
Backport of #9012

xds: Fix LBs blindly propagating XdsClient errors (1.45.x backport)

---

xds/src/main/java/io/grpc/xds/BootstrapperImpl.java
xds/src/main/java/io/grpc/xds/XdsCredentialsProvider.java
xds/src/main/java/io/grpc/xds/XdsCredentialsRegistry.java
xds/src/main/java/io/grpc/xds/internal/GoogleDefaultXdsCredentialsProvider.java
xds/src/main/java/io/grpc/xds/internal/InsecureXdsCredentialsProvider.java
xds/src/main/java/io/grpc/xds/internal/TlsXdsCredentialsProvider.java
xds/src/main/resources/META-INF/services/io.grpc.xds.XdsCredentialsProvider
xds/src/test/java/io/grpc/xds/XdsCredentialsRegistryTest.java
xds/src/test/java/io/grpc/xds/internal/GoogleDefaultXdsCredentialsProviderTest.java
xds/src/test/java/io/grpc/xds/internal/InsecureXdsCredentialsProviderTest.java
xds/src/test/java/io/grpc/xds/internal/TlsXdsCredentialsProviderTest.java

Currently the credentials used for xDS communications is hardcoded in the BootstrapperImpl. The bootstrap config chooses one of the possible hardcoded credential.
This PR adds support for a credential plugin which allows users to register custom credentials through XdsCredentialProviders. gRPC will automatically discover the implementations via Java's SPI mechanism
Bootstrapper will use XdsCredentialRegistry to retrieve the list of supported credentials. The current hardcoded list of credentials(google_default, insecure and tls) are registered by default to keep the behavior as is.

xds: Support custom credentials using XdsCredentialsRegistry

---

bom/build.gradle

protoc-gen-grpc-java isn't useful in a BOM because the Gradle plugin
doesn't support BOMs (google/protobuf-gradle-plugin#412) and it seems
unlikely the Maven plugin would as well.
Right now the type is pom, which is useless; nobody cares about the pom
itself. We'd need to use a type of exe and repeat it for each platform
(classifier). Given that it is a strange case and we can't actually test
the results and having it in the bom might lead a user to trying to make
it work, let's just remove it for now until it provides value.
Fixes #8936

bom: Remove protoc-gen-grpc-java

---

build.gradle
observability/build.gradle
repositories.bzl

Perfmark 0.24.0 is much more defensive about class initialization failures, and speeds up class load time by a few millis.

all: bump PerfMark to 0.25.0

---

xds/src/main/java/io/grpc/xds/AbstractXdsClient.java
xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java

This would limit ADS stream creation to one per second, even if the
old stream was considered good as it received a response. This shouldn't
really ever trigger, and if it does 1 QPS is probably still too high.
But 1 QPS is _substantially_ better than a closed loop and there's very
few additional signals we could use to avoid resetting the backoff.
b/224833499

xds: Unconditionally apply backoff on ADS stream recreation

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

fix https://github.com/grpc/grpc-java/issues/8950
Backport of #8953

xds: fix XdsNameResolver blindly propagates XdsClient errors (1.44.x backport)

---

stub/src/main/java/io/grpc/stub/ClientCalls.java

It is only safe to shutdown the executor if onClose() is called. Normal
RPC completions (both success and failure) will see the future complete,
so this only avoids shutting down in stranger cases like an interceptor
throwing an exception.

stub: Shutdown ThreadlessExecutor only if onClose() is called

---

stub/src/main/java/io/grpc/stub/ClientCalls.java

Did dryrun tests on cl/[435778399](https://critique.corp.google.com/cl/435778399), enabling the flag, for multiple times, not seeing failures cases that are obviously caused by our change, so I am willing to give it a try. @ejona86 Wdyt?
[Tests](https://fusion2.corp.google.com/presubmit/tap/435778399/OCL:435778399:BASE:438328166:1648659337447:7c76ceba/targets) tended to be flaky. But the latest TAP train test signals that google3 might be ok if we enable it:
* latest [TAP results](https://fusion2.corp.google.com/presubmit/tap/435778399/OCL:435778399:BASE:437299065:1648259684626:2d898e6c/targets), initially some are broken
* rerun failure [successful](https://fusion2.corp.google.com/presubmit/tap/435778399/OCL:435778399:BASE:438131147:1648590406016:1aa1f966;groups=NewlyFailing,PossiblyNewly …

stub: try enable GRPC_CLIENT_CALL_REJECT_RUNNABLE

---

gcp-observability/src/main/java/io/grpc/gcp/observability/GlobalLoggingTags.java
gcp-observability/src/test/java/io/grpc/gcp/observability/GlobalLoggingTagsTest.java

gcp-observability: trim strings to remove newline for hostname and namespace name from files

---

xds/src/test/java/io/grpc/xds/XdsClientWrapperForServerSdsTestMisc.java
xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java

Just using 100ms is mostly sufficient, but could potentially still flake
on the start()s that should return successfully. Waiting for the
XdsServingStatusListener to be called greatly reduces the amount of
processing needing to be done for start() to react and thus should
greatly avoid flakiness.

xds: Reduce XdsServer.start() test time by 24.5s

---

core/src/test/java/io/grpc/internal/FakeClock.java
xds/src/test/java/io/grpc/xds/internal/certprovider/FileWatcherCertificateProviderTest.java

This reduces test time by 7 seconds.

xds: Remove sleeps in FileWatcherCertificateProviderTest

---

xds/src/main/java/io/grpc/xds/XdsCredentialsRegistry.java
xds/src/test/java/io/grpc/xds/XdsCredentialsRegistryTest.java

1. Unnecessary fully qualified names
Currently in XdsCredentialsRegistry, the child classes are referred by
their fully qualified names i.e.
'io.grpc.xds.internal.GoogleDefaultXdsCredentialsProvider' instead of
importing GoogleDefaultXdsCredentialsProvider and just using
GoogleDefaultXdsCredentialsProvider.class.
2. Use immutable interfaces instead of the generic collection interface
i.e. ImmutableMap instead of just Map in the unit tests.
These improvements are related to changes made in #8924.
@ejona86

xds: Improve code clarity by removing Unnecessary fully qualified names and using Immutable interface types.

---

core/src/test/java/io/grpc/internal/FakeClock.java
rls/src/test/java/io/grpc/rls/AdaptiveThrottlerTest.java

There was an attempt to use different epochs for the wall clock and the
monotonic clock. However, 123456789 is actually less than a second.
We want the gap between clocks to be at least a day. This issue was
discovered in #8968.
This separation found a bug in an RLS test where it was mixing epochs.
However, it was only a problem in the test. The code under test is
wrongly using wall clock for calculation durations, but that seems to be
a wide-spread problem and will need to be handled separately.

core: Vastly separate types of clock in FakeClock

---

okhttp/src/main/java/io/grpc/okhttp/ExceptionHandlingFrameWriter.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/ExceptionHandlingFrameWriterTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

With the completely different constructor it was hard to track which
fields were different during the test and reduced confidence. Now the
test code flows are much closer to the real-life code flows.
----
This is a pre-cleanup before forking the code for server-side.

okhttp: Avoid test-specific transport.start()

---

gcp-observability/src/main/java/io/grpc/gcp/observability/logging/GcpLogSink.java
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/ConfigFilterHelperTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/LogHelperTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/logging/GcpLogSinkTest.java

When GCP logging is enabled for a project different from source_project, add `source_project_id : project-id` as a `<key:value>` pair entry to custom tags for each log entry.
Value for `project-id` is retrieved from `locationTags` map created in `GlobalLoggingTags` as part of `GcpObservability.grpcInit()`.

gcp-observability: add source project id to labels when cross project logging is enabled

---

gcp-observability/src/main/java/io/grpc/gcp/observability/GlobalLoggingTags.java
gcp-observability/src/test/java/io/grpc/gcp/observability/GlobalLoggingTagsTest.java

Reading Config in non-GKE instances throws NPE, when kubernetes specific files does not exist. 
Fix: Added null check before doing `trim()`.

gcp-observability: add null check before trim() for non-GKE instances

---

gcp-observability/src/main/java/io/grpc/gcp/observability/ObservabilityConfig.java
gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/LogHelper.java
gcp-observability/src/main/java/io/grpc/gcp/observability/logging/GcpLogSink.java
gcp-observability/src/main/java/io/grpc/gcp/observability/logging/Sink.java

Making classes which are only used by gcp-observability internal.

gcp-observability: making classes in Observability Internal

---

binder/src/main/java/io/grpc/binder/internal/BinderTransport.java
binder/src/main/java/io/grpc/binder/internal/PingTracker.java
binder/src/test/java/io/grpc/binder/internal/PingTrackerTest.java

Ticker is powered by System.nanoTime() which is CLOCK_MONOTONIC.
TimeProvider is powered by System.currentTimeMillis() which is
CLOCK_REALTIME. For durations, the monotonic clock is appropriate, not
the wall time which can jump around.
-----
I just happened to notice this, because of fallout from https://github.com/grpc/grpc-java/pull/8968#discussion_r819975613 . Got me poking around a bit more and noticed this and an rls/ usage were inappropriate.

binder: Use Ticker for durations

---

binder/src/main/java/io/grpc/binder/AndroidComponentAddress.java
binder/src/test/java/io/grpc/binder/AndroidComponentAddressTest.java

... where a package filter can make filterEquals() inconsistent with filterHashCode() on SDK>=30
Fixes #9045

binder: Work around an Android Intent bug

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

This greatly reduces the number of arguments passed to the constructor
and allows using the builder in tests to change specific arguments
without having to pass all the other arguments. It also makes it easier
to see where tests are doing something special.
While it is weird to expose fields as package-private for digging-into
in the constructor, it's actually very similar to the pattern of passing
the builder instance into the constuctor. In this case, the weirdness is
because the builder isn't a nested class of the transport and there is
an additional level of building going on (Builder and TransportFactory).
We do this pattern already in ManagedChannelImpl which only has the one
level of building.
----
@temawi, @YifeiZhuang, if you are doubtful of whether this is an improvement, we can …

okhttp: Pass TransportFactory directly to transport constructor

---

okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

In the olden days, before LB policies, transports had to accept RPCs as
soon as they were created. This hasn't been true for a very long time,
so remove the tests.
Since a978c9ed we're using real, legit code flows in the tests. This
allowed TSAN to discover that `attributes` is racy when read when
creating a new stream before the transport is ready. We could use a lock
or volatile, but the value of the attributes would still be incorrect
for any RPCs that are created before the transport is ready.
Since there's now only one test that delays the connection, I inline the
support code.

okhttp: Remove RPCs-before-ready tests

---

xds/src/main/java/io/grpc/xds/LoadReportClient.java
xds/src/test/java/io/grpc/xds/LoadReportClientTest.java

This would limit LRS stream creation to one per second, even if the
old stream was considered good as it received a response. This is the
same change as made to ADS in 957079194a.
b/224833499

xds: Unconditionally apply backoff on LRS stream recreation

---

okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/Util.java

A substantial portion of the methods are unused. While these don't
contribute to the size of Android builds because of dead code
elimination in the build process, they still show up in static analysis
and raise questions like "when are we using MD5" or "when are we special
casing exception message text" (answer: "we're not").
CC @temawi

okhttp: Remove dead code in io.grpc.okhttp.internal.Util

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java

I'll leave the two commits separate when merging. Each commit has a description discussing what is going on a bit more.

okhttp: Improve internals for executor handling

---

xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java

per gRFC change https://github.com/grpc/grpc/pull/29332:
Apply new aggregation rule: If there is at least one subchannel in state TRANSIENT_FAILURE and there are more than one subchannel, report state CONNECTING. If we hit this rule, proactively start a subchannel connection attempt.
backport of https://github.com/grpc/grpc-java/pull/9084

xds: change ring_hash LB aggregation rule to handle transient_failure (1.46.x backport)

---

xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java

ringHashPicker changes per gRFC: https://github.com/grpc/grpc/pull/29332:
previously it appears the picker logic is wrong, e.g. not request connecting on the any subchannel if it is in TRANSIENT_FAILURE
Refactored the logic to mirror the pseudo-code more so easier to understand.
backport of https://github.com/grpc/grpc-java/pull/9085

 xds: fix ring-hash-picker behaviour (1.46.x backport)

---

xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java

changes in priority:
Keep track of whether a child has seen TRANSIENT_FAILURE more recently than IDLE or READY, and use this to decide whether to restart the failover timer when a child reports CONNECTING. This ensures that we properly start the failover timer when the ring_hash child policy transitions from IDLE to CONNECTING at startup.
Behaviour change also affects address updates the current priority from CONNECTING to CONNECTING, previously it reports one CONNECTING, right now it does not report and wait there due to failover timer in effect. This helps to try the next priority.
backport of https://github.com/grpc/grpc-java/pull/9093

xds: priority reset failover timer when connecting if seen ready or idle since TF (#9093) (1.46.x backport)

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
xds/src/main/java/io/grpc/xds/ClientXdsClient.java
xds/src/main/java/io/grpc/xds/LegacyLoadBalancerConfigFactory.java
xds/src/main/java/io/grpc/xds/XdsClient.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java
xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
xds/src/test/java/io/grpc/xds/LegacyLoadBalancerConfigFactoryTest.java

This refactoring is done in preparation of a larger change where LB configuration will be provided in the xDS Cluster proto message load_balancing_policy field. This field will allow for the configuration of custom LB policies with arbitrary configuration data.
- Instead of directly creating Java configuration objects, the client delegates to a new factory class to generate JSON configurations
- This factory is considered a "legacy" one as a separate factory will be introduced to build configs based on the new load_balancing_policy field
- The client will use a LoadBalancerProvider to parse the generated config to assure it is valid.
- Overlapping LB config validation that exists both in ClientXdsClient and LB providers will be removed from the client.
This is a second attempt at #8996 …

xds: ClientXdsClient to provide JSON LB configurations (v2)

---

api/src/main/java/io/grpc/ManagedChannelProvider.java
api/src/main/java/io/grpc/ManagedChannelRegistry.java
api/src/main/java/io/grpc/NameResolverProvider.java
api/src/test/java/io/grpc/ManagedChannelRegistryTest.java
core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
gcp-observability/src/main/java/io/grpc/gcp/observability/LoggingChannelProvider.java
googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolverProvider.java
grpclb/src/main/java/io/grpc/grpclb/SecretGrpclbNameResolverProvider.java
netty/src/main/java/io/grpc/netty/NettyChannelProvider.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelProvider.java
xds/src/main/java/io/grpc/xds/XdsNameResolverProvider.java

also add support for SocketAddress types in NameResolverProvider
Use scheme in target URI to select a NameRseolverProvider and get
that provider's supported SocketAddress types.
implement selection in ManagedChannelRegistry of appropriate
ManagedChannelProvider based on NameResolver's SocketAddress types
fixes #3085

api: add support for SocketAddress types in ManagedChannelProvider

---

xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java

part of ring-hash part of the change https://github.com/grpc/grpc/pull/29332:
Apply new aggregation rule: If there is at least one subchannel in state TRANSIENT_FAILURE and there are more than one subchannel, report state CONNECTING. If we hit this rule, proactively start a subchannel connection attempt.
backport of https://github.com/grpc/grpc-java/pull/9084

xds: change ring_hash LB aggregation rule to handles transient_failures (#9084) (1.44.x backport)

---

xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java

part of ring-hash part of the change https://github.com/grpc/grpc/pull/29332:
Apply new aggregation rule: If there is at least one subchannel in state TRANSIENT_FAILURE and there are more than one subchannel, report state CONNECTING. If we hit this rule, proactively start a subchannel connection attempt.
backport of https://github.com/grpc/grpc-java/pull/9084

xds: change ring_hash LB aggregation rule to handles transient_failures (#9084)(1.45.x backport)

---

xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java

ringHashPicker changes per gRFC: https://github.com/grpc/grpc/pull/29332:
previously it appears the picker logic is wrong, e.g. not request connecting on the any subchannel if it is in TRANSIENT_FAILURE
Refactored the logic to mirror the pseudo-code more so easier to understand.
backport of https://github.com/grpc/grpc-java/pull/9085

xds: fix ring-hash-picker behaviour (#9085) (1.45.x backport)

---

repositories.bzl

~~When I try to use `IO_GRPC_GRPC_JAVA_ARTIFACTS`, it can't parse `com.google.code.gson:gson:jar`~~
> `Error in fail: Error while fetching artifact with coursier: Resolution error: Error downloading com.google.code.gson:gson:jar
not found: not a valid blob`

fix artifact name in IO_GRPC_GRPC_JAVA_ARTIFACTS

---

authz/build.gradle
bom/build.gradle

grpc-observability was accidentally included in grpc-bom in 1.45
even though it was not published to Maven Central. This
is intended to reduce the likelihood of such things reoccurring. We only
include a project in the bom if it is using maven-publish and if the
publishing task is enabled.
onlyIf is very similar to enabled, except it is processed just before
the task is run. We need a more static property here, so swap to
enabled. If a project uses onlyIf in the future, grpc-bom won't be able
to automatically exclude it.

bom: Automatically exclude unpublished projects

---

bom/build.gradle

grpc-observability has publishing to Maven Central disabled. As
discovered in GoogleCloudPlatform/cloud-opensource-java#2303
Related: f2348b0 (#9120)
CC @temawi

bom: Exclude grpc-observability (v1.45.x)

---

xds/src/main/java/io/grpc/xds/InternalXdsAttributes.java
xds/src/main/java/io/grpc/xds/WrrLocalityLoadBalancer.java
xds/src/main/java/io/grpc/xds/WrrLocalityLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/XdsLbPolicies.java
xds/src/main/resources/META-INF/services/io.grpc.LoadBalancerProvider
xds/src/test/java/io/grpc/xds/WrrLocalityLoadBalancerProviderTest.java
xds/src/test/java/io/grpc/xds/WrrLocalityLoadBalancerTest.java

This LB is the parent for weighted_target and will configure it based on the child policy it gets in its configuration and locality weights that come in a ResolvedAddresses attribute.

xds: A new wrr_locality load balancer.

---

xds/src/main/java/io/grpc/xds/ClientXdsClient.java
xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java

fixing up https://github.com/grpc/proposal/pull/295

xds: NACK EDS resources with duplicate localities in the same priority

---

rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java

The test appears to be slow because of classloading. The failure cases
were very slow at 14-16 seconds, but looking at other logs it succeeds
after 12 seconds. It is the first test in the class, and the other tests
run much faster. This could be solved with warmup code, but increasing
the RPC deadline is easier.
Two back-to-back failures on aarch64:
https://source.cloud.google.com/results/invocations/c4612a28-d594-42e9-b8ab-12c999690b40/targets
https://source.cloud.google.com/results/invocations/3d5d1dc2-6b47-493d-b15c-e99458067d73/targets
```
expected to be true
at app//io.grpc.rls.CachingRlsLbClientTest.rls_withCustomRlsChannelServiceConfig(CachingRlsLbClientTest.java:267)
```
And the next run failed on a different line but seems the same cause: …

rls: Increase RPC timeout for flaky rls_withCustomRlsChannelServiceConfig

---

interop-testing/src/test/java/io/grpc/testing/integration/ConcurrencyTest.java

When a problem happens, it will now report back quickly instead of
waiting until the timeout expires. The timeout exception will also
report each RPC's state.
This is to help diagnose aarch64 test failures.

interop-testing: Improve ConcurrencyTest error reporting

---

benchmarks/src/test/java/io/grpc/benchmarks/driver/LoadWorkerTest.java

This will produce better error messages when the comparisons fail. This
is to help debug aarch64 test failures.

benchmarks: Use Truth in LoadWorkerTest

---

benchmarks/src/test/java/io/grpc/benchmarks/driver/LoadWorkerTest.java

This should fix test failures on aarch64.
```
expected to be less than: 0.0
but was                 : 0.0
at app//io.grpc.benchmarks.driver.LoadWorkerTest.assertWorkOccurred(LoadWorkerTest.java:198)
at app//io.grpc.benchmarks.driver.LoadWorkerTest.runUnaryBlockingClosedLoop(LoadWorkerTest.java:90)
```
runUnaryBlockingClosedLoop() has been failing but the other tests
suceeding. The failure is complaining that getCount() == 0, which means
no RPCs completed. The slowest successful test has a mean RPC time of
226 ms (the unit was logged incorrectly) and comparing to x86 tests
runUnaryBlockingClosedLoop() is ~2x as slow because it executes first.
So this is probably _barely_ failing and 4 attempts instead of 3 would
be sufficient. While the test tries to wait for 10 RPCs to complete, it
seems …

benchmarks: Increase timeout of LoadWorkerTest

---

api/src/main/java/io/grpc/ManagedChannelRegistry.java
build.gradle
netty/BUILD.bazel
netty/build.gradle
netty/src/main/java/io/grpc/netty/UdsNameResolver.java
netty/src/main/java/io/grpc/netty/UdsNameResolverProvider.java
netty/src/main/java/io/grpc/netty/UdsNettyChannelProvider.java
netty/src/main/java/io/grpc/netty/Utils.java
netty/src/main/resources/META-INF/services/io.grpc.ManagedChannelProvider
netty/src/main/resources/META-INF/services/io.grpc.NameResolverProvider
netty/src/test/java/io/grpc/netty/UdsNameResolverProviderTest.java
netty/src/test/java/io/grpc/netty/UdsNameResolverTest.java
netty/src/test/java/io/grpc/netty/UdsNettyChannelProviderTest.java

When the scheme is "unix:" we get the UdsNettyChannelProvider to
create a NettyChannelBuilder with DomainSocketAddress type and
other related params needed for UDS sockets
fixes #8884

netty: implement UdsNameResolver and UdsNettyChannelProvider

---

benchmarks/src/test/java/io/grpc/benchmarks/driver/LoadWorkerTest.java

Also clean up resources at the end of test.

benchmarks: Propagate errors in LoadWorkerTest startup

---

build.gradle
census/src/main/java/io/grpc/census/CensusTracingModule.java
census/src/test/java/io/grpc/census/CensusModulesTest.java
gcp-observability/build.gradle
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

This PR adds dependencies required to export metrics and traces data to stackdriver.
- Also, updates opencensus version to `0.31.0`.
- As part of version update, `io.opencensus.trace.unsafe.ContextUtils` has been deprecated, suppressing warnings for now.

gcp-observability:  add grpc-census as a dependency and update opencensus version

---

netty/src/main/java/io/grpc/netty/UdsNettyChannelProvider.java
netty/src/test/java/io/grpc/netty/UdsNettyChannelProviderTest.java

The transport should be usable with non-`unix:` name resolvers. As long
as the name resolver returns the correct socket address type, things
should work fine.
CC @temawi

netty: Simplify and increase compat of UdsNettyChannelProvider

---

bom/build.gradle

This reverts commit 4a84c6fa96f11eababb32ab691e3bf9b62c3d374. The BOM
was usable for protoc-gen-grpc-java using dependencyManagement for the
buildscript. See conversation on #9020.
CC @ST-DDT 
Backport of #9154

Revert "bom: Remove protoc-gen-grpc-java" (1.46.x backport)

---

services/src/main/java/io/grpc/services/InternalMetricRecorder.java
services/src/main/java/io/grpc/services/MetricRecorder.java
xds/src/main/java/io/grpc/xds/orca/OrcaMetrics.java
xds/src/main/java/io/grpc/xds/orca/OrcaServiceImpl.java
xds/src/test/java/io/grpc/xds/orca/OrcaServiceImplTest.java

* moved orcaMetrics to service project and renamed to `MetricRecorder`, added internal accessor. Maybe we can combine metricsRecorder and callMetricRecorder, they looks almost the same things.
* OrcaServiceImpl depends on metricRecorder, not visa versa.

xds: separate orca APIs and implementations

---

xds/src/main/java/io/grpc/xds/WrrLocalityLoadBalancer.java
xds/src/test/java/io/grpc/xds/WrrLocalityLoadBalancerTest.java

WrrLocalityLoadBalancer should remove the locality weights attribute from Resolved addresses after using the information. Not propagating this attribute will make it impossible for another child wrr_locality from working. This is not a supported situation and this change make the failure happen earlier and to be more obvious as to the cause.

xsd: wrr_locality to not propagate locality weight attribute

---

xds/src/main/java/io/grpc/xds/ClientXdsClient.java
xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java

Support for the is_optional logic in Cluster Specifier Plugins: if unsupported Cluster Specifier Plugin is optional, don't NACK, and skip any routes that point to it.
Related changes:
- grpc cpp: https://github.com/grpc/grpc/pull/29259
- grpc-go: https://github.com/grpc/grpc-go/pull/5269

xds: ignore routes with unsupported optional cluster specifiers

---

binder/src/main/java/io/grpc/binder/internal/Inbound.java
core/src/test/java/io/grpc/internal/AbstractTransportTest.java

Add check for request message count in binder grpc inbound stream.
Without check if messages are available and requested, producer provides everything that is available ignoring the request count. It leads to call listener API violation - it's possible that more messages will be provided than requested.

Respect requested message limits within a single MessageProducer in BinderTransport.

---

xds/src/main/java/io/grpc/xds/ClientXdsClient.java
xds/src/test/java/io/grpc/xds/ClientXdsClientDataTest.java

Fix for #9157.
Ping @sanjaypujare

xds: Allow unspecified listener traffic direction to work with Istio

---

BUILD.bazel
WORKSPACE
googleapis/BUILD.bazel
repositories.bzl
rls/BUILD.bazel
services/BUILD.bazel
xds/BUILD.bazel

Not updating the example WORKSPACE because it doesn't have any
Bazel-enabled build that depends on xds and so doesn't need the
additional repository dependencies.
Fixes #9162
CC @SanjayVas

Add Bazel build support for xds, googleapis to flesh out maven_install

---

api/src/main/java/io/grpc/ForwardingServerBuilder.java
api/src/main/java/io/grpc/ServerBuilder.java
core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java
netty/src/main/java/io/grpc/netty/NettyServerBuilder.java

These APIs were added to NettyServerBuilder for gRFC A8 and A9. They are
important enough that they shouldn't require using the perma-unstable
transport API to access. This change also allows using these methods
with grpc-netty-shaded.
Fixes #8991
----
We want them for the okhttp server as well.

api: Add connection management APIs to ServerBuilder

---

api/src/main/java/io/grpc/ServiceProviders.java
api/src/test/java/io/grpc/ServiceProvidersTest.java

This was observed in the Bazel/Blaze build where io.grpc.util is a
separate target from the rest of core. During the build of a library
SecretRoundRobinLoadBalancerProvider was not on the classpath, and the
library was later included into a binary using grpc-core from Maven
Central which includes SecretRoundRobinLoadBalancerProvider.
```
java.util.ServiceConfigurationError: Provider io.grpc.util.SecretRoundRobinLoadBalancerProvider$Provider could not be instantiated java.lang.ClassCastException: class io.grpc.util.SecretRoundRobinLoadBalancerProvider$Provider cannot be cast to some.app.aaa.aab
```

api: Ignore ClassCastExceptions for hard-coded providers

---

benchmarks/src/test/java/io/grpc/benchmarks/driver/LoadWorkerTest.java

runUnaryBlockingClosedLoop is failing after 10.3s, which means 5.3s was
probably spent loading the LoadWorker. That means things are likely
indeed slow enough that 5s isn't enough time to wait for the server to
start. A successful execution of runUnaryBlockingClosedLoop takes
12.1 seconds, which again points to general slow execution.

benchmarks: Raise timeout for aarch64

---

api/src/main/java/io/grpc/ServerCall.java
core/src/main/java/io/grpc/internal/ServerCallImpl.java
core/src/test/java/io/grpc/internal/ServerCallImplTest.java

This is a shot to [#7719](https://github.com/grpc/grpc-java/issues/7719).
Added a new method to ServerCall which returns `SecurityLevel.NONE` and ServerCallImpl returns the security level `getAttributes().get(ATTR_SECURITY_LEVEL),` in the case of uncertainty will return a lower level of security.

Expose SecurityLevel on server-side

---

binder/src/main/java/io/grpc/binder/SecurityPolicies.java
binder/src/test/java/io/grpc/binder/SecurityPoliciesTest.java

binder: Add SecurityPolicies#anyOf(), similar to allOf(). Adds some details to the allOf() javadoc and test assertions to match.

binder: Add SecurityPolicies#anyOf(), similar to allOf()

---

android-interop-testing/src/generated/debug/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
android-interop-testing/src/generated/release/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
buildscripts/sync-protos.sh
interop-testing/src/generated/main/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/main/java/io/grpc/testing/integration/ReconnectTestClient.java
interop-testing/src/main/java/io/grpc/testing/integration/Util.java
interop-testing/src/main/proto/grpc/testing/empty.proto
interop-testing/src/main/proto/grpc/testing/messages.proto
interop-testing/src/main/proto/grpc/testing/test.proto
services/src/main/proto/grpc/channelz/v1/channelz.proto

Two main incompatibilities existed in the copy of protos in grpc-proto:
no SimpleContext and an Empty method argument was replaced with a
message. "Context" is a very old word for "Metadata" back from the days
before the current gRPC protocol. We don't need that message in
particular, and well-known protos actually works in Protobuf Lite these
days, so we can swap to wrappers.proto's StringValue and don't need to
upstream a change to grpc-proto. The argument problem is fixed just by
changing the type in the Java code.
With the incompatibilities fixed, do a sync from grpc-proto and include
interop-testing.

interop-testing: Support syncing protos from grpc-proto

---

interop-testing/src/main/java/io/grpc/testing/integration/RpcBehaviorLoadBalancerProvider.java
interop-testing/src/main/resources/META-INF/services/io.grpc.LoadBalancerProvider
interop-testing/src/test/java/io/grpc/testing/integration/RpcBehaviorLoadBalancerProviderTest.java

This load balancer can be used to trigger custom behavior on servers for all calls that use the LB.

interop-testing: LB that adds the rpc-behavior to calls

---

xds/src/main/java/io/grpc/xds/BootstrapperImpl.java
xds/src/main/java/io/grpc/xds/ClientXdsClient.java
xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java

There are still some cases for xdstp processing, but they are to percent
encoding replacement strings. Those seem better to leave running since
it looks like it they could be triggered even with federation disabled
in the bootstrap processing.
Backport of #9190

xds: Protect xdstp processing with federation env var (1.45.x backport)

---

xds/src/main/java/io/grpc/xds/BootstrapperImpl.java
xds/src/main/java/io/grpc/xds/ClientXdsClient.java
xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java

There are still some cases for xdstp processing, but they are to percent
encoding replacement strings. Those seem better to leave running since
it looks like it they could be triggered even with federation disabled
in the bootstrap processing.
Backport of #9190

xds: Protect xdstp processing with federation env var (1.46.x backport)

---

xds/src/main/java/io/grpc/xds/BootstrapperImpl.java
xds/src/main/java/io/grpc/xds/ClientXdsClient.java
xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java

There are still some cases for xdstp processing, but they are to percent
encoding replacement strings. Those seem better to leave running since
it looks like it they could be triggered even with federation disabled
in the bootstrap processing.
Backport of #9190

xds: Protect xdstp processing with federation env var (1.47.x backport)

---

xds/src/main/java/io/grpc/xds/WrrLocalityLoadBalancer.java
xds/src/test/java/io/grpc/xds/FakeControlPlaneXdsIntegrationTest.java
xds/src/test/java/io/grpc/xds/MetadataLoadBalancerProvider.java
xds/src/test/java/io/grpc/xds/WrrLocalityLoadBalancerTest.java

Fixes a bug where WrrLocalityLoadBalancer would use the endpoint picking policy provider instead of WeightedTargetLoadBalancerProvider.
Also adds a test to fake control plane integration test that caught this bug. The test scaffolding is also updated to have the test server echo all client headers back in the response.
The test load balancer in the test is an almost straight copy of: https://github.com/grpc/grpc-java/blob/master/interop-testing/src/test/java/io/grpc/testing/integration/RpcBehaviorLoadBalancerProviderTest.java

xds: Use weighted_target LB provider in wrr_locality

---

xds/src/main/java/io/grpc/xds/LoadBalancerConfigFactory.java
xds/src/test/java/io/grpc/xds/LoadBalancerConfigFactoryTest.java

The legacy com.github.udpa.udpa.type.v1.TypedStruct proto should be supported in addition to the current com.github.udpa.udpa.type.v1.TypedStruct one.

xds: Custom LB configs to support UDPA TypeStruct

---

interop-testing/src/main/java/io/grpc/testing/integration/RpcBehaviorLoadBalancerProvider.java
interop-testing/src/test/java/io/grpc/testing/integration/RpcBehaviorLoadBalancerProviderTest.java

Fixes a bug where the picker was not getting used in RpcBehaviorLoadBalancer.

xds: Properly assign picker.

---

examples/example-xds/settings.gradle

Previously examples-xds depended on the normal hello-world, as it used
the same classes. But since b6601ba273f it has had its own classes and
not had a dependency on `:examples.

examples/xds: Remove unnecessary includeBuild ..

---

buildscripts/kokoro/xds.sh

Backports https://github.com/grpc/grpc-java/pull/9199.
* [xds](http://sponge/77084ffc-bf00-47c9-a026-e06f88052952)
* [xds_v3](http://sponge/0ae23634-ecc7-41da-b89d-eb2942bcde9d)
* [xds_k8s_lb](http://sponge/d14f79bb-0adb-4400-abe5-dda40fee3dd0)
* [xds_url_map](http://sponge/a07a5248-03b5-4fc1-b319-e59c743aafee)

interop-test: Remove duplicated GCE tests (v1.47.x backport)

---

buildscripts/kokoro/xds.sh

Backports https://github.com/grpc/grpc-java/pull/9199.
* [xds](http://sponge/3da3cf9c-1135-4c5a-9bca-a2b811796abd)
* [xds_v3](http://sponge/4e358c72-a984-461f-bb4c-caf8ce4dbd18)
* [xds_k8s_lb](http://sponge/b6ffb846-b515-4dd2-8220-24da2af9ab68)
* [xds_url_map](http://sponge/260e678f-f3a6-472b-8618-c392e923b927)

interop-test: Remove duplicated GCE tests (v1.46.x backport)

---

buildscripts/kokoro/xds.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backports https://github.com/grpc/grpc-java/pull/9199 https://github.com/grpc/grpc-java/pull/8998 https://github.com/grpc/grpc-java/pull/8982. The xds_k8s_lb and xds_url_map files were copied from master branch.
* [xds](http://sponge/df42d85b-d7d4-46c9-b878-6c847ba7647f)
* [xds_v3](http://sponge/20152816-b58b-4e49-8c6a-950e52a93197)
* [xds_k8s_lb](http://sponge/8a7f6bf8-29a7-4113-8f3c-9c755c1d2e2a)
* [xds_url_map](http://sponge/a34673de-279c-4811-861e-74aa516a90f9)

interop-test: Opt-in GKE tests && Remove duplicated GCE tests (v1.45.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds.sh
buildscripts/kokoro/xds_k8s_lb.cfg
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.cfg
buildscripts/kokoro/xds_url_map.sh
buildscripts/xds-k8s/cloudbuild.yaml

Backports #8400 #8573 #8534 #8340 #8344 #8429 https://github.com/grpc/grpc-java/pull/8534 https://github.com/grpc/grpc-java/pull/8888 https://github.com/grpc/grpc-java/pull/8998 https://github.com/grpc/grpc-java/pull/8982 https://github.com/grpc/grpc-java/pull/9199.
* [xds](http://sponge/b9dcd2d3-4db7-4d59-b4d6-4e776ca622d8)
* [xds_v3](http://sponge/eaf73ba6-1da5-4449-971c-ad30c7e50525)
* [xds_k8s_lb](http://sponge/0fee1bfa-eaeb-4951-a6f9-a44c86f80ae7)
* [xds_url_map](http://sponge/e2ec35cd-f220-4e92-8fbe-b1cd2eae3aac)

interop-test: Opt-in GKE tests && Remove duplicated GCE tests (v1.39.x backport)

---

build.gradle
compiler/src/java_plugin/cpp/java_generator.cpp

Protobuf 3.21 [renamed](https://github.com/protocolbuffers/protobuf/commit/40db3dabf0fe72b572e89c1e176318b04d3e2408#diff-5f26c0a0569a037848b977aa23ab7107d6939e1d3886c6254aee00e19664fd06) `google/protobuf/compiler/java/java_names.h` to `google/protobuf/compiler/java/names.h`
Fixes #9220

Update to handle rename of java_names.h to names.h in protobuf upstream

---

build.gradle
examples/pom.xml
gcp-observability/build.gradle
repositories.bzl

Justification for the update: `gson` 2.8.9 and older has a security [vulnerability issue](https://nvd.nist.gov/vuln/detail/CVE-2022-25647). 
That also required updating `google-http-client` from 1.41.0 to 1.41.8.
`gradle test` passes.
Backport of #9215. CC @mirlord

Bump GSON to 2.9.0 (1.47.x backport)

---

compiler/src/java_plugin/cpp/java_generator.cpp

Protobuf 3.21 [renamed](https://github.com/protocolbuffers/protobuf/commit/40db3dabf0fe72b572e89c1e176318b04d3e2408#diff-5f26c0a0569a037848b977aa23ab7107d6939e1d3886c6254aee00e19664fd06) `google/protobuf/compiler/java/java_names.h` to `google/protobuf/compiler/java/names.h`
Fixes #9220
Backport of #9218. CC @jvolkman

Update to handle rename of java_names.h to names.h in protobuf upstream (1.47.x backport)

---

README.md
build.gradle
compiler/src/test/golden/TestDeprecatedService.java.txt
compiler/src/test/golden/TestService.java.txt
compiler/src/testLite/golden/TestDeprecatedService.java.txt
compiler/src/testLite/golden/TestService.java.txt
core/src/main/java/io/grpc/internal/GrpcUtil.java
cronet/README.md
documentation/android-channel-builder.md
examples/android/clientcache/app/build.gradle
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/strictmode/app/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-hostname/build.gradle
examples/example-hostname/pom.xml
examples/example-jwt-auth/build.gradle
examples/example-jwt-auth/pom.xml
examples/example-orca/build.gradle
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/example-xds/build.gradle
examples/pom.xml

A few notes:
1. Apparently we had `1.45.1` in the README.md (and other), not `1.46.0`
2. Bumped `com.google.protobuf` gradle plugin from `0.8.17` to `0.8.18` to be in sync with the `v1.47.x`'s settings.gradle: https://github.com/grpc/grpc-java/blob/e0238df70a33b649fa9bd9adfbc00a17fd27c9e7/settings.gradle#L8

Release v1.47.0

---

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceImpl.java
interop-testing/src/main/proto/grpc/testing/messages.proto

discovered during import, used : `../buildscripts/sync-protos.sh ` to sync proto

interop-test: sync grpc-proto and fix typo

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java

This should have been included in #8746 but wasn't.

core: Add missed internal comment about idle mode workaround

---

api/src/main/java/io/grpc/Attributes.java

The text here should be expanded once `keys()` is removed. But for now
this at least can make it clearer that the current behavior is on
purpose. The text here is the same as that in CallOptions.Key.
See https://github.com/grpc/grpc-java/issues/1764#issuecomment-1144935608

api: Document Attributes.Key uses reference equality

---

api/src/main/java/io/grpc/ServerBuilder.java

Most are not allowed to be zero. Grace period can be zero to immediately
close the connection when the age is hit. A zero permitKeepAliveTime()
simply doesn't enforce any limits on the client.
The choices here precisely matches the pre-existing Netty behavior, but
also seems to make sense in general.
CC @sergiitk

api: Document illegal arguments for server connection management APIs

---

gcp-observability/src/main/java/io/grpc/gcp/observability/logging/GcpLogSink.java
gcp-observability/src/test/java/io/grpc/gcp/observability/logging/GcpLogSinkTest.java

Change the gRPC o11y logName when sending logs to GCP.
From: grpc
To: microservices.googelapis.com%2Fobservability%2Fgrpc

Change the gRPC o11y logName when sending logs to GCP.

---

testing/src/main/java/io/grpc/testing/GrpcCleanupRule.java
testing/src/test/java/io/grpc/testing/GrpcCleanupRuleTest.java

This allows using GrpcCleanupRule with JUnit 5 when combined with
ExternalResourceSupport. We don't really lose anything important when
running with JUnit 4 and this eases migration to JUnit 5.
ExternalResource is now responsible for combining exceptions. after()
cannot throw checked exceptions, so we must now wrap the
InterruptedException. When used with JUnit 5 we are unable to detect the
test failed; we accept that for now but it may be fair to create a new
class for JUnit 5 to be used with `@RegisterExtension` that implements
BeforeEachCallback and AfterTestExecutionCallback to restore the JUnit 4
behavior.
See #5331

testing: Have GrpcCleanupRule extend ExternalResource

---

xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java

It's hard to create a test for this because the hash generated is pretty much arbitrary currently (see the existing TODO; the answer to that question is "no, it isn't correct").

xds: Fix hash gen in RingHash when generating more than 10 hashes

---

api/src/main/java/io/grpc/GlobalInterceptors.java
api/src/main/java/io/grpc/InternalGlobalInterceptors.java
api/src/test/java/io/grpc/GlobalInterceptorsTest.java

GlobalInterceptors API will be used to set global interceptors and global stream tracers.  
The API is intended for `Internal` use only for time being. It currently supports 
- `ClientInterceptor`
- `ServerInterceptor`
- `ClientStreamTracer Factory`
Sample use case:
These interceptors and tracer factories can be set by grpc observability and be queried later by grpc to set into each builder created as well as by direct users of Netty channel/server builders (as required).

api: Add GlobalInterceptors API

---

interop-testing/src/main/java/io/grpc/testing/integration/TestServiceImpl.java

this fix the problem that multiple clients run other unary test cases in parallel against the same server:
see [successful run](https://source.cloud.google.com/results/invocations/e1e21c7c-3942-420b-9101-2adad9f52825/log) on interop test driver change: https://github.com/grpc/grpc/pull/29791

interop-testing: skip empty orca updates for unary at the server 

---

api/src/test/java/io/grpc/GlobalInterceptorsTest.java

Internal build failed with 
```
grpc/api/src/test/java/io/grpc/GlobalInterceptorsTest.java:28: error: 
[JUnit4RunWithMissing] Test class may not be run because it is missing a @RunWith annotation
public class GlobalInterceptorsTest {
^
Did you mean '@RunWith(JUnit4.class)' or 'public abstract class GlobalInterceptorsTest {'?
```
Ref:
- https://github.com/grpc/grpc-java/pull/9235
- cl/454182049
cc @DNVindhya

api: Add missing RunWith annotation to GlobalInterceptorsTest

---

repositories.bzl
xds/BUILD.bazel
xds/src/main/java/io/grpc/xds/LoadBalancerConfigFactory.java
xds/src/test/java/io/grpc/xds/LoadBalancerConfigFactoryTest.java

Allows the least_request load balancer to be configured via the control plane using the new LoadBalancingPolicy message in Cluster.

xds: Support least_request LB in LoadBalancingPolicy

---

alts/build.gradle
android-interop-testing/build.gradle
android/build.gradle
api/build.gradle
auth/build.gradle
authz/build.gradle
benchmarks/build.gradle
binder/build.gradle
build.gradle
census/build.gradle
compiler/build.gradle
core/build.gradle
cronet/build.gradle
gae-interop-testing/gae-jdk8/build.gradle
gcp-observability/build.gradle
gradle/libs.versions.toml
grpclb/build.gradle
interop-testing/build.gradle
netty/build.gradle
netty/shaded/build.gradle
okhttp/build.gradle
protobuf-lite/build.gradle
protobuf/build.gradle
rls/build.gradle
services/build.gradle
settings.gradle
stub/build.gradle
testing-proto/build.gradle
testing/build.gradle
xds/build.gradle

Note that there are two commits here. One makes a preping change.
I've confirmed the poms produced are equivalent.
This moves our depedencies into a plain file that can be read and
updated by tooling. While the current tooling is not particularly better
than just using gradle-versions-plugin, it should put us on better
footing. gradle-versions-plugin is actually pretty nice, but will be
incompatible with Gradle 8, so we need to wait a bit to see what the
future holds.
Left libraries as an alias for libs to reduce the commit size and make
it easier to revert if we don't end up liking this approach.
We're using Gradle 7.3.3 where it was an incubating fetaure. But in
Gradle 7.4 is became stable.

Use Gradle's version catalog

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

If the failure is before the NameResolver has returned the first time,
RPCs would be queued waiting for service config. We don't want to use
the ConfigSelector, as we are trying to circumvent the NameResolver and
LoadBalancer.
Fixes #9257
CC @hikoma

core: Clear ConfigSelector in panic mode

---

build.gradle

The generated Class-Path is simply wrong and it will actually be
attempted to be used at runtime.
Fixes #8606

build.gradle: Clear Class-Path from shadowJar manifest

---

xds/src/main/java/io/grpc/xds/XdsServerWrapper.java
xds/src/test/java/io/grpc/xds/XdsServerWrapperTest.java

also add a unit test to test server restart on LdsUpdate

xds: when delegate server throws on start communicate the error to statusListener

---

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceImpl.java
interop-testing/src/main/proto/grpc/testing/messages.proto

[successful kokoro run](https://source.cloud.google.com/results/invocations/f5564114-7b0a-45ae-8bd7-2fee233d9d1c/log)
[latest kokoro run](https://source.cloud.google.com/results/invocations/8118505b-1256-4ed9-bb92-e1df271edf7a/log)

interop-testing: add orca_oob lock to allow only one test client at a time to perform the test case

---

netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyServerBuilder.java

Includes pushing @CanIgnoreReturnValue annotations down from the
class-level to method-level.
----
This will make it easier to accidentally be missing `@CanIgnoreReturnValue` on builder methods. But the next release of ErrorProne includes a check that notices the `return this` pattern and suggests the ignore. Unfortunately new versions of ErrorProne require Java 11 so we have some build issues to figure out.
CC @kluever ; cl/455143849

Tidy up @CheckReturnValue / @CanIgnoreReturnValue annotations

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

kokoro: standard TESTING_VERSION in k8s framework build scripts

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

kokoro: standard TESTING_VERSION in k8s framework build scripts (1.43.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

kokoro: standard TESTING_VERSION in k8s framework build scripts (1.41.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

kokoro: standard TESTING_VERSION in k8s framework build scripts (1.47.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

kokoro: standard TESTING_VERSION in k8s framework build scripts (1.46.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

kokoro: standard TESTING_VERSION in k8s framework build scripts (1.40.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

kokoro: standard TESTING_VERSION in k8s framework build scripts (1.45.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

kokoro: standard TESTING_VERSION in k8s framework build scripts (1.39.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

kokoro: standard TESTING_VERSION in k8s framework build scripts (1.42.x backport)

---

WORKSPACE
repositories.bzl

This seems like a poorly thought-out feature for maven_install in a
world where the dependency list is being combined from multiple
repositories, as it means all Bazel-aware dependencies must subscribe to
the idea this is good and useful. It also loses effectiveness as
transitive dependencies are likely to be included directly in
maven_install; users of gRPC can use netty, guava, and other
dependencies without explicitly defining them even with
strict_visibility=True. Given maven_install still complains
about "Found duplicate artifact versions", it isn't too surprising it
doesn't make sense in a multi-repo world.
This isn't a bad feature for gRPC as we are pretty low-level and it can
be helpful when making bazel dependency versions match gradle dependency
versions. But it doesn't …

bazel: Support maven_install's strict_visibility=True

---

buildscripts/kokoro/linux_artifacts.sh
buildscripts/kokoro/unix.sh
buildscripts/kokoro/upload_artifacts.sh
buildscripts/make_dependencies.sh
compiler/build.gradle
compiler/check-artifact.sh

..on the lines of https://github.com/grpc/grpc-java/pull/6441

Add support for cross-compiling for ppc64le platform

---

core/src/main/java/io/grpc/internal/ServerCallImpl.java
core/src/test/java/io/grpc/internal/ServerCallImplTest.java
interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java

Avoid flushing the stream after writing a message in case the server returns a single response

---

interop-testing/src/generated/main/grpc/io/grpc/testing/istio/EchoTestServiceGrpc.java
interop-testing/src/main/java/io/grpc/testing/istio/EchoTestServer.java
interop-testing/src/main/proto/istio/testing/echo.proto
interop-testing/src/test/java/io/grpc/testing/istio/EchoTestServerTest.java

This is based on the echo-server in C++ (ref: https://github.com/grpc/grpc/blob/master/test/cpp/interop/istio_echo_server.cc + https://github.com/grpc/grpc/blob/master/test/cpp/interop/istio_echo_server_lib.cc)
@yashykt

interop-testing: add echo-server for proxyless gRPC testing in Istio

---

stub/src/main/java/io/grpc/stub/ClientResponseObserver.java

stub: fix misspelled javadoc

---

netty/src/main/java/io/grpc/netty/Utils.java
netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

Both Netty and OkHttp had local and remote windows flipped. Also, the
comment in OkHttp about "not tracked" wasn't true, so make it more
accurate and provide a _hint_ of what the window may be instead of just
-1.
----
For reference:
https://github.com/grpc/grpc-proto/blob/99b9845f1df4313b87e878d0ad94ba994c1e06ca/grpc/channelz/v1/channelz.proto#L282
https://netty.io/4.1/api/io/netty/handler/codec/http2/Http2LocalFlowController.html

Fix Channelz window reporting

---

core/src/main/java/io/grpc/internal/CallCredentialsApplyingTransportFactory.java
core/src/test/java/io/grpc/internal/CallCredentialsApplyingTest.java

Previously would use the executor provided in CallOptions if it was present.  Now that executor is ignored.

core: Always pass offload executor to CallCredentials

---

api/src/main/java/io/grpc/GlobalInterceptors.java
api/src/main/java/io/grpc/InternalGlobalInterceptors.java
api/src/test/java/io/grpc/GlobalInterceptorsTest.java
core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java
core/src/main/java/io/grpc/internal/ServerImplBuilder.java
core/src/test/java/io/grpc/internal/ManagedChannelImplBuilderTest.java
core/src/test/java/io/grpc/internal/ServerImplBuilderTest.java

also added a getter in GlobalInterceptors to expose the set flag
CC @DNVindhya

api,core: change ManagedChannel and Server Builders to use GlobalInterceptors

---

COMPILING.md
buildscripts/kokoro/windows32.bat
buildscripts/kokoro/windows64.bat
buildscripts/make_dependencies.bat
buildscripts/make_dependencies.sh
examples/android/clientcache/app/build.gradle
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/strictmode/app/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-hostname/build.gradle
examples/example-hostname/pom.xml
examples/example-jwt-auth/build.gradle
examples/example-jwt-auth/pom.xml
examples/example-orca/build.gradle
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/example-xds/build.gradle
examples/pom.xml
gcp-observability/build.gradle
gradle/libs.versions.toml
repositories.bzl

Bump protobuf to 3.21.1

---

core/src/main/java/io/grpc/inprocess/InProcessTransport.java
examples/src/test/java/io/grpc/examples/helloworld/HelloWorldClientTest.java
examples/src/test/java/io/grpc/examples/helloworld/HelloWorldServerTest.java
examples/src/test/java/io/grpc/examples/routeguide/RouteGuideClientTest.java
examples/src/test/java/io/grpc/examples/routeguide/RouteGuideServerTest.java
stub/src/main/java/io/grpc/stub/ClientCalls.java

Fixes deadlocks caused by client and server listeners being called in a synchronized block  
Also support unary calls returning null values
Fixes #3084

core: Use SyncContext for InProcessTransport listener callbacks to avoid deadlocks

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

Previously if LDS/RDS were missing or improperly configured RPCs would
fail with "UNAVAILABLE: NameResolver returned no usable address errors".
That is very confusing and not helpful for debugging.
Ideally we'd also include the node id in this error message, but that's
a bit more involved and this is a huge improvement even without it.
b/237539851

xds: Fail RPCs with error details when resources are deleted

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpProtocolNegotiator.java

Fix for ipv6 link local with scope. If you try to connect passing address like "ipv6%wlan0" it will use 
```
public SNIHostName(String hostname) {
super(0, (hostname = IDN.toASCII((String)Objects.requireNonNull(hostname, "Server name value of host_name cannot be null"), 2)).getBytes(StandardCharsets.US_ASCII));
this.hostname = hostname;
this.checkHostName();
}
```
Which raises hostname is not valid because this method doesn't accept non ASCII characters. With the change it will use 
```
public SNIHostName(byte[] encoded) {
super(0, encoded);
try {
CharsetDecoder decoder = StandardCharsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).onUnmappableCharacter(CodingErrorAction.REPORT);
this.hostname = IDN.toASCII(decoder.decode(ByteBuffer.wrap(encoded)).toString());
} catch …
```

Fix for ipv6 link local with scope

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpProtocolNegotiator.java

Fix for ipv6 link local with scope. If you try to connect passing address like "ipv6%wlan0" it will use 
```
public SNIHostName(String hostname) {
super(0, (hostname = IDN.toASCII((String)Objects.requireNonNull(hostname, "Server name value of host_name cannot be null"), 2)).getBytes(StandardCharsets.US_ASCII));
this.hostname = hostname;
this.checkHostName();
}
```
Which raises hostname is not valid because this method doesn't accept non ASCII characters. With the change it will use 
```
public SNIHostName(byte[] encoded) {
super(0, encoded);
try {
CharsetDecoder decoder = StandardCharsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).onUnmappableCharacter(CodingErrorAction.REPORT);
this.hostname = IDN.toASCII(decoder.decode(ByteBuffer.wrap(encoded)).toString());
} catch …
```

Fix for ipv6 link local with scope (1.48.x backport)

---

gcp-observability/build.gradle
gradle/libs.versions.toml

If I didn't upgrade X there is probably a reason, but worst-case the
reason was "I was lazy." I did the easy stuff, so if upgrading caused
problems of any real sort I skipped it and moved on. The main other
reason is there's some stuff we're more conservative about upgrading,
but you can't distinguish one from the other in this commit.
Backport of #9329

Bump versions for assorted dependencies (1.48.x backport)

---

all/build.gradle
alts/build.gradle
android-interop-testing/build.gradle
android/build.gradle
api/build.gradle
authz/build.gradle
benchmarks/build.gradle
binder/build.gradle
build.gradle
census/build.gradle
compiler/build.gradle
core/build.gradle
gae-interop-testing/gae-jdk8/build.gradle
gcp-observability/build.gradle
grpclb/build.gradle
interop-testing/build.gradle
istio-interop-testing/build.gradle
netty/build.gradle
netty/shaded/build.gradle
okhttp/build.gradle
protobuf-lite/build.gradle
protobuf/build.gradle
rls/build.gradle
services/build.gradle
settings.gradle
stub/build.gradle
testing/build.gradle
xds/build.gradle

This can avoid creating an additional 736 tasks (previously 502 out of
1591 were not created). That's not all that important as the build time
is essentially the same, but this lets us see the poor behavior of the
protobuf plugin in our own project and increase our understanding of how
to avoid task creation when developing the plugin. Of the tasks still
being created, protobuf is the highest contributor with 165 tasks,
followed by maven-publish with 76 and appengine with 53. The remaining
59 are from our own build, but indirectly caused by maven-publish.
----
Before: https://scans.gradle.com/s/xqzdk3gmmm7vs/performance/configuration
After: https://scans.gradle.com/s/2agmuounbbzfa/performance/configuration

Use Gradle's task configuration avoidance APIs

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

https://github.com/grpc/grpc-java/pull/9269 probably pushed the build
b/238334438
CC @sergiitk

xds: Allow Gradle to use more memory when building interop

---

xds/src/main/java/io/grpc/xds/Bootstrapper.java
xds/src/main/java/io/grpc/xds/BootstrapperImpl.java
xds/src/main/java/io/grpc/xds/ClientXdsClient.java
xds/src/main/java/io/grpc/xds/XdsLogger.java
xds/src/test/java/io/grpc/xds/BootstrapperImplTest.java
xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
xds/src/test/java/io/grpc/xds/ClientXdsClientV2Test.java
xds/src/test/java/io/grpc/xds/ClientXdsClientV3Test.java

As defined in the gRFC [A53: Option for Ignoring xDS Resource Deletion](https://github.com/grpc/proposal/blob/master/A53-xds-ignore-resource-deletion.md).
Note for the reviewer: it'll probably be more convenient to review commit-by-commit. The test refactoring commit can be skipped: it's not required, but was very handy for implementing new tests, and modifying the old ones.

xds: implement ignore_resource_deletion server feature

---

grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancerProvider.java
interop-testing/src/main/java/io/grpc/testing/integration/RpcBehaviorLoadBalancerProvider.java
rls/src/main/java/io/grpc/rls/RlsLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
xds/src/main/java/io/grpc/xds/CdsLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/LeastRequestLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/RingHashLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/WeightedTargetLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/WrrLocalityLoadBalancerProvider.java
xds/src/test/java/io/grpc/xds/LeastRequestLoadBalancerProviderTest.java
xds/src/test/java/io/grpc/xds/MetadataLoadBalancerProvider.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerProviderTest.java

INVALID_ARGUMENT is propagated to the data plane if no previous config
is available. INVALID_ARGUMENT is reserved for application use; LBs
should pretty much use UNAVAILABLE exclusively.
While most of the changes are in xds, there do not appear to be likely
xds code paths that would propagate a bad status to the data plane.
Internal policies either don't use parseLoadBalancingPolicyConfig() and
instead have their configuration objects constructed directly or are
constructed transitively through the cluster manager which uses INTERNAL
if there's a child failure. There was a worrisome hole before this
commit for StatusRuntimeExceptions received by the cluster manager, but
the audit didn't find any locations throwing such an exception.
User-selected policies produce a NACK and are protected …

Service config parse failures should be UNAVAILABLE

---

grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancerProvider.java
interop-testing/src/main/java/io/grpc/testing/integration/RpcBehaviorLoadBalancerProvider.java
rls/src/main/java/io/grpc/rls/RlsLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
xds/src/main/java/io/grpc/xds/CdsLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/LeastRequestLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/RingHashLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/WeightedTargetLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/WrrLocalityLoadBalancerProvider.java
xds/src/test/java/io/grpc/xds/LeastRequestLoadBalancerProviderTest.java
xds/src/test/java/io/grpc/xds/MetadataLoadBalancerProvider.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerProviderTest.java

INVALID_ARGUMENT is propagated to the data plane if no previous config
is available. INVALID_ARGUMENT is reserved for application use; LBs
should pretty much use UNAVAILABLE exclusively.
While most of the changes are in xds, there do not appear to be likely
xds code paths that would propagate a bad status to the data plane.
Internal policies either don't use parseLoadBalancingPolicyConfig() and
instead have their configuration objects constructed directly or are
constructed transitively through the cluster manager which uses INTERNAL
if there's a child failure. There was a worrisome hole before this
commit for StatusRuntimeExceptions received by the cluster manager, but
the audit didn't find any locations throwing such an exception.
User-selected policies produce a NACK and are protected …

Service config parse failures should be UNAVAILABLE (1.48.x backport)

---

xds/src/main/java/io/grpc/xds/Bootstrapper.java
xds/src/main/java/io/grpc/xds/BootstrapperImpl.java
xds/src/main/java/io/grpc/xds/ClientXdsClient.java
xds/src/main/java/io/grpc/xds/XdsLogger.java
xds/src/test/java/io/grpc/xds/BootstrapperImplTest.java
xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
xds/src/test/java/io/grpc/xds/ClientXdsClientV2Test.java
xds/src/test/java/io/grpc/xds/ClientXdsClientV3Test.java

As defined in the gRFC [A53: Option for Ignoring xDS Resource Deletion](https://github.com/grpc/proposal/blob/master/A53-xds-ignore-resource-deletion.md).
Note for the reviewer: it'll probably be more convenient to review commit-by-commit. The test refactoring commit can be skipped: it's not required, but was very handy for implementing new tests, and modifying the old ones.
Backport of #9339

xds: implement ignore_resource_deletion server feature (1.48.x backport)

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpServerBuilder.java

Android linters can't recognize the difference when VisibleForTesting
is used because the method has different visibility, or because
the method only intended for testing.
Because of that linter complains when VisibleForTesting methods are
used in the production code.
Ideally we want to replace or remove this annotation, as its
usage for marking altered visibility for testing purposes is
discouraged since guava v30.0.

okhttp: Comment out VisibleForTesting annotation

---

buildscripts/kokoro/xds.sh

Same as #9347, but for GCE framework too (xds and xds_v3 jobs).
PR #9269 probably pushed the build
b/238334438

xds: Allow Gradle to use more memory when building interop - GCE

---

interop-testing/build.gradle

RuntimeOnly dependencies have been missing since 3624d59. This is
because the implementation configuration extendsFrom the shadow
configuration, so any of the things like runtimeOnly are being lost.
This change isn't "correct" but it stops the bleeding with minimal cost.
It is probably incorrect to be using shadow plugin in interop-testing at
all.

interop-testing: Hack runtimeOnly deps to be available at runtime

---

build.gradle
interop-testing/build.gradle
xds/build.gradle

The two checker tasks run quickly so don't gain much from UP-TO-DATE,
but it is convenient to not see them in the noise (checkUpperBoundDeps
in particular). Gradle only performs UP-TO-DATE checks (on the inputs)
if the task has both inputs and outputs defined.
The biggest saving was for distZip/distTar/shadowDistZip/shadowDistTar
which were using the same name for the non-shadow and shadow versions.
Thus the output file would always be out-of-date because it had been
rewritten and was invalid. This is worrisome because we could have
"randomly" been using the shadow Zip/Tar at times and the non-shadow
ones at others, although I think in practice the shadow tasks always run
last and so those are the files we'd see. Changing the classifier avoids
the colliding file names. These tasks took ~7 …

Fix Gradle UP-TO-DATE checking for all tasks

---

interop-testing/build.gradle

RuntimeOnly dependencies have been missing since 3624d59. This is
because the implementation configuration extendsFrom the shadow
configuration, so any of the things like runtimeOnly are being lost.
This change isn't "correct" but it stops the bleeding with minimal cost.
It is probably incorrect to be using shadow plugin in interop-testing at
all.
CC @YifeiZhuang 
Backport of #9358

interop-testing: Hack runtimeOnly deps to be available at runtime (1.48.x backport)

---

api/src/main/java/io/grpc/GlobalInterceptors.java
gcp-observability/build.gradle
gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java
gcp-observability/src/main/java/io/grpc/gcp/observability/ObservabilityConfig.java
gcp-observability/src/main/java/io/grpc/gcp/observability/ObservabilityConfigImpl.java
gcp-observability/src/test/java/io/grpc/gcp/observability/GcpObservabilityTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/ObservabilityConfigImplTest.java

This PR populates Global Interceptors and Stream Tracers based on observability configuration. 
Also, adds stackdriver exporter required for exporting metric and trace to Google cloud.

gcp-observability: Populate global interceptors from observability

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpProtocolNegotiator.java

This reverts commit c1abc7f8acb46a3c4500e6cf8352222422e8624f. It
produced compilation issues inside Google. I strongly suspect it isn't
this commit or gRPC's fault, but it prevents further testing until it is
resolved.
CC @jader-eero
I'll also be reverting this from the release branch. We have actually had quite a bit of trouble with the import, and we were able to resolve lots of issues semi-quickly, but we had wanted to do builds on Tuesday yet some of the commits still haven't been tested more widely. There's some ugly things to dig into for this one that will simply take too long and we don't want to delay the entire release even further. It seems highly likely there will be a 1.48.1 soon after the 1.48.0 release, so hopefully this change can make it into that.

Revert "Fix for ipv6 link local with scope (#9326)"

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpProtocolNegotiator.java

This reverts commit c1abc7f8acb46a3c4500e6cf8352222422e8624f. It
produced compilation issues inside Google. I strongly suspect it isn't
this commit or gRPC's fault, but it prevents further testing until it is
resolved.
CC @jader-eero
Backport of #9375

Revert "Fix for ipv6 link local with scope (#9326)" (1.48.x backport)

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

Data is getting orphaned sitting in MessageFramer. This hack thus always
flushes data out of the framer so no data can remain sitting there.
See #9340

core: Workaround retry causing memory leak

---

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

Noticed this crash in a couple of c-build failures
cc @ejona86

interop client: fix soak test bug where we can crash if peer wasn't set

---

buildscripts/kokoro/xds_k8s_lb.sh

Secondary cluster was not activated for LB tests. This resulted in the failover test failing, as it relies on workloads running in different zones.

buildscripts: Add missing secondary_kube_context to xds LB tests

---

buildscripts/kokoro/xds_k8s_lb.sh

Reverts grpc/grpc-java#9380
I've noticed that incorrect cluster is selected. I'll revert this change, and redo all in a single PR for easier backports.

Revert "buildscripts: Add missing secondary_kube_context to xds LB tests"

---

buildscripts/kokoro/xds_k8s_lb.sh

buildscripts: Fix kube contexts in the xds LB tests

---

buildscripts/kokoro/xds_k8s_lb.sh

buildscripts: Fix kube contexts in the xds LB tests (1.48.x backport)

---

buildscripts/kokoro/xds_k8s_lb.sh

buildscripts: Fix kube contexts in the xds LB tests (1.46.x backport)

---

buildscripts/kokoro/xds_k8s_lb.sh

buildscripts: Fix kube contexts in the xds LB tests (1.45.x backport)

---

buildscripts/kokoro/xds_k8s_lb.sh

buildscripts: Fix kube contexts in the xds LB tests (1.44.x backport)

---

buildscripts/kokoro/xds_k8s_lb.sh

buildscripts: Fix kube contexts in the xds LB tests (1.43.x backport)

---

buildscripts/kokoro/xds_k8s_lb.sh

buildscripts: Fix kube contexts in the xds LB tests (1.41.x backport)

---

buildscripts/kokoro/xds_k8s_lb.sh

buildscripts: Fix kube contexts in the xds LB tests (1.40.x backport)

---

core/src/main/java/io/grpc/inprocess/InProcessTransport.java
core/src/main/java/io/grpc/internal/AbstractClientStream.java
core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/main/java/io/grpc/internal/DelayedClientCall.java
core/src/main/java/io/grpc/internal/JsonUtil.java
core/src/main/java/io/grpc/internal/MessageDeframer.java
core/src/main/java/io/grpc/internal/MessageFramer.java
core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java
core/src/test/java/io/grpc/internal/MessageDeframerTest.java
core/src/test/java/io/grpc/internal/MessageFramerTest.java
gae-interop-testing/gae-jdk8/src/main/java/io/grpc/testing/integration/NettyClientInteropServlet.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/main/java/io/grpc/testing/integration/StressTestClient.java
interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/Headers.java
okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/framed/Http2.java
testing/src/main/java/io/grpc/internal/testing/TestStreamTracer.java
xds/src/main/java/io/grpc/xds/ClientXdsClient.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/main/java/io/grpc/xds/FaultFilter.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerProviderTest.java

%s is fairly safe (requires a Formattable to use Locale), so %d is the
main risk item. Places that really didn't need to use String.format()
were converted to plain string concatenation. Logging locations were
generally converted to using the log infrastructure's delayed
formatting, which is generally locale-sensitive but we're okay with
that. That wasn't done in okhttp, however, because Android frequently
doesn't use MessageFormat so we'd lose the parameters. Everywhere else
was explicitly defined to be Locale.US, to be consistent independent of
the default system locale.

Avoid accidental locale-sensitive String.format()

---

buildscripts/kokoro/xds_k8s_lb.sh

buildscripts: Fix kube contexts in the xds LB tests (1.42.x backport)

---

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
rls/src/main/java/io/grpc/rls/LbPolicyConfiguration.java
rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java
rls/src/test/java/io/grpc/rls/LbPolicyConfigurationTest.java

Pick the first target that is in a good state (READY or IDLE).  If none, then pick the first target in CONNECTING state.  If none, use the first target.
Fixes #9236

rls: Support multiple returned targets from RLS Server

---

rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java

When RLS returns a value, even when there are no okay subchannels, still return the value from the picker.  Only fallback to the default target when RLS can't communicate.
Fixes #9237

rls: Only use subchannel policy for default target when RLS is not available

---

core/src/main/java/io/grpc/inprocess/InProcessChannelBuilder.java

  core: Disable retry by default for in-process transport's channel (1.48.x backport)

---

rls/src/main/java/io/grpc/rls/AdaptiveThrottler.java
rls/src/test/java/io/grpc/rls/AdaptiveThrottlerTest.java

Ticker is based on System.nanoTime, so isn't affected by updates to the system clock like TimeProvider is.
Fixes #9048

rls: Change AdaptiveThrottler to use Ticker instead of TimeProvider

---

xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterManagerLoadBalancerTest.java

Correctly set the currentState and curentPicker when the
child LB updates balancing state

xds: ClusterManager LB state/picker update fix

---

xds/src/main/java/io/grpc/xds/PriorityLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java

this makes it easy to search and correlate

xds: use predefined XdsLbPolicies constants instead of string literals for consistency

---

gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java

CC @DNVindhya to provide context/background of this task to the reviewer(s)

gcp-observability: add custom tags to metrics and traces using Stackdriver config-builders

---

istio-interop-testing/build.gradle
istio-interop-testing/src/main/java/io/grpc/testing/istio/EchoTestServer.java
istio-interop-testing/src/test/java/io/grpc/testing/istio/EchoTestServerTest.java

- when we receive the forwardEchoRequest for non-grpc protocol just "forward" it to the forwarding-address which is the Go echo server
Similar to the C++ one in https://github.com/grpc/grpc/pull/30005

istio-interop-testing: add logic to forward non-grpc requests to the Go echo server

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

Data is getting orphaned sitting in MessageFramer. This hack thus always
flushes data out of the framer so no data can remain sitting there.
See #9340
Backport of #9360

core: Workaround retry causing memory leak (1.48.x backport)

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

Data is getting orphaned sitting in MessageFramer. This hack thus always
flushes data out of the framer so no data can remain sitting there.
See #9340
Backport of #9360

core: Workaround retry causing memory leak (1.47.x backport)

---

buildscripts/kokoro/unix.sh
examples/example-orca/src/main/java/io/grpc/examples/orca/CustomBackendMetricsLoadBalancerProvider.java
examples/example-orca/src/main/java/io/grpc/examples/orca/CustomBackendMetricsServer.java
interop-testing/src/main/java/io/grpc/testing/integration/CustomBackendMetricsLoadBalancerProvider.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceImpl.java
services/BUILD.bazel
services/src/main/java/io/grpc/services/CallMetricRecorder.java
services/src/main/java/io/grpc/services/InternalCallMetricRecorder.java
services/src/main/java/io/grpc/services/InternalMetricRecorder.java
services/src/main/java/io/grpc/services/MetricRecorder.java
services/src/main/java/io/grpc/services/MetricReport.java
services/src/test/java/io/grpc/services/CallMetricRecorderTest.java
xds/src/main/java/io/grpc/xds/orca/OrcaMetricReportingServerInterceptor.java
xds/src/main/java/io/grpc/xds/orca/OrcaOobUtil.java
xds/src/main/java/io/grpc/xds/orca/OrcaPerRequestUtil.java
xds/src/main/java/io/grpc/xds/orca/OrcaServiceImpl.java
xds/src/test/java/io/grpc/xds/orca/OrcaMetricReportingServerInterceptorTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaOobUtilTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaPerRequestUtilTest.java

The fix avoids shaded dependency of orca protos
backport of #9366 #9382 #9403 #9410 #9411

xds: do not expose orca proto in ORCA api (#9366) (v1.48 backport)

---

core/src/main/java/io/grpc/internal/AbstractServerStream.java
core/src/test/java/io/grpc/internal/AbstractServerStreamTest.java

Fix a bug where the server stream delivers halfClose() to the call during cancellation. It happens when call has a short deadline. Server sees `INTERNAL, desc: Half-closed without a request` due to the bug.
backport of #9362

core: server stream should not deliver halfClose() when call is immediately cancelled(#9362) (v1.48 backport)

---

repositories.bzl
xds/BUILD.bazel

This fixes builds including dependencies from Maven that use
io.grpc:grpc-services. It resolves this error:
```
no such target '@io_grpc_grpc_java//services:services': target 'services' not declared in package 'services' defined by services/BUILD.bazel and referenced by '@maven//:io_grpc_grpc_services'
```
Fixes #9419
CC @xushaoxiao

repositories.bzl: Use valid target name for grpc-services

---

repositories.bzl
xds/BUILD.bazel

This fixes builds including dependencies from Maven that use
io.grpc:grpc-services. It resolves this error:
```
no such target '@io_grpc_grpc_java//services:services': target 'services' not declared in package 'services' defined by services/BUILD.bazel and referenced by '@maven//:io_grpc_grpc_services'
```
Fixes #9419
CC @xushaoxiao
Backport of #9422

repositories.bzl: Use valid target name for grpc-services (1.48.x backport)

---

api/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/util/ForwardingLoadBalancerHelper.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java

It's been 17 months since the check was introduced, which is plenty for
the migration. Leaving ignoreRefreshNameResolutionCheck() in-place to
let users delete their call sites. We'll remove the method after a few
releases.
Fixes #9409

core: Remove LB refreshNameResolver check

---

gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java
gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/ConditionalClientInterceptor.java
gcp-observability/src/main/java/io/grpc/gcp/observability/logging/GcpLogSink.java
gcp-observability/src/test/java/io/grpc/gcp/observability/GcpObservabilityTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/LoggingTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/ConditionalClientInterceptorTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/logging/GcpLogSinkTest.java

by using a ConditionalClientInterceptor that conditionally delegates
CC @DNVindhya

gcp-observability: implement exclusion of cloud backend RPCs for all 3 signals

---

gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java
gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/ConditionalClientInterceptor.java
gcp-observability/src/main/java/io/grpc/gcp/observability/logging/GcpLogSink.java
gcp-observability/src/test/java/io/grpc/gcp/observability/GcpObservabilityTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/LoggingTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/ConditionalClientInterceptorTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/logging/GcpLogSinkTest.java

* gcp-observability: implement exclusion of cloud backend RPCs for all 3 signals
by using a ConditionalClientInterceptor that conditionally delegates

gcp-observability: implement exclusion of cloud backend RPCs for all 3 signals (backport to v1.49.x) (#9427)

---

api/src/main/java/io/grpc/LoadBalancer.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/util/ForwardingLoadBalancerHelper.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java

It's been 17 months since the check was introduced, which is plenty for
the migration. Leaving ignoreRefreshNameResolutionCheck() in-place to
let users delete their call sites. We'll remove the method after a few
releases.
Fixes #9409
Backport of #9429

core: Remove LB refreshNameResolver check (1.49.x backport)

---

auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java

[ServiceAccountCredentials](https://github.com/googleapis/google-auth-library-java/blob/7f2c535ab7c842a672d6761f4cd80df88e1a37ed/oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java) is converted to [ServiceAccountJwtAccessCredentials](https://github.com/googleapis/google-auth-library-java/blob/7f2c535ab7c842a672d6761f4cd80df88e1a37ed/oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java) if no scopes have been specified. 
During this conversion, a [set of values](https://github.com/grpc/grpc-java/blob/7bdca0c0efa7a77587738cd6556b9f5d6f9c640e/auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java?ln=297#L297) are copied over. Quotaprojectid is not part of the list. Adding it so that if user species `quota-project-id`, we set the …

fix: Copy quota project id when creating Self Signed JWT creds from Service Account Creds

---

auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java

[ServiceAccountCredentials](https://github.com/googleapis/google-auth-library-java/blob/7f2c535ab7c842a672d6761f4cd80df88e1a37ed/oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java) is converted to [ServiceAccountJwtAccessCredentials](https://github.com/googleapis/google-auth-library-java/blob/7f2c535ab7c842a672d6761f4cd80df88e1a37ed/oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java) if no scopes have been specified. 
During this conversion, a [set of values](https://github.com/grpc/grpc-java/blob/7bdca0c0efa7a77587738cd6556b9f5d6f9c640e/auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java?ln=297#L297) are copied over. Quotaprojectid is not part of the list. Adding it so that if user species `quota-project-id`, we set the …

fix: Copy quota project id when creating Self Signed JWT creds from Service Account Creds (1.47.x backport)

---

auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java

[ServiceAccountCredentials](https://github.com/googleapis/google-auth-library-java/blob/7f2c535ab7c842a672d6761f4cd80df88e1a37ed/oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java) is converted to [ServiceAccountJwtAccessCredentials](https://github.com/googleapis/google-auth-library-java/blob/7f2c535ab7c842a672d6761f4cd80df88e1a37ed/oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java) if no scopes have been specified. 
During this conversion, a [set of values](https://github.com/grpc/grpc-java/blob/7bdca0c0efa7a77587738cd6556b9f5d6f9c640e/auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java?ln=297#L297) are copied over. Quotaprojectid is not part of the list. Adding it so that if user species `quota-project-id`, we set the …

fix: Copy quota project id when creating Self Signed JWT creds from Service Account Creds (1.48.x backport)

---

auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
auth/src/test/java/io/grpc/auth/GoogleAuthLibraryCallCredentialsTest.java

[ServiceAccountCredentials](https://github.com/googleapis/google-auth-library-java/blob/7f2c535ab7c842a672d6761f4cd80df88e1a37ed/oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java) is converted to [ServiceAccountJwtAccessCredentials](https://github.com/googleapis/google-auth-library-java/blob/7f2c535ab7c842a672d6761f4cd80df88e1a37ed/oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java) if no scopes have been specified. 
During this conversion, a [set of values](https://github.com/grpc/grpc-java/blob/7bdca0c0efa7a77587738cd6556b9f5d6f9c640e/auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java?ln=297#L297) are copied over. Quotaprojectid is not part of the list. Adding it so that if user species `quota-project-id`, we set the …

fix: Copy quota project id when creating Self Signed JWT creds from Service Account Creds (1.49.x backport)

---

gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java
gcp-observability/src/main/java/io/grpc/gcp/observability/logging/GcpLogSink.java

This PR removes unregistering `Stackdriver<Stats/Trace>Exporter` because `unregister` shutdowns the channel even before creating metric descriptors causing `RunTimeException`.
Added a null check for `sourceProjectId` for non-GCP instances.

gcp-observability: remove unregistering stackdriverexporter

---

gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java
gcp-observability/src/main/java/io/grpc/gcp/observability/logging/GcpLogSink.java

This PR removes unregistering Stackdriver<Stats/Trace>Exporter because unregister shutdowns the channel even before creating metric descriptors causing RunTimeException.
Added a null check for sourceProjectId for non-GCP instances.
Backport of #9442 

gcp-observability: remove unregistering stackdriverexporter (1.49.x backport)

---

api/src/main/java/io/grpc/SynchronizationContext.java
api/src/test/java/io/grpc/LoadBalancerRegistryTest.java
core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancerProvider.java
core/src/main/resources/META-INF/services/io.grpc.LoadBalancerProvider
core/src/test/java/io/grpc/internal/FakeClock.java
core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerProviderTest.java
core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

Implements a new load balancer that tracks all RPC results to the addresses it is configured with and periodically attempts to detect outlier. It wraps a child load balancer that it hides any addresses that are deemed outliers.
Implementation follows the specification in [gRFC A50: gRPC xDS Outlier Detection Support](https://github.com/grpc/proposal/blob/master/A50-xds-outlier-detection.md)

Outlier detection load balancer

---

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
xds/src/main/java/io/grpc/xds/ClientXdsClient.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/EnvoyServerProtoData.java
xds/src/main/java/io/grpc/xds/XdsClient.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
xds/src/test/java/io/grpc/xds/ClientXdsClientV2Test.java
xds/src/test/java/io/grpc/xds/ClientXdsClientV3Test.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java

Enables the new `OutlierDetectionLoadBalancer` when outlier detection is enabled
in the xDS cluster configuration.

xds: Configure outlier detection.

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

The log id is an incrementing value starting from 0. That means the same
binary on two different machines will have the same hashes for each
consecutive Channel. That was not at all the intension of CHANNEL_ID.
From gRFC A42:
> This can be used in similar situations to where Envoy uses
> connection_properties to hash on the source IP address.
CC @apolcyn

xds: CHANNEL_ID hash should be random for the channel

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

The log id is an incrementing value starting from 0. That means the same
binary on two different machines will have the same hashes for each
consecutive Channel. That was not at all the intension of CHANNEL_ID.
From gRFC A42:
> This can be used in similar situations to where Envoy uses
> connection_properties to hash on the source IP address.
CC @apolcyn 
Backport of #9453

xds: CHANNEL_ID hash should be random for the channel (1.49.x backport)

---

xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

The log id is an incrementing value starting from 0. That means the same
binary on two different machines will have the same hashes for each
consecutive Channel. That was not at all the intension of CHANNEL_ID.
From gRFC A42:
> This can be used in similar situations to where Envoy uses
> connection_properties to hash on the source IP address.
CC @apolcyn 
Backport of #9453

xds: CHANNEL_ID hash should be random for the channel (1.48.x backport)

---

interop-testing/src/main/java/io/grpc/testing/integration/RpcBehaviorLoadBalancerProvider.java
rls/src/main/java/io/grpc/rls/AdaptiveThrottler.java
rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
rls/src/main/java/io/grpc/rls/LinkedHashLruCache.java
rls/src/main/java/io/grpc/rls/RlsProtoConverters.java
rls/src/main/java/io/grpc/rls/RlsRequestFactory.java

rls: Update implementation to match spec.
- Cleanup cache if exceeds max size when add an entry.  Make cache entry size calculations more accurate
- Trigger pending RPC processing if unexpired backoff entries were removed from the cache by triggering helper to call it's parent updateBalancingState with the same state and picker
- Introduce minimum time before eviction (5 seconds)
- Change default accept ratio for AdaptiveThrottler from 1.2 -> 2.0
- Configuration validation
- When checking key names for duplicates also look at headers
- Check extra keys for duplicates
See analysis of implementation versus spec at https://docs.google.com/spreadsheets/d/18w5s1TEebRumWzk1pvWnjiHFGKc6MW-vt8tRLY4eNs0/

Rls spec sync

---

googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdExperimentalNameResolverProvider.java
googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolverProvider.java
googleapis/src/main/resources/META-INF/services/io.grpc.NameResolverProvider
googleapis/src/test/java/io/grpc/googleapis/GoogleCloudToProdNameResolverProviderTest.java

Preserve google-c2p-experimental support for the moment to ease testing
migration.

googleapis: Stabilize google-c2p resolver

---

gcp-observability/src/main/java/io/grpc/gcp/observability/ObservabilityConfigImpl.java
gcp-observability/src/test/java/io/grpc/gcp/observability/ObservabilityConfigImplTest.java

This PR updates config variable to enable tracing in observability from `enable_cloud_tracing` to `enable_cloud_trace` as mentioned in User Guide.
Backport of #9463

gcp-observability: update configuration variable to enable cloud tracing (1.49.x backport) 

---

googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdExperimentalNameResolverProvider.java
googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolverProvider.java
googleapis/src/main/resources/META-INF/services/io.grpc.NameResolverProvider
googleapis/src/test/java/io/grpc/googleapis/GoogleCloudToProdNameResolverProviderTest.java

Preserve google-c2p-experimental support for the moment to ease testing
migration.
Backport of #8970
CC @apolcyn

googleapis: Stabilize google-c2p resolver (1.49.x backport)

---

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

The outlier detection config was incorrectly being passed to the wrapped child LB.
This PR has the outlier detection LB correctly extract the child LB config from the
outlier detection config and pass that to the child LB.

core: OutlierDetectionLoadBalancer to pass child LB config.

---

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java

Tracking can't be started when a subchannel is created as the addresses
are not known at that point. Delay the start of tracking until the
subchannel has started and goes into the READY state.

core: Delay start of outlier detection tracking

---

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

Only mark a subchannel ejected after delegating the UNAVAILABLE status
to the wrapped subchannel.

core: outlier detection - delay subchannel ejection

---

api/src/main/java/io/grpc/SynchronizationContext.java
api/src/test/java/io/grpc/LoadBalancerRegistryTest.java
core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancerProvider.java
core/src/main/resources/META-INF/services/io.grpc.LoadBalancerProvider
core/src/test/java/io/grpc/internal/FakeClock.java
core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerProviderTest.java
core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

Backport of #9447
Implements a new load balancer that tracks all RPC results to the addresses it is configured with and periodically attempts to detect outlier. It wraps a child load balancer that it hides any addresses that are deemed outliers.
Implementation follows the specification in [gRFC A50: gRPC xDS Outlier Detection Support](https://github.com/grpc/proposal/blob/master/A50-xds-outlier-detection.md)

Outlier detection load balancer (1.49.x backport)

---

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
xds/src/main/java/io/grpc/xds/ClientXdsClient.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/EnvoyServerProtoData.java
xds/src/main/java/io/grpc/xds/XdsClient.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
xds/src/test/java/io/grpc/xds/ClientXdsClientTestBase.java
xds/src/test/java/io/grpc/xds/ClientXdsClientV2Test.java
xds/src/test/java/io/grpc/xds/ClientXdsClientV3Test.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java

Backport of #9456
Enables the new `OutlierDetectionLoadBalancer` when outlier detection is enabled
in the xDS cluster configuration.

xds: Configure outlier detection. (1.49.x backport)

---

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

Backport of #9467
The outlier detection config was incorrectly being passed to the wrapped child LB.
This PR has the outlier detection LB correctly extract the child LB config from the
outlier detection config and pass that to the child LB.

core: OutlierDetectionLoadBalancer to pass child LB config. (1.49.x backport)

---

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

Backport of #9469
Only mark a subchannel ejected after delegating the UNAVAILABLE status
to the wrapped subchannel.

core: outlier detection - delay subchannel ejection (1.49.x backport)

---

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java

Backport of #9468
Tracking can't be started when a subchannel is created as the addresses
are not known at that point. Delay the start of tracking until the
subchannel has started and goes into the READY state.

core: Delay start of outlier detection tracking (1.49.x backport)

---

buildscripts/kokoro/xds_k8s_lb.sh

buildscripts: Enable outlier detection kokoro test. (1.49.x backport)

---

examples/android/helloworld/app/src/main/AndroidManifest.xml

Add android:exported="true" tag to activities/services/receivers that specify an intent filter.
Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. Future versions of the manifest merger, as well as the Android platform and the Playstore enforce this.
ref cl/469539970

example-android: Add android:exported="true" tag

---

context/src/test/java/io/grpc/ContextTest.java

JDK-8210522 changes the behaviour of Java reflection to filter out
security-sensitive fields in the java.lang.reflect.Field. This
prohibits Field.class.getDeclaredFields("modifiers") call we rely on
in this test. Until we have a good solution for setting a custom
storage for testing purposes, we'll have to skip this test
for JDK >= 11. Ref https://bugs.openjdk.org/browse/JDK-8210522

context: Skip storageReturnsNullTest for JDK >= 11

---

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

Stop further ejection if the ejection percentage is lesser than or equal
to the maximum ejection percentage. Previously this was only done when
the current ejection percentage was lesser than the maximum.

core: outlier detection max ejection logic update

---

census/src/main/java/io/grpc/census/CensusTracingModule.java
census/src/main/java/io/grpc/census/InternalCensusTracingAccessor.java
census/src/test/java/io/grpc/census/CensusModulesTest.java
census/src/test/java/io/grpc/census/CensusTracingNoMessageEventTest.java
gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java

census: provide a flag `addMessageEvents` for the client/server tracers to conditionally emit message events
observability: call the tracers with addMessageEvents set to false

census,observability: suppress message-events in traces when used by observability

---

core/src/main/java/io/grpc/internal/DelayedClientCall.java
core/src/test/java/io/grpc/internal/DelayedClientCallTest.java

This was already being done for the Listener, but it was missed for the
ClientCall draining itself. That's not too surprising, since very few
things should be looking at the context in that path. We don't care too
much about this client call case, but if the context _does_ end up
mattering it could be painful to debug.
Fixes #9478

core: DelayedClientCall should propagate context

---

api/src/main/java/io/grpc/LoadBalancer.java
api/src/test/java/io/grpc/LoadBalancerTest.java
core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/util/ForwardingLoadBalancer.java
core/src/test/java/io/grpc/internal/AutoConfiguredLoadBalancerFactoryTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/ServiceConfigErrorHandlingTest.java
rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java

Introduces a new acceptResolvedAddresses() method in LoadBalancer that
is to ultimately replace the existing handleResolvedAddresses(). The new
method allows the LoadBalancer implementation to reject the given
addresses by returning false from the method.
The long deprecated handleResolvedAddressGroups is also removed.

api,core: Add LoadBalancer.acceptResolvedAddresses()

---

api/src/main/java/io/grpc/InternalStatus.java
core/src/main/java/io/grpc/internal/ServerCallImpl.java
core/src/main/java/io/grpc/internal/ServerImpl.java
core/src/test/java/io/grpc/internal/ServerCallImplTest.java
core/src/test/java/io/grpc/internal/ServerImplTest.java

Makes sure that whenever a context is in a cancelled state, we also have
a cancellationCause.

core: Assure that context cancellationCause set

---

api/src/main/java/io/grpc/InternalMayRequireSpecificExecutor.java
auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
core/src/main/java/io/grpc/internal/CallCredentialsApplyingTransportFactory.java

[core,api,auth: Choose the callOptions executor when applying request metadata to credentials during newStream based upon whether AppEngineCredentials are being used as they require a specific thread to do the processing.
Add an interface to differentiate whether the specific thread is needed.
Fixes b/244209681

[core,api,auth: Choose executor based on need for thread affinity

---

buildscripts/kokoro/psm-security.cfg
buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.cfg
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.cfg
buildscripts/kokoro/xds_url_map.sh

xDS interop: enable pod log collection in the buildscripts

---

core/src/main/java/io/grpc/util/ForwardingLoadBalancer.java
core/src/test/java/io/grpc/util/ForwardingLoadBalancerTest.java

Forwarding acceptResolvedAddresses() to a delegate in ForwardingLoadBalancer can cause problems if an extending class expects its handleResolvedAddresses implementation to be called even when a client calls handleResolvedAddresses(). This would not happen as ForwardingLoadBalancer would directly send the call to the delegate.

core: Don't forward acceptResolvedAddresses()

---

buildscripts/kokoro/psm-security.cfg
buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.cfg
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.cfg
buildscripts/kokoro/xds_url_map.sh

xDS interop: enable pod log collection in the buildscripts (v1.47.x backport)

---

buildscripts/kokoro/psm-security.cfg
buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.cfg
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.cfg
buildscripts/kokoro/xds_url_map.sh

xDS interop: enable pod log collection in the buildscripts (v1.44.x backport)

---

buildscripts/kokoro/psm-security.cfg
buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.cfg
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.cfg
buildscripts/kokoro/xds_url_map.sh

xDS interop: enable pod log collection in the buildscripts (v1.49.x backport)

---

buildscripts/kokoro/psm-security.cfg
buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.cfg
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.cfg
buildscripts/kokoro/xds_url_map.sh

xDS interop: enable pod log collection in the buildscripts (v1.43.x backport)

---

buildscripts/kokoro/psm-security.cfg
buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.cfg
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.cfg
buildscripts/kokoro/xds_url_map.sh

xDS interop: enable pod log collection in the buildscripts (v1.41.x backport)

---

buildscripts/kokoro/psm-security.cfg
buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.cfg
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.cfg
buildscripts/kokoro/xds_url_map.sh

xDS interop: enable pod log collection in the buildscripts (v1.45.x backport)

---

buildscripts/kokoro/psm-security.cfg
buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.cfg
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.cfg
buildscripts/kokoro/xds_url_map.sh

xDS interop: enable pod log collection in the buildscripts (v1.46.x backport)

---

buildscripts/kokoro/psm-security.cfg
buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.cfg
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.cfg
buildscripts/kokoro/xds_url_map.sh

xDS interop: enable pod log collection in the buildscripts (v1.40.x backport)

---

buildscripts/kokoro/psm-security.cfg
buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.cfg
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.cfg
buildscripts/kokoro/xds_url_map.sh

xDS interop: enable pod log collection in the buildscripts (v1.42.x backport)

---

buildscripts/kokoro/psm-security.cfg
buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.cfg
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.cfg
buildscripts/kokoro/xds_url_map.sh

xDS interop: enable pod log collection in the buildscripts (v1.48.x backport)

---

binder/build.gradle
binder/src/main/java/io/grpc/binder/SecurityPolicies.java
binder/src/test/java/io/grpc/binder/SecurityPoliciesTest.java

Add security policies for checking device owner/profile owner.

Add security policies for checking device owner/profile owner.

---

core/src/test/java/io/grpc/internal/ForwardingReadableBufferTest.java

My motivation for making this change is that [`ByteBuffer` is becoming
`sealed`](https://download.java.net/java/early_access/loom/docs/api/java.base/java/nio/ByteBuffer.html)
in new versions of Java. This makes it impossible for Mockito's
_current_ default mockmaker to mock it.
That said, Mockito will likely [switch its default
mockmaker](https://github.com/mockito/mockito/issues/2589) to an
alternative that _is_ able to mock `sealed` classes. However, there are
downside to that, such as [slower
performance](https://github.com/mockito/mockito/issues/2589#issuecomment-1192725206),
so it's probably better to leave our options open by avoiding mocking at
all.
And in this case, it's equally easy to use real objects.
As a bonus, I think that real objects makes the code a little easier to …

Use real objects instead of mocks.

---

xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java

Removes the option of skipping the update of the priority LB state when the failover timer is pending.

xds: always update priority LB connectivity state

---

xds/src/main/java/io/grpc/xds/FilterChainMatchingProtocolNegotiators.java
xds/src/main/java/io/grpc/xds/XdsChannelCredentials.java
xds/src/main/java/io/grpc/xds/XdsServerCredentials.java
xds/src/main/java/io/grpc/xds/internal/certprovider/CertProviderClientSslContextProvider.java
xds/src/main/java/io/grpc/xds/internal/certprovider/CertProviderServerSslContextProvider.java
xds/src/main/java/io/grpc/xds/internal/sds/SecurityProtocolNegotiators.java
xds/src/main/java/io/grpc/xds/internal/sds/SslContextProvider.java
xds/src/main/java/io/grpc/xds/internal/sds/SslContextProviderSupplier.java
xds/src/main/java/io/grpc/xds/internal/sds/trust/XdsTrustManagerFactory.java
xds/src/main/java/io/grpc/xds/internal/sds/trust/XdsX509TrustManager.java
xds/src/test/java/io/grpc/xds/FilterChainMatchingProtocolNegotiatorsTest.java
xds/src/test/java/io/grpc/xds/XdsClientWrapperForServerSdsTestMisc.java
xds/src/test/java/io/grpc/xds/internal/sds/SecurityProtocolNegotiatorsTest.java
xds/src/test/java/io/grpc/xds/internal/sds/trust/XdsTrustManagerFactoryTest.java
xds/src/test/java/io/grpc/xds/internal/sds/trust/XdsX509TrustManagerTest.java

xds: rename Sds to Security or Xds in various classes to eliminate references to SDS

---

binder/src/test/java/io/grpc/binder/SecurityPoliciesTest.java

The test name includes "fails" but it asserts the result is OK. The test was added in #9428.
The binder tests are passing on the Android CI, but for some reason the tests with sdk >= 29 are skipped. Robolectric 4.8 claims API level 32 support and the tests are skipped even when using Java 11 and 17.
CC @prateek-0

binder: Fix expected result of security test

---

core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/test/java/io/grpc/internal/GrpcUtilTest.java

Certain status codes are inappropriate for a control plane to be returning and indicate a bug in the control plane. These status codes will be replaced by INTERNAL, to make it clearer to see that the control plane is misbehaving.
https://github.com/grpc/proposal/blob/master/A54-restrict-control-plane-status-codes.md

core: Replace inappropriate picker result status codes

---

census/src/main/java/io/grpc/census/CensusStatsModule.java
census/src/main/java/io/grpc/census/internal/DeprecatedCensusConstants.java
census/src/test/java/io/grpc/census/CensusModulesTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java

Many of the deprecated constants are just aliases for non-deprecated constants, so just swap which one we use.

census: Avoid deprecated measure constants

---

api/src/main/java/io/grpc/InternalMayRequireSpecificExecutor.java
auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
core/src/main/java/io/grpc/internal/CallCredentialsApplyingTransportFactory.java

Backport #9504 
* core,api,auth: Choose the callOptions executor when applying request metadata to credentials during newStream based upon whether AppEngineCredentials are being used as they require a specific thread to do the processing.
Add an interface to differentiate whether the specific thread is needed.
Fixes b/244209681

Backport #9504 [core,api,auth: Choose executor based on need for thread affinity

---

xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java

If a child policy triggers an update to the parent priority policy
it will be ignored if an update is already in process.

xds: prevent concurrent priority LB picker updates

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ConfigSelectingClientCallTest.java

In case a control plane returns an "inappropriate" response code, it is converted to INTERNAL to highlight the bug in the control plane.
https://github.com/grpc/proposal/blob/master/A54-restrict-control-plane-status-codes.md

core: Don't delegate inappropriate ConfigSelector errors

---

core/src/main/java/io/grpc/internal/MetadataApplierImpl.java
core/src/test/java/io/grpc/internal/CallCredentialsApplyingTest.java

If a CallCredentials implementation returns an error that is not appropriate to propagate from the control plane to the data plane, we convert it to an INTERNAL error. This makes the inappropriate control plane behavior to be discoverable in the logs.
https://github.com/grpc/proposal/blob/master/A54-restrict-control-plane-status-codes.md

core: Convert inappropriate call cred errors

---

xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java

xds: ringhash policy in TRANSIENT_FAILURE should not attempt connecting when already in connecting (#9535) (1.49 backport))

---

okhttp/src/main/java/io/grpc/okhttp/OutboundFlowController.java

When allocating bytes to streams within a flow control window we always go through the streams in the same order. This can lead to large streams hogging all the bytes and a smaller one down the list getting starved out. This change randomizes the start location to lower the chance of this happening.
Fixes #9089

okhttp: Fair treatment when writing out streams

---

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

Backport of #9489
Instead of strictly enforcing the max ejection percentage setting,
allow one additional ejection past the maximum. This quarantees at least
one ejection and matches Envoy proxy behavior

core: Update outlier detection max ejection logic. (1.49.x backport)

---

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

Backport of #9490
When doing the failure percentage algorithm, ejections should be skipped
if there are not enough addresses that meet the minimum volume
requirement

core: outlier detection to honor min host request volume (1.49.x backport)

---

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

Backport of #9492
Stop further ejection if the ejection percentage is lesser than or equal
to the maximum ejection percentage. Previously this was only done when
the current ejection percentage was lesser than the maximum

core: outlier detection max ejection logic update (1.49.x backport)

---

xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java

This reverts commit bcf5cde7dd31de4be3cfc8bf8264681abc8fb292.
Seems to break some tests internally - b/247115476
cc @temawi @ejona86

Revert "xds: prevent concurrent priority LB picker updates (#9363)"

---

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

Switch OutlierDetectionLoadBalancer to implement
acceptResolvedAddresses() to allow for the evential deprecation of handleResolvedAddresses().

core: outlier_detection LB to use acceptResolvedAddresses()

---

xds/src/main/java/io/grpc/xds/ClientXdsClient.java

This fixes a regression in commit e1ad984. I'd create a test, but the NPE gets thrown away in the context of the current test setup so can't be created as quickly as we'd like to fix this. I have manually tested in a custom reproduction to confirm it resolves the NPE.
Seen at b/248326695
```
java.lang.AssertionError: java.lang.NullPointerException
at io.grpc.xds.ClientXdsClient$1.uncaughtException(ClientXdsClient.java:89)
at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:97)
at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
at io.grpc.xds.ClientXdsClient.cancelXdsResourceWatch(ClientXdsClient.java:327)
at io.grpc.xds.ClusterResolverLoadBalancer$ClusterResolverLbState$EdsClusterState.shutdown(ClusterResolverLoadBalancer.java:378)
at …
```

xds: Avoid NPE from update after removing subscriptions

---

rls/src/main/java/io/grpc/rls/RlsLoadBalancer.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java

Switch over from handleResolvedAddresses as part of a LoadBalancer public API refactoring.

rls: use acceptResolvedAddresses()

---

googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolver.java

To properly use xds federation when the env var is set.
C++ PR: https://github.com/grpc/grpc/pull/29732
cc @ejona86

google-c2p resolver: add authority entry to bootstrap config

---

rls/src/main/java/io/grpc/rls/RlsLoadBalancer.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java

This reverts commit 3b62fbe3657097e2191b918619c5bed4fd23bfcc from https://github.com/grpc/grpc-java/pull/9569
Seems to cause internal test failures - see b/250700340
cc @ejona86 @temawi

Revert "rls: use acceptResolvedAddresses() (#9569)"

---

buildscripts/make_dependencies.bat
buildscripts/make_dependencies.sh

This aligns the C++ version we're using for gRPC-generated code with the Java version. This should have no real impact to our users, as there were no features added to .proto files or the like that would be visible to users.

Use Protobuf 21.7 is our code generator

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

Not having a timeout when reading the response from a proxy server can cause a hang if network connectivity is lost at the same time.

okhttp: Add client transport proxy socket timeout

---

COMPILING.md
README.md
build.gradle
buildscripts/make_dependencies.bat
buildscripts/make_dependencies.sh
examples/android/clientcache/app/build.gradle
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/strictmode/app/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-hostname/build.gradle
examples/example-hostname/pom.xml
examples/example-jwt-auth/build.gradle
examples/example-jwt-auth/pom.xml
examples/example-orca/build.gradle
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/example-xds/build.gradle
examples/pom.xml
gcp-observability/build.gradle
repositories.bzl

Bump protobuf to 3.19.6 (v1.47.x)

---

COMPILING.md
README.md
build.gradle
buildscripts/make_dependencies.bat
buildscripts/make_dependencies.sh
examples/android/clientcache/app/build.gradle
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/strictmode/app/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-hostname/build.gradle
examples/example-hostname/pom.xml
examples/example-jwt-auth/build.gradle
examples/example-jwt-auth/pom.xml
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/example-xds/build.gradle
examples/pom.xml
repositories.bzl

Bump protobuf to 3.19.6 (v1.47.x) (1.43.x backport)

---

COMPILING.md
README.md
build.gradle
buildscripts/make_dependencies.bat
buildscripts/make_dependencies.sh
examples/android/clientcache/app/build.gradle
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/strictmode/app/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-hostname/build.gradle
examples/example-hostname/pom.xml
examples/example-jwt-auth/build.gradle
examples/example-jwt-auth/pom.xml
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/example-xds/build.gradle
examples/pom.xml
gcp-observability/build.gradle
repositories.bzl

Bump protobuf to 3.19.6 (v1.47.x) (1.46.x backport)

---

COMPILING.md
README.md
build.gradle
buildscripts/make_dependencies.bat
buildscripts/make_dependencies.sh
examples/android/clientcache/app/build.gradle
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/strictmode/app/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-hostname/build.gradle
examples/example-hostname/pom.xml
examples/example-jwt-auth/build.gradle
examples/example-jwt-auth/pom.xml
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/example-xds/build.gradle
examples/pom.xml
observability/build.gradle
repositories.bzl

Bump protobuf to 3.19.6 (v1.47.x) (1.45.x backport)

---

COMPILING.md
README.md
build.gradle
buildscripts/make_dependencies.bat
buildscripts/make_dependencies.sh
examples/android/clientcache/app/build.gradle
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/strictmode/app/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-hostname/build.gradle
examples/example-hostname/pom.xml
examples/example-jwt-auth/build.gradle
examples/example-jwt-auth/pom.xml
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/example-xds/build.gradle
examples/pom.xml
repositories.bzl

Bump protobuf to 3.19.6 (v1.47.x) (1.44.x backport)

---

xds/src/main/java/io/grpc/xds/AbstractXdsClient.java
xds/src/main/java/io/grpc/xds/CsdsService.java
xds/src/main/java/io/grpc/xds/XdsClient.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/main/java/io/grpc/xds/XdsClusterResource.java
xds/src/main/java/io/grpc/xds/XdsEndpointResource.java
xds/src/main/java/io/grpc/xds/XdsListenerResource.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/main/java/io/grpc/xds/XdsResourceType.java
xds/src/main/java/io/grpc/xds/XdsRouteConfigureResource.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/CsdsServiceTest.java
xds/src/test/java/io/grpc/xds/XdsClientImplDataTest.java
xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java
xds/src/test/java/io/grpc/xds/XdsClientImplV2Test.java
xds/src/test/java/io/grpc/xds/XdsClientImplV3Test.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
xds/src/test/java/io/grpc/xds/XdsServerTestHelper.java

Follow up #9444 
Now the xds resources are dynamically managed in resourceStore in xdsClient. The types is a xdsResourceType, singleton.
There is no longer hardcoded static list of known resource types, the subscription list is the source of truth.
AbstractXdsClient that manages AdsStream will only accept the xds resource types that has already has watchers subscribed to, same behaviour as before.
Calling out that CSDS got slight behaviour changes: when it gets the subscribed resource snapshots, only the xds resource types that are actively subscribed will show up in the result map. The tests that might depend on this needs attention.
cc. @ejona86

xds: remove ResourceType enum, use XdsResourceType instead

---

grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java

I noticed these indices are mismatched, which led me to think some backends were resolved when they weren't.

grpclb: fix mismatched indices in addresses log

---

buildscripts/make_dependencies.bat
buildscripts/make_dependencies.sh

This aligns the C++ version we're using for gRPC-generated code with the Java version. This should have no real impact to our users, as there were no features added to .proto files or the like that would be visible to users.
Backport of #9585

Use Protobuf 21.7 in our code generator (1.50.x backport)

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

Not having a timeout when reading the response from a proxy server can cause a hang if network connectivity is lost at the same time.
Backport of #9586

okhttp: Add client transport proxy socket timeout (1.50.x backport)

---

rls/src/main/java/io/grpc/rls/RlsLoadBalancer.java
rls/src/test/java/io/grpc/rls/RlsLoadBalancerTest.java

Second attempt at this, now with the understanding that RLS actually can accept empty address lists.

rls: Migrate RLS LB to acceptResolvedAddresses()

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java

Moving over from handleResolvedAddresses() as part of an API migration.

xds: CdsLoadBalancer2 to use acceptResolvedAddresses

---

xds/src/main/java/io/grpc/xds/ClusterManagerLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterManagerLoadBalancerTest.java

Part of an API migration away from handleResolvedAddresses().

xds: ClusterManagerLoadBalancer to use acceptResolvedAddresses()

---

xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java

This is part of the API migration away from handleResolvedAddresses().

cds: ClusterImplLoadBalancer to use acceptResolvedAddresses()

---

xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java

Part of a wider migration to migrate load balancers away from handleResolvedAddresses().

xds: cluster_resolver to use acceptResolvedAddresses()

---

xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java

Part of a migration to move load balancers away from handleResolvedAddresses()

xds: Priority LB to use acceptResolvedAddresses()

---

gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java
gcp-observability/src/main/java/io/grpc/gcp/observability/ObservabilityConfig.java
gcp-observability/src/main/java/io/grpc/gcp/observability/ObservabilityConfigImpl.java
gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/InternalLoggingChannelInterceptor.java
gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/InternalLoggingServerInterceptor.java
gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/LogHelper.java
gcp-observability/src/main/java/io/grpc/gcp/observability/logging/GcpLogSink.java
gcp-observability/src/main/proto/grpc/observabilitylog/v1/observabilitylog.proto
gcp-observability/src/test/java/io/grpc/gcp/observability/LoggingTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/ObservabilityConfigImplTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/ConfigFilterHelperTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/InternalLoggingChannelInterceptorTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/InternalLoggingServerInterceptorTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/LogHelperTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/logging/GcpLogSinkTest.java

This PR includes changes to observability logging data model / proto as per latest logging design review.
Explicit flush is removed to rely on [default batching settings](https://github.com/googleapis/java-logging/blob/main/google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java#L649-L663) provided by Google Cloud Logging Client library. 
Ref b/248096772

gcp-observability: update observability logging proto

---

gcp-observability/src/main/java/io/grpc/gcp/observability/ObservabilityConfigImpl.java
gcp-observability/src/test/java/io/grpc/gcp/observability/ObservabilityConfigImplTest.java

This PR adds `period(.)` to the service name part of regular expression which is used to validate method or service filter provided in observability configuration.

gcp-observability: add period to service filter regular expression in logging config

---

gcp-observability/src/main/java/io/grpc/gcp/observability/ObservabilityConfigImpl.java
gcp-observability/src/test/java/io/grpc/gcp/observability/ObservabilityConfigImplTest.java

This PR adds period(.) to the service name part of regular expression which is used to validate method or service filter provided in observability configuration.
Backport of  #9631

gcp-observability: add period to service filter regular expression in logging config (1.50.x backport)

---

xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/main/java/io/grpc/xds/XdsRouteConfigureResource.java

fix 
```
> Task :grpc-xds:javadoc
/Users/zivy/src/grpc-java-2/xds/src/main/java/io/grpc/xds/XdsClientImpl.java:711: error: cannot find symbol
@VisibleForTesting
^
symbol:   class VisibleForTesting
location: class XdsClientImpl
/Users/zivy/src/grpc-java-2/xds/src/main/java/io/grpc/xds/XdsRouteConfigureResource.java:672: error: cannot find symbol
static final class RdsUpdate implements ResourceUpdate {
^
symbol:   class ResourceUpdate
location: class XdsRouteConfigureResource
```

xds: fix javadoc warning

---

.github/workflows/gradle-wrapper-validation.yml
.github/workflows/lock.yml
.github/workflows/testing.yml

Almost all of these major version bumps are because they upgraded to Node 16, which requires a new minimum version of the Runner (which matters for those maintaining their own runners). The main outlier is lock-threads, which changed the names of its input parameters.

.github/workflows: Bump action major versions

---

googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolver.java
googleapis/src/test/java/io/grpc/googleapis/GoogleCloudToProdNameResolverTest.java

This is a java analogue of C++ PR: https://github.com/grpc/grpc/pull/29922
Similar Go changes in https://github.com/grpc/grpc-go/pull/5743 and https://github.com/grpc/grpc-go/pull/5745
@ejona86

c2p resolver: use federation if enabled via env var

---

xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java

Part of a migration to move all LBs away from handleResolvedAddresses()

xds: ring_hash to use acceptResolvedAddresses()

---

xds/src/main/java/io/grpc/xds/LeastRequestLoadBalancer.java
xds/src/test/java/io/grpc/xds/LeastRequestLoadBalancerTest.java

This is part of a migration to move all LBs away from using handleResolvedAddresses().

xds: least_request LB to use acceptResolvedAddresses()

---

xds/src/test/java/io/grpc/xds/ControlPlaneRule.java
xds/src/test/java/io/grpc/xds/DataPlaneRule.java
xds/src/test/java/io/grpc/xds/FakeControlPlaneXdsIntegrationTest.java

This extracts the startup and shutdown code for the control and data plane server to separate JUnit rules, which allows this logic to be reused in other tests in a simple manner. Also makes the test easier to read with the boiler plate init code removed.

xds: Fake control plane test setup code to Rules

---

core/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
core/src/test/java/io/grpc/util/RoundRobinLoadBalancerTest.java

Switching to new API to allow eventual deprecation of handleResolvedAddresses()

core: round_robin to use acceptResolvedAddresses()

---

xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java
xds/src/test/java/io/grpc/xds/FakeControlPlaneXdsIntegrationTest.java
xds/src/test/java/io/grpc/xds/PriorityLoadBalancerTest.java

If a child policy triggers an update to the parent priority policy it will be ignored if an update is already in process.
This is the second attempt to make this change, the first one caused a problem with the ring hash LB. A new test that uses actual control plane and data plane servers is now included to prove the issue no longer appears.

xds: Delay priority LB updates from children (take 2)

---

build.gradle

I would have assumed a JMH plugin update renamed include to includes, but I don't see a mention to it in the plugin changelog. Either it was an undocumented rename, or devs just kept fixing it locally and not fixing upstream. In either case, it works now.

Fix jmh -PjmhIncludeSingleClass

---

java_grpc_library.bzl

This change migrates from `cfg = "host"` to `cfg = "exec"`.
This is a no-op cleanup: `cfg = "host"` is a deprecated alias for `cfg = "exec"`.
Tested:
```
bazel build //grpclb:grpclb
bazel build //compiler:java_grpc_library_toolchain
bazel build //compiler:grpc_java_plugin
bazel build '//compiler:*'
```
Internal ref cl/487924699

bazel: Migrate from `cfg = "host"` to `cfg = "exec"`

---

census/src/main/java/io/grpc/census/CensusStatsModule.java

This is a potential optimization, depending on the OpenCensus implementation installed. Currently, the code checks TagContext equality against the empty TagContext as an optimization to avoid updating the Context, but checking equality may not be cheaper than updating the Context. In particular, this condition is almost always true, because we [update the parentCtx with an additional
tag](https://github.com/grpc/grpc-java/blob/bacf18db8dcfbf50006eadaac1693fbce74bc550/census/src/main/java/io/grpc/census/CensusStatsModule.java#L770-L774). It's only true when there is no OpenCensus implementation (i.e. some kind of no-op implementation that ignores TagContexts) or when the empty TagContext already has that tag set to the specific value which varies depending on the RPC method.
For the …

Always update the TagContext in filterContext()

---

api/src/main/java/io/grpc/CallOptions.java

Fixes #9658 
Although `CallOptions` is annotated by `@Immutable`, its fields are not final. So it's not truly immutable, namely not thread-safe.
This PR add `final` to all fields of `CallOptions` and remove `@Immutable`. Using internal builder class to keep flexibility of constructing `CallOptions `.

Fix issue: CallOptions is not thread-safe.

---

examples/example-alts/src/main/java/io/grpc/examples/alts/HelloWorldAltsClient.java
examples/example-alts/src/main/java/io/grpc/examples/alts/HelloWorldAltsServer.java
examples/example-hostname/src/main/java/io/grpc/examples/hostname/HostnameServer.java
examples/example-jwt-auth/src/main/java/io/grpc/examples/jwtauth/AuthClient.java
examples/example-jwt-auth/src/main/java/io/grpc/examples/jwtauth/AuthServer.java
examples/example-orca/src/main/java/io/grpc/examples/orca/CustomBackendMetricsClient.java
examples/example-orca/src/main/java/io/grpc/examples/orca/CustomBackendMetricsServer.java
examples/src/main/java/io/grpc/examples/advanced/HelloJsonClient.java
examples/src/main/java/io/grpc/examples/advanced/HelloJsonServer.java
examples/src/main/java/io/grpc/examples/errorhandling/DetailErrorSample.java
examples/src/main/java/io/grpc/examples/errorhandling/ErrorHandlingClient.java
examples/src/main/java/io/grpc/examples/experimental/CompressingHelloWorldClient.java
examples/src/main/java/io/grpc/examples/experimental/CompressingHelloWorldServerAllMethods.java
examples/src/main/java/io/grpc/examples/experimental/CompressingHelloWorldServerPerMethod.java
examples/src/main/java/io/grpc/examples/header/CustomHeaderClient.java
examples/src/main/java/io/grpc/examples/header/CustomHeaderServer.java
examples/src/main/java/io/grpc/examples/hedging/HedgingHelloWorldClient.java
examples/src/main/java/io/grpc/examples/hedging/HedgingHelloWorldServer.java
examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java
examples/src/main/java/io/grpc/examples/helloworld/HelloWorldServer.java
examples/src/main/java/io/grpc/examples/retrying/RetryingHelloWorldClient.java
examples/src/main/java/io/grpc/examples/retrying/RetryingHelloWorldServer.java
examples/src/main/java/io/grpc/examples/routeguide/RouteGuideClient.java
examples/src/main/java/io/grpc/examples/routeguide/RouteGuideServer.java

This makes it more obvious when plaintext vs TLS is being used and is the preferred API.
I did not change the Google Auth example, because it is doing things a weird way and changing it would be more invasive. I also didn't update the Android examples.

examples: Swap to Channel/ServerCredentials API

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java
interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java

fix https://github.com/grpc/grpc-java/issues/9547
Add big negative integer to pending stream count when cancelled. The count is used to delay closing master listener until streams fully drained.
Increment pending stream count before creating one. The count is also used to indicate callExecutor is safe to be used. New stream not created if big negative number was added, i.e. stream cancelled. New stream is created if not cancelled, callExecutor is safe to be used, because cancel will be delayed.
1.  incrementing pending stream count only when cancel is not called, otherwise no op. This is to prevent the count never goes to `Integer.MIN_VALUE`.
2. create new streams (retry, hedging) is moved to the main thread, before callExecutor calls drain.
3. minor refactor the masterListener.close() …

core: fix RejectedExecutionException in  Retriable Stream

---

xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java
xds/src/main/java/io/grpc/xds/InternalXdsAttributes.java
xds/src/main/java/io/grpc/xds/WrrLocalityLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterResolverLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/WrrLocalityLoadBalancerTest.java

Additional logic to support for the same locality appearing under multiple priorities.

xds: Support localities in multiple priorities

---

xds/src/main/java/io/grpc/xds/RingHashLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/RingHashOptions.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerProviderTest.java

Implements https://github.com/grpc/proposal/pull/338 for Java.
Note: a configuration option (preferable taking the form of a dial option, but possibly using a global) is left as a TODO.
cc @ejona86

Limit ring hash max size to 4K

---

binder/src/main/java/io/grpc/binder/AndroidComponentAddress.java
binder/src/main/java/io/grpc/binder/BinderInternal.java
binder/src/main/java/io/grpc/binder/BinderServerBuilder.java
binder/src/main/java/io/grpc/binder/IBinderReceiver.java
binder/src/main/java/io/grpc/binder/ParcelableUtils.java
binder/src/main/java/io/grpc/binder/SecurityPolicies.java
binder/src/main/java/io/grpc/binder/SecurityPolicy.java
binder/src/main/java/io/grpc/binder/ServerSecurityPolicy.java

Removing the @experimentalapi annotation for APIs used by the App Interaction Library to enable gRPC to be used as dependency for IPCs for Jetpack.

Promoting binder out of experimental status

---

core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/main/java/io/grpc/internal/DelayedClientCall.java
core/src/test/java/io/grpc/internal/ClientCallImplTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java

Improve error message when deadline is exceeded, making it clear which deadline (Context or CallOptions) was exceeded and making the grammar clearer.

core: Improve error message when deadline is exceeded

---

core/src/main/java/io/grpc/internal/RetriableStream.java

updateAndGet is only available in API level 24+. It is unclear why AnimalSniffer didn't detect this.
This was noticed when doing the import, but the Android CI has also been failing because of it.

core: Replace AtomicInteger.updateAndGet with compareAndSet

---

api/src/main/java/io/grpc/CallOptions.java

The JIT probably cleans this up, but it is a bit confusing and needless.
CC @pandaapo 
(to be clear, it was partly confusing anyway; there was an issue before the recent change.)

api: Avoid initializing CallOptions.Builder fields that will be overwritten

---

xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/main/java/io/grpc/xds/XdsClusterResource.java
xds/src/main/java/io/grpc/xds/XdsEndpointResource.java
xds/src/main/java/io/grpc/xds/XdsListenerResource.java
xds/src/main/java/io/grpc/xds/XdsResourceType.java
xds/src/main/java/io/grpc/xds/XdsRouteConfigureResource.java
xds/src/test/java/io/grpc/xds/XdsClientImplDataTest.java
xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java

>  I argue there was never a reason for it.
The perceived value was that the dependent resources would be needed. That is true, but they would already be retained by the components outside of xds client. For example, the xds resolver watches the dependent RDS resources that were referenced in LDS.
-ejona@
follow up on https://github.com/grpc/grpc-java/pull/9444
Brief description document of the motivation: @ejona86 it would be great if you can have a glance on it. https://docs.google.com/document/d/18SYwBEt4vLsfKiJ_XOOo8lgi_HTovjz7VEhmCDkmmF4/edit#heading=h.h2ddie7y1g08

xds: remove retained resources logics for non State-of-The-World resources

---

xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java

The problem was introduced by [pr 9670](https://github.com/grpc/grpc-java/pull/9670). 
Make a copy of children values to iterate rather than directly using children in for loop
This fixes b/259971157.

xds:Fix ConcurrentModificationException in PriorityLoadBalancer

---

googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolver.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java

Log xDS node ID so that we can better debug DirectPath issues.
C++ change: https://github.com/grpc/grpc/pull/31797.

Log xDS node ID with verbosity INFO

---

xds/src/main/java/io/grpc/xds/XdsRouteConfigureResource.java
xds/src/test/java/io/grpc/xds/XdsClientImplDataTest.java
xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java

`total_weight` is deprecated and we should validate on the sum of the cluster weights
https://github.com/envoyproxy/envoy/pull/23170

xds: Nack xds response when weighted cluster total weight sums zero

---

xds/src/main/java/io/grpc/xds/PriorityLoadBalancer.java

Fix ConcurrentModificationException in PriorityLoadBalancer by making copy of children values to iterate rather than directly using children in for loop.

xds:Fix ConcurrentModificationException in PriorityLoadBalancer (#9728)

---

java_grpc_library.bzl

Replace ctx.host_configuration.host_path_separator with ctx.configuration.host_path_separator.
This is because
1. we're removing ctx.host_configuration
2. host_path_separator's value doesn't depend on the configuration (the API is misleading by embedding it under ctx.configuration). So this is a no-op.
Internal ref cl/494008561.

bazel: Replace ctx.host_configuration with ctx.configuration

---

xds/src/main/java/io/grpc/xds/AbstractXdsClient.java
xds/src/main/java/io/grpc/xds/XdsClient.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java

Update logic to match A57-xds-client-failure-mode-behavior.md
* When the ads stream is closed only send errors to subscribers that haven't yet gotten results to match spec
* Change timer creation logic to wait until the adsStream is ready before creating the timer to mark resources absent

xds:Update logic to match A57

---

api/src/main/java/io/grpc/NameResolver.java
core/src/main/java/io/grpc/internal/DnsNameResolver.java
core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/main/java/io/grpc/internal/RetryScheduler.java
core/src/main/java/io/grpc/internal/RetryingNameResolver.java
core/src/test/java/io/grpc/internal/DnsNameResolverProviderTest.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/ForwardingNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/ServiceConfigErrorHandlingTest.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancer.java

This change has these main aspects to it:
1. Removal of any name resolution responsibility from ManagedChannelImpl
2. Creation of a new RetryScheduler to own generic retry logic
- Can also be used outside the name resolution context
4. Creation of a new RetryingNameScheduler that can be used to wrap any polling name resolver to add retry capability
5. A new facility in NameResolver to allow implementations to notify listeners on the success of name resolution attempts
- RetryingNameScheduler relies on this

Move name resolution retry from managed channel to name resolver.

---

xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java

```
third_party/java_src/grpc/xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java:3519: error: [CheckReturnValue] The result of `take()` must be used
resourceDiscoveryCalls.take(); // clear this entry
```

test: fix internal ErrorProne failure

---

xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java

Previously the weight had to be <= the max signed value.  Now it can be up to the max unsigned value.

Eds weight allowed between max signed and max unsigned int

---

BUILD.bazel

bazel: Include `@Generated` dep for autovalue (1.52.x backport)

---

xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java
xds/src/test/java/io/grpc/xds/XdsClientImplV2Test.java
xds/src/test/java/io/grpc/xds/XdsClientImplV3Test.java

XdsClientImplTestBase.sendingToStoppedServer was flaky on g3, this resolves that.

xds:Fix test flakiness by adding a timeout to verify.

---

netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java

Only initiate a BDP ping after every X bytes of data where X is a multiple of the window size that increases when the window isn't changing.  
Added a ticker to the Netty handlers so that bandwidth could be properly controlled from tests.
Fixes #8260

netty:Auto adjust BDP ping frequency

---

xds/src/main/java/io/grpc/xds/RingHashLoadBalancer.java
xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java

Flag it as an error when the duplicate addresses are passed to acceptResolvedAddresses.
Removed test that was previously checking for specific expected behavior with duplicate addresses.

xds: Disallow duplicate addresses in the RingHashLB.

---

core/BUILD.bazel
netty/BUILD.bazel
services/BUILD.bazel
xds/BUILD.bazel

If an artifact on Maven Central exposes a type from gRPC on its API surface, then consumers of that artifact need that gRPC API in the compile classpath. Bazel handles this by making hjars for transitive dependencies, but if the dependencies are runtime_deps then Bazel won't generate hjars containing the needed symbols.
We don't export netty-shaded because the classes already don't match Maven Central. If an artifact on Maven Central is exposing a netty-shaded class on its API surface, it wouldn't work anyway since the class simply doesn't exist for the Bazel build.
Fixes #9772

bazel: Export deps from maven stand-in targets

---

xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java

Fixes `RingHashLoadBalancerTest.duplicateAddresses()` test.
Multiset entries are not ordered. This PR updates the test so it's not assuming the order of addresses in the error message.

xds: fix the EDS dups test so it doesn't assume address order

---

core/BUILD.bazel
netty/BUILD.bazel
services/BUILD.bazel
xds/BUILD.bazel

If an artifact on Maven Central exposes a type from gRPC on its API surface, then consumers of that artifact need that gRPC API in the compile classpath. Bazel handles this by making hjars for transitive dependencies, but if the dependencies are runtime_deps then Bazel won't generate hjars containing the needed symbols.
We don't export netty-shaded because the classes already don't match Maven Central. If an artifact on Maven Central is exposing a netty-shaded class on its API surface, it wouldn't work anyway since the class simply doesn't exist for the Bazel build.
Fixes #9772
Backport of #9780

bazel: Export deps from maven stand-in targets (1.52.x backport)

---

api/src/main/java/io/grpc/Metadata.java

api: Early-detect null bytes from Metadata.Marshaller

---

core/src/test/java/io/grpc/internal/CallCredentialsApplyingTest.java
core/src/test/java/io/grpc/internal/ClientCallImplTest.java
core/src/test/java/io/grpc/internal/ConfigSelectingClientCallTest.java
core/src/test/java/io/grpc/internal/DelayedClientCallTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplIdlenessTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java
core/src/test/java/io/grpc/internal/ServiceConfigErrorHandlingTest.java
core/src/test/java/io/grpc/util/GracefulSwitchLoadBalancerTest.java
interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java
xds/src/test/java/io/grpc/xds/WeightedTargetLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/XdsServerBuilderTest.java
xds/src/test/java/io/grpc/xds/internal/security/SslContextProviderSupplierTest.java
xds/src/test/java/io/grpc/xds/internal/security/certprovider/FileWatcherCertificateProviderTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaOobUtilTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaPerRequestUtilTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaServiceImplTest.java

The former will [soon throw NullPointerException][notnull].
[notnull]: https://github.com/mockito/mockito/commit/fe1cb2de0923e78bf7d7ae46cbab792dd4e94136#diff-8d274a9bda2d871524d15bbfcd6272bd893a47e6b1a0b460d82a8845615f26daR31
This is an export of cl/499211958

Change ArgumentCaptor.forClass(null) to ArgumentCaptor.forClass(Foo.class)

---

okhttp/src/test/java/io/grpc/okhttp/TlsTest.java

Previously, untrustedServer_fails could have been failing for the same reason as unmatchedServerSubjectAlternativeNames_fails. The implementation could have been broken and not checking the cert chain but still checking the hostname. We'd either need to override the authority to match the badserver cert or use the normal server certificates. It is best to use the normal server certificates as mtls_succeeds confirms the configuration is correct and so our test is failing for the right reason.

okhttp: Use normal server cert when testing trust checking

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

Data is getting orphaned sitting in MessageFramer. This hack thus always
flushes data out of the framer so no data can remain sitting there.
See #9340
Backport of #9360. b/264866811

core: Workaround retry causing memory leak (1.45.x backport)

---

okhttp/src/test/java/io/grpc/okhttp/TlsTest.java

This simplifies the tests and makes them more clear. basicTls_succeeds was added to confirm excluding the client cert functions.

okhttp: Remove unnecessary client certs in TlsTest

---

interop-testing/build.gradle

```
zivy-macbookpro:grpc-java-v1 zivy$ ./gradlew  :grpc-interop-testing:test
FAILURE: Build failed with an exception.
* Where:
Build file '/Users/zivy/src/grpc-java-v1/interop-testing/build.gradle' line: 54
* What went wrong:
A problem occurred evaluating project ':grpc-interop-testing'.
> Could not get unknown property 'sourceSets' for project ':grpc-api' of type org.gradle.api.Project.
BUILD FAILED in 1s
```

interop test: fix project evaluation order

---

buildscripts/kokoro/bazel.sh

Bazel 6 has been released, and we track the two most recent major versions.

Drop Bazel 4 support

---

README.md
build.gradle
compiler/build.gradle
examples/android/clientcache/build.gradle
examples/android/helloworld/build.gradle
examples/android/routeguide/build.gradle
examples/android/strictmode/build.gradle
examples/build.gradle
examples/gradle/wrapper/gradle-wrapper.properties
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
settings.gradle

As normal, Android versions weren't touched as it tends to be special to upgrade.
The errorprone plugin handles errorproneJavac for us now, since it hasn't changed in five years. VERSION_CATALOGS is already enabled by default and graduated out of preview.
Fixes #9802
-----
FYI, I released protobuf-gradle-plugin 0.9.2 yesterday, but I had already prepared this. I'll do a separate PR to upgrade to 0.9.2.

Bump to Gradle 7.6 and update plugins

---

xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java

fix b/265017892
When any of the subscribers for a resource has the last watcher cancelled,  the bug will accidentally remove that resource type from the map, which make xds stream not accepting response update for that resource type entirely (pass through, no ACK will send).
This was introduced in https://github.com/grpc/grpc-java/pull/9607 where the resource url map is dynamically controlled by the watchers.

xds:fix cancel xds watcher accidentally removes the url

---

xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java

backport of https://github.com/grpc/grpc-java/pull/9809

xds:fix cancel xds watcher accidentally removes the url (v1.52 backport)

---

xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java

backport of https://github.com/grpc/grpc-java/pull/9809

xds:fix cancel xds watcher accidentally removes the url (v1.51 backport)

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

This is follow up fix of https://github.com/grpc/grpc-java/pull/9626
This helps to prevent retryable stream from using calloptions.executor when it shouldn't. It is done by delaying notifying upper layer (through masterListener).

core: delay retriable stream master listener close until all sub streams are closed

---

interop-testing/build.gradle
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
interop-testing/src/main/java/io/grpc/testing/integration/XdsFederationTestClient.java

This client can be used as a part of XDS federation integration tests. It can concurrently perform RPCs with different stubs using different underlying XDS servers.
For example, one might perform proxyless service mesh and DirectPath RPCs in the same process with flags like:
```
--server_uris=xds:///${PSM_TARGET},google-c2p:///${DIRECTPATH_TARGET} \
--credentials_types=INSECURE_CREDENTIALS,compute_engine_channel_creds \
--test_case=rpc_soak \
--soak_iterations=10  \
--soak_max_failures=0  \
--soak_per_iteration_max_acceptable_latency_ms=2500 \
--soak_overall_timeout_seconds=300
```
cc @ejona86 
- related C++ PR: https://github.com/grpc/grpc/pull/32020
- related Go PR: https://github.com/grpc/grpc-go/pull/5878
Reviewer note: I needed to comment out `classPath` in the gradle config because …

testing: create test client for XDS federation integration tests

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

xds interop: Fix buildscripts not continuing on a failed test suite

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Reverts grpc/grpc-java#9817
Reverted in favor of better syntax suggested here: https://github.com/grpc/grpc-node/pull/2323#pullrequestreview-1248043432. This fix will be sent as another PR for the convenience of backporting.

Revert "xds interop: Fix buildscripts not continuing on a failed test suite"

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #9833 to v1.44.x.
---

xds interop: Fix buildscripts not continuing on a failed test suite (v1.44.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #9833 to v1.50.x.
---

xds interop: Fix buildscripts not continuing on a failed test suite (v1.50.x backport)

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java
stub/src/main/java/io/grpc/stub/ServerCalls.java

Fixes #9641
Add `grpc-previous-rpc-attempts` to headers when response metadata is initialized.

Fix issue: grpc-previous-rpc-attempts not added to initial response metadata

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #9833 to v1.48.x.
---

xds interop: Fix buildscripts not continuing on a failed test suite (v1.48.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #9833 to v1.52.x.
---

xds interop: Fix buildscripts not continuing on a failed test suite (v1.52.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #9833 to v1.43.x.
---

xds interop: Fix buildscripts not continuing on a failed test suite (v1.43.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #9833 to v1.47.x.
---

xds interop: Fix buildscripts not continuing on a failed test suite (v1.47.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #9833 to v1.45.x.
---
The `((` construct returns a 0 exit code if the value is non-zero. Since the value starts at 0 and we do a post-increment, it will always fail the first time. Changing it to a pre-increment should fix it.

xds interop: Fix buildscripts not continuing on a failed test suite (v1.45.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #9833 to v1.49.x.
---

xds interop: Fix buildscripts not continuing on a failed test suite (v1.49.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #9833 to v1.51.x.
---

xds interop: Fix buildscripts not continuing on a failed test suite (v1.51.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #9833 to v1.46.x.
---

xds interop: Fix buildscripts not continuing on a failed test suite (v1.46.x backport)

---

netty/src/main/java/io/grpc/netty/AbstractNettyHandler.java
netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyClientTransport.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/test/java/io/grpc/netty/NettyClientHandlerTest.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
netty/src/test/java/io/grpc/netty/NettyHandlerTestBase.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java

Restores #9650 which was reverted in grpc/grpc-java#9821 with a fix to the performance hit.

Restore "netty:Auto adjust BDP ping frequency" with fix

---

okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java

Our tests assume localhost is in /etc/hosts or uses some other form of local-only resolution. But that wouldn't apply to "host". What was happening is this was causing a DNS resolution, which would fail, and the InetSocketAddress would be "unresolved". Thus, the equivalent and faster code would be `InetSocketAddress.createUnresolved("host", 1234)`. But there doesn't seem to be any reason to avoid localhost in this test, so swap to the more typical solution instead.
This should avoid flakes like:
```
io.grpc.okhttp.OkHttpClientTransportTest > invalidAuthorityPropagates FAILED
org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
at java.base@11.0.17/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
at …
```

okhttp: Avoid DNS lookup in test

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

core: Free unused MessageProducer in RetriableStream

---

core/src/test/java/io/grpc/internal/ReadableBuffersTest.java
examples/android/clientcache/app/build.gradle
examples/build.gradle
examples/example-gauth/pom.xml
examples/example-hostname/build.gradle
examples/example-hostname/pom.xml
examples/example-jwt-auth/build.gradle
examples/example-jwt-auth/pom.xml
examples/pom.xml
gradle/libs.versions.toml
netty/src/test/java/io/grpc/netty/AdvancedTlsTest.java

ExpectedException is deprecated, so I fixed the new warnings. However, we are still using ExpectedException many places and had previously supressed the warning. See
https://github.com/grpc/grpc-java/issues/7467 . I did not fix those existing instances that had suppressed the warning, since it is unrelated to the upgrade and we have been free to fix them at any time since we dropped Java 7.

Upgrade JUnit to 4.13.2

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

core: Free unused MessageProducer in RetriableStream (1.51.x backport)

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

core: Free unused MessageProducer in RetriableStream (1.52.x backport)

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

core: Free unused MessageProducer in RetriableStream (1.45.x backport)

---

xds/src/main/java/io/grpc/xds/XdsRouteConfigureResource.java
xds/src/test/java/io/grpc/xds/XdsClientImplDataTest.java

[HeaderMatcher needs to support stringMatcher and contains](https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/route/v3/route_components.proto#L2189), and the analysis of HeaderMatcher has already been implemented in [MatcherParser](https://github.com/grpc/grpc-java/blob/master/xds/src/main/java/io/grpc/xds/internal/MatcherParser.java). Therefore, I  did the replacement.

xds: fix RouteConfiguration not supporting contains and stringMatcher

---

googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolver.java
googleapis/src/test/java/io/grpc/googleapis/GoogleCloudToProdNameResolverTest.java

Instead of always overriding the bootstrap with a custom c2p config, now we allow user defined ones to also be used. This only applies when running in GCP with federation.

googleapis: Allow user set c2p bootstrap config

---

xds/src/main/java/io/grpc/xds/AbstractXdsClient.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java

Eliminated waitForReady in XdsClient's stub. (Addresses the needs of TD Client Migration team)
The AbstractAdsStream.handleRpcStreamClosed method is used to handle both rpc error and rpc completed. Previously, if AbstractAdsStream.closed == true, then all the logic in handleRpcStreamClosed was skipped. Now it is only skipped if shutdown == true.
Additionally, adds some cleanup.

xds: Update logic so that an error being reported when stream is closed gets propagated to subscribers 

---

xds/third_party/xds/import.sh
xds/third_party/xds/src/main/proto/udpa/type/v1/typed_struct.proto
xds/third_party/xds/src/main/proto/xds/core/v3/collection_entry.proto
xds/third_party/xds/src/main/proto/xds/core/v3/context_params.proto
xds/third_party/xds/src/main/proto/xds/data/orca/v3/orca_load_report.proto
xds/third_party/xds/src/main/proto/xds/service/orca/v3/orca.proto
xds/third_party/xds/src/main/proto/xds/type/v3/typed_struct.proto

xds: import cncf/xds

---

api/src/main/java/io/grpc/MethodDescriptor.java

According to git history, method 'getBareMethodName' and 'extractBareMethodName' of MethodDescriptor appeared in [1.33.0](https://github.com/grpc/grpc-java/blob/v1.33.0/api/src/main/java/io/grpc/MethodDescriptor.java#L268)
See [1.32.0 source version](https://github.com/grpc/grpc-java/blob/v1.32.0/api/src/main/java/io/grpc/MethodDescriptor.java#L268)
Here is the diff between 1.32.0 and 1.33.0
```diff
@@ -262,6 +262,17 @@ public final class MethodDescriptor<ReqT, RespT> {
return serviceName;
}
+  /**
+   * A convenience method for {@code extractBareMethodName(getFullMethodName())}.
+   *
+   * @since 1.32.0
+   */
+  @Nullable
+  @ExperimentalApi("https://github.com/grpc/grpc-java/issues/5635")
+  public String getBareMethodName() {
+    return extractBareMethodName(fullMethodName);
+  }
+ …
```

Fixes MethodDescriptor java documentation

---

repositories.bzl
services/src/main/java/io/grpc/services/CallMetricRecorder.java
services/src/main/java/io/grpc/services/InternalCallMetricRecorder.java
services/src/main/java/io/grpc/services/MetricRecorder.java
services/src/main/java/io/grpc/services/MetricReport.java
services/src/test/java/io/grpc/services/CallMetricRecorderTest.java
xds/src/main/java/io/grpc/xds/orca/OrcaPerRequestUtil.java
xds/src/main/java/io/grpc/xds/orca/OrcaServiceImpl.java
xds/src/test/java/io/grpc/xds/orca/OrcaServiceImplTest.java

Related to cl/500201189
Uses https://github.com/grpc/grpc-java/pull/9862
gRFC: https://github.com/grpc/proposal/pull/343
cc. @ejona86

services: add qps in orca api

---

buildscripts/grpc-java-artifacts/Dockerfile

Maven seems to have improved their download management and instead of having their webpage choose a host they now have a CDN domain. apache.cs.utah.edu is slow and is failing to finish the downloading.
As discovered trying to merge #9871

Use Apache CDN to download Maven

---

api/src/main/java/io/grpc/MethodDescriptor.java
buildscripts/grpc-java-artifacts/Dockerfile
repositories.bzl
services/src/main/java/io/grpc/services/CallMetricRecorder.java
services/src/main/java/io/grpc/services/InternalCallMetricRecorder.java
services/src/main/java/io/grpc/services/MetricRecorder.java
services/src/main/java/io/grpc/services/MetricReport.java
services/src/test/java/io/grpc/services/CallMetricRecorderTest.java
xds/src/main/java/io/grpc/xds/ThreadSafeRandom.java
xds/src/main/java/io/grpc/xds/WeightedRandomPicker.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/main/java/io/grpc/xds/XdsRouteConfigureResource.java
xds/src/main/java/io/grpc/xds/orca/OrcaPerRequestUtil.java
xds/src/main/java/io/grpc/xds/orca/OrcaServiceImpl.java
xds/src/test/java/io/grpc/xds/WeightedRandomPickerTest.java
xds/src/test/java/io/grpc/xds/XdsNameResolverTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaServiceImplTest.java

Allow a cluster's total weight to be in the range between max signed int and max unsigned int.

xds:Allow big cluster total weight

---

build.gradle
netty/shaded/build.gradle

This PR fixes a pair of issues that prevent complete cacheability of certain tasks in the project's build:
1. All proto tasks rely on the root `build.gradle` file in such a way that the dependency is registered with the full absolute path of the project on the local node. This makes it impossible to cache those tasks between two nodes with a different directory layout. Fixed by specifying that the file path should be relative to the project dir.
2. The `NettyResourceTransformer` object in `netty/shaded/build.gradle` is not explicitly marked as cacheable. This, I admit, I took more of a guess that it was an oversight, but if there's a reason, I can drop that from the PR.
UPDATE:
These are the build scans that demonstrate the change:
1. [Build scan from …

Build Improvements

---

interop-testing/src/main/java/io/grpc/testing/integration/TestServiceImpl.java
interop-testing/src/test/java/io/grpc/testing/integration/NettyFlowControlTest.java
rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java

Fixes b/262779100
Previously, registerBackendResponse was being passed the opposite value from what it should have been.  Thus, successes were being registered as throttled and all errors were registered as not throttled by the backend.  Now it is only registered as throttled when there is an error and the cause is a ThrottledException.

rls:Fix throttling in route lookup (b/262779100)

---

interop-testing/src/main/java/io/grpc/testing/integration/TestServiceImpl.java
interop-testing/src/test/java/io/grpc/testing/integration/NettyFlowControlTest.java
rls/src/main/java/io/grpc/rls/CachingRlsLbClient.java
rls/src/test/java/io/grpc/rls/CachingRlsLbClientTest.java

Backport #9874 to 1.53.x
* Correct value being passed to throttler which had been backwards.
* Fix flaky test.
* Add a test using AdaptiveThrottler with a CachingRlsLBClient.
* Address test flakiness.

rls:Fix throttling in route lookup (b/262779100) (#9874)

---

api/src/main/java/io/grpc/ServerInterceptors.java
api/src/test/java/io/grpc/ServerInterceptorsTest.java

Updating ServerInterceptors to support different marshallers for requests and responses.
See https://github.com/grpc/grpc-java/issues/9870 for more details.

Updating ServerInterceptors.java to support different marshallers for Request and Response messages.

---

protobuf/build.gradle

protobuf: update external javadoc link

---

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java

This updates the value to match what is specified in [gRFC A50](https://github.com/grpc/proposal/blob/master/A50-xds-outlier-detection.md).
Based on PR #9806 by @richardartoul that can't be merged without CLA authorization.

core: fix outlier detection default ejection time

---

core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancer.java
core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerProviderTest.java
core/src/test/java/io/grpc/util/OutlierDetectionLoadBalancerTest.java

Right now there is no visibility at all into what OutlierDetection lb is doing. 
This PR is intended to fix this problem by adding ChannelLogger to the load balancer.  Here are the different types of message that will be logged (taken from my end-to-end test):
```
[2023-02-07 05:37:12 525] [FINEST ] [Channel<1>: (logs-backend-rpc-test-server.service-discovery.all-clusters.local-dc.fabric.dog:50051)] OutlierDetection lb created.
```
```
[2023-02-07 05:37:12 532] [FINEST ] [Channel<1>: (logs-backend-rpc-test-server.service-discovery.all-clusters.local-dc.fabric.dog:50051)] Received resolution result: ResolvedAddresses{addresses=[[[logs-backend-rpc-test-server.service-discovery.all-clusters.local-dc.fabric.dog/10.131.230.154:50051]/{}], …
```

add logger to OutlierDetectionLoadBalancer

---

census/src/main/java/io/grpc/census/internal/ObservabilityCensusConstants.java
gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java

This PR adds new views for payload metrics and registers new views along with latency related views for gcp-observability. 
List of new views for payload metrics:
Client Views
* `grpc.io/client/sent_compressed_message_bytes_per_rpc`
* `grpc.io/client/received_compressed_message_bytes_per_rpc`
Server Views
* `grpc.io/server/sent_compressed_message_bytes_per_rpc`
* `grpc.io/server/received_compressed_message_bytes_per_rpc`
Note: Payload related views are defined in `grpc-census` temporarily. This will be moved to [`opencensus-java`](https://github.com/census-instrumentation/opencensus-java) repository later.
The above listed views along with latency related views are enabled for `gcp-observability`.
CC @sanjaypujare @ejona86

gcp-observability: add new *compressed_bytes_per_rpc views

---

grpclb/src/main/java/io/grpc/grpclb/GrpclbNameResolver.java

This change is to address b/269159638 about GCP metadata server returning an unexpected REFUSED status instead of NXDOMAIN. This causes a 15s delay with older versions of systemd-resolved.
This issue was observed with systemd 245.4. Version 251 worked without issue.

grpclb: no SRV lookup for "metadata.google.internal."

---

xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/ControlPlaneRule.java
xds/src/test/java/io/grpc/xds/XdsClientFederationTest.java

When XdsClient learns that a control plane no longer tracks a resource, it should only notify watchers associated with that control plane.
This matters in control plane federation cases when more than one control plane is in use.

xds: deletion only to watchers of same control plane

---

api/src/main/java/io/grpc/NameResolverProvider.java
api/src/main/java/io/grpc/NameResolverRegistry.java
api/src/test/java/io/grpc/NameResolverRegistryTest.java

URI schema are case-insensitive. Previously the code would do case-sensitive matching. We expect NameResolverProviders to return the typical canonical scheme formatting, which is lower-case. If a NameResolverProvider returns an unexpected string (upper case, unicode, etc), then it simply won't ever match. Channel users, however, can use either casing in target strings.
The code implicitly already handled relative URIs by returning null, as Map.get(null) returned null.

api: Target schema should be case insensitive

---

compiler/src/java_plugin/cpp/java_generator.cpp

Linters don't like this kind of stuff.

compiler: add missing break in switch statement

---

servlet/src/jettyTest/java/io/grpc/servlet/GrpcServletSmokeTest.java
servlet/src/jettyTest/java/io/grpc/servlet/JettyInteropTest.java
servlet/src/tomcatTest/java/io/grpc/servlet/TomcatInteropTest.java
servlet/src/undertowTest/java/io/grpc/servlet/UndertowInteropTest.java

Use `NettyChannelBuilder` instead
#9858 needed this when a new dependency is added

Fix ManagedChannelBuilder

---

gcp-observability/build.gradle

google-cloud-logging brings in xds, services, and netty-shaded versions 1.43.2. grpc-netty-shaded and xds use internal APIs, so their version needs to align with grpc-api and grpc-core.  OpenCensus stackdriver components also brings in netty-shaded version 1.27.2, but it was later in the dependency list so google-cloud-logging's versions won out even if using Maven.
We don't need an explicit dependency on netty-shaded because xds depends on it transitively.
This was discovered because our GAE interop test failed in the course of PR #9858 which added grpc-gcp-observability to interop-testing (and thus also gae-interop-test):
```
Caused by: java.lang.AbstractMethodError: io.grpc.ManagedChannelProvider.getSupportedSocketAddressTypes()Ljava/util/Collection;
    at …
```

gcp-observability: Fix transitive gRPC versions

---

compiler/src/java_plugin/cpp/java_generator.cpp
compiler/src/java_plugin/cpp/java_generator.h

This is enough for the linter to realize that the missing break cases do not imply fallthrough.

compiler: Inform the compiler that GRPC_CODEGEN_FAIL aborts

---

xds/build.gradle

compile failures workaround:
https://github.com/google/error-prone/pull/2923
```
xds/build/tmp/compileJava/compileTransaction/annotation-output/io/grpc/xds/AutoValue_XdsClusterResource_CdsUpdate.java:314: warning: [AutoValueSubclassLeaked] Do not refer to the autogenerated AutoValue_ class outside the file containing the corresponding @AutoValue base class.
```

exclude generated error prone

---

xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

follow up change #9873
cc. @larry-safran

xds, wrr: randomize the initial deadline in the scheduler

---

xds/src/main/java/io/grpc/xds/AbstractXdsClient.java

Moving the retrieval of elapsed time to before cleanup avoids the meaningless race condition to which TSan objects.
fixes #9920

Move retrieval of elapsed time in handleRpcStreamClosed to make TSan happy

---

census/src/main/java/io/grpc/census/CensusStatsModule.java
census/src/main/java/io/grpc/census/internal/ObservabilityCensusConstants.java
census/src/test/java/io/grpc/census/CensusModulesTest.java
gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java

This PR adds a new measure to calculate time taken by gRPC to complete an RPC (i.e `grpc.io/client/api_latency`).
It also enables corresponding view `GRPC_CLIENT_API_LATENCY_VIEW` for `grpc-gcp-observability`.
Note: New measure and view are defined in `grpc-census` temporarily. This will be moved to [opencensus-java](https://github.com/census-instrumentation/opencensus-java) repository later.
CC @ejona86 @sanjaypujare

census: add per call latency metric

---

android-interop-testing/build.gradle
binder/build.gradle
build.gradle
core/build.gradle

The Java 7 compatibility rationale no longer holds.

errorprone: enable UnnecessaryAnonymousClass

---

xds/src/main/java/io/grpc/xds/ControlPlaneClient.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java

AbstractXdsClient is not abstract.

Rename AbstractXdsClient to ControlPlaneClient

---

api/src/main/java/io/grpc/ManagedChannelBuilder.java
api/src/main/java/io/grpc/NameResolver.java

Remove experimental annotation from the 3 relevant methods
fixes #6279

api:stabilize offloadExecutor.

---

buildscripts/observability-test/Dockerfile
buildscripts/observability-test/run.sh
gae-interop-testing/gae-jdk8/build.gradle
gcp-observability/interop/build.gradle
gcp-observability/interop/src/main/java/io/grpc/gcp/observability/interop/TestServiceInterop.java
interop-testing/build.gradle
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceServer.java
settings.gradle

gcp-observability has many dependencies so is a bit annoying in some build systems to get working... just for it not to be used in non-observability scenarios.
grpc-go and c core are using separate binaries for gcp-observability interop testing, so do the same in Java, which makes interop-testing a bit lighter.

Move gcp-observability interop binary out of interop-testing

---

binder/build.gradle

We will be running this with Java 11, which has elevated some earlier warnings to errors that fail the build. We don't want the build to fail because of this.

binder: Do not fail binder build on javadoc errors

---

.github/workflows/testing.yml
android-interop-testing/build.gradle
android-interop-testing/proguard-rules.pro
android-interop-testing/src/androidTest/AndroidManifest.xml
android-interop-testing/src/main/AndroidManifest.xml
android/build.gradle
android/src/main/AndroidManifest.xml
binder/build.gradle
binder/src/androidTest/AndroidManifest.xml
binder/src/main/AndroidManifest.xml
build.gradle
buildscripts/kokoro/android.sh
buildscripts/kokoro/linux_artifacts.sh
cronet/build.gradle
cronet/src/main/AndroidManifest.xml
examples/android/clientcache/app/build.gradle
examples/android/clientcache/app/src/main/AndroidManifest.xml
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/routeguide/app/src/main/AndroidManifest.xml
examples/android/strictmode/app/build.gradle
examples/android/strictmode/app/src/main/AndroidManifest.xml
settings.gradle

This is the latest version of the plugin supported by the Gradle version
in use at the moment (7.6).
Note that this also upgrades the R8 optimizer to a version (4.0.48) that
now uses "full mode" optimization by default.
This also splits off Android projects to run under Java 11 (Gradle
plugin requirement) while the other projects continue to run under Java
8.

Upgrade Android Gradle plugin to 7.4.0

---

interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java

I noticed that after #9937 was merged, the Java observability tests start to fail.
I track it down to this [System.exit(0)](https://github.com/grpc/grpc-java/blob/master/interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java#L74) call in the existing Interop client `main()` method. That line is preventing execution to continue in the new combined Observability Interop test binary [here](https://github.com/grpc/grpc-java/blob/master/gcp-observability/interop/src/main/java/io/grpc/gcp/observability/interop/TestServiceInterop.java#L50-L54).  (The new binary is calling the old binary's `main()` method.)
I think normal execution (no errors) of the existing interop client binary will still end up with a 0 exit status even without that line?

Do not System.exit(0) from interop client

---

api/src/main/java/io/grpc/CallOptions.java
api/src/main/java/io/grpc/ServerCall.java
stub/src/main/java/io/grpc/stub/AbstractStub.java

Stabilize the following by removing `@ExperimentalApi`
CallOptions.withCompression
CallOptions.getCompressor
ServerCall.setCompression - make clear it is for sending
ServerCall. setMessageCompression
AbstractStub.withCompression - update javadoc to stop implying have to call decompressionRegistry
addresses parts of #1704 that were agreed to in the stabilization meeting

api,stub:Stabilize part of compression agreed to in the stabilization meeting

---

buildscripts/observability-test/run.sh

Each `run.sh` should just pass those parameters through to the interop client/server binaries as-is.
Framework PR: https://github.com/GoogleCloudPlatform/grpc-gcp-tools/pull/28

Observability Testing: Pass interop parameters to each lang's run.sh as-is

---

android-interop-testing/build.gradle
android-interop-testing/src/androidTest/java/io/grpc/android/integrationtest/UdsChannelInteropTest.java
android-interop-testing/src/main/AndroidManifest.xml
android-interop-testing/src/main/java/io/grpc/android/integrationtest/TesterActivity.java
android-interop-testing/src/main/java/io/grpc/android/integrationtest/UdsTcpEndpointConnector.java
android-interop-testing/src/main/res/color/focus.xml
android-interop-testing/src/main/res/layout/activity_tester.xml
android/src/main/java/io/grpc/android/UdsChannelBuilder.java
android/src/main/java/io/grpc/android/UdsSocket.java
android/src/main/java/io/grpc/android/UdsSocketFactory.java

Allows using Android's LocalSocket via a Socket adapter. Such an adapter
isn't generally 100% safe, since some methods may not have any effect,
but we know what methods are called by gRPC's okhttp transport and can
update the adapter or the transport as appropriate.
----
This code is actually dates back to March and has already been used by an app for a while. This is merely the open sourcing of the code that I'd promised @kenk42292. The reflection in UDSChannelBuilder is new (previously it referenced OkHttpChannelBuilder directly) and I added a few comments. I'm disappointed we need to use Netty in the interop test, but TLS isn't really an option because Conscrypt is incompatible with non-platform Socket implementations.
@dapengzhang0, we may want to discuss if someone else should …

android: Add UdsChannelBuilder

---

census/src/main/java/io/grpc/census/CensusTracingModule.java
census/src/main/java/io/grpc/census/InternalCensusTracingAccessor.java
census/src/test/java/io/grpc/census/CensusModulesTest.java
census/src/test/java/io/grpc/census/CensusTracingAnnotationEventTest.java
gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java

This PR uses [OpenCensus Annotation](https://www.javadoc.io/static/io.opencensus/opencensus-api/0.31.0/io/opencensus/trace/Annotation.html) to report message size [bytes] for inbound/received messages in traces.
`addMessageEvent` API which is currently used expects both uncompressed and compressed message (optional) sizes to be reported at the same. Since decompression for messages happens at a later point in time, reporting compressed message as is and reporting uncompressed size as `-1` renders the size as _0 bytes received_ in cloud tracing front end.
As a workaround, we add _two annotations for each received message_:
* For compressed message size
* For uncompressed message size (when it is available)
This PR also removes `addMessageEvents` a flag introduced in PR #9485 to temporarily …

census: Trace annotation for reporting inbound message sizes

---

census/src/main/java/io/grpc/census/CensusTracingModule.java
census/src/main/java/io/grpc/census/InternalCensusTracingAccessor.java
census/src/test/java/io/grpc/census/CensusModulesTest.java
census/src/test/java/io/grpc/census/CensusTracingAnnotationEventTest.java
gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java

Backport of #9944 to v1.54.x.
---
This PR uses [OpenCensus Annotation](https://www.javadoc.io/static/io.opencensus/opencensus-api/0.31.0/io/opencensus/trace/Annotation.html) to report message size [bytes] for inbound/received messages in traces.
`addMessageEvent` API which is currently used expects both uncompressed and compressed message (optional) sizes to be reported at the same. Since decompression for messages happens at a later point in time, reporting compressed message as is and reporting uncompressed size as `-1` renders the size as _0 bytes received_ in cloud tracing front end.
As a workaround, we add _two annotations for each received message_:
* For compressed message size
* For uncompressed message size (when it is available)
This PR also removes `addMessageEvents` a flag …

census: Trace annotation for reporting inbound message sizes (v1.54.x backport)

---

buildscripts/kokoro/unix.sh
examples/example-servlet/build.gradle

buildscript: iterate example folder and build

---

gcp-observability/build.gradle
gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/LogHelper.java
gcp-observability/src/main/java/io/grpc/gcp/observability/logging/GcpLogSink.java
gcp-observability/src/main/proto/grpc/observabilitylog/v1/observabilitylog.proto
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/LogHelperTest.java

This PR updates the following in gcp observability logging schema
* `payload.status_code` will be of type `google.rpc.Code` instead of `uint32`.
*  names in enum `Address.TYPE`
Use custom batching settings for [LoggingOptions](https://javadoc.io/doc/com.google.cloud/google-cloud-logging/latest/com/google/cloud/logging/LoggingOptions.html)
Note: Upgraded `com.google.cloud:google-cloud-logging` from `3.6.1` to `3.14.5`.
CC @ejona86  @sanjaypujare

gcp-observability: Update logging fields for GA and use custom BatchingSettings

---

examples/README.md
examples/build.gradle
examples/logging.properties
examples/src/main/java/io/grpc/examples/keepalive/KeepAliveClient.java
examples/src/main/java/io/grpc/examples/keepalive/KeepAliveServer.java

fixes [b/259284839](http://b/259284839)

examples: add keepalive example

---

census/src/main/java/io/grpc/census/CensusTracingModule.java
census/src/main/java/io/grpc/census/internal/ObservabilityCensusConstants.java
census/src/test/java/io/grpc/census/CensusModulesTest.java
census/src/test/java/io/grpc/census/CensusTracingAnnotationEventTest.java
gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java
gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/InternalLoggingChannelInterceptor.java
gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/InternalLoggingServerInterceptor.java
gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/LogHelper.java
gcp-observability/src/main/java/io/grpc/gcp/observability/logging/GcpLogSink.java
gcp-observability/src/main/java/io/grpc/gcp/observability/logging/Sink.java
gcp-observability/src/main/java/io/grpc/gcp/observability/logging/TraceLoggingHelper.java
gcp-observability/src/test/java/io/grpc/gcp/observability/LoggingTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/InternalLoggingChannelInterceptorTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/InternalLoggingServerInterceptorTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/LogHelperTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/logging/GcpLogSinkTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/logging/TraceLoggingHelperTest.java

This PR adds trace information (TraceId, SpanId and TraceSampled) fields to LogEntry, when both logging and tracing are enabled in gcp-observability. 
For server-side logs, span information was readily available using Span.getContext() propagated via `io.grpc.Context`. Similar approach is not feasible for client-side architecture.
Client SpanContext which has all the information required to be added to logs is propagated to the logging interceptor via `io.grpc.CallOptions`.
CC @ejona86 @sanjaypujare

gcp-observability, census: add trace information to logs

---

gcp-observability/build.gradle
gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/LogHelper.java
gcp-observability/src/main/java/io/grpc/gcp/observability/logging/GcpLogSink.java
gcp-observability/src/main/proto/grpc/observabilitylog/v1/observabilitylog.proto
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/LogHelperTest.java

Backport of #9959 to v1.54.x.
---
This PR updates the following in gcp observability logging schema
* `payload.status_code` will be of type `google.rpc.Code` instead of `uint32`.
*  names in enum `Address.TYPE`
Use custom batching settings for [LoggingOptions](https://javadoc.io/doc/com.google.cloud/google-cloud-logging/latest/com/google/cloud/logging/LoggingOptions.html)
Note: Upgraded `com.google.cloud:google-cloud-logging` from `3.6.1` to `3.14.5`.
CC @ejona86  @sanjaypujare

gcp-observability: Update logging fields for GA and use custom BatchingSettings (v1.54.x backport)

---

census/src/main/java/io/grpc/census/CensusTracingModule.java
census/src/main/java/io/grpc/census/internal/ObservabilityCensusConstants.java
census/src/test/java/io/grpc/census/CensusModulesTest.java
census/src/test/java/io/grpc/census/CensusTracingAnnotationEventTest.java
gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java
gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/InternalLoggingChannelInterceptor.java
gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/InternalLoggingServerInterceptor.java
gcp-observability/src/main/java/io/grpc/gcp/observability/interceptors/LogHelper.java
gcp-observability/src/main/java/io/grpc/gcp/observability/logging/GcpLogSink.java
gcp-observability/src/main/java/io/grpc/gcp/observability/logging/Sink.java
gcp-observability/src/main/java/io/grpc/gcp/observability/logging/TraceLoggingHelper.java
gcp-observability/src/test/java/io/grpc/gcp/observability/LoggingTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/InternalLoggingChannelInterceptorTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/InternalLoggingServerInterceptorTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/LogHelperTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/logging/GcpLogSinkTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/logging/TraceLoggingHelperTest.java

Backport of #9963 to v1.54.x.
---
This PR adds trace information (TraceId, SpanId and TraceSampled) fields to LogEntry, when both logging and tracing are enabled in gcp-observability. 
For server-side logs, span information was readily available using Span.getContext() propagated via `io.grpc.Context`. Similar approach is not feasible for client-side architecture.
Client SpanContext which has all the information required to be added to logs is propagated to the logging interceptor via `io.grpc.CallOptions`.
CC @ejona86 @sanjaypujare

gcp-observability, census: add trace information to logs (v1.54.x backport)

---

interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java

I noticed that after #9937 was merged, the Java observability tests start to fail.
I track it down to this [System.exit(0)](https://github.com/grpc/grpc-java/blob/master/interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java#L74) call in the existing Interop client `main()` method. That line is preventing execution to continue in the new combined Observability Interop test binary [here](https://github.com/grpc/grpc-java/blob/master/gcp-observability/interop/src/main/java/io/grpc/gcp/observability/interop/TestServiceInterop.java#L50-L54).  (The new binary is calling the old binary's `main()` method.)
I think normal execution (no errors) of the existing interop client binary will still end up with a 0 exit status even without that line?
Backport of #9940

Do not System.exit(0) from interop client (1.54.x backport)

---

gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java

This PR disables recording real time metrics, which are just being recorded and not exported by observability.

gcp-o11y: disable recording real-time metrics

---

android-interop-testing/src/androidTest/java/io/grpc/android/integrationtest/UdsChannelInteropTest.java

Everywhere else is using
androidx.test.ext.junit.runners.AndroidJUnit4, and google internally only has that variant.

test/android: fix the import for AndroidJUnit4.

---

gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java

Backport of #9976 to v1.54.x.
---
This PR disables recording real time metrics, which are just being recorded and not exported by observability

gcp-o11y: disable recording real-time metrics (v1.54.x backport)

---

gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java

Backport of #9972 to v1.54.x.
---
This PR adds sleep in `close()` for metrics and/or traces to be flushed before closing observability.
Currently sleep is set to 2 * [Metrics export interval (30 secs)].
CC @sanjaypujare @ejona86 
CC @stanley-cheung : this might alter inter-op tests results

gcp-o11y: add sleep in Observability close() (v1.54.x backport)

---

gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java

This PR adds a default custom tag for metrics, irrespective of custom tags being present in the observability configuration. 
OpenCensus by default adds a custom tag [opencenus_task](https://docs.google.com/document/d/1sWC-XD277cM0PXxAhzJKY2X0Uj2W7bVoSv-jvnA0N8Q/edit?resourcekey=0-l-wqh1fctxZXHCUrvZv2BQ#heading=h.xy85j580eik0) for metrics which gets overriden if custom tags are set.
The unique custom tag is required to ensure the uniqueness of the Timeseries. The format of the default custom tag is: `java-{PID}@{HOSTNAME}`, if `{PID}` is not available a random number will be used.

gcp-o11y: add default custom tag for metrics exporter

---

examples/BUILD.bazel
examples/build.gradle
examples/src/main/java/io/grpc/examples/cancellation/CancellationClient.java
examples/src/main/java/io/grpc/examples/cancellation/CancellationServer.java
examples/src/main/proto/grpc/examples/echo/echo.proto

It uses the echo service for both unary and bidi RPCs, to show the various cancellation circumstances and APIs.
-----
I'm not wild about all the comments needed, as it reduces the "flow" when reading, but it seemed they were needed. Maybe I could remove the "Make logs more obvious" comments, but...

examples: Add cancellation example

---

examples/example-gcp-observability/README.md
examples/example-gcp-observability/build.gradle
examples/example-gcp-observability/settings.gradle
examples/example-gcp-observability/src/main/java/io/grpc/examples/gcpobservability/GcpObservabilityClient.java
examples/example-gcp-observability/src/main/java/io/grpc/examples/gcpobservability/GcpObservabilityServer.java
examples/example-gcp-observability/src/main/proto/helloworld/helloworld.proto
examples/example-gcp-observability/src/main/resources/io/grpc/examples/gcpobservability/gcp_observability_client_config.json
examples/example-gcp-observability/src/main/resources/io/grpc/examples/gcpobservability/gcp_observability_server_config.json

Backport of #9967 to v1.54.x.
---
This PR adds `gcp-observability` example based on `HelloWorld`.
CC @sanjaypujare @ejona86 @fengli79

examples: add gcp-observability examples (v1.54.x backport)

---

gcp-observability/interop/src/main/java/io/grpc/gcp/observability/interop/TestServiceInterop.java

After #9972, the `sleep()` is done inside Observability `close()`, we can remove this `sleep()` in the Observability Interop test binary.
Backport of #9977
CC @DNVindhya, @stanley-cheung

Remove sleep from Observability Interop Test binary now that its done in close() (1.54.x backport)

---

servlet/src/main/java/io/grpc/servlet/AsyncServletOutputStreamWriter.java

The commit https://github.com/grpc/grpc-java/pull/8596/commits/792946132c6bb38ebfd84787fa40b768f4b6d7ad#diff-cc7b2eb82d208e027f432435bcd324a46713c31096352f437417b770752f92abR197 makes it possible that the sleep can naturally wake up while `writeState` gets changes at the same time, causing a data race in the value of `parkingThread` between
https://github.com/niloc132/grpc-java/blob/792946132c6bb38ebfd84787fa40b768f4b6d7ad/servlet/src/main/java/io/grpc/servlet/AsyncServletOutputStreamWriter.java#L199
and 
https://github.com/niloc132/grpc-java/blob/792946132c6bb38ebfd84787fa40b768f4b6d7ad/servlet/src/main/java/io/grpc/servlet/AsyncServletOutputStreamWriter.java#L218
in extreme scenario such as the CPU is stressed.
Fixes #9917

servlet: Fix AsyncServletOutputStreamWriterConcurrencyTest flakiness

---

.github/workflows/testing.yml

The coveralls task has been silently failing since we migrated to GitHub Actions, away form Travis-CI:
```
no COVERALLS_REPO_TOKEN environmental variable found
no available CI service
> Task :grpc-all:coveralls
BUILD SUCCESSFUL in 23s
7 actionable tasks: 1 executed, 6 up-to-date
```
We'd rather not deal with private tokens, but the Coveralls GitHub Action [only supports lcov][1] which makes it unhelpful for Java. Looking deeper, yep, we [aren't the only ones impacted][2]:
[1]: https://github.com/marketplace/actions/coveralls-github-action
[2]: https://github.com/coverallsapp/github-action/issues/22

.github/workflows: Pass COVERALLS_REPO_TOKEN to coveralls task

---

RELEASING.md

Clarify some areas where I misstepped on my first time doing a full release.

README.md:Improve instructions

---

gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/InternalLoggingChannelInterceptorTest.java
gcp-observability/src/test/java/io/grpc/gcp/observability/interceptors/InternalLoggingServerInterceptorTest.java
services/src/test/java/io/grpc/protobuf/services/BinlogHelperTest.java

Fix order dependent tests by changing the initializations and comparison so that elapsed time isn't as significant in identifying whether it was the context or call option's duration that was used.
Test are related to getting duration from either calloptions or context and, because real time was involved, when class loading got in the picture the comparison could exceed the 250 ms limit.

Fix order dependent tests regarding message duration b/271122310

---

examples/BUILD.bazel
examples/build.gradle
examples/src/main/java/io/grpc/examples/multiplex/EchoService.java
examples/src/main/java/io/grpc/examples/multiplex/MultiplexingServer.java
examples/src/main/java/io/grpc/examples/multiplex/SharingClient.java

Part of example Fixit
Fixes b/259285817

examples:Client and Server sharing example

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpServerTransport.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpServerTransportTest.java

fixes https://github.com/grpc/grpc-java/issues/9721

okhttp: forceful close after MAX_CONNECTION_AGE_GRACE_TIME

---

RELEASING.md

Address some review comments that came in for #9974 after it had already been merged.
* Updated push command to include the --set-upstream argument for people who haven't enabled autoSetupRemote.
* Removed comments about updating protoc plugin version

RELEASING.md:Addressed review comments.

---

examples/BUILD.bazel
examples/build.gradle
examples/src/main/java/io/grpc/examples/customloadbalance/CustomLoadBalanceClient.java
examples/src/main/java/io/grpc/examples/customloadbalance/ShufflingPickFirstLoadBalancer.java
examples/src/main/java/io/grpc/examples/customloadbalance/ShufflingPickFirstLoadBalancerProvider.java

Example on how to implement a custom `LoadBalancer`.

examples: custom load balancer example

---

RELEASING.md

This PR uses glob `example-*` instead of explicitly adding all the example `build.gradle` and `pom.xml` files which has gRPC versions.
This change fixes instances like `example-gcp-observability/build.gradle` (a new example) was added and `RELEASING.md` was not updated to include the new file.

RELEASING.md: use glob for example file names

---

examples/build.gradle
examples/src/main/java/io/grpc/examples/errordetails/DetailErrorSample.java
examples/src/main/java/io/grpc/examples/errordetails/ErrorDetailsExample.java

Show how to use google.rpc.Status returned as the details of io.grpc.Status.

examples: Error details example

---

xds/src/main/java/io/grpc/xds/LoadReportClient.java
xds/src/main/java/io/grpc/xds/XdsClient.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/XdsClientFederationTest.java

The old code used a single member variable to indicate if load reporting had already been started by XdsClientImpl. This boolean was used to avoid starting a LoadReportClient more than twice. This works fine with a single control plane server.
The problem occurs in federation situations where there is more than one control plane and thus more than one LoadReportClient. Once the first LoadReportClient is started, the member variable boolean is flipped to true and no other LoadReportClients would be started.
This change removes the boolean member variable and relies on the fact that starting an already started LoadReportClient is a no-op.
This is to address b/274812461.

xds: Correctly start LRS clients in federation situations

---

examples/example-gcp-observability/build.gradle

gcp-observability was missing from RELEASING.md, so it wasn't updated when we changed the patch release.
CC @DNVindhya 
I checked, and master was already okay. So this is not a backport.

examples: Fix grpc version in gcp-observability (v1.54.x)

---

RELEASING.md

This PR uses glob `example-*` instead of explicitly adding all the example `build.gradle` and `pom.xml` files which has gRPC versions.
This change fixes instances like `example-gcp-observability/build.gradle` (a new example) was added and `RELEASING.md` was not updated to include the new file.
Backport of #9998
CC @DNVindhya

RELEASING.md: use glob for example file names (1.54.x backport)

---

xds/src/main/java/io/grpc/xds/LoadReportClient.java
xds/src/main/java/io/grpc/xds/XdsClientImpl.java
xds/src/test/java/io/grpc/xds/XdsClientFederationTest.java

Currently the code maintains one LoadStatsManager2 that collects all stats. The problem with this is that in a federation situation there will be multiple LrsClients that will be periodically picking up stats from the manager and sending them to their respective control planes. This creates a first-come-first-serve situation where the stats get randomly distributed across the control planes.
This change creates separate LoadStatsManagers dedicated to their own control planes, thus assuring no stats will get lost.
b/274812461

xds: Distinct LoadStatManagers

---

netty/build.gradle

This was added in 9ef07916 and should have lived until we upgraded to a newer Netty in 67eefa69.

netty: Remove long-dead third_party reference

---

xds/src/test/java/io/grpc/xds/XdsTestControlPlaneService.java

This is to eliminate concurrent modification issues when XdsTestControlPlaneService is used by multiple threads.
Fixes: #9938

xds: Synchronize access to test control plane collections

---

protobuf/build.gradle

Backport of #9890. Seeing the error in #10019

protobuf: update external javadoc link (1.50.x backport)

---

gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java

Removes the ExperimentalApi annotation from GcpObservability.
Contributes to: #8869

gcp-o11y: Stabilize GcpObservability

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

core: Free unused MessageProducer in RetriableStream (1.50.x backport)

---

gcp-observability/src/main/java/io/grpc/gcp/observability/GcpObservability.java

Removes the ExperimentalApi annotation from GcpObservability.
Contributes to: #8869 
Backport of #10024

gcp-o11y: Stabilize GcpObservability (1.54.x backport)

---

alts/src/main/java/io/grpc/alts/internal/AltsProtocolNegotiator.java
alts/src/test/java/io/grpc/alts/internal/AltsProtocolNegotiatorTest.java

The logic is straightforward: attempt to read the GRPC_ALTS_MAX_CONCURRENT_HANDSHAKES environment variable and, if it set to an integer, instantiate the handshake queues based on this integer.
Based on go/grpc-alts-concurrent-handshake-cap. See https://github.com/grpc/grpc/pull/32672 for a comparison with the C-core logic.

alts: Enable user to configure max number of concurrent ALTS handshakes.

---

interop-testing/src/main/java/io/grpc/testing/integration/RpcBehaviorLoadBalancerProvider.java
interop-testing/src/test/java/io/grpc/testing/integration/RpcBehaviorLoadBalancerProviderTest.java

Move this test LB over to using `acceptResolvedAddresses()` as `handleResolvedAddresses()` is going to be deprecated.

testing: RpcBehaviorLoadBalancingProvider to use acceptResolvedAddresses()

---

benchmarks/src/test/java/io/grpc/benchmarks/driver/LoadWorkerTest.java
interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java

LoadWorkerTest.runUnaryBlockingClosedLoop and Http2NettyTest.tlsInfo are failing every CI run. It appears they are the unfortunate tests run first, so are slowest to start as classloading proceeds. There's definitely other tests that probably need adjustment, but fixing these two gives us some hope of having a green run occasionally.

Increase test timeouts for ARM emulation

---

.github/workflows/testing.yml

There was recently a failure with the Tomcat test in servlet/jakarta:
```
io.grpc.servlet.jakarta.TomcatInteropTest > pingPong FAILED
java.lang.AssertionError at AbstractInteropTest.java:845
Caused by: io.grpc.StatusRuntimeException at Status.java:539
...
* What went wrong:
Execution failed for task ':grpc-servlet-jakarta:tomcat10Test'.
> There were failing tests. See the report at: file:///home/runner/work/grpc-java/grpc-java/servlet/jakarta/build/reports/tests/tomcat10Test/index.html
```
But we couldn't get more details because servlet/jakarta didn't match the artifact glob.

.github/workflows: Save subproject reports on test failure

---

binder/src/main/java/io/grpc/binder/BindServiceFlags.java
binder/src/test/java/io/grpc/binder/BindServiceFlagsTest.java

This flag is added in the U SDK, which is still under development. Since it's just a numeric constant, we copy the value until it is stable and mark the API is experimental, with appropriate warnings about depending on it from production code.
A follow-up change will be made after SDK finalization to point to the official constant (or otherwise update to match any SDK changes), at which point we can remove the `@ExternalApi` annotation.
See b/274061424

Add BIND_ALLOW_ACTIVITY_STARTS to BindServiceFlags.

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

The problem was one hedge was committed before another had drained start(). This was not testable because HedgingRunnable checks whether scheduledHedgingRef is cancelled, which is racy, but there's no way to deterministically trigger either race.
The same problem couldn't be triggered with retries because only one attempt will be draining at a time. Retries with cancellation also couldn't trigger it, for the surprising reason that the noop stream used in cancel() wasn't considered drained.
This commit marks the noop stream as drained with cancel(), which allows memory to be garbage collected sooner and exposes the race for tests. That then showed the stream as hanging, because inFlightSubStreams wasn't being decremented.
Fixes #9185

core: Fix NPE race during hedging

---

xds/src/test/java/io/grpc/xds/ControlPlaneRule.java
xds/src/test/java/io/grpc/xds/XdsTestLoadReportingService.java

`LoadReportingClient` not being able to connect to a `LoadReportingService` in the test control plane server is the probable cause for the flaky test behavior described in #10015. When the `LoadReportingClient` is not able to connect to the service, it would set the `lrsStream` field to null. This is racing with the test execution and results in occasional test failures.
This PR sets a dummy `LoadReportingService` in the control plane server, allowing the test to properly open an LRS stream to the control plane.

xds: Add dummy LRS service for control plane tests

---

buildscripts/observability-test/run.sh

I noticed that Java observability tests fail when run on a forked branch of `v1.54.x`, because the positional arguments mentioned were not in the right format.
Backport of #9946 
Each `run.sh` should just pass those parameters through to the interop client/server binaries as-is.
Framework PR: https://github.com/GoogleCloudPlatform/grpc-gcp-tools/pull/28
CC @ejona86 @fengli79

Observability Testing: Pass interop parameters to each lang's run.sh as-is (v1.54.x backport)

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

The problem was one hedge was committed before another had drained start(). This was not testable because HedgingRunnable checks whether scheduledHedgingRef is cancelled, which is racy, but there's no way to deterministically trigger either race.
The same problem couldn't be triggered with retries because only one attempt will be draining at a time. Retries with cancellation also couldn't trigger it, for the surprising reason that the noop stream used in cancel() wasn't considered drained.
This commit marks the noop stream as drained with cancel(), which allows memory to be garbage collected sooner and exposes the race for tests. That then showed the stream as hanging, because inFlightSubStreams wasn't being decremented.
Fixes #9185
Backport of #10007

core: Fix NPE race during hedging (1.53.x backport)

---

.github/workflows/testing.yml

This has been broken and not running tests since d580bd3 (just a few days ago).

.github/workflows: Fix duplicate key in testing CI

---

.github/workflows/testing.yml

This will replace the kokoro-based CI. We need to upgrade the image Kokoro runs on, but it is easier to add a GitHub Actions CI than to run a one-off test on a new image with Kokoro.
A clean run takes 10 minutes and a cached run takes 8.5. So it is a little bit slower than the 5.5 minutes on Kokoro, but still pretty quick.
----
This is related to #10045. CC @larry-safran

.github/workflows: Add Bazel CI

---

core/src/main/java/io/grpc/util/ForwardingLoadBalancer.java
core/src/test/java/io/grpc/util/ForwardingLoadBalancerTest.java

`ForwardingLoadBalancer` was not forwarding `acceptResolvedAddresses()` calls to its delegate. This was not an issue before because the LBs that extended `ForwardingLoadBalancer` all implemented `handleResolvedAddresses()`. With the push to deprecate `handleResolvedAddresses()` `RpcBehaviorLoadBalancerProvider` recently changed to use `acceptResolvedAddresses()` but this caused problems in internal interop tests as that method was not being delegated.
This should fix b/277724057

core: ForwardingLoadBalancer to forward acceptResolvedAddresses()

---

core/src/main/java/io/grpc/util/ForwardingLoadBalancer.java
core/src/test/java/io/grpc/util/ForwardingLoadBalancerTest.java
interop-testing/src/main/java/io/grpc/testing/integration/RpcBehaviorLoadBalancerProvider.java
interop-testing/src/test/java/io/grpc/testing/integration/RpcBehaviorLoadBalancerProviderTest.java

A recent change (#10030) to move this test load balancer to use `acceptResolvedAddresses()` caused a test failure that a subsequent commit (#10050  failed to remedy. Reverting both for now since we are so close to release branch cut. I will make another go at this later.

Revert RpcBehaviorLoadBalancerProvider.acceptResolvedAddresses()

---

api/src/main/java/io/grpc/ClientStreamTracer.java
census/src/main/java/io/grpc/census/CensusTracingModule.java
census/src/test/java/io/grpc/census/CensusModulesTest.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

follow up https://github.com/grpc/grpc-java/pull/10014

census: add delayed name resolution tracing annotation

---

RELEASING.md
cronet/README.md
documentation/android-channel-builder.md

This removes some steps from the release process. These two locations aren't special enough in way that deserves manually changing the version each release.

Avoid repeating grpc version in Android documentation

---

rls/src/main/java/io/grpc/rls/LbPolicyConfiguration.java
rls/src/test/java/io/grpc/rls/LbPolicyConfigurationTest.java

If a child load balancer rejects the addresses it if given all we can do is to trigger a name resolution refresh and hope for a better set of addresses.

rls: Refresh name resolution on rejected addresses

---

examples/build.gradle

The point of the sorting is to reduce the chances of merge conflicts. I greatly prefer verboseness over cleverness in examples, but the tasks can only be sorted manually and there's so many of them.
It is counter-productive to do this for the examples that have their own project folder, as there's so few tasks in that case that they don't need to be ordered.
------
I don't mind if you don't like this approach. In #10059 I realized this still needed some love. Sorting the existing `applicationDistribution` was easy, but the tasks would have been a PITA.

examples: Reduce boilerplate and sort scripts

---

core/src/main/java/io/grpc/internal/AbstractStream.java
core/src/main/java/io/grpc/internal/ClientCallImpl.java
core/src/main/java/io/grpc/internal/MigratingThreadDeframer.java
core/src/main/java/io/grpc/internal/ServerCallImpl.java
core/src/main/java/io/grpc/internal/ServerImpl.java
netty/src/main/java/io/grpc/netty/NettyClientHandler.java
netty/src/main/java/io/grpc/netty/NettyClientStream.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/main/java/io/grpc/netty/NettyServerStream.java
netty/src/main/java/io/grpc/netty/WriteQueue.java
okhttp/src/main/java/io/grpc/okhttp/AsyncSink.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java
okhttp/src/main/java/io/grpc/okhttp/OkHttpServerStream.java

PerfMark was added to gRPC before Java7 features like try-with-resources were allowed.   This changes moves over all the old calls to PerfMark startTask and stopTask to traceTask, which works nicely with TwR.   Useless `finally` blocks are mostly gone.  Some indentation is added to adapt this change, but there should be no functionality changes with this PR, except for the bug mentioned below.
The motivation for this change is `NettyServerStream.cancel`, which accidentally calls `startTask` incorrectly in the finally block.

all: use PerfMark.traceTask

---

examples/build.gradle
examples/src/main/java/io/grpc/examples/grpcproxy/GrpcProxy.java

I finally cleaned it up where it could be merged.

examples: grpc-level proxy

---

buildscripts/kokoro/psm-security.cfg

buildscripts: increase PSM Security test timeout to 4h

---

authz/build.gradle
authz/src/main/java/io/grpc/authz/AuthorizationServerInterceptor.java
authz/src/main/java/io/grpc/authz/FileWatcherAuthorizationServerInterceptor.java
authz/src/test/java/io/grpc/authz/AuthorizationEnd2EndTest.java
authz/src/test/java/io/grpc/authz/AuthorizationPolicyTranslatorTest.java
authz/src/test/java/io/grpc/authz/AuthorizationServerInterceptorTest.java
authz/src/test/java/io/grpc/authz/FileWatcherAuthorizationServerInterceptorTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-java/9775)

File Watcher Authorization Server Interceptor

---

buildscripts/kokoro/psm-security.cfg

Backport of #10065 to v1.54.x.
---

buildscripts: increase PSM Security test timeout to 4h (v1.54.x backport)

---

buildscripts/kokoro/psm-security.cfg

Backport of #10065 to v1.53.x.
---

buildscripts: increase PSM Security test timeout to 4h (v1.53.x backport)

---

buildscripts/kokoro/psm-security.cfg

Backport of #10065 to v1.52.x.
---

buildscripts: increase PSM Security test timeout to 4h (v1.52.x backport)

---

buildscripts/kokoro/psm-security.cfg

Backport of #10065 to v1.51.x.
---

buildscripts: increase PSM Security test timeout to 4h (v1.51.x backport)

---

buildscripts/kokoro/psm-security.cfg

Backport of #10065 to v1.50.x.
---

buildscripts: increase PSM Security test timeout to 4h (v1.50.x backport)

---

buildscripts/kokoro/psm-security.cfg

Backport of #10065 to v1.49.x.
---

buildscripts: increase PSM Security test timeout to 4h (v1.49.x backport)

---

buildscripts/kokoro/psm-security.cfg

Backport of #10065 to v1.48.x.
---

buildscripts: increase PSM Security test timeout to 4h (v1.48.x backport)

---

buildscripts/kokoro/psm-security.cfg

Backport of #10065 to v1.46.x.
---

buildscripts: increase PSM Security test timeout to 4h (v1.46.x backport)

---

buildscripts/kokoro/psm-security.cfg

Backport of #10065 to v1.45.x.
---

buildscripts: increase PSM Security test timeout to 4h (v1.45.x backport)

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

RetriableStream was trying to do an optimization by doing early commits when there were not going to be any further explicit retries, but it should never have been done.  This is removing the optimization and reversing the test that checked for an early commit.
Fixes #10011

retries:Remove early commit for transparent retries with none remaining.

---

buildscripts/kokoro/psm-security.cfg

Backport of #10065 to v1.47.x.
---

buildscripts: increase PSM Security test timeout to 4h (v1.47.x backport)

---

api/src/main/java/io/grpc/Detachable.java
api/src/main/java/io/grpc/HasByteBuffer.java

api: Stabilize Detachable and HasByteBuffer

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

RetriableStream was trying to do an optimization by doing early commits when there were not going to be any further explicit retries, but it should never have been done.  This is removing the optimization and reversing the test that checked for an early commit.
Fixes #10011
Backport of #10066

retries:Remove early commit for transparent retries with none remaining. (1.50.x backport)

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

RetriableStream was trying to do an optimization by doing early commits when there were not going to be any further explicit retries, but it should never have been done.  This is removing the optimization and reversing the test that checked for an early commit.
Fixes #10011
Backport of #10066

retries:Remove early commit for transparent retries with none remaining. (1.53.x backport)

---

android-interop-testing/build.gradle

This fixes the interop test on API levels 19-23

android-interop-testing: Avoid JRE Guava from Protobuf 22.3 upgrade

---

interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java

interop-testing: Start mgmt server before xds server

---

authz/src/main/java/io/grpc/authz/FileWatcherAuthorizationServerInterceptor.java

It was missed in b43ddc28
CC @ashithasantosh

authz: Add missing ExperimentalApi annotation

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

RetriableStream was trying to do an optimization by doing early commits when there were not going to be any further explicit retries, but it should never have been done.  This is removing the optimization and reversing the test that checked for an early commit.
Fixes #10011
Backport of #10066

retries:Remove early commit for transparent retries with none remaining. (1.54.x backport)

---

googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolver.java
googleapis/src/test/java/io/grpc/googleapis/GoogleCloudToProdNameResolverTest.java
xds/src/main/java/io/grpc/xds/BootstrapperImpl.java

The federation behavior has stabilized and we are ready to enable the behavior by default. The flag can still be used to disable federation.

xds,googleapis: Default GRPC_EXPERIMENTAL_XDS_FEDERATION to true

---

binder/src/androidTest/java/io/grpc/binder/BinderChannelSmokeTest.java
binder/src/main/java/io/grpc/binder/internal/BinderTransport.java

All BinderTransport transactions are oneway which means uncaught Exceptions processing them are merely logged locally and not propagated to the peer. This PR adds a top level catch block that handles the unexpected by shutting down the whole transport. This makes our peer aware of the problem immediately (instead of relying on a deadline) and gives clients a fresh transport instance to handle any retries.

Handle unexpected exceptions on binder threads

---

auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java

Previously was checking for a null value and then initializing it.  This is cleaner and lets us use a `final boolean` rather than the `Boolean` that had previously been used and caused TSAN to complain.
Fixes b/277276312

Refactor so that requiresSpecificExecutor calculation happens in constructor

---

googleapis/src/main/java/io/grpc/googleapis/GoogleCloudToProdNameResolver.java
googleapis/src/test/java/io/grpc/googleapis/GoogleCloudToProdNameResolverTest.java
xds/src/main/java/io/grpc/xds/BootstrapperImpl.java

Backport of #10093
The federation behavior has stabilized and we are ready to enable the behavior by default. The flag can still be used to disable federation

xds,googleapis: Default GRPC_EXPERIMENTAL_XDS_FEDERATION to true (1.55.x backport)

---

stub/src/main/java/io/grpc/stub/ClientCalls.java
stub/src/test/java/io/grpc/stub/ClientCallsTest.java

Add null check for responseObserver in the methods for initiating a call that take a responseObserver argument.  This insures a fail fast with a clearer cause instead of an NPE when the observer is first used.
Fixes #10064

stub: Add null check for responseObserver

---

xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java

Backport of #10091
~Under normal conditions the child LB of `ClusterImplLoadBalancer` does not fluctuate, based on the field used to configure load balancing in the xDS `Cluster` proto it is either:~
~1. `WrrLocalityLoadBalancer` if the newer `load_balancing_policy` field is used
2. `WeightedTargetLoadBalancer` if the legacy `lb_policy` field is used~
(The premise set here is off, see comment)
`ClusterImplLoadBalancer` currently assumes that this child does not change and so does not change the child LB when the name resolver sends an update. If the control plane does switch to using a different field for LB config, that update will have an LB config meant for the other child LB type. This will result in a ClassCastException and a channel panic.
To address this, `ClusterImplLoadBalancer` …

xds: Allow child of cluster_impl LB to change (1.53.x backport)

---

xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java

Backport of #10091
~Under normal conditions the child LB of `ClusterImplLoadBalancer` does not fluctuate, based on the field used to configure load balancing in the xDS `Cluster` proto it is either:~
~1. `WrrLocalityLoadBalancer` if the newer `load_balancing_policy` field is used
2. `WeightedTargetLoadBalancer` if the legacy `lb_policy` field is used~
(The premise set here is off, see comment)
`ClusterImplLoadBalancer` currently assumes that this child does not change and so does not change the child LB when the name resolver sends an update. If the control plane does switch to using a different field for LB config, that update will have an LB config meant for the other child LB type. This will result in a ClassCastException and a channel panic.
To address this, `ClusterImplLoadBalancer` …

xds: Allow child of cluster_impl LB to change (1.54.x backport)

---

xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java

Backport of #10091
Under normal conditions the child LB of `ClusterImplLoadBalancer` does not fluctuate, based on the field used to configure load balancing in the xDS `Cluster` proto it is either:
1. `WrrLocalityLoadBalancer` if the newer `load_balancing_policy` field is used
2. `WeightedTargetLoadBalancer` if the legacy `lb_policy` field is used
`ClusterImplLoadBalancer` currently assumes that this child does not change and so does not change the child LB when the name resolver sends an update. If the control plane does switch to using a different field for LB config, that update will have an LB config meant for the other child LB type. This will result in a ClassCastException and a channel panic.
To address this, `ClusterImplLoadBalancer` will now use `GracefulSwitchLoadBalancer` and …

xds: Allow child of cluster_impl LB to change (1.55.x backport)

---

protobuf/build.gradle

Backport of #9890
Looks like this link now redirects to another place and that gradle can't follow that redirect

protobuf: update external javadoc link (1.53.x backport)

---

core/src/main/java/io/grpc/internal/PickFirstLoadBalancer.java
core/src/test/java/io/grpc/internal/PickFirstLoadBalancerTest.java

When the subchannel is transitioning from TRANSIENT_FAILURE to either IDLE or CONNECTING we will not update the LB state. Additionally, if the subchannel becomes idle we request a new connection so that the subchannel will keep on trying to establish a connection.

core: Sticky TRANSIENT_FAILURE in PickFirstLoadBalancer

---

xds/src/test/java/io/grpc/xds/XdsClientImplTestBase.java

fix tsan data race b/269942507
```
Details
==================
WARNING: ThreadSanitizer: data race (pid=5874)
Read of size 8 at 0x0000cd26bec8 by thread T25:
#0 io.grpc.internal.FakeClock$2.read()J FakeClock.java:61 
#1 com.google.common.base.Stopwatch.elapsedNanos()J Stopwatch.java:222 
#2 com.google.common.base.Stopwatch.elapsed(Ljava/util/concurrent/TimeUnit;)J Stopwatch.java:239 
#3 io.grpc.xds.ControlPlaneClient$AbstractAdsStream.handleRpcStreamClosed(Lio/grpc/Status;)V ControlPlaneClient.java:339 
#4 io.grpc.xds.ControlPlaneClient$AbstractAdsStream.handleRpcError(Ljava/lang/Throwable;)V ControlPlaneClient.java:321 
#5 io.grpc.xds.ControlPlaneClient$AdsStreamV3$1$2.run()V ControlPlaneClient.java:423 
#6 io.grpc.SynchronizationContext.drain()V SynchronizationContext.java:95 
#7 …
```

xds: fix flaky xds test

---

core/src/main/java/io/grpc/internal/PickFirstLoadBalancer.java
core/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java
core/src/test/java/io/grpc/internal/PickFirstLoadBalancerProviderTest.java
core/src/test/java/io/grpc/internal/PickFirstLoadBalancerTest.java

If provided with the new PickFirstLoadBalancerConfig, PickFirstLoadBalancer will shuffle the list of addresses it receives from the name resolver.

core: Optional address shuffle in PickFirstLoadBalancer

---

xds/src/main/java/io/grpc/xds/internal/security/SecurityProtocolNegotiators.java
xds/src/test/java/io/grpc/xds/internal/security/SecurityProtocolNegotiatorsTest.java

To fix the issue in https://groups.google.com/g/grpc-io/c/KR5FCi5wD0s/m/eEtHNszmAgAJ
Backport of #10118

xds: handle the handlerRemoved callback to skip updateSslContext processing (1.55.x backport)

---

binder/src/androidTest/java/io/grpc/binder/BinderChannelSmokeTest.java

[go/bugpattern/GrpcUseClientCallBasedBlockingMethods](https://goto.google.com/bugpattern/GrpcUseClientCallBasedBlockingMethods)

binder: fix binder error prone todo

---

android/build.gradle
binder/build.gradle
buildscripts/kokoro/android.sh
buildscripts/kokoro/unix.sh
cronet/build.gradle
settings.gradle

The upgraded Android Gradle Plugin no longer played nice with the `android-maven-publish` plugin used earlier to produce Android library .aar files. No .aar files were being published at all.
This removes the android-maven-publish plugin that is no longer needed with the newer version of AGP and updates the `grpc-android`, `grpc-binder` and `grpc-cronet` to use the native Android library publishing features of AGP.
Using the `grpc-android` project as an example, before these changes the files produced by the publishing step were:
```
-rw-r--r--@ 1 tmwilson  wheel  287157 May  4 16:15 grpc-android-1.56.0-20230504.231500-1-javadoc.jar
-rw-r--r--@ 1 tmwilson  wheel      32 May  4 16:15 grpc-android-1.56.0-20230504.231500-1-javadoc.jar.md5
-rw-r--r--@ 1 tmwilson  wheel      40 May  4 16:15 …
```

android,binder,cronet: .aar file when publishing

---

binder/src/androidTest/java/io/grpc/binder/BinderChannelSmokeTest.java

The Channel-based overload can change the CallOptions to use ThreadlessExecutor, so avoids using extra threads.
CC @temawi

binder: Use Channel-based blockingUnaryCall()

---

android/build.gradle
binder/build.gradle
buildscripts/kokoro/android.sh
buildscripts/kokoro/unix.sh
cronet/build.gradle
settings.gradle

Backport of #10138
The upgraded Android Gradle Plugin no longer played nice with the `android-maven-publish` plugin used earlier to produce Android library .aar files. No .aar files were being published at all.
This removes the android-maven-publish plugin that is no longer needed with the newer version of AGP and updates the `grpc-android`, `grpc-binder` and `grpc-cronet` to use the native Android library publishing features of AGP.
Using the `grpc-android` project as an example, before these changes the files produced by the publishing step were:
```
-rw-r--r--@ 1 tmwilson  wheel  287157 May  4 16:15 grpc-android-1.56.0-20230504.231500-1-javadoc.jar
-rw-r--r--@ 1 tmwilson  wheel      32 May  4 16:15 grpc-android-1.56.0-20230504.231500-1-javadoc.jar.md5
-rw-r--r--@ 1 tmwilson  wheel …
```

android,binder,cronet: .aar file when publishing (1.55.x backport)

---

api/src/main/java/io/grpc/Status.java
api/src/test/java/io/grpc/StatusTest.java

api: Fix boundary check in Status.fromCodeValue()

---

core/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

ReadyPicker hasn't been necessary since 111ff60e, when we stopped calling super.pickSubchannel(). EmptyPicker was only used in tests, and we can just compare the class name instead of doing an instanceof check.
Unfortunately, calling getClass() caused Java to start casting the return value of pickerCaptor.getValue() based on its generics. Captors don't verify the type they capture, so using any type other than SubchannelPicker for the pickerCaptor is misleading and hides a cast.

core: Hide RR's ReadyPicker and EmptyPicker

---

authz/src/test/java/io/grpc/authz/AuthorizationEnd2EndTest.java
benchmarks/src/main/java/io/grpc/benchmarks/driver/LoadServer.java
benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncServer.java
interop-testing/src/main/java/io/grpc/testing/integration/StressTestClient.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceServer.java
interop-testing/src/test/java/io/grpc/testing/integration/ConcurrencyTest.java
interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyTest.java
interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
interop-testing/src/test/java/io/grpc/testing/integration/Http2Test.java
netty/shaded/src/testShadow/java/io/grpc/netty/shaded/ShadingTest.java
netty/src/test/java/io/grpc/netty/AdvancedTlsTest.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpChannelBuilderTest.java
testing/src/main/java/io/grpc/internal/testing/TestUtils.java
xds/src/test/java/io/grpc/xds/internal/security/CommonTlsContextTestsUtil.java
xds/src/test/java/io/grpc/xds/internal/security/trust/XdsTrustManagerFactoryTest.java
xds/src/test/java/io/grpc/xds/internal/security/trust/XdsX509TrustManagerTest.java

TlsTesting.loadCert() is a public API and so should be preferred over our internal utility. It avoids creating a temp file that has to be deleted by a shutdown hook. Usages that needed a file were not migrated.

Migrate many usages of TestUtils.loadCert() to the public TlsTesting

---

core/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java
core/src/main/java/io/grpc/util/OutlierDetectionLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/ClusterResolverLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/PriorityLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/RingHashLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancerProvider.java

LoadBalancers in general should never throw, but
parseLoadBalancingConfig() in particular has a return value to communicate the error. Throwing can be a bit unpredictable, but at its most trivial form causes a channel panic. There's no reason to throw explicitly and calls to JsonUtil have to be protected by a try-catch because it can throw.

Fix throwing LBProvider.parseLoadBalancingConfig() impls

---

build.gradle

This removes the need to specify dependsOn explicitly, because the task input carries the dependency.

build.gradle: Use proto task output instead of hard-coding path

---

build.gradle

CC @sergiitk 
Example output (after some upgrades that I have queued, so the list is smaller):
```
> Task :checkForUpdates
com.puppycrawl.tools:checkstyle 8.28 -> 10.10.0
com.google.errorprone:error_prone_core 2.10.0 -> 2.18.0
com.google.auth:google-auth-library-credentials 1.4.0 -> 1.16.1
com.google.auth:google-auth-library-oauth2-http 1.4.0 -> 1.16.1
com.google.guava:guava 31.1-android -> 31.1-jre
com.google.guava:guava-testlib 31.1-android -> 31.1-jre
org.mockito:mockito-android 3.12.4 -> 5.3.1
org.mockito:mockito-core 3.12.4 -> 5.3.1
io.netty:netty-codec-http2 4.1.87.Final -> 4.1.92.Final
io.netty:netty-handler-proxy 4.1.87.Final -> 4.1.92.Final
io.netty:netty-tcnative-boringssl-static 2.0.56.Final -> 2.0.61.Final
io.netty:netty-tcnative-classes 2.0.56.Final -> 2.0.61.Final …
```

build.gradle: Add checkForUpdates task

---

alts/build.gradle
build.gradle
googleapis/build.gradle
netty/shaded/build.gradle
xds/build.gradle

The pinning is unreliable in Maven and ignored by Gradle. I'm not at all convinced that we are pinning/not pinning in appropriate projects. The pinning also serves less of a purpose since we started encouraging the BOM and grpc-netty-shaded. Netty's HTTP/2 API has also become somewhat stable compared to its earlier history. If we notice an up-tick in version skew, we can reinstate it.
The pinning is annoying in the build.gradle code and causes Maven/Gradle to download the version list once a day, which can be troublesome to users unaware of how to tell the tools to work offline.
It also opens our users to platform issues like seen in #10043 and #10086 where Maven Central's version list was incorrectly generated. Or like #9664 where Gradle Plugin's repository caches packages from JCenter …

gradle: Remove version pinning from POMs

---

buildscripts/xds-k8s/test-client.Dockerfile
buildscripts/xds-k8s/test-server.Dockerfile

xds interop: Update Docker images to `eclipse-temurin:11-jre`

---

examples/example-hostname/README.md

The command has been wrong since it was introduced. The hostname-server comes from the applicationName, which hasn't changed.
Addresses #10169

examples: Fix hostname binary name in README

---

buildscripts/xds-k8s/test-client.Dockerfile
buildscripts/xds-k8s/test-server.Dockerfile

Backport of #10172 to v1.54.x.
---

xds interop: Update Docker images to `eclipse-temurin:11-jre` (v1.54.x backport)

---

buildscripts/xds-k8s/test-client.Dockerfile
buildscripts/xds-k8s/test-server.Dockerfile

Backport of #10172 to v1.50.x.
---

xds interop: Update Docker images to `eclipse-temurin:11-jre` (v1.50.x backport)

---

buildscripts/xds-k8s/test-client.Dockerfile
buildscripts/xds-k8s/test-server.Dockerfile

Backport of #10172 to v1.53.x.
---

xds interop: Update Docker images to `eclipse-temurin:11-jre` (v1.53.x backport)

---

buildscripts/xds-k8s/test-client.Dockerfile
buildscripts/xds-k8s/test-server.Dockerfile

Backport of #10172 to v1.51.x.
---

xds interop: Update Docker images to `eclipse-temurin:11-jre` (v1.51.x backport)

---

repositories.bzl
xds/BUILD.bazel
xds/src/main/java/io/grpc/xds/LoadBalancerConfigFactory.java
xds/src/main/java/io/grpc/xds/XdsClusterResource.java
xds/src/main/java/io/grpc/xds/XdsResourceType.java
xds/src/test/java/io/grpc/xds/LoadBalancerConfigFactoryTest.java

Configure `pick_first` load balancing if the xDS `PickFirst` LB config message is specified in the load balancing config for `Cluster`

xds: pick_first LB configuration

---

protobuf/build.gradle

Backport of #9890 to v1.52.x.
---

protobuf: update external javadoc link (v1.52.x backport)

---

protobuf/build.gradle

Backport of #9890 to v1.47.x.
---

protobuf: update external javadoc link (v1.47.x backport)

---

protobuf/build.gradle

Backport of #9890 to v1.48.x.
---

protobuf: update external javadoc link (v1.48.x backport)

---

protobuf/build.gradle

Backport of #9890 to v1.49.x.
---

protobuf: update external javadoc link (v1.49.x backport)

---

protobuf/build.gradle

Backport of #9890 to v1.46.x.
---

protobuf: update external javadoc link (v1.46.x backport)

---

buildscripts/xds-k8s/test-client.Dockerfile
buildscripts/xds-k8s/test-server.Dockerfile

Backport of #10172 to v1.52.x.
---

xds interop: Update Docker images to `eclipse-temurin:11-jre` (v1.52.x backport)

---

buildscripts/xds-k8s/test-client.Dockerfile
buildscripts/xds-k8s/test-server.Dockerfile

Backport of #10172 to v1.48.x.
---

xds interop: Update Docker images to `eclipse-temurin:11-jre` (v1.48.x backport)

---

buildscripts/xds-k8s/test-client.Dockerfile
buildscripts/xds-k8s/test-server.Dockerfile

Backport of #10172 to v1.46.x.
---

xds interop: Update Docker images to `eclipse-temurin:11-jre` (v1.46.x backport)

---

cronet/src/test/java/io/grpc/cronet/CronetClientStreamTest.java
cronet/src/test/java/io/grpc/cronet/CronetClientTransportTest.java

It is forbidden internally. Error message:
Mocking types which have complex contracts or are easy to construct by other means is forbidden:
'executor' is mocking 'interface java.util.concurrent.Executor'. Use a real executor. Mocks of Executor don't execute submitted tasks at all, which leads to suppressed errors, deadlocks, and brittle tests..

test: stop mocking Executor.

---

buildscripts/xds-k8s/test-client.Dockerfile
buildscripts/xds-k8s/test-server.Dockerfile

Backport of #10172 to v1.49.x.
---

xds interop: Update Docker images to `eclipse-temurin:11-jre` (v1.49.x backport)

---

buildscripts/xds-k8s/test-client.Dockerfile
buildscripts/xds-k8s/test-server.Dockerfile

Backport of #10172 to v1.47.x.
---

xds interop: Update Docker images to `eclipse-temurin:11-jre` (v1.47.x backport)

---

testing-proto/src/test/java/io/grpc/testing/protobuf/SimpleServiceTest.java

This fixes the warning during the test run:
```
warning: No SupportedSourceVersion annotation found on io.grpc.testing.protobuf.SimpleServiceTest$AnnotationProcessor, returning RELEASE_6.
warning: Supported source version 'RELEASE_6' from annotation processor 'io.grpc.testing.protobuf.SimpleServiceTest$AnnotationProcessor' less than -source '1.8'
```
Note: authored by @cushon (cl/532476479)

testing-proto: Define supported SourceVersion in annotation test

---

api/src/main/java/io/grpc/CallCredentials.java
api/src/main/java/io/grpc/CompositeCallCredentials.java
api/src/test/java/io/grpc/CompositeCallCredentialsTest.java
auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java
core/src/test/java/io/grpc/internal/FakeCallCredentials.java

Removes the `@ExperimentalApi` annotation from the class and provides an empty implementation for the `thisUsesUnstableApi()` method.

api: Stabilize io.grpc.CallCredentials

---

api/src/main/java/io/grpc/CallCredentials.java

The `thisUsesUnstableApi()` method was earlier deprecated and the `@ExperimentalApi` annotation removed. Adding `@ExperimentalApi` back to make it clear that this method can (and will) later be removed.

api: Experimental CallCredentials.thisUsesUnstableApi()

---

core/src/test/java/io/grpc/inprocess/InProcessClientTransportFactoryTest.java
core/src/test/java/io/grpc/internal/ClientCallImplTest.java
core/src/test/java/io/grpc/internal/DelayedStreamTest.java
core/src/test/java/io/grpc/internal/ServerCallImplTest.java
core/src/test/java/io/grpc/internal/ServerImplTest.java
core/src/testFixtures/java/io/grpc/internal/AbstractClientTransportFactoryTest.java
core/src/testFixtures/java/io/grpc/internal/SingleMessageProducer.java
netty/src/test/java/io/grpc/netty/NettyClientTransportFactoryTest.java
okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportFactoryTest.java

These two classes are precisely the purpose of test fixtures. Move them close to the classes they make easier to use in tests.

testing: Move some internal classes to testFixtures

---

interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceServer.java
interop-testing/src/test/java/io/grpc/testing/integration/Http2OkHttpTest.java
interop-testing/src/test/java/io/grpc/testing/integration/Http2Test.java
netty/src/test/java/io/grpc/netty/NettyClientTransportTest.java
netty/src/test/java/io/grpc/netty/ProtocolNegotiatorsTest.java
testing/src/main/java/io/grpc/internal/testing/TestUtils.java

Ciphers have been "fast enough" for testing since early Java 8 updates; we haven't needed to override ciphers since we dropped Java 7 support. Java 8u252 had ALPN, so Conscrypt or Jetty ALPN hasn't been necessary for basic testing for a while. We still want specialized testing for Conscrypt, but only tests testing Conscrypt need to care.

Remove old Java 7/8 TLS testing workarounds

---

repositories.bzl

The previous syntax for just adding your own keys doesn't seem to work, but was similar to the approach of using `dict(d, foo=bar)`. You can't have '.' and ':' in a key that way though. The doc was written before Bazel 1.0 and in newer Bazel versions you can just use | to concatenate.
Fixes #10203
CC @aryeh-looker

repositories.bzl: In doc, use | to combine dicts

---

interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java

This is a Java analogue of a C++ PR from a while ago: https://github.com/grpc/grpc/pull/18156/files
Also created a Go PR in https://github.com/grpc/grpc-go/pull/6295 to do the same thing.
This flag will be useful for some RLS integration tests where we need to have the client set certain headers for routing purposes.
cc @temawi @ejona86

interop client: introduce --additional_metadata flag to let client optionally send extra metadata

---

core/src/main/java/io/grpc/internal/JsonUtil.java
core/src/test/java/io/grpc/internal/JsonUtilTest.java
repositories.bzl
services/src/main/java/io/grpc/services/CallMetricRecorder.java
services/src/main/java/io/grpc/services/InternalCallMetricRecorder.java
services/src/main/java/io/grpc/services/MetricRecorder.java
services/src/main/java/io/grpc/services/MetricRecorderHelper.java
services/src/main/java/io/grpc/services/MetricReport.java
services/src/test/java/io/grpc/services/CallMetricRecorderTest.java
xds/src/main/java/io/grpc/xds/LoadBalancerConfigFactory.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancerProvider.java
xds/src/main/java/io/grpc/xds/orca/OrcaMetricReportingServerInterceptor.java
xds/src/main/java/io/grpc/xds/orca/OrcaPerRequestUtil.java
xds/src/main/java/io/grpc/xds/orca/OrcaServiceImpl.java
xds/src/test/java/io/grpc/xds/LoadBalancerConfigFactoryTest.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerProviderTest.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/XdsClientImplDataTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaMetricReportingServerInterceptorTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaPerRequestUtilTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaServiceImplTest.java

Design: go/wrr-eps-design-review-slides
Uses: #10160
Tested: updated & ran tests 100 times to ensure they are not flaky

services, xds, orca: support EPS in client-side WRR

---

examples/src/main/java/io/grpc/examples/manualflowcontrol/README.md

Moved from the generic user guide on flow control.

Add a java specific description of manual flow control to the example.

---

buildscripts/observability-test/Dockerfile

Sergii noticed that the GCP Observability Integration testing docker image in the `microsvcs-testing` project popped up on the vulnerabilities dashboard. So we need to fix which base docker image we use. Similar to the fix in #10191

gcp observability: Update Docker images to eclipse-temurin

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

The same change in core: https://github.com/grpc/grpc/pull/33222.

buildscripts, psm interop: Don't fail target if sub-target already failed

---

api/src/main/java/io/grpc/ManagedChannelBuilder.java

api: stabilize ManagedChannelBuilder.useTransportSecurity

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #10232 to v1.56.x.
---

buildscripts, psm interop: Don't fail target if sub-target already failed (v1.56.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #10232 to v1.55.x.
---

buildscripts, psm interop: Don't fail target if sub-target already failed (v1.55.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #10232 to v1.54.x.
---

buildscripts, psm interop: Don't fail target if sub-target already failed (v1.54.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #10232 to v1.51.x.
---

buildscripts, psm interop: Don't fail target if sub-target already failed (v1.51.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #10232 to v1.52.x.
---

buildscripts, psm interop: Don't fail target if sub-target already failed (v1.52.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #10232 to v1.50.x.
---

buildscripts, psm interop: Don't fail target if sub-target already failed (v1.50.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #10232 to v1.49.x.
---

buildscripts, psm interop: Don't fail target if sub-target already failed (v1.49.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #10232 to v1.47.x.
---

buildscripts, psm interop: Don't fail target if sub-target already failed (v1.47.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #10232 to v1.53.x.
---

buildscripts, psm interop: Don't fail target if sub-target already failed (v1.53.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh

Backport of #10232 to v1.48.x.
---

buildscripts, psm interop: Don't fail target if sub-target already failed (v1.48.x backport)

---

xds/src/main/java/io/grpc/xds/XdsResourceType.java
xds/src/test/java/io/grpc/xds/XdsClientImplDataTest.java

As requested by Eric in thread: https://chat.google.com/room/AAAAbkw9L3c/HzqpO0OaYlQ

Flip default for RLS on XDS being enabled to true.

---

xds/src/main/java/io/grpc/xds/XdsResourceType.java
xds/src/test/java/io/grpc/xds/XdsClientImplDataTest.java

As requested by Eric in thread: https://chat.google.com/room/AAAAbkw9L3c/HzqpO0OaYlQ
Backport of #10248

Flip default for RLS on XDS being enabled to true. (1.56.x backport)

---

interop-testing/src/main/java/io/grpc/testing/integration/XdsTestClient.java
interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java
xds/src/test/java/io/grpc/xds/ControlPlaneRule.java

These code locations just needed a generic gRPC server, without any transport-specific configuration. Use vanilla ManagedServerBuilder instead of hard-coding to Netty, as we would suggest to our users.

Avoid NettyServerBuilder when unnecessary

---

repositories.bzl
services/src/main/java/io/grpc/services/CallMetricRecorder.java
services/src/main/java/io/grpc/services/InternalCallMetricRecorder.java
services/src/main/java/io/grpc/services/MetricRecorder.java
services/src/main/java/io/grpc/services/MetricRecorderHelper.java
services/src/main/java/io/grpc/services/MetricReport.java
services/src/test/java/io/grpc/services/CallMetricRecorderTest.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/main/java/io/grpc/xds/orca/OrcaMetricReportingServerInterceptor.java
xds/src/main/java/io/grpc/xds/orca/OrcaPerRequestUtil.java
xds/src/main/java/io/grpc/xds/orca/OrcaServiceImpl.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaMetricReportingServerInterceptorTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaPerRequestUtilTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaServiceImplTest.java
xds/third_party/xds/import.sh
xds/third_party/xds/src/main/proto/xds/data/orca/v3/orca_load_report.proto

* Import cncf/xds: original cl/538546518
* Add new APIs to `CallMetricRecorder` and `MetricRecorder` for `application_utilization`
* Use `application_utilization` and fallback to `cpu_utilization` if unset for client-side WRR

services, xds, orca: use application_utilization and fallback to cpu_utilization if unset in WRR, import cncf/xds

---

buildscripts/grpc-java-artifacts/Dockerfile

Download Maven from Maven Central

---

buildscripts/grpc-java-artifacts/Dockerfile

Download Maven from Maven Central (1.56.x backport)

---

buildscripts/grpc-java-artifacts/Dockerfile

Download Maven from Maven Central (1.53.x backport)

---

buildscripts/grpc-java-artifacts/Dockerfile

Download Maven from Maven Central (1.52.x backport)

---

buildscripts/grpc-java-artifacts/Dockerfile

Download Maven from Maven Central (1.55.x backport)

---

buildscripts/grpc-java-artifacts/Dockerfile

Download Maven from Maven Central (1.51.x backport)

---

buildscripts/grpc-java-artifacts/Dockerfile

Download Maven from Maven Central (1.50.x backport)

---

buildscripts/grpc-java-artifacts/Dockerfile

Download Maven from Maven Central (1.49.x backport)

---

buildscripts/grpc-java-artifacts/Dockerfile

Download Maven from Maven Central (1.48.x backport)

---

buildscripts/grpc-java-artifacts/Dockerfile

Download Maven from Maven Central (1.45.x backport)

---

repositories.bzl
services/src/main/java/io/grpc/services/CallMetricRecorder.java
services/src/main/java/io/grpc/services/InternalCallMetricRecorder.java
services/src/main/java/io/grpc/services/MetricRecorder.java
services/src/main/java/io/grpc/services/MetricRecorderHelper.java
services/src/main/java/io/grpc/services/MetricReport.java
services/src/test/java/io/grpc/services/CallMetricRecorderTest.java
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/main/java/io/grpc/xds/orca/OrcaMetricReportingServerInterceptor.java
xds/src/main/java/io/grpc/xds/orca/OrcaPerRequestUtil.java
xds/src/main/java/io/grpc/xds/orca/OrcaServiceImpl.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaMetricReportingServerInterceptorTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaPerRequestUtilTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaServiceImplTest.java
xds/third_party/xds/import.sh
xds/third_party/xds/src/main/proto/xds/data/orca/v3/orca_load_report.proto

Backport of #10256 to v1.56.x
PR created via `git cherry-pick 1daf0ff720ebc9b9c466a2c608e186d88644a572`

services, xds, orca: use application_utilization and fallback to cpu_utilization if unset in WRR, import cncf/xds (v1.56.x backport)

---

build.gradle
examples/example-debug/pom.xml
examples/example-hostname/pom.xml
examples/pom.xml
gcp-observability/build.gradle
gradle/libs.versions.toml
repositories.bzl
services/build.gradle

Update guava dependency to address CVE-2023-2976

---

netty/src/main/java/io/grpc/netty/SendGrpcFrameCommand.java

DefaultByteBufHolder has many perfectly good implementations. It should be enought to implement the replace method.

netty: simplify SendGrpcFrameCommand

---

okhttp/src/test/java/io/grpc/okhttp/OkHttpServerTransportTest.java

The PipeSocket was convenient and avoided real I/O, but the
shutdown/close while connecting/handshaking tests were triggering a
Socket bug in Java (https://bugs.openjdk.org/browse/JDK-8278326). Using
a real socket doesn't trigger the bug because the test stops sharing
state with the code under test.
Fixes #10228
```
Details
==================
WARNING: ThreadSanitizer: data race (pid=4528)
Write of size 1 at 0x0000cfb9d5f4 by thread T36 (mutexes: write M0):
#0 java.net.Socket.setCreated()V Socket.java:687
#1 java.net.AbstractPlainSocketImpl.create(Z)V AbstractPlainSocketImpl.java:149
#2 java.net.Socket.createImpl(Z)V Socket.java:477
#3 java.net.Socket.getImpl()Ljava/net/SocketImpl; Socket.java:540
#4 java.net.Socket.setTcpNoDelay(Z)V Socket.java:998
#5 …
```

okhttp: Use a real socket during server transport testing

---

xds/src/main/java/io/grpc/xds/CdsLoadBalancer2.java
xds/src/test/java/io/grpc/xds/CdsLoadBalancer2Test.java

For duplicate children, just ignore them
For loops, Put the channels into TRANSIENT_FAILURE like when no edge policy is provided
Note, to handle loop detection being done after state objects are created, I updated FakeXdsClient watcher map value to be a collection (as is true for XdsClientImpl).
Fixes go/grpc-lb-xds-tracker row 22 (not tracked as an issue)

Handle Aggregate cluster loops and dups

---

buildscripts/sonatype-upload.sh

This is a simpler alternative to #7305. I tested it by uploading a SNAPSHOT version, which fails.

buildscripts: Fail sonatype-upload for non-200 HTTP status code

---

xds/src/test/java/io/grpc/xds/FakeControlPlaneXdsIntegrationTest.java

This is now the preferred way to specify rule execution order.

xds: Use Rule order instead of RuleChain

---

core/src/main/java/io/grpc/internal/RetriableStream.java
core/src/test/java/io/grpc/internal/RetriableStreamTest.java

Change delay for hedging retry after a non-fatal error to be 0 to match gRFC A6

---

okhttp/src/main/java/io/grpc/okhttp/OkHttpServerTransport.java

The original TSAN data race described in #10228 was fixed by rewriting a test case that used a PipeSocket which triggered a bug in Java's Socket as described in #10281. Doing so uncovered the "original" data race bug: #10284.

okhttp: tsan socket data race bug fix

---

buildscripts/kokoro/xds_url_map.sh

The same change in core: https://github.com/grpc/grpc/pull/33520.

buildscripts, psm interop: Don't fail url_map target if sub-target already failed

---

buildscripts/qemu_helpers/prepare_qemu.sh

Apparently our Kokoro image has this done already, and my laptop as well. But the newer Kokoro image and other computers like my desktop don't have it already.

buildscripts: Fix prepare_qemu to not assume system already has emulation

---

alts/build.gradle
android/build.gradle
api/build.gradle
authz/build.gradle
binder/build.gradle
context/build.gradle
core/build.gradle
cronet/build.gradle
testing/build.gradle
xds/build.gradle

Since 44847bf4e, when we upgraded our JUnit version, the JUnit exclusions have probably not been necessary. e0ac97c4f upgraded Robolectric to a version that had the auto.service problem fixed.

Remove unneeded dependency excludes

---

buildscripts/kokoro/xds_url_map.sh

Backport of #10295 to v1.56.x.
---

buildscripts, psm interop: Don't fail url_map target if sub-target already failed (v1.56.x backport)

---

buildscripts/kokoro/xds_url_map.sh

Backport of #10295 to v1.55.x.
---

buildscripts, psm interop: Don't fail url_map target if sub-target already failed (v1.55.x backport)

---

buildscripts/kokoro/xds_url_map.sh

Backport of #10295 to v1.51.x.
---

buildscripts, psm interop: Don't fail url_map target if sub-target already failed (v1.51.x backport)

---

buildscripts/kokoro/xds_url_map.sh

Backport of #10295 to v1.53.x.
---

buildscripts, psm interop: Don't fail url_map target if sub-target already failed (v1.53.x backport)

---

buildscripts/kokoro/xds_url_map.sh

Backport of #10295 to v1.50.x.
---

buildscripts, psm interop: Don't fail url_map target if sub-target already failed (v1.50.x backport)

---

buildscripts/kokoro/xds_url_map.sh

Backport of #10295 to v1.48.x.
---

buildscripts, psm interop: Don't fail url_map target if sub-target already failed (v1.48.x backport)

---

buildscripts/kokoro/xds_url_map.sh

Backport of #10295 to v1.49.x.
---

buildscripts, psm interop: Don't fail url_map target if sub-target already failed (v1.49.x backport)

---

xds/build.gradle

Plumbing through sourceSet lets cross-project dependencies work the same way as artifacts published to Maven. This fixes an issue for interop-testing where build/install would include all the raw files from thirdparty in addition to the grpc-xds.jar. For example: build/install/grpc-interop-testing/lib/com/github/xds/data/orca/v3/OrcaLoadReport$1.class
b/288577812
CC @sergiitk, @sanjaypujare

xds: Plumb thirdparty classes through sourceSet instead of jar

---

android-interop-testing/build.gradle
binder/build.gradle
build.gradle
buildscripts/grpc-java-artifacts/Dockerfile
buildscripts/kokoro/android-interop.sh
buildscripts/kokoro/android.sh
buildscripts/kokoro/linux_artifacts.sh
buildscripts/kokoro/unix.sh

Note that this changes the JDK used to compile releases to Java 11. That should only impact the appearance of the Javadoc.
This adds the Android SDK to the build container, removing the dependency on the Android SDK being available on the CI host. This allows running on newer Kokoro images. 'Android' and 'Android interop' CIs still depend on the Android SDK being available on the host, but since they aren't used as part of the release process, they can more easily migrate off Kokoro as part of future work.
This also causes Android components to now be built with -Werror, as we use -PfailOnWarnings=true in unix.sh but were missing it from the Android build invocations.
Gradle will auto-download the necessary version of build-tools. We don't want to download it ourselves because the version …

buildscripts: Build Android with main build in linux_artifacts

---

api/src/main/java/io/grpc/Status.java

This stabilizes:
- Status.asRuntimeException(Metadata)
- Status.trailersFromThrowable(Throwable)

api: Stabilize two io.grpc.Status methods

---

android-interop-testing/src/generated/debug/grpc/io/grpc/testing/integration/LoadBalancerStatsServiceGrpc.java
android-interop-testing/src/generated/debug/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
android-interop-testing/src/generated/debug/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
android-interop-testing/src/generated/debug/grpc/io/grpc/testing/integration/TestServiceGrpc.java
android-interop-testing/src/generated/debug/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
android-interop-testing/src/generated/debug/grpc/io/grpc/testing/integration/XdsUpdateClientConfigureServiceGrpc.java
android-interop-testing/src/generated/debug/grpc/io/grpc/testing/integration/XdsUpdateHealthServiceGrpc.java
android-interop-testing/src/generated/release/grpc/io/grpc/testing/integration/LoadBalancerStatsServiceGrpc.java
android-interop-testing/src/generated/release/grpc/io/grpc/testing/integration/MetricsServiceGrpc.java
android-interop-testing/src/generated/release/grpc/io/grpc/testing/integration/ReconnectServiceGrpc.java
android-interop-testing/src/generated/release/grpc/io/grpc/testing/integration/TestServiceGrpc.java
android-interop-testing/src/generated/release/grpc/io/grpc/testing/integration/UnimplementedServiceGrpc.java
android-interop-testing/src/generated/release/grpc/io/grpc/testing/integration/XdsUpdateClientConfigureServiceGrpc.java
android-interop-testing/src/generated/release/grpc/io/grpc/testing/integration/XdsUpdateHealthServiceGrpc.java

3808e707 (#10321) fixed references of String to be java.lang.String, but failed to update the Android build.
CC @pkwarren

Rebuild Android generated code for java.lang.String

---

build.gradle

This has been fixed in the Protobuf Gradle Plugin since probably 0.8.13.

Remove old Protobuf Gradle Plugin caching workaround

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplGetNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

`ManagedChannelImpl` did not make sure to use a `RetryingNameResolver` if authority was not overriden. This was not a problem for DNS name resolution as the DNS name resolver factory explicitly returns a `RetryingNameResolver`. For polling name resolvers that do not do this in their factories (like the grpclb name resolver) this meant not having retry at all.
b/289123469

core: ManagedChannelImpl to always use RetryingNameResolver

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplGetNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

Backport of #10328
`ManagedChannelImpl` did not make sure to use a `RetryingNameResolver` if authority was not overriden. This was not a problem for DNS name resolution as the DNS name resolver factory explicitly returns a `RetryingNameResolver`. For polling name resolvers that do not do this in their factories (like the grpclb name resolver) this meant not having retry at all.
b/289123469

core: ManagedChannelImpl to always use RetryingNameResolver (1.54.x backport)

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplGetNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

Backport of #10328
`ManagedChannelImpl` did not make sure to use a `RetryingNameResolver` if authority was not overriden. This was not a problem for DNS name resolution as the DNS name resolver factory explicitly returns a `RetryingNameResolver`. For polling name resolvers that do not do this in their factories (like the grpclb name resolver) this meant not having retry at all.
b/289123469

core: ManagedChannelImpl to always use RetryingNameResolver (1.55.x backport)

---

core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/ManagedChannelImplGetNameResolverTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplTest.java

Backport of #10328
`ManagedChannelImpl` did not make sure to use a `RetryingNameResolver` if authority was not overriden. This was not a problem for DNS name resolution as the DNS name resolver factory explicitly returns a `RetryingNameResolver`. For polling name resolvers that do not do this in their factories (like the grpclb name resolver) this meant not having retry at all.
b/289123469

core: ManagedChannelImpl to always use RetryingNameResolver (1.56.x backport)

---

README.md
build.gradle
compiler/src/test/golden/TestDeprecatedService.java.txt
compiler/src/test/golden/TestService.java.txt
compiler/src/testLite/golden/TestDeprecatedService.java.txt
compiler/src/testLite/golden/TestService.java.txt
core/src/main/java/io/grpc/internal/GrpcUtil.java
examples/android/clientcache/app/build.gradle
examples/android/helloworld/app/build.gradle
examples/android/routeguide/app/build.gradle
examples/android/strictmode/app/build.gradle
examples/build.gradle
examples/example-alts/build.gradle
examples/example-debug/build.gradle
examples/example-debug/pom.xml
examples/example-gauth/build.gradle
examples/example-gauth/pom.xml
examples/example-gcp-observability/build.gradle
examples/example-hostname/build.gradle
examples/example-hostname/pom.xml
examples/example-jwt-auth/build.gradle
examples/example-jwt-auth/pom.xml
examples/example-orca/build.gradle
examples/example-reflection/build.gradle
examples/example-servlet/build.gradle
examples/example-tls/build.gradle
examples/example-tls/pom.xml
examples/example-xds/build.gradle
examples/pom.xml

CC @temawi 
(The 1.55.2 release commits were accidentally squashed into the branch. So they are useless for the release. 1.55.3 will take its place.)

Release 1.55.3

---

buildscripts/grpc-java-artifacts/Dockerfile

This backport wasn't done earlier because the diff didn't apply cleanly (it had a different download URL already). But it is now needed in #10301.
CC @XuanWang-Amos @sergiitk

Download Maven from Maven Central (v1.47.x backport)

---

buildscripts/kokoro/xds_url_map.sh

Backport of #10295 to v1.47.x.
---

buildscripts, psm interop: Don't fail url_map target if sub-target already failed (v1.47.x backport)

---

core/src/main/java/io/grpc/util/MutableHandlerRegistry.java

core: stabilize MutableHandlerRegistry by removing ExperimentalApi annotation

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

Backport of #9347 to v1.47.x.
---
https://github.com/grpc/grpc-java/pull/9269 probably pushed the build
b/238334438
CC @sergiitk

xds: Allow Gradle to use more memory when building interop (v1.47.x backport)

---

buildscripts/kokoro/psm-security.sh
buildscripts/kokoro/xds_k8s_lb.sh
buildscripts/kokoro/xds_url_map.sh

Backport of #9347 to v1.48.x.
---
https://github.com/grpc/grpc-java/pull/9269 probably pushed the build
b/238334438
CC @sergiitk

xds: Allow Gradle to use more memory when building interop (v1.48.x backport)

---

.vscode/settings.json
xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

The core of the Weighted Round Robin load balancer policy on the client side is a stride scheduler originally implemented by an [EDFScheduler](http://google3/net/rpc2/edf_scheduler.h;rcl=438515966). However, the mutex lock required by the EDFScheduler has been a frequent source of thread contention at high request rates and a block on other cost saving efforts.
The Static Stride Scheduler is a generator of a practically equivalent sequence of picks as EDFScheduler. It removes the need for a priority queue (and thus a lock) and improves latency at high request rates. 
[go/static-stride-scheduler](https://g3doc.corp.google.com/production/rpc/stubs/g3doc/loadbalancing/static_stride_scheduler.md?cl=head)

implemented and tested static stride scheduler for weighted round robin load balancing policy

---

core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
grpclb/src/main/java/io/grpc/grpclb/SecretGrpclbNameResolverProvider.java

Motivation:
When multiple NameResolvers are created, the Classloader is scanned every time trying to figure out if the Platform is Android. This expensive work could be done only once.
Modification:
Cache isAndroid resolution in a constant.
Result:
Less expensive multiple NameResolvers instantiation.

core,grpclb: Resolve isAndroid only once on class loading

---

build.gradle

Instead of assignment, it now seems to be a FileCollection that you modify. This has probably been broken since f458f22.
```
> Could not create task ':grpc-auth:japicmp'.
> Cannot set the value of read-only property 'oldClasspath' for task ':grpc-auth:japicmp' of type me.champeau.gradle.japicmp.JapicmpTask.
```
The change works with or without the files(), but the conversion is just not needed anymore as it is handled by FileCollection.

build.gradle: Avoid assignment to japicmp configuration

---

RELEASING.md

I moved items that could be done immediately after the release up into the main release flow. I also stripped some outdated or unnecessary text to make it quicker to follow.
-----
I'll add "upgrade dependencies" at the very, very end, but I felt I needed to clean up all the random stuff at the end of the process to make it more visible. This change also might reduce chances something is forgotten, because we do more up-front.

RELEASING.md: Reorder contents to make it a bit more streamlined

---

api/src/main/java/io/grpc/ClientInterceptors.java

`StatusException` thrown from `checkedStart()` may have `trailers`. Therefore, `CheckedForwardingClientCall` should pass the `trailers` to `responseListener.onClose()`.

CheckedForwardingClientCall should pass trailers from the caught exception

---

services/src/main/java/io/grpc/services/CallMetricRecorder.java
services/src/main/java/io/grpc/services/InternalCallMetricRecorder.java
services/src/main/java/io/grpc/services/MetricRecorder.java
services/src/main/java/io/grpc/services/MetricReport.java
services/src/test/java/io/grpc/services/CallMetricRecorderTest.java
xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java
xds/src/main/java/io/grpc/xds/LoadReportClient.java
xds/src/main/java/io/grpc/xds/LoadStatsManager2.java
xds/src/main/java/io/grpc/xds/Stats.java
xds/src/main/java/io/grpc/xds/orca/OrcaMetricReportingServerInterceptor.java
xds/src/main/java/io/grpc/xds/orca/OrcaPerRequestUtil.java
xds/src/test/java/io/grpc/xds/ClusterImplLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/LoadReportClientTest.java
xds/src/test/java/io/grpc/xds/LoadStatsManager2Test.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaMetricReportingServerInterceptorTest.java
xds/src/test/java/io/grpc/xds/orca/OrcaPerRequestUtilTest.java

Design: 
* go/grpc-xds-lrs-named-metrics 
* go/lrs-named-metrics-design-review-slides
* Implements https://github.com/grpc/proposal/blob/master/A64-lrs-custom-metrics.md

services, xds, orca: LRS named metrics support

---

core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/DnsNameResolverProviderTest.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/ServiceConfigErrorHandlingTest.java

Wrapping the `DnsNameResolver` in `DnsNameResolverProvider` can cause problems to external name resolvers that delegate to a `DnsResolver` already wrapped in a `RetryingNameResolver`.
`ManagedChannelImpl` would end up wrapping these name resolvers again, causing an exception later from a `RetryingNameResolver` safeguard that checks for double wrapping.
This removes the wrapping logic from `DnsNameResolverProvider` and has `ManagedChannelImpl` always explicitly do it.

core: Apply RetryingNameResolver in ManagedChannelImpl

---

core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/DnsNameResolverProviderTest.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/ServiceConfigErrorHandlingTest.java

Backport of #10371
Wrapping the `DnsNameResolver` in `DnsNameResolverProvider` can cause problems to external name resolvers that delegate to a `DnsResolver` already wrapped in a `RetryingNameResolver`.
`ManagedChannelImpl` would end up wrapping these name resolvers again, causing an exception later from a `RetryingNameResolver` safeguard that checks for double wrapping.
This removes the wrapping logic from `DnsNameResolverProvider` and has `ManagedChannelImpl` always explicitly do it

core: Apply RetryingNameResolver in ManagedChannelImpl (1.54.x backport)

---

core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/DnsNameResolverProviderTest.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/ServiceConfigErrorHandlingTest.java

Backport of #10371
Wrapping the `DnsNameResolver` in `DnsNameResolverProvider` can cause problems to external name resolvers that delegate to a `DnsResolver` already wrapped in a `RetryingNameResolver`.
`ManagedChannelImpl` would end up wrapping these name resolvers again, causing an exception later from a `RetryingNameResolver` safeguard that checks for double wrapping.
This removes the wrapping logic from `DnsNameResolverProvider` and has `ManagedChannelImpl` always explicitly do it

core: Apply RetryingNameResolver in ManagedChannelImpl (1.55.x backport)

---

core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java
core/src/test/java/io/grpc/internal/DnsNameResolverProviderTest.java
core/src/test/java/io/grpc/internal/DnsNameResolverTest.java
core/src/test/java/io/grpc/internal/ServiceConfigErrorHandlingTest.java

Backport of #10371
Wrapping the `DnsNameResolver` in `DnsNameResolverProvider` can cause problems to external name resolvers that delegate to a `DnsResolver` already wrapped in a `RetryingNameResolver`.
`ManagedChannelImpl` would end up wrapping these name resolvers again, causing an exception later from a `RetryingNameResolver` safeguard that checks for double wrapping.
This removes the wrapping logic from `DnsNameResolverProvider` and has `ManagedChannelImpl` always explicitly do it

core: Apply RetryingNameResolver in ManagedChannelImpl (1.56.x backport)

---

xds/src/main/java/io/grpc/xds/WeightedRoundRobinLoadBalancer.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

#10366 details a bug with the new implementation of the weighted round robin earliest deadline first scheduler, StaticStrideScheduler.
This bug was fixed by properly scaling the mean weight in the edge case where all subchannel weights are invalid and making sure they have correct casting and rounding logic. An assert statement was added to check for cases with many passthroughs and test cases were also made to be more strict to better verify behavior.

fixed StaticStrideScheduler looping too many times

---

core/src/main/java/io/grpc/internal/GrpcUtil.java
core/src/test/java/io/grpc/internal/GrpcUtilTest.java
core/src/test/java/io/grpc/internal/ManagedChannelImplBuilderTest.java
xds/src/main/java/io/grpc/xds/XdsNameResolver.java
xds/src/main/java/io/grpc/xds/XdsNameResolverProvider.java
xds/src/test/java/io/grpc/xds/XdsNameResolverProviderTest.java

Encode the service authority before passing it into gRPC util in the xDS name resolver to handle xDS requests which might contain multiple slashes. Example: xds:///path/to/service:port.
As currently the underlying Java URI library does not break the encoded authority into host/port correctly simplify the check to just look for '@' as we are only interested in checking for user info to validate the authority for HTTP.
This change also leads to few changes in unit tests that relied on this check for invalid authorities which now will be considered valid. 
Just like https://github.com/grpc/grpc-java/pull/9376, depending on Guava packages such as URLEscapers or PercentEscapers leads to internal failures(Ex: Unresolvable reference to com.google.common.escape.Escaper from …

Encode the service authority in xDSNameResolver

---

all/build.gradle

grpc-context is empty, so isn't needed. Including it also causes the warning:
```
> Task :grpc-all:javadoc
Resolution of the configuration :grpc-context:compileClasspath was attempted from a context different than the project context. Have a look at the documentation to understand why this is a problem and how it can be resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. See https://docs.gradle.org/7.6/userguide/viewing_debugging_dependencies.html#sub:resolving-unsafe-configuration-resolution-errors for more details.
```

all: Remove grpc-context from grpc-all

---

alts/src/main/java/io/grpc/alts/FailingCallCredentials.java
examples/example-jwt-auth/src/main/java/io/grpc/examples/jwtauth/JwtCredential.java

This method has been unnecessary/deprecated since dd2dc21d.

Remove unnecessary thisUsesUnstableApi from CallCredentials impls

---

api/src/main/java/io/grpc/ClientCall.java
api/src/main/java/io/grpc/PartialForwardingServerCall.java

Note: `ServerCall#setMessageCompression` was already stabilized, while its implementer PartialForwardingServerCall still had the `@ExperimentalApi` annotation (incorrectly).
Closes #1703

Stabilize setMessageCompression()

---

build.gradle

Guava 32.1.0 added Gradle Module Metadata to their artifact (they still use Maven for their build). Because of that, we're now seeing less normal dependencies that were confusing checkUpperBoundDeps.  Obviously 'null' is not the version we were looking for.
We aren't upgrading to Guava 32.1.x yet as there's still other problems.
```
Execution failed for task ':grpc-census:checkUpperBoundDeps'.
> Maven version skew: com.google.guava:guava-parent (32.1.1-jre != null) Bad version dependency path: [project ':grpc-census', com.google.guava:guava:32.1.1-android] Run './gradlew :grpc-census:dependencies --configuration runtimeClasspath' to diagnose
```

Restrict checkUpperBoundDeps to library dependencies

---

servlet/build.gradle
servlet/jakarta/build.gradle

Also convert to testFixtures, like we did elsewhere.

servlet: Remove unused dependency on grpc-util in tests

---

core/BUILD.bazel
services/build.gradle
util/build.gradle

- move the gson dependency to services from util to resolve the checkUpperBoundDeps error
- for bazel build export util instead of inprocess from core 
(this is from the trailing comments in https://github.com/grpc/grpc-java/pull/10362)

core, services, util: export util from core and move gson dep to services for the checkUpperBoundDeps error

---

rls/src/main/java/io/grpc/rls/RlsProtoConverters.java
rls/src/test/java/io/grpc/rls/RlsProtoConvertersTest.java

Change the default for staleAge to be maxAge - 1 minute rather than maxAge (unless maxAge is < 2 minutes) for the RLS configuration from proto.  This allows for the stale logic to process updates so that in a steady state system the expiration shouldn't ever be encountered.
Fixes b/290931431

Change the default for staleAge to be maxAge - 1 minute

---

core/src/testFixtures/java/io/grpc/internal/AbstractTransportTest.java
netty/src/main/java/io/grpc/netty/NettyServerHandler.java
netty/src/test/java/io/grpc/netty/NettyServerHandlerTest.java
rls/src/main/java/io/grpc/rls/RlsProtoConverters.java
xds/src/test/java/io/grpc/xds/WeightedRoundRobinLoadBalancerTest.java

We catch a number of errors in onHeadersRead where we return an error to the caller and then return without completing any more logic.  When endStream is true, onDataRead which is dependent on values set at the end of the onHeadersRead method which was leading to NPEs.
Fixes #10364

Handle header with errors and endStream = true
